Fix error reading Component.__NEXT_SPR in packages/next/client/index.js
vercel/next.js pull request #10037
Opened 2020-01-10 18:25 UTC by tomas-c

Closes #10036

2020-01-10 18:32 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +55ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 3.07 kB | 3.07 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__NEXT_SPR && location.search)
+                  (Component && Component.__NEXT_SPR && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__NEXT_SPR && location.search)
+            (Component && Component.__NEXT_SPR && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      href="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-6c834265eb8485e95adc.js"
+      src="/_next/static/runtime/main-858e1e5b8678aa5d26c6.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-a331dd089ba7487bc805.module.js"
+      src="/_next/static/runtime/main-0bcb847ac444c3ba095b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.6s | ⚠️ +56ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><s [...]

2020-01-10 19:01 UTC, timneutkens commented on packages/next/client/index.js
> +      (Component && Component.__NEXT_SPR && location.search)
```suggestion
      (Component?.__NEXT_SPR && location.search)
```

2020-01-10 19:45 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.2s | 363ms | -11.8s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.7 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.4 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | N/A | N/A |
| link.html gzip | 1.03 kB | N/A | N/A |
| withRouter.html gzip | 1.02 kB | N/A | N/A |
| Overall change | 3.07 kB | 0 B | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..16.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..92a927903.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>commons.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..26.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..ba6a65095.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
deleted
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.7s | 407ms | -12.3s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.7 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.4 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></ [...]

2020-01-10 20:53 UTC, Timer requested changes
This change doesn't make sense to me – Component should always be defined. Let's make sure we understand problem first.

2020-01-14 19:00 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 344ms | -11.3s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.5 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | N/A | N/A |
| Overall change | 4.76 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | N/A | N/A |
| _error.js gzip | 4.07 kB | N/A | N/A |
| hooks.js gzip | 779 B | N/A | N/A |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.9 kB | N/A | N/A |
| routerDirect.js gzip | 283 B | N/A | N/A |
| withRouter.js gzip | 282 B | N/A | N/A |
| Overall change | 9.87 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | N/A | N/A |
| _error.module.js gzip | 3.06 kB | N/A | N/A |
| hooks.module.js gzip | 371 B | N/A | N/A |
| index.module.js gzip | 212 B | N/A | N/A |
| link.module.js gzip | 2.47 kB | N/A | N/A |
| routerDirect..dule.js gzip | 273 B | N/A | N/A |
| withRouter.m..dule.js gzip | 272 B | N/A | N/A |
| Overall change | 7.41 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | N/A | N/A |
| _buildManife..dule.js gzip | 61 B | N/A | N/A |
| Overall change | 122 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | N/A | N/A |
| link.html gzip | 1.03 kB | N/A | N/A |
| withRouter.html gzip | 1.02 kB | N/A | N/A |
| Overall change | 3.06 kB | 0 B | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..16.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>4952ddcd88e7..92a927903.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>commons.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..26.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..ba6a65095.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>framework.HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>webpack-HASH.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
deleted
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.2s | 355ms | -11.8s |
| nodeModulesSize | 49 MB | 48.9 MB | -87.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | N/A | N/A |
| webpack-HASH.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | N/A | N/A |
| commons.HASH.js gzip | 4.06 kB | N/A | N/A |
| de003c3a9d30..9881.js gzip | 13.7 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 67.5 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | N/A | N/A |
| webpack-HASH..dule.js gzip | 746 B | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | N/A | N/A |
| Overall change | 62.1 kB | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></ [...]

2020-01-14 19:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +49ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__NEXT_SPR && location.search)
+                  (Component && Component.__NEXT_SPR && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__NEXT_SPR && location.search)
+            (Component && Component.__NEXT_SPR && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      href="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-24e04d939f54ee455844.js"
+      src="/_next/static/runtime/main-8397b6ff07e28f7d8f3b.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-c26b641603395ec31912.module.js"
+      src="/_next/static/runtime/main-5f72831cf35898f87caf.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.4s | ⚠️ +195ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Cli [...]

2020-01-14 19:32 UTC, Timer approved these changes
Thanks!

2020-01-14 19:51 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.1s | ⚠️ +192ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__N_SSG && location.search)
+                  (Component && Component.__N_SSG && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__N_SSG && location.search)
+            (Component && Component.__N_SSG && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.8s | ⚠️ +443ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpac [...]

2020-01-14 20:01 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -109ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.18 kB | 4.18 kB | ⚠️ +3 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ✓ |
| withRouter.html gzip | 1.02 kB | 1.01 kB | -1 B |
| Overall change | 3.07 kB | 3.06 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -475,7 +475,7 @@
                   (data.nextExport &&
                     ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                       location.search)) ||
-                  (Component.__N_SSG && location.search)
+                  (Component && Component.__N_SSG && location.search)
                 ) {
                   // update query on mount for exported pages
                   router.replace(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -359,7 +359,7 @@
             (data.nextExport &&
               ((0, _isDynamic.isDynamicRoute)(router.pathname) ||
                 location.search)) ||
-            (Component.__N_SSG && location.search)
+            (Component && Component.__N_SSG && location.search)
           ) {
             // update query on mount for exported pages
             router.replace(
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      href="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-958c0bb4c1297de8088f.js"
+      src="/_next/static/runtime/main-4dc7ee942236d9bde769.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-d00e2d63c88a481156d8.module.js"
+      src="/_next/static/runtime/main-3f6998fe5b4d88671b6b.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.4s | ⚠️ +127ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | tomas-c/next.js issue-10036 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ⚠️ +3 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..e54b.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | ⚠️ +3 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack,  [...]

2020-01-14 20:06 UTC, merged