Make sure to not duplicate exports with exportTrailingSlash
vercel/next.js pull request #11011
Opened 2020-03-12 19:53 UTC by ijjk

This makes sure we don't duplicate the `/` route or any others while exporting with `exportTrailingSlash` enabled. We do still output `404.html` with `exportTrailingSlash` enabled in case anyone was relying on this file being present.

Fixes: https://github.com/zeit/next.js/issues/11008

2020-03-12 19:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 7.5s | 7.8s | ⚠️ +332ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +295 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..cfaa.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 914 B | 914 B | ✓ |
| link.html gzip | 922 B | 922 B | ✓ |
| withRouter.html gzip | 910 B | 910 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 8.2s | 8.1s | -136ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +295 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..cfaa.js gzip | 9.77 kB | 9.77 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 293 kB | ⚠️ +312 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 954 B | 954 B | ✓ |
| index.js gzip | 293 kB | 293 kB | -246 B |
| link.js gzip | 300 kB | 301 kB | ⚠️ +633 B |
| routerDirect.js gzip | 299 kB | 299 kB | ⚠️ +19 B |
| withRouter.js gzip | 300 kB | 300 kB | -2 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +716 B |

</details>

</details>

2020-03-13 03:52 UTC, Timer requested changes
I don't think we should dedupe like the example for this fix.

If you inspect `build-manifest.json` and `pages-manifest.json` you'll see we're for some reason duplicating the index page:

```json
{
  "pages": {
    "/": [
      "static/runtime/webpack-b65cab0b00afd201cbda.js",
      "static/chunks/framework.ce12e34a742da81a373d.js",
      "static/chunks/4522ebda9405b36fb7d55a026e4d359d68f65d3d.faed0dea3e4112f5e8e4.js",
      "static/runtime/main-4b8fd022073eefeb3fc7.js"
    ],
    "/_app": [
      "static/runtime/webpack-b65cab0b00afd201cbda.js",
      "static/chunks/framework.ce12e34a742da81a373d.js",
      "static/chunks/4522ebda9405b36fb7d55a026e4d359d68f65d3d.faed0dea3e4112f5e8e4.js",
      "static/runtime/main-4b8fd022073eefeb3fc7.js"
    ],
    "/_error": [
      "static/runtime/webpack-b65cab0b00afd201cbda.js",
      "static/chunks/framework.ce12e34a742da81a373d.js",
      "static/runtime/main-4b8fd022073eefeb3fc7.js"
    ],
    "/_polyfills": [
      "static/runtime/polyfills-004902dd81db5da28570.js"
    ],
    "/index": [
      "static/runtime/webpack-b65cab0b00afd201cbda.js",
      "static/chunks/framework.ce12e34a742da81a373d.js",
      "static/chunks/4522ebda9405b36fb7d55a026e4d359d68f65d3d.faed0dea3e4112f5e8e4.js",
      "static/runtime/main-4b8fd022073eefeb3fc7.js"
    ]
  }
}
```

```json
{
  "/_app": "static/eEz3ZnrR27rbzQutJeopc/pages/_app.js",
  "/_document": "static/eEz3ZnrR27rbzQutJeopc/pages/_document.js",
  "/_error": "static/eEz3ZnrR27rbzQutJeopc/pages/_error.js",
  "/index": "static/eEz3ZnrR27rbzQutJeopc/pages/index.html",
  "/": "static/eEz3ZnrR27rbzQutJeopc/pages/index.html"
}
```

Can we fix these 2 files instead?

2020-03-13 19:33 UTC, ijjk commented
@Timer it seems we're duplicating these entries explicitly so not sure if it's for backwards compatibility or not 🤔 

https://github.com/zeit/next.js/blob/b596c2167d715a0e5f91b530d19367c7e3c4046e/packages/next/build/webpack/plugins/build-manifest-plugin.ts#L130

https://github.com/zeit/next.js/blob/b596c2167d715a0e5f91b530d19367c7e3c4046e/packages/next/build/webpack/plugins/pages-manifest-plugin.ts#L48

2020-03-13 19:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 8.6s | 8.5s | -89ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +295 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 916 B | 916 B | ✓ |
| link.html gzip | 925 B | 925 B | ✓ |
| withRouter.html gzip | 913 B | 913 B | ✓ |
| Overall change | 2.75 kB | 2.75 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 9.4s | 8.8s | -580ms |
| nodeModulesSize | 56.6 MB | 56.6 MB | ⚠️ +295 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.77 kB | 5.77 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..8eb0.js gzip | 9.78 kB | 9.78 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 55.4 kB | 55.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.78 kB | 4.78 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.09 kB | 1.09 kB | ✓ |
| _error.js gzip | 2.96 kB | 2.96 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 1.89 kB | 1.89 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.38 kB | 7.38 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.06 kB | 2.06 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.26 kB | 5.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 293 kB | -58 B |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 957 B | 957 B | ✓ |
| index.js gzip | 293 kB | 293 kB | -510 B |
| link.js gzip | 301 kB | 301 kB | ⚠️ +267 B |
| routerDirect.js gzip | 300 kB | 300 kB | -203 B |
| withRouter.js gzip | 300 kB | 300 kB | ⚠️ +21 B |
| Overall change | 1.49 MB | 1.49 MB | -483 B |

</details>

</details>

2020-05-23 20:34 UTC, Timer submitted a review, later dismissed
LGTM!

2020-05-23 20:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.8s | ⚠️ +438ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.013 | 2.077 | ⚠️ +0.06 |
| / avg req/sec | 1242.09 | 1203.61 | -38.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.166 | 1.139 | -0.03 |
| /error-in-render avg req/sec | 2144.63 | 2195.57 | ⚠️ +50.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 928 B | 928 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.5s | ⚠️ +263ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-23 20:46 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.9s | ⚠️ +131ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.002 | 2.019 | ⚠️ +0.02 |
| / avg req/sec | 1248.77 | 1237.97 | -10.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.138 | 1.143 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2195.91 | 2187.36 | -8.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.7s | ⚠️ +23ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-23 20:47 UTC, ijjk commented
## Failing test suites <!--711638516-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > production mode > should handle / correctly
- Route indexes handling > production mode > should handle /index correctly
- Route indexes handling > production mode > should handle /index/index correctly
- Route indexes handling > production mode > should handle /nested-index correctly
- Route indexes handling > production mode > should handle /nested-index/index correctly
- Route indexes handling > production mode > should handle /nested-index/index/index correctly
- Route indexes handling > production mode > should handle /sub correctly
- Route indexes handling > production mode > should handle /sub/index correctly
- Route indexes handling > production mode > should handle /sub/index/index correctly
- Route indexes handling > production mode > should handle /sub/another correctly
- Route indexes handling > production mode > should handle /sub/another/index correctly
- Route indexes handling > production mode > should handle /api/sub correctly
- Route indexes handling > production mode > should handle /api/sub/index correctly
- Route indexes handling > production mode > should handle /api/sub/index/index correctly
- Route indexes handling > production mode > should handle /api/sub/another correctly
- Route indexes handling > production mode > should handle /api/sub/another/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › production mode › should handle / correctly

    FetchError: request to http://localhost:46845/ failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index correctly

    FetchError: request to http://localhost:46845/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index/index correctly

    FetchError: request to http://localhost:46845/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index correctly

    FetchError: request to http://localhost:46845/nested-index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index correctly

    FetchError: request to http://localhost:46845/nested-index/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index/index correctly

    FetchError: request to http://localhost:46845/nested-index/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub correctly

    FetchError: request to http://localhost:46845/sub failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index correctly

    FetchError: request to http://localhost:46845/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index/index correctly

    FetchError: request to http://localhost:46845/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another correctly

    FetchError: request to http://localhost:46845/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another/index correctly

    FetchError: request to http://localhost:46845/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub correctly

    FetchError: request to http://localhost:46845/api/sub failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index correctly

    FetchError: request to http://localhost:46845/api/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index/index correctly

    FetchError: request to http://localhost:46845/api/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another correctly

    FetchError: request to http://localhost:46845/api/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another/index correctly

    FetchError: request to http://localhost:46845/api/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:46845

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      263 | export async function killApp(instance) {
      264 |   await new Promise((resolve, reject) => {
    > 265 |     treeKill(instance.pid, (err) => {
          |                       ^
      266 |       if (err) {
      267 |         if (
      268 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:265:23
      at killApp (lib/next-test-utils.js:264:9)
      at integration/route-indexes/test/index.test.js:134:20

</details>

2020-05-23 20:51 UTC, ijjk commented
## Failing test suites <!--711641833-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > production mode > should handle / correctly
- Route indexes handling > production mode > should handle /index correctly
- Route indexes handling > production mode > should handle /index/index correctly
- Route indexes handling > production mode > should handle /nested-index correctly
- Route indexes handling > production mode > should handle /nested-index/index correctly
- Route indexes handling > production mode > should handle /nested-index/index/index correctly
- Route indexes handling > production mode > should handle /sub correctly
- Route indexes handling > production mode > should handle /sub/index correctly
- Route indexes handling > production mode > should handle /sub/index/index correctly
- Route indexes handling > production mode > should handle /sub/another correctly
- Route indexes handling > production mode > should handle /sub/another/index correctly
- Route indexes handling > production mode > should handle /api/sub correctly
- Route indexes handling > production mode > should handle /api/sub/index correctly
- Route indexes handling > production mode > should handle /api/sub/index/index correctly
- Route indexes handling > production mode > should handle /api/sub/another correctly
- Route indexes handling > production mode > should handle /api/sub/another/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › production mode › should handle / correctly

    FetchError: request to http://localhost:44639/ failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index correctly

    FetchError: request to http://localhost:44639/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index/index correctly

    FetchError: request to http://localhost:44639/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index correctly

    FetchError: request to http://localhost:44639/nested-index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index correctly

    FetchError: request to http://localhost:44639/nested-index/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index/index correctly

    FetchError: request to http://localhost:44639/nested-index/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub correctly

    FetchError: request to http://localhost:44639/sub failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index correctly

    FetchError: request to http://localhost:44639/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index/index correctly

    FetchError: request to http://localhost:44639/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another correctly

    FetchError: request to http://localhost:44639/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another/index correctly

    FetchError: request to http://localhost:44639/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub correctly

    FetchError: request to http://localhost:44639/api/sub failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index correctly

    FetchError: request to http://localhost:44639/api/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index/index correctly

    FetchError: request to http://localhost:44639/api/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another correctly

    FetchError: request to http://localhost:44639/api/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another/index correctly

    FetchError: request to http://localhost:44639/api/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:44639

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      263 | export async function killApp(instance) {
      264 |   await new Promise((resolve, reject) => {
    > 265 |     treeKill(instance.pid, (err) => {
          |                       ^
      266 |       if (err) {
      267 |         if (
      268 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:265:23
      at killApp (lib/next-test-utils.js:264:9)
      at integration/route-indexes/test/index.test.js:134:20

</details>

2020-05-23 21:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 9.4s | 9.2s | -113ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.578 | 1.689 | ⚠️ +0.11 |
| / avg req/sec | 1584.76 | 1479.92 | -104.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.906 | 0.94 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2760.42 | 2660.18 | -100.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 9.9s | 9.8s | -114ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-23 21:35 UTC, ijjk commented
## Failing test suites <!--711705366-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > production mode > should handle / correctly
- Route indexes handling > production mode > should handle /index correctly
- Route indexes handling > production mode > should handle /index/index correctly
- Route indexes handling > production mode > should handle /nested-index correctly
- Route indexes handling > production mode > should handle /nested-index/index correctly
- Route indexes handling > production mode > should handle /nested-index/index/index correctly
- Route indexes handling > production mode > should handle /sub correctly
- Route indexes handling > production mode > should handle /sub/index correctly
- Route indexes handling > production mode > should handle /sub/index/index correctly
- Route indexes handling > production mode > should handle /sub/another correctly
- Route indexes handling > production mode > should handle /sub/another/index correctly
- Route indexes handling > production mode > should handle /api/sub correctly
- Route indexes handling > production mode > should handle /api/sub/index correctly
- Route indexes handling > production mode > should handle /api/sub/index/index correctly
- Route indexes handling > production mode > should handle /api/sub/another correctly
- Route indexes handling > production mode > should handle /api/sub/another/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › production mode › should handle / correctly

    FetchError: request to http://localhost:34571/ failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index correctly

    FetchError: request to http://localhost:34571/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index/index correctly

    FetchError: request to http://localhost:34571/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index correctly

    FetchError: request to http://localhost:34571/nested-index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index correctly

    FetchError: request to http://localhost:34571/nested-index/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index/index correctly

    FetchError: request to http://localhost:34571/nested-index/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub correctly

    FetchError: request to http://localhost:34571/sub failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index correctly

    FetchError: request to http://localhost:34571/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index/index correctly

    FetchError: request to http://localhost:34571/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another correctly

    FetchError: request to http://localhost:34571/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another/index correctly

    FetchError: request to http://localhost:34571/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub correctly

    FetchError: request to http://localhost:34571/api/sub failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index correctly

    FetchError: request to http://localhost:34571/api/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index/index correctly

    FetchError: request to http://localhost:34571/api/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another correctly

    FetchError: request to http://localhost:34571/api/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another/index correctly

    FetchError: request to http://localhost:34571/api/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:34571

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      263 | export async function killApp(instance) {
      264 |   await new Promise((resolve, reject) => {
    > 265 |     treeKill(instance.pid, (err) => {
          |                       ^
      266 |       if (err) {
      267 |         if (
      268 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:265:23
      at killApp (lib/next-test-utils.js:264:9)
      at integration/route-indexes/test/index.test.js:134:20

</details>

2020-05-24 01:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.8s | ⚠️ +222ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.19 | 2.26 | ⚠️ +0.07 |
| / avg req/sec | 1141.48 | 1106.13 | -35.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.411 | 1.392 | -0.02 |
| /error-in-render avg req/sec | 1771.92 | 1796.34 | ⚠️ +24.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 926 B | 926 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -154ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-24 01:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | -62ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.094 | 2.057 | -0.04 |
| / avg req/sec | 1193.93 | 1215.22 | ⚠️ +21.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.171 | 1.149 | -0.02 |
| /error-in-render avg req/sec | 2135.08 | 2175.27 | ⚠️ +40.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 926 B | 926 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +11ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-24 01:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.6s | ⚠️ +17ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.456 | 2.394 | -0.06 |
| / avg req/sec | 1018.09 | 1044.29 | ⚠️ +26.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.478 | 1.488 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1691.43 | 1679.67 | -11.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 926 B | 926 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 923 B | 923 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.3s | -57ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +445 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.66 kB | 5.66 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-24 01:43 UTC, ijjk commented
## Failing test suites <!--712014901-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > production mode > should handle / correctly
- Route indexes handling > production mode > should handle /index correctly
- Route indexes handling > production mode > should handle /index/index correctly
- Route indexes handling > production mode > should handle /nested-index correctly
- Route indexes handling > production mode > should handle /nested-index/index correctly
- Route indexes handling > production mode > should handle /nested-index/index/index correctly
- Route indexes handling > production mode > should handle /sub correctly
- Route indexes handling > production mode > should handle /sub/index correctly
- Route indexes handling > production mode > should handle /sub/index/index correctly
- Route indexes handling > production mode > should handle /sub/another correctly
- Route indexes handling > production mode > should handle /sub/another/index correctly
- Route indexes handling > production mode > should handle /api/sub correctly
- Route indexes handling > production mode > should handle /api/sub/index correctly
- Route indexes handling > production mode > should handle /api/sub/index/index correctly
- Route indexes handling > production mode > should handle /api/sub/another correctly
- Route indexes handling > production mode > should handle /api/sub/another/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › production mode › should handle / correctly

    FetchError: request to http://localhost:37769/ failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index correctly

    FetchError: request to http://localhost:37769/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index/index correctly

    FetchError: request to http://localhost:37769/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index correctly

    FetchError: request to http://localhost:37769/nested-index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index correctly

    FetchError: request to http://localhost:37769/nested-index/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index/index correctly

    FetchError: request to http://localhost:37769/nested-index/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub correctly

    FetchError: request to http://localhost:37769/sub failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index correctly

    FetchError: request to http://localhost:37769/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index/index correctly

    FetchError: request to http://localhost:37769/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another correctly

    FetchError: request to http://localhost:37769/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another/index correctly

    FetchError: request to http://localhost:37769/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub correctly

    FetchError: request to http://localhost:37769/api/sub failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index correctly

    FetchError: request to http://localhost:37769/api/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index/index correctly

    FetchError: request to http://localhost:37769/api/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another correctly

    FetchError: request to http://localhost:37769/api/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another/index correctly

    FetchError: request to http://localhost:37769/api/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:37769

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      263 | export async function killApp(instance) {
      264 |   await new Promise((resolve, reject) => {
    > 265 |     treeKill(instance.pid, (err) => {
          |                       ^
      266 |       if (err) {
      267 |         if (
      268 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:265:23
      at killApp (lib/next-test-utils.js:264:9)
      at integration/route-indexes/test/index.test.js:134:20

</details>

2020-05-24 01:46 UTC, ijjk commented
## Failing test suites <!--712018283-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > production mode > should handle / correctly
- Route indexes handling > production mode > should handle /index correctly
- Route indexes handling > production mode > should handle /index/index correctly
- Route indexes handling > production mode > should handle /nested-index correctly
- Route indexes handling > production mode > should handle /nested-index/index correctly
- Route indexes handling > production mode > should handle /nested-index/index/index correctly
- Route indexes handling > production mode > should handle /sub correctly
- Route indexes handling > production mode > should handle /sub/index correctly
- Route indexes handling > production mode > should handle /sub/index/index correctly
- Route indexes handling > production mode > should handle /sub/another correctly
- Route indexes handling > production mode > should handle /sub/another/index correctly
- Route indexes handling > production mode > should handle /api/sub correctly
- Route indexes handling > production mode > should handle /api/sub/index correctly
- Route indexes handling > production mode > should handle /api/sub/index/index correctly
- Route indexes handling > production mode > should handle /api/sub/another correctly
- Route indexes handling > production mode > should handle /api/sub/another/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › production mode › should handle / correctly

    FetchError: request to http://localhost:38681/ failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index correctly

    FetchError: request to http://localhost:38681/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /index/index correctly

    FetchError: request to http://localhost:38681/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index correctly

    FetchError: request to http://localhost:38681/nested-index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index correctly

    FetchError: request to http://localhost:38681/nested-index/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /nested-index/index/index correctly

    FetchError: request to http://localhost:38681/nested-index/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub correctly

    FetchError: request to http://localhost:38681/sub failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index correctly

    FetchError: request to http://localhost:38681/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/index/index correctly

    FetchError: request to http://localhost:38681/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another correctly

    FetchError: request to http://localhost:38681/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /sub/another/index correctly

    FetchError: request to http://localhost:38681/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub correctly

    FetchError: request to http://localhost:38681/api/sub failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index correctly

    FetchError: request to http://localhost:38681/api/sub/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/index/index correctly

    FetchError: request to http://localhost:38681/api/sub/index/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another correctly

    FetchError: request to http://localhost:38681/api/sub/another failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)

  ● Route indexes handling › production mode › should handle /api/sub/another/index correctly

    FetchError: request to http://localhost:38681/api/sub/another/index failed, reason: connect ECONNREFUSED 127.0.0.1:38681

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1455:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      263 | export async function killApp(instance) {
      264 |   await new Promise((resolve, reject) => {
    > 265 |     treeKill(instance.pid, (err) => {
          |                       ^
      266 |       if (err) {
      267 |         if (
      268 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:265:23
      at killApp (lib/next-test-utils.js:264:9)
      at integration/route-indexes/test/index.test.js:134:20

</details>

2020-05-26 17:11 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.2s | -323ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ⚠️ +449 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.33 | 2.559 | ⚠️ +0.23 |
| / avg req/sec | 1072.93 | 976.85 | -96.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.378 | 1.428 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1813.97 | 1750.73 | -63.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 14.1s | 13.6s | -517ms |
| nodeModulesSize | 66.4 MB | 66.4 MB | ⚠️ +449 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 844 kB | 844 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 844 kB | 844 kB | ✓ |
| link.js | 882 kB | 882 kB | ✓ |
| routerDirect.js | 874 kB | 874 kB | ✓ |
| withRouter.js | 874 kB | 874 kB | ✓ |
| Overall change | 4.33 MB | 4.33 MB | ✓ |

</details>

</details>

2020-05-27 05:00 UTC, Timer approved these changes

2020-05-27 05:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.9s | ⚠️ +189ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +449 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.857 | 1.866 | ⚠️ +0.01 |
| / avg req/sec | 1346.2 | 1339.7 | -6.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.259 | 1.17 | -0.09 |
| /error-in-render avg req/sec | 1986.17 | 2135.91 | ⚠️ +149.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 936 B | 936 B | ✓ |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.1s | -748ms |
| nodeModulesSize | 67.3 MB | 67.3 MB | ⚠️ +449 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c03c.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js fix/duplicate-exports | Change |
| - | - | - | - |
| _error.js | 876 kB | 876 kB | ✓ |
| 404.html | 4.18 kB | 4.18 kB | ✓ |
| hooks.html | 3.81 kB | 3.81 kB | ✓ |
| index.js | 877 kB | 877 kB | ✓ |
| link.js | 914 kB | 914 kB | ✓ |
| routerDirect.js | 907 kB | 907 kB | ✓ |
| withRouter.js | 907 kB | 907 kB | ✓ |
| Overall change | 4.49 MB | 4.49 MB | ✓ |

</details>

</details>

2020-05-27 05:48 UTC, merged