add(examples): with-indent
vercel/next.js pull request #11207
Opened 2020-03-19 23:19 UTC by fouad

2020-03-20 09:12 UTC, timneutkens commented
Seems that the library has gotten quite large 🤔 https://bundlephobia.com/result?p=@indent/audit@0.0.20

2020-03-20 18:23 UTC, fouad commented
Thanks for pointing that out! Fixed in `v0.0.21` https://bundlephobia.com/result?p=@indent/audit@0.0.21

2020-03-21 16:21 UTC, timneutkens requested changes
Could you update the readme? We changed the structure a bit

2020-03-31 00:04 UTC, fouad commented
@timneutkens yup, done!

2020-03-31 20:15 UTC, lfades commented on examples/with-indent/pages/find.js
> +      event: 'server_side_event',
If you want to showcase server side events let's use API Routes, but not an empty `getInitialProps` like in this case.

2020-03-31 20:16 UTC, lfades commented on examples/with-indent/pages/find.js
> +export default class extends Component {
Let's do a functional component with Hooks here.

2020-03-31 20:21 UTC, lfades commented on examples/with-indent/pages/index.js
> +import React from 'react'
Remove all react imports unless `React` is explicitly used.

2020-03-31 20:24 UTC, lfades commented on examples/with-indent/pages/_app.js
> +  dsn: '{{INDENT_INPUT_DSN}}',
If this variable is required for the example to work properly, add a `now.json` that requires it as a secret, so when trying to deploy using the deployment button in the example, ZEIT Now will ask for the secret before making the deployment.

2020-03-31 20:25 UTC, lfades commented on examples/with-indent/README.md
> +Follow the [Indent Quickstart](https://indent.com/docs/quickstart) for step by step instructions.
```suggestion
```

2020-03-31 20:26 UTC, lfades commented on examples/with-indent/README.md
> +
```suggestion

This example shows how to use [Next.js](https://github.com/zeit/next.js) with [Indent](https://indent.com/?ref=nextjs).

Follow the [Indent Quickstart](https://indent.com/docs/quickstart) for step by step instructions.

```

2020-03-31 20:29 UTC, lfades commented on examples/with-indent/README.md
> +Follow the [Indent Quickstart](https://indent.com/docs/quickstart) for step by step instructions.
```suggestion
```

2020-03-31 20:31 UTC, lfades requested changes
Requested some changes in my suggestions, also please run the linter over the files :pray:

2020-05-22 08:42 UTC, timneutkens commented
Hey @fouad could you update the PR 🙏 Then we'll re-open

2020-05-22 08:42 UTC, closed without merging