Don't override tsconfig.json with required changes
vercel/next.js pull request #11440
Opened 2020-03-28 19:25 UTC by rovansteen

This attempts to resolve #8128 as per @Timer's comment https://github.com/zeit/next.js/pull/9119#issuecomment-543487461.

Rather than updating `tsconfig.json` with the required fields, it will ask the user to update the file with the mentioned changes.

I am not sure what to do about the suggestions yet. Do we want to keep them and mention them to the user in the console every time if they are undefined?

2020-03-28 19:31 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.2s | -20ms |
| nodeModulesSize | 52.8 MB | 52.8 MB | ⚠️ +172 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.2 kB | 56.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.77 kB | 4.77 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| index.html gzip | 917 B | 917 B | ✓ |
| link.html gzip | 925 B | 925 B | ✓ |
| withRouter.html gzip | 915 B | 915 B | ✓ |
| Overall change | 2.76 kB | 2.76 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.3s | ⚠️ +207ms |
| nodeModulesSize | 52.8 MB | 52.8 MB | ⚠️ +172 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | 10.1 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.2 kB | 56.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.77 kB | 4.77 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | rovansteen/next.js patch/8128 | Change |
| - | - | - | - |
| _error.js gzip | 293 kB | 294 kB | ⚠️ +1.27 kB |
| 404.html gzip | 1.32 kB | 1.32 kB | ✓ |
| hooks.html gzip | 958 B | 958 B | ✓ |
| index.js gzip | 294 kB | 294 kB | ⚠️ +699 B |
| link.js gzip | 302 kB | 302 kB | ⚠️ +7 B |
| routerDirect.js gzip | 300 kB | 300 kB | -150 B |
| withRouter.js gzip | 300 kB | 300 kB | -887 B |
| Overall change | 1.49 MB | 1.49 MB | ⚠️ +942 B |

</details>

</details>

2020-03-30 15:27 UTC, Timer requested changes
We should prompt interactively if the user wants us to update for them.

If they answer no, that's when we should `process.exit(1)`.

2020-04-02 22:28 UTC, lalau commented
> We should prompt interactively if the user wants us to update for them.
> 
> If they answer no, that's when we should `process.exit(1)`.

Can we have it only ask once or have a config in next.config.js to not ask at all? I doubt one would change his mind after selecting want it or not want it. And if they want it later, they can always look it up in the doc to get the values.

2020-04-02 22:31 UTC, ajcrews commented
Agreed with @lalau. @Timer I also have concerns with the suggested approach. This means we will be prompted every time we are running our nodejs app and libraries that use nextjs. Instead, a warning could be printed indicating that the recommended tsconfig is not being used and can provide instructions on how to opt-in.

2020-04-03 07:44 UTC, timneutkens commented
Problem is that if you do not configure the needed values the type checking or compilation will crash all the time as the configuration is needed to mirror Babel's TS compilation with the TS compiler that does type checking.

2020-04-03 15:52 UTC, ajcrews commented
@timneutkens @Timer how would you feel about the following approach. The user would be prompted only when Next.js determines that the tsconfig does not have all recommended settings:

Would you like Next.js to modify your tsconfig with recommended settings?
1. Yes
2. No

If a user selects No, Next.js will write to `next.config.js` with a setting that prevents the prompt from happening in future. We could warn the user on each run that they have chosen to opt-out of required tsconfig settings and instruct them how to opt back in if needed.

2020-04-04 22:13 UTC, rovansteen commented
What is the point of opting out of *required* settings? Like @timneutkens said, next.js will not work properly without these required settings so I think we should not give the user the choice to not do it. What I am trying to do with this PR is to give the user the option to do it themselves to preserve comments/syntax.

2020-04-05 01:24 UTC, ajcrews commented
@rovansteen not all of the settings are required for Next.js to operate depending on the use case. My team uses Next.js in our nodejs libraries so we can develop components in isolation but also mimic our Next.js application environment. In these nodejs libs we need to be able to control the `noEmit` property in the tsconfig.

2020-04-05 08:33 UTC, rovansteen commented
@ajcrews I understand, but that's a different discussion. This is about not overriding an existing `tsconfig.json`

2020-04-05 18:50 UTC, ajcrews commented
@rovansteen for the record I'm on board with your current approach to stop overriding an existing `tsconfig.json`, warn the user and display the required/recommended settings. 

The other discussion is coming from @Timer's suggestion for the user prompt. It's less than ideal to be prompted every time we run Next.js when an existing `tsconfig.json` works just fine. What settings are "required" differs based on the context. In the case of a nodejs lib that uses Next.js for development purposes, we need  to set `noEmit: false` when we build the lib. Assuming we go this route and the user does get prompted, the idea of "opting out" is really about opting out of being prompted every time we run Next.js.

I hope that makes sense and do appreciate your time. Thanks!

2020-04-05 19:44 UTC, lalau commented
I think there is a disconnect here. Next js alter tsconfig.json for running the server. I understand that it needs to change some values in tsconfig.json to be able to run the server. On the other hand, in my workflow, we uses babel to convert ts to js, then uses tsc which reads tsconfig.json to emit type definition for the ts files. This is where the issue is, next.js wants to have `noEmit: true` but my tsc step wants to emit declaration.

These are two different uses of tsconfig.json and it makes sense for them to differ. One possible workaround is to have two tsconfig.json. Next js keeps managing tsconfig.json whatever it wants to run the server. Then in the tsc step in my workflow, I specify a different tsc project file for emitting the type definition.

2020-04-06 07:29 UTC, sophistifunk commented
If Next.js insists on controlling a tsconfig file for some reason (I'm wildly assuming it's to fork and run tsc that way?), it should *absolutely not* be the root tsconfig. That file belongs to each application and its maintainers, and is often filled with settings that are only for build/edit time and should be different at runtime.

2020-04-22 13:49 UTC, eric-burel commented
Related to https://github.com/zeit/next.js/issues/8060 regarding not considering `tsconfig.json` as the Next source of truth.

2020-05-23 12:36 UTC, timneutkens commented
@rovansteen is this PR almost ready? otherwise I think it's better to close the PR so that it doesn't look like the good first issue has been resolved 👍

2020-05-23 13:49 UTC, rovansteen commented
@timneutkens I wasn’t sure which course to take with this PR as there seems to be some discussion about the best way to tackle this. Happy to continue with this if there’s a clear approach :)

2020-05-23 18:43 UTC, timneutkens commented
@rovansteen Overall the only goal of the PR is to introduce a check with the user before updating the tsconfig.json, anything else seems off-topic, so it comes down to this comment from @Timer: https://github.com/zeit/next.js/pull/11440#pullrequestreview-383971158

2020-05-27 18:46 UTC, closed without merging