fix: shallow routing never happens unless the new route is the existing route
vercel/next.js pull request #11453
Opened 2020-03-29 03:49 UTC by samschooler

I'm not sure this is a bug, or a feature, so please tell me if I'm wrong. 

Right now the logic for returning a cached route is:
```
shallow && cachedRouteInfo && this.route === route
```
However, this means this will only returned the `cachedRouteInfo` if the route is current page.

In this PR I changed the logic to:
```
cachedRouteInfo && (shallow || this.route === route)
```
This makes it so if the route is cached, and`shallow` is enabled or it is the current route, return `cachedRouteInfo`

2020-03-29 03:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.5s | ⚠️ +304ms |
| nodeModulesSize | 52.8 MB | 52.8 MB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..66af.js gzip | N/A | 10.1 kB | N/A |
| Overall change | 56.2 kB | 56.2 kB | -1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.77 kB | 4.77 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | 6.71 kB | ⚠️ +1 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| index.html gzip | 917 B | 916 B | -1 B |
| link.html gzip | 925 B | 924 B | -1 B |
| withRouter.html gzip | 915 B | 911 B | -4 B |
| Overall change | 2.76 kB | 2.75 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -1 +1 @@
-<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/link.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d8f88b74aefd825bf023.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/main-2bd6e9e56ab1a4d74c13.module.js" as="script" crossorigin="anonymous"/></head><body><div id="__next"><div><h3>A Link page!</h3><a href="/">Go to /</a></div></div><script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">{"props":{"pageProps":{}},"page":"/link","query":{},"buildId":"BUILD_ID","isFallback":false}</script><script crossorigin="anonymous" nomodule="">!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script><script crossorigin="anonymous" nomodule="" src="/_next/static/runtime/polyfills-1d4fa480fe12c18ddc5f.js"></script><script async="" data-next-page="/link" src="/_next/static/BUILD_ID/pages/link.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/link" src="/_next/static/BUILD_ID/pages/link.module.js" crossorigin="anonymous" type="module"></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.module.js" crossorigin="anonymous" type="module"></script><script src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d70844b46f3177e37fca.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d8f88b74aefd825bf023.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/runtime/main-496c627e4cae2c2e76d4.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/runtime/main-2bd6e9e56ab1a4d74c13.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/BUILD_ID/_buildManifest.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/BUILD_ID/_buildManifest.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/BUILD_ID/_ssgManifest.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/BUILD_ID/_ssgManifest.module.js" async="" crossorigin="anonymous" type="module"></script></body></html>
\ No newline at end of file
+<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/link.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.15fd7d356d224838760d.module.js" as= [...]

2020-03-29 04:00 UTC, ijjk commented
## Failing test suites <!--555307095-->

**test/integration/query-with-encoding/test/index.test.js** 
- Query String with Encoding > new line > should have correct query on Router#push
- Query String with Encoding > percent > should have correct query on Router#push
- Query String with Encoding > plus > should have correct query on Router#push
- Query String with Encoding > trailing space > should have correct query on Router#push

<details>
<summary>Expand output</summary>

  ● Query String with Encoding › new line › should have correct query on Router#push

    expect(received).toBe(expected) // Object.is equality

    Expected: "{\"abc\":\"def\\n\"}"
    Received: "{}"

      53 |         await waitFor(1000)
      54 |         const text = await browser.elementByCss('#query-content').text()
    > 55 |         expect(text).toBe('{"abc":"def\\n"}')
         |                      ^
      56 |       } finally {
      57 |         await browser.close()
      58 |       }

      at Object.<anonymous> (integration/query-with-encoding/test/index.test.js:55:22)

  ● Query String with Encoding › trailing space › should have correct query on Router#push

    expect(received).toBe(expected) // Object.is equality

    Expected: "{\"abc\":\"def \"}"
    Received: "{}"

      106 |         await waitFor(1000)
      107 |         const text = await browser.elementByCss('#query-content').text()
    > 108 |         expect(text).toBe('{"abc":"def "}')
          |                      ^
      109 |       } finally {
      110 |         await browser.close()
      111 |       }

      at Object.<anonymous> (integration/query-with-encoding/test/index.test.js:108:22)

  ● Query String with Encoding › percent › should have correct query on Router#push

    expect(received).toBe(expected) // Object.is equality

    Expected: "{\"abc\":\"def%\"}"
    Received: "{}"

      159 |         await waitFor(1000)
      160 |         const text = await browser.elementByCss('#query-content').text()
    > 161 |         expect(text).toBe('{"abc":"def%"}')
          |                      ^
      162 |       } finally {
      163 |         await browser.close()
      164 |       }

      at Object.<anonymous> (integration/query-with-encoding/test/index.test.js:161:22)

  ● Query String with Encoding › plus › should have correct query on Router#push

    expect(received).toBe(expected) // Object.is equality

    Expected: "{\"abc\":\"def+\"}"
    Received: "{}"

      212 |         await waitFor(1000)
      213 |         const text = await browser.elementByCss('#query-content').text()
    > 214 |         expect(text).toBe('{"abc":"def+"}')
          |                      ^
      215 |       } finally {
      216 |         await browser.close()
      217 |       }

      at Object.<anonymous> (integration/query-with-encoding/test/index.test.js:214:22)
          at runMicrotasks (<anonymous>)

</details>

2020-03-29 05:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.9s | ⚠️ +294ms |
| nodeModulesSize | 52.8 MB | 52.8 MB | ⚠️ +53.4 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.24 kB | 6.24 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c6c1.js gzip | 10.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..007d.js gzip | N/A | 13.7 kB | N/A |
| Overall change | 56.2 kB | 59.8 kB | ⚠️ +3.55 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.77 kB | 4.77 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.71 kB | N/A | N/A |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | N/A | 10.3 kB | N/A |
| Overall change | 51.4 kB | 54.9 kB | ⚠️ +3.57 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.15 kB | 3.15 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.03 kB | 2.03 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.86 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _app.module.js gzip | 594 B | 594 B | ✓ |
| _error.module.js gzip | 2.08 kB | 2.08 kB | ✓ |
| hooks.module.js gzip | 370 B | 370 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 1.48 kB | 1.48 kB | ✓ |
| routerDirect..dule.js gzip | 271 B | 271 B | ✓ |
| withRouter.m..dule.js gzip | 270 B | 270 B | ✓ |
| Overall change | 5.28 kB | 5.28 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | samschooler/next.js fix/shallow-routing | Change |
| - | - | - | - |
| index.html gzip | 917 B | 916 B | -1 B |
| link.html gzip | 925 B | 924 B | -1 B |
| withRouter.html gzip | 915 B | 912 B | -3 B |
| Overall change | 2.76 kB | 2.75 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..23.module.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..177e37fca.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..99.module.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1 +1 @@
-<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/index.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d8f88b74aefd825bf023.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/main-2bd6e9e56ab1a4d74c13.module.js" as="script" crossorigin="anonymous"/></head><body><div id="__next">Hello world 👋</div><script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"BUILD_ID","isFallback":false}</script><script crossorigin="anonymous" nomodule="">!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script><script crossorigin="anonymous" nomodule="" src="/_next/static/runtime/polyfills-1d4fa480fe12c18ddc5f.js"></script><script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.module.js" crossorigin="anonymous" type="module"></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.module.js" crossorigin="anonymous" type="module"></script><script src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d70844b46f3177e37fca.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.d8f88b74aefd825bf023.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/runtime/main-496c627e4cae2c2e76d4.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/runtime/main-2bd6e9e56ab1a4d74c13.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/BUILD_ID/_buildManifest.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/BUILD_ID/_buildManifest.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/BUILD_ID/_ssgManifest.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/BUILD_ID/_ssgManifest.module.js" async="" crossorigin="anonymous" type="module"></script></body></html>
\ No newline at end of file
+<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/index.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link re [...]

2020-03-29 05:12 UTC, ijjk commented
## Failing test suites <!--555371058-->

**test/integration/size-limit/test/index.test.js** 
- Production response size > should not increase the overall response size of default build
- Production response size > should not increase the overall response size of modern build

<details>
<summary>Expand output</summary>

  ● Production response size › should not increase the overall response size of default build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    10942

      82 |     // These numbers are without gzip compression!
      83 |     const delta = responseSizesBytes - 257 * 1024
    > 84 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
         |                   ^
      85 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      86 |   })
      87 | 

      at Object.<anonymous> (integration/size-limit/test/index.test.js:84:19)

  ● Production response size › should not increase the overall response size of modern build

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 1024
    Received:    11060

      102 |     // These numbers are without gzip compression!
      103 |     const delta = responseSizesBytes - 165 * 1024
    > 104 |     expect(delta).toBeLessThanOrEqual(1024) // don't increase size more than 1kb
          |                   ^
      105 |     expect(delta).toBeGreaterThanOrEqual(-1024) // don't decrease size more than 1kb without updating target
      106 |   })
      107 | })

      at Object.<anonymous> (integration/size-limit/test/index.test.js:104:19)

</details>

2020-05-20 04:49 UTC, Timer requested changes
As evidenced by the test cases, this is by design and should be captured in the documentation. Thanks for the PR!

2020-05-20 04:49 UTC, closed without merging