Move focus to the beginning of body even if no tabindex -1 was set
vercel/next.js pull request #11983
Opened 2020-04-17 20:22 UTC by olpeh

From accessibility point-of-view, it is important to move focus to the beginning of the body after navigation so that screen readers notice that a navigation happened. This is also what most users of assistive technologies and keyboard users expect.

As discussed in #7681 where @timneutkens suggested making a PR out of this.

This is similar to #8493, but here we also remove the `tabindex` attribute if it did not exist in body to begin with. This is explained in the code comment.

I wonder if I should cherry-pick at least the tests from #7693?

2020-04-17 20:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.9s | ⚠️ +325ms |
| nodeModulesSize | 55.5 MB | 55.5 MB | ⚠️ +723 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.918 | 2.004 | ⚠️ +0.09 |
| / avg req/sec | 1303.56 | 1247.31 | -56.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.985 | 0.975 | -0.01 |
| /error-in-render avg req/sec | 2537.63 | 2563.68 | ⚠️ +26.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5e5e.js gzip | 10.3 kB | 10.3 kB | ✓ |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| Overall change | 56.7 kB | 56.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.79 kB | 4.79 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.1 kB | ⚠️ +46 B |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.9 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.module.js gzip | 602 B | 602 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.57 kB | ⚠️ +50 B |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.43 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -299,7 +299,24 @@ var Link = /*#__PURE__*/function (_react$Component) {
 
         if (scroll) {
           window.scrollTo(0, 0);
+          var bodyHadTabIndex = document.body.hasAttribute('tabindex');
+
+          if (!bodyHadTabIndex) {
+            // Body cannot receive focus without tab index -1
+            document.body.setAttribute('tabindex', '-1');
+          }
+
           document.body.focus();
+
+          if (!bodyHadTabIndex) {
+            // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+            // So, let's remove it since we added it there.
+            // This is important because we probably don't want to focus the body if the user clicks on some
+            // parts of the page that is not an interactive element.
+            // This is useful for click+tab interaction, where you click close to a link + tab in order
+            // to focus that link – a fast way for moving the focus exactly where you want it to be.
+            document.body.removeAttribute('tabindex');
+          }
         }
       });
     };
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -209,7 +209,24 @@ class Link extends _react.Component {
 
         if (scroll) {
           window.scrollTo(0, 0);
+          var bodyHadTabIndex = document.body.hasAttribute('tabindex');
+
+          if (!bodyHadTabIndex) {
+            // Body cannot receive focus without tab index -1
+            document.body.setAttribute('tabindex', '-1');
+          }
+
           document.body.focus();
+
+          if (!bodyHadTabIndex) {
+            // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+            // So, let's remove it since we added it there.
+            // This is important because we probably don't want to focus the body if the user clicks on some
+            // parts of the page that is not an interactive element.
+            // This is useful for click+tab interaction, where you click close to a link + tab in order
+            // to focus that link – a fast way for moving the focus exactly where you want it to be.
+            document.body.removeAttribute('tabindex');
+          }
         }
       });
     };
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +168ms |
| nodeModulesSize | 55.5 MB | 55.5 MB | ⚠️ +723 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5e5e.js gzip | 10.3 kB | 10.3 kB | ✓ |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| Overall change | 56.7 kB | 56.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.79 kB | 4.79 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| Overall change | 51.4 kB | 51.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall incre [...]

2020-04-17 20:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.4s | ⚠️ +121ms |
| nodeModulesSize | 55.5 MB | 55.5 MB | ⚠️ +1.02 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.938 | 1.892 | -0.05 |
| / avg req/sec | 1289.79 | 1321.55 | ⚠️ +31.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.944 | 0.958 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2648.33 | 2609.26 | -39.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.25 kB | 6.25 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5e5e.js gzip | 10.3 kB | N/A | N/A |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.a1..NSE.txt gzip | 220 B | 220 B | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| de003c3a9d30..63c7.js gzip | N/A | 10.3 kB | N/A |
| Overall change | 56.7 kB | 56.8 kB | ⚠️ +57 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.79 kB | 4.79 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.91 kB | ⚠️ +59 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| Overall change | 51.4 kB | 51.5 kB | ⚠️ +59 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.2 kB | 26.2 kB | ✓ |
| Overall change | 26.2 kB | 26.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.js gzip | 1.24 kB | 1.24 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| hooks.js gzip | 664 B | 664 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.05 kB | -13 B |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 7.86 kB | 7.84 kB | -13 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.module.js gzip | 602 B | 602 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.5 kB | -17 B |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.38 kB | 5.36 kB | -17 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| index.html gzip | 927 B | 926 B | -1 B |
| link.html gzip | 937 B | 936 B | -1 B |
| withRouter.html gzip | 924 B | 921 B | -3 B |
| Overall change | 2.79 kB | 2.78 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -299,7 +299,6 @@ var Link = /*#__PURE__*/function (_react$Component) {
 
         if (scroll) {
           window.scrollTo(0, 0);
-          document.body.focus();
         }
       });
     };
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -209,7 +209,6 @@ class Link extends _react.Component {
 
         if (scroll) {
           window.scrollTo(0, 0);
-          document.body.focus();
         }
       });
     };
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..a36f5c6f7.js</strong></summary>

```diff
@@ -818,6 +818,25 @@ var Router = /*#__PURE__*/function () {
             throw error;
           }
 
+          var bodyHadTabIndex = document.body.hasAttribute('tabindex');
+
+          if (!bodyHadTabIndex) {
+            // Body cannot receive focus without tab index -1
+            document.body.setAttribute('tabindex', '-1');
+          }
+
+          document.body.focus();
+
+          if (!bodyHadTabIndex) {
+            // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+            // So, let's remove it since we added it there.
+            // This is important because we probably don't want to focus the body if the user clicks on some
+            // parts of the page that is not an interactive element.
+            // This is useful for click+tab interaction, where you click close to a link + tab in order
+            // to focus that link – a fast way for moving the focus exactly where you want it to be.
+            document.body.removeAttribute('tabindex');
+          }
+
           Router.events.emit('routeChangeComplete', as);
           return resolve(true);
         }, reject);
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..92.module.js</strong></summary>

```diff
@@ -745,6 +745,25 @@ class Router {
           throw error;
         }
 
+        var bodyHadTabIndex = document.body.hasAttribute('tabindex');
+
+        if (!bodyHadTabIndex) {
+          // Body cannot receive focus without tab index -1
+          document.body.setAttribute('tabindex', '-1');
+        }
+
+        document.body.focus();
+
+        if (!bodyHadTabIndex) {
+          // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+          // So, let's remove it since we added it there.
+          // This is important because we probably don't want to focus the body if the user clicks on some
+          // parts of the page that is not an interactive element.
+          // This is useful for click+tab interaction, where you click close to a link + tab in order
+          // to focus that link – a fast way for moving the focus exactly where you want it to be.
+          document.body.removeAttribute('tabindex');
+        }
+
         Router.events.emit('routeChangeComplete', as);
         return resolve(true);
       }, reject);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1 +1 @@
-<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/index.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.7d6979ed92064e0b8892.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/main-ba0429788c8e1fb33 [...]

2020-04-18 18:23 UTC, timneutkens requested changes
Looks great! I'd like to have integration tests for this in `test/integration`

2020-05-22 09:05 UTC, timneutkens commented
Hey! I'd like to land this PR, it'd be great to have some tests for it though 🙏

2020-05-22 13:15 UTC, NMinhNguyen commented
> Hey! I'd like to land this PR, it'd be great to have some tests for it though

Would it make more sense to simply bring back https://github.com/zeit/next.js/pull/7693 which had tests? Or was there a reason why that old implementation was deemed insufficient and this new implementation was put forward instead?

2020-05-22 16:57 UTC, timneutkens commented
> > Hey! I'd like to land this PR, it'd be great to have some tests for it though
> 
> Would it make more sense to simply bring back #7693 which had tests? Or was there a reason why that old implementation was deemed insufficient and this new implementation was put forward instead?

It only worked for `next/link` and apparently was not sufficient.

2020-05-23 23:56 UTC, NMinhNguyen commented
I tried running the tests from #7693 on `canary` and they all passed without this code change, so I'm not sure if they're useful tests 😕

2020-05-24 15:08 UTC, olpeh commented
> I tried running the tests from #7693 on `canary` and they all passed without this code change, so I'm not sure if they're useful tests confused

Yeah, I noticed the same. Thanks for mentioning this. Maybe we should figure out why this happens.

2020-05-24 15:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +138ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +2.34 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.058 | 2.117 | ⚠️ +0.06 |
| / avg req/sec | 1215.07 | 1180.76 | -34.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.201 | 1.222 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2081.06 | 2046.38 | -34.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.6 kB | ⚠️ +57 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +57 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.98 kB | ⚠️ +64 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +64 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.04 kB | -14 B |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.21 kB | -14 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.5 kB | -18 B |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.31 kB | -18 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -364,7 +364,6 @@
 
                 if (scroll) {
                   window.scrollTo(0, 0);
-                  document.body.focus();
                 }
               });
           };
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -229,7 +229,6 @@
 
               if (scroll) {
                 window.scrollTo(0, 0);
-                document.body.focus();
               }
             });
           };
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..1c.module.js</strong></summary>

```diff
@@ -1041,6 +1041,30 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     throw error;
                   }
 
+                  if (error) {
+                    Router.events.emit("routeChangeError", error, as);
+                    throw error;
+                  }
+
+                  var bodyHadTabIndex = document.body.hasAttribute("tabindex");
+
+                  if (!bodyHadTabIndex) {
+                    // Body cannot receive focus without tab index -1
+                    document.body.setAttribute("tabindex", "-1");
+                  }
+
+                  document.body.focus();
+
+                  if (!bodyHadTabIndex) {
+                    // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+                    // So, let's remove it since we added it there.
+                    // This is important because we probably don't want to focus the body if the user clicks on some
+                    // parts of the page that is not an interactive element.
+                    // This is useful for click+tab interaction, where you click close to a link + tab in order
+                    // to focus that link – a fast way for moving the focus exactly where you want it to be.
+                    document.body.removeAttribute("tabindex");
+                  }
+
                   Router.events.emit("routeChangeComplete", as);
                   return resolve(true);
                 });
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..88f374159.js</strong></summary>

```diff
@@ -1206,6 +1206,32 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
                           }
 
+                          if (error) {
+                            Router.events.emit("routeChangeError", error, as);
+                            throw error;
+                          }
+
+                          var bodyHadTabIndex = document.body.hasAttribute(
+                            "tabindex"
+                          );
+
+                          if (!bodyHadTabIndex) {
+                            // Body cannot receive focus without tab index -1
+                            document.body.setAttribute("tabindex", "-1");
+                          }
+
+                          document.body.focus();
+
+                          if (!bodyHadTabIndex) {
+                            // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+                            // So, let's remove it since we added it there.
+                            // This is important because we probably don't want to focus the body if the user clicks on some
+                            // parts of the page that is not an interactive element.
+                            // This is useful for click+tab interaction, where you click close to a link + tab in order
+                            // to focus that link – a fast way for moving the focus exactly where you want it to be.
+                            document.body.removeAttribute("tabindex");
+                          }
+
                           Router.events.emit("routeChangeComplete", as);
                           return resolve(true);
                         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 [...]

2020-05-24 15:28 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | -55ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +2.34 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.099 | 2.259 | ⚠️ +0.16 |
| / avg req/sec | 1191.06 | 1106.59 | -84.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.338 | 1.313 | -0.03 |
| /error-in-render avg req/sec | 1868.85 | 1904.1 | ⚠️ +35.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..1e23.js gzip | 10.5 kB | 10.6 kB | ⚠️ +57 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +57 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.67 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.98 kB | ⚠️ +64 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +64 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.04 kB | -14 B |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.21 kB | -14 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.5 kB | -18 B |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.31 kB | -18 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | olpeh/next.js routing-focus-body | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -364,7 +364,6 @@
 
                 if (scroll) {
                   window.scrollTo(0, 0);
-                  document.body.focus();
                 }
               });
           };
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -229,7 +229,6 @@
 
               if (scroll) {
                 window.scrollTo(0, 0);
-                document.body.focus();
               }
             });
           };
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..1c.module.js</strong></summary>

```diff
@@ -1041,6 +1041,30 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     throw error;
                   }
 
+                  if (error) {
+                    Router.events.emit("routeChangeError", error, as);
+                    throw error;
+                  }
+
+                  var bodyHadTabIndex = document.body.hasAttribute("tabindex");
+
+                  if (!bodyHadTabIndex) {
+                    // Body cannot receive focus without tab index -1
+                    document.body.setAttribute("tabindex", "-1");
+                  }
+
+                  document.body.focus();
+
+                  if (!bodyHadTabIndex) {
+                    // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+                    // So, let's remove it since we added it there.
+                    // This is important because we probably don't want to focus the body if the user clicks on some
+                    // parts of the page that is not an interactive element.
+                    // This is useful for click+tab interaction, where you click close to a link + tab in order
+                    // to focus that link – a fast way for moving the focus exactly where you want it to be.
+                    document.body.removeAttribute("tabindex");
+                  }
+
                   Router.events.emit("routeChangeComplete", as);
                   return resolve(true);
                 });
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..88f374159.js</strong></summary>

```diff
@@ -1206,6 +1206,32 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
                           }
 
+                          if (error) {
+                            Router.events.emit("routeChangeError", error, as);
+                            throw error;
+                          }
+
+                          var bodyHadTabIndex = document.body.hasAttribute(
+                            "tabindex"
+                          );
+
+                          if (!bodyHadTabIndex) {
+                            // Body cannot receive focus without tab index -1
+                            document.body.setAttribute("tabindex", "-1");
+                          }
+
+                          document.body.focus();
+
+                          if (!bodyHadTabIndex) {
+                            // If the body did not originally have the tabindex attribute, there's probably a reason for that.
+                            // So, let's remove it since we added it there.
+                            // This is important because we probably don't want to focus the body if the user clicks on some
+                            // parts of the page that is not an interactive element.
+                            // This is useful for click+tab interaction, where you click close to a link + tab in order
+                            // to focus that link – a fast way for moving the focus exactly where you want it to be.
+                            document.body.removeAttribute("tabindex");
+                          }
+
                           Router.events.emit("routeChangeComplete", as);
                           return resolve(true);
                         });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,7 +30, [...]

2020-05-25 17:05 UTC, olpeh commented
I have now been debugging the test cases a bit around and to me it seems like the test pages are too simple, and thus the browsers knows to move the focus to the body in canary, but in reality this does not happen in a larger real-world app without these changes.

2020-05-25 17:32 UTC, NMinhNguyen commented
@olpeh that’s very interesting! You don’t think it’s possible to write a minimal failing test case for this then?

2020-05-26 03:31 UTC, olpeh commented
> @olpeh that’s very interesting! You don’t think it’s possible to write a minimal failing test case for this then?

Well, of course it has to be possible. I did not manage to do so yet. I tried with a slightly more complex example, that had more links on both of the pages and was expecting the focus to stay in one of the links.

2021-01-21 21:04 UTC, olpeh commented
Closing this PR as #20428 solves the same problem and more

2021-01-21 21:04 UTC, closed without merging