Improve `readme.md`
vercel/next.js pull request #1256
Opened 2017-02-23 14:18 UTC by nikvm

I tried to improve the docs under the following premises:

* Strong introduction
* Detailed Getting Started guide (especially for beginners)
* Improved consistency and clarity in language and appearance (layout, typography)
* Add missing docs, especially: #1069, #1134
* Link to resources in and outside the document as much as possible

What's missing:

* CLI docs (e.g. `next init`)
* ...?

Honestly, once started, I got carried away and might have gone a bit overboard with the changes.
But what's done is done and I might as well share what I've got.

As always, these are suggestions: Keep what you like, discard the rest. ❤️

2017-02-25 09:13 UTC, timneutkens reviewed
I like the improvements. Only thing I notice is that the docs feel 'crowded' because the sub-sub headings are as small as the content. Could you have a look at this?

2017-02-25 09:13 UTC, timneutkens commented
Found another missing docs ticket: https://github.com/zeit/next.js/issues/630#issuecomment-270040021

2017-02-25 11:08 UTC, sedubois commented
Well if you want to add more docs there's also https://github.com/zeit/next.js/issues/1229 😄 but personally I'd consider the PR already good enough, then refine things in a new one.

2017-02-25 13:54 UTC, nikvm commented
Thanks guys for having a read through.

@timneutkens I'm guessing you are especially looking at `h4` headings. Unfortunately this is Github's styling which we can't easily change. Using different heading levels breaks semantics. One change I was thinking about earlier is numbered sections and/or linked headings (appearing in blue). [Here is an example](https://github.com/jkbrzt/httpie/blob/master/README.rst). What do you think?

As for more missing docs: I'm with @sedubois and would rather get this PR approved and merged as is. And make changes in following PRs.

2017-02-25 13:56 UTC, sedubois commented
I also think that the README is starting to show its limits. Ideally Next.js needs a proper documentation website... Then starting from there, it could later also have a nice gallery of examples, with screenshots and a link to each of their versions deployed on Now.

2017-02-25 14:49 UTC, timneutkens commented
@sedubois I like this idea. 

@nikvm yeah I know 😞 The numbered sections thing is better indeed.

2017-02-25 15:27 UTC, nikvm commented
@rauchg mentioned [here](https://github.com/zeit/next.js/issues/1069#issuecomment-279271542) that he'd like to stick with the readme. I don't mind either way. Personally I like [Gitbook](https://www.gitbook.com/). But these options always come with added maintenance overhead&mdash;keeping code and docs in one place is always nice. Plus `readme.md` comes bundled with the `npm` package (which is good for offline usage).

@timneutkens I'll look into how we might automate numbered sections as `tocdoc` (used to automate creating our T.O.C.) doesn't provide the functionality.

2017-02-26 15:28 UTC, HaNdTriX commented on readme.md
> +When this higher-level `<Link>` component is first used, the `ServiceWorker` gets installed.
I think this is obsolete since https://github.com/zeit/next.js/pull/957

2017-02-26 17:08 UTC, arunoda commented on readme.md
> +When this higher-level `<Link>` component is first used, the `ServiceWorker` gets installed.
Yep.

2017-02-26 17:15 UTC, bdefore commented
This is great @nikvm, thanks!

If I could add one further request: this PR improves the warning somewhat but I think it should be more prominent and to link directly to the README of the latest stable release. I initially missed this when starting with next and tried using the beta functionality of `next.config.js` unawares and silently ignored.

2017-02-28 16:26 UTC, nikvm commented on readme.md
> +When this higher-level `<Link>` component is first used, the `ServiceWorker` gets installed.
I pushed [an update](https://github.com/zeit/next.js/pull/1256/commits/48b454605733c60b759038720cab230332b3e527) to address this.

2017-02-28 16:40 UTC, nikvm commented
@bdefore How should we make it more obvious? Add more ⚠️ signs? Move it up?

@timneutkens I thought a little more a bout numbered sections. The problem I see is when adding sections not to the end of a level. This might break links referencing a particular issue. As headings get auto-linked it's also not trivial to exclude the numbering. So I still hesitate implementing numbering.

2017-03-07 14:07 UTC, sedubois commented
@timneutkens how about merging this? It's going to get more and more conflicts otherwise

2017-03-15 16:35 UTC, rauchg commented on readme.md
> +- `push(url: string, as?: string): boolean` &ndash; Performs a [`pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_pushState()_method) call with the given url. Retur
we've deprecated `push` and `replace`, we want people to use `Router.push` and `Router.replace`

2017-03-15 16:35 UTC, rauchg commented on readme.md
> +First up, install Next.js and it's peer dependencies via [npm](https://npmjs.com/package/next):
`its`

2017-03-15 16:35 UTC, rauchg requested changes
Two changes and we're good to go! Thank you so much, sorry for the delay

2017-03-15 21:23 UTC, timneutkens commented
@nikvm please merge https://github.com/nikvm/next.js/pull/2 then I can merge this in. Thanks! 🤗

2017-03-16 00:58 UTC, bdefore commented
@nikvm sorry i'm so late to respond, but at this point it's not important to highlight the difference between master and stable release. looking forward to the major bump!

2017-03-16 05:06 UTC, timneutkens commented
@bdefore we will remove it right before 2.0 is released.

2017-03-16 15:49 UTC, timneutkens commented
@nikvm yeah it includes those. I'm curious what conflicts it has now :(

2017-06-30 20:18 UTC, timneutkens commented
Going to close this. We should port some of it at a later point.

2017-06-30 20:18 UTC, closed without merging