Add example with-hls-js
vercel/next.js pull request #12723
Opened 2020-05-11 15:26 UTC by dylanjha

Follow-up from discussion https://github.com/zeit/next.js/pull/12289

This example uses:

  * [hls.js](https://github.com/video-dev/hls.js/)
  * For content -- the canonical video example from the video community "Big Buck Bunny" - hosted by Mux (https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8)

<img width="1338" alt="with-hls-js_2020-05-11_08-25-12" src="https://user-images.githubusercontent.com/764988/81579389-f7b1f580-9360-11ea-8f7c-91871538830b.png">

2020-05-12 17:02 UTC, dylanjha commented
Thanks for taking a look @lfades! Let me know if there are any blockers to getting this in examples/!

2020-05-12 21:46 UTC, lfades requested changes
@dylanjha Thank you for the PR, please check my suggestion and then I'll merge.

2020-05-12 21:46 UTC, lfades commented on examples/with-hls-js/.gitignore
> +.env.production.local
```suggestion
.env*.local
```

2020-05-12 21:46 UTC, lfades commented on examples/with-hls-js/package.json
> +  "private": true,
```suggestion
  "license": "MIT",
```

2020-05-12 21:46 UTC, lfades commented on examples/with-hls-js/package.json
> +    "next": "9.3.6",
```suggestion
    "next": "latest",
```

2020-05-12 21:46 UTC, lfades commented on examples/with-hls-js/pages/api/hello.js
> +}
Remove `pages/api` entirely, the example doesn't need API routes.

2020-05-12 23:25 UTC, dylanjha commented
@lfades thanks! Updated.. That one "azure next.js" check seems to be a little flakey

2020-05-14 02:44 UTC, lfades approved these changes
Niceeee, thank you!

2020-05-14 02:47 UTC, merged

2021-02-17 23:47 UTC, jcohenho commented
I'm trying to follow this example but I keep getting the error `Uncaught ReferenceError: window is not defined`. I was under the impression that using hooks like `useEffect` would give us access to window, and in fact I do have access to window, yet I still see this error message. Where in the chain would window be undefined by hls.js?