Update routeKeys to handle non-word characters
vercel/next.js pull request #12801
Opened 2020-05-12 17:51 UTC by ijjk

This updates the named regexes output in the `routes-manifest` and the associated `routeKeys` to not use any non-word characters as this breaks the named regexes e.g. `"Invalid regular expression: "^/(?<data\-provider\-id>[^/]+?)(?:/)?$"`

2020-05-12 17:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.7s | ⚠️ +369ms |
| nodeModulesSize | 58.7 MB | 58.7 MB | ⚠️ +601 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.912 | 1.861 | -0.05 |
| / avg req/sec | 1307.83 | 1343.69 | ⚠️ +35.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.102 | 1.062 | -0.04 |
| /error-in-render avg req/sec | 2269.3 | 2354.48 | ⚠️ +85.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.68 kB | 6.68 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..e49d.js gzip | 10.4 kB | 10.4 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.72 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.85 kB | 6.85 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.29 kB | 3.29 kB | ✓ |
| hooks.js gzip | 880 B | 880 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 280 B | 280 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.26 kB | 8.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _app.module.js gzip | 599 B | 599 B | ✓ |
| _error.module.js gzip | 2.09 kB | 2.09 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 279 B | 279 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.37 kB | 5.37 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 927 B | 928 B | ⚠️ +1 B |
| link.html gzip | 937 B | 938 B | ⚠️ +1 B |
| withRouter.html gzip | 925 B | 926 B | ⚠️ +1 B |
| Overall change | 2.79 kB | 2.79 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..bc265fb82.js</strong></summary>

```diff
@@ -342,7 +342,8 @@ function getRouteRegex(normalizedRoute) {
     };
     return isCatchAll ? '/(.+?)' : '/([^/]+?)';
   });
-  var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+  var namedParameterizedRoute;
+  var routeKeys = {}; // dead code eliminate for browser since it's only needed
   // while generating routes-manifest
 
   if (false) {}
@@ -351,6 +352,7 @@ function getRouteRegex(normalizedRoute) {
     re: new RegExp('^' + parameterizedRoute + '(?:/)?$', 'i'),
     groups: groups
   }, namedParameterizedRoute ? {
+    routeKeys: routeKeys,
     namedRegex: "^".concat(namedParameterizedRoute, "(?:/)?$")
   } : {});
 }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..48.module.js</strong></summary>

```diff
@@ -267,7 +267,8 @@ function getRouteRegex(normalizedRoute) {
     };
     return isCatchAll ? '/(.+?)' : '/([^/]+?)';
   });
-  var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+  var namedParameterizedRoute;
+  var routeKeys = {}; // dead code eliminate for browser since it's only needed
   // while generating routes-manifest
 
   if (false) {}
@@ -276,6 +277,7 @@ function getRouteRegex(normalizedRoute) {
     re: new RegExp('^' + parameterizedRoute + '(?:/)?$', 'i'),
     groups
   }, namedParameterizedRoute ? {
+    routeKeys,
     namedRegex: "^".concat(namedParameterizedRoute, "(?:/)?$")
   } : {});
 }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -1 +1 @@
-<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/BUILD_ID/pages/_app.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/BUILD_ID/pages/index.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9c10f81c48c2c37b9948.module.js" as="script" crossorigin="anonymous"/><link rel="preload" href="/_next/static/runtime/main-bd1bb58e8c7ab90459e2.module.js" as="script" crossorigin="anonymous"/></head><body><div id="__next">Hello world 👋</div><script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"BUILD_ID","isFallback":false,"gip":true}</script><script crossorigin="anonymous" nomodule="">!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script><script crossorigin="anonymous" nomodule="" src="/_next/static/runtime/polyfills-1ec398ef836868c20f25.js"></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/_app" src="/_next/static/BUILD_ID/pages/_app.module.js" crossorigin="anonymous" type="module"></script><script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.js" crossorigin="anonymous" nomodule=""></script><script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.module.js" crossorigin="anonymous" type="module"></script><script src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js" async="" crossorigin="anonymous" type="module"></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.js" async="" crossorigin="anonymous" nomodule=""></script><script src="/_next/static/chunks/framework.5bb7f30f859f5f31359f.module.js" async="" crossorigin="ano [...]

2020-05-23 20:26 UTC, Timer requested changes
Do we need to increment the version on this manifest?

2020-06-12 20:01 UTC, ijjk commented
@Timer we might need to increment the version just to be safe since there were a couple stable versions of the builder that are expecting the previous `routeKeys` shape although those versions will encounter the bug when non-word characters are used in a dynamic route segment 🤔 so not sure, what do you think?

Versions of the builder expecting previous `routeKeys` shape:

Canary builders
@now/next@2.5.5-canary.5
@vercel/next@2.5.5-canary.7
@vercel/next@2.6.1-canary.0

Stable builders
@vercel/next@2.6.0
@vercel/next@2.6.1

2020-06-12 20:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.3s | -444ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.012 | 2.021 | ⚠️ +0.01 |
| / avg req/sec | 1242.7 | 1237.11 | -5.59 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.225 | 1.255 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2040.79 | 1991.56 | -49.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.7 kB | ⚠️ +197 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 57.1 kB | ⚠️ +197 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 7.14 kB | ⚠️ +207 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.6 kB | ⚠️ +207 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 956 B | ✓ |
| link.html gzip | 963 B | 963 B | ✓ |
| withRouter.html gzip | 949 B | 949 B | ✓ |
| Overall change | 2.87 kB | 2.87 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -513,6 +513,46 @@
     /***/ YTqd: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _defineProperty = __webpack_require__("lSNA");
+
+      function ownKeys(object, enumerableOnly) {
+        var keys = Object.keys(object);
+        if (Object.getOwnPropertySymbols) {
+          var symbols = Object.getOwnPropertySymbols(object);
+          if (enumerableOnly)
+            symbols = symbols.filter(function(sym) {
+              return Object.getOwnPropertyDescriptor(object, sym).enumerable;
+            });
+          keys.push.apply(keys, symbols);
+        }
+        return keys;
+      }
+
+      function _objectSpread(target) {
+        for (var i = 1; i < arguments.length; i++) {
+          var source = arguments[i] != null ? arguments[i] : {};
+          if (i % 2) {
+            ownKeys(Object(source), true).forEach(function(key) {
+              _defineProperty(target, key, source[key]);
+            });
+          } else if (Object.getOwnPropertyDescriptors) {
+            Object.defineProperties(
+              target,
+              Object.getOwnPropertyDescriptors(source)
+            );
+          } else {
+            ownKeys(Object(source)).forEach(function(key) {
+              Object.defineProperty(
+                target,
+                key,
+                Object.getOwnPropertyDescriptor(source, key)
+              );
+            });
+          }
+        }
+        return target;
+      }
+
       exports.__esModule = true;
       exports.getRouteRegex = getRouteRegex; // this isn't importing the escape-string-regex module
       // to reduce bytes
@@ -558,19 +598,25 @@
               : "/([^/]+?)";
           }
         );
-        var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+        var namedParameterizedRoute;
+        var routeKeys = {}; // dead code eliminate for browser since it's only needed
         // while generating routes-manifest
 
         if (false) {
         }
 
-        return {
-          re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
-        };
+        return _objectSpread(
+          {
+            re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
+            groups: groups
+          },
+          namedParameterizedRoute
+            ? {
+                routeKeys: routeKeys,
+                namedRegex: "^".concat(namedParameterizedRoute, "(?:/)?$")
+              }
+            : {}
+        );
       }
 
       /***/
@@ -2005,6 +2051,27 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
+    /***/ lSNA: /***/ function(module, exports) {
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+
+        return obj;
+      }
+
+      module.exports = _defineProperty;
+
+      /***/
+    },
+
     /***/ ls82: /***/ function(module, exports, __webpack_require__) {
       /**
        * Copyright (c) 2014-present, Facebook, Inc.
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -435,6 +435,46 @@
     /***/ YTqd: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _defineProperty = __webpack_require__("lSNA");
+
+      function ownKeys(object, enumerableOnly) {
+        var keys = Object.keys(object);
+        if (Object.getOwnPropertySymbols) {
+          var symbols = Object.getOwnPropertySymbols(object);
+          if (enumerableOnly)
+            symbols = symbols.filter(function(sym) {
+              return Object.getOwnPropertyDescriptor(object, sym).enumerable;
+            });
+          keys.pu [...]

2020-06-12 20:24 UTC, ijjk commented
## Failing test suites <!--791458156-->

**test/integration/prerender/test/index.test.js** 
- SSG Prerender > enumlated serverless mode > outputs dataRoutes in routes-manifest correctly
- SSG Prerender > production mode > outputs dataRoutes in routes-manifest correctly
- SSG Prerender > serverless mode > outputs dataRoutes in routes-manifest correctly

<details>
<summary>Expand output</summary>

  ● SSG Prerender › serverless mode › outputs dataRoutes in routes-manifest correctly

    expect(received).toEqual(expected) // deep equality

    - Expected  - 29
    + Received  + 29

    @@ -1,94 +1,94 @@
      Array [
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/index.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/index.json$",
          "page": "/",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/another.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/another.json$",
          "page": "/another",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/bad-gssp.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/bad-gssp.json$",
          "page": "/bad-gssp",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/bad-ssr.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/bad-ssr.json$",
          "page": "/bad-ssr",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/blog.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/blog.json$",
          "page": "/blog",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/blog\\/([^\\/]+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/blog/(?<post>[^/]+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/blog\\/([^\\/]+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/blog/(?<post>[^/]+?)\\.json$",
          "page": "/blog/[post]",
          "routeKeys": Object {
            "post": "post",
          },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/blog\\/([^\\/]+?)\\/([^\\/]+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/blog/(?<post>[^/]+?)/(?<comment>[^/]+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/blog\\/([^\\/]+?)\\/([^\\/]+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/blog/(?<post>[^/]+?)/(?<comment>[^/]+?)\\.json$",
          "page": "/blog/[post]/[comment]",
          "routeKeys": Object {
            "comment": "comment",
            "post": "post",
          },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/catchall\\/(.+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/catchall/(?<slug>.+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/catchall\\/(.+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/catchall/(?<slug>.+?)\\.json$",
          "page": "/catchall/[...slug]",
          "routeKeys": Object {
            "slug": "slug",
          },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/catchall\\-explicit\\/(.+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/catchall\\-explicit/(?<slug>.+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/catchall\\-explicit\\/(.+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/catchall\\-explicit/(?<slug>.+?)\\.json$",
          "page": "/catchall-explicit/[...slug]",
          "routeKeys": Object {
            "slug": "slug",
          },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/default-revalidate.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/default-revalidate.json$",
          "page": "/default-revalidate",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/fallback\\-only\\/([^\\/]+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/fallback\\-only/(?<slug>[^/]+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/fallback\\-only\\/([^\\/]+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/fallback\\-only/(?<slug>[^/]+?)\\.json$",
          "page": "/fallback-only/[slug]",
    -     "routeKeys": Array [
    -       "slug",
    -     ],
    +     "routeKeys": Object {
    +       "slug": "slug",
    +     },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/lang\\/([^\\/]+?)\\/about\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/lang/(?<lang>[^/]+?)/about\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/lang\\/([^\\/]+?)\\/about\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/lang/(?<lang>[^/]+?)/about\\.json$",
          "page": "/lang/[lang]/about",
    -     "routeKeys": Array [
    -       "lang",
    -     ],
    +     "routeKeys": Object {
    +       "lang": "lang",
    +     },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/non\\-json\\/([^\\/]+?)\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/non\\-json/(?<p>[^/]+?)\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/non\\-json\\/([^\\/]+?)\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/non\\-json/(?<p>[^/]+?)\\.json$",
          "page": "/non-json/[p]",
          "routeKeys": Object {
            "p": "p",
          },
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/something.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/something.json$",
          "page": "/something",
        },
        Object {
    -     "dataRouteRegex": "^\\/_next\\/data\\/GWfJxddDsWfFAXeKqbCoq\\/user\\/([^\\/]+?)\\/profile\\.json$",
    -     "namedDataRouteRegex": "^/_next/data/GWfJxddDsWfFAXeKqbCoq/user/(?<user>[^/]+?)/profile\\.json$",
    +     "dataRouteRegex": "^\\/_next\\/data\\/WygBYYn6LYfDpPTuDYzLU\\/user\\/([^\\/]+?)\\/profile\\.json$",
    +     "namedDataRouteRegex": "^/_next/data/WygBYYn6LYfDpPTuDYzLU/user/(?<user>[^/]+?)/profile\\.json$",
          "page": "/user/[user]/profile",
          "routeKeys": Object {
            "user": "user",
          },
        },

      820 |       }
      821 | 
    > 822 |       expect(dataRoutes).toEqual([
          |                          ^
      823 |         {
      824 |           dataRouteRegex: normalizeRegEx(
      825 |             `^\\/_next\\/data\\/${escapeRegex(buildId)}\\/index.json$`

      at Object.<anonymous> (integration/prerender/test/index.test.js:822:26)

  ● SSG Prerender › enumlated serverless mode › outputs dataRoutes in routes-manifest correctly

    expect(received).toEqual(expected) // deep equality

    - Expected  - 6
    + Received  + 6

    @@ -58,21 +58,21 @@
        },
        Object {
          "dataRouteRegex": "^\\/_next\\/data\\/ULFARVa5MPpbxZSeZiN2l\\/fallback\\-only\\/([^\\/]+?)\\.json$",
          "namedDataRouteRegex": "^/_next/data/ULFARVa5MPpbxZSeZiN2l/fallback\\-only/(?<slug>[^/]+?)\\.json$",
          "page": "/fallback-only/[slug]",
    -     "routeKeys": Array [
    -       "slug",
    -     ],
    +     "routeKeys": Object {
    +       "slug": "slu [...]

2020-06-12 20:46 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 13s | 12.7s | -333ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.246 | 2.244 | 0 |
| / avg req/sec | 1112.88 | 1114.21 | ⚠️ +1.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.443 | 1.449 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1732.15 | 1724.77 | -7.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.7 kB | ⚠️ +197 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 57.1 kB | ⚠️ +197 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 7.14 kB | ⚠️ +207 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.6 kB | ⚠️ +207 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 956 B | ✓ |
| link.html gzip | 963 B | 963 B | ✓ |
| withRouter.html gzip | 949 B | 949 B | ✓ |
| Overall change | 2.87 kB | 2.87 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -513,6 +513,46 @@
     /***/ YTqd: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _defineProperty = __webpack_require__("lSNA");
+
+      function ownKeys(object, enumerableOnly) {
+        var keys = Object.keys(object);
+        if (Object.getOwnPropertySymbols) {
+          var symbols = Object.getOwnPropertySymbols(object);
+          if (enumerableOnly)
+            symbols = symbols.filter(function(sym) {
+              return Object.getOwnPropertyDescriptor(object, sym).enumerable;
+            });
+          keys.push.apply(keys, symbols);
+        }
+        return keys;
+      }
+
+      function _objectSpread(target) {
+        for (var i = 1; i < arguments.length; i++) {
+          var source = arguments[i] != null ? arguments[i] : {};
+          if (i % 2) {
+            ownKeys(Object(source), true).forEach(function(key) {
+              _defineProperty(target, key, source[key]);
+            });
+          } else if (Object.getOwnPropertyDescriptors) {
+            Object.defineProperties(
+              target,
+              Object.getOwnPropertyDescriptors(source)
+            );
+          } else {
+            ownKeys(Object(source)).forEach(function(key) {
+              Object.defineProperty(
+                target,
+                key,
+                Object.getOwnPropertyDescriptor(source, key)
+              );
+            });
+          }
+        }
+        return target;
+      }
+
       exports.__esModule = true;
       exports.getRouteRegex = getRouteRegex; // this isn't importing the escape-string-regex module
       // to reduce bytes
@@ -558,19 +598,25 @@
               : "/([^/]+?)";
           }
         );
-        var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+        var namedParameterizedRoute;
+        var routeKeys = {}; // dead code eliminate for browser since it's only needed
         // while generating routes-manifest
 
         if (false) {
         }
 
-        return {
-          re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
-        };
+        return _objectSpread(
+          {
+            re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
+            groups: groups
+          },
+          namedParameterizedRoute
+            ? {
+                routeKeys: routeKeys,
+                namedRegex: "^".concat(namedParameterizedRoute, "(?:/)?$")
+              }
+            : {}
+        );
       }
 
       /***/
@@ -2005,6 +2051,27 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       /***/
     },
 
+    /***/ lSNA: /***/ function(module, exports) {
+      function _defineProperty(obj, key, value) {
+        if (key in obj) {
+          Object.defineProperty(obj, key, {
+            value: value,
+            enumerable: true,
+            configurable: true,
+            writable: true
+          });
+        } else {
+          obj[key] = value;
+        }
+
+        return obj;
+      }
+
+      module.exports = _defineProperty;
+
+      /***/
+    },
+
     /***/ ls82: /***/ function(module, exports, __webpack_require__) {
       /**
        * Copyright (c) 2014-present, Facebook, Inc.
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -435,6 +435,46 @@
     /***/ YTqd: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _defineProperty = __webpack_require__("lSNA");
+
+      function ownKeys(object, enumerableOnly) {
+        var keys = Object.keys(object);
+        if (Object.getOwnPropertySymbols) {
+          var symbols = Object.getOwnPropertySymbols(object);
+          if (enumerableOnly)
+            symbols = symbols.filter(function(sym) {
+              return Object.getOwnPropertyDescriptor(object, sym).enumerable;
+            });
+          keys.push.app [...]

2020-06-12 21:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 10.8s | 10.9s | ⚠️ +125ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.49 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.864 | 1.881 | ⚠️ +0.02 |
| / avg req/sec | 1341.16 | 1329.36 | -11.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.2 | 1.208 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2083.56 | 2069.58 | -13.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | -8 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.92 kB | -9 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 954 B | -2 B |
| link.html gzip | 963 B | 961 B | -2 B |
| withRouter.html gzip | 949 B | 948 B | -1 B |
| Overall change | 2.87 kB | 2.86 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -558,7 +558,8 @@
               : "/([^/]+?)";
           }
         );
-        var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+        var namedParameterizedRoute;
+        var routeKeys = {}; // dead code eliminate for browser since it's only needed
         // while generating routes-manifest
 
         if (false) {
@@ -566,10 +567,7 @@
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups: groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -480,7 +480,8 @@
               : "/([^/]+?)";
           }
         );
-        var namedParameterizedRoute; // dead code eliminate for browser since it's only needed
+        var namedParameterizedRoute;
+        var routeKeys = {}; // dead code eliminate for browser since it's only needed
         // while generating routes-manifest
 
         if (false) {
@@ -488,10 +489,7 @@
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6939074386b3587fce47.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6962571ed86d59cf6d0f.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6939074386b3587fce47.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6939074386b3587fce47.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6962571ed86d59cf6d0f.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6939074386b3587fce47.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.6939074386b3587fce47.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <sc [...]

2020-06-14 17:49 UTC, Timer reviewed
Let's bump it.

2020-06-15 03:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.5s | ⚠️ +258ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.49 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.902 | 1.898 | 0 |
| / avg req/sec | 1314.59 | 1317.48 | ⚠️ +2.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.132 | -0.05 |
| /error-in-render avg req/sec | 2119.37 | 2207.6 | ⚠️ +88.23 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | -8 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.92 kB | -9 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 954 B | -2 B |
| link.html gzip | 963 B | 961 B | -2 B |
| withRouter.html gzip | 949 B | 947 B | -2 B |
| Overall change | 2.87 kB | 2.86 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -562,14 +562,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups: groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -484,14 +484,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       asy [...]

2020-06-15 16:16 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 11s | 11.3s | ⚠️ +347ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.49 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.997 | 2.083 | ⚠️ +0.09 |
| / avg req/sec | 1252.06 | 1200.45 | -51.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.458 | 1.215 | -0.24 |
| /error-in-render avg req/sec | 1714.92 | 2056.95 | ⚠️ +342.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | -8 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.92 kB | -9 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 954 B | -2 B |
| link.html gzip | 963 B | 961 B | -2 B |
| withRouter.html gzip | 949 B | 947 B | -2 B |
| Overall change | 2.87 kB | 2.86 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -562,14 +562,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups: groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -484,14 +484,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
     [...]

2020-06-16 13:31 UTC, Timer approved these changes

2020-06-16 13:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| buildDuration | 12.3s | 11.7s | -559ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ⚠️ +1.49 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.232 | 2.13 | -0.1 |
| / avg req/sec | 1119.94 | 1173.67 | ⚠️ +53.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.555 | 1.415 | -0.14 |
| /error-in-render avg req/sec | 1607.53 | 1766.53 | ⚠️ +159 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | -8 B |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.92 kB | -9 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js update/route-keys | Change |
| - | - | - | - |
| index.html gzip | 956 B | 954 B | -2 B |
| link.html gzip | 963 B | 961 B | -2 B |
| withRouter.html gzip | 949 B | 947 B | -2 B |
| Overall change | 2.87 kB | 2.86 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..8dcf890b6.js</strong></summary>

```diff
@@ -562,14 +562,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups: groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups: groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6c.module.js</strong></summary>

```diff
@@ -484,14 +484,12 @@
         // while generating routes-manifest
 
         if (false) {
+          var routeKeys;
         }
 
         return {
           re: new RegExp("^" + parameterizedRoute + "(?:/)?$", "i"),
-          groups,
-          namedRegex: namedParameterizedRoute
-            ? "^".concat(namedParameterizedRoute, "(?:/)?$")
-            : undefined
+          groups
         };
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -122,13 +122,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.0ea083186308dcf890b6.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.c055dea44cbce095b7e0.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.f733a40f0fc0ecaa4b6c.module.js"
+      src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.deb50154f80a4044eb84.module.js"
       asy [...]

2020-06-16 13:49 UTC, merged