Wait until flush before resolving render promises
vercel/next.js pull request #12938
Opened 2020-05-15 16:28 UTC by devknoll

2020-05-18 16:59 UTC, devknoll commented
Ping @Timer @timneutkens

2020-05-18 17:29 UTC, Timer requested changes

2020-05-18 17:29 UTC, Timer commented on packages/next/client/index.js
> +    const self = (lastRenderResolver = () => {
Please use a different name that does not shadow a global.

2020-05-19 18:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| buildDuration | 11.9s | 12.8s | ⚠️ +857ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +1.82 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.98 | 2.067 | ⚠️ +0.09 |
| / avg req/sec | 1262.43 | 1209.54 | -52.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.146 | 1.164 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2181.27 | 2148.23 | -33.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.65 kB | 6.76 kB | ⚠️ +114 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..b058.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..1e06.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57.2 kB | ⚠️ +113 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.78 kB | ⚠️ +88 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ⚠️ +3 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.6 kB | ⚠️ +91 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| index.html gzip | 927 B | 927 B | ✓ |
| link.html gzip | 937 B | 937 B | ✓ |
| withRouter.html gzip | 924 B | 924 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..da.module.js</strong></summary>

```diff
@@ -774,15 +774,15 @@ class Router {
 
         if (false) { var appComp; }
 
-        this.set(route, pathname, query, as, routeInfo);
-
-        if (error) {
-          Router.events.emit('routeChangeError', error, as);
-          throw error;
-        }
+        this.set(route, pathname, query, as, routeInfo).then(() => {
+          if (error) {
+            Router.events.emit('routeChangeError', error, as);
+            throw error;
+          }
 
-        Router.events.emit('routeChangeComplete', as);
-        return resolve(true);
+          Router.events.emit('routeChangeComplete', as);
+          return resolve(true);
+        });
       }, reject);
     });
   }
@@ -904,7 +904,7 @@ class Router {
     this.pathname = pathname;
     this.query = query;
     this.asPath = as;
-    this.notify(data);
+    return this.notify(data);
   }
   /**
   * Callback to execute before replacing router state
@@ -1069,7 +1069,7 @@ class Router {
   }
 
   notify(data) {
-    this.sub(data, this.components['/_app'].Component);
+    return this.sub(data, this.components['/_app'].Component);
   }
 
 }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..6d213b24c.js</strong></summary>

```diff
@@ -906,15 +906,15 @@ var Router = /*#__PURE__*/function () {
 
           if (false) { var appComp; }
 
-          _this2.set(route, pathname, query, as, routeInfo);
-
-          if (error) {
-            Router.events.emit('routeChangeError', error, as);
-            throw error;
-          }
+          _this2.set(route, pathname, query, as, routeInfo).then(function () {
+            if (error) {
+              Router.events.emit('routeChangeError', error, as);
+              throw error;
+            }
 
-          Router.events.emit('routeChangeComplete', as);
-          return resolve(true);
+            Router.events.emit('routeChangeComplete', as);
+            return resolve(true);
+          });
         }, reject);
       });
     }
@@ -1043,7 +1043,7 @@ var Router = /*#__PURE__*/function () {
       this.pathname = pathname;
       this.query = query;
       this.asPath = as;
-      this.notify(data);
+      return this.notify(data);
     }
     /**
     * Callback to execute before replacing router state
@@ -1261,7 +1261,7 @@ var Router = /*#__PURE__*/function () {
   }, {
     key: "notify",
     value: function notify(data) {
-      this.sub(data, this.components['/_app'].Component);
+      return this.sub(data, this.components['/_app'].Component);
     }
   }], [{
     key: "_rewriteUrlForNextExport",
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,6 +289,9 @@ window.__NEXT_P.push = register;
 var updateHead = (0, _headManager["default"])();
 var appElement = document.getElementById('__next');
 var lastAppProps;
+
+var _lastRenderResolver;
+
 var webpackHMR;
 var router;
 exports.router = router;
@@ -384,7 +387,7 @@ var emitter = (0, _mitt["default"])();
 exports.emitter = emitter;
 
 var _default = /*#__PURE__*/function () {
-  var _ref3 = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee() {
+  var _ref3 = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee2() {
     var _ref4,
         passedWebpackHMR,
         _yield$pageLoader$loa,
@@ -397,22 +400,22 @@ var _default = /*#__PURE__*/function () {
         _require3,
         getNodeError,
         renderCtx,
-        _args = arguments;
+        _args2 = arguments;
 
-    return _regeneratorRuntime.wrap(function _callee$(_context) {
+    return _regeneratorRuntime.wrap(function _callee2$(_context2) {
       while (1) {
-        switch (_context.prev = _context.next) {
+        switch (_context2.prev = _context2.next) {
           case 0:
-            _ref4 = _args.length > 0 && _args[0] !== undefined ? _args[0] : {}, passedWebpackHMR = _ref4.webpackHMR;
+            _ref4 = _args2.length > 0 && _args2[0] !== undefined ? _args2[0] : {}, passedWebpackHMR = _ref4.webpackHMR;
 
             // This makes sure this spe [...]

2020-05-19 21:49 UTC, Timer requested changes

2020-05-19 21:49 UTC, Timer commented on packages/next/client/index.js
> +    subscription: async ({ Component, props, err }, App) =>
Seems this `async` / `await` is unnecessary. Can we directly return `render` to skip regenerator?

2020-05-19 21:49 UTC, Timer commented on packages/next/client/index.js
> +  React.useLayoutEffect(() => {
Is there any reason to prefer `useLayoutEffect` over `useEffect` here? Could you elaborate on why with a comment (or switch to `useEffect`)?

2020-05-19 21:49 UTC, Timer commented on packages/next/client/index.js
> +    lastRenderResolver()
Wouldn't this fire `after-reactdom-render` requests for canceled renders? Is that OK? Might also be good to note in comments.

2020-05-20 16:34 UTC, ijjk commented
## Failing test suites <!--700918902-->

**test/integration/auto-export-serverless/test/index.test.js** 
- Auto Export Serverless > Refreshes query on mount

<details>
<summary>Expand output</summary>

  ● Auto Export Serverless › Refreshes query on mount

    expect(received).toMatch(expected)

    Expected pattern: /post.*post-1/
    Received string:  "<div id=\"__next\"><div style=\"color: rgb(0, 0, 0); background: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif; height: 100vh; text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center;\"><div><style>body { margin: 0 }</style><div style=\"display: inline-block; text-align: left; line-height: 49px; height: 49px; vertical-align: middle;\"><h2 style=\"font-size: 14px; font-weight: normal; line-height: inherit; margin: 0px; padding: 0px;\">An unexpected error has occurred.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/[post]\",\"query\":{},\"buildId\":\"qIWDNbQsRquudxGh4qeE8\",\"runtimeConfig\":{},\"nextExport\":true,\"autoExport\":true,\"isFallback\":false}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-c347cb6f295444888ea6.js\"></script><script async=\"\" data-next-page=\"/_app\" src=\"/_next/static/qIWDNbQsRquudxGh4qeE8/pages/_app.js\"></script><script async=\"\" data-next-page=\"/[post]\" src=\"/_next/static/qIWDNbQsRquudxGh4qeE8/pages/%5Bpost%5D.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" async=\"\"></script><script src=\"/_next/static/chunks/commons.661bce04834ce6ed9d8b.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-aca5eb5fbfbddb66a18a.js\" async=\"\"></script><script src=\"/_next/static/qIWDNbQsRquudxGh4qeE8/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/qIWDNbQsRquudxGh4qeE8/_ssgManifest.js\" async=\"\"></script><script src=\"/_next/static/qIWDNbQsRquudxGh4qeE8/pages/_error.js\"></script>"

      18 |     const browser = await webdriver(appPort, '/post-1')
      19 |     const html = await browser.eval('document.body.innerHTML')
    > 20 |     expect(html).toMatch(/post.*post-1/)
         |                  ^
      21 |     expect(html).toMatch(/nextExport/)
      22 | 
      23 |     await killApp(app)

      at Object.<anonymous> (integration/auto-export-serverless/test/index.test.js:20:18)

</details>

2020-05-20 16:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.7s | ⚠️ +299ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +2.71 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.999 | 2.026 | ⚠️ +0.03 |
| / avg req/sec | 1250.68 | 1233.99 | -16.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.349 | 1.301 | -0.05 |
| /error-in-render avg req/sec | 1853.33 | 1921.9 | ⚠️ +68.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.65 kB | 6.77 kB | ⚠️ +123 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..1e23.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57.2 kB | ⚠️ +122 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.81 kB | ⚠️ +123 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ⚠️ +3 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.6 kB | ⚠️ +126 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| index.html gzip | 928 B | 927 B | -1 B |
| link.html gzip | 938 B | 935 B | -3 B |
| withRouter.html gzip | 925 B | 923 B | -2 B |
| Overall change | 2.79 kB | 2.79 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..95.module.js</strong></summary>

```diff
@@ -775,15 +775,15 @@ class Router {
 
         if (false) { var appComp; }
 
-        this.set(route, pathname, query, as, routeInfo);
-
-        if (error) {
-          Router.events.emit('routeChangeError', error, as);
-          throw error;
-        }
+        this.set(route, pathname, query, as, routeInfo).then(() => {
+          if (error) {
+            Router.events.emit('routeChangeError', error, as);
+            throw error;
+          }
 
-        Router.events.emit('routeChangeComplete', as);
-        return resolve(true);
+          Router.events.emit('routeChangeComplete', as);
+          return resolve(true);
+        });
       }, reject);
     });
   }
@@ -905,7 +905,7 @@ class Router {
     this.pathname = pathname;
     this.query = query;
     this.asPath = as;
-    this.notify(data);
+    return this.notify(data);
   }
   /**
   * Callback to execute before replacing router state
@@ -1070,7 +1070,7 @@ class Router {
   }
 
   notify(data) {
-    this.sub(data, this.components['/_app'].Component);
+    return this.sub(data, this.components['/_app'].Component);
   }
 
 }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..af23efe53.js</strong></summary>

```diff
@@ -907,15 +907,15 @@ var Router = /*#__PURE__*/function () {
 
           if (false) { var appComp; }
 
-          _this2.set(route, pathname, query, as, routeInfo);
-
-          if (error) {
-            Router.events.emit('routeChangeError', error, as);
-            throw error;
-          }
+          _this2.set(route, pathname, query, as, routeInfo).then(function () {
+            if (error) {
+              Router.events.emit('routeChangeError', error, as);
+              throw error;
+            }
 
-          Router.events.emit('routeChangeComplete', as);
-          return resolve(true);
+            Router.events.emit('routeChangeComplete', as);
+            return resolve(true);
+          });
         }, reject);
       });
     }
@@ -1044,7 +1044,7 @@ var Router = /*#__PURE__*/function () {
       this.pathname = pathname;
       this.query = query;
       this.asPath = as;
-      this.notify(data);
+      return this.notify(data);
     }
     /**
     * Callback to execute before replacing router state
@@ -1262,7 +1262,7 @@ var Router = /*#__PURE__*/function () {
   }, {
     key: "notify",
     value: function notify(data) {
-      this.sub(data, this.components['/_app'].Component);
+      return this.sub(data, this.components['/_app'].Component);
     }
   }], [{
     key: "_rewriteUrlForNextExport",
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,6 +289,9 @@ window.__NEXT_P.push = register;
 var updateHead = (0, _headManager["default"])();
 var appElement = document.getElementById('__next');
 var lastAppProps;
+
+var _lastRenderReject;
+
 var webpackHMR;
 var router;
 exports.router = router;
@@ -502,7 +505,7 @@ var _default = /*#__PURE__*/function () {
                 var Component = _ref6.Component,
                     props = _ref6.props,
                     err = _ref6.err;
-                render({
+                return render({
                   App: App,
                   Component: Component,
                   props: props,
@@ -751,7 +754,7 @@ function doRender(_x2) {
 
 function _doRender() {
   _doRender = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee3(_ref9) {
-    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, elem;
+    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, resolvePromise, renderPromise, elem;
 
     return _regeneratorRuntime.wrap(function _callee3$(_context3) {
       while (1) {
@@ -794,19 +797,32 @@ function _doRender() {
             }); // lastAppProps has to be set before ReactDom.render to account for ReactDom throwing an error.
 
             lastAppProps = appProps;
-            emitter.emit('before-reactdom-render' [...]

2020-05-20 17:37 UTC, ijjk commented
## Failing test suites <!--701147706-->

**test/integration/auto-export-serverless/test/index.test.js** 
- Auto Export Serverless > Refreshes query on mount

<details>
<summary>Expand output</summary>

  ● Auto Export Serverless › Refreshes query on mount

    expect(received).toMatch(expected)

    Expected pattern: /post.*post-1/
    Received string:  "<div id=\"__next\"><div style=\"color: rgb(0, 0, 0); background: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif; height: 100vh; text-align: center; display: flex; flex-direction: column; align-items: center; justify-content: center;\"><div><style>body { margin: 0 }</style><div style=\"display: inline-block; text-align: left; line-height: 49px; height: 49px; vertical-align: middle;\"><h2 style=\"font-size: 14px; font-weight: normal; line-height: inherit; margin: 0px; padding: 0px;\">An unexpected error has occurred.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/[post]\",\"query\":{},\"buildId\":\"VQ0x6Sr5BrrT4bG0Oz7oe\",\"runtimeConfig\":{},\"nextExport\":true,\"autoExport\":true,\"isFallback\":false}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-c347cb6f295444888ea6.js\"></script><script async=\"\" data-next-page=\"/_app\" src=\"/_next/static/VQ0x6Sr5BrrT4bG0Oz7oe/pages/_app.js\"></script><script async=\"\" data-next-page=\"/[post]\" src=\"/_next/static/VQ0x6Sr5BrrT4bG0Oz7oe/pages/%5Bpost%5D.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" async=\"\"></script><script src=\"/_next/static/chunks/commons.661bce04834ce6ed9d8b.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-282e1cb6ac0ff49ffb7e.js\" async=\"\"></script><script src=\"/_next/static/VQ0x6Sr5BrrT4bG0Oz7oe/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/VQ0x6Sr5BrrT4bG0Oz7oe/_ssgManifest.js\" async=\"\"></script><script src=\"/_next/static/VQ0x6Sr5BrrT4bG0Oz7oe/pages/_error.js\"></script>"

      18 |     const browser = await webdriver(appPort, '/post-1')
      19 |     const html = await browser.eval('document.body.innerHTML')
    > 20 |     expect(html).toMatch(/post.*post-1/)
         |                  ^
      21 |     expect(html).toMatch(/nextExport/)
      22 | 
      23 |     await killApp(app)

      at Object.<anonymous> (integration/auto-export-serverless/test/index.test.js:20:18)

</details>

2020-05-20 17:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.5s | ⚠️ +30ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +2.73 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.367 | 2.385 | ⚠️ +0.02 |
| / avg req/sec | 1056.08 | 1048.06 | -8.02 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.537 | 1.471 | -0.07 |
| /error-in-render avg req/sec | 1626.16 | 1699.29 | ⚠️ +73.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.65 kB | 6.77 kB | ⚠️ +124 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..1e23.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57.2 kB | ⚠️ +123 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.81 kB | ⚠️ +122 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ⚠️ +3 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.6 kB | ⚠️ +125 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| index.html gzip | 928 B | 927 B | -1 B |
| link.html gzip | 938 B | 936 B | -2 B |
| withRouter.html gzip | 925 B | 925 B | ✓ |
| Overall change | 2.79 kB | 2.79 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..95.module.js</strong></summary>

```diff
@@ -775,15 +775,15 @@ class Router {
 
         if (false) { var appComp; }
 
-        this.set(route, pathname, query, as, routeInfo);
-
-        if (error) {
-          Router.events.emit('routeChangeError', error, as);
-          throw error;
-        }
+        this.set(route, pathname, query, as, routeInfo).then(() => {
+          if (error) {
+            Router.events.emit('routeChangeError', error, as);
+            throw error;
+          }
 
-        Router.events.emit('routeChangeComplete', as);
-        return resolve(true);
+          Router.events.emit('routeChangeComplete', as);
+          return resolve(true);
+        });
       }, reject);
     });
   }
@@ -905,7 +905,7 @@ class Router {
     this.pathname = pathname;
     this.query = query;
     this.asPath = as;
-    this.notify(data);
+    return this.notify(data);
   }
   /**
   * Callback to execute before replacing router state
@@ -1070,7 +1070,7 @@ class Router {
   }
 
   notify(data) {
-    this.sub(data, this.components['/_app'].Component);
+    return this.sub(data, this.components['/_app'].Component);
   }
 
 }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..af23efe53.js</strong></summary>

```diff
@@ -907,15 +907,15 @@ var Router = /*#__PURE__*/function () {
 
           if (false) { var appComp; }
 
-          _this2.set(route, pathname, query, as, routeInfo);
-
-          if (error) {
-            Router.events.emit('routeChangeError', error, as);
-            throw error;
-          }
+          _this2.set(route, pathname, query, as, routeInfo).then(function () {
+            if (error) {
+              Router.events.emit('routeChangeError', error, as);
+              throw error;
+            }
 
-          Router.events.emit('routeChangeComplete', as);
-          return resolve(true);
+            Router.events.emit('routeChangeComplete', as);
+            return resolve(true);
+          });
         }, reject);
       });
     }
@@ -1044,7 +1044,7 @@ var Router = /*#__PURE__*/function () {
       this.pathname = pathname;
       this.query = query;
       this.asPath = as;
-      this.notify(data);
+      return this.notify(data);
     }
     /**
     * Callback to execute before replacing router state
@@ -1262,7 +1262,7 @@ var Router = /*#__PURE__*/function () {
   }, {
     key: "notify",
     value: function notify(data) {
-      this.sub(data, this.components['/_app'].Component);
+      return this.sub(data, this.components['/_app'].Component);
     }
   }], [{
     key: "_rewriteUrlForNextExport",
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,6 +289,9 @@ window.__NEXT_P.push = register;
 var updateHead = (0, _headManager["default"])();
 var appElement = document.getElementById('__next');
 var lastAppProps;
+
+var _lastRenderReject;
+
 var webpackHMR;
 var router;
 exports.router = router;
@@ -502,7 +505,7 @@ var _default = /*#__PURE__*/function () {
                 var Component = _ref6.Component,
                     props = _ref6.props,
                     err = _ref6.err;
-                render({
+                return render({
                   App: App,
                   Component: Component,
                   props: props,
@@ -751,7 +754,7 @@ function doRender(_x2) {
 
 function _doRender() {
   _doRender = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee3(_ref9) {
-    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, elem;
+    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, resolvePromise, renderPromise, elem;
 
     return _regeneratorRuntime.wrap(function _callee3$(_context3) {
       while (1) {
@@ -794,21 +797,35 @@ function _doRender() {
             }); // lastAppProps has to be set before ReactDom.render to account for ReactDom throwing an error.
 
             lastAppProps = appProps;
-            emitter.emit('before-reactdom-render', {
 [...]

2020-05-20 18:15 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.6s | ⚠️ +203ms |
| nodeModulesSize | 61.8 MB | 61.8 MB | ⚠️ +1.52 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.018 | 2.05 | ⚠️ +0.03 |
| / avg req/sec | 1238.63 | 1219.64 | -18.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.171 | 1.228 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 2135.38 | 2036.44 | -98.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.65 kB | 6.69 kB | ⚠️ +44 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..fef6.js gzip | 10.5 kB | N/A | N/A |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| de003c3a9d30..1e23.js gzip | N/A | 10.5 kB | N/A |
| Overall change | 57 kB | 57.1 kB | ⚠️ +43 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.69 kB | 5.74 kB | ⚠️ +46 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ⚠️ +3 B |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +49 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.06 kB | 2.06 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.22 kB | 8.22 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.33 kB | 5.33 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | azukaru/next.js fix-router-wait | Change |
| - | - | - | - |
| index.html gzip | 928 B | 928 B | ✓ |
| link.html gzip | 938 B | 937 B | -1 B |
| withRouter.html gzip | 925 B | 924 B | -1 B |
| Overall change | 2.79 kB | 2.79 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>de003c3a9d30..95.module.js</strong></summary>

```diff
@@ -775,15 +775,15 @@ class Router {
 
         if (false) { var appComp; }
 
-        this.set(route, pathname, query, as, routeInfo);
-
-        if (error) {
-          Router.events.emit('routeChangeError', error, as);
-          throw error;
-        }
+        this.set(route, pathname, query, as, routeInfo).then(() => {
+          if (error) {
+            Router.events.emit('routeChangeError', error, as);
+            throw error;
+          }
 
-        Router.events.emit('routeChangeComplete', as);
-        return resolve(true);
+          Router.events.emit('routeChangeComplete', as);
+          return resolve(true);
+        });
       }, reject);
     });
   }
@@ -905,7 +905,7 @@ class Router {
     this.pathname = pathname;
     this.query = query;
     this.asPath = as;
-    this.notify(data);
+    return this.notify(data);
   }
   /**
   * Callback to execute before replacing router state
@@ -1070,7 +1070,7 @@ class Router {
   }
 
   notify(data) {
-    this.sub(data, this.components['/_app'].Component);
+    return this.sub(data, this.components['/_app'].Component);
   }
 
 }
```
</details>
<details>
<summary>Diff for <strong>de003c3a9d30..af23efe53.js</strong></summary>

```diff
@@ -907,15 +907,15 @@ var Router = /*#__PURE__*/function () {
 
           if (false) { var appComp; }
 
-          _this2.set(route, pathname, query, as, routeInfo);
-
-          if (error) {
-            Router.events.emit('routeChangeError', error, as);
-            throw error;
-          }
+          _this2.set(route, pathname, query, as, routeInfo).then(function () {
+            if (error) {
+              Router.events.emit('routeChangeError', error, as);
+              throw error;
+            }
 
-          Router.events.emit('routeChangeComplete', as);
-          return resolve(true);
+            Router.events.emit('routeChangeComplete', as);
+            return resolve(true);
+          });
         }, reject);
       });
     }
@@ -1044,7 +1044,7 @@ var Router = /*#__PURE__*/function () {
       this.pathname = pathname;
       this.query = query;
       this.asPath = as;
-      this.notify(data);
+      return this.notify(data);
     }
     /**
     * Callback to execute before replacing router state
@@ -1262,7 +1262,7 @@ var Router = /*#__PURE__*/function () {
   }, {
     key: "notify",
     value: function notify(data) {
-      this.sub(data, this.components['/_app'].Component);
+      return this.sub(data, this.components['/_app'].Component);
     }
   }], [{
     key: "_rewriteUrlForNextExport",
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,6 +289,9 @@ window.__NEXT_P.push = register;
 var updateHead = (0, _headManager["default"])();
 var appElement = document.getElementById('__next');
 var lastAppProps;
+
+var _lastRenderReject;
+
 var webpackHMR;
 var router;
 exports.router = router;
@@ -502,7 +505,7 @@ var _default = /*#__PURE__*/function () {
                 var Component = _ref6.Component,
                     props = _ref6.props,
                     err = _ref6.err;
-                render({
+                return render({
                   App: App,
                   Component: Component,
                   props: props,
@@ -751,7 +754,7 @@ function doRender(_x2) {
 
 function _doRender() {
   _doRender = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime.mark(function _callee3(_ref9) {
-    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, elem;
+    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps, resolvePromise, renderPromise, elem;
 
     return _regeneratorRuntime.wrap(function _callee3$(_context3) {
       while (1) {
@@ -794,21 +797,30 @@ function _doRender() {
             }); // lastAppProps has to be set before ReactDom.render to account for ReactDom throwing an error.
 
             lastAppProps = appProps;
-            emitter.emit('before-reactdom-render', {
-  [...]

2020-05-23 21:54 UTC, closed without merging