Fix pages/index.js and pages/index/index.js behavior
vercel/next.js pull request #13699
Opened 2020-06-03 05:36 UTC by Janpot

Disambiguate between pages/index.js and pages/index/index.js so that they resolve differently.
It all started with a bug in pagesmanifest that propagated throughout the codebase. After fixing pagesmanifest I was able to remove a few hacks here and there and more logic is shared now. especially the logic that resolves an entrypoint back into a route path.

2020-06-03 05:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.9s | -152ms |
| nodeModulesSize | 66 MB | 66 MB | -330 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.114 | 2.191 | ⚠️ +0.08 |
| / avg req/sec | 1182.34 | 1140.91 | -41.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.448 | 1.28 | -0.17 |
| /error-in-render avg req/sec | 1726.09 | 1952.54 | ⚠️ +226.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.66 kB | -9 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 924 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 922 B | 922 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,7 +1464,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1107,7 +1107,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -150,13 +150,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.7s | -410ms |
| nodeModulesSize | 66 MB | 66 MB | -330 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js  [...]

2020-06-03 06:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.3s | ⚠️ +17ms |
| nodeModulesSize | 66 MB | 66 MB | -649 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.081 | 2.056 | -0.02 |
| / avg req/sec | 1201.28 | 1216.2 | ⚠️ +14.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.192 | 1.214 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2097.52 | 2058.7 | -38.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.66 kB | -9 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 924 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 922 B | 922 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,7 +1464,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1107,7 +1107,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -150,13 +150,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -113ms |
| nodeModulesSize | 66 MB | 66 MB | -649 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js  [...]

2020-06-03 06:48 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.6s | -146ms |
| nodeModulesSize | 66 MB | 66 MB | -1.27 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.416 | 2.359 | -0.06 |
| / avg req/sec | 1034.56 | 1059.95 | ⚠️ +25.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.567 | 1.522 | -0.04 |
| /error-in-render avg req/sec | 1595.27 | 1642.67 | ⚠️ +47.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.66 kB | -9 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 924 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 922 B | 922 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,7 +1464,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1107,7 +1107,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -150,13 +150,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.5s | ⚠️ +114ms |
| nodeModulesSize | 66 MB | 66 MB | -1.27 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.modul [...]

2020-06-03 06:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.9s | ⚠️ +46ms |
| nodeModulesSize | 66 MB | 66 MB | -1.27 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.288 | 2.353 | ⚠️ +0.07 |
| / avg req/sec | 1092.85 | 1062.65 | -30.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.414 | 1.385 | -0.03 |
| /error-in-render avg req/sec | 1767.57 | 1805.6 | ⚠️ +38.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.66 kB | -9 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | -9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 924 B | ✓ |
| link.html gzip | 934 B | 934 B | ✓ |
| withRouter.html gzip | 922 B | 922 B | ✓ |
| Overall change | 2.78 kB | 2.78 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1464,7 +1464,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1107,7 +1107,6 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -150,13 +150,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      href="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -145,13 +145,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/runtime/main-750a8131bb83360bfd80.js"
+      src="/_next/static/runtime/main-087f0e4219e35a79617c.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/runtime/main-5062a6ab83d04dfd16c2.module.js"
+      src="/_next/static/runtime/main-7de5e1201b6117a97e03.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.6s | -182ms |
| nodeModulesSize | 66 MB | 66 MB | -1.27 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.58 kB | -8 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module. [...]

2020-06-03 15:28 UTC, Timer commented on test/integration/custom-server/server.js
> +      return app.render(req, res, '/')
I believe this is a breaking change, and we needed to keep it for backwards compat.

2020-06-03 15:30 UTC, Timer requested changes
I'm pretty sure the intention of `pages/index/index.js` is to resolve at `/`, **not** `/index`. The updated tests seem to undo that behavior. cc @ijjk

2020-06-03 16:07 UTC, Timer reviewed
Let's comprehensively test the client-side Link behavior and land this.

2020-06-03 21:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.6s | ⚠️ +29ms |
| nodeModulesSize | 66 MB | 66 MB | -635 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.934 | 1.912 | -0.02 |
| / avg req/sec | 1292.73 | 1307.76 | ⚠️ +15.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.127 | 1.178 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 2218.22 | 2122.15 | -96.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = [...]

2020-06-03 22:03 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.2s | -156ms |
| nodeModulesSize | 66 MB | 66 MB | -635 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.066 | 2.156 | ⚠️ +0.09 |
| / avg req/sec | 1210.03 | 1159.41 | -50.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.194 | 1.158 | -0.04 |
| /error-in-render avg req/sec | 2093.69 | 2159.81 | ⚠️ +66.12 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = ge [...]

2020-06-03 22:07 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.5s | -242ms |
| nodeModulesSize | 66 MB | 66 MB | -635 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.281 | 2.336 | ⚠️ +0.05 |
| / avg req/sec | 1095.79 | 1070.17 | -25.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.462 | 1.436 | -0.03 |
| /error-in-render avg req/sec | 1709.71 | 1741.04 | ⚠️ +31.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = ge [...]

2020-06-03 23:43 UTC, ijjk commented
## Failing test suites <!--752585730-->

**test/integration/index-index/test/index.test.js** 
- nested index.js > dev mode > should ssr page /index/user
- nested index.js > dev mode > should client render page /index/user
- nested index.js > dev mode > should follow link to /index/user
- nested index.js > dev mode > should ssr page /index/project
- nested index.js > dev mode > should client render page /index/project
- nested index.js > dev mode > should follow link to /index/project

<details>
<summary>Expand output</summary>

  ● nested index.js › dev mode › should ssr page /index/user

    expect(received).toBe(expected) // Object.is equality

    Expected: "index > user"
    Received: ""

      81 |     const html = await renderViaHTTP(appPort, '/index/user')
      82 |     const $ = cheerio.load(html)
    > 83 |     expect($('#page').text()).toBe('index > user')
         |                               ^
      84 |   })
      85 | 
      86 |   it('should client render page /index/user', async () => {

      at Object.<anonymous> (integration/index-index/test/index.test.js:83:31)

  ● nested index.js › dev mode › should client render page /index/user

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#page"}
      (Session info: headless chrome=81.0.4044.138)

      87 |     const browser = await webdriver(appPort, '/index/user')
      88 |     try {
    > 89 |       const text = await browser.elementByCss('#page').text()
         |                    ^
      90 |       expect(text).toBe('index > user')
      91 |     } finally {
      92 |       await browser.close()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/index-index/test/index.test.js:89:20)

  ● nested index.js › dev mode › should client render page /index/user

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      84 |   })
      85 | 
    > 86 |   it('should client render page /index/user', async () => {
         |   ^
      87 |     const browser = await webdriver(appPort, '/index/user')
      88 |     try {
      89 |       const text = await browser.elementByCss('#page').text()

      at runTests (integration/index-index/test/index.test.js:86:3)
      at integration/index-index/test/index.test.js:194:5
      at integration/index-index/test/index.test.js:187:3
      at Object.<anonymous> (integration/index-index/test/index.test.js:186:1)

  ● nested index.js › dev mode › should follow link to /index/user

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#page"}
      (Session info: headless chrome=81.0.4044.138)

      347 |   for (let tries = 0; tries < 30; tries++) {
      348 |     try {
    > 349 |       content = await contentFn()
          |                 ^
      350 |       if (regex.test(content)) {
      351 |         // found the content
      352 |         return true

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at check (lib/next-test-utils.js:349:17)
      at Object.<anonymous> (integration/index-index/test/index.test.js:101:7)

  ● nested index.js › dev mode › should follow link to /index/user

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      94 |   })
      95 | 
    > 96 |   it('should follow link to /index/user', async () => {
         |   ^
      97 |     const browser = await webdriver(appPort, '/links')
      98 |     try {
      99 |       await browser.elementByCss('#link5').click()

      at runTests (integration/index-index/test/index.test.js:96:3)
      at integration/index-index/test/index.test.js:194:5
      at integration/index-index/test/index.test.js:187:3
      at Object.<anonymous> (integration/index-index/test/index.test.js:186:1)

  ● nested index.js › dev mode › should ssr page /index/project

    expect(received).toBe(expected) // Object.is equality

    Expected: "index > project"
    Received: ""

      108 |     const html = await renderViaHTTP(appPort, '/index/project')
      109 |     const $ = cheerio.load(html)
    > 110 |     expect($('#page').text()).toBe('index > project')
          |                               ^
      111 |   })
      112 | 
      113 |   it('should client render page /index/project', async () => {

      at Object.<anonymous> (integration/index-index/test/index.test.js:110:31)

  ● nested index.js › dev mode › should client render page /index/project

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#page"}
      (Session info: headless chrome=81.0.4044.138)

      114 |     const browser = await webdriver(appPort, '/index/project')
      115 |     try {
    > 116 |       const text = await browser.elementByCss('#page').text()
          |                    ^
      117 |       expect(text).toBe('index > project')
      118 |     } finally {
      119 |       await browser.close()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
          at runMicrotasks (<anonymous>)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous> (integration/index-index/test/index.test.js:116:20)

  ● nested index.js › dev mode › should client render page /index/project

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      111 |   })
      112 | 
    > 113 |   it('should client render page /index/project', async () => {
          |   ^
      114 |     const browser = await webdriver(appPort, '/index/project')
      115 |     try {
      116 |       const text = await browser.elementByCss('#page').text()

      at runTests (integration/index-index/test/index.test.js:113:3)
      at integration/index-index/test/index.test.js:194:5
      at integration/index-index/test/index.test.js:187:3
      at Object.<anonymous> (integration/index-index/test/index.test.js:186:1)

  ● nested index.js › dev mode › should follow link to /index/project

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#page"}
      (Session info: headless chrome=81.0.4044.138)

      347 |   for (let tries = 0; tries < 30; tries++) {
      348 |     try {
    > 349 |       content = await contentFn()
          |                 ^
      350 |       if (regex.test(content)) {
      351 |         // found the content
      352 |         return true

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:563:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:489:26)
          at runMicrotasks (<anonymous>)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at check (lib/next-test-utils.js:349:17)
      at Objec [...]

2020-06-04 05:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12s | 12.2s | ⚠️ +150ms |
| nodeModulesSize | 66 MB | 66 MB | -984 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.98 | 2.01 | ⚠️ +0.03 |
| / avg req/sec | 1262.41 | 1243.98 | -18.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.239 | 1.157 | -0.08 |
| /error-in-render avg req/sec | 2017.16 | 2161.33 | ⚠️ +144.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = ge [...]

2020-06-04 05:57 UTC, ijjk commented
## Failing test suites <!--753656251-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > dev mode > should handle /api/sub/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › dev mode › should handle /api/sub/index correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      92 |   it('should handle /api/sub/index correctly', async () => {
      93 |     const res = await fetchViaHTTP(appPort, '/api/sub/index')
    > 94 |     expect(res.status).toBe(200)
         |                        ^
      95 |     expect(await res.text()).toContain('hi from sub id')
      96 |   })
      97 | 

      at Object.<anonymous> (integration/route-indexes/test/index.test.js:94:24)

</details>

2020-06-04 06:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.9s | -14ms |
| nodeModulesSize | 66 MB | 66 MB | -980 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.998 | 2.009 | ⚠️ +0.01 |
| / avg req/sec | 1251.13 | 1244.36 | -6.77 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.167 | 1.154 | -0.01 |
| /error-in-render avg req/sec | 2141.89 | 2166.8 | ⚠️ +24.91 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = getAs [...]

2020-06-04 06:07 UTC, ijjk commented
## Failing test suites <!--753678011-->

**test/integration/route-indexes/test/index.test.js** 
- Route indexes handling > dev mode > should handle /api/sub/index correctly

<details>
<summary>Expand output</summary>

  ● Route indexes handling › dev mode › should handle /api/sub/index correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      92 |   it('should handle /api/sub/index correctly', async () => {
      93 |     const res = await fetchViaHTTP(appPort, '/api/sub/index')
    > 94 |     expect(res.status).toBe(200)
         |                        ^
      95 |     expect(await res.text()).toContain('hi from sub id')
      96 |   })
      97 | 

      at Object.<anonymous> (integration/route-indexes/test/index.test.js:94:24)

</details>

2020-06-04 06:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.4s | ⚠️ +53ms |
| nodeModulesSize | 66 MB | 66 MB | -972 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.354 | 2.315 | -0.04 |
| / avg req/sec | 1061.93 | 1080.03 | ⚠️ +18.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.479 | 1.522 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1690.46 | 1642.96 | -47.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +19 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +19 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 926 B | ⚠️ +2 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path, ".json");
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute);
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,8 +1740,7 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route, ".js");
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
@@ -1828,10 +1836,7 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
+                var scriptRoute = getAssetPath(route, ".js");
 
                 if (true && hasNoModule) {
                   scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route, extension) {
+        return route === "/"
+          ? "/index".concat(extension)
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route).concat(extension)
+          : "".concat(route).concat(extension);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path, ".json");
               return ""
                 .concat(this.assetPrefix, "/_next/data/")
                 .concat(this.buildId)
-                .concat(path === "/" ? "/index" : path, ".json");
+                .concat(dataRoute);
             };
 
           var { pathname: hrefPathname, query } = (0, _url.parse)(href, true);
@@ -1331,8 +1340,7 @@
 
         loadRoute(route) {
           route = normalizeRoute(route);
-          var scriptRoute =
-            route === "/" ? "/index.js" : "".concat(route, ".js");
+          var scriptRoute = g [...]

2020-06-04 07:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.8s | ⚠️ +273ms |
| nodeModulesSize | 66 MB | 66 MB | -1.25 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.39 | 2.41 | ⚠️ +0.02 |
| / avg req/sec | 1045.98 | 1037.2 | -8.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.545 | 1.543 | 0 |
| /error-in-render avg req/sec | 1617.64 | 1620.06 | ⚠️ +2.42 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +20 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +22 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 925 B | ⚠️ +1 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path);
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute, ".json");
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,12 +1740,11 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route);
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
-                .concat(encodeURI(scriptRoute));
+                .concat(encodeURI(scriptRoute), ".js");
               this.loadScript(url, route, true);
             }
           },
@@ -1828,19 +1836,13 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
-
-                if (true && hasNoModule) {
-                  scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
-                }
-
+                var scriptRoute = getAssetPath(route);
+                var ext = true && hasNoModule ? ".module.js" : ".js";
                 url = ""
                   .concat(this.assetPrefix, "/_next/static/")
                   .concat(encodeURIComponent(this.buildId), "/pages")
-                  .concat(encodeURI(scriptRoute));
+                  .concat(encodeURI(scriptRoute))
+                  .concat(ext);
               }
 
               return Promise.all(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path);
               return ""
                 .concat(this.assetPrefix, "/_n [...]

2020-06-04 07:17 UTC, ijjk commented
## Failing test suites <!--753828257-->

**test/integration/css/test/index.test.js** 
- CSS Support > Ordering with Global CSS and Modules (dev) > should have the correct color (css ordering) during hot reloads

<details>
<summary>Expand output</summary>

  ● CSS Support › Ordering with Global CSS and Modules (dev) › should have the correct color (css ordering) during hot reloads

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `CSS Support Ordering with Global CSS and Modules (dev) should have the correct color (css ordering) during hot reloads 1`

    Snapshot: "rgb(0, 0, 255)"
    Received: "rgb(255, 0, 0)"

      829 |           `window.getComputedStyle(document.querySelector('#blueText')).color`
      830 |         )
    > 831 |         expect(currentColor).toMatchInlineSnapshot(`"rgb(0, 0, 255)"`)
          |                              ^
      832 | 
      833 |         const cssFile = new File(join(appDir, 'pages/index.module.css'))
      834 |         try {

      at Object.<anonymous> (integration/css/test/index.test.js:831:30)

  ● CSS Support › Ordering with Global CSS and Modules (dev) › should have the correct color (css ordering) during hot reloads

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `CSS Support Ordering with Global CSS and Modules (dev) should have the correct color (css ordering) during hot reloads 2`

    Snapshot: "rgb(0, 0, 255)"
    Received: "rgb(255, 0, 0)"

      839 |             `window.getComputedStyle(document.querySelector('#blueText')).color`
      840 |           )
    > 841 |           expect(refreshedColor).toMatchInlineSnapshot(`"rgb(0, 0, 255)"`)
          |                                  ^
      842 |         } finally {
      843 |           cssFile.restore()
      844 |         }

      at Object.<anonymous> (integration/css/test/index.test.js:841:34)

</details>

2020-06-04 07:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.7s | ⚠️ +173ms |
| nodeModulesSize | 66 MB | 66 MB | -1.25 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.953 | 1.95 | 0 |
| / avg req/sec | 1279.77 | 1282.02 | ⚠️ +2.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.105 | 1.128 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2261.51 | 2216.38 | -45.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +20 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +22 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 925 B | ⚠️ +1 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path);
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute, ".json");
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,12 +1740,11 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route);
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
-                .concat(encodeURI(scriptRoute));
+                .concat(encodeURI(scriptRoute), ".js");
               this.loadScript(url, route, true);
             }
           },
@@ -1828,19 +1836,13 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
-
-                if (true && hasNoModule) {
-                  scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
-                }
-
+                var scriptRoute = getAssetPath(route);
+                var ext = true && hasNoModule ? ".module.js" : ".js";
                 url = ""
                   .concat(this.assetPrefix, "/_next/static/")
                   .concat(encodeURIComponent(this.buildId), "/pages")
-                  .concat(encodeURI(scriptRoute));
+                  .concat(encodeURI(scriptRoute))
+                  .concat(ext);
               }
 
               return Promise.all(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path);
               return ""
                 .concat(this.assetPrefix, " [...]

2020-06-04 08:19 UTC, Janpot commented
@Timer tests added

2020-06-04 15:58 UTC, Timer requested changes

2020-06-04 16:45 UTC, Timer submitted a review, later dismissed
LGTM. Excited to have this behavior be consistent!

2020-06-04 16:55 UTC, Timer approved these changes

2020-06-04 17:16 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.1s | ⚠️ +252ms |
| nodeModulesSize | 66 MB | 66 MB | -644 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.287 | 2.329 | ⚠️ +0.04 |
| / avg req/sec | 1093.34 | 1073.38 | -19.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.558 | 1.498 | -0.06 |
| /error-in-render avg req/sec | 1604.49 | 1669.19 | ⚠️ +64.7 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +20 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +22 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 925 B | ⚠️ +1 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path);
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute, ".json");
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,12 +1740,11 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route);
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
-                .concat(encodeURI(scriptRoute));
+                .concat(encodeURI(scriptRoute), ".js");
               this.loadScript(url, route, true);
             }
           },
@@ -1828,19 +1836,13 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
-
-                if (true && hasNoModule) {
-                  scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
-                }
-
+                var scriptRoute = getAssetPath(route);
+                var ext = true && hasNoModule ? ".module.js" : ".js";
                 url = ""
                   .concat(this.assetPrefix, "/_next/static/")
                   .concat(encodeURIComponent(this.buildId), "/pages")
-                  .concat(encodeURI(scriptRoute));
+                  .concat(encodeURI(scriptRoute))
+                  .concat(ext);
               }
 
               return Promise.all(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path);
               return ""
                 .concat(this.assetPrefix, [...]

2020-06-04 17:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11.8s | ⚠️ +568ms |
| nodeModulesSize | 66 MB | 66 MB | -644 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.987 | 1.994 | ⚠️ +0.01 |
| / avg req/sec | 1258.24 | 1253.62 | -4.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.153 | 1.117 | -0.04 |
| /error-in-render avg req/sec | 2168.17 | 2238.92 | ⚠️ +70.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.59 kB | 6.61 kB | ⚠️ +20 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..6c2a.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57 kB | 57 kB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.67 kB | 5.69 kB | ⚠️ +22 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.5 kB | 52.5 kB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error.js gzip | 3.25 kB | 3.25 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| Overall change | 8.21 kB | 8.21 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| _error.module.js gzip | 2.04 kB | 2.04 kB | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 5.32 kB | 5.32 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Janpot/next.js clean-index-index | Change |
| - | - | - | - |
| index.html gzip | 924 B | 925 B | ⚠️ +1 B |
| link.html gzip | 934 B | 935 B | ⚠️ +1 B |
| withRouter.html gzip | 922 B | 923 B | ⚠️ +1 B |
| Overall change | 2.78 kB | 2.78 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1427,6 +1427,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports["default"] = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1464,11 +1465,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise(function(res, rej, link) {
           link = document.createElement("link");
@@ -1548,10 +1556,11 @@
                 /** @type string */
                 function getHrefForSlug(path) {
                   path = (0, _router.delBasePath)(path);
+                  var dataRoute = getAssetPath(path);
                   return ""
                     .concat(_this2.assetPrefix, "/_next/data/")
                     .concat(_this2.buildId)
-                    .concat(path === "/" ? "/index" : path, ".json");
+                    .concat(dataRoute, ".json");
                 };
 
               var _ref = (0, _url.parse)(href, true),
@@ -1731,12 +1740,11 @@
             key: "loadRoute",
             value: function loadRoute(route) {
               route = normalizeRoute(route);
-              var scriptRoute =
-                route === "/" ? "/index.js" : "".concat(route, ".js");
+              var scriptRoute = getAssetPath(route);
               var url = ""
                 .concat(this.assetPrefix, "/_next/static/")
                 .concat(encodeURIComponent(this.buildId), "/pages")
-                .concat(encodeURI(scriptRoute));
+                .concat(encodeURI(scriptRoute), ".js");
               this.loadScript(url, route, true);
             }
           },
@@ -1828,19 +1836,13 @@
                 url = route;
               } else {
                 route = normalizeRoute(route);
-                var scriptRoute = "".concat(
-                  route === "/" ? "/index" : route,
-                  ".js"
-                );
-
-                if (true && hasNoModule) {
-                  scriptRoute = scriptRoute.replace(/\.js$/, ".module.js");
-                }
-
+                var scriptRoute = getAssetPath(route);
+                var ext = true && hasNoModule ? ".module.js" : ".js";
                 url = ""
                   .concat(this.assetPrefix, "/_next/static/")
                   .concat(encodeURIComponent(this.buildId), "/pages")
-                  .concat(encodeURI(scriptRoute));
+                  .concat(encodeURI(scriptRoute))
+                  .concat(ext);
               }
 
               return Promise.all(
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1070,6 +1070,7 @@
       var _interopRequireDefault = __webpack_require__("TqRt");
 
       exports.__esModule = true;
+      exports.getAssetPath = getAssetPath;
       exports.default = void 0;
 
       var _url = __webpack_require__("QmWs");
@@ -1107,11 +1108,18 @@
           );
         }
 
-        route = route.replace(/\/index$/, "/");
         if (route === "/") return route;
         return route.replace(/\/$/, "");
       }
 
+      function getAssetPath(route) {
+        return route === "/"
+          ? "/index"
+          : /^\/index(\/|$)/.test(route)
+          ? "/index".concat(route)
+          : "".concat(route);
+      }
+
       function appendLink(href, rel, as) {
         return new Promise((res, rej, link) => {
           link = document.createElement("link");
@@ -1177,10 +1185,11 @@
             /** @type string */
             path => {
               path = (0, _router.delBasePath)(path);
+              var dataRoute = getAssetPath(path);
               return ""
                 .concat(this.assetPrefix, [...]

2020-06-04 17:32 UTC, merged