Use chunkhash instead of buildId for pages
vercel/next.js pull request #13937
Opened 2020-06-09 11:27 UTC by timneutkens

Went with the simple approach initially so that all other internals depending on the directory structure are not affected.
Will do another pass at this once tests pass.

2020-06-09 11:31 UTC, ijjk commented
## Failing test suites <!--775398138-->

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    Cannot find module '/home/runner/work/next.js/next.js/test/integration/amphtml-fragment-style/.next/prerender-manifest.json' from 'next-server.js'

      309 |       return this._cachedPreviewManifest
      310 |     }
    > 311 |     const manifest = require(join(this.distDir, PRERENDER_MANIFEST))
          |                      ^
      312 |     return (this._cachedPreviewManifest = manifest)
      313 |   }
      314 | 

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:259:17)
      at Server.getPrerenderManifest (../packages/next/next-server/server/next-server.ts:311:22)
      at Server.getPreviewProps (../packages/next/next-server/server/next-server.ts:316:12)
      at new Server (../packages/next/next-server/server/next-server.ts:168:23)
      at createServer (../packages/next/server/next.ts:41:10)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      297 | 
      298 | export async function stopApp(server) {
    > 299 |   if (server.__app) {
          |              ^
      300 |     await server.__app.close()
      301 |   }
      302 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:299:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

2020-06-09 11:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 13s | 13.4s | ⚠️ +334ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +497 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.372 | 2.31 | -0.06 |
| / avg req/sec | 1054.11 | 1082.31 | ⚠️ +28.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.459 | 1.529 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1714.01 | 1634.6 | -79.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html [...]

2020-06-09 11:56 UTC, ijjk commented
## Failing test suites <!--775482334-->

**test/integration/404-page-custom-error/test/index.test.js** 
- Default 404 Page with custom _error > dev mode > should respond to 404 correctly
- Default 404 Page with custom _error > dev mode > should render error correctly
- Default 404 Page with custom _error > dev mode > should render index page normal

<details>
<summary>Expand output</summary>

  ● Default 404 Page with custom _error › dev mode › should respond to 404 correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 404
    Received: 500

      27 |   it('should respond to 404 correctly', async () => {
      28 |     const res = await fetchViaHTTP(appPort, '/404')
    > 29 |     expect(res.status).toBe(404)
         |                        ^
      30 |     expect(await res.text()).toContain('This page could not be found')
      31 |   })
      32 | 

      at Object.<anonymous> (integration/404-page-custom-error/test/index.test.js:29:24)

  ● Default 404 Page with custom _error › dev mode › should render error correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "oops"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack.js?ts=1591703783273\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/development/pages/_app.js?ts=1591703783273\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main.js?ts=1591703783273\" as=\"script\"/><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/runtime/react-refresh.js?ts=1591703783273\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ChunkRenderError\",\"message\":\"Conflict: Multiple chunks emit assets to the same filename static/development/pages/_error.js (chunks static/BUILD_ID/pages/_error.js and static/development/pages/_error.js)\",\"stack\":\"ChunkRenderError: Conflict: Multiple chunks emit assets to the same filename static/development/pages/_error.js (chunks static/BUILD_ID/pages/_error.js and static/development/pages/_error.js)\\n    at Compilation.createChunkAssets (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:2202:6)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1397:10\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/next.js/next.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), \\u003canonymous\\u003e:4:1)\\n    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/next.js/next.js/node_modules/tapable/lib/Hook.js:154:20)\\n    at Compilation.seal (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1342:27)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compiler.js:675:18\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1261:4\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/next.js/next.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), \\u003canonymous\\u003e:13:1)\\n    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/next.js/next.js/node_modules/tapable/lib/Hook.js:154:20)\\n    at Compilation.finish (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1253:28)\"},\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills.js?ts=1591703783273\"></script><script src=\"/_next/static/runtime/webpack.js?ts=1591703783273\" async=\"\"></script><script src=\"/_next/static/development/pages/_app.js?ts=1591703783273\" async=\"\"></script><script src=\"/_next/static/runtime/main.js?ts=1591703783273\" async=\"\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1591703783273\" async=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1591703783273\" async=\"\"></script></body></html>"

      33 |   it('should render error correctly', async () => {
      34 |     const text = await renderViaHTTP(appPort, '/err')
    > 35 |     expect(text).toContain(isDev ? 'oops' : 'Internal Server Error')
         |                  ^
      36 |   })
      37 | 
      38 |   it('should render index page normal', async () => {

      at Object.<anonymous> (integration/404-page-custom-error/test/index.test.js:35:18)

  ● Default 404 Page with custom _error › dev mode › should render index page normal

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello from index"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack.js?ts=1591703783333\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/development/pages/_app.js?ts=1591703783333\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main.js?ts=1591703783333\" as=\"script\"/><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/runtime/react-refresh.js?ts=1591703783333\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ChunkRenderError\",\"message\":\"Conflict: Multiple chunks emit assets to the same filename static/development/pages/_error.js (chunks static/BUILD_ID/pages/_error.js and static/development/pages/_error.js)\",\"stack\":\"ChunkRenderError: Conflict: Multiple chunks emit assets to the same filename static/development/pages/_error.js (chunks static/BUILD_ID/pages/_error.js and static/development/pages/_error.js)\\n    at Compilation.createChunkAssets (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:2202:6)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1397:10\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/next.js/next.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), \\u003canonymous\\u003e:4:1)\\n    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/next.js/next.js/node_modules/tapable/lib/Hook.js:154:20)\\n    at Compilation.seal (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1342:27)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compiler.js:675:18\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1261:4\\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/runner/work/next.js/next.js/node_modules/tapable/lib/HookCodeFactory.js:33:10), \\u003canonymous\\u003e:13:1)\\n    at AsyncSeriesHook.lazyCompileHook (/home/runner/work/next.js/next.js/node_modules/tapable/lib/Hook.js:154:20)\\n    at Compilation.finish (/home/runner/work/next.js/next.js/node_modules/webpack/lib/Compilation.js:1253:28)\"},\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills.js?ts=1591703783333\"></script><script src=\"/_next/static/runtime/webpack.js?ts=1591703783333\" async=\"\"></script><script src=\"/_next/static/development/pages/_app.js?ts=1591703783333\" async=\"\"></script><script src=\"/_next/static/runtime/main.js?ts=1591703783333\" async=\"\"></script><script src=\"/_next/static/development/_buildManifest.js? [...]

2020-06-09 11:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.5s | ⚠️ +185ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +1.18 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.115 | 2.175 | ⚠️ +0.06 |
| / avg req/sec | 1182.31 | 1149.31 | -33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.387 | 1.34 | -0.05 |
| /error-in-render avg req/sec | 1802.83 | 1865.67 | ⚠️ +62.84 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.ht [...]

2020-06-09 12:15 UTC, ijjk commented
## Failing test suites <!--775555081-->

**test/integration/api-support/test/index.test.js** 
- API routes > Server support > should return data on dynamic optional nested route
- API routes > dev support > should return data on dynamic optional nested route

<details>
<summary>Expand output</summary>

  ● API routes › dev support › should return data on dynamic optional nested route

    expect(received).toEqual(expected) // deep equality

    Expected: {"id": "1", "post": "post-1"}
    Received: false

      346 |     ).then((res) => res.ok && res.json())
      347 | 
    > 348 |     expect(data).toEqual({ post: 'post-1', id: '1' })
          |                  ^
      349 |   })
      350 | 
      351 |   it('should work with child_process correctly', async () => {

      at Object.<anonymous> (integration/api-support/test/index.test.js:348:18)

  ● API routes › Server support › should return data on dynamic optional nested route

    expect(received).toEqual(expected) // deep equality

    Expected: {"id": "1", "post": "post-1"}
    Received: false

      346 |     ).then((res) => res.ok && res.json())
      347 | 
    > 348 |     expect(data).toEqual({ post: 'post-1', id: '1' })
          |                  ^
      349 |   })
      350 | 
      351 |   it('should work with child_process correctly', async () => {

      at Object.<anonymous> (integration/api-support/test/index.test.js:348:18)

</details>

2020-06-09 12:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.5s | ⚠️ +80ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +695 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.336 | 2.308 | -0.03 |
| / avg req/sec | 1070.21 | 1083.04 | ⚠️ +12.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.509 | 1.452 | -0.06 |
| /error-in-render avg req/sec | 1656.77 | 1721.52 | ⚠️ +64.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.h [...]

2020-06-09 12:52 UTC, ijjk commented
## Failing test suites <!--775693945-->

**test/integration/custom-routes-catchall/test/index.test.js** 
- Custom routes > production mode > should rewrite to /_next/static correctly

<details>
<summary>Expand output</summary>

  ● Custom routes › production mode › should rewrite to /_next/static correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello from hello.js"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"3\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/commons.ce3be78d7938f807ddbb.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/6d60c78382255190d079/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main-8ff26abc5efa3c374854.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>body { margin: 0 }</style><h1 style=\"display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top\">404</h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">This page could not be found<!-- -->.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"zZzww-VF03fkAxUl9opOw\",\"nextExport\":true,\"isFallback\":false,\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-c347cb6f295444888ea6.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" async=\"\"></script><script src=\"/_next/static/chunks/commons.ce3be78d7938f807ddbb.js\" async=\"\"></script><script src=\"/_next/static/6d60c78382255190d079/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-8ff26abc5efa3c374854.js\" async=\"\"></script><script src=\"/_next/static/zZzww-VF03fkAxUl9opOw/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/zZzww-VF03fkAxUl9opOw/_ssgManifest.js\" async=\"\"></script></body></html>"

      30 |     )
      31 |     const data = await renderViaHTTP(appPort, bundlePath)
    > 32 |     expect(data).toContain('hello from hello.js')
         |                  ^
      33 |   })
      34 | 
      35 |   it('should rewrite and render page correctly', async () => {

      at Object.<anonymous> (integration/custom-routes-catchall/test/index.test.js:32:18)

</details>

2020-06-09 12:52 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.3s | -214ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | ⚠️ +759 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.923 | 1.847 | -0.08 |
| / avg req/sec | 1300.13 | 1353.82 | ⚠️ +53.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.17 | 1.125 | -0.04 |
| /error-in-render avg req/sec | 2136.18 | 2222.96 | ⚠️ +86.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html [...]

2020-06-09 14:21 UTC, ijjk commented
## Failing test suites <!--776092666-->

**test/integration/custom-routes-catchall/test/index.test.js** 
- Custom routes > production mode > should rewrite to /_next/static correctly

<details>
<summary>Expand output</summary>

  ● Custom routes › production mode › should rewrite to /_next/static correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello from hello.js"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"3\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/commons.ce3be78d7938f807ddbb.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/6d60c78382255190d079/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main-8ff26abc5efa3c374854.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>body { margin: 0 }</style><h1 style=\"display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top\">404</h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">This page could not be found<!-- -->.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"4e97yQ_Dc9xWXFAKqf9DO\",\"nextExport\":true,\"isFallback\":false,\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-c347cb6f295444888ea6.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.d6bb50426bc40cdcacde.js\" async=\"\"></script><script src=\"/_next/static/chunks/commons.ce3be78d7938f807ddbb.js\" async=\"\"></script><script src=\"/_next/static/6d60c78382255190d079/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-8ff26abc5efa3c374854.js\" async=\"\"></script><script src=\"/_next/static/4e97yQ_Dc9xWXFAKqf9DO/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/4e97yQ_Dc9xWXFAKqf9DO/_ssgManifest.js\" async=\"\"></script></body></html>"

      30 |     )
      31 |     const data = await renderViaHTTP(appPort, bundlePath)
    > 32 |     expect(data).toContain('hello from hello.js')
         |                  ^
      33 |   })
      34 | 
      35 |   it('should rewrite and render page correctly', async () => {

      at Object.<anonymous> (integration/custom-routes-catchall/test/index.test.js:32:18)

</details>

2020-06-09 14:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13s | -206ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.161 | 2.225 | ⚠️ +0.06 |
| / avg req/sec | 1156.79 | 1123.73 | -33.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.544 | 1.454 | -0.09 |
| /error-in-render avg req/sec | 1619.11 | 1719.18 | ⚠️ +100.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</ [...]

2020-06-09 16:07 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 10.8s | 11.6s | ⚠️ +771ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.811 | 1.869 | ⚠️ +0.06 |
| / avg req/sec | 1380.25 | 1337.59 | -42.66 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.052 | 1.069 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2375.79 | 2337.98 | -37.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.h [...]

2020-06-09 16:10 UTC, ijjk commented
## Failing test suites <!--776606445-->

**test/integration/custom-routes/test/index.test.js** 
- Custom routes > server mode > should match /_next file after rewrite
- Custom routes > serverless mode > should match /_next file after rewrite

<details>
<summary>Expand output</summary>

  ● Custom routes › server mode › should match /_next file after rewrite

    expect(received).toContain(expected) // indexOf

    Expected substring: "Hello"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"3\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/framework.6c1ee01da8e490b7ed87.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/f91a559473e44da845deb759750b8a9ce082113b.b039c804546338d80c2f.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/46a6d0144eb32de56141/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main-852e1cd26317ec26686f.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>body { margin: 0 }</style><h1 style=\"display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top\">404</h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">This page could not be found<!-- -->.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"tG_I00ckc6a-gUQMKOUqZ\",\"nextExport\":true,\"isFallback\":false,\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-31f3323beae1fd78b18b.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.6c1ee01da8e490b7ed87.js\" async=\"\"></script><script src=\"/_next/static/chunks/f91a559473e44da845deb759750b8a9ce082113b.b039c804546338d80c2f.js\" async=\"\"></script><script src=\"/_next/static/46a6d0144eb32de56141/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-852e1cd26317ec26686f.js\" async=\"\"></script><script src=\"/_next/static/tG_I00ckc6a-gUQMKOUqZ/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/tG_I00ckc6a-gUQMKOUqZ/_ssgManifest.js\" async=\"\"></script></body></html>"

      306 |       `/hidden/_next/static/${buildId}/pages/hello.js`
      307 |     )
    > 308 |     expect(data).toContain('Hello')
          |                  ^
      309 |     expect(data).toContain('createElement')
      310 |   })
      311 | 

      at Object.<anonymous> (integration/custom-routes/test/index.test.js:308:18)
          at runMicrotasks (<anonymous>)

  ● Custom routes › serverless mode › should match /_next file after rewrite

    expect(received).toContain(expected) // indexOf

    Expected substring: "Hello"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"3\"/><link rel=\"preload\" href=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/framework.6c1ee01da8e490b7ed87.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/f91a559473e44da845deb759750b8a9ce082113b.b039c804546338d80c2f.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/46a6d0144eb32de56141/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/runtime/main-852e1cd26317ec26686f.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"color:#000;background:#fff;font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>body { margin: 0 }</style><h1 style=\"display:inline-block;border-right:1px solid rgba(0, 0, 0,.3);margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top\">404</h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">This page could not be found<!-- -->.</h2></div></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"rkXuBXuMqFmsmLL_tH5j8\",\"runtimeConfig\":{},\"nextExport\":true,\"isFallback\":false,\"gip\":true}</script><script nomodule=\"\" src=\"/_next/static/runtime/polyfills-31f3323beae1fd78b18b.js\"></script><script src=\"/_next/static/runtime/webpack-c212667a5f965e81e004.js\" async=\"\"></script><script src=\"/_next/static/chunks/framework.6c1ee01da8e490b7ed87.js\" async=\"\"></script><script src=\"/_next/static/chunks/f91a559473e44da845deb759750b8a9ce082113b.b039c804546338d80c2f.js\" async=\"\"></script><script src=\"/_next/static/46a6d0144eb32de56141/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/runtime/main-852e1cd26317ec26686f.js\" async=\"\"></script><script src=\"/_next/static/rkXuBXuMqFmsmLL_tH5j8/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/rkXuBXuMqFmsmLL_tH5j8/_ssgManifest.js\" async=\"\"></script></body></html>"

      306 |       `/hidden/_next/static/${buildId}/pages/hello.js`
      307 |     )
    > 308 |     expect(data).toContain('Hello')
          |                  ^
      309 |     expect(data).toContain('createElement')
      310 |   })
      311 | 

      at Object.<anonymous> (integration/custom-routes/test/index.test.js:308:18)
          at runMicrotasks (<anonymous>)

</details>

2020-06-09 18:12 UTC, ijjk commented
## Failing test suites <!--777113249-->

**test/integration/modern-mode/test/index.test.js** 
- Modern Mode > should generate client side modern and legacy build files

<details>
<summary>Expand output</summary>

  ● Modern Mode › should generate client side modern and legacy build files

    ENOENT: no such file or directory, scandir '/home/runner/work/next.js/next.js/test/integration/modern-mode/.next/static/70eWreLKno0tF6dgyi_l4/pages'

      43 |     const expectedFiles = ['index', '_app', '_error', 'main', 'webpack']
      44 |     const buildFiles = [
    > 45 |       ...readdirSync(join(appDir, '.next/static', buildId, 'pages')),
         |          ^
      46 |       ...readdirSync(join(appDir, '.next/static/runtime')).map(
      47 |         (file) => file.replace(/-\w+\./, '.') // remove hash
      48 |       ),

      at Object.<anonymous> (integration/modern-mode/test/index.test.js:45:10)

</details>

2020-06-09 18:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 14.1s | 11.6s | -2.5s |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.487 | 1.923 | -0.56 |
| / avg req/sec | 1005.3 | 1299.87 | ⚠️ +294.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.431 | 1.137 | -0.29 |
| /error-in-render avg req/sec | 1747.56 | 2199.4 | ⚠️ +451.84 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</ [...]

2020-06-09 20:28 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 10.6s | 11.7s | ⚠️ +1.1s |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.776 | 1.952 | ⚠️ +0.18 |
| / avg req/sec | 1408.01 | 1280.72 | -127.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.049 | 1.099 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 2383.96 | 2275.62 | -108.34 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link. [...]

2020-06-09 20:28 UTC, ijjk commented
## Failing test suites <!--777644253-->

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from red to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from blue to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from red to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from blue to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      272 | export async function killApp(instance) {
      273 |   await new Promise((resolve, reject) => {
    > 274 |     treeKill(instance.pid, (err) => {
          |                       ^
      275 |       if (err) {
      276 |         if (
      277 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:274:23
      at killApp (lib/next-test-utils.js:273:9)
      at integration/css-client-nav/test/index.test.js:34:11

  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      272 | export async function killApp(instance) {
      273 |   await new Promise((resolve, reject) => {
    > 274 |     treeKill(instance.pid, (err) => {
          |                       ^
      275 |       if (err) {
      276 |         if (
      277 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:274:23
      at killApp (lib/next-test-utils.js:273:9)
      at integration/css-client-nav/test/index.test.js:190:11

</details>

2020-06-09 20:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.4s | -254ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.13 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.169 | 2.195 | ⚠️ +0.03 |
| / avg req/sec | 1152.77 | 1139.04 | -13.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.432 | 1.403 | -0.03 |
| /error-in-render avg req/sec | 1745.94 | 1781.44 | ⚠️ +35.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..ec24.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.92 kB | 6.92 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 901 B | 959 B | ⚠️ +58 B |
| link.html gzip | 906 B | 965 B | ⚠️ +59 B |
| withRouter.html gzip | 894 B | 951 B | ⚠️ +57 B |
| Overall change | 2.7 kB | 2.88 kB | ⚠️ +174 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -24,7 +24,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -36,7 +36,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -117,13 +117,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
@@ -141,13 +141,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</ [...]

2020-06-09 20:41 UTC, ijjk commented
## Failing test suites <!--777684729-->

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production (Modern) > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from red to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from blue to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from red to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from blue to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to red

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)

  ● CSS Module client-side navigation in Production (Modern) › should be able to client-side navigate from none to blue

    command failed with code 1

      133 |         code !== 0
      134 |       ) {
    > 135 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      136 |       }
      137 | 
      138 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:135:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      272 | export async function killApp(instance) {
      273 |   await new Promise((resolve, reject) => {
    > 274 |     treeKill(instance.pid, (err) => {
          |                       ^
      275 |       if (err) {
      276 |         if (
      277 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:274:23
      at killApp (lib/next-test-utils.js:273:9)
      at integration/css-client-nav/test/index.test.js:34:11

  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      272 | export async function killApp(instance) {
      273 |   await new Promise((resolve, reject) => {
    > 274 |     treeKill(instance.pid, (err) => {
          |                       ^
      275 |       if (err) {
      276 |         if (
      277 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:274:23
      at killApp (lib/next-test-utils.js:273:9)
      at integration/css-client-nav/test/index.test.js:190:11

</details>

2020-06-10 08:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.2s | -211ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -895 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.255 | 2.222 | -0.03 |
| / avg req/sec | 1108.87 | 1125.1 | ⚠️ +16.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.477 | 1.458 | -0.02 |
| /error-in-render avg req/sec | 1692.68 | 1714.75 | ⚠️ +22.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b11.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.26 kB | 7.26 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 895 B | 954 B | ⚠️ +59 B |
| link.html gzip | 901 B | 961 B | ⚠️ +60 B |
| withRouter.html gzip | 888 B | 948 B | ⚠️ +60 B |
| Overall change | 2.68 kB | 2.86 kB | ⚠️ +179 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -129,25 +129,25 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
   [...]

2020-06-10 08:58 UTC, ijjk commented
## Failing test suites <!--779674734-->

**test/integration/typeof-window-replace/test/index.test.js** 
- typeof window replace > Replaces `typeof window` with object for client code
- typeof window replace > Does not replace `typeof window` for `node_modules` code

<details>
<summary>Expand output</summary>

  ● typeof window replace › Replaces `typeof window` with object for client code

    ENOENT: no such file or directory, open '/home/runner/work/next.js/next.js/test/integration/typeof-window-replace/app/.next/static/_0gZqs_JQJ1eAcTDAeU8n/pages/index.js'



  ● typeof window replace › Does not replace `typeof window` for `node_modules` code

    ENOENT: no such file or directory, open '/home/runner/work/next.js/next.js/test/integration/typeof-window-replace/app/.next/static/_0gZqs_JQJ1eAcTDAeU8n/pages/index.js'



</details>

2020-06-10 09:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.1s | -317ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -895 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.869 | 1.857 | -0.01 |
| / avg req/sec | 1337.41 | 1346.37 | ⚠️ +8.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.076 | 1.073 | 0 |
| /error-in-render avg req/sec | 2323.91 | 2329.19 | ⚠️ +5.28 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b11.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.26 kB | 7.26 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 895 B | 954 B | ⚠️ +59 B |
| link.html gzip | 901 B | 961 B | ⚠️ +60 B |
| withRouter.html gzip | 888 B | 948 B | ⚠️ +60 B |
| Overall change | 2.68 kB | 2.86 kB | ⚠️ +179 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -129,25 +129,25 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
        [...]

2020-06-10 09:09 UTC, ijjk commented
## Failing test suites <!--779722450-->

**test/integration/serverless-trace/test/index.test.js** 
- Serverless Trace > should not have combined client-side chunks

<details>
<summary>Expand output</summary>

  ● Serverless Trace › should not have combined client-side chunks

    ENOENT: no such file or directory, open '/home/runner/work/next.js/next.js/test/integration/serverless-trace/.next/static/oNCEtVaCmMtddm9S53kqm/pages/dynamic.js'

      116 |       'pages/dynamic.js'
      117 |     )
    > 118 |     expect(readFileSync(pageContent, 'utf8')).not.toContain('Hello!')
          |            ^
      119 |   })
      120 | 
      121 |   it('should not output _app.js and _document.js to serverless build', () => {

      at Object.<anonymous> (integration/serverless-trace/test/index.test.js:118:12)

</details>

2020-06-10 10:01 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.9s | ⚠️ +333ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -895 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.975 | 1.98 | 0 |
| / avg req/sec | 1265.54 | 1262.78 | -2.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.308 | 1.34 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1911.93 | 1866.34 | -45.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b11.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.26 kB | 7.26 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 895 B | 954 B | ⚠️ +59 B |
| link.html gzip | 901 B | 961 B | ⚠️ +60 B |
| withRouter.html gzip | 888 B | 948 B | ⚠️ +60 B |
| Overall change | 2.68 kB | 2.86 kB | ⚠️ +179 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -129,25 +129,25 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
        [...]

2020-06-10 10:51 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 11.3s | 10.9s | -414ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.25 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.887 | 1.937 | ⚠️ +0.05 |
| / avg req/sec | 1324.77 | 1290.45 | -34.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.335 | 1.23 | -0.1 |
| /error-in-render avg req/sec | 1872.03 | 2032 | ⚠️ +159.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b11.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.26 kB | 7.26 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 895 B | 954 B | ⚠️ +59 B |
| link.html gzip | 901 B | 961 B | ⚠️ +60 B |
| withRouter.html gzip | 888 B | 948 B | ⚠️ +60 B |
| Overall change | 2.68 kB | 2.86 kB | ⚠️ +179 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -129,25 +129,25 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
    [...]

2020-06-10 10:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.8s | ⚠️ +178ms |
| nodeModulesSize | 64.9 MB | 64.9 MB | -1.01 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.164 | 2.162 | 0 |
| / avg req/sec | 1155.24 | 1156.37 | ⚠️ +1.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.465 | 1.408 | -0.06 |
| /error-in-render avg req/sec | 1706.34 | 1775.52 | ⚠️ +69.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.49 kB | 6.49 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b11.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.58 kB | 5.58 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 7.26 kB | 7.26 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.js gzip | 1.26 kB | N/A | N/A |
| _error.js gzip | 3.25 kB | N/A | N/A |
| hooks.js gzip | 881 B | 881 B | ✓ |
| index.js gzip | 222 B | N/A | N/A |
| link.js gzip | 2.05 kB | N/A | N/A |
| routerDirect.js gzip | 279 B | N/A | N/A |
| withRouter.js gzip | 278 B | N/A | N/A |
| Overall change | 8.22 kB | 881 B | -7.34 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _app.module.js gzip | 604 B | N/A | N/A |
| _error.module.js gzip | 2.04 kB | N/A | N/A |
| hooks.module.js gzip | 383 B | N/A | N/A |
| index.module.js gzip | 223 B | N/A | N/A |
| link.module.js gzip | 1.52 kB | N/A | N/A |
| routerDirect..dule.js gzip | 281 B | N/A | N/A |
| withRouter.m..dule.js gzip | 278 B | N/A | N/A |
| Overall change | 5.33 kB | 0 B | -5.33 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| _buildManifest.js gzip | 171 B | 270 B | ⚠️ +99 B |
| _buildManife..dule.js gzip | 180 B | 275 B | ⚠️ +95 B |
| Overall change | 351 B | 545 B | ⚠️ +194 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/use-chunkhash-for-browser-page-file | Change |
| - | - | - | - |
| index.html gzip | 895 B | 954 B | ⚠️ +59 B |
| link.html gzip | 901 B | 961 B | ⚠️ +60 B |
| withRouter.html gzip | 888 B | 948 B | ⚠️ +60 B |
| Overall change | 2.68 kB | 2.86 kB | ⚠️ +179 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,9 +1,13 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.js"],
-  "/routerDirect": ["static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.js"],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.js"]
+  "/": ["static\u002F8f6ec52978e4ed685749\u002Fpages\u002Findex.js"],
+  "/_error": ["static\u002F0dd45ce0aa0f4454606b\u002Fpages\u002F_error.js"],
+  "/hooks": ["static\u002F701db499b372d8b4ad8a\u002Fpages\u002Fhooks.js"],
+  "/link": ["static\u002Fe826d21ad4f09aa9e68e\u002Fpages\u002Flink.js"],
+  "/routerDirect": [
+    "static\u002F70609b58a7b84ec58870\u002Fpages\u002FrouterDirect.js"
+  ],
+  "/withRouter": [
+    "static\u002F216d6fd4cf8ffe57dc0c\u002Fpages\u002FwithRouter.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,11 +1,17 @@
 self.__BUILD_MANIFEST = {
-  "/": ["static\u002FBUILD_ID\u002Fpages\u002Findex.module.js"],
-  "/_error": ["static\u002FBUILD_ID\u002Fpages\u002F_error.module.js"],
-  "/hooks": ["static\u002FBUILD_ID\u002Fpages\u002Fhooks.module.js"],
-  "/link": ["static\u002FBUILD_ID\u002Fpages\u002Flink.module.js"],
+  "/": ["static\u002F617084c2156e7a4c3a6e\u002Fpages\u002Findex.module.js"],
+  "/_error": [
+    "static\u002F044e777feb8a752b7656\u002Fpages\u002F_error.module.js"
+  ],
+  "/hooks": [
+    "static\u002F680ac2d033b0bc870c3a\u002Fpages\u002Fhooks.module.js"
+  ],
+  "/link": ["static\u002Fd5a70ed72905d882658f\u002Fpages\u002Flink.module.js"],
   "/routerDirect": [
-    "static\u002FBUILD_ID\u002Fpages\u002FrouterDirect.module.js"
+    "static\u002Ff4884873d5a5d6e895c1\u002Fpages\u002FrouterDirect.module.js"
   ],
-  "/withRouter": ["static\u002FBUILD_ID\u002Fpages\u002FwithRouter.module.js"]
+  "/withRouter": [
+    "static\u002F0154f653f0641299a259\u002Fpages\u002FwithRouter.module.js"
+  ]
 };
 self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/_app.module.js"
+      href="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       as="script"
       crossorigin="anonymous"
     />
     <link
       rel="preload"
-      href="/_next/static/BUILD_ID/pages/index.module.js"
+      href="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -129,25 +129,25 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.js"
+      src="/_next/static/2d534c4cbe6457a78b96/pages/_app.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/_app.module.js"
+      src="/_next/static/9f6eca2066ca23127bda/pages/_app.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.js"
+      src="/_next/static/8f6ec52978e4ed685749/pages/index.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/BUILD_ID/pages/index.module.js"
+      src="/_next/static/617084c2156e7a4c3a6e/pages/index.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -30,13 +30,13 @@
     />
     <link
  [...]

2020-06-10 13:36 UTC, Timer requested changes
I don't see a test added for https://github.com/vercel/next.js/issues/13970 or https://github.com/vercel/next.js/issues/13986

2020-06-10 17:30 UTC, Timer approved these changes

2020-06-10 17:37 UTC, ijjk approved these changes

2020-06-11 08:57 UTC, merged