Make ReactDevOverlay reducer more resilient to bad events
vercel/next.js pull request #14112
Opened 2020-06-12 04:14 UTC by mohsen1

I got the following stack and thought the error presenter should not throw so easily 

<details>
```
[example-server] TypeError: Cannot read property 'type' of undefined
[example-server]     at reducer (/Users/mohsen_azimi/Code/nice-commander/node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:51:16)
[example-server]     at Object.useReducer (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:1170:22)
[example-server]     at Object.useReducer (/Users/mohsen_azimi/Code/nice-commander/node_modules/react/cjs/react.development.js:1501:21)
[example-server]     at ReactDevOverlay (/Users/mohsen_azimi/Code/nice-commander/node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:74:27)
[example-server]     at finishHooks (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:1075:16)
[example-server]     at processChild (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:3044:14)
[example-server]     at resolve (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
[example-server]     at ReactDOMServerRenderer.render (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
[example-server]     at ReactDOMServerRenderer.read (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
[example-server]     at renderToString (/Users/mohsen_azimi/Code/nice-commander/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
[example-server]     at render (/Users/mohsen_azimi/Code/nice-commander/node_modules/next/dist/next-server/server/render.js:3:298)
[example-server]     at renderPageError (/Users/mohsen_azimi/Code/nice-commander/node_modules/next/dist/next-server/server/render.js:46:516)
[example-server]     at Object.renderPage (/Users/mohsen_azimi/Code/nice-commander/node_modules/next/dist/next-server/server/render.js:46:869)
[example-server]     at Function.getInitialProps (webpack-internal:///../../node_modules/next/dist/pages/_document.js:133:19)
[example-server]     at loadGetInitialProps (/Users/mohsen_azimi/Code/nice-commander/node_modules/next/dist/next-server/lib/utils.js:5:101)
[example-server]     at renderToHTML (/Users/mohsen_azimi/Code/nice-commander/node_modules/next/dist/next-server/server/render.js:46:1330)
```

</details>

if you are wondering how this can happen, this issue is reproducible here:

https://github.com/mohsen1/nice-commander/tree/1995cce6b858204c4a7ebcd76d9cacb2f4c1ae6b

2020-06-12 04:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.7s | -195ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.837 | 1.894 | ⚠️ +0.06 |
| / avg req/sec | 1360.84 | 1320 | -40.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.046 | 1.085 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2390.25 | 2305.2 | -85.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| index.html gzip | 957 B | 957 B | ✓ |
| link.html gzip | 963 B | 963 B | ✓ |
| withRouter.html gzip | 951 B | 951 B | ✓ |
| Overall change | 2.87 kB | 2.87 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| buildDuration | 11.7s | 12.1s | ⚠️ +389ms |
| nodeModulesSize | 65.2 MB | 65.2 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.51 kB | 6.51 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..0538.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.6 kB | 5.6 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..dule.js gzip | 6.93 kB | 6.93 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.3 kB | 26.3 kB | ✓ |
| Overall change | 26.3 kB | 26.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| routerDirect.js gzip | 279 B | 279 B | ✓ |
| withRouter.js gzip | 278 B | 278 B | ✓ |
| _error.js gzip | 3.37 kB | 3.37 kB | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.05 kB | 2.05 kB | ✓ |
| hooks.js gzip | 881 B | 881 B | ✓ |
| _app.js gzip | 1.26 kB | 1.26 kB | ✓ |
| Overall change | 8.34 kB | 8.34 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| index.module.js gzip | 223 B | 223 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| hooks.module.js gzip | 383 B | 383 B | ✓ |
| _error.module.js gzip | 2.21 kB | 2.21 kB | ✓ |
| link.module.js gzip | 1.52 kB | 1.52 kB | ✓ |
| _app.module.js gzip | 604 B | 604 B | ✓ |
| Overall change | 5.49 kB | 5.49 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 270 B | 270 B | ✓ |
| _buildManife..dule.js gzip | 274 B | 274 B | ✓ |
| Overall change | 544 B | 544 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | mohsen1/next.js patch-2 | Change |
| - | - | - | - |
| _error.js | 875 kB | 875 kB | ✓ |
| 404.html | 4.17 kB | 4.17 kB | ✓ |
| hooks.html | 3.79 kB | 3.79 kB | ✓ |
| index.js | 875 kB | 875 kB | ✓ |
| link.js | 913 kB | 913 kB | ✓ |
| routerDirect.js | 905 kB | 905 kB | ✓ |
| withRouter.js | 905 kB | 905 kB | ✓ |
| Overall change | 4.48 MB | 4.48 MB | ✓ |

</details>

</details>

2020-06-12 15:19 UTC, Timer requested changes
Blocking this as it should be an impossible state. We need to figure out what is sending a null event.

2020-06-12 15:57 UTC, mohsen1 commented
Since opening this PR I figured issue was a function in render that was throwing. The `pretty-bytes` package throws on null input

2020-06-12 16:11 UTC, Timer commented
I cannot reproduce it with the project you provided.

All I get is this:
![image](https://user-images.githubusercontent.com/616428/84523186-e6347400-aca5-11ea-9a72-b46a1b0722de.png)

2020-06-12 17:34 UTC, mohsen1 commented
@Timer you will need a MySQL database and AWS account with CloudWatch Logs access to build my project. I tried reducing it to a very small Next.js app but can't reproduce it in isolation.

Maybe it has to do with Next being used as a middleware?

2020-06-12 17:47 UTC, Timer commented
Not sure! But you'll need to figure out a minimal reproducing case that we can run please.

2020-06-17 20:08 UTC, Timer commented
Closing as there's no reproduction. Please open an issue with a reproduction and we can get this fixed. Thanks!

2020-06-17 20:08 UTC, closed without merging

2020-06-17 21:18 UTC, mohsen1 commented
I tried a bit but can't narrow it down. Unless you setup MySQL and AWS you can't run my project. I resolved my issue. If I run into it again I will try to reproduce it.

2020-06-18 09:56 UTC, timneutkens commented
Thanks @mohsen1!

2020-06-30 07:04 UTC, mauricekleine commented
@mohsen1 how did you end up resolving it? I'm running into a similar issue:

```
TypeError: Cannot read property 'type' of undefined
    at reducer (/Users/maurice-pb/Projects/tinnies/node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:51:16)
    at Object.useReducer (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:1170:22)
    at Object.useReducer (/Users/maurice-pb/Projects/tinnies/node_modules/react/cjs/react.development.js:1501:21)
    at ReactDevOverlay (/Users/maurice-pb/Projects/tinnies/node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:74:27)
    at finishHooks (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:1075:16)
    at processChild (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:3044:14)
    at resolve (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/maurice-pb/Projects/tinnies/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/maurice-pb/Projects/tinnies/node_modules/next/dist/next-server/server/render.js:3:298)
    at renderPageError (/Users/maurice-pb/Projects/tinnies/node_modules/next/dist/next-server/server/render.js:46:516)
    at Object.renderPage (/Users/maurice-pb/Projects/tinnies/node_modules/next/dist/next-server/server/render.js:46:869)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:133:19)
    at loadGetInitialProps (/Users/maurice-pb/Projects/tinnies/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/maurice-pb/Projects/tinnies/node_modules/next/dist/next-server/server/render.js:46:1330)
```

It started happening after I added Apollo GraphQL to my Next.js app

2020-06-30 13:08 UTC, Timer commented
@mauricekleine can you please share a full reproduction?

2020-06-30 13:30 UTC, mauricekleine commented
@Timer I'll try later, short on time right now. For now, I figured out what my problem was. I had this code in my `_app.tsx`:

```ts
...
import ApolloClient, { InMemoryCache, gql } from "apollo-boost";
import withApollo from "next-with-apollo";
...

export default withApollo(({ initialState }) => {
  return new ApolloClient({
    request: (operation) => {
      const token = localStorage.getItem("token");

      operation.setContext({
        headers: {
          authorization: token ? `Bearer ${token}` : "",
        },
      });
    },
    resolvers: {},
    typeDefs: gql`
      extend type Query {
        isLoggedIn: Boolean!
      }
    `,
    uri: "http://localhost:3000/api/graphql",
  });
})(App);
```

After changing the `request` function ⬇️  it worked again:

```ts
    request: (operation) => {
      if (process.browser) {
        const token = localStorage.getItem("token");

        operation.setContext({
          headers: {
            authorization: token ? `Bearer ${token}` : "",
          },
        });
      }
    },
```

Hopefully that helps to pinpoint the issue already. I'll try to create a reproduction later today. Thanks for looking into this!