Upgrading babel packages to get better tree shaking with react
vercel/next.js pull request #14981
Opened 2020-07-08 14:29 UTC by Bjodol

## Why?
As part of [babel 7.10.0](https://babeljs.io/blog/2020/05/25/7.10.0#better-tree-shaking-for-react-components-11428-https-githubcom-babel-babel-pull-11428) tree-shaking for react has become way better. Among the changes is removal of react pure functions such as `React.forwardRef` and `React.memo`. This will in cases where bigger component libraries are potentially reduce the initial bundle-size quite significantly. You could always ask, why not just import the things you need? Well in my case an internal design system is bundled as one package and restructuring it to smaller bundles is currently not prioritized. So by having better tree-shaking it would solve the problem downstream instead of upstream.

## What
- Simply made changes to babel version numbers for the nextjs package and the core repository. 
- Noteworthy: In the core repository I changed the package from `babel-core` to `@babel/core`

As this is my first time submission I hope everything is up to standards and will take any input provided :)

2020-07-08 14:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| buildDuration | 12.4s | 11.9s | -502ms |
| nodeModulesSize | 65.9 MB | 65.1 MB | -802 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.264 | 2.098 | -0.17 |
| / avg req/sec | 1104.3 | 1191.8 | +87.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.463 | 1.33 | -0.13 |
| /error-in-render avg req/sec | 1708.82 | 1879.22 | +170.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.62 kB | -8 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..c646.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | -10 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 267 B | -1 B |
| _buildManife..dule.js gzip | 272 B | 274 B | ⚠️ +2 B |
| Overall change | 540 B | 541 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| index.html gzip | 954 B | 953 B | -1 B |
| link.html gzip | 960 B | 960 B | ✓ |
| withRouter.html gzip | 946 B | 944 B | -2 B |
| Overall change | 2.86 kB | 2.86 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-f35cd1774d910f5523ed.js"],
-  "/_error": ["static\u002Fpages\u002F_error-f39e6723c6acde17325a.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b5c3e8d3fd7cb18089e0.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-9e216cd51bf04b309e08.js"],
-  "/link": ["static\u002Fpages\u002Flink-d0cd3d2b80934d6c003a.js"],
+  "/link": ["static\u002Fpages\u002Flink-9cbc3acb75186d5885ae.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-b95d3f54c75949a43da6.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-da343bca3b67f1bcf42d.module.js"],
-  "/_error": ["static\u002Fpages\u002F_error-b3c4c3f8dbb1417657e6.module.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b51f16b902f3e71973eb.module.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-dc8f274035a2839a1e61.module.js"],
-  "/link": ["static\u002Fpages\u002Flink-5a10d6c964f4c88363cd.module.js"],
+  "/link": ["static\u002Fpages\u002Flink-a90c99c9a9ddaa07df87.module.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-c62f258dff7fece0a732.module.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..73.module.js</strong></summary>

```diff
@@ -1931,7 +1931,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react.default.createContext(null);
+      var RouterContext = /*#__PURE__*/ _react.default.createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..d0645a966.js</strong></summary>

```diff
@@ -3184,7 +3184,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react["default"].createContext(null);
+      var RouterContext = /*#__PURE__*/ _react["default"].createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -178,7 +178,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             };
       }
 
-      var HeadManagerContext = _react["default"].createContext({});
+      var HeadManagerContext = /*#__PURE__*/ _react["default"].createContext(
+        {}
+      );
 
       exports.HeadManagerContext = HeadManagerContext;
 
@@ -402,7 +404,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                     "?" +
                     (0, _querystring.stringify)(
                       (0, _extends2["default"])(
-                        (0, _extends2["default"])({}, router.query),
+                        {},
+                        router.query,
                         (0, _querystring.parse)(location.search.substr(1))
                       )
                     ),
@@ -724,13 +727,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
                       _context2.next = 14;
                       return renderError(
-                        (0, _extends2["default"])(
-                          (0, _extends2["default"])({}, renderingProps),
-                          {},
-                          {
-                            err: _context2.t0
-                          }
-                        )
+                        (0, _extends2["default"])({}, renderingProps, {
+                          err: _context2.t0
+                        })
                       );
 
                     case 14:
@@ -784,15 +783,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               : (0, _utils.loadGetInitialProps)(App, appCtx)
           ).then(function(initProps) {
             return doRender(
-              (0, _extends2["default"])(
-                (0, _extends2["default"])({}, renderErrorProps),
-                {},
-                {
-                  err: err,
-                  Component: ErrorComponent,
-                  props: initProps
-                }
-              )
+              (0, _extends2["default"])({}, renderErrorProps, {
+                err: err,
+                Component: ErrorComponent,
+                props: initProps
+              })
             );
           });
         });
@@ -923,15 +918,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var wrapApp = function wrapApp(App) {
         return function(wrappedAppProps) {
-          var appProps = (0, _extends2["default"])(
-            (0, _extends2["default"])({}, wrappedAppProps),
-            {},
-            {
-              Component: CachedComponent,
-              err: hydrateErr,
-              router: router
-            }
-          );
+          var appProps = (0, _extends2["default"])({}, wrappedAppProps, {
+            Component: Cached [...]

2020-07-08 14:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| buildDuration | 13s | 13.3s | ⚠️ +290ms |
| nodeModulesSize | 65.9 MB | 65.1 MB | -802 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.256 | 2.228 | -0.03 |
| / avg req/sec | 1108.24 | 1122.26 | +14.02 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.529 | 1.528 | 0 |
| /error-in-render avg req/sec | 1634.89 | 1636.09 | +1.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.62 kB | -8 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..c646.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.71 kB | 5.71 kB | -10 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 267 B | -1 B |
| _buildManife..dule.js gzip | 272 B | 274 B | ⚠️ +2 B |
| Overall change | 540 B | 541 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| index.html gzip | 954 B | 953 B | -1 B |
| link.html gzip | 960 B | 960 B | ✓ |
| withRouter.html gzip | 946 B | 944 B | -2 B |
| Overall change | 2.86 kB | 2.86 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-f35cd1774d910f5523ed.js"],
-  "/_error": ["static\u002Fpages\u002F_error-f39e6723c6acde17325a.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b5c3e8d3fd7cb18089e0.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-9e216cd51bf04b309e08.js"],
-  "/link": ["static\u002Fpages\u002Flink-d0cd3d2b80934d6c003a.js"],
+  "/link": ["static\u002Fpages\u002Flink-9cbc3acb75186d5885ae.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-b95d3f54c75949a43da6.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-da343bca3b67f1bcf42d.module.js"],
-  "/_error": ["static\u002Fpages\u002F_error-b3c4c3f8dbb1417657e6.module.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b51f16b902f3e71973eb.module.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-dc8f274035a2839a1e61.module.js"],
-  "/link": ["static\u002Fpages\u002Flink-5a10d6c964f4c88363cd.module.js"],
+  "/link": ["static\u002Fpages\u002Flink-a90c99c9a9ddaa07df87.module.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-c62f258dff7fece0a732.module.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..73.module.js</strong></summary>

```diff
@@ -1931,7 +1931,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react.default.createContext(null);
+      var RouterContext = /*#__PURE__*/ _react.default.createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..d0645a966.js</strong></summary>

```diff
@@ -3184,7 +3184,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react["default"].createContext(null);
+      var RouterContext = /*#__PURE__*/ _react["default"].createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -178,7 +178,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             };
       }
 
-      var HeadManagerContext = _react["default"].createContext({});
+      var HeadManagerContext = /*#__PURE__*/ _react["default"].createContext(
+        {}
+      );
 
       exports.HeadManagerContext = HeadManagerContext;
 
@@ -402,7 +404,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                     "?" +
                     (0, _querystring.stringify)(
                       (0, _extends2["default"])(
-                        (0, _extends2["default"])({}, router.query),
+                        {},
+                        router.query,
                         (0, _querystring.parse)(location.search.substr(1))
                       )
                     ),
@@ -724,13 +727,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
                       _context2.next = 14;
                       return renderError(
-                        (0, _extends2["default"])(
-                          (0, _extends2["default"])({}, renderingProps),
-                          {},
-                          {
-                            err: _context2.t0
-                          }
-                        )
+                        (0, _extends2["default"])({}, renderingProps, {
+                          err: _context2.t0
+                        })
                       );
 
                     case 14:
@@ -784,15 +783,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               : (0, _utils.loadGetInitialProps)(App, appCtx)
           ).then(function(initProps) {
             return doRender(
-              (0, _extends2["default"])(
-                (0, _extends2["default"])({}, renderErrorProps),
-                {},
-                {
-                  err: err,
-                  Component: ErrorComponent,
-                  props: initProps
-                }
-              )
+              (0, _extends2["default"])({}, renderErrorProps, {
+                err: err,
+                Component: ErrorComponent,
+                props: initProps
+              })
             );
           });
         });
@@ -923,15 +918,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var wrapApp = function wrapApp(App) {
         return function(wrappedAppProps) {
-          var appProps = (0, _extends2["default"])(
-            (0, _extends2["default"])({}, wrappedAppProps),
-            {},
-            {
-              Component: CachedComponent,
-              err: hydrateErr,
-              router: router
-            }
-          );
+          var appProps = (0, _extends2["default"])({}, wrappedAppProps, {
+            Component: CachedC [...]

2020-07-08 14:45 UTC, ijjk commented
## Failing test suites <!--891293760-->
Commit: 808da4a06a3016046e3bbcc8de318f61dd23a205

**test/integration/styled-jsx-plugin/test/index.test.js** 
- styled-jsx using in node_modules > production mode > should serve a page correctly

<details>
<summary>Expand output</summary>

  ● styled-jsx using in node_modules › production mode › should serve a page correctly

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      25 | describe('styled-jsx using in node_modules', () => {
      26 |   describe('production mode', () => {
    > 27 |     beforeAll(async () => {
         |     ^
      28 |       const output = await nextBuild(appDir, undefined, {
      29 |         stdout: true,
      30 |         stderr: true,

      at integration/styled-jsx-plugin/test/index.test.js:27:5
      at integration/styled-jsx-plugin/test/index.test.js:26:3
      at Object.<anonymous> (integration/styled-jsx-plugin/test/index.test.js:25:1)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      271 | export async function killApp(instance) {
      272 |   await new Promise((resolve, reject) => {
    > 273 |     treeKill(instance.pid, (err) => {
          |                       ^
      274 |       if (err) {
      275 |         if (
      276 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:273:23
      at killApp (lib/next-test-utils.js:272:9)
      at integration/styled-jsx-plugin/test/index.test.js:39:20

</details>

2020-07-08 14:45 UTC, timneutkens approved these changes
The change looks good, however based on the description in the blog/release notes the improvements are likely not as big as you're expecting given that components are generally used. This change mostly helps when tree shaking certain cases.

2020-07-08 14:46 UTC, ijjk commented
## Failing test suites <!--891294974-->
Commit: 76e06a77d3b71d123922ebb426be5fd36abca91e

**test/integration/styled-jsx-plugin/test/index.test.js** 
- styled-jsx using in node_modules > production mode > should serve a page correctly

<details>
<summary>Expand output</summary>

  ● styled-jsx using in node_modules › production mode › should serve a page correctly

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      25 | describe('styled-jsx using in node_modules', () => {
      26 |   describe('production mode', () => {
    > 27 |     beforeAll(async () => {
         |     ^
      28 |       const output = await nextBuild(appDir, undefined, {
      29 |         stdout: true,
      30 |         stderr: true,

      at integration/styled-jsx-plugin/test/index.test.js:27:5
      at integration/styled-jsx-plugin/test/index.test.js:26:3
      at Object.<anonymous> (integration/styled-jsx-plugin/test/index.test.js:25:1)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      271 | export async function killApp(instance) {
      272 |   await new Promise((resolve, reject) => {
    > 273 |     treeKill(instance.pid, (err) => {
          |                       ^
      274 |       if (err) {
      275 |         if (
      276 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:273:23
      at killApp (lib/next-test-utils.js:272:9)
      at integration/styled-jsx-plugin/test/index.test.js:39:20

</details>

2020-07-08 15:18 UTC, timneutkens requested changes
Looks like one of the styled-jsx tests is failing

2020-07-09 06:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.3s | ⚠️ +444ms |
| nodeModulesSize | 66.1 MB | 65.3 MB | -802 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.137 | 2.193 | ⚠️ +0.06 |
| / avg req/sec | 1169.68 | 1140.05 | ⚠️ -29.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.489 | 1.465 | -0.02 |
| /error-in-render avg req/sec | 1679.5 | 1705.95 | +26.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.63 kB | 6.62 kB | -8 B |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..e4a8.js gzip | 10.7 kB | 10.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 57.2 kB | 57.2 kB | -8 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.72 kB | 5.71 kB | -10 B |
| webpack-HASH..dule.js gzip | 751 B | 751 B | ✓ |
| 19b7e98f51cc..dule.js gzip | 7.1 kB | 7.1 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 52.7 kB | 52.7 kB | -10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 26.4 kB | 26.4 kB | ✓ |
| Overall change | 26.4 kB | 26.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 268 B | 267 B | -1 B |
| _buildManife..dule.js gzip | 272 B | 274 B | ⚠️ +2 B |
| Overall change | 540 B | 541 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Bjodol/next.js babel-upgrade-7.10.4 | Change |
| - | - | - | - |
| index.html gzip | 953 B | 952 B | -1 B |
| link.html gzip | 961 B | 960 B | -1 B |
| withRouter.html gzip | 946 B | 946 B | ✓ |
| Overall change | 2.86 kB | 2.86 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-f35cd1774d910f5523ed.js"],
-  "/_error": ["static\u002Fpages\u002F_error-f39e6723c6acde17325a.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b5c3e8d3fd7cb18089e0.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-9e216cd51bf04b309e08.js"],
-  "/link": ["static\u002Fpages\u002Flink-d0cd3d2b80934d6c003a.js"],
+  "/link": ["static\u002Fpages\u002Flink-9cbc3acb75186d5885ae.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-b95d3f54c75949a43da6.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1,8 +1,8 @@
 self.__BUILD_MANIFEST = {
   "/": ["static\u002Fpages\u002Findex-da343bca3b67f1bcf42d.module.js"],
-  "/_error": ["static\u002Fpages\u002F_error-b3c4c3f8dbb1417657e6.module.js"],
+  "/_error": ["static\u002Fpages\u002F_error-b51f16b902f3e71973eb.module.js"],
   "/hooks": ["static\u002Fpages\u002Fhooks-dc8f274035a2839a1e61.module.js"],
-  "/link": ["static\u002Fpages\u002Flink-5a10d6c964f4c88363cd.module.js"],
+  "/link": ["static\u002Fpages\u002Flink-a90c99c9a9ddaa07df87.module.js"],
   "/routerDirect": [
     "static\u002Fpages\u002FrouterDirect-c62f258dff7fece0a732.module.js"
   ],
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..b697ae7df.js</strong></summary>

```diff
@@ -3188,7 +3188,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react["default"].createContext(null);
+      var RouterContext = /*#__PURE__*/ _react["default"].createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>19b7e98f51cc..de.module.js</strong></summary>

```diff
@@ -1935,7 +1935,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
             };
       }
 
-      var RouterContext = _react.default.createContext(null);
+      var RouterContext = /*#__PURE__*/ _react.default.createContext(null);
 
       exports.RouterContext = RouterContext;
```
</details>
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -178,7 +178,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             };
       }
 
-      var HeadManagerContext = _react["default"].createContext({});
+      var HeadManagerContext = /*#__PURE__*/ _react["default"].createContext(
+        {}
+      );
 
       exports.HeadManagerContext = HeadManagerContext;
 
@@ -402,7 +404,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                     "?" +
                     (0, _querystring.stringify)(
                       (0, _extends2["default"])(
-                        (0, _extends2["default"])({}, router.query),
+                        {},
+                        router.query,
                         (0, _querystring.parse)(location.search.substr(1))
                       )
                     ),
@@ -724,13 +727,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
                       _context2.next = 14;
                       return renderError(
-                        (0, _extends2["default"])(
-                          (0, _extends2["default"])({}, renderingProps),
-                          {},
-                          {
-                            err: _context2.t0
-                          }
-                        )
+                        (0, _extends2["default"])({}, renderingProps, {
+                          err: _context2.t0
+                        })
                       );
 
                     case 14:
@@ -784,15 +783,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
               : (0, _utils.loadGetInitialProps)(App, appCtx)
           ).then(function(initProps) {
             return doRender(
-              (0, _extends2["default"])(
-                (0, _extends2["default"])({}, renderErrorProps),
-                {},
-                {
-                  err: err,
-                  Component: ErrorComponent,
-                  props: initProps
-                }
-              )
+              (0, _extends2["default"])({}, renderErrorProps, {
+                err: err,
+                Component: ErrorComponent,
+                props: initProps
+              })
             );
           });
         });
@@ -923,15 +918,11 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var wrapApp = function wrapApp(App) {
         return function(wrappedAppProps) {
-          var appProps = (0, _extends2["default"])(
-            (0, _extends2["default"])({}, wrappedAppProps),
-            {},
-            {
-              Component: CachedComponent,
-              err: hydrateErr,
-              router: router
-            }
-          );
+          var appProps = (0, _extends2["default"])({}, wrappedAppProps, {
+            Compo [...]

2020-07-09 07:06 UTC, ijjk commented
## Failing test suites <!--894410464-->
Commit: b5ef70689f5e1d8ccf4cfa8d371705c22c1b5fe0

**test/integration/styled-jsx-plugin/test/index.test.js** 
- styled-jsx using in node_modules > production mode > should serve a page correctly

<details>
<summary>Expand output</summary>

  ● styled-jsx using in node_modules › production mode › should serve a page correctly

    thrown: "Exceeded timeout of 60000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      25 | describe('styled-jsx using in node_modules', () => {
      26 |   describe('production mode', () => {
    > 27 |     beforeAll(async () => {
         |     ^
      28 |       const output = await nextBuild(appDir, undefined, {
      29 |         stdout: true,
      30 |         stderr: true,

      at integration/styled-jsx-plugin/test/index.test.js:27:5
      at integration/styled-jsx-plugin/test/index.test.js:26:3
      at Object.<anonymous> (integration/styled-jsx-plugin/test/index.test.js:25:1)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      271 | export async function killApp(instance) {
      272 |   await new Promise((resolve, reject) => {
    > 273 |     treeKill(instance.pid, (err) => {
          |                       ^
      274 |       if (err) {
      275 |         if (
      276 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:273:23
      at killApp (lib/next-test-utils.js:272:9)
      at integration/styled-jsx-plugin/test/index.test.js:39:20

</details>

2020-07-09 15:39 UTC, Bjodol commented
Been doing a some digging today and the test issue has already occurred [once before](https://github.com/vercel/next.js/pull/12952) it seems, where the result has been that @StarpTech has submitted a [pull request](https://github.com/michael-ciniawsky/postcss-load-plugins/pull/119) to [postcss-load-plugins](https://github.com/michael-ciniawsky/postcss-load-plugins), which now has been two months stale. The proposed changes would hopefully result in code that is easier to follow, but I still think that it would requires some change in [styled-jsx-plugin-postcss](https://github.com/giuseppeg/styled-jsx-plugin-postcss) to get it working all the way through. 

I am still uncertain of why the bug happens in the first place. I tried running the styledstyled-jsx-plugin-postcss through the next babel preset with the different versions of babel and they both came out identical from what I could see.

If anyone has some pointers on where to look next (pun-intended) I'll see if I can find the time :)

2020-07-19 08:28 UTC, Pedja21 submitted a review, later dismissed

2020-08-28 00:30 UTC, lfades commented
Hi @Bjodol are you still working on this PR? There are some conflicts but next@canary hasn't updated yet to babel 7.10. You can run the styled-jsx tests locally and see why they broke:

```bash
yarn testonly --testPathPattern=integration/styled-jsx-plugin
```

See [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md) for more detailed steps.

2020-08-30 02:02 UTC, Timer commented
Closing this PR as stale.

2020-08-30 02:02 UTC, closed without merging