chore(lint): Use lint-staged with standard --fix
vercel/next.js pull request #1519
Opened 2017-03-27 14:16 UTC by okonet

With the current setup all project files will be linted on each commit which might take quite some time but more importantly, it will display results irrelevant to the commit. 

lint-staged on the other hand only runs linter against staged files (i.e. files that were selected for the commit but `git add`) which is faster and will get relevant results.

This PR also implements autofixing of some rules. The only gotcha with this approach is that it doesn't work with partially staged files yet (i.e. `git add -p`). See https://github.com/okonet/lint-staged/issues/62. If you think this is a blocker, I can remove the autofixing option from this PR.

Another note is that files in `/bin` still can have `.js` extensions without introducing any breaking changes. I can rename them to make the config even simpler and remove some duplication.

2017-03-27 14:30 UTC, arunoda requested changes
I've made some comments.
I think we need to have the existing `lint` command as well.

Because we need to do a full lint check on Travis.

2017-03-27 14:30 UTC, arunoda commented on package.json
> +      "standard --fix",
We don't wanna fix automatically.

2017-03-27 14:30 UTC, arunoda commented on package.json
> +  "lint-staged": {
Add another command for `lint-staged-fix`

2017-03-27 14:30 UTC, arunoda commented on package.json
> -    "lint": "standard 'bin/*' 'client/**/*.js' 'examples/**/*.js' 'lib/**/*.js' 'pages/**/*.js' 'server/**/*.js' 'test/**/*.js'",
Keep this as it is.

2017-03-27 18:23 UTC, okonet commented on package.json
> +      "standard --fix",
If you don't want to fix automatically, I think it's better to just use `standard` command without going through npm `scripts`

2017-03-27 18:23 UTC, okonet commented on package.json
> -    "lint": "standard 'bin/*' 'client/**/*.js' 'examples/**/*.js' 'lib/**/*.js' 'pages/**/*.js' 'server/**/*.js' 'test/**/*.js'",
You're right. I see it's being used in `pretest`.

2017-03-27 18:25 UTC, okonet commented on package.json
> +      "standard --fix",
Just out of curiosity: why don't you want to fix automatically? In my experience this is a real time-saver.

2017-03-27 18:27 UTC, okonet commented
Updated the PR.

2017-03-29 23:20 UTC, arunoda approved these changes

2017-03-29 23:21 UTC, merged