Add handling for redirects from getStaticProps/getServerSideProps
vercel/next.js pull request #16642
Opened 2020-08-28 00:32 UTC by ijjk

This implements the RFC posted here https://github.com/vercel/next.js/discussions/14890

Closes: https://github.com/vercel/next.js/issues/16587

TODO:

- [ ] tests
- [ ] add error handling for redirects being returned during prerendering

2020-08-28 00:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +131ms |
| nodeModulesSize | 57.5 MB | 57.5 MB | ⚠️ +7.84 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.172 | 2.152 | -0.02 |
| / avg req/sec | 1151.02 | 1161.98 | +10.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.224 | 1.153 | -0.07 |
| /error-in-render avg req/sec | 2042.73 | 2167.65 | +124.92 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..7f47.js gzip | 10.3 kB | 10.4 kB | ⚠️ +129 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ce79c9a..12c9.js gzip | 7.36 kB | 7.36 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.4 kB | 57.5 kB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.15 kB | 6.25 kB | ⚠️ +99 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9973c26..dule.js gzip | 6.42 kB | 6.42 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.4 kB | ⚠️ +99 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-28298..e0c9.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-65c8a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 972 B | 970 B | -2 B |
| link.html gzip | 978 B | 976 B | -2 B |
| withRouter.html gzip | 964 B | 963 B | -1 B |
| Overall change | 2.91 kB | 2.91 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..6e297704b.js</strong></summary>

```diff
@@ -1128,7 +1128,12 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
-                    appComp;
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    appComp,
+                    destination,
+                    parsedHref;
 
                   return _regeneratorRuntime.wrap(
                     function _callee$(_context) {
@@ -1315,7 +1320,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 53:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP);
                             Router.events.emit("beforeHistoryChange", as);
                             this.changeState(method, url, as, options);
 
@@ -1348,27 +1356,76 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             throw error;
 
                           case 63:
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 72;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 70;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 70;
+                              break;
+                            }
+
+                            return _context.abrupt(
+                              "return",
+                              this.change(
+                                "replaceState",
+                                destination,
+                                destination,
+                                options
+                              )
+                            );
+
+                          case 70:
+                            window.location.href = destination;
+                            return _context.abrupt(
+                              "return",
+                              new Promise(function() {})
+                            );
+
+                          case 72:
                             if (false) {
                             }
 
                             Router.events.emit("routeChangeComplete", as);
                             return _context.abrupt("return", true);
 
-                          case 68:
-                            _context.prev = 68;
+                          case 77:
+                            _context.prev = 77;
                             _context.t0 = _context["catch"](50);
 
                     [...]

2020-08-28 00:46 UTC, ijjk commented
## Failing test suites <!--1109650945-->
Commit: bdc98f012269938b8af5f060679b694a1d8c33e3

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.09999999999999432

       96 | 
       97 |       // should be no bigger than 60.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 60.2).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

2020-08-28 03:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.5s | -316ms |
| nodeModulesSize | 57.5 MB | 57.5 MB | ⚠️ +7.84 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.469 | 2.395 | -0.07 |
| / avg req/sec | 1012.39 | 1043.91 | +31.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.415 | 1.413 | 0 |
| /error-in-render avg req/sec | 1767.11 | 1769.36 | +2.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..f20b.js gzip | 10.3 kB | 10.4 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ce79c9a..12c9.js gzip | 7.36 kB | 7.36 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.5 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.23 kB | ⚠️ +103 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9973c26..dule.js gzip | 6.42 kB | 6.42 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.4 kB | ⚠️ +103 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-28298..e0c9.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-65c8a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 972 B | 971 B | -1 B |
| link.html gzip | 978 B | 977 B | -1 B |
| withRouter.html gzip | 964 B | 963 B | -1 B |
| Overall change | 2.91 kB | 2.91 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..60.module.js</strong></summary>

```diff
@@ -1041,7 +1041,39 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               as,
               shallow
             );
-            var { error } = routeInfo;
+            var { error, props, __N_SSG, __N_SSP } = routeInfo; // handle redirect on client-transition
+
+            if (
+              (__N_SSG || __N_SSP) &&
+              props &&
+              props.pageProps &&
+              props.pageProps.__N_REDIRECT
+            ) {
+              var destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+              // client-navigation if it is falling back to hard navigation if
+              // it's not
+
+              if (destination.startsWith("/")) {
+                var parsedHref = (0, _parseRelativeUrl.parseRelativeUrl)(
+                  destination
+                );
+
+                this._resolveHref(parsedHref, pages);
+
+                if (pages.includes(parsedHref.pathname)) {
+                  return this.change(
+                    "replaceState",
+                    destination,
+                    destination,
+                    options
+                  );
+                }
+              }
+
+              window.location.href = destination;
+              return new Promise(() => {});
+            }
+
             Router.events.emit("beforeHistoryChange", as);
             this.changeState(method, url, as, options);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..886051899.js</strong></summary>

```diff
@@ -1117,6 +1117,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1297,14 +1302,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+              [...]

2020-08-28 15:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.8s | ⚠️ +639ms |
| nodeModulesSize | 57.5 MB | 57.5 MB | ⚠️ +8.44 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.66 | 2.647 | -0.01 |
| / avg req/sec | 939.8 | 944.49 | +4.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.665 | 1.691 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1501.62 | 1478.75 | ⚠️ -22.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..f20b.js gzip | 10.3 kB | 10.4 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ce79c9a..12c9.js gzip | 7.36 kB | 7.36 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.5 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.23 kB | ⚠️ +103 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-9973c26..dule.js gzip | 6.42 kB | 6.42 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.4 kB | ⚠️ +103 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-28298..e0c9.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-65c8a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 972 B | 971 B | -1 B |
| link.html gzip | 978 B | 977 B | -1 B |
| withRouter.html gzip | 964 B | 963 B | -1 B |
| Overall change | 2.91 kB | 2.91 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..60.module.js</strong></summary>

```diff
@@ -1041,7 +1041,39 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               as,
               shallow
             );
-            var { error } = routeInfo;
+            var { error, props, __N_SSG, __N_SSP } = routeInfo; // handle redirect on client-transition
+
+            if (
+              (__N_SSG || __N_SSP) &&
+              props &&
+              props.pageProps &&
+              props.pageProps.__N_REDIRECT
+            ) {
+              var destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+              // client-navigation if it is falling back to hard navigation if
+              // it's not
+
+              if (destination.startsWith("/")) {
+                var parsedHref = (0, _parseRelativeUrl.parseRelativeUrl)(
+                  destination
+                );
+
+                this._resolveHref(parsedHref, pages);
+
+                if (pages.includes(parsedHref.pathname)) {
+                  return this.change(
+                    "replaceState",
+                    destination,
+                    destination,
+                    options
+                  );
+                }
+              }
+
+              window.location.href = destination;
+              return new Promise(() => {});
+            }
+
             Router.events.emit("beforeHistoryChange", as);
             this.changeState(method, url, as, options);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..886051899.js</strong></summary>

```diff
@@ -1117,6 +1117,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1297,14 +1302,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+    [...]

2020-08-30 16:13 UTC, timneutkens commented on packages/next/next-server/server/render.tsx
> +  // TODO: this should error if a redirect is returned while prerendering
Looks like you handled this case right?

2020-08-31 15:27 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.8s | ⚠️ +525ms |
| nodeModulesSize | 57.4 MB | 57.4 MB | ⚠️ +8.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.402 | 2.541 | ⚠️ +0.14 |
| / avg req/sec | 1040.99 | 983.94 | ⚠️ -57.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.519 | 1.613 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1645.38 | 1549.73 | ⚠️ -95.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..f20b.js gzip | 10.3 kB | 10.4 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-49b1fd5..c64c.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.5 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.23 kB | ⚠️ +103 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-99715b4..dule.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.2 kB | 52.3 kB | ⚠️ +103 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-28298..e0c9.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-65c8a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 971 B | 971 B | ✓ |
| link.html gzip | 977 B | 979 B | ⚠️ +2 B |
| withRouter.html gzip | 964 B | 964 B | ✓ |
| Overall change | 2.91 kB | 2.91 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..60.module.js</strong></summary>

```diff
@@ -1041,7 +1041,39 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               as,
               shallow
             );
-            var { error } = routeInfo;
+            var { error, props, __N_SSG, __N_SSP } = routeInfo; // handle redirect on client-transition
+
+            if (
+              (__N_SSG || __N_SSP) &&
+              props &&
+              props.pageProps &&
+              props.pageProps.__N_REDIRECT
+            ) {
+              var destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+              // client-navigation if it is falling back to hard navigation if
+              // it's not
+
+              if (destination.startsWith("/")) {
+                var parsedHref = (0, _parseRelativeUrl.parseRelativeUrl)(
+                  destination
+                );
+
+                this._resolveHref(parsedHref, pages);
+
+                if (pages.includes(parsedHref.pathname)) {
+                  return this.change(
+                    "replaceState",
+                    destination,
+                    destination,
+                    options
+                  );
+                }
+              }
+
+              window.location.href = destination;
+              return new Promise(() => {});
+            }
+
             Router.events.emit("beforeHistoryChange", as);
             this.changeState(method, url, as, options);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..886051899.js</strong></summary>

```diff
@@ -1117,6 +1117,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1297,14 +1302,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              br [...]

2020-09-01 07:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.4s | -88ms |
| nodeModulesSize | 56.8 MB | 56.8 MB | ⚠️ +8.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.511 | 2.517 | ⚠️ +0.01 |
| / avg req/sec | 995.46 | 993.27 | ⚠️ -2.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.518 | 1.487 | -0.03 |
| /error-in-render avg req/sec | 1646.58 | 1681.7 | +35.12 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..f20b.js gzip | 10.3 kB | 10.4 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-49b1fd5..c64c.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.5 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.23 kB | ⚠️ +103 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-99715b4..dule.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.2 kB | 52.3 kB | ⚠️ +103 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-28298..e0c9.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-000f151..65d4.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-65c8a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-4cfda7a..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 971 B | 971 B | ✓ |
| link.html gzip | 977 B | 979 B | ⚠️ +2 B |
| withRouter.html gzip | 964 B | 964 B | ✓ |
| Overall change | 2.91 kB | 2.91 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..60.module.js</strong></summary>

```diff
@@ -1041,7 +1041,39 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
               as,
               shallow
             );
-            var { error } = routeInfo;
+            var { error, props, __N_SSG, __N_SSP } = routeInfo; // handle redirect on client-transition
+
+            if (
+              (__N_SSG || __N_SSP) &&
+              props &&
+              props.pageProps &&
+              props.pageProps.__N_REDIRECT
+            ) {
+              var destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+              // client-navigation if it is falling back to hard navigation if
+              // it's not
+
+              if (destination.startsWith("/")) {
+                var parsedHref = (0, _parseRelativeUrl.parseRelativeUrl)(
+                  destination
+                );
+
+                this._resolveHref(parsedHref, pages);
+
+                if (pages.includes(parsedHref.pathname)) {
+                  return this.change(
+                    "replaceState",
+                    destination,
+                    destination,
+                    options
+                  );
+                }
+              }
+
+              window.location.href = destination;
+              return new Promise(() => {});
+            }
+
             Router.events.emit("beforeHistoryChange", as);
             this.changeState(method, url, as, options);
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..886051899.js</strong></summary>

```diff
@@ -1117,6 +1117,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1297,14 +1302,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+         [...]

2020-09-01 16:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13s | -428ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | ⚠️ +8.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.504 | 2.545 | ⚠️ +0.04 |
| / avg req/sec | 998.59 | 982.16 | ⚠️ -16.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.504 | 1.57 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1662.25 | 1592.34 | ⚠️ -69.91 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..9ff9.js gzip | 10.3 kB | 10.4 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-2db3d72..5955.js gzip | 7.35 kB | 7.35 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.5 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.23 kB | ⚠️ +103 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-d7fe688..dule.js gzip | 6.41 kB | 6.41 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.4 kB | ⚠️ +103 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-ae98065..267e.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-cb244c4..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 971 B | 972 B | ⚠️ +1 B |
| link.html gzip | 976 B | 977 B | ⚠️ +1 B |
| withRouter.html gzip | 964 B | 965 B | ⚠️ +1 B |
| Overall change | 2.91 kB | 2.91 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..7000fca82.js</strong></summary>

```diff
@@ -1117,6 +1117,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     missingParams,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1297,14 +1302,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            return _context.abrupt(
+                              "return",
+                              this.change(
+                                "replaceState",
+                                destination,
+                                destination,
+                                options
+                              )
+                            );
+
+                          case 60:
+                            window.location.href = destination;
+                            return _context.abrupt(
+                              "return",
+                              new Promise(function() {})
+                            );
+
+                          case 62:
                             Router.events.emit("beforeHistoryChange", as);
                             this.changeState(method, url, as, options);
 
                             if (false) {
                             }
 
-                            _context.next = 58;
+                            _context.next = 67;
                             return this.set(
                               route,
                               pathname,
@@ -1316,9 +1374,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                               else throw e;
                             });
 
-                          case 58:
+                          case 67:
                             if (!error) {
-                              _context.next = 61;
+                              _conte [...]

2020-09-07 09:53 UTC, timneutkens approved these changes

2020-09-07 09:54 UTC, timneutkens commented on packages/next/types/index.d.ts
> +  unstable_redirect?: Redirect
The type is incorrect, you can either return `unstable_redirect` or `props`, not both

2020-09-07 09:55 UTC, timneutkens requested changes
As per the comment

2020-09-07 18:15 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.7s | ⚠️ +288ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | ⚠️ +8.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.247 | 2.206 | -0.04 |
| / avg req/sec | 1112.75 | 1133.36 | +20.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.22 | 1.201 | -0.02 |
| /error-in-render avg req/sec | 2048.9 | 2082.38 | +33.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..7362.js gzip | 10.6 kB | 10.8 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-979126c..02f7.js gzip | 7.08 kB | 7.08 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.4 kB | 57.6 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.51 kB | 6.62 kB | ⚠️ +104 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e37c8f7..dule.js gzip | 6.14 kB | 6.14 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.5 kB | ⚠️ +104 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 973 B | 972 B | -1 B |
| link.html gzip | 979 B | 979 B | ✓ |
| withRouter.html gzip | 966 B | 965 B | -1 B |
| Overall change | 2.92 kB | 2.92 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..2db076a1e.js</strong></summary>

```diff
@@ -1214,6 +1214,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     params,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1406,14 +1411,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            return _context.abrupt(
+                              "return",
+                              this.change(
+                                "replaceState",
+                                destination,
+                                destination,
+                                options
+                              )
+                            );
+
+                          case 60:
+                            window.location.href = destination;
+                            return _context.abrupt(
+                              "return",
+                              new Promise(function() {})
+                            );
+
+                          case 62:
                             Router.events.emit("beforeHistoryChange", as);
                             this.changeState(method, url, as, options);
 
                             if (false) {
                             }
 
-                            _context.next = 58;
+                            _context.next = 67;
                             return this.set(
                               route,
                               pathname,
@@ -1425,9 +1483,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                               else throw e;
                             });
 
-                          case 58:
+                          case 67:
                             if (!error) {
-                              _context.next = 61;
+                              _context.next = 70;
                   [...]

2020-09-07 18:20 UTC, ijjk commented
## Failing test suites <!--1156338945-->
Commit: 461c52abe9db4e483c9a2279eaca6cb9c3f44f4c

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

       96 | 
       97 |       // should be no bigger than 60.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 60.3).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

2020-09-07 19:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.8s | ⚠️ +110ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | ⚠️ +8.61 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.061 | 2.093 | ⚠️ +0.03 |
| / avg req/sec | 1212.89 | 1194.17 | ⚠️ -18.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.1 | 1.14 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2272.11 | 2193.51 | ⚠️ -78.6 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..7362.js gzip | 10.6 kB | 10.8 kB | ⚠️ +124 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-979126c..02f7.js gzip | 7.08 kB | 7.08 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.4 kB | 57.6 kB | ⚠️ +124 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.51 kB | 6.62 kB | ⚠️ +104 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e37c8f7..dule.js gzip | 6.14 kB | 6.14 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.5 kB | ⚠️ +104 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js add/gssp-redirect-handling | Change |
| - | - | - | - |
| index.html gzip | 973 B | 972 B | -1 B |
| link.html gzip | 979 B | 979 B | ✓ |
| withRouter.html gzip | 966 B | 965 B | -1 B |
| Overall change | 2.92 kB | 2.92 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..2db076a1e.js</strong></summary>

```diff
@@ -1214,6 +1214,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     params,
                     routeInfo,
                     error,
+                    props,
+                    __N_SSG,
+                    __N_SSP,
+                    destination,
+                    parsedHref,
                     appComp;
 
                   return _regeneratorRuntime.wrap(
@@ -1406,14 +1411,67 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
                           case 51:
                             routeInfo = _context.sent;
-                            error = routeInfo.error;
+                            (error = routeInfo.error),
+                              (props = routeInfo.props),
+                              (__N_SSG = routeInfo.__N_SSG),
+                              (__N_SSP = routeInfo.__N_SSP); // handle redirect on client-transition
+
+                            if (
+                              !(
+                                (__N_SSG || __N_SSP) &&
+                                props &&
+                                props.pageProps &&
+                                props.pageProps.__N_REDIRECT
+                              )
+                            ) {
+                              _context.next = 62;
+                              break;
+                            }
+
+                            destination = props.pageProps.__N_REDIRECT; // check if destination is internal (resolves to a page) and attempt
+                            // client-navigation if it is falling back to hard navigation if
+                            // it's not
+
+                            if (!destination.startsWith("/")) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            parsedHref = (0,
+                            _parseRelativeUrl.parseRelativeUrl)(destination);
+
+                            this._resolveHref(parsedHref, pages);
+
+                            if (!pages.includes(parsedHref.pathname)) {
+                              _context.next = 60;
+                              break;
+                            }
+
+                            return _context.abrupt(
+                              "return",
+                              this.change(
+                                "replaceState",
+                                destination,
+                                destination,
+                                options
+                              )
+                            );
+
+                          case 60:
+                            window.location.href = destination;
+                            return _context.abrupt(
+                              "return",
+                              new Promise(function() {})
+                            );
+
+                          case 62:
                             Router.events.emit("beforeHistoryChange", as);
                             this.changeState(method, url, as, options);
 
                             if (false) {
                             }
 
-                            _context.next = 58;
+                            _context.next = 67;
                             return this.set(
                               route,
                               pathname,
@@ -1425,9 +1483,9 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                               else throw e;
                             });
 
-                          case 58:
+                          case 67:
                             if (!error) {
-                              _context.next = 61;
+                              _context.next = 70;
        [...]

2020-09-08 07:22 UTC, timneutkens approved these changes

2020-09-08 07:23 UTC, merged

2020-09-19 07:22 UTC, DmitryKvant commented
How i can use it for redirect with status 404?