Remove `next-head-count`
vercel/next.js pull request #16758
Opened 2020-09-01 18:02 UTC by devknoll

Removes `next-head-count`, improving support for 3rd party libraries that insert or append new elements to `<head>`.

---

This is more or less what a solution with a `data-` attribute would look like, except that instead of directly searching for elements with that attribute, we serialize the elements expected in `<head>` and then find them/assume ownership of them during initialization (in a manner similar to React's reconciliation) based on their properties.

There are two main assumptions here:
1. Content is served with compression, so duplicate serialization of e.g. inline script or style tags doesn't have a meaningful impact. Storing a hash would be a potential optimization.
2. 3rd party libraries primarily only insert new, unique elements to head. Libraries trying to actively manage elements that overlap with those that Next.js claims ownership of will still be unsupported.

The reason for this roundabout approach is that I'd really like to avoid `data-` if possible, for maximum compatibility. Implicitly adding an attribute could be a breaking change for some class of tools or crawlers and makes it otherwise impossible to insert raw HTML into `<head>`. Adding an unexpected attribute is why the original `class="next-head"` approach was problematic in the first place!

That said, while I don't expect this to be more problematic than `next-head-count` (anything that would break in this new model also should have broken in the old model), if that does end up being the case, it might make sense to just bite the bullet.

Fixes #11012

---

cc @Timer @timneutkens

2020-09-01 18:12 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.6s | -193ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.509 | 2.321 | -0.19 |
| / avg req/sec | 996.23 | 1076.97 | +80.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.379 | 1.384 | 0 |
| /error-in-render avg req/sec | 1812.78 | 1805.99 | ⚠️ -6.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..9ff9.js gzip | 10.3 kB | 10.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-cc92da0..0b67.js gzip | 7.35 kB | 7.71 kB | ⚠️ +360 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +360 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.13 kB | 6.13 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-0ed168f..dule.js gzip | 6.41 kB | 6.32 kB | -99 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -99 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-ae98065..267e.js gzip | 1.29 kB | 1.29 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.69 kB | 7.69 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-cb244c4..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.35 kB | 5.35 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 970 B | 1.01 kB | ⚠️ +36 B |
| link.html gzip | 976 B | 1.01 kB | ⚠️ +34 B |
| withRouter.html gzip | 964 B | 999 B | ⚠️ +35 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +105 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-0ed0039..df.module.js</strong></summary>

```diff
@@ -19,6 +19,9 @@
 
       exports.__esModule = true;
       exports.default = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -51,48 +54,55 @@
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
-
-        if (false) {
-        }
-
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+        var oldTags = new Set(elements);
+        components.forEach(tag => {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var { children } = tag.props;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
+            if (title !== document.title) document.title = title;
+            return;
           }
-        }
 
-        var newTags = components.map(reactElementToDOM).filter(newTag => {
-          for (var k = 0, len = oldTags.length; k < len; k++) {
-            var oldTag = oldTags[k];
+          var newTag = reactElementToDOM(tag);
 
+          for (var oldTag of elements) {
             if (oldTag.isEqualNode(newTag)) {
-              oldTags.splice(k, 1);
-              return false;
+              oldTags.delete(oldTag);
+              return;
             }
           }
 
-          return true;
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        oldTags.forEach(t => t.parentNode.removeChild(t));
-        newTags.forEach(t => headEl.insertBefore(t, headCountEl));
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
+
+        for (var oldTag of oldTags) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements.delete(oldTag);
+        }
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(entry =>
+            /*#__PURE__*/ (0, _react.createElement)(entry.type, entry.props)
+          ),
+          false
+        );
         var updatePromise = null;
         return {
           mountedInstances: new Set(),
@@ -100,25 +110,7 @@
             var promise = (updatePromise = Promise.resolve().then(() => {
               if (promise !== updatePromise) return;
               updatePromise = null;
-              var tags = {};
-              head.forEach(h => {
-                var components = tags[h.type] || [];
-                components.push(h);
-                tags[h.type] = components;
-              });
-              var titleComponent = tags.title ? tags.title[0] : null;
-              var title = "";
-
-              if (titleComponent) {
-                var { children } = titleComponent.props;
-                title =
-                  typeof children === "string" ? children : children.join("");
-              }
-
-              if (title !== document.title) document.title = title;
-              ["meta", "base", "link", "style", "script"].forEach(type => {
-                updateElements(type, tags[type] || []);
-        [...]

2020-09-01 18:12 UTC, Timer commented on errors/next-head-count-missing.md
> -# `next-head-count` is missing
We need to keep this file and tell people there was an issue with 3rd party libs that was fixed in a newer version of Next.js and to please upgrade.

2020-09-01 19:13 UTC, stefvhuynh commented
here is my PR for this issue: https://github.com/vercel/next.js/pull/16707

it uses a different approach that uses `next-head-count` along with a `data-` attribute. the logic involves traversing the head contents upwards and tracking the count if the element has the `data-` attribute.

2020-09-02 18:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.8s | -293ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.417 | 2.297 | -0.12 |
| / avg req/sec | 1034.14 | 1088.33 | +54.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.347 | 1.218 | -0.13 |
| /error-in-render avg req/sec | 1856.14 | 2052.45 | +196.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..01b7.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f69b135..640b.js gzip | 7.1 kB | 7.46 kB | ⚠️ +360 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +360 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.39 kB | 6.39 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ed2fed0..dule.js gzip | 6.16 kB | 6.06 kB | -101 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -101 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 972 B | 1.01 kB | ⚠️ +35 B |
| link.html gzip | 978 B | 1.01 kB | ⚠️ +36 B |
| withRouter.html gzip | 964 B | 1 kB | ⚠️ +38 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +109 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-7a454bf..8850624a9.js</strong></summary>

```diff
@@ -42,8 +42,85 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      function _createForOfIteratorHelper(o, allowArrayLike) {
+        var it;
+        if (typeof Symbol === "undefined" || o[Symbol.iterator] == null) {
+          if (
+            Array.isArray(o) ||
+            (it = _unsupportedIterableToArray(o)) ||
+            (allowArrayLike && o && typeof o.length === "number")
+          ) {
+            if (it) o = it;
+            var i = 0;
+            var F = function F() {};
+            return {
+              s: F,
+              n: function n() {
+                if (i >= o.length) return { done: true };
+                return { done: false, value: o[i++] };
+              },
+              e: function e(_e) {
+                throw _e;
+              },
+              f: F
+            };
+          }
+          throw new TypeError(
+            "Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
+          );
+        }
+        var normalCompletion = true,
+          didErr = false,
+          err;
+        return {
+          s: function s() {
+            it = o[Symbol.iterator]();
+          },
+          n: function n() {
+            var step = it.next();
+            normalCompletion = step.done;
+            return step;
+          },
+          e: function e(_e2) {
+            didErr = true;
+            err = _e2;
+          },
+          f: function f() {
+            try {
+              if (!normalCompletion && it["return"] != null) it["return"]();
+            } finally {
+              if (didErr) throw err;
+            }
+          }
+        };
+      }
+
+      function _unsupportedIterableToArray(o, minLen) {
+        if (!o) return;
+        if (typeof o === "string") return _arrayLikeToArray(o, minLen);
+        var n = Object.prototype.toString.call(o).slice(8, -1);
+        if (n === "Object" && o.constructor) n = o.constructor.name;
+        if (n === "Map" || n === "Set") return Array.from(o);
+        if (
+          n === "Arguments" ||
+          /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)
+        )
+          return _arrayLikeToArray(o, minLen);
+      }
+
+      function _arrayLikeToArray(arr, len) {
+        if (len == null || len > arr.length) len = arr.length;
+        for (var i = 0, arr2 = new Array(len); i < len; i++) {
+          arr2[i] = arr[i];
+        }
+        return arr2;
+      }
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +155,78 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag);
 
-        [...]

2020-09-02 18:12 UTC, ijjk commented
## Failing test suites <!--1134423016-->
Commit: cd0f546c1e031cecc368d0c2cc0478c4a0b9c3c3

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

       96 | 
       97 |       // should be no bigger than 60.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 60.5).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

2020-09-02 18:14 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 13.2s | 12.9s | -214ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.369 | 2.32 | -0.05 |
| / avg req/sec | 1055.36 | 1077.38 | +22.02 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.28 | 1.295 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1953.6 | 1930.5 | ⚠️ -23.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..01b7.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f69b135..640b.js gzip | 7.1 kB | 7.46 kB | ⚠️ +360 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +360 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.39 kB | 6.39 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ed2fed0..dule.js gzip | 6.16 kB | 6.06 kB | -101 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -101 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 972 B | 1.01 kB | ⚠️ +35 B |
| link.html gzip | 978 B | 1.01 kB | ⚠️ +36 B |
| withRouter.html gzip | 964 B | 1 kB | ⚠️ +38 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +109 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-7a454bf..8850624a9.js</strong></summary>

```diff
@@ -42,8 +42,85 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      function _createForOfIteratorHelper(o, allowArrayLike) {
+        var it;
+        if (typeof Symbol === "undefined" || o[Symbol.iterator] == null) {
+          if (
+            Array.isArray(o) ||
+            (it = _unsupportedIterableToArray(o)) ||
+            (allowArrayLike && o && typeof o.length === "number")
+          ) {
+            if (it) o = it;
+            var i = 0;
+            var F = function F() {};
+            return {
+              s: F,
+              n: function n() {
+                if (i >= o.length) return { done: true };
+                return { done: false, value: o[i++] };
+              },
+              e: function e(_e) {
+                throw _e;
+              },
+              f: F
+            };
+          }
+          throw new TypeError(
+            "Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
+          );
+        }
+        var normalCompletion = true,
+          didErr = false,
+          err;
+        return {
+          s: function s() {
+            it = o[Symbol.iterator]();
+          },
+          n: function n() {
+            var step = it.next();
+            normalCompletion = step.done;
+            return step;
+          },
+          e: function e(_e2) {
+            didErr = true;
+            err = _e2;
+          },
+          f: function f() {
+            try {
+              if (!normalCompletion && it["return"] != null) it["return"]();
+            } finally {
+              if (didErr) throw err;
+            }
+          }
+        };
+      }
+
+      function _unsupportedIterableToArray(o, minLen) {
+        if (!o) return;
+        if (typeof o === "string") return _arrayLikeToArray(o, minLen);
+        var n = Object.prototype.toString.call(o).slice(8, -1);
+        if (n === "Object" && o.constructor) n = o.constructor.name;
+        if (n === "Map" || n === "Set") return Array.from(o);
+        if (
+          n === "Arguments" ||
+          /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)
+        )
+          return _arrayLikeToArray(o, minLen);
+      }
+
+      function _arrayLikeToArray(arr, len) {
+        if (len == null || len > arr.length) len = arr.length;
+        for (var i = 0, arr2 = new Array(len); i < len; i++) {
+          arr2[i] = arr[i];
+        }
+        return arr2;
+      }
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +155,78 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag);
 
-       [...]

2020-09-02 18:18 UTC, ijjk commented
## Failing test suites <!--1134454406-->
Commit: 4d42dedd2bf6aa53f50b6cfba342666dc47afdb6

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

       96 | 
       97 |       // should be no bigger than 60.5 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 60.5).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.5).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

2020-09-02 18:37 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 11.6s | 12.1s | ⚠️ +464ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.182 | 2.308 | ⚠️ +0.13 |
| / avg req/sec | 1145.83 | 1083.12 | ⚠️ -62.71 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.384 | 1.335 | -0.05 |
| /error-in-render avg req/sec | 1806.49 | 1873.23 | +66.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..01b7.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f69b135..640b.js gzip | 7.1 kB | 7.46 kB | ⚠️ +360 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +360 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.39 kB | 6.39 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ed2fed0..dule.js gzip | 6.16 kB | 6.06 kB | -101 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -101 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 972 B | 1.01 kB | ⚠️ +35 B |
| link.html gzip | 978 B | 1.01 kB | ⚠️ +36 B |
| withRouter.html gzip | 964 B | 1 kB | ⚠️ +38 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +109 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-7a454bf..8850624a9.js</strong></summary>

```diff
@@ -42,8 +42,85 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      function _createForOfIteratorHelper(o, allowArrayLike) {
+        var it;
+        if (typeof Symbol === "undefined" || o[Symbol.iterator] == null) {
+          if (
+            Array.isArray(o) ||
+            (it = _unsupportedIterableToArray(o)) ||
+            (allowArrayLike && o && typeof o.length === "number")
+          ) {
+            if (it) o = it;
+            var i = 0;
+            var F = function F() {};
+            return {
+              s: F,
+              n: function n() {
+                if (i >= o.length) return { done: true };
+                return { done: false, value: o[i++] };
+              },
+              e: function e(_e) {
+                throw _e;
+              },
+              f: F
+            };
+          }
+          throw new TypeError(
+            "Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
+          );
+        }
+        var normalCompletion = true,
+          didErr = false,
+          err;
+        return {
+          s: function s() {
+            it = o[Symbol.iterator]();
+          },
+          n: function n() {
+            var step = it.next();
+            normalCompletion = step.done;
+            return step;
+          },
+          e: function e(_e2) {
+            didErr = true;
+            err = _e2;
+          },
+          f: function f() {
+            try {
+              if (!normalCompletion && it["return"] != null) it["return"]();
+            } finally {
+              if (didErr) throw err;
+            }
+          }
+        };
+      }
+
+      function _unsupportedIterableToArray(o, minLen) {
+        if (!o) return;
+        if (typeof o === "string") return _arrayLikeToArray(o, minLen);
+        var n = Object.prototype.toString.call(o).slice(8, -1);
+        if (n === "Object" && o.constructor) n = o.constructor.name;
+        if (n === "Map" || n === "Set") return Array.from(o);
+        if (
+          n === "Arguments" ||
+          /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)
+        )
+          return _arrayLikeToArray(o, minLen);
+      }
+
+      function _arrayLikeToArray(arr, len) {
+        if (len == null || len > arr.length) len = arr.length;
+        for (var i = 0, arr2 = new Array(len); i < len; i++) {
+          arr2[i] = arr[i];
+        }
+        return arr2;
+      }
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +155,78 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag);
 
 [...]

2020-09-02 20:11 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.8s | ⚠️ +38ms |
| nodeModulesSize | 55.9 MB | 55.9 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.345 | 2.354 | ⚠️ +0.01 |
| / avg req/sec | 1065.93 | 1061.82 | ⚠️ -4.11 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.285 | 1.293 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1946.23 | 1933.3 | ⚠️ -12.93 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..01b7.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f69b135..640b.js gzip | 7.1 kB | 7.46 kB | ⚠️ +360 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +360 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.39 kB | 6.39 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ed2fed0..dule.js gzip | 6.16 kB | 6.06 kB | -101 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -101 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 972 B | 1.01 kB | ⚠️ +35 B |
| link.html gzip | 978 B | 1.01 kB | ⚠️ +36 B |
| withRouter.html gzip | 964 B | 1 kB | ⚠️ +38 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +109 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-7a454bf..8850624a9.js</strong></summary>

```diff
@@ -42,8 +42,85 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      function _createForOfIteratorHelper(o, allowArrayLike) {
+        var it;
+        if (typeof Symbol === "undefined" || o[Symbol.iterator] == null) {
+          if (
+            Array.isArray(o) ||
+            (it = _unsupportedIterableToArray(o)) ||
+            (allowArrayLike && o && typeof o.length === "number")
+          ) {
+            if (it) o = it;
+            var i = 0;
+            var F = function F() {};
+            return {
+              s: F,
+              n: function n() {
+                if (i >= o.length) return { done: true };
+                return { done: false, value: o[i++] };
+              },
+              e: function e(_e) {
+                throw _e;
+              },
+              f: F
+            };
+          }
+          throw new TypeError(
+            "Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
+          );
+        }
+        var normalCompletion = true,
+          didErr = false,
+          err;
+        return {
+          s: function s() {
+            it = o[Symbol.iterator]();
+          },
+          n: function n() {
+            var step = it.next();
+            normalCompletion = step.done;
+            return step;
+          },
+          e: function e(_e2) {
+            didErr = true;
+            err = _e2;
+          },
+          f: function f() {
+            try {
+              if (!normalCompletion && it["return"] != null) it["return"]();
+            } finally {
+              if (didErr) throw err;
+            }
+          }
+        };
+      }
+
+      function _unsupportedIterableToArray(o, minLen) {
+        if (!o) return;
+        if (typeof o === "string") return _arrayLikeToArray(o, minLen);
+        var n = Object.prototype.toString.call(o).slice(8, -1);
+        if (n === "Object" && o.constructor) n = o.constructor.name;
+        if (n === "Map" || n === "Set") return Array.from(o);
+        if (
+          n === "Arguments" ||
+          /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)
+        )
+          return _arrayLikeToArray(o, minLen);
+      }
+
+      function _arrayLikeToArray(arr, len) {
+        if (len == null || len > arr.length) len = arr.length;
+        for (var i = 0, arr2 = new Array(len); i < len; i++) {
+          arr2[i] = arr[i];
+        }
+        return arr2;
+      }
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +155,78 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag) [...]

2020-09-04 16:10 UTC, devknoll commented
Ping @Timer

2020-09-04 16:19 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.2s | ⚠️ +4ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | -600 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.365 | 2.324 | -0.04 |
| / avg req/sec | 1057.3 | 1075.62 | +18.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.426 | 1.375 | -0.05 |
| /error-in-render avg req/sec | 1753.71 | 1818.5 | +64.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..b5de.js gzip | 10.5 kB | 10.5 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-195c642..b6b7.js gzip | 7.08 kB | 7.43 kB | ⚠️ +356 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.3 kB | 57.7 kB | ⚠️ +356 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.4 kB | 6.4 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ad445e5..dule.js gzip | 6.14 kB | 6.04 kB | -101 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.3 kB | 52.2 kB | -101 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 968 B | 1 kB | ⚠️ +36 B |
| link.html gzip | 975 B | 1.01 kB | ⚠️ +36 B |
| withRouter.html gzip | 962 B | 1 kB | ⚠️ +38 B |
| Overall change | 2.9 kB | 3.02 kB | ⚠️ +110 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-f3a9e5b..24.module.js</strong></summary>

```diff
@@ -19,6 +19,9 @@
 
       exports.__esModule = true;
       exports.default = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -51,48 +54,55 @@
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
-
-        if (false) {
-        }
-
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+        var oldTags = new Set(elements);
+        components.forEach(tag => {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var { children } = tag.props;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
+            if (title !== document.title) document.title = title;
+            return;
           }
-        }
 
-        var newTags = components.map(reactElementToDOM).filter(newTag => {
-          for (var k = 0, len = oldTags.length; k < len; k++) {
-            var oldTag = oldTags[k];
+          var newTag = reactElementToDOM(tag);
 
+          for (var oldTag of elements) {
             if (oldTag.isEqualNode(newTag)) {
-              oldTags.splice(k, 1);
-              return false;
+              oldTags.delete(oldTag);
+              return;
             }
           }
 
-          return true;
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        oldTags.forEach(t => t.parentNode.removeChild(t));
-        newTags.forEach(t => headEl.insertBefore(t, headCountEl));
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
+
+        for (var oldTag of oldTags) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements.delete(oldTag);
+        }
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(entry =>
+            /*#__PURE__*/ (0, _react.createElement)(entry.type, entry.props)
+          ),
+          false
+        );
         var updatePromise = null;
         return {
           mountedInstances: new Set(),
@@ -100,25 +110,7 @@
             var promise = (updatePromise = Promise.resolve().then(() => {
               if (promise !== updatePromise) return;
               updatePromise = null;
-              var tags = {};
-              head.forEach(h => {
-                var components = tags[h.type] || [];
-                components.push(h);
-                tags[h.type] = components;
-              });
-              var titleComponent = tags.title ? tags.title[0] : null;
-              var title = "";
-
-              if (titleComponent) {
-                var { children } = titleComponent.props;
-                title =
-                  typeof children === "string" ? children : children.join("");
-              }
-
-              if (title !== document.title) document.title = title;
-              ["meta", "base", "link", "style", "script"].forEach(type => {
-                updateElements(type, tags[type] || []);
-             [...]

2020-09-04 17:58 UTC, Timer requested changes

2020-09-04 17:58 UTC, Timer commented on packages/next/client/head-manager.ts
> +    for (const oldTag of elements) {
Please make this a `forEach` so we don't polyfill iterators for `for of`.

2020-09-04 17:58 UTC, Timer commented on packages/next/client/head-manager.ts
> +  for (const oldTag of oldTags) {
Please make this a forEach so we don't polyfill iterators for for of.

2020-09-08 16:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 12s | 12.2s | ⚠️ +236ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | -629 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.307 | 2.282 | -0.02 |
| / avg req/sec | 1083.51 | 1095.34 | +11.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.512 | 1.44 | -0.07 |
| /error-in-render avg req/sec | 1653.16 | 1736.17 | +83.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-4d826ad..023b.js gzip | 7.08 kB | 6.94 kB | -138 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.4 kB | -138 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-4dbc74f..dule.js gzip | 6.14 kB | 6.02 kB | -121 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.5 kB | 52.4 kB | -121 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 970 B | 1 kB | ⚠️ +35 B |
| link.html gzip | 977 B | 1.01 kB | ⚠️ +34 B |
| withRouter.html gzip | 963 B | 999 B | ⚠️ +36 B |
| Overall change | 2.91 kB | 3.02 kB | ⚠️ +105 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-3510944..db9e3ffb3.js</strong></summary>

```diff
@@ -44,6 +44,9 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +81,53 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
-
-        if (false) {
-        }
-
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
+            if (title !== document.title) document.title = title;
+            return;
           }
-        }
 
-        var newTags = components
-          .map(reactElementToDOM)
-          .filter(function(newTag) {
-            for (var k = 0, len = oldTags.length; k < len; k++) {
-              var oldTag = oldTags[k];
-
-              if (oldTag.isEqualNode(newTag)) {
-                oldTags.splice(k, 1);
-                return false;
-              }
+          var newTag = reactElementToDOM(tag);
+          elements.forEach(function(oldTag) {
+            if (oldTag.isEqualNode(newTag)) {
+              oldTags["delete"](oldTag);
+              return;
             }
-
-            return true;
           });
-        oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        newTags.forEach(function(t) {
-          return headEl.insertBefore(t, headCountEl);
+        oldTags.forEach(function(oldTag) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements["delete"](oldTag);
         });
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(function(entry) {
+            return /*#__PURE__*/ (0,
+            _react.createElement)(entry.type, entry.props);
+          }),
+          false
+        );
         var updatePromise = null;
         return {
           mountedInstances: new Set(),
@@ -133,27 +135,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             var promise = (updatePromise = Promise.resolve().then(function() {
               if (promise !== updatePromise) return;
               updatePromise = null;
-              var tags = {};
-              head.forEach(function(h) {
-                var components = tags[h.type] || [];
-                components.push(h);
-                tags[h.type] = components;
-              });
-              var titleComponent = tags.title ? tags.title[0] : null;
- [...]

2020-09-08 16:59 UTC, ijjk commented
## Failing test suites <!--1161036440-->
Commit: 6e85b798a2f4ba45c209fafa110b71c29553ea5c

**test/integration/production/test/index.test.js** 
- Production Usage > should not clear custom performance marks

<details>
<summary>Expand output</summary>

  ● Production Usage › should not clear custom performance marks

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      815 |         }).length === 1`
      816 |       )
    > 817 |       expect(customMarkFound).toBe(true)
          |                               ^
      818 |     } finally {
      819 |       if (browser) {
      820 |         await browser.close()

      at Object.<anonymous> (integration/production/test/index.test.js:817:31)
          at runMicrotasks (<anonymous>)

</details>

2020-09-08 17:00 UTC, ijjk commented
## Failing test suites <!--1161104180-->
Commit: 443201e18f130aa752a4aa476092b7090f63228a

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      309 | 
      310 | export async function stopApp(server) {
    > 311 |   if (server.__app) {
          |              ^
      312 |     await server.__app.close()
      313 |   }
      314 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:311:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

2020-09-08 17:06 UTC, ijjk commented
## Failing test suites <!--1161130792-->
Commit: 8631f997e4544538a0757e6bff5164222840e11a

**test/integration/amphtml-fragment-style/test/index.test.js** 
- AMP Fragment Styles > adds styles from fragment in AMP mode correctly

<details>
<summary>Expand output</summary>

  ● AMP Fragment Styles › adds styles from fragment in AMP mode correctly

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)


  ● Test suite failed to run

    TypeError: Cannot read property '__app' of undefined

      309 | 
      310 | export async function stopApp(server) {
    > 311 |   if (server.__app) {
          |              ^
      312 |     await server.__app.close()
      313 |   }
      314 |   await promiseCall(server, 'close')

      at stopApp (lib/next-test-utils.js:311:14)
      at integration/amphtml-fragment-style/test/index.test.js:32:18

</details>

2020-09-08 18:36 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +73ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | -640 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.339 | 2.356 | ⚠️ +0.02 |
| / avg req/sec | 1069.02 | 1060.98 | ⚠️ -8.04 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.321 | 1.307 | -0.01 |
| /error-in-render avg req/sec | 1892.97 | 1913.23 | +20.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-4d826ad..023b.js gzip | 7.08 kB | 6.95 kB | -131 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.4 kB | -131 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-4dbc74f..dule.js gzip | 6.14 kB | 6.02 kB | -124 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.5 kB | 52.4 kB | -124 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 970 B | 1 kB | ⚠️ +33 B |
| link.html gzip | 977 B | 1.01 kB | ⚠️ +32 B |
| withRouter.html gzip | 963 B | 994 B | ⚠️ +31 B |
| Overall change | 2.91 kB | 3.01 kB | ⚠️ +96 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-3510944..db9e3ffb3.js</strong></summary>

```diff
@@ -42,8 +42,13 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +83,56 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
-
-        if (false) {
-        }
-
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
+            if (title !== document.title) document.title = title;
+            return;
           }
-        }
-
-        var newTags = components
-          .map(reactElementToDOM)
-          .filter(function(newTag) {
-            for (var k = 0, len = oldTags.length; k < len; k++) {
-              var oldTag = oldTags[k];
 
-              if (oldTag.isEqualNode(newTag)) {
-                oldTags.splice(k, 1);
-                return false;
-              }
+          var newTag = reactElementToDOM(tag);
+          elements.forEach(function(oldTag) {
+            if (oldTag.isEqualNode(newTag)) {
+              oldTags["delete"](oldTag);
+              return;
             }
-
-            return true;
           });
-        oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        newTags.forEach(function(t) {
-          return headEl.insertBefore(t, headCountEl);
+        oldTags.forEach(function(oldTag) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements["delete"](oldTag);
         });
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(function(_ref2) {
+            var _ref3 = _slicedToArray(_ref2, 2),
+              type = _ref3[0],
+              props = _ref3[1];
+
+            return /*#__PURE__*/ (0, _react.createElement)(type, props);
+          }),
+          false
+        );
         var updatePromise = null;
         return {
           mountedInstances: new Set(),
@@ -133,27 +140,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
             var promise = (updatePromise = Promise.resolve().then(function() {
               if (promise !== updatePromise) return;
               updatePromise = null;
-              var tags = {};
-              hea [...]

2020-09-08 18:46 UTC, ijjk commented
## Failing test suites <!--1161508958-->
Commit: 5b6fc47f298d4131ebd89803ac6d528d511baeaf

**test/integration/production/test/index.test.js** 
- Production Usage > should not clear custom performance marks

<details>
<summary>Expand output</summary>

  ● Production Usage › should not clear custom performance marks

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      815 |         }).length === 1`
      816 |       )
    > 817 |       expect(customMarkFound).toBe(true)
          |                               ^
      818 |     } finally {
      819 |       if (browser) {
      820 |         await browser.close()

      at Object.<anonymous> (integration/production/test/index.test.js:817:31)

</details>

2020-09-08 20:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.7s | ⚠️ +460ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | -134 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.243 | 2.27 | ⚠️ +0.03 |
| / avg req/sec | 1114.38 | 1101.52 | ⚠️ -12.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.197 | 1.187 | -0.01 |
| /error-in-render avg req/sec | 2088.31 | 2105.28 | +16.97 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-4d826ad..023b.js gzip | 7.08 kB | 6.99 kB | -88 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.5 kB | -88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-4dbc74f..dule.js gzip | 6.14 kB | 6.06 kB | -83 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.5 kB | 52.4 kB | -83 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 970 B | 1 kB | ⚠️ +35 B |
| link.html gzip | 977 B | 1.01 kB | ⚠️ +33 B |
| withRouter.html gzip | 963 B | 996 B | ⚠️ +33 B |
| Overall change | 2.91 kB | 3.01 kB | ⚠️ +101 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-3510944..db9e3ffb3.js</strong></summary>

```diff
@@ -42,8 +42,13 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +83,68 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag);
+          var elementIter = elements.values();
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
-          }
-        }
+          while (true) {
+            // Note: We don't use for-of here to avoid needing to polyfill it.
+            var _elementIter$next = elementIter.next(),
+              done = _elementIter$next.done,
+              value = _elementIter$next.value;
 
-        var newTags = components
-          .map(reactElementToDOM)
-          .filter(function(newTag) {
-            for (var k = 0, len = oldTags.length; k < len; k++) {
-              var oldTag = oldTags[k];
+            if (value.isEqualNode(newTag)) {
+              oldTags["delete"](value);
+              return;
+            }
 
-              if (oldTag.isEqualNode(newTag)) {
-                oldTags.splice(k, 1);
-                return false;
-              }
+            if (done) {
+              break;
             }
+          }
 
-            return true;
-          });
-        oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        newTags.forEach(function(t) {
-          return headEl.insertBefore(t, headCountEl);
+        oldTags.forEach(function(oldTag) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements["delete"](oldTag);
         });
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(function(_ref2) {
+            var _ref3 = _slicedToArray(_ref2, 2),
+              type = _ref3[0],
+              props = _ref3[1];
+
+            return /*#__PURE__*/ (0, _react.createElement)(type, props);
+          }),
+          false
+        );
         var updatePromise = null;
         return {
           mou [...]

2020-09-08 20:20 UTC, ijjk commented
## Failing test suites <!--1161937358-->
Commit: 339174da0b4e2d04b18c86c6d63e0ebaaab027fb

**test/integration/basic/test/index.test.js** 
- Basic Features > Dynamic import > default behavior > should render the component Head content

<details>
<summary>Expand output</summary>

  ● Basic Features › Dynamic import › default behavior › should render the component Head content

    expect(received).toBe(expected) // Object.is equality

    Expected: "200px"
    Received: "18px"

      86 |             .elementByCss('.dynamic-style')
      87 |             .getComputedCss('height')
    > 88 |           expect(height).toBe('200px')
         |                          ^
      89 |           expect(backgroundColor).toBe('rgba(0, 128, 0, 1)')
      90 |         } finally {
      91 |           if (browser) {

      at Object.<anonymous> (integration/basic/test/dynamic.js:88:26)

</details>

2020-09-08 20:57 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.3s | -292ms |
| nodeModulesSize | 56.7 MB | 56.7 MB | -103 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.198 | 2.317 | ⚠️ +0.12 |
| / avg req/sec | 1137.59 | 1079.19 | ⚠️ -58.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.482 | 1.366 | -0.12 |
| /error-in-render avg req/sec | 1687.06 | 1829.84 | +142.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-4d826ad..023b.js gzip | 7.08 kB | 7 kB | -82 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.5 kB | -82 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-4dbc74f..dule.js gzip | 6.14 kB | 6.07 kB | -77 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.5 kB | 52.4 kB | -77 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | azukaru/next.js x-fix-next-head-compat | Change |
| - | - | - | - |
| index.html gzip | 970 B | 1 kB | ⚠️ +33 B |
| link.html gzip | 977 B | 1.01 kB | ⚠️ +33 B |
| withRouter.html gzip | 963 B | 996 B | ⚠️ +33 B |
| Overall change | 2.91 kB | 3.01 kB | ⚠️ +99 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-3510944..db9e3ffb3.js</strong></summary>

```diff
@@ -42,8 +42,13 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
     /***/ DqTX: /***/ function(module, exports, __webpack_require__) {
       "use strict";
 
+      var _slicedToArray = __webpack_require__("J4zp");
+
       exports.__esModule = true;
       exports["default"] = initHeadManager;
+
+      var _react = __webpack_require__("q1tI");
+
       var DOMAttributeNames = {
         acceptCharset: "accept-charset",
         className: "class",
@@ -78,54 +83,68 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         return el;
       }
 
-      function updateElements(type, components) {
+      function updateElements(elements, components, removeOldTags) {
         var headEl = document.getElementsByTagName("head")[0];
-        var headCountEl = headEl.querySelector("meta[name=next-head-count]");
+        var oldTags = new Set(elements);
+        components.forEach(function(tag) {
+          if (tag.type === "title") {
+            var title = "";
+
+            if (tag) {
+              var children = tag.props.children;
+              title =
+                typeof children === "string" ? children : children.join("");
+            }
 
-        if (false) {
-        }
+            if (title !== document.title) document.title = title;
+            return;
+          }
 
-        var headCount = Number(headCountEl.content);
-        var oldTags = [];
+          var newTag = reactElementToDOM(tag);
+          var elementIter = elements.values();
 
-        for (
-          var i = 0, j = headCountEl.previousElementSibling;
-          i < headCount;
-          i++, j = j.previousElementSibling
-        ) {
-          if (j.tagName.toLowerCase() === type) {
-            oldTags.push(j);
-          }
-        }
+          while (true) {
+            // Note: We don't use for-of here to avoid needing to polyfill it.
+            var _elementIter$next = elementIter.next(),
+              done = _elementIter$next.done,
+              value = _elementIter$next.value;
 
-        var newTags = components
-          .map(reactElementToDOM)
-          .filter(function(newTag) {
-            for (var k = 0, len = oldTags.length; k < len; k++) {
-              var oldTag = oldTags[k];
+            if (value == null ? void 0 : value.isEqualNode(newTag)) {
+              oldTags["delete"](value);
+              return;
+            }
 
-              if (oldTag.isEqualNode(newTag)) {
-                oldTags.splice(k, 1);
-                return false;
-              }
+            if (done) {
+              break;
             }
+          }
 
-            return true;
-          });
-        oldTags.forEach(function(t) {
-          return t.parentNode.removeChild(t);
+          elements.add(newTag);
+          headEl.appendChild(newTag);
         });
-        newTags.forEach(function(t) {
-          return headEl.insertBefore(t, headCountEl);
+        oldTags.forEach(function(oldTag) {
+          if (removeOldTags) {
+            oldTag.parentNode.removeChild(oldTag);
+          }
+
+          elements["delete"](oldTag);
         });
-        headCountEl.content = (
-          headCount -
-          oldTags.length +
-          newTags.length
-        ).toString();
       }
 
-      function initHeadManager() {
+      function initHeadManager(initialHeadEntries) {
+        var headEl = document.getElementsByTagName("head")[0];
+        var elements = new Set(headEl.children);
+        updateElements(
+          elements,
+          initialHeadEntries.map(function(_ref2) {
+            var _ref3 = _slicedToArray(_ref2, 2),
+              type = _ref3[0],
+              props = _ref3[1];
+
+            return /*#__PURE__*/ (0, _react.createElement)(type, props);
+          }),
+          false
+        );
         var updatePromise = null;
         retu [...]

2020-09-09 01:41 UTC, Timer approved these changes

2020-09-09 01:41 UTC, merged