upgrade react to v15.5 and use prop-types instead of React.PropTypes
vercel/next.js pull request #1684
Opened 2017-04-10 07:00 UTC by chentsulin

Use `react-codemod` to transform the prop-types

2017-04-10 10:55 UTC, ooade commented
Would have been my first PR here :smile:

2017-04-10 10:56 UTC, ooade requested changes
https://github.com/zeit/next.js/blob/master/server/document.js ???

2017-04-10 17:05 UTC, arunoda commented
In this case I'd like to see the changes in all of these: https://github.com/zeit/next.js/search?utf8=%E2%9C%93&q=PropTypes&type=

2017-04-10 17:06 UTC, arunoda commented on package.json
> +    "react": "^15.5.3",
We don't need to bump this.
Just using `prop-types` is enough.

2017-04-10 18:00 UTC, chentsulin commented
Already updated the pr against the comments

2017-04-10 18:31 UTC, arunoda commented
Okay. This looks great to me.

2017-04-10 18:35 UTC, merged

2017-04-21 08:29 UTC, ooade commented
@bbnnt It's not from your edge. BTW, It's bin resolved but not yet published.

2017-04-21 08:31 UTC, bbnnt commented
ok got it, thx for your rep