Upgrade css and sass loaders
vercel/next.js pull request #16970
Opened 2020-09-09 19:05 UTC by TrySound

- https://github.com/webpack-contrib/sass-loader/releases/tag/v10.0.0
- https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0
- https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0

2020-09-09 19:13 UTC, ijjk commented
## Failing test suites <!--1167411625-->
Commit: d1cf9c3a7e5746a28edafffcdd0bcc52e365295f

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from red to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from blue to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to red

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to blue

    command failed with code 1

      132 |         code !== 0
      133 |       ) {
    > 134 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      135 |       }
      136 | 
      137 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:134:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      275 | export async function killApp(instance) {
      276 |   await new Promise((resolve, reject) => {
    > 277 |     treeKill(instance.pid, (err) => {
          |                       ^
      278 |       if (err) {
      279 |         if (
      280 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:277:23
      at killApp (lib/next-test-utils.js:276:9)
      at integration/css-client-nav/test/index.test.js:34:11

</details>

2020-09-09 19:15 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.2s | -554ms |
| nodeModulesSize | 56.7 MB | 56.6 MB | -135 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.677 | 2.618 | -0.06 |
| / avg req/sec | 933.75 | 954.97 | +21.22 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.538 | 1.567 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1624.96 | 1595.69 | ⚠️ -29.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6743a22..e6ce.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-3b374ae..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 14.6s | 15s | ⚠️ +443ms |
| nodeModulesSize | 56.7 MB | 56.6 MB | -135 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..a2cc.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6743a22..e6ce.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.62 kB | 6.62 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-3b374ae..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.31 MB | 5.31 MB | ✓ |

</details>

</details>
Commit: d1cf9c3a7e5746a28edafffcdd0bcc52e365295f

2020-09-10 09:17 UTC, timneutkens requested changes
Looks like this broke a lot of the CSS tests.

2020-09-10 09:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.3s | ⚠️ +51ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.412 | 2.435 | ⚠️ +0.02 |
| / avg req/sec | 1036.65 | 1026.74 | ⚠️ -9.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.36 | 1.279 | -0.08 |
| /error-in-render avg req/sec | 1838.19 | 1954.48 | +116.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..6177.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ee619e3..fb8c.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.63 kB | 6.63 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f1103fb..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 995 B | 995 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.8s | ⚠️ +100ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..6177.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ee619e3..fb8c.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.63 kB | 6.63 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f1103fb..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.31 MB | 5.31 MB | ✓ |

</details>

</details>
Commit: 29b2637126b007fe48428c60d91e24c673b2c214

2020-09-10 09:58 UTC, ijjk commented
## Failing test suites <!--1170533143-->
Commit: 29b2637126b007fe48428c60d91e24c673b2c214

**test/integration/typescript/test/index.test.js** 
- TypeScript Features > should build the app
- TypeScript Features > default behavior > should render the page
- TypeScript Features > default behavior > should resolve files in correct order
- TypeScript Features > default behavior > should respond to sync API route correctly
- TypeScript Features > default behavior > should respond to async API route correctly
- TypeScript Features > default behavior > should not fail to render when an inactive page has an error
- TypeScript Features > should compile with different types > should compile async getInitialProps for _error

<details>
<summary>Expand output</summary>

  ● TypeScript Features › default behavior › should render the page

    expect(received).toMatch(expected)

    Expected pattern: /Hello World/
    Received string:  "{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleBuildError\",\"message\":\"Module build failed (from /home/runner/work/next.js/next.js/node_modules/sass-loader/dist/cjs.js):\\nValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.\\n - options has an unknown property 'prependData'. These properties are valid:\\n   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }\\n    at validate (/home/runner/work/next.js/next.js/node_modules/schema-utils/dist/validate.js:98:11)\\n    at Object.loader (/home/runner/work/next.js/next.js/node_modules/sass-loader/dist/index.js:30:28)\",\"stack\":\"ModuleBuildError: Module build failed (from /home/runner/work/next.js/next.js/node_modules/sass-loader/dist/cjs.js):\\nValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.\\n - options has an unknown property 'prependData'. These properties are valid:\\n   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }\\n    at validate (/home/runner/work/next.js/next.js/node_modules/schema-utils/dist/validate.js:98:11)\\n    at Object.loader (/home/runner/work/next.js/next.js/node_modules/sass-loader/dist/index.js:30:28)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/NormalModule.js:316:20\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:367:11\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:233:18\\n    at runSyncOrAsync (/home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:143:3)\\n    at iterateNormalLoaders (/home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:232:2)\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:205:4\\n    at /home/runner/work/next.js/next.js/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15\\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)\"},\"gip\":true,\"head\":[[\"meta\",{\"charSet\":\"utf-8\"}],[\"meta\",{\"name\":\"viewport\",\"content\":\"width=device-width\"}]]}"

      43 |     it('should render the page', async () => {
      44 |       const $ = await get$('/hello')
    > 45 |       expect($('body').text()).toMatch(/Hello World/)
         |                                ^
      46 |       expect($('body').text()).toMatch(/1000000000000/)
      47 |     })
      48 | 

      at Object.<anonymous> (integration/typescript/test/index.test.js:45:32)

  ● TypeScript Features › default behavior › should resolve files in correct order

    expect(received).toBe(expected) // Object.is equality

    Expected: "OK"
    Received: ""

      49 |     it('should resolve files in correct order', async () => {
      50 |       const $ = await get$('/hello')
    > 51 |       expect($('#imported-value').text()).toBe('OK')
         |                                           ^
      52 |     })
      53 | 
      54 |     // old behavior:

      at Object.<anonymous> (integration/typescript/test/index.test.js:51:43)

  ● TypeScript Features › default behavior › should respond to sync API route correctly

    SyntaxError: Unexpected token < in JSON at position 0
        at JSON.parse (<anonymous>)

      58 | 
      59 |     it('should respond to sync API route correctly', async () => {
    > 60 |       const data = JSON.parse(await renderViaHTTP(appPort, '/api/sync'))
         |                         ^
      61 |       expect(data).toEqual({ code: 'ok' })
      62 |     })
      63 | 

      at Object.<anonymous> (integration/typescript/test/index.test.js:60:25)

  ● TypeScript Features › default behavior › should respond to async API route correctly

    SyntaxError: Unexpected token < in JSON at position 0
        at JSON.parse (<anonymous>)

      63 | 
      64 |     it('should respond to async API route correctly', async () => {
    > 65 |       const data = JSON.parse(await renderViaHTTP(appPort, '/api/async'))
         |                         ^
      66 |       expect(data).toEqual({ code: 'ok' })
      67 |     })
      68 | 

      at Object.<anonymous> (integration/typescript/test/index.test.js:65:25)

  ● TypeScript Features › default behavior › should not fail to render when an inactive page has an error

    expect(received).toMatch(expected)

    Expected pattern: /Hello World/
    Received string:  "{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleBuildError\",\"message\":\"Module build failed (from /home/runner/work/next.js/next.js/node_modules/sass-loader/dist/cjs.js):\\nValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.\\n - options has an unknown property 'prependData'. These properties are valid:\\n   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }\\n    at validate (/home/runner/work/next.js/next.js/node_modules/schema-utils/dist/validate.js:98:11)\\n    at Object.loader (/home/runner/work/next.js/next.js/node_modules/sass-loader/dist/index.js:30:28)\",\"stack\":\"ModuleBuildError: Module build failed (from /home/runner/work/next.js/next.js/node_modules/sass-loader/dist/cjs.js):\\nValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.\\n - options has an unknown property 'prependData'. These properties are valid:\\n   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }\\n    at validate (/home/runner/work/next.js/next.js/node_modules/schema-utils/dist/validate.js:98:11)\\n    at Object.loader (/home/runner/work/next.js/next.js/node_modules/sass-loader/dist/index.js:30:28)\\n    at /home/runner/work/next.js/next.js/node_modules/webpack/lib/NormalModule.js:316:20\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:367:11\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:233:18\\n    at runSyncOrAsync (/home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:143:3)\\n    at iterateNormalLoaders (/home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:232:2)\\n    at /home/runner/work/next.js/next.js/node_modules/loader-runner/lib/LoaderRunner.js:205:4\\n    at /home/runner/work/next.js/next.js/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15\\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)\"},\"gip\":true,\"head\":[[\"meta\",{\"charSet\":\"utf-8\"}],[\"meta\",{\"name\":\"viewport\",\"content\":\"width=device-width\"}]]}"

      83 | 
      84 |         [...]

2020-09-10 10:01 UTC, TrySound commented
@timneutkens Rebased css-loader upgrade. Now I see only typescript tests failed. Is this related to sass?

2020-09-10 11:50 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 12.3s | 13s | ⚠️ +738ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.319 | 2.511 | ⚠️ +0.19 |
| / avg req/sec | 1077.82 | 995.52 | ⚠️ -82.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.371 | 1.558 | ⚠️ +0.19 |
| /error-in-render avg req/sec | 1823.19 | 1604.79 | ⚠️ -218.4 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..6177.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ee619e3..fb8c.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.63 kB | 6.63 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f1103fb..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 995 B | 995 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.5s | -63ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..6177.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-ee619e3..fb8c.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.5 kB | 57.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.63 kB | 6.63 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-f1103fb..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.4 kB | 52.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.03 MB | 1.03 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.31 MB | 5.31 MB | ✓ |

</details>

</details>
Commit: 032f69305773aab1489cdc993237c24d7ba99a9b

2020-09-10 20:22 UTC, merceyz commented
If merged this fixes https://github.com/vercel/next.js/issues/15753

2020-09-11 08:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14s | ⚠️ +168ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.538 | 2.515 | -0.02 |
| / avg req/sec | 984.94 | 993.88 | +8.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.578 | 1.626 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1583.91 | 1537.43 | ⚠️ -46.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..68c9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-7ae8495..db56.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-5a735ed..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.6 kB | 52.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.4s | -53ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..68c9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-7ae8495..db56.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-5a735ed..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.6 kB | 52.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.04 MB | 1.04 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.31 MB | 5.31 MB | ✓ |

</details>

</details>
Commit: 5e801537605808234fb3b360d7dba9c56516731b

2020-09-11 10:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.5s | -84ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.703 | 2.658 | -0.04 |
| / avg req/sec | 924.99 | 940.38 | +15.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.675 | 1.564 | -0.11 |
| /error-in-render avg req/sec | 1492.1 | 1598.85 | +106.75 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..68c9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-7ae8495..db56.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-5a735ed..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.6 kB | 52.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| buildDuration | 15.8s | 16s | ⚠️ +206ms |
| nodeModulesSize | 57 MB | 56.6 MB | -421 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..68c9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-7ae8495..db56.js gzip | 7 kB | 7 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.6 kB | 57.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.77 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-5a735ed..dule.js gzip | 6.07 kB | 6.07 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.6 kB | 52.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | TrySound/next.js upgrade-css-loaders | Change |
| - | - | - | - |
| _error.js | 1.03 MB | 1.03 MB | ✓ |
| 404.html | 4.34 kB | 4.34 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.04 MB | 1.04 MB | ✓ |
| link.js | 1.08 MB | 1.08 MB | ✓ |
| routerDirect.js | 1.07 MB | 1.07 MB | ✓ |
| withRouter.js | 1.07 MB | 1.07 MB | ✓ |
| Overall change | 5.31 MB | 5.31 MB | ✓ |

</details>

</details>
Commit: 9821e149296d31e978c897aea16dee44588c768c

2020-09-11 12:36 UTC, timneutkens approved these changes

2020-09-11 12:36 UTC, merged

2020-09-11 12:37 UTC, timneutkens commented
Thanks!