feat: SSR fetch function to be customizable
vercel/next.js pull request #17655
Opened 2020-10-06 15:01 UTC by stegano

In the case of using getServerSideProps, the customized fetch function can be used when requesting data about the page from the browser.

By using this function, when a browser requests data about a page, it can be transmitted including the client's status information, and the server can use the client's status information for more flexible processing.

2020-10-06 15:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| buildDuration | 14.3s | 14.3s | -61ms |
| nodeModulesSize | 63.2 MB | 63.2 MB | ⚠️ +2.59 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.607 | 2.65 | ⚠️ +0.04 |
| / avg req/sec | 958.91 | 943.49 | ⚠️ -15.42 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.64 | 1.696 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1524.85 | 1474.47 | ⚠️ -50.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| 677f882d2ed8..9339.js gzip | 10.9 kB | 11 kB | ⚠️ +50 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e5f5aee..31e1.js gzip | 7.17 kB | 7.21 kB | ⚠️ +38 B |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 57.8 kB | 57.9 kB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 6.77 kB | 6.8 kB | ⚠️ +34 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-ff4dea7..dule.js gzip | 6.24 kB | 6.28 kB | ⚠️ +40 B |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 52.7 kB | 52.8 kB | ⚠️ +74 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d2344ce..8b36.js gzip | 1.3 kB | 1.3 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.71 kB | 7.71 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-f8c0daf..dule.js gzip | 1.26 kB | 1.26 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.36 kB | 5.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 329 B | 329 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | stegano/next.js feature/custom-ss-props-fetcher | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | -2 B |
| withRouter.html gzip | 996 B | 995 B | -1 B |
| Overall change | 3.01 kB | 3 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..5fa35cac6.js</strong></summary>

```diff
@@ -917,8 +917,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
       var manualScrollRestoration = false && false;
 
-      function fetchRetry(url, attempts) {
-        return fetch(url, {
+      function fetchRetry(url, attempts, customFetcher) {
+        var fetcher =
+          typeof customFetcher === "function" ? customFetcher : fetch;
+        return fetcher(url, {
           // Cookies are required to be present for Next.js' SSG "Preview Mode".
           // Cookies may also be required for `getServerSideProps`.
           //
@@ -934,7 +936,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }).then(function(res) {
           if (!res.ok) {
             if (attempts > 1 && res.status >= 500) {
-              return fetchRetry(url, attempts - 1);
+              return fetchRetry(url, attempts - 1, customFetcher);
             }
 
             throw new Error("Failed to load static props");
@@ -944,10 +946,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         });
       }
 
-      function fetchNextData(dataHref, isServerRender) {
-        return fetchRetry(dataHref, isServerRender ? 3 : 1)["catch"](function(
-          err
-        ) {
+      function fetchNextData(dataHref, isServerRender, customFetcher) {
+        return fetchRetry(dataHref, isServerRender ? 3 : 1, customFetcher)[
+          "catch"
+        ](function(err) {
           // We should only trigger a server-side transition if this was caused
           // on a client-side transition. Otherwise, we'd get into an infinite
           // loop.
@@ -1740,6 +1742,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                     _require,
                     isValidElementType,
                     dataHref,
+                    customFetcher,
                     props,
                     _args3 = arguments;
 
@@ -1830,23 +1833,32 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                             );
 
                           case 18:
-                            if (__N_SSG || __N_SSP) {
-                              dataHref = this.pageLoader.getDataHref(
-                                (0, _utils.formatWithValidation)({
-                                  pathname: pathname,
-                                  query: query
-                                }),
-                                delBasePath(as),
-                                __N_SSG
-                              );
+                            if (!(__N_SSG || __N_SSP)) {
+                              _context3.next = 23;
+                              break;
                             }
 
-                            _context3.next = 21;
+                            dataHref = this.pageLoader.getDataHref(
+                              (0, _utils.formatWithValidation)({
+                                pathname: pathname,
+                                query: query
+                              }),
+                              delBasePath(as),
+                              __N_SSG
+                            );
+                            _context3.next = 22;
+                            return this.pageLoader.getCustomFetcher(route);
+
+                          case 22:
+                            customFetcher = _context3.sent;
+
+                          case 23:
+                            _context3.next = 25;
                             return this._getData(function() {
                               return __N_SSG
-                                ? _this3._getStaticData(dataHref)
+                                ? _this3._getStaticData(dataH [...]

2020-10-06 15:15 UTC, ijjk commented
## Failing test suites <!--1297136877-->
Commit: 974d4295e188e1dc47fc5bc209f6bf14806c5694

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

      102 |       expect(err404Size.endsWith('kB')).toBe(true)
      103 | 
    > 104 |       expect(parseFloat(err404FirstLoad) - 63.8).toBeLessThanOrEqual(0)
          |                                                  ^
      105 |       expect(err404FirstLoad.endsWith('kB')).toBe(true)
      106 | 
      107 |       expect(parseFloat(sharedByAll) - 60.4).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:104:50)

</details>

2020-10-06 15:27 UTC, lfades requested changes
@stegano 👋 

Changes like this have to start with an RFC where we can discuss why is this needed, what are the use cases and how should be the implementation. That way we can reach a consensus before you start adding any code/work to it

2020-10-06 15:32 UTC, stegano commented
@lfades Okay 👌👌 Thanks for letting me know 😀
I'll close this issue 😭

2020-10-06 15:32 UTC, closed without merging

2020-10-10 12:42 UTC, stegano commented
I wrote an RFC in the discussion tab.
but, no one seems to be interested... 🥺

2020-10-11 04:06 UTC, lfades commented
@stegano I read it, and even though I understand what it's for, it's probably much better to provide use cases for it, something that can't be done in another way and it's very useful!

2020-10-11 04:18 UTC, stegano commented
> @stegano I read it, and even though I understand what it's for, it's probably much better to provide use cases for it, something that can't be done in another way and it's very useful!

Thanks for your advice 😀