Update GetStaticPathsResult type
vercel/next.js pull request #18814
Opened 2020-11-04 21:03 UTC by whitneyit

Currently, the `GetStaticPathsResult` type exposes two properties,
`paths`, and `fallback`.

The definitions for these properties are inline, meaning, the only way
to access them is with some pretty ugly looking TypeScript code.

```ts
type ArrayType<T extends Array<any> | ReadonlyArray<any>> = T extends Array<infer R>
  ? R
  : T extends ReadonlyArray<infer R>
  ? R
  : never;

type GetStaticPathsPath = ArrayType<GetStaticPathsResult<PostQuery>['paths']>;

type GetStaticPathsFallback = GetStaticPathsResult<PostQuery>['fallback'];
```

The use case for `GetStaticPathsPath` can be seen below:

```ts
export const getStaticPaths: GetStaticPaths<PostQuery> = async (
  ctx: GetStaticPathsContext,
): Promise<GetStaticPathsResult<PostQuery>> => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=3`);
  const posts = (await res.json()) as Array<Post>;
  const paths = posts.map((post: Post): GetStaticPathsPath<PostQuery> => {
    return {
      params: {
        postId: String(post.id),
      },
    };
  });
  return {
    paths,
    fallback: `blocking`,
  };
};
```

In the above example, `GetStaticPathsPath` is used to type hint the
return type for the `.map()` Function.

Coming up with an example for `GetStaticPathsFallback` is a bit more
contrived. That being said, the type is added to ensure consistency.

The tslint [`typedef`](https://palantir.github.io/tslint/rules/typedef/)
linting rule has the ability to enforce return types. Adding these types
would reduce friction for teams that use the `typedef` linting rule.

Furthermore, it would also allow developers who want to type hint the
return value of the `.map()` Function to not have to go to the trouble
of creating these work around types.

2020-11-04 21:16 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.5s | -352ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.642 | 2.625 | -0.02 |
| / avg req/sec | 946.37 | 952.32 | +5.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.395 | 1.414 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1792.5 | 1767.76 | ⚠️ -24.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 994 B | 994 B | ✓ |
| Overall change | 3 kB | 3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| buildDuration | 15.6s | 16.1s | ⚠️ +488ms |
| nodeModulesSize | 90.5 MB | 90.5 MB | ⚠️ +169 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-be398bc..d262.js gzip | 7.33 kB | 7.33 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.3 kB | 58.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-378f0c6..dule.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | whitneyit/next.js feature/update-get-static-paths-result-type | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: 8d3c81700129c2ed9b19a37e33ef2538331fd84b

2020-11-05 15:43 UTC, lfades requested changes
@whitneyit Hi there and thank you for the PR 👋 

TypeScript can infer the return type of your map function, if it matches the return type for the getStaticPaths method then you're typing it entirely while using less code. Your code sample is quite confusing and I don't see this as something we want to add to the core types or to docs because type inferring works very well for cases like this one.

> The tslint typedef
linting rule has the ability to enforce return types. Adding these types
would reduce friction for teams that use the typedef linting rule.

We don't add types based on linter rules

> Furthermore, it would also allow developers who want to type hint the
return value of the .map() Function to not have to go to the trouble
of creating these work around types.

You don't have to.

2020-11-05 15:43 UTC, closed without merging

2020-11-05 22:04 UTC, whitneyit commented
Hi @lfades, thanks for taking the time to consider this PR. I still think that it is worth considering. TypeScripts's inference capabilities are pretty outstanding, I agree. There are use cases though, (in the codebase that I am working on at least), where the creations of the `paths` Object is not created from within the `getStaticPaths` Function.

Consider this example:

```ts
function createPostsPaths() {
  // TODO
}
```

There is no inference here that TypeScript can help with. Adding the `GetStaticPathsPath` type allows for the following:

```ts
function createPostsPaths(): Array<GetStaticPathsPath<PostQuery>> {
  // TODO
}
```



> Your code sample is quite confusing

Perhaps I didn't demonstrate my original example clearly. Ultimately, this PR boils down to being able to type hint a return type as seen above, or as in the original comment. Like so:

```ts
const paths = posts.map((post: Post): GetStaticPathsPath<PostQuery> => {
  return {
    params: {
      postId: String(post.id),
    },
  };
});
```

Not having the `GetStaticPathsPath` type means that developers would need to jump through hoops discuss in the original comment to support it.

In regards to your points;

> We don't add types based on linter rules

I wouldn't expect this either. I would argue that it is not _because_ of the linting rule itself, it is because of what that rule _represents_. The desire from the TypeScript community to be able to explicitly type hint their code. This linting rules helps enforce that desire. This PR would aid at reducing the friction to do so.

> You don't have to.

Of course you don't have to! But what if you want to? This feature request is because teams that I am a part of, (and others for that matter - probably), _do_ want to have explicit type hinting 😄 

Regardless, if a user doesn't want to use this type, they don't have to use it.

Thanks again mate.

2020-11-05 23:30 UTC, lfades commented
@whitneyit We don't try to serve every possible use case with our types, only the ones that make the most sense and are not possible without updating our types. Do keep in mind that the more types we add, the more difficult it's to document them in a way that makes sense (we won't document all possible use cases if some are better), and the more code we have to ship to npm.

In your case, if you use `GetStaticPaths<PostQuery>` and then use the match function without assigning any return type to it, like this:

```ts
function createPostsPaths() {
  // TODO
}
```

If you then try to use it to set the types, TS will validate that the return type of the function matches `GetStaticPaths<PostQuery>`, you're getting the same validation benefits without adding more code.