Improve and expand .env file loading
vercel/next.js pull request #18821
Opened 2020-11-04 23:52 UTC by mattcarlotta

Note: The previous pull request ran into some git branching issues and it became a pain to update, so I created a new pull request.

### Proposal
I've developed an alternative to dotenv and dotenv-expand called snackables. Snackables accomplishes what is achieved by dotenv and dotenv-expand with some improvements and additional features like: custom root directory paths, single or multiple .env file preloading, single or multiple .env paths, optional `process.env` overriding, and caching/utilizing parsed file contents. The purpose of this package is to keep everything within one encapsulated loop for a server configuration (with smaller additional loops for value interpolation) and a small additional loop for a serverless configuration. In terms of performance, snackables is **up to 50% faster than dotenv and dotenv-expand** and **up to 80% faster than Next's current implementation**. In addition, like dotenv, snackables is unopinionated about file naming and is therefore compatible with the standard Next `.env` file priority and naming conventions.

In summation, snackables will handle the reading, parsing, caching and assigning ENVs by replacing the [current approach](https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts) with the following [code](https://github.com/mattcarlotta/next.js/blob/snackables/packages/next-env/index.ts).

### Documentation and Source Materials

[Instructions](https://github.com/mattcarlotta/snackables/blob/main/README.md)
[Source](https://github.com/mattcarlotta/snackables/blob/main/index.ts)
[Dependencies](https://bundlephobia.com/result?p=snackables@)
[npmjs](https://www.npmjs.com/package/snackables)

### Build stats

| package | files | unpacked | minified | gzipped | download time | coverage |
| --- | --- | --- | --- | --- | --- | --- |
| snackables | 5 | 28.1kB | 2kB |  1.1kB  | 37ms (2G) / 22ms (3G) | 100% |
| denv+denv-exp | 18 | 39.0kB | 1.8kB |  1kB  | 35ms (2G) / 21ms (3G) | 100% |

### Tests
Some rudimentary non-caching [tests](https://github.com/mattcarlotta/snackables-v-dotenv-v-next).

Loading and interpolating a single [small env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables | default | 500,000 | 16.67s, 16.79s, 16.90s | 16.79s | 100% |
| denv+denv-exp | default | 500,000 | 23.86s, 24.06s, 24.10s | 24.00s | 69.96% |
| next | .env only | 500,000 | 82.22s, 84.57s, 85.59s | 84.13s | 19.96% |

Loading and interpolating a single [large env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.interp):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest  |
| --- | --- | --- | --- | --- | --- |
| snackables | .env.interp only | 5,000 | 36.38s, 36.45s, 36.46s | 36.53s | 100% |
| denv+denv-exp | .env.interp only | 5,000 | 72.82s, 73.19s, 75.21s | 73.74s | 49.54% | 
| next | .env.interp only | 5,000 | 88.94s, 91.59s, 91.68s | 90.74s | 40.26% |

Loading and interpolating multiple small env files ([1](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env), [2](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development), [3](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.local), [4](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development.local)):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables | .env, .env.development, .env.local, .env.development.local | 500,000 | 32.05s, 32.12s, 32.33s | 32.17s | 100% |
| denv+denv-exp | - | - | - | - | - |
| next | default (for development) | 500,000 | 104.54s, 104.77s, 105.79s | 105.03s | 30.63% |

2020-11-05 00:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.6s | ⚠️ +158ms |
| nodeModulesSize | 90.1 MB | 90.1 MB | -216 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.37 | 2.392 | ⚠️ +0.02 |
| / avg req/sec | 1054.83 | 1045.16 | ⚠️ -9.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.306 | 1.269 | -0.04 |
| /error-in-render avg req/sec | 1913.99 | 1969.85 | +55.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1bcbf27..3cd1.js gzip | 7.41 kB | 7.41 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e11a5d3..dule.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 995 B | 995 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.6s | ⚠️ +12ms |
| nodeModulesSize | 90.1 MB | 90.1 MB | -216 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..1f3c.js gzip | 11.2 kB | 11.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1bcbf27..3cd1.js gzip | 7.41 kB | 7.41 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.02 kB | 7.02 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-e11a5d3..dule.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-9a0b9e1..b37e.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-ed1b0..8fbd.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-89731c..c609.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 322 B | 322 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 652 B | 652 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.48 MB | 5.48 MB | ✓ |

</details>

</details>
Commit: 2ffcb8f78ba10dca3c7b9a186deff74c80532656

2020-11-05 17:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 13.3s | 14.7s | ⚠️ +1.4s |
| nodeModulesSize | 87 MB | 87 MB | -216 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.374 | 2.553 | ⚠️ +0.18 |
| / avg req/sec | 1053.2 | 979.31 | ⚠️ -73.89 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.257 | 1.269 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1988.72 | 1970.82 | ⚠️ -17.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-5b72373..17dd.js gzip | 7.37 kB | 7.37 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-2d01f96..dule.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html gzip | 1.01 kB | 1.01 kB | ✓ |
| withRouter.html gzip | 996 B | 996 B | ✓ |
| Overall change | 3.01 kB | 3.01 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 16.7s | 16.5s | -189ms |
| nodeModulesSize | 87 MB | 87 MB | -216 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..7d3b.js gzip | 11.3 kB | 11.3 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-5b72373..17dd.js gzip | 7.37 kB | 7.37 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.4 kB | 58.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 7.04 kB | 7.04 kB | ✓ |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-2d01f96..dule.js gzip | 6.37 kB | 6.37 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.1 kB | 53.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-b5..1119.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-7231d4b..5856.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-fca3d..2eb1.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4591d..e7c2.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-a674d88..ccde.js gzip | 1.35 kB | 1.35 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.75 kB | 7.75 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-4469a..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-a4469f3..dule.js gzip | 1.32 kB | 1.32 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.41 kB | 5.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _error.js | 1.07 MB | 1.07 MB | ✓ |
| 404.html | 4.73 kB | 4.73 kB | ✓ |
| hooks.html | 3.92 kB | 3.92 kB | ✓ |
| index.js | 1.07 MB | 1.07 MB | ✓ |
| link.js | 1.12 MB | 1.12 MB | ✓ |
| routerDirect.js | 1.11 MB | 1.11 MB | ✓ |
| withRouter.js | 1.11 MB | 1.11 MB | ✓ |
| Overall change | 5.49 MB | 5.49 MB | ✓ |

</details>

</details>
Commit: b4d1c70c77a12e1daa062110ffe6a31946308ca7

2020-11-07 18:11 UTC, Timer requested changes
We do not want to add any new env loading behavior. Happy to entertain this PR if it changes zero behavior.

2020-11-07 19:36 UTC, mattcarlotta commented
> We do not want to add any new env loading behavior. Happy to entertain this PR if it changes zero behavior.

I removed the ENV overrides, so Next will only be able to load the [predefined defaults](https://github.com/mattcarlotta/next.js/blob/snackables/packages/next-env/index.ts#L40-L48). However, there's only one minor issue: Defining an `ENV_LOAD` variable within the package.json scripts/CLI will load user defined .env files when the `snackables` package is imported (this **WILL NOT** prevent Next's defaults from being loaded). The base dotenv package has a [similar setup](https://github.com/motdotla/dotenv#preload), although it separates the [IFFE](https://github.com/motdotla/dotenv/blob/master/config.js) to its own file, whereas snackables keeps its [IFFE](https://github.com/mattcarlotta/snackables/blob/main/index.ts#L246-L272) within the default import. 

The reason the IFFE was moved to the default import was to: 
- Reduce build output size
- Reduce the `import`/`require` statement boilerplate required to load .env files -- you no longer need to manually invoke the `config()` method if `ENV_LOAD` was defined; instead, importing the base package would invoke the IFFE, which would invoke the `config()` method for you


If this is an issue, then there's 3 ways to resolve it:
1.) Simply leave `ENV_LOAD` undocumented within Next's documentation
2.) Within Next, remove the `ENV_LOAD` variable before importing the `snackables` package: `if(process.env.ENV_LOAD !=  null) delete process.env.ENV_LOAD`
3.) Within snackables, implement an additional ENV variable that prevents `ENV_LOAD` from loading

2020-11-08 04:47 UTC, mattcarlotta commented
@Timer 

I went ahead and resolved an issue I mentioned [here](https://github.com/vercel/next.js/pull/18821#issuecomment-723485735) by creating a [package]((https://github.com/mattcarlotta/snackables-next)) specifically for Next -- I figured there's no use shipping dead code. In short, I stripped out preloading and ENV overrides by removing the IFFE. As is, the package mimics dotenv+dotenv-expand but with a smaller build output and better performances (see stats below). Since this package is now tailored for Next, I could even hardcode [this piece of code](https://github.com/mattcarlotta/next.js/blob/snackables/packages/next-env/index.ts#L28-L33) and [this piece of code](https://github.com/mattcarlotta/next.js/blob/snackables/packages/next-env/index.ts#L39-L53) into the package. But, for now, I've left it similar to dotenv.

### Documentation and Source Materials

[Instructions](https://github.com/mattcarlotta/snackables-next/blob/main/README.md)
[Source](https://github.com/mattcarlotta/snackables-next/blob/main/index.ts)
[Dependencies](https://bundlephobia.com/result?p=snackables-next@)
[npmjs](https://www.npmjs.com/package/snackables-next)

### Build stats

| package | files | unpacked | minified | gzipped | download time | coverage |
| --- | --- | --- | --- | --- | --- | --- |
| snackables-next | 5 | 20.1kB | 1.7kB |  989kB  | 32ms (2G) / 19ms (3G) | 100% |
| denv+denv-exp | 18 | 39.0kB | 1.8kB |  1kB  | 35ms (2G) / 21ms (3G) | N/A |


### Tests
Some rudimentary non-caching [tests](https://github.com/mattcarlotta/snackables-v-dotenv-v-next).

Loading and interpolating a single [small env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables-next | default | 500,000 | 16.46s, 16.48s, 16.54s | 16.49s | 100% |
| denv+denv-exp | default | 500,000 | 23.86s, 24.06s, 24.10s | 24.00s | 68.71% |
| next | .env only | 500,000 | 82.22s, 84.57s, 85.59s | 84.13s | 19.60% |

Loading and interpolating a single [large env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.interp):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest  |
| --- | --- | --- | --- | --- | --- |
| snackables-next | .env.interp only | 5,000 | 32.82s, 32.83s, 32.87s | 32.84s | 100% |
| denv+denv-exp | .env.interp only | 5,000 | 72.82s, 73.19s, 75.21s | 73.74s | 44.53% | 
| next | .env.interp only | 5,000 | 88.94s, 91.59s, 91.68s | 90.74s | 36.19% |

Loading and interpolating multiple small env files ([1](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env), [2](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development), [3](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.local), [4](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development.local)):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables-next | .env, .env.development, .env.local, .env.development.local | 500,000 | 30.95s, 31.34s, 31.43s | 31.24s | 100% |
| denv+denv-exp | - | - | - | - | - |
| next | default (for development) | 500,000 | 104.54s, 104.77s, 105.79s | 105.03s | 29.74% |

2020-11-19 22:44 UTC, mattcarlotta commented
@Timer 

I managed to increase env file loading performance by another 5-15%. If you're still interested in this proposal, let me know and I can make any necessary adjustments. Otherwise, feel free to close this PR if you guys ultimately decide not integrate it.

### Documentation and Source Materials

[Instructions](https://github.com/mattcarlotta/snackables-next/blob/main/README.md)
[Source](https://github.com/mattcarlotta/snackables-next/blob/main/index.ts)
[Dependencies](https://bundlephobia.com/result?p=snackables-next@)
[npmjs](https://www.npmjs.com/package/snackables-next)

### Build stats

| package | files | unpacked | minified | gzipped | download time | coverage |
| --- | --- | --- | --- | --- | --- | --- |
| snackables-next | 5 | 20kB | 1.7kB |  985kB  | 32ms (2G) / 19ms (3G) | 100% |
| denv+denv-exp | 18 | 39.0kB | 1.8kB |  1kB  | 35ms (2G) / 21ms (3G) | 100% |


### Tests
Some rudimentary non-caching [tests](https://github.com/mattcarlotta/snackables-v-dotenv-v-next).

Loading and interpolating a single [small env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables-next | default (.env only) | 500,000 | 13.67s, 13.68s, 13.77s | 13.71s | 100% |
| denv+denv-exp | default (.env only) | 500,000 | 23.61s, 23.91s, 24.01s | 23.84s | 57.51% |
| next | .env only | 500,000 | 82.22s, 84.57s, 85.59s | 84.13s | 16.30% |

Loading and interpolating a single [large env file](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.interp):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest  |
| --- | --- | --- | --- | --- | --- |
| snackables-next | .env.interp only | 5,000 | 22.40s, 22.52s, 22.54s | 22.49s | 100% |
| denv+denv-exp | .env.interp only | 5,000 | 72.14s, 72.15s, 72.63s | 72.31s | 31.10% | 
| next | .env.interp only | 5,000 | 88.94s, 91.59s, 91.68s | 90.74s | 24.79% |

Loading and interpolating multiple small env files ([1](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env), [2](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development), [3](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.local), [4](https://github.com/mattcarlotta/snackables-v-dotenv-v-next/blob/master/.env.development.local)):
| package | type | iterations | duration (3 fastest runs out of 6) | avg | fastest |
| --- | --- | --- | --- | --- | --- |
| snackables-next | .env, .env.development, .env.local, .env.development.local | 500,000 | 26.45s, 26.53s, 26.60s | 26.53s | 100% |
| denv+denv-exp | .env, .env.development, .env.local, .env.development.local | 500,000 | 41.59s, 41.63s, 42.05s | 41.76s | 63.53% |
| next | default (for development) | 500,000 | 104.54s, 104.77s, 105.79s | 105.03s | 25.26% |

2020-11-19 23:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 8.6s | 8.6s | ⚠️ +10ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | -216 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.972 | 1.982 | ⚠️ +0.01 |
| / avg req/sec | 1267.58 | 1261.06 | ⚠️ -6.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.138 | 1.17 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2196.22 | 2136.92 | ⚠️ -59.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..4972.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f1a49fb..e45e.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.1s | -210ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | -216 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| 677f882d2ed8..4972.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-f1a49fb..e45e.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | mattcarlotta/next.js snackables | Change |
| - | - | - | - |
| _error.js | 914 kB | 914 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 915 kB | 915 kB | ✓ |
| link.js | 973 kB | 973 kB | ✓ |
| routerDirect.js | 966 kB | 966 kB | ✓ |
| withRouter.js | 966 kB | 966 kB | ✓ |
| Overall change | 4.74 MB | 4.74 MB | ✓ |

</details>

</details>
Commit: fd86caa873151925a93528e883f7d4dd54bd822b

2022-02-07 00:59 UTC, ijjk reviewed
Hi, I think we are going to stick with `dotenv` to ensure we don't diverge with behavior inadvertently, thanks for the research done here though!

2022-02-07 00:59 UTC, closed without merging