Fix prefetching in IE11
vercel/next.js pull request #19171
Opened 2020-11-14 16:25 UTC by ijjk

This re-adds the previous prefecthing check to ensure we prefetch in IE11 correctly. 

Fixes: https://dev.azure.com/nextjs/next.js/_build/results?buildId=22101&view=logs&jobId=7e716fea-41ba-511a-dd63-bebc999892ee&j=7e716fea-41ba-511a-dd63-bebc999892ee&t=1b0e7aed-8aab-5481-c243-0ad76c6ead70

2020-11-14 16:33 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11.2s | ⚠️ +303ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +440 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.057 | 1.961 | -0.1 |
| / avg req/sec | 1215.39 | 1275.07 | +59.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.091 | 1.073 | -0.02 |
| /error-in-render avg req/sec | 2291.78 | 2329.82 | +38.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +14 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.25 kB | ⚠️ +15 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +15 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -434,16 +434,19 @@
           : prom;
       }
 
-      function hasPrefetch(link) {
+      function hasRel(rel, link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
-        } catch (_unused) {
-          return false;
-        }
+          return link.relList.supports(rel);
+        } catch (_unused) {}
       }
 
-      var canPrefetch = hasPrefetch();
+      var relPrefetch =
+        hasRel("preload") && !hasRel("prefetch") // https://caniuse.com/#feat=link-rel-preload
+          ? // macOS and iOS (Safari does not support prefetch)
+            "preload" // https://caniuse.com/#feat=link-rel-prefetch
+          : // IE 11, Edge 12+, nearly all evergreen
+            "prefetch";
 
       function prefetchViaDom(href, as, link) {
         return new Promise((res, rej) => {
@@ -458,7 +461,7 @@
           link = document.createElement("link"); // The order of property assignment here is intentional:
 
           if (as) link.as = as;
-          link.rel = "prefetch";
+          link.rel = relPrefetch;
           link.crossOrigin = "anonymous";
           link.onload = res;
           link.onerror = rej; // `href` should always be last:
@@ -682,11 +685,7 @@
             return getFilesForRoute(assetPrefix, route)
               .then(output =>
                 Promise.all(
-                  canPrefetch
-                    ? output.scripts.map(script =>
-                        prefetchViaDom(script, "script")
-                      )
-                    : []
+                  output.scripts.map(script => prefetchViaDom(script, "script"))
                 )
               )
               .then(() => {
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -474,16 +474,19 @@
           : prom;
       }
 
-      function hasPrefetch(link) {
+      function hasRel(rel, link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
-        } catch (_unused) {
-          return false;
-        }
+          return link.relList.supports(rel);
+        } catch (_unused) {}
       }
 
-      var canPrefetch = hasPrefetch();
+      var relPrefetch =
+        hasRel("preload") && !hasRel("prefetch") // https://caniuse.com/#feat=link-rel-preload
+          ? // macOS and iOS (Safari does not support prefetch)
+            "preload" // https://caniuse.com/#feat=link-rel-prefetch
+          : // IE 11, Edge 12+, nearly all evergreen
+            "prefetch";
 
       function prefetchViaDom(href, as, link) {
         return new Promise(function(res, rej) {
@@ -498,7 +501,7 @@
           link = document.createElement("link"); // The order of property assignment here is intentional:
 
           if (as) link.as = as;
-          link.rel = "prefetch";
+          link.rel = relPrefetch;
           link.crossOrigin = "anonymous";
           link.onload = res;
           link.onerror = rej; // `href` should always be last:
@@ -792,11 +795,9 @@
             return getFilesForRoute(assetPrefix, route)
               .then(function(output) {
                 return Promise.all(
-                  canPrefetch
-                    ? output.scripts.map(function(script) {
-                        return prefetchViaDom(script, "script");
-                      })
-                    : []
+                  output.scripts.map(function(script) {
+                    return prefetchViaDom(script, "script");
+                  })
                 );
               })
               .then(function() {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc [...]

2020-11-14 16:38 UTC, ijjk commented
## Failing test suites <!--1502347841-->
Commit: 1109916ac597439c0ee0ddcb481437afe592cb37

**test/integration/not-found-revalidate/test/index.test.js** 
- SSG notFound revalidate > production mode > should revalidate after notFound is returned for fallback: blocking

<details>
<summary>Expand output</summary>

  ● SSG notFound revalidate › production mode › should revalidate after notFound is returned for fallback: blocking

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not 0.546064988885365

      64 |     expect(props2.params).toEqual({ slug: 'hello' })
      65 |     expect(isNaN(props2.random)).toBe(false)
    > 66 |     expect(props2.random).not.toBe(props.random)
         |                               ^
      67 |   })
      68 | 
      69 |   it('should revalidate after notFound is returned for fallback: true', async () => {

      at Object.<anonymous> (integration/not-found-revalidate/test/index.test.js:66:31)

</details>

2020-11-14 16:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.4s | -51ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +440 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.475 | 2.375 | -0.1 |
| / avg req/sec | 1009.94 | 1052.78 | +42.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.273 | 1.256 | -0.02 |
| /error-in-render avg req/sec | 1963.38 | 1990.87 | +27.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +14 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +14 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.25 kB | ⚠️ +15 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +15 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -434,16 +434,19 @@
           : prom;
       }
 
-      function hasPrefetch(link) {
+      function hasRel(rel, link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
-        } catch (_unused) {
-          return false;
-        }
+          return link.relList.supports(rel);
+        } catch (_unused) {}
       }
 
-      var canPrefetch = hasPrefetch();
+      var relPrefetch =
+        hasRel("preload") && !hasRel("prefetch") // https://caniuse.com/#feat=link-rel-preload
+          ? // macOS and iOS (Safari does not support prefetch)
+            "preload" // https://caniuse.com/#feat=link-rel-prefetch
+          : // IE 11, Edge 12+, nearly all evergreen
+            "prefetch";
 
       function prefetchViaDom(href, as, link) {
         return new Promise((res, rej) => {
@@ -458,7 +461,7 @@
           link = document.createElement("link"); // The order of property assignment here is intentional:
 
           if (as) link.as = as;
-          link.rel = "prefetch";
+          link.rel = relPrefetch;
           link.crossOrigin = "anonymous";
           link.onload = res;
           link.onerror = rej; // `href` should always be last:
@@ -682,11 +685,7 @@
             return getFilesForRoute(assetPrefix, route)
               .then(output =>
                 Promise.all(
-                  canPrefetch
-                    ? output.scripts.map(script =>
-                        prefetchViaDom(script, "script")
-                      )
-                    : []
+                  output.scripts.map(script => prefetchViaDom(script, "script"))
                 )
               )
               .then(() => {
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -474,16 +474,19 @@
           : prom;
       }
 
-      function hasPrefetch(link) {
+      function hasRel(rel, link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
-        } catch (_unused) {
-          return false;
-        }
+          return link.relList.supports(rel);
+        } catch (_unused) {}
       }
 
-      var canPrefetch = hasPrefetch();
+      var relPrefetch =
+        hasRel("preload") && !hasRel("prefetch") // https://caniuse.com/#feat=link-rel-preload
+          ? // macOS and iOS (Safari does not support prefetch)
+            "preload" // https://caniuse.com/#feat=link-rel-prefetch
+          : // IE 11, Edge 12+, nearly all evergreen
+            "prefetch";
 
       function prefetchViaDom(href, as, link) {
         return new Promise(function(res, rej) {
@@ -498,7 +501,7 @@
           link = document.createElement("link"); // The order of property assignment here is intentional:
 
           if (as) link.as = as;
-          link.rel = "prefetch";
+          link.rel = relPrefetch;
           link.crossOrigin = "anonymous";
           link.onload = res;
           link.onerror = rej; // `href` should always be last:
@@ -792,11 +795,9 @@
             return getFilesForRoute(assetPrefix, route)
               .then(function(output) {
                 return Promise.all(
-                  canPrefetch
-                    ? output.scripts.map(function(script) {
-                        return prefetchViaDom(script, "script");
-                      })
-                    : []
+                  output.scripts.map(function(script) {
+                    return prefetchViaDom(script, "script");
+                  })
                 );
               })
               .then(function() {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df. [...]

2020-11-14 18:32 UTC, Timer requested changes
I'm not sure we need to fix this in this way. The code path would likely be skipping the `<link rel=prefetch>` and just jumping immediately to the script injection phase, right?

Maybe we should disable the script injection in IE11. Blocking this until we can discuss more.

2020-11-14 19:00 UTC, ijjk commented
A user can still invoke `Router.prefetch` in IE11 and it be expected to prefetch which this fixes, we don't only need to handle prefetching on hover right?

2020-11-14 22:19 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.3s | ⚠️ +80ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +535 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.38 | 2.394 | ⚠️ +0.01 |
| / avg req/sec | 1050.63 | 1044.13 | ⚠️ -6.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.254 | 1.279 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1993.6 | 1955.17 | ⚠️ -38.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +27 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +27 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.26 kB | ⚠️ +28 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 967 B | -1 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -443,7 +443,10 @@
         }
       }
 
-      var canPrefetch = hasPrefetch();
+      var canPrefetch =
+        hasPrefetch() || // detect IE11 since it supports prefetch but isn't detected
+        // with relList.support
+        (true && !!window.MSInputMethodContext && !!document.documentMode);
 
       function prefetchViaDom(href, as, link) {
         return new Promise((res, rej) => {
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -483,7 +483,10 @@
         }
       }
 
-      var canPrefetch = hasPrefetch();
+      var canPrefetch =
+        hasPrefetch() || // detect IE11 since it supports prefetch but isn't detected
+        // with relList.support
+        (true && !!window.MSInputMethodContext && !!document.documentMode);
 
       function prefetchViaDom(href, as, link) {
         return new Promise(function(res, rej) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0012e7862247aed8e86a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5fe6996d5088f67e58b1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0012e7862247aed8e86a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0012e7862247aed8e86a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5fe6996d5088f67e58b1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0012e7862247aed8e86a.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0012e7862247aed8e86a.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.5fe6996d5088f67e58b1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src=" [...]

2020-11-14 22:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 13s | 13.2s | ⚠️ +196ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +455 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.451 | 2.373 | -0.08 |
| / avg req/sec | 1019.85 | 1053.68 | +33.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.262 | 1.275 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1981.08 | 1960.32 | ⚠️ -20.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +28 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.26 kB | ⚠️ +30 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -437,7 +437,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -477,7 +477,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       a [...]

2020-11-14 22:26 UTC, ijjk commented
## Failing test suites <!--1503032506-->
Commit: 574776fce8716201c3ff00e5718331839081c4e1

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 0
    Received:    0.10000000000000142

       96 | 
       97 |       // should be no bigger than 61.8 kb
    >  98 |       expect(parseFloat(indexFirstLoad) - 61.8).toBeLessThanOrEqual(0)
          |                                                 ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.6).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:49)

</details>

2020-11-15 03:16 UTC, ijjk commented
## Failing test suites <!--1503546347-->
Commit: 52626a092ce525986492ba65a7070af9a2e2d6b1

**test/integration/dist-dir/test/index.test.js** 
- distDir > should handle null/undefined distDir
- distDir > With basic usage > should not build the app within the default `.next` directory

<details>
<summary>Expand output</summary>

  ● distDir › With basic usage › should not build the app within the default `.next` directory

    expect(received).toBeFalsy()

    Received: true

      40 |       expect(
      41 |         await fs.exists(join(__dirname, `/../.next/${BUILD_ID_FILE}`))
    > 42 |       ).toBeFalsy()
         |         ^
      43 |     })
      44 |   })
      45 | 

      at Object.<anonymous> (integration/dist-dir/test/index.test.js:42:9)

  ● distDir › should handle null/undefined distDir

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 189

      61 |     await fs.writeFile(nextConfig, origNextConfig)
      62 | 
    > 63 |     expect(stderr.length).toBe(0)
         |                           ^
      64 |   })
      65 | })
      66 | 

      at Object.<anonymous> (integration/dist-dir/test/index.test.js:63:27)

</details>

2020-11-15 03:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 14s | 13.9s | -37ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +455 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.695 | 2.569 | -0.13 |
| / avg req/sec | 927.51 | 973.15 | +45.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.605 | 1.596 | -0.01 |
| /error-in-render avg req/sec | 1557.73 | 1566.75 | +9.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +28 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.26 kB | ⚠️ +30 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -437,7 +437,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -477,7 +477,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
      [...]

2020-11-15 04:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.2s | -354ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +4.36 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.343 | 2.45 | ⚠️ +0.11 |
| / avg req/sec | 1067.02 | 1020.27 | ⚠️ -46.75 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.26 | 1.324 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1984.1 | 1888.82 | ⚠️ -95.28 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +28 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.26 kB | ⚠️ +30 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -437,7 +437,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -477,7 +477,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
    [...]

2020-11-15 04:32 UTC, ijjk commented
## Failing test suites <!--1503618103-->
Commit: 0244783554c91ed2f76751871ec6ab7b5dafe682

**test/integration/css/test/index.test.js** 
- CSS Support > CSS Compilation and Prefixing > should've compiled and prefixed
- CSS Support > CSS Compilation and Prefixing > should've emitted a source map

<details>
<summary>Expand output</summary>

  ● CSS Support › CSS Compilation and Prefixing › should've compiled and prefixed

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `CSS Support CSS Compilation and Prefixing should've compiled and prefixed 1`

    Snapshot: "@media (min-width:480px) and (max-width:767px){::-moz-placeholder{color:green}:-ms-input-placeholder{color:green}::-ms-input-placeholder{color:green}::placeholder{color:green}}.flex-parsing{flex:0 0 calc(50% - var(--vertical-gutter))}.transform-parsing{transform:translate3d(0,0)}.css-grid-shorthand{grid-column:span 2}.g-docs-sidenav .filter::-webkit-input-placeholder{opacity:80%}"
    Received: "@media (min-width:480px) and (max-width:767px){::-moz-placeholder{color:green}:-ms-input-placeholder{color:green}::placeholder{color:green}}.flex-parsing{flex:0 0 calc(50% - var(--vertical-gutter))}.transform-parsing{transform:translate3d(0,0)}.css-grid-shorthand{grid-column:span 2}.g-docs-sidenav .filter::-webkit-input-placeholder{opacity:80%}"

      163 |       expect(
      164 |         cssContent.replace(/\/\*.*?\*\//g, '').trim()
    > 165 |       ).toMatchInlineSnapshot(
          |         ^
      166 |         `"@media (min-width:480px) and (max-width:767px){::-moz-placeholder{color:green}:-ms-input-placeholder{color:green}::-ms-input-placeholder{color:green}::placeholder{color:green}}.flex-parsing{flex:0 0 calc(50% - var(--vertical-gutter))}.transform-parsing{transform:translate3d(0,0)}.css-grid-shorthand{grid-column:span 2}.g-docs-sidenav .filter::-webkit-input-placeholder{opacity:80%}"`
      167 |       )
      168 | 

      at Object.<anonymous> (integration/css/test/index.test.js:165:9)

  ● CSS Support › CSS Compilation and Prefixing › should've emitted a source map

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `CSS Support CSS Compilation and Prefixing should've emitted a source map 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,7 +1,7 @@
      Object {
    -   "mappings": "AAAA,+CACE,mBACE,WACF,CAFA,uBACE,WACF,CAFA,wBACE,WACF,CAFA,cACE,WACF,CACF,CAEA,cACE,2CACF,CAEA,mBACE,0BACF,CAEA,oBACE,kBACF,CAEA,mDACE,WACF",
    +   "mappings": "AAAA,+CACE,mBACE,WACF,CAFA,uBACE,WACF,CAFA,cACE,WACF,CACF,CAEA,cACE,2CACF,CAEA,mBACE,0BACF,CAEA,oBACE,kBACF,CAEA,mDACE,WACF",
        "sourcesContent": Array [
          "@media (480px <= width < 768px) {
        ::placeholder {
          color: green;
        }

      183 | 
      184 |       const { version, mappings, sourcesContent } = JSON.parse(cssMapContent)
    > 185 |       expect({ version, mappings, sourcesContent }).toMatchInlineSnapshot(`
          |                                                     ^
      186 |         Object {
      187 |           "mappings": "AAAA,+CACE,mBACE,WACF,CAFA,uBACE,WACF,CAFA,wBACE,WACF,CAFA,cACE,WACF,CACF,CAEA,cACE,2CACF,CAEA,mBACE,0BACF,CAEA,oBACE,kBACF,CAEA,mDACE,WACF",
      188 |           "sourcesContent": Array [

      at Object.<anonymous> (integration/css/test/index.test.js:185:53)

</details>

2020-11-15 05:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11s | -144ms |
| nodeModulesSize | 85 MB | 85 MB | ⚠️ +4.36 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.062 | 2.075 | ⚠️ +0.01 |
| / avg req/sec | 1212.41 | 1204.77 | ⚠️ -7.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.102 | 1.119 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2268.96 | 2234.11 | ⚠️ -34.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..d9fb.js gzip | 12.7 kB | 12.7 kB | ⚠️ +28 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-6b336ff..ab65.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 58.9 kB | 58.9 kB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| 677f882d2ed8..dule.js gzip | 8.23 kB | 8.26 kB | ⚠️ +30 B |
| framework.HA..dule.js gzip | 39 kB | 39 kB | ✓ |
| main-878859a..dule.js gzip | 5.64 kB | 5.64 kB | ✓ |
| webpack-07c5..dule.js gzip | 751 B | 751 B | ✓ |
| Overall change | 53.6 kB | 53.6 kB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-d9a15a0..130a.js gzip | 1.57 kB | 1.57 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 7.98 kB | 7.98 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _app-75d3a82..dule.js gzip | 625 B | 625 B | ✓ |
| _error-f2fcc..dule.js gzip | 2.29 kB | 2.29 kB | ✓ |
| hooks-cbf13f..dule.js gzip | 387 B | 387 B | ✓ |
| index-b9a643..dule.js gzip | 226 B | 226 B | ✓ |
| link-973cce3..dule.js gzip | 1.51 kB | 1.51 kB | ✓ |
| routerDirect..dule.js gzip | 284 B | 284 B | ✓ |
| withRouter-f..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 5.6 kB | 5.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| _buildManife..dule.js gzip | 330 B | 330 B | ✓ |
| Overall change | 651 B | 651 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/ie11-prefetch | Change |
| - | - | - | - |
| index.html gzip | 968 B | 966 B | -2 B |
| link.html gzip | 975 B | 974 B | -1 B |
| withRouter.html gzip | 962 B | 960 B | -2 B |
| Overall change | 2.9 kB | 2.9 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..a6.module.js</strong></summary>

```diff
@@ -437,7 +437,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>677f882d2ed8..8c8c6127b.js</strong></summary>

```diff
@@ -477,7 +477,12 @@
       function hasPrefetch(link) {
         try {
           link = document.createElement("link");
-          return link.relList.supports("prefetch");
+          return (
+            // detect IE11 since it supports prefetch but isn't detected
+            // with relList.support
+            (!!window.MSInputMethodContext && !!document.documentMode) ||
+            link.relList.supports("prefetch")
+          );
         } catch (_unused) {
           return false;
         }
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -123,13 +123,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -25,7 +25,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.8820a560590f533604a6.module.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9d3c1b141d687e5765f4.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -118,13 +118,13 @@
       type="module"
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.9729a1323ef8c8c6127b.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c11e52639d6f9ffa2701.js"
    [...]

2020-11-15 21:17 UTC, Timer approved these changes

2020-11-15 21:18 UTC, merged