Removes invocation from import
vercel/next.js pull request #19487
Opened 2020-11-24 17:21 UTC by will-holley

The invocation appears to have been committed in error and results in an unintended outcome.

2020-11-24 17:28 UTC, lfades requested changes
Doesn't seen to be the case, note how the first time it expects `pluginOptions`: https://github.com/vercel/next-plugins/blob/master/packages/next-source-maps/index.js#L1

2020-11-24 17:30 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.2s | ⚠️ +136ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.19 | 2.263 | ⚠️ +0.07 |
| / avg req/sec | 1141.41 | 1104.76 | ⚠️ -36.65 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.247 | 1.385 | ⚠️ +0.14 |
| /error-in-render avg req/sec | 2004.48 | 1805.09 | ⚠️ -199.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..8b81.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-fbd7082..8b7a.js gzip | 6.54 kB | 6.54 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.2s | ⚠️ +94ms |
| nodeModulesSize | 84.9 MB | 84.9 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| 677f882d2ed8..8b81.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-fbd7082..8b7a.js gzip | 6.54 kB | 6.54 kB | ✓ |
| webpack-e067..f178.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-4b..e242.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| _app-3b0cf13..85f8.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-6f635..c393.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-d4ffc3..9e0f.js gzip | 887 B | 887 B | ✓ |
| index-17468f..5d83.js gzip | 227 B | 227 B | ✓ |
| link-b618194..5477.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..924c.js gzip | 284 B | 284 B | ✓ |
| withRouter-7..c13d.js gzip | 284 B | 284 B | ✓ |
| Overall change | 8.01 kB | 8.01 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | will-holley/next.js patch-1 | Change |
| - | - | - | - |
| _error.js | 915 kB | 915 kB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 915 kB | 915 kB | ✓ |
| link.js | 973 kB | 973 kB | ✓ |
| routerDirect.js | 966 kB | 966 kB | ✓ |
| withRouter.js | 966 kB | 966 kB | ✓ |
| Overall change | 4.74 MB | 4.74 MB | ✓ |

</details>

</details>
Commit: 54bd12485f6a99aff9330aa4da0963637890dcf2

2020-11-24 20:34 UTC, closed without merging

2020-11-24 20:56 UTC, will-holley commented
@lfades I installed v0.0.3 this morning via NPM; here are the contents of my local `index.js`

```javascript
module.exports = (nextConfig = {}) => {
  return Object.assign({}, nextConfig, {
    webpack(config, options) {
      if (!options.defaultLoaders) {
        throw new Error(
          'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
        )
      }

      const { dev } = options

      if (!dev) {
        config.devtool = 'source-map'

        for (const plugin of config.plugins) {
          if (plugin.constructor.name === 'UglifyJsPlugin') {
            plugin.options.sourceMap = true
            break
          }
        }
      }

      if (typeof nextConfig.webpack === 'function') {
        return nextConfig.webpack(config, options)
      }
      return config
    }
  })
}
```

Note the initial difference.

2020-11-25 00:31 UTC, lfades commented
@will-holley I just installed the dependencies in the repo and I can see what's on https://github.com/vercel/next-plugins/blob/master/packages/next-source-maps/index.js#L1

2020-11-25 01:42 UTC, will-holley commented
Ah, I am running `0.0.3` rather than `0.0.4-canary.1` listed in the repo's dependencies.  I'd like to amend my suggested change to also pin the repo's dependency to `0.0.3` until `0.0.4` migrates from canary to latest on npm.

2020-11-25 17:02 UTC, lfades commented
@will-holley No need. That will break the example.

2020-11-25 17:05 UTC, will-holley commented
Not to be argumentative, but doesn't pegging the dependency to version the majority of clients _won't_ install by default decrease the practical efficacy of the example? ..that is unless `0.0.4` will be bumped up soon.

2020-11-25 17:14 UTC, lfades commented
@will-holley That may be a good point. But if a downgrade doesn't fix anything, don't change it. I don't see how changing that in the example adds any value to it.

2020-11-25 17:19 UTC, will-holley commented
@lfades In my case, I did not install the repo but rather referenced the example `next.config.js` while modifying my own.  I _should_ have checked first to ensure I had the correct version installed but didn't... I can imagine this being a common scenario; however if it is not, then I agree definitively.