Add profiling to webpack loaders
vercel/next.js pull request #20392
Opened 2020-12-22 12:29 UTC by timneutkens

Follow-up to #20357 with additional tracers.

2020-12-22 12:33 UTC, ijjk commented
## Failing test suites <!--1710489105-->
Commit: 8bffd7aea86ffd67eb0777f8da634c7bcd3e9fbf

**test/unit/next-babel-loader.unit.test.js** 
- next-babel-loader > replace constants > should replace typeof window expression nested
- next-babel-loader > replace constants > should replace typeof window expression top level (client)
- next-babel-loader > replace constants > should replace typeof window expression top level (server)
- next-babel-loader > replace constants > should replace typeof window in === expression nested
- next-babel-loader > replace constants > should replace typeof window expression top level
- next-babel-loader > replace constants > should replace typeof window in === expression top level
- next-babel-loader > replace constants > should replace typeof window in !== expression top level
- next-babel-loader > replace constants > should replace typeof window expression !== object top level
- next-babel-loader > replace constants > should replace typeof window expression top level serverside
- next-babel-loader > replace constants > should replace typeof window expression !== object top level serverside
- next-babel-loader > replace constants > should replace process.browser (1)
- next-babel-loader > replace constants > should replace process.browser (2)
- next-babel-loader > replace constants > should replace process.browser (3)
- next-babel-loader > replace constants > should replace process.browser (4)
- next-babel-loader > replace constants > should replace process.browser (5)
- next-babel-loader > replace constants > should replace NODE_ENV on client (dev)
- next-babel-loader > replace constants > should replace NODE_ENV on client (prod)
- next-babel-loader > replace constants > should replace NODE_ENV on server
- next-babel-loader > replace constants > should replace NODE_ENV in statement (dev)
- next-babel-loader > replace constants > should replace NODE_ENV in === statement (prod)
- next-babel-loader > replace constants > should replace NODE_ENV in !== statement (prod)
- next-babel-loader > replace constants > should not drop unused exports by default
- next-babel-loader > replace constants > should not drop unused exports by default in a page
- next-babel-loader > replace constants > should drop unused exports in a modern-apis page
- next-babel-loader > replace constants > should keep used exports in a modern-apis page (server)
- next-babel-loader > replace constants > should keep used exports in a modern-apis page (client)
- next-babel-loader > replace constants > should keep used exports and react in a modern-apis page with JSX (client)
- next-babel-loader > replace constants > should support 9.4 regression
- next-babel-loader > replace constants > should support optional chaining for JS file
- next-babel-loader > replace constants > should support optional chaining for TS file
- next-babel-loader > replace constants > should support nullish coalescing for JS file
- next-babel-loader > replace constants > should support nullish coalescing for TS file

<details>
<summary>Expand output</summary>

  ● next-babel-loader › replace constants › should replace typeof window expression nested

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:68:26)

  ● next-babel-loader › replace constants › should replace typeof window expression top level (client)

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:75:26)

  ● next-babel-loader › replace constants › should replace typeof window expression top level (server)

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:80:26)

  ● next-babel-loader › replace constants › should replace typeof window in === expression nested

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:85:26)

  ● next-babel-loader › replace constants › should replace typeof window expression top level

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:92:26)

  ● next-babel-loader › replace constants › should replace typeof window in === expression top level

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:97:26)

  ● next-babel-loader › replace constants › should replace typeof window in !== expression top level

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:102:26)

  ● next-babel-loader › replace constants › should replace typeof window expression !== object top level

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:107:26)

  ● next-babel-loader › replace constants › should replace typeof window expression top level serverside

    TypeError: loader.bind is not a function

      27 |     }
      28 | 
    > 29 |     const res = loader.bind({
         |                        ^
      30 |       resourcePath,
      31 |       async() {
      32 |         isAsync = true

      at unit/next-babel-loader.unit.test.js:29:24
      at babel (unit/next-babel-loader.unit.test.js:20:10)
      at Object.<anonymous> (unit/next-babel-loader.unit.test.js:112:26)

  ● next-babel-loader › replace constants › should replace typeof window expression !== object top level serverside

    TypeError: loader.bind is not a function [...]

2020-12-22 12:37 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 8.9s | 8.8s | -54ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +32.6 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.747 | 1.704 | -0.04 |
| / avg req/sec | 1431.21 | 1466.74 | +35.53 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.06 | 1.134 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 2358.41 | 2204.98 | ⚠️ -153.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-72193d1..1356.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 321 B | -2 B |
| Overall change | 323 B | 321 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 618 B | 619 B | ⚠️ +1 B |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,18 +1,18 @@
 self.__BUILD_MANIFEST = {
   __rewrites: [],
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-283eed3c1520dcc26e8d.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-5219d40a02e71ed7dcbf.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-671dbf297c19f6f715f8.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-691e25800d10f0f794d2.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-bdd2cad07648acf22380.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-61cb7b66e376b851f63a.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-00f0f71a76f57326f2aa.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5820d5e6a59bed70b81f.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f408582ce776dfa74d5.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-a5bdcfc87579b1d2776d.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-2cdddce06c9626f1dcfa.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-748b809bbc7636857f70.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      href="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      src="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      href="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       as="script"
     />
   </head>
@@ -74,11 +74,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      src="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      href="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      src="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.3s | ⚠️ +82ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +32.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-72193 [...]

2020-12-22 15:16 UTC, Timer approved these changes

2020-12-22 15:23 UTC, ijjk approved these changes, later dismissed

2020-12-22 15:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 8.6s | 8.4s | -250ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +33.3 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.719 | 1.714 | -0.01 |
| / avg req/sec | 1454.1 | 1458.34 | +4.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.062 | 1.083 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2355.15 | 2308.62 | ⚠️ -46.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-abf8a5b..ea50.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 321 B | -2 B |
| Overall change | 323 B | 321 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| index.html gzip | 612 B | 614 B | ⚠️ +2 B |
| link.html gzip | 617 B | 620 B | ⚠️ +3 B |
| withRouter.html gzip | 606 B | 607 B | ⚠️ +1 B |
| Overall change | 1.83 kB | 1.84 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,18 +1,18 @@
 self.__BUILD_MANIFEST = {
   __rewrites: [],
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-283eed3c1520dcc26e8d.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-5219d40a02e71ed7dcbf.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-671dbf297c19f6f715f8.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-691e25800d10f0f794d2.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-bdd2cad07648acf22380.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-61cb7b66e376b851f63a.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-00f0f71a76f57326f2aa.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5820d5e6a59bed70b81f.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f408582ce776dfa74d5.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-a5bdcfc87579b1d2776d.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-2cdddce06c9626f1dcfa.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-748b809bbc7636857f70.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      href="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      src="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      href="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       as="script"
     />
   </head>
@@ -74,11 +74,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      src="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      href="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      src="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 10s | 10.4s | ⚠️ +403ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +33.3 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| [...]

2020-12-22 15:27 UTC, Timer requested changes
We need to drop `babel-loader` as a dep and remove the `ncc` step if we're doing it

2020-12-23 17:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 8.7s | 9.7s | ⚠️ +990ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +27.8 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.894 | 1.87 | -0.02 |
| / avg req/sec | 1319.92 | 1336.73 | +16.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.349 | 1.315 | -0.03 |
| /error-in-render avg req/sec | 1852.54 | 1900.9 | +48.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d2962..b163.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-95c2..e870.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| polyfills-d3..23f6.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _app-0d19cb6..5497.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-85785..a9f3.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-42456f..0c06.js gzip | 887 B | 887 B | ✓ |
| index-8081ce..e44f.js gzip | 227 B | 227 B | ✓ |
| link-0ab9f83..fa00.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..c3d8.js gzip | 303 B | 303 B | ✓ |
| withRouter-0..a68e.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 321 B | -2 B |
| Overall change | 323 B | 321 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| index.html gzip | 612 B | 613 B | ⚠️ +1 B |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 607 B | 606 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,18 +1,18 @@
 self.__BUILD_MANIFEST = {
   __rewrites: [],
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-283eed3c1520dcc26e8d.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-5219d40a02e71ed7dcbf.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-671dbf297c19f6f715f8.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-691e25800d10f0f794d2.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-bdd2cad07648acf22380.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-61cb7b66e376b851f63a.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-00f0f71a76f57326f2aa.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5820d5e6a59bed70b81f.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f408582ce776dfa74d5.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-a5bdcfc87579b1d2776d.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-2cdddce06c9626f1dcfa.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-748b809bbc7636857f70.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      href="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      src="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      href="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       as="script"
     />
   </head>
@@ -74,11 +74,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      src="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      href="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      src="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.7s | ⚠️ +187ms |
| nodeModulesSize | 82.6 MB | 82.7 MB | ⚠️ +27.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..5e70.js gzip | 12.8 kB | 12.8 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e0d296 [...]

2020-12-29 20:52 UTC, Timer approved these changes
Great work, @timneutkens!

2020-12-29 20:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.4s | -115ms |
| nodeModulesSize | 82.9 MB | 83 MB | ⚠️ +14.2 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.916 | 1.891 | -0.02 |
| / avg req/sec | 1304.64 | 1322.26 | +17.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.171 | 1.249 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 2134.96 | 2001.42 | ⚠️ -133.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..45a8.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-eda9847..6ba4.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _app-370a053..c381.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-b7502..6249.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-baa922..722d.js gzip | 887 B | 887 B | ✓ |
| index-c8a663..7961.js gzip | 227 B | 227 B | ✓ |
| link-64502f2..a071.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..4623.js gzip | 303 B | 303 B | ✓ |
| withRouter-f..7105.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 322 B | -1 B |
| Overall change | 323 B | 322 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| index.html gzip | 614 B | 616 B | ⚠️ +2 B |
| link.html gzip | 620 B | 621 B | ⚠️ +1 B |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,18 +1,18 @@
 self.__BUILD_MANIFEST = {
   __rewrites: [],
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-283eed3c1520dcc26e8d.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-5219d40a02e71ed7dcbf.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-671dbf297c19f6f715f8.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-691e25800d10f0f794d2.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-bdd2cad07648acf22380.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-61cb7b66e376b851f63a.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-00f0f71a76f57326f2aa.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5820d5e6a59bed70b81f.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f408582ce776dfa74d5.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-a5bdcfc87579b1d2776d.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-2cdddce06c9626f1dcfa.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-748b809bbc7636857f70.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      href="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      src="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      href="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       as="script"
     />
   </head>
@@ -74,11 +74,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      src="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      href="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      src="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.2s | -554ms |
| nodeModulesSize | 82.9 MB | 83 MB | ⚠️ +14.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..45a8.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
|  [...]

2020-12-29 21:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 8.8s | 8.8s | ⚠️ +60ms |
| nodeModulesSize | 82.9 MB | 83 MB | ⚠️ +14.2 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.772 | 1.742 | -0.03 |
| / avg req/sec | 1410.78 | 1435.01 | +24.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.091 | 1.114 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2291.7 | 2243.66 | ⚠️ -48.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..45a8.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-eda9847..6ba4.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-7193..1446.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59 kB | 59 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| polyfills-67..b7d1.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _app-370a053..c381.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-b7502..6249.js gzip | 3.44 kB | 3.44 kB | ✓ |
| hooks-baa922..722d.js gzip | 887 B | 887 B | ✓ |
| index-c8a663..7961.js gzip | 227 B | 227 B | ✓ |
| link-64502f2..a071.js gzip | 1.61 kB | 1.61 kB | ✓ |
| routerDirect..4623.js gzip | 303 B | 303 B | ✓ |
| withRouter-f..7105.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.05 kB | 8.05 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 322 B | -1 B |
| Overall change | 323 B | 322 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| index.html gzip | 614 B | 616 B | ⚠️ +2 B |
| link.html gzip | 620 B | 621 B | ⚠️ +1 B |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,18 +1,18 @@
 self.__BUILD_MANIFEST = {
   __rewrites: [],
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-283eed3c1520dcc26e8d.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-5219d40a02e71ed7dcbf.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-671dbf297c19f6f715f8.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-691e25800d10f0f794d2.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-bdd2cad07648acf22380.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-61cb7b66e376b851f63a.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-00f0f71a76f57326f2aa.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-5820d5e6a59bed70b81f.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6f408582ce776dfa74d5.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-a5bdcfc87579b1d2776d.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-2cdddce06c9626f1dcfa.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-748b809bbc7636857f70.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      href="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/index-283eed3c1520dcc26e8d.js"
+      src="/_next/static/chunks/pages/index-5219d40a02e71ed7dcbf.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      href="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       as="script"
     />
   </head>
@@ -74,11 +74,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/link-00f0f71a76f57326f2aa.js"
+      src="/_next/static/chunks/pages/link-5820d5e6a59bed70b81f.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -27,12 +27,12 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      href="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      href="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       as="script"
     />
   </head>
@@ -69,11 +69,11 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/_app-265ddf2d03dbe48fa6cb.js"
+      src="/_next/static/chunks/pages/_app-f6044d7389b6f97833eb.js"
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/pages/withRouter-2cdddce06c9626f1dcfa.js"
+      src="/_next/static/chunks/pages/withRouter-748b809bbc7636857f70.js"
       async=""
     ></script>
     <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""></script>
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.4s | -115ms |
| nodeModulesSize | 82.9 MB | 83 MB | ⚠️ +14.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/tracing-to-webpack-loader | Change |
| - | - | - | - |
| 677f882d2ed8..45a8.js gzip | 12.7 kB | 12.7 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
|  [...]

2020-12-29 21:21 UTC, merged