Add next configuration as an option for custom servers
vercel/next.js pull request #2058
Opened 2017-05-24 19:04 UTC by reel

Instead of having a `next.config.js` file, we can dynamically add configuration from the custom server.

The use case would be to support many different webpack configuration with a `minimist` flag.

I can add an example if wanted.

2017-05-26 03:07 UTC, arunoda requested changes
The idea looks great to me.
Could you work on this change?

2017-05-26 03:07 UTC, arunoda commented on server/index.js
> +    this.config = getConfig(this.dir, conf)
If we've a config via the option, it shouldn't read from the filesystem. Change the code to reflect that.

And make sure to get default configurations. May be we need to add method called `withDefaults` to `server/config.js`

2017-05-26 09:43 UTC, reel commented on server/index.js
> +    this.config = getConfig(this.dir, conf)
Well, for my use case, I still want to be able to read from filesystem to overwrite default & custom server.

That's why I have this order in Object.assign

Your thoughts?

2017-05-30 13:43 UTC, reel commented on server/index.js
> +    this.config = getConfig(this.dir, conf)
@arunoda Is this OK?

2017-05-31 06:59 UTC, arunoda approved these changes

2017-05-31 07:00 UTC, arunoda commented
@reel everything looks great to me. Let's wait for tests.

2017-05-31 08:06 UTC, arunoda commented
Actually the error is not our fault.
See: https://github.com/zeit/styled-jsx/pull/217

So. I'm taking this in.

2017-05-31 08:06 UTC, merged

2017-06-03 16:38 UTC, reel commented
Thank's @arunoda 

Here's a peak at what we can do now: https://github.com/usehenri/henri/blob/master/packages/view/conf.js