refactor(next): client/index.tsx
vercel/next.js pull request #20806
Opened 2021-01-06 04:23 UTC by tarunama

## summary
- add return types
- eval NODE_ENV once
- arrange import syntax
- move `locale` variable const from let
- use [strict equality]()

2021-01-06 04:33 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 10.7s | 11.7s | ⚠️ +1s |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +81 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.179 | 2.061 | -0.12 |
| / avg req/sec | 1147.06 | 1213.01 | +65.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.284 | 1.29 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1946.7 | 1938.52 | ⚠️ -8.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | N/A | N/A |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| main-bd74f8e..b249.js gzip | N/A | 41 kB | N/A |
| Overall change | 59.4 kB | 93.8 kB | ⚠️ +34.4 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| index.html gzip | 613 B | 614 B | ⚠️ +1 B |
| link.html gzip | 620 B | 621 B | ⚠️ +1 B |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-0573c44..82ff96878.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>main-0ae841d..26d092b3c.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-0573c44621582ff96878.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-0573c44621582ff96878.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-0573c44621582ff96878.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-0573c44621582ff96878.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-0573c44621582ff96878.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-0573c44621582ff96878.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 12.5s | 14s | ⚠️ +1.5s |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +81 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | N/A | N/A |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| main-bd74f8e..b249.js gzip | N/A | 41 kB | N/A |
| Overall change | 59.4 kB | 93.8 kB | ⚠️ +34.4 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 71096a6099ad54368f6817cf0414414425a3c86b

2021-01-06 04:35 UTC, ijjk commented
## Failing test suites <!--1775375859-->
Commit: 71096a6099ad54368f6817cf0414414425a3c86b

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 62.4
    Received: 96.4

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   34.00000000000001

       96 | 
       97 |       // should be no bigger than 62.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(62.4, 1)
          |                                          ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.7).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:42)

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 65
    Received:    99

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(65)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-01-06 06:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 10s | 11.3s | ⚠️ +1.3s |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +79 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.028 | 2.002 | -0.03 |
| / avg req/sec | 1232.44 | 1248.53 | +16.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.303 | 1.256 | -0.05 |
| /error-in-render avg req/sec | 1918.19 | 1990.64 | +72.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | N/A | N/A |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| main-09c319a..9264.js gzip | N/A | 41 kB | N/A |
| Overall change | 59.4 kB | 93.8 kB | ⚠️ +34.4 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 621 B | ⚠️ +1 B |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-0ae841d..26d092b3c.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>main-a86664a..5ae2ed541.js</strong></summary>

```diff
failed to diff
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-a86664aae4c5ae2ed541.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 13s | 13.1s | ⚠️ +93ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +79 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | N/A | N/A |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| main-09c319a..9264.js gzip | N/A | 41 kB | N/A |
| Overall change | 59.4 kB | 93.8 kB | ⚠️ +34.4 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 3f1f03724bde8eee3a0176a42db253d4196aa40d

2021-01-06 06:11 UTC, ijjk commented
## Failing test suites <!--1775786964-->
Commit: 3f1f03724bde8eee3a0176a42db253d4196aa40d

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 62.4
    Received: 96.4

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   34.00000000000001

       96 | 
       97 |       // should be no bigger than 62.2 kb
    >  98 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(62.4, 1)
          |                                          ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.7).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:42)

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 65
    Received:    99

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(65)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-01-06 06:46 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 9.9s | 9.7s | -206ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +601 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.986 | 1.942 | -0.04 |
| / avg req/sec | 1258.67 | 1287.28 | +28.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.237 | 1.223 | -0.01 |
| /error-in-render avg req/sec | 2020.85 | 2044.48 | +23.63 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1f258db..b7d8.js gzip | 6.63 kB | 6.63 kB | ⚠️ +2 B |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-705099c..c35d.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 606 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-0ae841d..26d092b3c.js</strong></summary>

```diff
@@ -371,10 +371,10 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         runtimeConfig = data.runtimeConfig,
         dynamicIds = data.dynamicIds,
         isFallback = data.isFallback,
+        locale = data.locale,
         locales = data.locales,
         domainLocales = data.domainLocales;
-      var locale = data.locale,
-        defaultLocale = data.defaultLocale;
+      var defaultLocale = data.defaultLocale;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
       // So, this is how we do it in the client side at runtime
 
@@ -429,14 +429,12 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       window.__NEXT_P.push = register;
       var headManager = (0, _headManager["default"])();
       var appElement = document.getElementById("__next");
-      var lastAppProps;
 
       var _lastRenderReject;
 
       var webpackHMR;
       var router;
       exports.router = router;
-      var CachedComponent;
       var CachedApp, onPerfEntry;
 
       var Container = /*#__PURE__*/ (function(_react$default$Compon) {
@@ -539,6 +537,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var emitter = (0, _mitt["default"])();
       exports.emitter = emitter;
+      var CachedComponent;
 
       var _default = /*#__PURE__*/ (function() {
         var _ref3 = _asyncToGenerator(
@@ -955,11 +954,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
           "routeChange",
           "mark"
         );
-
-        if (!navStartEntries.length) {
-          return;
-        }
-
+        if (!navStartEntries.length) return;
         performance.measure(
           "Next.js-route-change-to-render",
           navStartEntries[0].name,
@@ -1000,7 +995,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                 App: CachedApp,
                 err: error
               })["catch"](function(err) {
-                return console.error("Error rendering page: ", err);
+                return console.error("Error rendering page: ".concat(err));
               });
             }
           },
@@ -1035,6 +1030,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         };
       };
 
+      var lastAppProps;
+
       function doRender(input) {
         var App = input.App,
           Component = input.Component,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      href="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-0ae841d5a7826d092b3c.js"
+      src="/_next/static/chunks/main-49ce2c46242b8f22d6d2.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.3s | -448ms |
| nodeModulesSize | 80.6 MB | 80.6 MB | ⚠️ +601 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d [...]

2021-01-07 11:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 9.2s | 9.2s | -70ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +601 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.874 | 1.927 | ⚠️ +0.05 |
| / avg req/sec | 1333.93 | 1297.69 | ⚠️ -36.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.407 | 1.355 | -0.05 |
| /error-in-render avg req/sec | 1776.73 | 1845.1 | +68.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1fee81a..2bb3.js gzip | 6.62 kB | 6.63 kB | ⚠️ +2 B |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| index.html gzip | 613 B | 615 B | ⚠️ +2 B |
| link.html gzip | 618 B | 619 B | ⚠️ +1 B |
| withRouter.html gzip | 605 B | 606 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-2b75875..9851c6cd8.js</strong></summary>

```diff
@@ -371,10 +371,10 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         runtimeConfig = data.runtimeConfig,
         dynamicIds = data.dynamicIds,
         isFallback = data.isFallback,
+        locale = data.locale,
         locales = data.locales,
         domainLocales = data.domainLocales;
-      var locale = data.locale,
-        defaultLocale = data.defaultLocale;
+      var defaultLocale = data.defaultLocale;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
       // So, this is how we do it in the client side at runtime
 
@@ -429,14 +429,12 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       window.__NEXT_P.push = register;
       var headManager = (0, _headManager["default"])();
       var appElement = document.getElementById("__next");
-      var lastAppProps;
 
       var _lastRenderReject;
 
       var webpackHMR;
       var router;
       exports.router = router;
-      var CachedComponent;
       var CachedApp, onPerfEntry;
 
       var Container = /*#__PURE__*/ (function(_react$default$Compon) {
@@ -539,6 +537,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var emitter = (0, _mitt["default"])();
       exports.emitter = emitter;
+      var CachedComponent;
 
       var _default = /*#__PURE__*/ (function() {
         var _ref3 = _asyncToGenerator(
@@ -955,11 +954,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
           "routeChange",
           "mark"
         );
-
-        if (!navStartEntries.length) {
-          return;
-        }
-
+        if (!navStartEntries.length) return;
         performance.measure(
           "Next.js-route-change-to-render",
           navStartEntries[0].name,
@@ -1000,7 +995,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
                 App: CachedApp,
                 err: error
               })["catch"](function(err) {
-                return console.error("Error rendering page: ", err);
+                return console.error("Error rendering page: ".concat(err));
               });
             }
           },
@@ -1035,6 +1030,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         };
       };
 
+      var lastAppProps;
+
       function doRender(input) {
         var App = input.App,
           Component = input.Component,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-7e21faea7507050847e5.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-7e21faea7507050847e5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-7e21faea7507050847e5.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-7e21faea7507050847e5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-7e21faea7507050847e5.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-7e21faea7507050847e5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.8s | -42ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +601 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - |  [...]

2021-01-07 13:44 UTC, Timer requested changes

2021-01-07 13:44 UTC, Timer commented on packages/next/client/index.tsx
> +          console.error(`Error rendering page: ${err}`)
Please undo this change, as it results in larger code output.

2021-01-07 14:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.4s | -4ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.324 | 2.384 | ⚠️ +0.06 |
| / avg req/sec | 1075.78 | 1048.85 | ⚠️ -26.93 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.725 | 1.73 | 0 |
| /error-in-render avg req/sec | 1449.09 | 1444.7 | ⚠️ -4.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1fee81a..2bb3.js gzip | 6.62 kB | 6.63 kB | ⚠️ +2 B |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _app-b6fc6bc..222c.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-e2ffa..0f3f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-010c20..8411.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-d979103..c5ff.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| _buildManifest.js gzip | 323 B | 323 B | ✓ |
| Overall change | 323 B | 323 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| index.html gzip | 613 B | 614 B | ⚠️ +1 B |
| link.html gzip | 618 B | 619 B | ⚠️ +1 B |
| withRouter.html gzip | 605 B | 606 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-2b75875..9851c6cd8.js</strong></summary>

```diff
@@ -371,10 +371,10 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         runtimeConfig = data.runtimeConfig,
         dynamicIds = data.dynamicIds,
         isFallback = data.isFallback,
+        locale = data.locale,
         locales = data.locales,
         domainLocales = data.domainLocales;
-      var locale = data.locale,
-        defaultLocale = data.defaultLocale;
+      var defaultLocale = data.defaultLocale;
       var prefix = assetPrefix || ""; // With dynamic assetPrefix it's no longer possible to set assetPrefix at the build time
       // So, this is how we do it in the client side at runtime
 
@@ -429,14 +429,12 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
       window.__NEXT_P.push = register;
       var headManager = (0, _headManager["default"])();
       var appElement = document.getElementById("__next");
-      var lastAppProps;
 
       var _lastRenderReject;
 
       var webpackHMR;
       var router;
       exports.router = router;
-      var CachedComponent;
       var CachedApp, onPerfEntry;
 
       var Container = /*#__PURE__*/ (function(_react$default$Compon) {
@@ -539,6 +537,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
 
       var emitter = (0, _mitt["default"])();
       exports.emitter = emitter;
+      var CachedComponent;
 
       var _default = /*#__PURE__*/ (function() {
         var _ref3 = _asyncToGenerator(
@@ -955,11 +954,7 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
           "routeChange",
           "mark"
         );
-
-        if (!navStartEntries.length) {
-          return;
-        }
-
+        if (!navStartEntries.length) return;
         performance.measure(
           "Next.js-route-change-to-render",
           navStartEntries[0].name,
@@ -1035,6 +1030,8 @@ _N_E = (window["webpackJsonp_N_E"] = window["webpackJsonp_N_E"] || []).push([
         };
       };
 
+      var lastAppProps;
+
       function doRender(input) {
         var App = input.App,
           Component = input.Component,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-6b66615487b2bff789df.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-6b66615487b2bff789df.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-6b66615487b2bff789df.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-6b66615487b2bff789df.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      href="/_next/static/chunks/main-6b66615487b2bff789df.js"
       as="script"
     />
     <link
@@ -53,7 +53,7 @@
       src="/_next/static/chunks/polyfills-ae47a1f95297af5f55f8.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-2b758757f019851c6cd8.js"
+      src="/_next/static/chunks/main-6b66615487b2bff789df.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.7s | ⚠️ +31ms |
| nodeModulesSize | 80.8 MB | 80.8 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js refactor/client-index | Change |
| - | - | - | - |
| 677f882d2ed8..89aa.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-1fee81a..2bb3.js gzip | 6.62 kB | N/A | N/A |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| main-dba4ec1..27c0.js gzip | N/A | 6.63 kB | N/A |
| Overall change | 59.4 kB | 59.4 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</st [...]

2021-01-07 15:02 UTC, Timer approved these changes
Thanks!

2021-01-07 15:02 UTC, merged