fix(next/server): add undefined distDir value for optimizeCss
vercel/next.js pull request #20911
Opened 2021-01-08 20:39 UTC by newsroomdev

My team was trying out `optimizeCss` and noticed that it didn’t work in a server context. This PR fixes an error when enabling the `optimizeCss` flag while running next-server where `critters` cannot determine the `distDir` because the value is `undefined` on `renderOpts`. Please let me know if there’s anything else I can add to the PR or additional details that would help.

2021-01-11 13:56 UTC, timneutkens requested changes
Can you add a test for this change to `test/integration`

2021-01-13 17:23 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.1s | -51ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.046 | 2.021 | -0.02 |
| / avg req/sec | 1222.17 | 1236.9 | +14.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.311 | 1.279 | -0.03 |
| /error-in-render avg req/sec | 1906.72 | 1954.7 | +47.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.4s | ⚠️ +265ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 1080273ba35240c05810fb236616ae52f7e58711

2021-01-13 17:23 UTC, ijjk commented
## Failing test suites <!--1823135187-->
Commit: 1080273ba35240c05810fb236616ae52f7e58711

**test/integration/css-customization/test/index.test.js** 
- Bad CSS Customization > should've compiled and prefixed
- Bad CSS Customization > should've emitted a source map
- CSS Customization > should've compiled and prefixed
- CSS Customization > should've emitted a source map
- CSS Customization Array > should've compiled and prefixed
- CSS Customization Array > should've emitted a source map

<details>
<summary>Expand output</summary>

  ● CSS Customization › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  "@media (480px <= width < 768px){::placeholder{color:green}}.video{max-width:400px;max-height:300px}"

      38 | 
      39 |     // Contains a source map
    > 40 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
         |                        ^
      41 |   })
      42 | 
      43 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:40:24)

  ● CSS Customization › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      47 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      48 | 
    > 49 |     expect(cssMapFiles.length).toBe(1)
         |                                ^
      50 |     const cssMapContent = (
      51 |       await readFile(join(cssFolder, cssMapFiles[0]), 'utf8')
      52 |     ).trim()

      at Object.<anonymous> (integration/css-customization/test/index.test.js:49:32)

  ● CSS Customization Array › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  "@media (480px <= width < 768px){a:before{content:\"\"}::placeholder{color:green}}.video{max-width:6400px;max-height:4800px;max-width:400rem;max-height:300rem}"

      170 | 
      171 |     // Contains a source map
    > 172 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
          |                        ^
      173 |   })
      174 | 
      175 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:172:24)

  ● CSS Customization Array › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      179 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      180 | 
    > 181 |     expect(cssMapFiles.length).toBe(1)
          |                                ^
      182 |     const cssMapContent = (
      183 |       await readFile(join(cssFolder, cssMapFiles[0]), 'utf8')
      184 |     ).trim()

      at Object.<anonymous> (integration/css-customization/test/index.test.js:181:32)

  ● Bad CSS Customization › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  ".video{max-width:400px;max-height:300px}"

      251 | 
      252 |     // Contains a source map
    > 253 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
          |                        ^
      254 |   })
      255 | 
      256 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:253:24)

  ● Bad CSS Customization › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      260 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      261 | 
    > 262 |     expect(cssMapFiles.length).toBe(1)
          |                                ^
      263 |   })
      264 | })
      265 | 

      at Object.<anonymous> (integration/css-customization/test/index.test.js:262:32)

</details>

2021-01-13 17:44 UTC, ijjk commented
## Failing test suites <!--1823303824-->
Commit: 6792615a26503eead913244d075b1c17f319613e

**test/integration/css-client-nav/test/index.test.js** 
- CSS Module client-side navigation in Production > should be able to client-side navigate from red to blue
- CSS Module client-side navigation in Production > should be able to client-side navigate from blue to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to red
- CSS Module client-side navigation in Production > should be able to client-side navigate from none to blue

<details>
<summary>Expand output</summary>

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from red to blue

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from blue to red

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to red

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)

  ● CSS Module client-side navigation in Production › should be able to client-side navigate from none to blue

    command failed with code 1

      138 |         code !== 0
      139 |       ) {
    > 140 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      141 |       }
      142 | 
      143 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:140:23)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      282 | export async function killApp(instance) {
      283 |   await new Promise((resolve, reject) => {
    > 284 |     treeKill(instance.pid, (err) => {
          |                       ^
      285 |       if (err) {
      286 |         if (
      287 |           process.platform === 'win32' &&

      at lib/next-test-utils.js:284:23
      at killApp (lib/next-test-utils.js:283:9)
      at integration/css-client-nav/test/index.test.js:34:11

</details>

2021-01-13 17:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 9s | 8.8s | -231ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.764 | 1.745 | -0.02 |
| / avg req/sec | 1417.08 | 1432.66 | +15.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.115 | 1.144 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2243.16 | 2184.84 | ⚠️ -58.32 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.4s | -97ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 81fae88d1fa054c5074ca0dd23d39cd9cd7930b8

2021-01-13 18:01 UTC, ijjk commented
## Failing test suites <!--1823344594-->
Commit: 81fae88d1fa054c5074ca0dd23d39cd9cd7930b8

**test/integration/css-customization/test/index.test.js** 
- Bad CSS Customization > should've compiled and prefixed
- Bad CSS Customization > should've emitted a source map
- CSS Customization > should've compiled and prefixed
- CSS Customization > should've emitted a source map
- CSS Customization Array > should've compiled and prefixed
- CSS Customization Array > should've emitted a source map

<details>
<summary>Expand output</summary>

  ● CSS Customization › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  "@media (480px <= width < 768px){::placeholder{color:green}}.video{max-width:400px;max-height:300px}"

      38 | 
      39 |     // Contains a source map
    > 40 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
         |                        ^
      41 |   })
      42 | 
      43 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:40:24)

  ● CSS Customization › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      47 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      48 | 
    > 49 |     expect(cssMapFiles.length).toBe(1)
         |                                ^
      50 |     const cssMapContent = (
      51 |       await readFile(join(cssFolder, cssMapFiles[0]), 'utf8')
      52 |     ).trim()

      at Object.<anonymous> (integration/css-customization/test/index.test.js:49:32)

  ● CSS Customization Array › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  "@media (480px <= width < 768px){a:before{content:\"\"}::placeholder{color:green}}.video{max-width:6400px;max-height:4800px;max-width:400rem;max-height:300rem}"

      170 | 
      171 |     // Contains a source map
    > 172 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
          |                        ^
      173 |   })
      174 | 
      175 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:172:24)

  ● CSS Customization Array › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      179 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      180 | 
    > 181 |     expect(cssMapFiles.length).toBe(1)
          |                                ^
      182 |     const cssMapContent = (
      183 |       await readFile(join(cssFolder, cssMapFiles[0]), 'utf8')
      184 |     ).trim()

      at Object.<anonymous> (integration/css-customization/test/index.test.js:181:32)

  ● Bad CSS Customization › should've compiled and prefixed

    expect(received).toMatch(expected)

    Expected pattern: /\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//
    Received string:  ".video{max-width:400px;max-height:300px}"

      251 | 
      252 |     // Contains a source map
    > 253 |     expect(cssContent).toMatch(/\/\*#\s*sourceMappingURL=(.+\.map)\s*\*\//)
          |                        ^
      254 |   })
      255 | 
      256 |   it(`should've emitted a source map`, async () => {

      at Object.<anonymous> (integration/css-customization/test/index.test.js:253:24)

  ● Bad CSS Customization › should've emitted a source map

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      260 |     const cssMapFiles = files.filter((f) => /\.css\.map$/.test(f))
      261 | 
    > 262 |     expect(cssMapFiles.length).toBe(1)
          |                                ^
      263 |   })
      264 | })
      265 | 

      at Object.<anonymous> (integration/css-customization/test/index.test.js:262:32)

</details>

2021-01-13 19:26 UTC, newsroomdev commented
Thank you for the initial feedback, @timneutkens! I worked with my co-worker @ctbarna to add an integration test based on the existing  `image-optimization` test suite. We would appreciate additional feedback and assistance since adding `distDir` to `renderOpts` appears to cause failures within the  `css-customization` suite. Additionally, only one snapshot test from that same suite fails when running it locally. Please let us know how to best proceed

2021-01-13 19:32 UTC, newsroomdev commented
Thank you for the initial feedback, @timneutkens! I worked with my co-worker @ctbarna to add an integration test based on the existing  `image-optimization` test suite. We would appreciate additional feedback and assistance since adding the `distDir` to renderOpts appears to cause a failure with a  `css-customization`  snapshot test.

2021-01-13 19:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 9.1s | 9.4s | ⚠️ +267ms |
| nodeModulesSize | 80.9 MB | 80.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.849 | 1.875 | ⚠️ +0.03 |
| / avg req/sec | 1352.23 | 1333.28 | ⚠️ -18.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.107 | 1.194 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 2257.93 | 2094.45 | ⚠️ -163.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 619 B | 619 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 11.4s | 11.3s | -157ms |
| nodeModulesSize | 80.9 MB | 80.8 MB | -9.88 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..b025.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-e66dcae..6635.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-81..14d7.js gzip | 31.2 kB | 31.2 kB | ✓ |
| Overall change | 31.2 kB | 31.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.18 MB | 5.18 MB | ✓ |

</details>

</details>
Commit: 35c4119900edc3e88226f4e9e0247f88309cbba2

2021-01-15 10:14 UTC, hesselbom commented
@newsroomdev Have you tried running this PR on a vercel.com next app? I tried adding distDir to renderOps by patching node_modules/next/dist/next-server/server/next-server.js with patch-package. With that it's running fine both with "next" (i.e. "yarn dev") and with "next build" (i.e. "yarn build") locally but the same error appears when building on Vercel. Adding some logging by patching "critters" the same way I can see that when building on Vercel, distDir is undefined despite the patch.

2021-01-25 23:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 8.7s | 8.7s | -39ms |
| nodeModulesSize | 74.9 MB | 74.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.751 | 1.765 | ⚠️ +0.01 |
| / avg req/sec | 1428.04 | 1416.73 | ⚠️ -11.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.098 | 1.097 | 0 |
| /error-in-render avg req/sec | 2276.95 | 2279.51 | +2.56 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.4s | -212ms |
| nodeModulesSize | 74.9 MB | 74.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.5s | -212ms |
| nodeModulesSize | 74.9 MB | 74.9 MB | ⚠️ +129 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.756 | 1.757 | 0 |
| / avg req/sec | 1423.89 | 1423.09 | ⚠️ -0.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.11 | 1.131 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2252.4 | 2210.57 | ⚠️ -41.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| 597-c48889ef..1870.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _app-a5b2e84..33cf.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-6f1f9..5577.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-725de8..0a15.js gzip | 904 B | 904 B | ✓ |
| index-939503..6e1c.js gzip | 232 B | 232 B | ✓ |
| link-e0cc871..fdbb.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..9360.js gzip | 308 B | 308 B | ✓ |
| withRouter-6..44ec.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | newsroomdev/next.js fix/optimizecss-server-distdir | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js c [...]

2021-02-01 14:12 UTC, newsroomdev commented
Appears to have been fixed in #21646

2021-02-01 14:12 UTC, closed without merging