Add better error reporting
vercel/next.js pull request #2105
Opened 2017-05-29 20:56 UTC by bhefty

#2087 
Not sure if I did this 100% correct so I'm open to suggestions, but this seems to work in throwing a more verbose error message to the console if 'react' or 'react-dom' is not in the dependencies list.

2017-05-31 07:06 UTC, arunoda requested changes

2017-05-31 07:06 UTC, arunoda commented on bin/next
> +      if (dependency === 'react' || dependency === 'react-dom') {
I think we don't need to check this only for react and react-dom. Just make this message the default.

2017-06-01 01:42 UTC, bhefty commented
@arunoda Sorry, not sure why the checks are failing?

2017-06-05 09:21 UTC, timneutkens commented
Closing this in favor of #2168

2017-06-05 09:21 UTC, closed without merging