Fix buildmanifest for webpack 5 splitchunks
vercel/next.js pull request #21325
Opened 2021-01-19 11:28 UTC by timneutkens

Fixes an edge case introduced in #21208

2021-01-19 11:34 UTC, ijjk commented
## Failing test suites <!--1856392201-->
Commit: 4fcbb5584ebc354622e1ff42f0869f36299aca84

**test/integration/auto-export/test/index.test.js** 
- Auto Export > dev > Refreshes query on mount
- Auto Export > dev > should update asPath after mount
- Auto Export > dev > should not show hydration warning from mismatching asPath

<details>
<summary>Expand output</summary>

  ● Auto Export › dev › Refreshes query on mount

    expect(received).toMatch(expected)

    Expected pattern: /post.*post-1/
    Received string:  "<div id=\"__next\"></div><script src=\"/_next/static/chunks/webpack.js?ts=1611056045669\"></script><script src=\"/_next/static/chunks/react-refresh.js?ts=1611056045669\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/[post]\",\"query\":{},\"buildId\":\"development\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false}</script><script nomodule=\"\" src=\"/_next/static/chunks/webpack.js?ts=1611056045669\"></script><script nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1611056045669\"></script><script src=\"/_next/static/chunks/webpack.js?ts=1611056045669\"></script><script src=\"/_next/static/chunks/main.js?ts=1611056045669\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1611056045669\"></script><script src=\"/_next/static/chunks/pages/%5Bpost%5D.js?ts=1611056045669\"></script><div id=\"__next-build-watcher\" style=\"position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;\"></div><script src=\"/_next/static/development/_buildManifest.js?ts=1611056045669\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1611056045669\"></script><nextjs-portal></nextjs-portal>"

      36 |     const browser = await webdriver(appPort, '/post-1')
      37 |     const html = await browser.eval('document.body.innerHTML')
    > 38 |     expect(html).toMatch(/post.*post-1/)
         |                  ^
      39 |     expect(html).toMatch(/nextExport/)
      40 |   })
      41 | 

      at Object.<anonymous> (integration/auto-export/test/index.test.js:38:18)

  ● Auto Export › dev › should update asPath after mount

    expect(received).toMatch(expected)

    Expected pattern: /\/zeit\/cmnt-2/
    Received string:  "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><meta name=\"next-head-count\" content=\"2\"><noscript data-n-css=\"\"></noscript><link rel=\"preload\" href=\"/_next/static/chunks/webpack.js?ts=1611056046428\" as=\"script\"><link rel=\"preload\" href=\"/_next/static/chunks/main.js?ts=1611056046428\" as=\"script\"><link rel=\"preload\" href=\"/_next/static/chunks/pages/_app.js?ts=1611056046428\" as=\"script\"><link rel=\"preload\" href=\"/_next/static/chunks/pages/%5Bpost%5D/%5Bcmnt%5D.js?ts=1611056046428\" as=\"script\"><link rel=\"preload\" href=\"/_next/static/development/_buildManifest.js?ts=1611056046428\" as=\"script\"><noscript id=\"__next_css__DO_NOT_USE__\"></noscript><script charset=\"utf-8\" src=\"/_next/static/chunks/0.js\"></script><script charset=\"utf-8\" src=\"/_next/static/chunks/0.js\"></script></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/webpack.js?ts=1611056046428\"></script><script src=\"/_next/static/chunks/react-refresh.js?ts=1611056046428\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/[post]/[cmnt]\",\"query\":{},\"buildId\":\"development\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false}</script><script nomodule=\"\" src=\"/_next/static/chunks/webpack.js?ts=1611056046428\"></script><script nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1611056046428\"></script><script src=\"/_next/static/chunks/webpack.js?ts=1611056046428\"></script><script src=\"/_next/static/chunks/main.js?ts=1611056046428\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1611056046428\"></script><script src=\"/_next/static/chunks/pages/%5Bpost%5D/%5Bcmnt%5D.js?ts=1611056046428\"></script><div id=\"__next-build-watcher\" style=\"position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;\"></div><script src=\"/_next/static/development/_buildManifest.js?ts=1611056046428\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1611056046428\"></script><nextjs-portal></nextjs-portal></body>"

      43 |     const browser = await webdriver(appPort, '/zeit/cmnt-2')
      44 |     const html = await browser.eval(`document.documentElement.innerHTML`)
    > 45 |     expect(html).toMatch(/\/zeit\/cmnt-2/)
         |                  ^
      46 |   })
      47 | 
      48 |   it('should not replace URL with page name while asPath is delayed', async () => {

      at Object.<anonymous> (integration/auto-export/test/index.test.js:45:18)

  ● Auto Export › dev › should not show hydration warning from mismatching asPath

    expect(received).toEqual(expected) // deep equality

    - Expected  -  1
    + Received  + 62

    - Array []
    + Array [
    +   Array [
    +     "Warning: Did not expect server HTML to contain a <%s> in <%s>.",
    +     "p",
    +     "div",
    +   ],
    +   Array [
    +     "Warning: Did not expect server HTML to contain a <%s> in <%s>.",
    +     "p",
    +     "div",
    +   ],
    +   Array [
    +     "The above error occurred in the <Page> component:
    +
    +     at Page (http://localhost:34873/_next/static/chunks/pages/%5Bpost%5D/%5Bcmnt%5D.js?ts=1611056048029:10134:76)
    +     at App (http://localhost:34873/_next/static/chunks/pages/_app.js?ts=1611056048029:8919:5)
    +     at ErrorBoundary (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43307:47)
    +     at ReactDevOverlay (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43411:23)
    +     at Container (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:36592:5)
    +     at AppContainer (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37080:24)
    +     at Root (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37211:24)
    +
    + React will try to recreate this component tree from scratch using the error boundary you provided, App.",
    +   ],
    +   Array [
    +     "The above error occurred in the <Page> component:
    +
    +     at Page (http://localhost:34873/_next/static/chunks/pages/%5Bpost%5D/%5Bcmnt%5D.js?ts=1611056048029:10134:76)
    +     at App (http://localhost:34873/_next/static/chunks/pages/_app.js?ts=1611056048029:8919:5)
    +     at ErrorBoundary (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43307:47)
    +     at ReactDevOverlay (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43411:23)
    +     at Container (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:36592:5)
    +     at AppContainer (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37080:24)
    +     at Root (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37211:24)
    +
    + React will try to recreate this component tree from scratch using the error boundary you provided, App.",
    +   ],
    +   Array [
    +     "The above error occurred in the <App> component:
    +
    +     at App (http://localhost:34873/_next/static/chunks/pages/_app.js?ts=1611056048029:8919:5)
    +     at ErrorBoundary (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43307:47)
    +     at ReactDevOverlay (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:43411:23)
    +     at Container (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:36592:5)
    +     at AppContainer (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37080:24)
    +     at Root (http://localhost:34873/_next/static/chunks/main.js?ts=1611056048029:37211:24)
    +
    + React will try to recreate this component tree from scratch using the [...]

2021-01-19 11:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11.3s | ⚠️ +385ms |
| nodeModulesSize | 77.6 MB | 77.6 MB | -1.04 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.114 | 2.17 | ⚠️ +0.06 |
| / avg req/sec | 1182.37 | 1151.96 | ⚠️ -30.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.374 | 1.389 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1820.11 | 1799.4 | ⚠️ -20.71 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9e3e4e6..2023.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| polyfills-af..9390.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -50,11 +50,11 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
+      src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
+      nomodule=""
+      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
@@ -68,6 +68,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -55,11 +55,11 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
+      src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
+      nomodule=""
+      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
@@ -73,6 +73,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -50,11 +50,11 @@
     </script>
     <script
       nomodule=""
-      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
+      src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
     ></script>
     <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
+      nomodule=""
+      src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
     <script
       sr [...]

2021-01-19 11:48 UTC, ijjk commented
## Failing test suites <!--1856468627-->
Commit: 70252546154c3811b2d3c8236f81c501ba612fd6

**test/integration/client-shallow-routing/test/index.test.js** 
- Client Shallow Routing > dev mode > should not shallowly navigate back in history when current page was not shallow
- Client Shallow Routing > dev mode > should not shallowly navigate forwards in history when current page was not shallow

<details>
<summary>Expand output</summary>

  ● Client Shallow Routing › dev mode › should not shallowly navigate back in history when current page was not shallow

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#add-query-shallow"}
      (Session info: headless chrome=87.0.4280.141)

      24 |     expect(props.params).toEqual({ slug: 'first' })
      25 | 
    > 26 |     await browser.elementByCss('#add-query-shallow').click()
         |     ^
      27 | 
      28 |     const props2 = JSON.parse(await browser.elementByCss('#props').text())
      29 |     expect(props2).toEqual(props)

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/client-shallow-routing/test/index.test.js:26:5)

  ● Client Shallow Routing › dev mode › should not shallowly navigate forwards in history when current page was not shallow

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#add-query-shallow"}
      (Session info: headless chrome=87.0.4280.141)

      53 |     expect(props.params).toEqual({ slug: 'first' })
      54 | 
    > 55 |     await browser.elementByCss('#add-query-shallow').click()
         |     ^
      56 | 
      57 |     const props2 = JSON.parse(await browser.elementByCss('#props').text())
      58 |     expect(props2).toEqual(props)

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/client-shallow-routing/test/index.test.js:55:5)

</details>

2021-01-19 11:52 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| buildDuration | 8.1s | 7.7s | -350ms |
| nodeModulesSize | 77.6 MB | 77.6 MB | ⚠️ +9.74 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.647 | 1.616 | -0.03 |
| / avg req/sec | 1518.29 | 1546.75 | +28.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.086 | 1.045 | -0.04 |
| /error-in-render avg req/sec | 2301.93 | 2391.29 | +89.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9e3e4e6..2023.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| polyfills-af..9390.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -57,10 +57,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -73,6 +69,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase de [...]

2021-01-19 12:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.2s | -16ms |
| nodeModulesSize | 77.6 MB | 77.6 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.97 | 1.951 | -0.02 |
| / avg req/sec | 1269 | 1281.41 | +12.41 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.212 | 1.216 | 0 |
| /error-in-render avg req/sec | 2063.54 | 2056.17 | ⚠️ -7.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-9e3e4e6..2023.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-50be..df5b.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| polyfills-af..9390.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -57,10 +57,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -73,6 +69,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-d0ca4c755b62bd05137c.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected  [...]

2021-01-19 12:59 UTC, timneutkens commented
<img width="823" alt="Screen Shot 2021-01-19 at 13 59 12" src="https://user-images.githubusercontent.com/6324199/105037616-8897af80-5a5e-11eb-92e4-74396445ee86.png">

This would explain the 88b polyfills report, which is incorrect. The file is split out into more bundles.

2021-01-20 09:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| buildDuration | 7.7s | 7.8s | ⚠️ +104ms |
| nodeModulesSize | 73.3 MB | 73.3 MB | ⚠️ +241 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.603 | 1.592 | -0.01 |
| / avg req/sec | 1559.75 | 1570.04 | +10.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.97 | 1.008 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2576.85 | 2481.21 | ⚠️ -95.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| 677f882d2ed8..43e3.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/webpack5-splitchunks | Change |
| - | - | - | - |
| index.html gzip | 616 B | 616 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.85 kB | 1.85 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-039d3df776c23de90078.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-039d3df776c23de90078.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-039d3df776c23de90078.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-039d3df776c23de90078.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-039d3df776c23de90078.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-039d3df776c23de90078.js"
       as="script"
     />
     <link
@@ -57,10 +57,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-039d3df776c23de90078.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -73,6 +69,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-039d3df776c23de90078.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -7,22 +7,22 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/main-039d3df776c23de90078.js"
+      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
+      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/framework.c2766659ac6e6a63ca79.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       as="script"
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
+      href="/_next/static/chunks/main-039d3df776c23de90078.js"
       as="script"
     />
     <link
@@ -52,10 +52,6 @@
       nomodule=""
       src="/_next/static/chunks/polyfills-7cd0807c85ae48513b2d.js"
     ></script>
-    <script
-      src="/_next/static/chunks/main-039d3df776c23de90078.js"
-      async=""
-    ></script>
     <script
       src="/_next/static/chunks/webpack-becabbdf5d4df28a038e.js"
       async=""
@@ -68,6 +64,10 @@
       src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.68413f75a18d3759e1c6.js"
       async=""
     ></script>
+    <script
+      src="/_next/static/chunks/main-039d3df776c23de90078.js"
+      async=""
+    ></script>
     <script
       src="/_next/static/chunks/pages/_app-b9cf267ce11e4373e54e.js"
       async=""
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</s [...]

2021-01-20 18:02 UTC, Timer requested changes
Blocking this temporarily while so we can adjust the polyfill chunk handling.

Also, the react refresh chunk handling can probably be tweaked, too.

2021-02-12 13:33 UTC, closed without merging