Remove revert of custom devtool in development mode
vercel/next.js pull request #21450
Opened 2021-01-22 16:23 UTC by ryan-codingintrigue

Remove the *revert* of `devtool` when manually changed for development mode, leaving in-tact the warning about the effects of its use.

As described in [this discussion (20294)](https://github.com/vercel/next.js/discussions/20294) the revert of the devtool has two knock-on effects:
1) Strict Content Security Policy cannot be used in development mode, causing a severe difference between dev & production
2) SSR debugging on Windows does not work correctly

This allows the user to make a **choice** about the use of `devtool` in development, giving the information in [the example](https://github.com/vercel/next.js/blob/master/errors/improper-devtool.md) as cause not to change it unless absolutely necessary.

2021-01-22 17:08 UTC, Timer requested changes
Next.js' dev tooling is not compatible with other source map modes, so things like the overlay will not necessarily work correctly or in the most optimal way. We're likely not going to add support for this.

Happy to fence an RFC about official CSP support which could work around the `eval` limitations.

2021-01-22 17:38 UTC, ryan-codingintrigue commented
> Next.js' dev tooling is not compatible with other source map modes, so things like the overlay will not necessarily work correctly or in the most optimal way. We're likely not going to add support for this.
> 
> Happy to fence an RFC about official CSP support which could work around the `eval` limitations.

Makes sense.

What about allowing `inline-source-map` or `eval-source-map` as required instead of forcing the OS down the path?
https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/config/blocks/base.ts

That might address at least the SSR debugging on Windows. Could also allow non-Windows not to use eval.

I still think there is merit in the warning, but the revert is overly prohibitive. I'd even sacrifice the overlay myself but like to have the option.

2021-02-03 17:10 UTC, ijjk commented
## Failing test suites <!--1960942953-->
Commit: a6c1f9cfe777be516016523a764aa5ba50bb274c

**test/integration/script-loader/test/index.test.js** 
- Script Loader > priority lazy

<details>
<summary>Expand output</summary>

  ● Script Loader › priority lazy

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      66 |   })
      67 | 
    > 68 |   it('priority lazy', async () => {
         |   ^
      69 |     let browser
      70 |     try {
      71 |       browser = await webdriver(appPort, '/page3')

      at integration/script-loader/test/index.test.js:68:3
      at Object.<anonymous> (integration/script-loader/test/index.test.js:21:1)

</details>

2021-02-24 09:18 UTC, ryan-codingintrigue commented
@Timer Just checking in to see if there's a way we can move this forward?

I still feel the [`isWindows`](https://github.com/vercel/next.js/blob/460c7c7ddcc55f9f15e43250b01f09e8385abc52/packages/next/build/webpack/config/blocks/base.ts#L25) check could be handed off to the user if required whilst keeping existing functionality in-tact, e.g.:

```
if (process.env.__NEXT_TEST_MODE && !process.env.__NEXT_TEST_WITH_DEVTOOL) {
      config.devtool = false
    } else if(ctx.unsaveDevToolOverride && ['inline-source-map', 'eval-source-map'].includes(ctx.unsaveDevToolOverride)) {
      config.devtool = ctx.unsaveDevToolOverride;
    } else if (isWindows) {
      // Non-eval based source maps are slow to rebuild, so we only enable
      // them for Windows. Unfortunately, eval source maps are flagged as
      // suspicious by Windows Defender and block HMR.
      config.devtool = 'inline-source-map'
    } else {
      // `eval-source-map` provides full-fidelity source maps for the
      // original source, including columns and original variable names.
      // This is desirable so the in-browser debugger can correctly pause
      // and show scoped variables with their original names.
      config.devtool = 'eval-source-map'
    }
```
If Windows users are forced to use `inline-source-map` then I see no reason why other users can't choose to use it if it suits their use case.

2021-12-07 15:32 UTC, closed without merging