Fix Link.href the same URL, begin with slash
vercel/next.js pull request #21623
Opened 2021-01-28 11:54 UTC by tarunama

fixes #19998 
Fixes Link href value, when does set `add-prefix-slash`(does not start begin slash) to Link href

- Fix return value when condition is true
- Add client side test
- Add server side test

2021-01-28 11:58 UTC, ijjk commented
## Failing test suites <!--1917717344-->
Commit: 3b0171c9bd8644ef37aa4467904ffb6e815d2ff4

**test/unit/link-rendering.unit.test.js** 
- Link rendering > should render Link on its own

<details>
<summary>Expand output</summary>

  ● Link rendering › should render Link on its own

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Link rendering should render Link on its own 1`

    Snapshot: "<a href=\"/my-path\" data-reactroot=\"\">to another page</a>"
    Received: "<a href=\"my-path\" data-reactroot=\"\">to another page</a>"

      14 |     )
      15 |     const html = ReactDOM.renderToString(element)
    > 16 |     expect(html).toMatchInlineSnapshot(
         |                  ^
      17 |       `"<a href=\\"/my-path\\" data-reactroot=\\"\\">to another page</a>"`
      18 |     )
      19 |   })

      at Object.<anonymous> (unit/link-rendering.unit.test.js:16:18)

</details>

2021-01-28 12:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 8.9s | 8.8s | -40ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.763 | 1.806 | ⚠️ +0.04 |
| / avg req/sec | 1418.02 | 1384.21 | ⚠️ -33.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.142 | 1.116 | -0.03 |
| /error-in-render avg req/sec | 2189.32 | 2239.17 | +49.85 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ⚠️ +4 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 613 B | -1 B |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..dde534236.js</strong></summary>

```diff
@@ -1447,7 +1447,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
           var resolvedHref =
             finalUrl.origin === base.origin
-              ? finalUrl.href.slice(finalUrl.origin.length)
+              ? finalUrl.href.slice(finalUrl.origin.length + 1)
               : finalUrl.href;
           return resolveAs
             ? [resolvedHref, interpolatedAs || resolvedHref]
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       as="script"
     />
     <link
@@ -40,7 +40,7 @@
     <div id="__next">
       <div>
         <h3>A Link page!</h3>
-        <a href="/">Go to /</a>
+        <a href="">Go to /</a>
       </div>
     </div>
     <script id="__NEXT_DATA__" type="application/json">
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c64b6e32607d53e26ce8.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 11s | 10.7s | -315ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..0a50.js gzip | N/A | 13.1 kB | N/A |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +4 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB [...]

2021-01-28 13:06 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 8.7s | 8.6s | -130ms |
| nodeModulesSize | 75 MB | 75 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.697 | 1.72 | ⚠️ +0.02 |
| / avg req/sec | 1473.03 | 1453.17 | ⚠️ -19.86 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.065 | 1.075 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2346.57 | 2326.42 | ⚠️ -20.15 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.3s | -80ms |
| nodeModulesSize | 75 MB | 75 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.05 MB | 1.05 MB | ✓ |
| withRouter.js | 1.05 MB | 1.05 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.5s | ⚠️ +125ms |
| nodeModulesSize | 75 MB | 75 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.714 | 1.741 | ⚠️ +0.03 |
| / avg req/sec | 1458.63 | 1436.35 | ⚠️ -22.28 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.099 | 1.09 | -0.01 |
| /error-in-render avg req/sec | 2273.98 | 2292.76 | +18.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 597-7c719119..27b6.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
        [...]

2021-01-28 13:15 UTC, ijjk commented
## Failing test suites <!--1918104343-->
Commit: 6d8e3e371ebcd38b0b8a707c7377de57303b98d9

**test/integration/client-navigation/test/index.test.js** 
- Client Navigation > should add prefix slash
- Client Navigation > with hash changes > check hydration mis-match > should not have hydration mis-match for hash link

<details>
<summary>Expand output</summary>

  ● Client Navigation › with hash changes › check hydration mis-match › should not have hydration mis-match for hash link

    expect(received).toEqual(expected) // deep equality

    Expected: false
    Received: true

      563 |           }
      564 |         })
    > 565 |         expect(found).toEqual(false)
          |                       ^
      566 |       })
      567 |     })
      568 | 

      at Object.<anonymous> (integration/client-navigation/test/index.test.js:565:23)
          at runMicrotasks (<anonymous>)

  ● Client Navigation › should add prefix slash

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"a"}
      (Session info: headless chrome=88.0.4324.96)

      1561 |   it('should add prefix slash', async () => {
      1562 |     const browser = await webdriver(context.appPort, '/add-prefix-slash')
    > 1563 |     expect(await browser.elementByCss('a').text()).toBe('Add prefix slash')
           |            ^
      1564 | 
      1565 |     await browser.close()
      1566 |   })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
          at runMicrotasks (<anonymous>)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/client-navigation/test/index.test.js:1563:12)

</details>

2021-01-29 02:58 UTC, ijjk commented
## Failing test suites <!--1923245778-->
Commit: b9b4f792bf6b2387c1e0a68b25409995b8ae9388

**test/integration/absolute-assetprefix/test/index.test.js** 
- absolute assetPrefix with path prefix > should fetch from cache correctly

<details>
<summary>Expand output</summary>

  ● absolute assetPrefix with path prefix › should fetch from cache correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: null

      84 |     const prop = await browser.waitForElementByCss('#prop').text()
      85 |     expect(prop).toBe('hello')
    > 86 |     expect(await browser.eval('window.clientSideNavigated')).toBe(true)
         |                                                              ^
      87 |     expect(
      88 |       cdnAccessLog.filter(
      89 |         (path) => path === `/_next/data/${buildId}/about.json`

      at Object.<anonymous> (integration/absolute-assetprefix/test/index.test.js:86:62)

</details>

2021-01-29 03:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 11.2s | 11s | -187ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +532 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.229 | 2.327 | ⚠️ +0.1 |
| / avg req/sec | 1121.8 | 1074.16 | ⚠️ -47.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.597 | 1.588 | -0.01 |
| /error-in-render avg req/sec | 1565.51 | 1574.42 | +8.91 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ⚠️ +34 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +34 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 607 B | 608 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..dde534236.js</strong></summary>

```diff
@@ -343,13 +343,26 @@
 
       var slashedProtocols = /https?|ftp|gopher|file/;
 
-      function formatUrl(urlObj) {
-        var auth = urlObj.auth,
-          hostname = urlObj.hostname;
+      function getProtocol(urlObj) {
+        var _protocol;
+
         var protocol = urlObj.protocol || "";
-        var pathname = urlObj.pathname || "";
-        var hash = urlObj.hash || "";
-        var query = urlObj.query || "";
+
+        if (
+          ((_protocol = protocol) == null ? void 0 : _protocol.substr(-1)) !==
+          ":"
+        ) {
+          protocol += ":";
+        }
+
+        return protocol;
+      }
+
+      function formatUrl(urlObj) {
+        var _hash, _search;
+
+        var auth = urlObj.auth;
+        var hostname = urlObj.hostname;
         var host = false;
         auth = auth ? encodeURIComponent(auth).replace(/%3A/i, ":") + "@" : "";
 
@@ -365,25 +378,34 @@
           }
         }
 
+        var query = urlObj.query || "";
+
         if (query && typeof query === "object") {
           query = String(querystring.urlQueryToSearchParams(query));
         }
 
-        var search = urlObj.search || (query && "?".concat(query)) || "";
-        if (protocol && protocol.substr(-1) !== ":") protocol += ":";
+        var protocol = getProtocol(urlObj);
+        var pathname = urlObj.pathname || "";
 
         if (
           urlObj.slashes ||
           ((!protocol || slashedProtocols.test(protocol)) && host !== false)
         ) {
+          var _pathname;
+
           host = "//" + (host || "");
-          if (pathname && pathname[0] !== "/") pathname = "/" + pathname;
+          if (((_pathname = pathname) == null ? void 0 : _pathname[0]) !== "/")
+            pathname = "/" + pathname;
         } else if (!host) {
           host = "";
         }
 
-        if (hash && hash[0] !== "#") hash = "#" + hash;
-        if (search && search[0] !== "?") search = "?" + search;
+        var hash = urlObj.hash || "";
+        if (((_hash = hash) == null ? void 0 : _hash[0]) !== "#")
+          hash = "#" + hash;
+        var search = urlObj.search || (query && "?".concat(query)) || "";
+        if (((_search = search) == null ? void 0 : _search[0]) !== "?")
+          search = "?" + search;
         pathname = pathname.replace(/[?#]/g, encodeURIComponent);
         search = search.replace("#", "%23");
         return ""
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.f1a9ca7a638bc4c7f73b.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.1s | -144ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +532 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js  [...]

2021-01-29 03:12 UTC, ijjk commented
## Failing test suites <!--1923294695-->
Commit: b6007de789e60b9d19fd163b093f96e8f81b139b

**test/integration/absolute-assetprefix/test/index.test.js** 
- absolute assetPrefix with path prefix > should fetch from cache correctly

<details>
<summary>Expand output</summary>

  ● absolute assetPrefix with path prefix › should fetch from cache correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: null

      84 |     const prop = await browser.waitForElementByCss('#prop').text()
      85 |     expect(prop).toBe('hello')
    > 86 |     expect(await browser.eval('window.clientSideNavigated')).toBe(true)
         |                                                              ^
      87 |     expect(
      88 |       cdnAccessLog.filter(
      89 |         (path) => path === `/_next/data/${buildId}/about.json`

      at Object.<anonymous> (integration/absolute-assetprefix/test/index.test.js:86:62)

</details>

2021-01-29 03:14 UTC, gubasza51 commented
@

2021-01-29 03:19 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.1s | ⚠️ +29ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +1.47 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.363 | 2.302 | -0.06 |
| / avg req/sec | 1057.76 | 1086.11 | +28.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.597 | 1.565 | -0.03 |
| /error-in-render avg req/sec | 1565.84 | 1597.22 | +31.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ⚠️ +24 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 613 B | -1 B |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..dde534236.js</strong></summary>

```diff
@@ -343,13 +343,55 @@
 
       var slashedProtocols = /https?|ftp|gopher|file/;
 
-      function formatUrl(urlObj) {
-        var auth = urlObj.auth,
-          hostname = urlObj.hostname;
+      function getQuery(urlObj) {
+        var query = urlObj.query || "";
+
+        if (query && typeof query === "object") {
+          query = String(querystring.urlQueryToSearchParams(query));
+        }
+
+        return query;
+      }
+
+      function getProtocol(urlObj) {
+        var _protocol;
+
         var protocol = urlObj.protocol || "";
-        var pathname = urlObj.pathname || "";
+
+        if (
+          ((_protocol = protocol) == null ? void 0 : _protocol.substr(-1)) !==
+          ":"
+        ) {
+          protocol += ":";
+        }
+
+        return protocol;
+      }
+
+      function getSearch(urlObj, query) {
+        var _search;
+
+        var search = urlObj.search || (query && "?".concat(query)) || "";
+
+        if (((_search = search) == null ? void 0 : _search[0]) !== "?") {
+          search = "?" + search;
+        }
+
+        return search.replace("#", "%23");
+      }
+
+      function getHash(urlObj) {
+        var _hash;
+
         var hash = urlObj.hash || "";
-        var query = urlObj.query || "";
+        if (((_hash = hash) == null ? void 0 : _hash[0]) !== "#")
+          hash = "#" + hash;
+        return hash;
+      }
+
+      function formatUrl(urlObj) {
+        var auth = urlObj.auth;
+        var hostname = urlObj.hostname;
         var host = false;
         auth = auth ? encodeURIComponent(auth).replace(/%3A/i, ":") + "@" : "";
 
@@ -365,27 +407,26 @@
           }
         }
 
-        if (query && typeof query === "object") {
-          query = String(querystring.urlQueryToSearchParams(query));
-        }
-
-        var search = urlObj.search || (query && "?".concat(query)) || "";
-        if (protocol && protocol.substr(-1) !== ":") protocol += ":";
+        var query = getQuery(urlObj);
+        var protocol = getProtocol(urlObj);
+        var pathname = urlObj.pathname || "";
 
         if (
           urlObj.slashes ||
           ((!protocol || slashedProtocols.test(protocol)) && host !== false)
         ) {
+          var _pathname;
+
           host = "//" + (host || "");
-          if (pathname && pathname[0] !== "/") pathname = "/" + pathname;
+          if (((_pathname = pathname) == null ? void 0 : _pathname[0]) !== "/")
+            pathname = "/" + pathname;
         } else if (!host) {
           host = "";
         }
 
-        if (hash && hash[0] !== "#") hash = "#" + hash;
-        if (search && search[0] !== "?") search = "?" + search;
         pathname = pathname.replace(/[?#]/g, encodeURIComponent);
-        search = search.replace("#", "%23");
+        var search = getSearch(urlObj, query);
+        var hash = getHash(urlObj);
         return ""
           .concat(protocol)
           .concat(host)
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.cdf74e767e7792015bb4.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Se [...]

2021-01-29 03:32 UTC, ijjk commented
## Failing test suites <!--1923376300-->
Commit: 80bef38dfc3ac5798ac7f5c182e771b776f39d22

**test/unit/link-rendering.unit.test.js** 
- Link rendering > should render Link on its own

<details>
<summary>Expand output</summary>

  ● Link rendering › should render Link on its own

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Link rendering should render Link on its own 1`

    Snapshot: "<a href=\"/my-path\" data-reactroot=\"\">to another page</a>"
    Received: "<a href=\"my-path\" data-reactroot=\"\">to another page</a>"

      14 |     )
      15 |     const html = ReactDOM.renderToString(element)
    > 16 |     expect(html).toMatchInlineSnapshot(
         |                  ^
      17 |       `"<a href=\\"/my-path\\" data-reactroot=\\"\\">to another page</a>"`
      18 |     )
      19 |   })

      at Object.<anonymous> (unit/link-rendering.unit.test.js:16:18)

</details>

2021-01-29 03:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 10.9s | 10.1s | -808ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +1.49 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.143 | 2.1 | -0.04 |
| / avg req/sec | 1166.74 | 1190.31 | +23.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.619 | 1.494 | -0.12 |
| /error-in-render avg req/sec | 1543.73 | 1673.9 | +130.17 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ⚠️ +29 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +29 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 607 B | 608 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..dde534236.js</strong></summary>

```diff
@@ -343,13 +343,55 @@
 
       var slashedProtocols = /https?|ftp|gopher|file/;
 
-      function formatUrl(urlObj) {
-        var auth = urlObj.auth,
-          hostname = urlObj.hostname;
+      function getQuery(urlObj) {
+        var query = urlObj.query || "";
+
+        if (query && typeof query === "object") {
+          query = String(querystring.urlQueryToSearchParams(query));
+        }
+
+        return query;
+      }
+
+      function getProtocol(urlObj) {
+        var _protocol;
+
         var protocol = urlObj.protocol || "";
-        var pathname = urlObj.pathname || "";
+
+        if (
+          ((_protocol = protocol) == null ? void 0 : _protocol.substr(-1)) !==
+          ":"
+        ) {
+          protocol += ":";
+        }
+
+        return protocol;
+      }
+
+      function getSearch(urlObj, query) {
+        var _search;
+
+        var search = urlObj.search || (query && "?".concat(query)) || "";
+
+        if (((_search = search) == null ? void 0 : _search[0]) !== "?") {
+          search = "?" + search;
+        }
+
+        return search.replace("#", "%23");
+      }
+
+      function getHash(urlObj) {
+        var _hash;
+
         var hash = urlObj.hash || "";
-        var query = urlObj.query || "";
+        if (((_hash = hash) == null ? void 0 : _hash[0]) !== "#")
+          hash = "#" + hash;
+        return hash;
+      }
+
+      function formatUrl(urlObj) {
+        var auth = urlObj.auth;
+        var hostname = urlObj.hostname;
         var host = false;
         auth = auth ? encodeURIComponent(auth).replace(/%3A/i, ":") + "@" : "";
 
@@ -365,27 +407,26 @@
           }
         }
 
-        if (query && typeof query === "object") {
-          query = String(querystring.urlQueryToSearchParams(query));
-        }
-
-        var search = urlObj.search || (query && "?".concat(query)) || "";
-        if (protocol && protocol.substr(-1) !== ":") protocol += ":";
+        var query = getQuery(urlObj);
+        var protocol = getProtocol(urlObj);
+        var pathname = urlObj.pathname || "";
 
         if (
           urlObj.slashes ||
           ((!protocol || slashedProtocols.test(protocol)) && host !== false)
         ) {
+          var _pathname;
+
           host = "//" + (host || "");
-          if (pathname && pathname[0] !== "/") pathname = "/" + pathname;
+          if (((_pathname = pathname) == null ? void 0 : _pathname[0]) !== "/")
+            pathname = "/" + pathname;
         } else if (!host) {
           host = "";
         }
 
-        if (hash && hash[0] !== "#") hash = "#" + hash;
-        if (search && search[0] !== "?") search = "?" + search;
         pathname = pathname.replace(/[?#]/g, encodeURIComponent);
-        search = search.replace("#", "%23");
+        var search = getSearch(urlObj, query);
+        var hash = getHash(urlObj);
         return ""
           .concat(protocol)
           .concat(host)
@@ -1400,8 +1441,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
        */
 
       function resolveHref(currentPath, href, resolveAs) {
-        // we use a dummy base url for relative urls
-        var base = new URL(currentPath, "http://n");
         var urlAsString =
           typeof href === "string"
             ? href
@@ -1412,6 +1451,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
 
         try {
+          // we use a dummy base url for relative urls
+          var base = new URL(currentPath, "http://n");
           var finalUrl = new URL(urlAsString, base);
           finalUrl.pathname = (0,
           _normalizeTrailingSlash.normalizePathTrailingSlash)(
@@ -1447,7 +1488,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
           var resolvedHref =
             finalUrl.origin === base.origin
-              ? finalUrl.href.slice(finalUrl.origin.length)
+              ? finalUrl.href.slice(finalUrl.origin.length + 1)
               : finalUrl.href;
           return resolveAs
             ? [resolvedHref, interpolatedAs || resolvedHref]
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ff9891b9965ad26acbf9.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ff9891b9965ad26acbf9.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/ [...]

2021-01-29 03:47 UTC, ijjk commented
## Failing test suites <!--1923429165-->
Commit: 951d5b30211d9852d6723625a18e4169bb58eebc

**test/unit/link-rendering.unit.test.js** 
- Link rendering > should render Link on its own

<details>
<summary>Expand output</summary>

  ● Link rendering › should render Link on its own

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `Link rendering should render Link on its own 1`

    Snapshot: "<a href=\"/my-path\" data-reactroot=\"\">to another page</a>"
    Received: "<a href=\"my-path\" data-reactroot=\"\">to another page</a>"

      14 |     )
      15 |     const html = ReactDOM.renderToString(element)
    > 16 |     expect(html).toMatchInlineSnapshot(
         |                  ^
      17 |       `"<a href=\\"/my-path\\" data-reactroot=\\"\\">to another page</a>"`
      18 |     )
      19 |   })

      at Object.<anonymous> (unit/link-rendering.unit.test.js:16:18)

</details>

2021-01-29 03:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.9s | -156ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.445 | 2.355 | -0.09 |
| / avg req/sec | 1022.44 | 1061.52 | +39.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.732 | 1.669 | -0.06 |
| /error-in-render avg req/sec | 1443.06 | 1497.51 | +54.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | 13.1 kB | ⚠️ +5 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 607 B | 607 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..dde534236.js</strong></summary>

```diff
@@ -1400,8 +1400,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
        */
 
       function resolveHref(currentPath, href, resolveAs) {
-        // we use a dummy base url for relative urls
-        var base = new URL(currentPath, "http://n");
         var urlAsString =
           typeof href === "string"
             ? href
@@ -1412,6 +1410,8 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
 
         try {
+          // we use a dummy base url for relative urls
+          var base = new URL(currentPath, "http://n");
           var finalUrl = new URL(urlAsString, base);
           finalUrl.pathname = (0,
           _normalizeTrailingSlash.normalizePathTrailingSlash)(
@@ -1447,7 +1447,7 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
 
           var resolvedHref =
             finalUrl.origin === base.origin
-              ? finalUrl.href.slice(finalUrl.origin.length)
+              ? finalUrl.href.slice(finalUrl.origin.length + 1)
               : finalUrl.href;
           return resolveAs
             ? [resolvedHref, interpolatedAs || resolvedHref]
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       as="script"
     />
     <link
@@ -40,7 +40,7 @@
     <div id="__next">
       <div>
         <h3>A Link page!</h3>
-        <a href="/">Go to /</a>
+        <a href="">Go to /</a>
       </div>
     </div>
     <script id="__NEXT_DATA__" type="application/json">
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.d59cca9b248dde534236.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ac12a2d40ac4bff15f2d.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.1s | -560ms |
| nodeModulesSize | 75 MB | 75 MB | ⚠️ +22 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| 677f882d2ed8..38ed.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..1b09.js gzip | N/A | 13.1 kB | N/A |
| Overall change | 59.4 kB | 59.5 kB | ⚠️ +5 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | tarunama/next.js fix/prefix-slash | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1 [...]

2022-02-06 20:24 UTC, ijjk requested changes
Hi, this doesn't look like the right approach to resolve #19922 and seems to be breaking tests. I'm gonna close this since it's pretty out of date, if you'd like to open a fresh PR for this I think we want to ensure [`getLocationOrigin`](https://github.com/vercel/next.js/blob/6090101581620416ae653d519608f03dc966be9f/packages/next/shared/lib/utils.ts#L324) is updated to check correctly on the server potentially using the host header.

2022-02-06 20:25 UTC, closed without merging