fix: convert Set spread calls to Array.from for more universal compatibility #17094
vercel/next.js pull request #21837
Opened 2021-02-04 01:02 UTC by wyantb

For background, see the issue this fixes: https://github.com/vercel/next.js/issues/17094

Please let me know if there's any tests you'd like me to run as part of putting this up here; I attempted to run the headless test suite according to https://github.com/vercel/next.js/blob/4dc32ec0a7bc389d553efcbf976d4a5429c3fc72/contributing.md but eventually the suite bailed out because of a used port. And NOTE: I did see failures in the `SSG Prerender serverless mode` testcase suite - such failures seem unlikely to be caused by this change, but perhaps I'm missing something very obviously wrong here. Either way, if these are important to you I'm happy to dig in further. 

Caniuse lists pretty widespread availability for `Array.from` (outside of IE11 which would need to have the spread polyfilled/converted by the typescript compiler anyway) so I wouldn't expect any compatibility concerns with this either. Again, happy to dig in further if these are of a concern to you.

2021-02-04 01:11 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 8.9s | 8.7s | -213ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +85 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.753 | 1.756 | 0 |
| / avg req/sec | 1426.5 | 1423.45 | ⚠️ -3.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.093 | 1.067 | -0.03 |
| /error-in-render avg req/sec | 2286.44 | 2341.96 | +55.52 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.5s | ⚠️ +83ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +85 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +7 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +7 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +35 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.7s | ⚠️ +307ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +85 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.711 | 1.77 | ⚠️ +0.06 |
| / avg req/sec | 1461.45 | 1412.08 | ⚠️ -49.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.105 | 1.076 | -0.03 |
| /error-in-render avg req/sec | 2263.35 | 2323.03 | +59.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "iKWNO6LIT0_yzgsQhcrL [...]

2021-02-04 01:52 UTC, wyantb commented
(Force pushed to address prettier failure)

2021-02-04 02:02 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 11.1s | 11.2s | ⚠️ +90ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.394 | 2.363 | -0.03 |
| / avg req/sec | 1044.25 | 1057.76 | +13.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.678 | 1.611 | -0.07 |
| /error-in-render avg req/sec | 1489.75 | 1551.79 | +62.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.5s | ⚠️ +18ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +7 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +7 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +35 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14s | 14s | -56ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.472 | 2.366 | -0.11 |
| / avg req/sec | 1011.41 | 1056.52 | +45.11 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.677 | 1.612 | -0.06 |
| /error-in-render avg req/sec | 1490.94 | 1551.14 | +60.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 579 B | 579 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "kScpdV75pgMIn3MH5k7IA",
+   [...]

2021-02-05 03:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.7s | 10.6s | -140ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.224 | 2.175 | -0.05 |
| / avg req/sec | 1124.05 | 1149.66 | +25.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.589 | 1.554 | -0.03 |
| /error-in-render avg req/sec | 1573.29 | 1608.59 | +35.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 13s | 12.7s | -284ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +7 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +7 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +35 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 13.5s | 13.1s | -361ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +84 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.187 | 2.242 | ⚠️ +0.06 |
| / avg req/sec | 1143.32 | 1115.18 | ⚠️ -28.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.566 | 1.563 | 0 |
| /error-in-render avg req/sec | 1596.7 | 1599.42 | +2.72 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 592 B | 592 B | ✓ |
| withRouter.html gzip | 580 B | 580 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "44PWwr7-WjVf9qsuN0J5I",
+    [...]

2021-02-08 16:46 UTC, wyantb commented
Tim or others, I don't want to ping with an @ mention unless necessary - is there any chance this could make it into nextjs 10.0.7? As it stands since we always use a custom server, I can't actually upgrade any of our projects to the latest version.

2021-02-11 01:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.4s | -181ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +38 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.093 | 2.028 | -0.06 |
| / avg req/sec | 1194.38 | 1232.65 | +38.27 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.271 | 1.282 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1966.24 | 1950.05 | ⚠️ -16.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.5s | ⚠️ +39ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +38 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +7 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ⚠️ +7 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +7 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +35 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| buildDuration | 12.5s | 13.1s | ⚠️ +613ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +38 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.966 | 2.125 | ⚠️ +0.16 |
| / avg req/sec | 1271.68 | 1176.36 | ⚠️ -95.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.245 | 1.409 | ⚠️ +0.16 |
| /error-in-render avg req/sec | 2007.48 | 1774.71 | ⚠️ -232.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | wyantb/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.75 kB | 1.75 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -43,7 +43,7 @@
         "props": { "pageProps": {} },
         "page": "/",
         "query": {},
-        "buildId": "b [...]

2021-02-11 01:55 UTC, ijjk commented
## Failing test suites <!--2015150692-->
Commit: b84695efb35163c891ed2bcade9e13fa2489ac08

**test/integration/script-loader/test/index.test.js** 
- Script Loader > priority lazy

<details>
<summary>Expand output</summary>

  ● Script Loader › priority lazy

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      66 |   })
      67 | 
    > 68 |   it('priority lazy', async () => {
         |   ^
      69 |     let browser
      70 |     try {
      71 |       browser = await webdriver(appPort, '/page3')

      at integration/script-loader/test/index.test.js:68:3
      at Object.<anonymous> (integration/script-loader/test/index.test.js:21:1)

</details>

2021-02-11 09:38 UTC, timneutkens requested changes
It's unclear why this would be any different from spreading into the array. There shouldn't be any helpers for this compiled 🤔

E.g. looking at the compiled file: `.next/server/pages/_document.js` shows the exact code written is in the final bundle:

```js
function getDocumentFiles(buildManifest, pathname, inAmpMode) {
  const sharedFiles = (0, _getPageFiles.getPageFiles)(buildManifest, '/_app');
  const pageFiles = inAmpMode ? [] : (0, _getPageFiles.getPageFiles)(buildManifest, pathname);
  return {
    sharedFiles,
    pageFiles,
    allFiles: [...new Set([...sharedFiles, ...pageFiles])]
  };
}
```

Can you add integration tests for this case? As there's currently no failing tests for this change.

2021-02-11 15:42 UTC, wyantb commented
I admit to some confusion as well, yes. If I try to spread a Set _outside_ of this context, it behaves fine. I'll take a closer look at our babel context and try to come up with an integration test for this.

The symptoms are still oddly clear, though. If I prettify the file locally in my dist folder, to the following:

~/dev/Golden-Portal/node_modules/next/dist/pages/_document.js, lines 77-87:

```
function getDocumentFiles(buildManifest, pathname, inAmpMode) {
    const sharedFiles = (0, _getPageFiles.getPageFiles)(buildManifest, '/_app');
    const pageFiles = inAmpMode ? [] : (0, _getPageFiles.getPageFiles)(buildManifest, pathname);
    const ret = {
        sharedFiles,
        pageFiles,
        allFiles: [...new Set([...sharedFiles, ...pageFiles])]
    };
    console.log(sharedFiles, pageFiles, ret);
    return ret;
}
```

Then I get the following output (see the allFiles [Set (4)...]):

```
_app api configured: http://localhost:1338/v1
[
  'static/chunks/main.js',
  'static/chunks/webpack.js',
  'static/chunks/pages/_app.js'
] [
  'static/chunks/main.js',
  'static/chunks/webpack.js',
  'static/chunks/pages/_error.js'
] {
  sharedFiles: [
    'static/chunks/main.js',
    'static/chunks/webpack.js',
    'static/chunks/pages/_app.js'
  ],
  pageFiles: [
    'static/chunks/main.js',
    'static/chunks/webpack.js',
    'static/chunks/pages/_error.js'
  ],
  allFiles: [
    Set(4) {
      'static/chunks/main.js',
      'static/chunks/webpack.js',
      'static/chunks/pages/_app.js',
      'static/chunks/pages/_error.js'
    }
  ]
}
TypeError: f.endsWith is not a function
    at eval (webpack-internal:///./node_modules/next/dist/pages/_document.js:308:16)
    at Array.filter (<anonymous>)
    at Head.getCssLinks (webpack-internal:///./node_modules/next/dist/pages/_document.js:307:35)
    at Head.render (webpack-internal:///./node_modules/next/dist/pages/_document.js:620:23)
    at processChild (/Users/brianwyant/dev/Golden-Portal/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/Users/brianwyant/dev/Golden-Portal/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
```

2021-02-11 17:25 UTC, wyantb commented
@timneutkens you were right; we had the following presets, and the `loose` config in the preset-env broke spreading sets. Technically that makes this user error; just one that, if you wanted, nextjs could preemptively help out with by avoiding any spread sets. If I took the time to get an integration test in place (I haven't looked to see if it's possible to modify a babel config for one test), would you still be interested in a PR w/ tests or would you prefer to tell users to only use recommended configurations?

~/dev/Golden-Portal/babel.config.js, lines 2-16:

```
"presets": [
  [
    "@babel/preset-env",
    {
      "loose": true,
      "modules": false,
      "useBuiltIns": "usage",
      "corejs": 3,
      "targets": {
        "browsers": [">0.25%", "ie > 10"],
      },
    },
  ],
  'next/babel',
],
```

2021-02-12 10:20 UTC, timneutkens commented
So do you have a babel require hook registered? If so it sounds like there's a wrong `include` / `exclude` configuration in your app, it should already exclude `node_modules` by default though 🤔 https://babeljs.io/docs/en/babel-register#ignores-node_modules-by-default

2021-06-11 09:53 UTC, ijjk commented
## Failing test suites <!--2970176704-->
Commit: 0402fc459eb12a775372172a351f3a3f4fee83e3

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

</details>

2021-06-11 10:14 UTC, ijjk commented
## Failing test suites <!--2970348527-->
Commit: e26188792629ebabff8c93a67c786d8e1ebfe182

**test/integration/basic/test/index.test.js** 
- Basic Features > should polyfill Node.js modules

<details>
<summary>Expand output</summary>

  ● Basic Features › should polyfill Node.js modules

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      35 |   afterAll(() => killApp(context.server))
      36 |
    > 37 |   it('should polyfill Node.js modules', async () => {
         |   ^
      38 |     const browser = await webdriver(context.appPort, '/node-browser-polyfills')
      39 |
      40 |     console.error({

      at integration/basic/test/index.test.js:37:3
      at Object.<anonymous> (integration/basic/test/index.test.js:18:1)

</details>

2021-12-07 15:54 UTC, closed without merging