I18n context initial props
vercel/next.js pull request #21930
Opened 2021-02-06 17:55 UTC by Gigiz

### Add i18n locale props on getInitialProps context. 

In order to manage custom errors, such as a 410 status code, and to guarantee the internationalization of the contents, it is necessary have access to the i18n properties in `getInitialProps` context.

Discussion: https://github.com/vercel/next.js/discussions/18396

2021-02-06 18:06 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.4s | ⚠️ +111ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.167 | 2.233 | ⚠️ +0.07 |
| / avg req/sec | 1153.92 | 1119.73 | ⚠️ -34.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.432 | 1.504 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1746.41 | 1662.6 | ⚠️ -83.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.2s | 11.8s | -402ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +130 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1.01 MB | ⚠️ +130 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +650 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.3s | -178ms |
| nodeModulesSize | 75.3 MB | 75.3 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.027 | 2.047 | ⚠️ +0.02 |
| / avg req/sec | 1233.22 | 1221.47 | ⚠️ -11.75 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.53 | 1.544 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1633.55 | 1618.69 | ⚠️ -14.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | [...]

2021-02-07 00:05 UTC, BjoernRave commented
@aralroca

2021-02-11 08:45 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.5s | ⚠️ +127ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.008 | 2.057 | ⚠️ +0.05 |
| / avg req/sec | 1244.93 | 1215.58 | ⚠️ -29.35 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.284 | 1.312 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1946.86 | 1905.55 | ⚠️ -41.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.3s | ⚠️ +192ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ⚠️ +130 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1.01 MB | ⚠️ +130 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +130 B |
| Overall change | 5.19 MB | 5.19 MB | ⚠️ +650 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.7s | 12.9s | ⚠️ +160ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +432 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.006 | 2.081 | ⚠️ +0.08 |
| / avg req/sec | 1246.03 | 1201.36 | ⚠️ -44.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.292 | 1.246 | -0.05 |
| /error-in-render avg req/sec | 1935.09 | 2006.45 | +71.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - [...]

2021-02-11 09:44 UTC, timneutkens requested changes
This looks incorrect, I doubt it works for client-side navigation 🤔

2021-02-11 10:41 UTC, Gigiz commented
It works like a charm. Locale props are correctly valued for `initialProps` context.

2021-02-12 10:48 UTC, timneutkens requested changes
As said it's very unlikely this works correctly currently given you did not change cases like https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/router/router.ts#L1230-L1234 and https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/router/router.ts#L1310-L1317 

There are no tests for client-side navigation included in the PR, can you add them.

2021-02-12 16:20 UTC, Gigiz commented
Sorry my bad.
I added props on the client side routing method

2021-02-12 16:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 9.2s | 9.2s | ⚠️ +2ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.755 | 1.781 | ⚠️ +0.03 |
| / avg req/sec | 1424.18 | 1403.72 | ⚠️ -20.46 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.105 | 1.121 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2263.24 | 2229.3 | ⚠️ -33.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.2 kB | ⚠️ +32 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 615 B | ⚠️ +1 B |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..fb73c6f26.js</strong></summary>

```diff
@@ -2743,7 +2743,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 11s | 10.4s | -556ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..13c0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details [...]

2021-02-12 16:31 UTC, ijjk commented
## Failing test suites <!--2028232894-->
Commit: 92d61df33f7335802eb0d21d0b36c47b0a0f0eb5

**test/integration/build-output/test/index.test.js** 
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 66.6
    Received:    66.7

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(66.6)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-02-12 19:58 UTC, ijjk commented
## Failing test suites <!--2029579817-->
Commit: 7fb307a069e872aaec49d0901e5503388bf5c8cd

**test/integration/build-output/test/index.test.js** 
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 66.6
    Received:    66.7

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(66.6)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-02-12 19:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.3s | -140ms |
| nodeModulesSize | 69.7 MB | 69.8 MB | ⚠️ +90.5 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.357 | 2.346 | -0.01 |
| / avg req/sec | 1060.69 | 1065.48 | +4.79 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.885 | 1.66 | -0.23 |
| /error-in-render avg req/sec | 1326.08 | 1505.89 | +179.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.2 kB | ⚠️ +32 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 615 B | ⚠️ +1 B |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..fb73c6f26.js</strong></summary>

```diff
@@ -2743,7 +2743,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.5s | -8ms |
| nodeModulesSize | 69.7 MB | 69.8 MB | ⚠️ +90.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..13c0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summa [...]

2021-02-16 13:33 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.4s | -158ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.901 | 1.926 | ⚠️ +0.02 |
| / avg req/sec | 1314.79 | 1297.94 | ⚠️ -16.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.266 | 1.238 | -0.03 |
| /error-in-render avg req/sec | 1975.1 | 2018.64 | +43.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.2 kB | ⚠️ +32 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 615 B | ⚠️ +1 B |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..fb73c6f26.js</strong></summary>

```diff
@@ -2743,7 +2743,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.3s | -229ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..13c0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
 [...]

2021-02-16 13:35 UTC, ijjk commented
## Failing test suites <!--2051179683-->
Commit: 3ded2dd65b924d290e6a635a17e7c6b05904195b

**test/integration/build-output/test/index.test.js** 
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 66.6
    Received:    66.7

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(66.6)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-02-17 22:12 UTC, ijjk commented
## Failing test suites <!--2063571262-->
Commit: dc9adf88ababc31659f1e5a368bbe6ae12d00ea8

**test/integration/build-output/test/index.test.js** 
- Build Output > Crypto Application > should not include crypto

<details>
<summary>Expand output</summary>

  ● Build Output › Crypto Application › should not include crypto

    expect(received).toBeLessThanOrEqual(expected)

    Expected: <= 66.6
    Received:    66.7

      169 |       expect(indexSize.endsWith('kB')).toBe(true)
      170 | 
    > 171 |       expect(parseFloat(indexFirstLoad)).toBeLessThanOrEqual(66.6)
          |                                          ^
      172 |       expect(parseFloat(indexFirstLoad)).toBeGreaterThanOrEqual(60)
      173 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      174 |     })

      at Object.<anonymous> (integration/build-output/test/index.test.js:171:42)

</details>

2021-02-17 22:12 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.1s | -728ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.33 | 2.243 | -0.09 |
| / avg req/sec | 1072.86 | 1114.8 | +41.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.633 | 1.49 | -0.14 |
| /error-in-render avg req/sec | 1530.99 | 1678.28 | +147.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | 13.2 kB | ⚠️ +32 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 614 B | 615 B | ⚠️ +1 B |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..fb73c6f26.js</strong></summary>

```diff
@@ -2743,7 +2743,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7cb49231e31fb73c6f26.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.57fe24c22dc6a0808de5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 14.7s | 14.2s | -505ms |
| nodeModulesSize | 69.8 MB | 69.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..5cb0.js gzip | 13.1 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..13c0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.5 kB | 59.5 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summar [...]

2021-02-18 18:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 11s | 11.2s | ⚠️ +188ms |
| nodeModulesSize | 37.6 MB | 42.5 MB | ⚠️ +4.91 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.006 | 2.779 | ⚠️ +0.77 |
| / avg req/sec | 1246.01 | 899.54 | ⚠️ -346.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.265 | 1.246 | -0.02 |
| /error-in-render avg req/sec | 1976.14 | 2006.64 | +30.5 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ⚠️ +26 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 615 B | 614 B | -1 B |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..7143b2168.js</strong></summary>

```diff
@@ -2748,7 +2748,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -155ms |
| nodeModulesSize | 37.6 MB | 42.5 MB | ⚠️ +4.91 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..43e0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.6 kB | 59.6 kB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
 [...]

2021-02-18 18:57 UTC, ijjk commented
## Failing test suites <!--2071371342-->
Commit: 07bdc2ccfa3befe98c318dea2fdc24f025e50b3f

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 63.9
    Received: 64

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   0.10000000000000142

       96 | 
       97 |       // should be no bigger than 63.9 kb
    >  98 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(63.9, 1)
          |                                          ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.7).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:42)

</details>

2021-02-22 08:41 UTC, ijjk commented
## Failing test suites <!--2092974980-->
Commit: 049260b3e32c5c6864320c941e692c75ca148909

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 63.9
    Received: 64

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   0.10000000000000142

       96 | 
       97 |       // should be no bigger than 63.9 kb
    >  98 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(63.9, 1)
          |                                          ^
       99 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      100 | 
      101 |       expect(parseFloat(err404Size) - 3.7).toBeLessThanOrEqual(0)

      at Object.<anonymous> (integration/build-output/test/index.test.js:98:42)

</details>

2021-02-22 08:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -28ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.225 | 2.246 | ⚠️ +0.02 |
| / avg req/sec | 1123.66 | 1113.29 | ⚠️ -10.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.568 | 1.516 | -0.05 |
| /error-in-render avg req/sec | 1594.34 | 1649.37 | +55.03 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ⚠️ +26 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 615 B | 614 B | -1 B |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 608 B | 609 B | ⚠️ +1 B |
| Overall change | 1.84 kB | 1.84 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..7143b2168.js</strong></summary>

```diff
@@ -2748,7 +2748,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this3.locale,
+                                      locales: _this3.locales,
+                                      defaultLocale: _this3.defaultLocale,
+                                      domainLocales: _this3.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.7a8444d5b037143b2168.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.69a37c199cc9f2448c0e.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.1s | -221ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..43e0.js gzip | N/A | 13.2 kB | N/A |
| Overall change | 59.6 kB | 59.6 kB | ⚠️ +26 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<s [...]

2021-02-25 07:41 UTC, Gigiz commented
Hi @timneutkens,
I don't know why this test fails

```
test/integration/build-output/test/index.test.js
Build Output > Basic Application Output > should not deviate from snapshot

Expected: 63.9
Received: 64

// should be no bigger than 63.9 kb
>  98 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(63.9, 1)
```

When I running local this test is green but another one fails :\ 
I'm not sure what to do as there are differences between local environment and pipeline

2021-02-25 09:37 UTC, timneutkens commented
Most likely because you increased the bundle size of Next.js while adding this feature. You'll have to ensure it does not increase bundle size.

2021-03-04 14:33 UTC, aralroca commented
Waiting a lot for this to be merged

2021-03-04 20:15 UTC, ijjk commented
## Failing test suites <!--2181400464-->
Commit: 29523cfbc6e95f0e74a7d4a107f55d4055275df8

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 63.8
    Received: 63.9

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   0.10000000000000142

      105 |       expect(err404FirstLoad.endsWith('kB')).toBe(true)
      106 | 
    > 107 |       expect(parseFloat(sharedByAll)).toBeCloseTo(63.8, 1)
          |                                       ^
      108 |       expect(sharedByAll.endsWith('kB')).toBe(true)
      109 | 
      110 |       if (_appSize.endsWith('kB')) {

      at Object.<anonymous> (integration/build-output/test/index.test.js:107:39)

</details>

2021-03-04 20:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 8.2s | 7.9s | -264ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.337 | 1.329 | -0.01 |
| / avg req/sec | 1869.81 | 1880.6 | +10.79 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 0.911 | 0.888 | -0.02 |
| /error-in-render avg req/sec | 2744.15 | 2816.22 | +72.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ⚠️ +24 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.8 kB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 620 B | 619 B | -1 B |
| withRouter.html gzip | 609 B | 607 B | -2 B |
| Overall change | 1.84 kB | 1.84 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..5ec6837e3.js</strong></summary>

```diff
@@ -2801,7 +2801,11 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this2.locale,
+                                      locales: _this2.locales,
+                                      defaultLocale: _this2.defaultLocale,
+                                      domainLocales: _this2.domainLocales
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.ef23ea6eba23c07b811b.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 9.5s | 9.6s | ⚠️ +118ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +832 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..0b58.js gzip | N/A | 13.4 kB | N/A |
| Overall change | 59.7 kB | 59.8 kB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><str [...]

2021-03-08 10:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.6s | ⚠️ +225ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.391 | 2.327 | -0.06 |
| / avg req/sec | 1045.75 | 1074.18 | +28.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.609 | 1.676 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1553.89 | 1491.44 | ⚠️ -62.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ⚠️ +16 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.8 kB | 59.8 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| index.html gzip | 615 B | 614 B | -1 B |
| link.html gzip | 623 B | 620 B | -3 B |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.85 kB | 1.84 kB | -5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..29e58243f.js</strong></summary>

```diff
@@ -2807,7 +2807,10 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
                                     {
                                       pathname: pathname,
                                       query: query,
-                                      asPath: as
+                                      asPath: as,
+                                      locale: _this2.locale,
+                                      locales: _this2.locales,
+                                      defaultLocale: _this2.defaultLocale
                                     }
                                   );
                             });
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.3f42defbaad29e58243f.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.0860fa415f8cb57c59dd.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.7s | -11ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +598 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | N/A | N/A |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| 677f882d2ed8..7094.js gzip | N/A | 13.4 kB | N/A |
| Overall change | 59.8 kB | 59.8 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Gigiz/next.js i18n-context-initial-props | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>
 [...]

2021-04-07 16:21 UTC, aralroca commented
How is it going? I can't wait to have this merged 😊

2021-04-15 21:40 UTC, ValentinH commented
> Most likely because you increased the bundle size of Next.js while adding this feature. You'll have to ensure it does not increase bundle size.

@timneutkens I don't see how not to add code to support this feature. Thus, the size of Next has to increase. How do you usually add features without increasing the size?

2021-04-18 03:38 UTC, satazor commented
The increase is necessary and minimal (400 bytes). I'm hoping this gets merged soon as I need this too.

2021-05-06 16:39 UTC, Iliyass commented
@aralroca  thanks for your work,
@timneutkens please, can you make this possible, we need this PR to be merged!

2021-05-07 08:56 UTC, timneutkens approved these changes, later dismissed
Looks fine to land now.

2021-05-07 08:57 UTC, timneutkens commented
> > Most likely because you increased the bundle size of Next.js while adding this feature. You'll have to ensure it does not increase bundle size.
> 
> @timneutkens I don't see how not to add code to support this feature. Thus, the bundle size of Next has to increase. How do you usually add features without increasing the bundle size?

By optimizing other parts of the client bundles.

2021-05-07 09:45 UTC, ijjk commented
## Failing test suites <!--2674884639-->
Commit: ebd6551b18f3ad30d790de2c51abebe40d746029

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 63.5
    Received: 63.6

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   0.10000000000000142

      100 |
      101 |       // should be no bigger than 64.8 kb
    > 102 |       expect(parseFloat(indexFirstLoad)).toBeCloseTo(63.5, 1)
          |                                          ^
      103 |       expect(indexFirstLoad.endsWith('kB')).toBe(true)
      104 |
      105 |       expect(parseFloat(err404Size)).toBeCloseTo(3.04, 1)

      at Object.<anonymous> (integration/build-output/test/index.test.js:102:42)

</details>

2021-05-07 17:38 UTC, timneutkens commented
Looks like this is failing against the latest canary, can you update the test @Gigiz. Thanks!

2021-05-10 12:11 UTC, merged

2021-05-12 09:33 UTC, hedwiggggg commented
Seem's, the types are still missing:
https://github.com/vercel/next.js/blob/4443d6f3d36b107e833376c2720c1e206eee720d/packages/next/next-server/lib/utils.ts#L113

2021-05-22 15:53 UTC, rokinsky commented
> Seem's, the types are still missing:
> https://github.com/vercel/next.js/blob/4443d6f3d36b107e833376c2720c1e206eee720d/packages/next/next-server/lib/utils.ts#L113-L142

I've noticed this as well. I hope #25363 will be merged to canary soon.