Allows . (dot) to be a valid value for basePath
vercel/next.js pull request #22023
Opened 2021-02-10 16:15 UTC by andrius-k

Over at CERN, we're experiencing an issue when we need to deploy multiple versions of exactly the same, statically exported websites, on one domain. Think like this:

https://department.cern.ch/group/service1/

https://department.cern.ch/group/service2/

https://department.cern.ch/group/service3/

... and we have about 10 different services like that (all on the same domain).

Exporting and deploying 10 versions where the only difference is the value of `basePath` seems very inefficient and cumbersome. Therefore, we suggest to lift the restriction that prohibits us from using `.` as a `basePath`. This ensures that all paths are relative and static files come from the same service (`/group/serviceX/`) from which `index.html` was requested.

I made a small sample app (that's a slight modification of one of the out-of-the-box samples) to showcase that this indeed works:
https://github.com/andrius-k/relative-imports-nextjs

This contribution was made following the procedure outlined here: https://github.com/andrius-k/next.js/blob/canary/contributing.md

2021-02-10 16:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| buildDuration | 10.1s | 10.2s | ⚠️ +96ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +119 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.964 | 1.955 | -0.01 |
| / avg req/sec | 1273.13 | 1278.98 | +5.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.236 | 1.244 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2021.85 | 2009.47 | ⚠️ -12.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.9s | -211ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +119 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| 677f882d2ed8..49c4.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.5 kB | 59.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| hooks-c71ae4..70cd.js gzip | 887 B | 887 B | ✓ |
| index-bbee2f..528b.js gzip | 227 B | 227 B | ✓ |
| link-7faf09b..eba4.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..bf84.js gzip | 303 B | 303 B | ✓ |
| withRouter-a..5826.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.09 kB | 8.09 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _buildManifest.js gzip | 321 B | 321 B | ✓ |
| Overall change | 321 B | 321 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _error.js | 1 MB | 1 MB | ✓ |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1 MB | 1 MB | ✓ |
| link.js | 1.06 MB | 1.06 MB | ✓ |
| routerDirect.js | 1.06 MB | 1.06 MB | ✓ |
| withRouter.js | 1.06 MB | 1.06 MB | ✓ |
| Overall change | 5.19 MB | 5.19 MB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.2s | -82ms |
| nodeModulesSize | 75.4 MB | 75.4 MB | ⚠️ +119 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.054 | 2.01 | -0.04 |
| / avg req/sec | 1217 | 1244.09 | +27.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.242 | 1.221 | -0.02 |
| /error-in-render avg req/sec | 2012.39 | 2048.01 | +35.62 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| 597-6c246419..806f.js gzip | 13 kB | 13 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.58 kB | 6.58 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 59.9 kB | 59.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _app-6e0a903..b885.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-7a100..a392.js gzip | 3.38 kB | 3.38 kB | ✓ |
| hooks-f7e199..11b9.js gzip | 904 B | 904 B | ✓ |
| index-3dc22c..ffbb.js gzip | 232 B | 232 B | ✓ |
| link-c010d28..b60a.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..323a.js gzip | 308 B | 308 B | ✓ |
| withRouter-a..2ef8.js gzip | 304 B | 304 B | ✓ |
| Overall change | 8.02 kB | 8.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| _buildManifest.js gzip | 299 B | 299 B | ✓ |
| Overall change | 299 B | 299 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | andrius-k/next.js allow-dot-as-basePath | Change |
| - | - | - | - |
| index.html gzip | 584 B | 584 B | ✓ |
| link.html gzip | 591 B | 591 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Ov [...]

2021-02-11 14:07 UTC, andrius-k commented
Hi guys, any comment about this? I'd love to hear your opinion about the issue :)

2021-02-12 10:49 UTC, timneutkens requested changes
This PR is missing integration tests and it doesn't seem like this is enough to make the behavior you're mentioning work. Happy to merge this if tests are added and it has no impact on bundle size.

2022-08-08 01:07 UTC, ijjk reviewed
Hi, as mentioned above it seems there may be more changes needed to make this work properly and integration tests weren't added. I'm gonna close this for now since this PR appears to have gone stale.

2022-08-08 01:07 UTC, closed without merging