feat(next-server): detect current domain locale first
vercel/next.js pull request #22337
Opened 2021-02-19 13:42 UTC by blurrah

This will check whether the current domain is available in i18n domains before checking all domains for current locale.

This fixes an issue where you can have multiple domains assigned for one locale and the function will return a different domain than the one you're currently on.

E.g. you can have your domains config set up as follows:
```javascript
domains: [
      {
        domain: 'examplebehindcloudfront.com',
        defaultLocale: 'en-US',
      },
      {
        domain: 'examplebehindloadbalancer.com',
        defaultLocale: 'en-US',
      },
    ],
```
Where you will then visit `examplebehindloadbalancer.com` and all your links will send you to `examplebehindcloudfront.com` because it's the first result in the list.

2021-02-19 13:53 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 10.6s | 10.1s | -580ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.16 | 2.047 | -0.11 |
| / avg req/sec | 1157.3 | 1221.33 | +64.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.505 | 1.419 | -0.09 |
| /error-in-render avg req/sec | 1660.7 | 1762.36 | +101.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| index.html gzip | 615 B | 615 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 608 B | 608 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 13s | 12.9s | -174ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 677f882d2ed8..854c.js gzip | 13.2 kB | 13.2 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.6 kB | 59.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _error.js | 1.01 MB | 1.01 MB | ⚠️ +167 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| amp.amp.html | 10.4 kB | 10.4 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.01 MB | 1.01 MB | ⚠️ +167 B |
| link.js | 1.06 MB | 1.06 MB | ⚠️ +167 B |
| routerDirect.js | 1.06 MB | 1.06 MB | ⚠️ +167 B |
| withRouter.js | 1.06 MB | 1.06 MB | ⚠️ +167 B |
| Overall change | 5.2 MB | 5.2 MB | ⚠️ +835 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 13.2s | 12.7s | -508ms |
| nodeModulesSize | 42.6 MB | 42.6 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.111 | 2.065 | -0.05 |
| / avg req/sec | 1184.16 | 1210.83 | +26.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.434 | 1.465 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1742.94 | 1706.2 | ⚠️ -36.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 597-dc8125e2..ef24.js gzip | 13.1 kB | 13.1 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 6.59 kB | 6.59 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60 kB | 60 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-aedc815..1421.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-71ec2..1a96.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-33a09cb0..6745.js gzip | 536 B | 536 B | ✓ |
| hooks-4e968a..f870.js gzip | 902 B | 902 B | ✓ |
| index-5c6845..f75c.js gzip | 230 B | 230 B | ✓ |
| link-99f0c6c..b84a.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..bb56.js gzip | 306 B | 306 B | ✓ |
| withRouter-7..2133.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.57 kB | 8.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-loc [...]

2021-03-16 11:02 UTC, ijjk commented
## Failing test suites <!--2268859858-->
Commit: 4df38ec53778508b7f1dbbe65a8d1258fe6f473d

**test/integration/build-output/test/index.test.js** 
- Build Output > Basic Application Output > should not deviate from snapshot

<details>
<summary>Expand output</summary>

  ● Build Output › Basic Application Output › should not deviate from snapshot

    expect(received).toBeCloseTo(expected, precision)

    Expected: 64.3
    Received: 64.4

    Expected precision:    1
    Expected difference: < 0.05
    Received difference:   0.10000000000000853

      105 |       expect(err404FirstLoad.endsWith('kB')).toBe(true)
      106 | 
    > 107 |       expect(parseFloat(sharedByAll)).toBeCloseTo(64.3, 1)
          |                                       ^
      108 |       expect(sharedByAll.endsWith('kB')).toBe(true)
      109 | 
      110 |       if (_appSize.endsWith('kB')) {

      at Object.<anonymous> (integration/build-output/test/index.test.js:107:39)

</details>

2021-03-16 11:03 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 12.2s | 12.2s | ⚠️ +38ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.071 | 2.098 | ⚠️ +0.03 |
| / avg req/sec | 1206.91 | 1191.61 | ⚠️ -15.3 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.306 | 1.279 | -0.03 |
| /error-in-render avg req/sec | 1914.15 | 1954.25 | +40.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| index.html gzip | 614 B | 614 B | ✓ |
| link.html gzip | 621 B | 621 B | ✓ |
| withRouter.html gzip | 609 B | 609 B | ✓ |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -66ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 677f882d2ed8..a2e7.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.14 kB | 7.14 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-fde3324..9dd1.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-af59f..582f.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-9716187d..0aa8.js gzip | 536 B | 536 B | ✓ |
| hooks-107e90..74c7.js gzip | 888 B | 888 B | ✓ |
| index-ac435c..ecf2.js gzip | 227 B | 227 B | ✓ |
| link-e6cee42..49eb.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..dc9d.js gzip | 303 B | 303 B | ✓ |
| withRouter-6..0e02.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.64 kB | 8.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _buildManifest.js gzip | 346 B | 346 B | ✓ |
| Overall change | 346 B | 346 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _error.js | 1.02 MB | 1.02 MB | ⚠️ +167 B |
| 404.html | 2.67 kB | 2.67 kB | ✓ |
| 500.html | 2.65 kB | 2.65 kB | ✓ |
| amp.amp.html | 10.6 kB | 10.6 kB | ✓ |
| amp.html | 1.86 kB | 1.86 kB | ✓ |
| hooks.html | 1.92 kB | 1.92 kB | ✓ |
| index.js | 1.02 MB | 1.02 MB | ⚠️ +167 B |
| link.js | 1.08 MB | 1.08 MB | ⚠️ +167 B |
| routerDirect.js | 1.07 MB | 1.07 MB | ⚠️ +167 B |
| withRouter.js | 1.07 MB | 1.07 MB | ⚠️ +167 B |
| Overall change | 5.27 MB | 5.27 MB | ⚠️ +835 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 5 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.1s | -20ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +238 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.037 | 2.044 | ⚠️ +0.01 |
| / avg req/sec | 1227.39 | 1222.92 | ⚠️ -4.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.293 | 1.346 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1933.85 | 1856.97 | ⚠️ -76.88 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| 597-2bc2376a..203d.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 7.08 kB | 7.08 kB | ✓ |
| webpack-HASH.js gzip | 954 B | 954 B | ✓ |
| Overall change | 60.7 kB | 60.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | blurrah/next.js detect-current-domain-locale | Change |
| - | - | - | - |
| _app-0c62a59..94b7.js gzip | 1.26 kB | 1.26 kB | ✓ |
| _error-97d24..ed28.js gzip | 3.38 kB | 3.38 kB | ✓ |
| amp-2926e4c2..9ccc.js gzip | 536 B | 536 B | ✓ |
| hooks-1ed65b..8908.js gzip | 902 B | 902 B | ✓ |
| index-6259b6..77d8.js gzip | 230 B | 230 B | ✓ |
| link-2a29128..cc6e.js gzip | 1.63 kB | 1.63 kB | ✓ |
| routerDirect..862a.js gzip | 306 B | 306 B | ✓ |
| withRouter-4..76fd.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.54 kB | 8.54 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/ne [...]

2021-03-31 13:43 UTC, blurrah commented
Sorry for bumping and pinging you guys, but could this be looked at? This blocks us from updating past 10.0.2.
@divmain @timneutkens @ijjk @lfades

2021-04-01 08:51 UTC, Poitrin commented
> This blocks us from updating past 10.0.2.

Yeah, we have the same problem (we are at 10.0.4) and can't update to ≥ 10.0.5

What you can do in the meantime is to merge in the latest changes from the base branch and update the failing integration test `test/integration/build-output/test/index.test.js`.
Apparently, it checks the current build size, so as branch `canary` currently expects `65`, and your changes lead to an increase of `0.1`, the test needs to be updated to `65.1` (or it stays at `65` if you merge in the base branch).

2021-04-01 11:04 UTC, blurrah commented
While this fix is a step in the right direction, it does not completely fix the issue. The Link component does not send in a domain to the detectDomainLocale function so this check will inevitably fail again.
So to fix this we'd either need to always send a domain name to the link component or by adding in a flag to disable this functionality.

@Poitrin I used `patch-package` to create a mini patch that disables the domain switching functionality in the Link component if you want to upgrade in the meantime: [https://gist.github.com/blurrah/cd82c00ad2a6dcf55b40ae98092e6b7a](https://gist.github.com/blurrah/cd82c00ad2a6dcf55b40ae98092e6b7a).
You can add this as a patch file, does nothing more than just removing the domainLocale output from the Link component, falling back to the original URLs

2021-04-01 11:32 UTC, Poitrin commented
> @Poitrin I used `patch-package` to create a mini patch…

Haven't heard of `patch-package` before, thanks for the hint!
We will keep using v10.0.4 in the meantime, and maybe implement our own locale detection mechanism as soon as _Must-have_ Next.js features come out :)

2021-07-23 12:20 UTC, VWSCoronaDashboard10 commented
We're experiencing the same issue w/multiple domains for a single locale and this PR does seem to fix the issue on our local environments @timneutkens

2021-07-23 20:30 UTC, ijjk requested changes
Hi, having multiple domain items with the same `defaultLocale` like this isn't currently supported and it looks like we are missing a check explaining this which I added [here](https://github.com/vercel/next.js/pull/27451) we already have an existing check [here](https://github.com/vercel/next.js/blob/9cbc4aacd50d0e79be7b8178eec9219457514da9/packages/next/server/config.ts#L353) to prevent accidentally defining locales for multiple domains. 

This isn't supported as we currently don't know which domain to use when redirecting and creating links. I'm gonna close this as it seems like this should be a feature request/needs discussion instead of a bug fix.

2021-07-23 20:30 UTC, closed without merging