Fix idleTimeout error being thrown in route loader
vercel/next.js pull request #22775
Opened 2021-03-04 15:31 UTC by shuding

In the current implementation, `idleTimeout` will always be thrown even if it didn't time out and `Promise.race` was resolved. This causes the error `Error: Route did not complete loading` on every route transition and Chrome Devtools will pause code execution if you have "Pause on exceptions" enabled.

This PR adds `resolvePromiseWithTimeout` which does the same thing as `Promise.race` and `idleTimeout`, but it cancels the rejection when it resolves successfully, in which case the error won't be thrown.

Fixes #21543.

2021-03-04 15:44 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.5s | ⚠️ +309ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +663 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.417 | 2.433 | ⚠️ +0.02 |
| / avg req/sec | 1034.51 | 1027.37 | ⚠️ -7.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.634 | 1.584 | -0.05 |
| /error-in-render avg req/sec | 1529.92 | 1577.79 | +47.87 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ⚠️ +7 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| index.html gzip | 613 B | 614 B | ⚠️ +1 B |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..5ec6837e3.js</strong></summary>

```diff
@@ -589,13 +589,21 @@
           script.src = src;
           document.body.appendChild(script);
         });
-      }
+      } // Resolve a promise that times out after given amount of milliseconds.
 
-      function idleTimeout(ms, err) {
-        return new Promise(function(_resolve, reject) {
-          return (0, _requestIdleCallback.requestIdleCallback)(function() {
+      function resolvePromiseWithTimeout(p, ms, err) {
+        return new Promise(function(resolve, reject) {
+          var cancelled = false;
+          p.then(function(r) {
+            // Resolved, cancel the timeout
+            cancelled = true;
+            resolve(r);
+          })["catch"](reject);
+          (0, _requestIdleCallback.requestIdleCallback)(function() {
             return setTimeout(function() {
-              return reject(err);
+              if (!cancelled) {
+                reject(err);
+              }
             }, ms);
           });
         });
@@ -620,13 +628,11 @@
             cb && cb();
           };
         });
-        return Promise.race([
+        return resolvePromiseWithTimeout(
           onBuildManifest,
-          idleTimeout(
-            MS_MAX_IDLE_DELAY,
-            markAssetError(new Error("Failed to load client build manifest"))
-          )
-        ]);
+          MS_MAX_IDLE_DELAY,
+          markAssetError(new Error("Failed to load client build manifest"))
+        );
       }
 
       function getFilesForRoute(assetPrefix, route) {
@@ -778,19 +784,17 @@
                             );
                             styles = _yield$Promise$all2[1];
                             _context.next = 13;
-                            return Promise.race([
+                            return resolvePromiseWithTimeout(
                               _this.whenEntrypoint(route),
-                              idleTimeout(
-                                MS_MAX_IDLE_DELAY,
-                                markAssetError(
-                                  new Error(
-                                    "Route did not complete loading: ".concat(
-                                      route
-                                    )
+                              MS_MAX_IDLE_DELAY,
+                              markAssetError(
+                                new Error(
+                                  "Route did not complete loading: ".concat(
+                                    route
                                   )
                                 )
                               )
-                            ]);
+                            );
 
                           case 13:
                             entrypoint = _context.sent;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (In [...]

2021-03-04 16:13 UTC, ijjk approved these changes

2021-03-04 16:21 UTC, ijjk requested changes
Waiting to land until current stable is up, but changes look good to me 👍

2021-03-04 16:23 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| buildDuration | 9.7s | 9.9s | ⚠️ +189ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +663 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.708 | 1.73 | ⚠️ +0.02 |
| / avg req/sec | 1463.97 | 1445.47 | ⚠️ -18.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.073 | 1.066 | -0.01 |
| /error-in-render avg req/sec | 2330.61 | 2344.29 | +13.68 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ⚠️ +7 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| index.html gzip | 613 B | 614 B | ⚠️ +1 B |
| link.html gzip | 620 B | 620 B | ✓ |
| withRouter.html gzip | 609 B | 608 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..5ec6837e3.js</strong></summary>

```diff
@@ -589,13 +589,21 @@
           script.src = src;
           document.body.appendChild(script);
         });
-      }
+      } // Resolve a promise that times out after given amount of milliseconds.
 
-      function idleTimeout(ms, err) {
-        return new Promise(function(_resolve, reject) {
-          return (0, _requestIdleCallback.requestIdleCallback)(function() {
+      function resolvePromiseWithTimeout(p, ms, err) {
+        return new Promise(function(resolve, reject) {
+          var cancelled = false;
+          p.then(function(r) {
+            // Resolved, cancel the timeout
+            cancelled = true;
+            resolve(r);
+          })["catch"](reject);
+          (0, _requestIdleCallback.requestIdleCallback)(function() {
             return setTimeout(function() {
-              return reject(err);
+              if (!cancelled) {
+                reject(err);
+              }
             }, ms);
           });
         });
@@ -620,13 +628,11 @@
             cb && cb();
           };
         });
-        return Promise.race([
+        return resolvePromiseWithTimeout(
           onBuildManifest,
-          idleTimeout(
-            MS_MAX_IDLE_DELAY,
-            markAssetError(new Error("Failed to load client build manifest"))
-          )
-        ]);
+          MS_MAX_IDLE_DELAY,
+          markAssetError(new Error("Failed to load client build manifest"))
+        );
       }
 
       function getFilesForRoute(assetPrefix, route) {
@@ -778,19 +784,17 @@
                             );
                             styles = _yield$Promise$all2[1];
                             _context.next = 13;
-                            return Promise.race([
+                            return resolvePromiseWithTimeout(
                               _this.whenEntrypoint(route),
-                              idleTimeout(
-                                MS_MAX_IDLE_DELAY,
-                                markAssetError(
-                                  new Error(
-                                    "Route did not complete loading: ".concat(
-                                      route
-                                    )
+                              MS_MAX_IDLE_DELAY,
+                              markAssetError(
+                                new Error(
+                                  "Route did not complete loading: ".concat(
+                                    route
                                   )
                                 )
                               )
-                            ]);
+                            );
 
                           case 13:
                             entrypoint = _context.sent;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Incr [...]

2021-03-05 16:09 UTC, ijjk approved these changes

2021-03-05 16:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.7s | -90ms |
| nodeModulesSize | 42.8 MB | 42.8 MB | ⚠️ +663 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.47 | 2.481 | ⚠️ +0.01 |
| / avg req/sec | 1012.05 | 1007.73 | ⚠️ -4.32 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.756 | 1.695 | -0.06 |
| /error-in-render avg req/sec | 1423.88 | 1474.95 | +51.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| 677f882d2ed8..e7a0.js gzip | 13.4 kB | 13.4 kB | ⚠️ +7 B |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 59.7 kB | 59.7 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _app-2a09aa2..4a98.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-8b758..aef6.js gzip | 3.46 kB | 3.46 kB | ✓ |
| amp-e3e9bc99..932c.js gzip | 536 B | 536 B | ✓ |
| hooks-5023ef..3670.js gzip | 888 B | 888 B | ✓ |
| index-3a2b03..c677.js gzip | 227 B | 227 B | ✓ |
| link-177412b..043e.js gzip | 1.67 kB | 1.67 kB | ✓ |
| routerDirect..1a66.js gzip | 303 B | 303 B | ✓ |
| withRouter-9..1b7d.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.66 kB | 8.66 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| _buildManifest.js gzip | 347 B | 347 B | ✓ |
| Overall change | 347 B | 347 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | shuding/next.js fix-route-loading-timeout-error-thrown | Change |
| - | - | - | - |
| index.html gzip | 613 B | 613 B | ✓ |
| link.html gzip | 621 B | 620 B | -1 B |
| withRouter.html gzip | 608 B | 607 B | -1 B |
| Overall change | 1.84 kB | 1.84 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>677f882d2ed8..5ec6837e3.js</strong></summary>

```diff
@@ -589,13 +589,21 @@
           script.src = src;
           document.body.appendChild(script);
         });
-      }
+      } // Resolve a promise that times out after given amount of milliseconds.
 
-      function idleTimeout(ms, err) {
-        return new Promise(function(_resolve, reject) {
-          return (0, _requestIdleCallback.requestIdleCallback)(function() {
+      function resolvePromiseWithTimeout(p, ms, err) {
+        return new Promise(function(resolve, reject) {
+          var cancelled = false;
+          p.then(function(r) {
+            // Resolved, cancel the timeout
+            cancelled = true;
+            resolve(r);
+          })["catch"](reject);
+          (0, _requestIdleCallback.requestIdleCallback)(function() {
             return setTimeout(function() {
-              return reject(err);
+              if (!cancelled) {
+                reject(err);
+              }
             }, ms);
           });
         });
@@ -620,13 +628,11 @@
             cb && cb();
           };
         });
-        return Promise.race([
+        return resolvePromiseWithTimeout(
           onBuildManifest,
-          idleTimeout(
-            MS_MAX_IDLE_DELAY,
-            markAssetError(new Error("Failed to load client build manifest"))
-          )
-        ]);
+          MS_MAX_IDLE_DELAY,
+          markAssetError(new Error("Failed to load client build manifest"))
+        );
       }
 
       function getFilesForRoute(assetPrefix, route) {
@@ -778,19 +784,17 @@
                             );
                             styles = _yield$Promise$all2[1];
                             _context.next = 13;
-                            return Promise.race([
+                            return resolvePromiseWithTimeout(
                               _this.whenEntrypoint(route),
-                              idleTimeout(
-                                MS_MAX_IDLE_DELAY,
-                                markAssetError(
-                                  new Error(
-                                    "Route did not complete loading: ".concat(
-                                      route
-                                    )
+                              MS_MAX_IDLE_DELAY,
+                              markAssetError(
+                                new Error(
+                                  "Route did not complete loading: ".concat(
+                                    route
                                   )
                                 )
                               )
-                            ]);
+                            );
 
                           case 13:
                             entrypoint = _context.sent;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -70,7 +70,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,7 +22,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      href="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       as="script"
     />
     <link
@@ -65,7 +65,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.42120b530b65ec6837e3.js"
+      src="/_next/static/chunks/677f882d2ed86fa3467b8979053c1a4c3f8bc4df.c6f31967688cbdf31d2b.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mod [...]

2021-03-05 16:32 UTC, merged

2021-03-25 04:31 UTC, parishshani reviewed
Run script