chore: adds compiled css example
vercel/next.js pull request #22786
Opened 2021-03-05 01:00 UTC by madou

2021-03-05 02:10 UTC, HESHAMALHASHMI approved these changes

2021-03-05 02:12 UTC, HESHAMALHASHMI approved these changes
heshamalhashmi #

2021-03-05 02:12 UTC, HESHAMALHASHMI approved these changes
heshamalhashmi #

2021-03-05 02:12 UTC, HESHAMALHASHMI approved these changes, later dismissed
heshamalhashmi #

2021-03-05 05:20 UTC, nadejdidjdhdhdh approved these changes

2021-03-05 05:40 UTC, marcodejongh approved these changes

2021-03-05 05:40 UTC, marcodejongh submitted a review, later dismissed
Just testing to see if randoms can approve PR's

2021-03-05 07:54 UTC, andreipfeiffer requested changes

2021-03-05 07:54 UTC, andreipfeiffer commented on examples/with-compiled-css/pages/class-names-box.js
> +import { ClassNames } from '@compiled/react'
In Next.js, the files that are placed in the `/pages` folder become routes
A general practice is to put any included components in a separate root folder, like `/components`, so they don't become routes in the app

Only `index.js` should stay in `/pages` folder, as far as I can see, the others are only components

2021-03-05 08:56 UTC, andreipfeiffer requested changes

2021-03-05 08:56 UTC, andreipfeiffer commented on examples/with-compiled-css/.babelrc
> +  "presets": ["@babel/preset-react"],
I get `Error: Cannot find module '@babel/preset-react'`

Based on the official [Next.js Customizing Babel Config](https://nextjs.org/docs/advanced-features/customizing-babel-config) this should be:

```
{
  "presets": ["next/babel"],
  ...
}
```

2021-03-05 11:32 UTC, andreipfeiffer requested changes

2021-03-05 11:32 UTC, andreipfeiffer commented on examples/with-compiled-css/.babelrc
> -  "plugins": ["@babel/plugin-syntax-jsx"]
the additional plugin is required, for me it doesn't work without it, so `.babelrc` should look like:

```
{
  "presets": ["next/babel"],
  "plugins": ["@babel/plugin-syntax-jsx"]
}
```

2021-03-05 12:06 UTC, andreipfeiffer requested changes

2021-03-05 12:06 UTC, andreipfeiffer commented on examples/with-compiled-css/.babelrc
> +}
the additional plugin is required, for me it doesn't work without it, so `.babelrc` should look like:

```
{
  "presets": ["next/babel"],
  "plugins": ["@babel/plugin-syntax-jsx"]
}
```

2021-03-06 08:15 UTC, andreipfeiffer approved these changes

2021-03-06 12:05 UTC, andreipfeiffer commented
@lfades @marcodejongh @timneutkens I have a question and can't seem to find an answer.

When you build this example, you **don't get a separate `chunk` for the library**, instead it's bundled inside each page.
The **same applies for** the examples for [Fela](https://github.com/vercel/next.js/tree/canary/examples/with-fela) and [JSS](https://github.com/vercel/next.js/tree/canary/examples/with-react-jss) and [Goober](https://github.com/vercel/next.js/tree/canary/examples/with-goober).

However, for other **CSS-in-JS** solutions like [Styled Components](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components), [Emotion](https://github.com/vercel/next.js/tree/canary/examples/with-emotion), [Stitches](https://github.com/vercel/next.js/tree/canary/examples/with-stitches) or [TypeStyle](https://github.com/vercel/next.js/tree/canary/examples/with-typestyle) you **get a separate `chunk` of the lib**, that is shared across all pages.

So, the questions are:
- why is this difference? is there a reason for getting handled differently?
- is there a way to control what gets to common chunks, and what not? (I've searched all the official docs, without any luck)

I would really appreciate if you could shed some light.

I'm working on a [thorough analysis of all CSS-in-JS](https://github.com/andreipfeiffer/css-in-js) solutions with Next.js, and can't get my head around this tiny bit.

2021-03-08 21:19 UTC, lfades approved these changes
LGTM. Thank you @madou !

2021-03-08 21:25 UTC, merged