Added proper error for running `next start` on dev build
vercel/next.js pull request #2337
Opened 2017-06-22 02:54 UTC by xuezhma

Fixes #1937 
Tells user to run `next start` when they run `next start` on dev build.

2017-06-22 04:35 UTC, arunoda requested changes

2017-06-22 04:35 UTC, arunoda commented on server/index.js
> +      console.error('No build-stats.json found. Did you forget to run `next build`?')
I'd like to do this in our `bin/*` files.
For an example, do this check here: https://github.com/zeit/next.js/blob/v3-beta/bin/next-start#L55

2017-06-22 05:06 UTC, xuezhma commented on server/index.js
> +      console.error('No build-stats.json found. Did you forget to run `next build`?')
Looks like `next start` is already checking if a build exists, but the code does the checking is after trying to create a server. I put them in the correct order in my last commit.

2017-06-22 05:20 UTC, xuezhma commented
It just occurred to me that checking if a build exists in `/bin/next-start` doesn't cover people with custom servers. Maybe it's better to put the checking in `server/index.js`?

2017-06-22 05:37 UTC, timneutkens commented on server/index.js
> +      console.error('No build-stats.json found. Did you forget to run `next build`?')
👌

2017-06-22 05:37 UTC, timneutkens approved these changes

2017-06-23 05:42 UTC, arunoda commented
@xuezhma that's a good point.
Yep. Then that's a good idea. Move the BUILD_ID check from the `bin` to `server/index.js`

2017-06-23 18:08 UTC, xuezhma commented
@arunoda Done

2017-06-26 18:13 UTC, timneutkens commented
Lets merge this against v3

2017-06-26 20:18 UTC, timneutkens approved these changes

2017-06-26 20:18 UTC, merged

2017-06-26 20:19 UTC, timneutkens commented
🎉