Font
vercel/next.js pull request #24162
Opened 2021-04-16 21:28 UTC by janicklas-ralph

## Bug

- [x] Related issues linked using `fixes #23896`
- [x] Integration tests added

2021-04-16 21:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.3s | -163ms |
| buildDurationCached | 4.6s | 4.5s | -90ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | -372 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.468 | 2.449 | -0.02 |
| / avg req/sec | 1012.87 | 1020.93 | +8.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.309 | 1.304 | 0 |
| /error-in-render avg req/sec | 1909.33 | 1917.35 | +8.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 604 B | 604 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 17.6s | 17.4s | -139ms |
| buildDurationCached | 6.3s | 6.5s | ⚠️ +239ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | -372 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.05 kB | 7.05 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| Overall change | 9.03 kB | 9.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _buildManifest.js gzip | 349 B | 349 B | ✓ |
| Overall change | 349 B | 349 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | -39 B |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.7 kB | 10.7 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | -39 B |
| link.js | 1.45 MB | 1.45 MB | -39 B |
| routerDirect.js | 1.44 MB | 1.44 MB | -39 B |
| withRouter.js | 1.44 MB | 1.44 MB | -39 B |
| Overall change | 7.14 MB | 7.14 MB | -195 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12.3s | ⚠️ +141ms |
| buildDurationCached | 4.8s | 4.7s | -132ms |
| nodeModulesSize | 46.2 MB | 46.2 MB | -372 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.494 | 2.503 | ⚠️ +0.01 |
| / avg req/sec | 1002.24 | 998.93 | ⚠️ -3.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.257 | 1.308 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1988.53 | 1910.79 | ⚠️ -77.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.2 kB | 60.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| hooks-HASH.js gzip | 888 B | 888 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| Overall change | 8.89 kB | 8.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _buildManifest.js gzip | 371 B | 371 B | ✓ |
| Overall change | 371 B | 371 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next [...]

2021-04-17 22:14 UTC, ijjk requested changes
Can we add an additional test case to ensure https://github.com/vercel/next.js/issues/23896 is covered?

2021-04-18 10:22 UTC, timneutkens requested changes
Looks good but this needs an integration test 👍

2021-04-26 18:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 14.7s | 15.5s | ⚠️ +784ms |
| buildDurationCached | 5.1s | 4.6s | -508ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -374 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.623 | 2.683 | ⚠️ +0.06 |
| / avg req/sec | 953.01 | 931.63 | ⚠️ -21.38 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.396 | 1.398 | 0 |
| /error-in-render avg req/sec | 1790.25 | 1788.84 | ⚠️ -1.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 615 B | 615 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 18.2s | 19s | ⚠️ +789ms |
| buildDurationCached | 7.1s | 7.1s | -4ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -374 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | -39 B |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| css.html | 2.13 kB | 2.13 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | -39 B |
| link.js | 1.45 MB | 1.45 MB | -39 B |
| routerDirect.js | 1.44 MB | 1.44 MB | -39 B |
| withRouter.js | 1.44 MB | 1.44 MB | -41 B |
| Overall change | 7.14 MB | 7.14 MB | -197 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.7s | ⚠️ +143ms |
| buildDurationCached | 5.3s | 5.1s | -129ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | -374 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.489 | 2.44 | -0.05 |
| / avg req/sec | 1004.3 | 1024.77 | +20.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.323 | 1.265 | -0.06 |
| /error-in-render avg req/sec | 1889.19 | 1976.77 | +87.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | janicklas-ralph/next.js font | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 303 B | 303 B | ✓ |
| withRouter-HASH.js gzip | 302 B | 302 B | ✓ |
| 21c68fa65a48..217.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.36 kB | 9.36 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summa [...]

2021-04-26 18:27 UTC, timneutkens approved these changes

2021-04-26 18:30 UTC, ijjk approved these changes

2021-04-26 18:30 UTC, merged