fix(react-refresh-utils): Include source maps in the package
vercel/next.js pull request #24373
Opened 2021-04-23 07:14 UTC by apollonian

Add *.js.map to package.json's `files`. Fixes #24349. 

## Bug

- [x] Related issues linked using `fixes #number`
- [ ] Integration tests added

## ~Feature~

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## ~Documentation / Examples~

- [ ] Make sure the linting passes

2021-04-23 07:28 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.5s | ⚠️ +88ms |
| buildDurationCached | 4.8s | 4.6s | -240ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.535 | 2.509 | -0.03 |
| / avg req/sec | 986.31 | 996.46 | +10.15 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.328 | 1.306 | -0.02 |
| /error-in-render avg req/sec | 1881.88 | 1914.03 | +32.15 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 610 B | 610 B | ✓ |
| link.html gzip | 614 B | 614 B | ✓ |
| withRouter.html gzip | 604 B | 604 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 18.5s | 18.3s | -203ms |
| buildDurationCached | 7s | 6.9s | -23ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| css.html | 2.13 kB | 2.13 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | ✓ |
| link.js | 1.45 MB | 1.45 MB | ✓ |
| routerDirect.js | 1.44 MB | 1.44 MB | ⚠️ +2 B |
| withRouter.js | 1.44 MB | 1.44 MB | ✓ |
| Overall change | 7.14 MB | 7.14 MB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.7s | ⚠️ +121ms |
| buildDurationCached | 5.3s | 5.2s | -114ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.519 | 2.453 | -0.07 |
| / avg req/sec | 992.58 | 1019.16 | +26.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.412 | 1.314 | -0.1 |
| /error-in-render avg req/sec | 1770.22 | 1902.59 | +132.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js [...]

2021-04-23 08:16 UTC, timneutkens requested changes
Overall sourcemap generation should only happen during the development build, it should be excluded from the production build.

2021-04-24 07:31 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.7s | ⚠️ +122ms |
| buildDurationCached | 5.1s | 4.6s | -460ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.868 | 2.647 | -0.22 |
| / avg req/sec | 871.55 | 944.48 | +72.93 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.546 | 1.633 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1616.57 | 1531.3 | ⚠️ -85.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 616 B | 616 B | ✓ |
| withRouter.html gzip | 606 B | 606 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 19.1s | 19.7s | ⚠️ +591ms |
| buildDurationCached | 7.3s | 6.9s | -393ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | -2 B |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| css.html | 2.13 kB | 2.13 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | ✓ |
| link.js | 1.45 MB | 1.45 MB | -2 B |
| routerDirect.js | 1.44 MB | 1.44 MB | ✓ |
| withRouter.js | 1.44 MB | 1.44 MB | ✓ |
| Overall change | 7.14 MB | 7.14 MB | -4 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13s | -229ms |
| buildDurationCached | 5.6s | 5.5s | -71ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.845 | 2.683 | -0.16 |
| / avg req/sec | 878.77 | 931.8 | +53.03 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.648 | 1.57 | -0.08 |
| /error-in-render avg req/sec | 1516.9 | 1591.97 | +75.07 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| r [...]

2021-04-24 13:32 UTC, apollonian commented
> Overall sourcemap generation should only happen during the development build, it should be excluded from the production build.

Oh, my bad. That makes complete sense. Thanks for giving it a review!

@timneutkens We may conditionally set [`sourceMaps`](https://github.com/vercel/next.js/blob/canary/packages/next/taskfile-babel.js#L120) (based on the `dev` option) here in the taskfile, and for the packages ([next-codemod](https://github.com/vercel/next.js/blob/canary/packages/next-codemod/tsconfig.json#L4), [react-dev-overlay](https://github.com/vercel/next.js/blob/canary/packages/react-dev-overlay/tsconfig.json#L3), and [react-refresh-utils](https://github.com/vercel/next.js/blob/canary/packages/react-refresh-utils/tsconfig.json#L4)) that are always generating source-maps, we may remove the flag from tsconfig, and add a tsconfig.dev.json (extended from base, with `sourceMap` set to `true`) for the dev command.

2021-04-25 14:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12s | ⚠️ +222ms |
| buildDurationCached | 4s | 3.7s | -296ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.023 | 2.031 | ⚠️ +0.01 |
| / avg req/sec | 1235.77 | 1231.01 | ⚠️ -4.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.045 | 1.034 | -0.01 |
| /error-in-render avg req/sec | 2392.96 | 2417.95 | +24.99 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 608 B | 608 B | ✓ |
| link.html gzip | 615 B | 615 B | ✓ |
| withRouter.html gzip | 605 B | 605 B | ✓ |
| Overall change | 1.83 kB | 1.83 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.7s | ⚠️ +76ms |
| buildDurationCached | 5.6s | 5.6s | ⚠️ +29ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 390 B | ✓ |
| Overall change | 390 B | 390 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 1.39 MB | 1.39 MB | ✓ |
| 404.html | 2.76 kB | 2.76 kB | ✓ |
| 500.html | 2.75 kB | 2.75 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.96 kB | 1.96 kB | ✓ |
| css.html | 2.13 kB | 2.13 kB | ✓ |
| hooks.html | 2.01 kB | 2.01 kB | ✓ |
| index.js | 1.39 MB | 1.39 MB | ✓ |
| link.js | 1.45 MB | 1.45 MB | ⚠️ +2 B |
| routerDirect.js | 1.44 MB | 1.44 MB | ✓ |
| withRouter.js | 1.44 MB | 1.44 MB | ✓ |
| Overall change | 7.14 MB | 7.14 MB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 10.2s | 10.2s | ⚠️ +46ms |
| buildDurationCached | 4.3s | 4.2s | -15ms |
| nodeModulesSize | 46.6 MB | 46.6 MB | ⚠️ +4.91 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.985 | 2.026 | ⚠️ +0.04 |
| / avg req/sec | 1259.34 | 1234 | ⚠️ -25.34 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.067 | 1.038 | -0.03 |
| /error-in-render avg req/sec | 2342.12 | 2408.67 | +66.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 39 kB | 39 kB | ✓ |
| main-HASH.js gzip | 7.19 kB | 7.19 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.28 kB | 1.28 kB | ✓ |
| _error-HASH.js gzip | 3.71 kB | 3.71 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 339 B | 339 B | ✓ |
| hooks-HASH.js gzip | 887 B | 887 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDi [...]

2021-04-25 15:06 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 17s | 17.1s | ⚠️ +113ms |
| buildDurationCached | 5.6s | 5.1s | -429ms |
| nodeModulesSize | 46.6 MB | 43.8 MB | -2.81 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.994 | 2.966 | -0.03 |
| / avg req/sec | 834.92 | 842.79 | +7.87 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.701 | 1.703 | 0 |
| /error-in-render avg req/sec | 1469.69 | 1468.38 | ⚠️ -1.31 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 395 B | ⚠️ +5 B |
| Overall change | 390 B | 395 B | ⚠️ +5 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 608 B | 610 B | ⚠️ +2 B |
| link.html gzip | 615 B | 616 B | ⚠️ +1 B |
| withRouter.html gzip | 605 B | 606 B | ⚠️ +1 B |
| Overall change | 1.83 kB | 1.83 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -2,15 +2,15 @@ self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
   "/": ["static\u002Fchunks\u002Fpages\u002Findex-fec729acd14e4a5583b2.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-55112c9d838f988b054d.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-8d376292e26889ef827a.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-89a5460cada4d99b567f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-f6147d0abffd0f5c90d0.js"],
   "/css": [
     "static\u002Fcss\u002F99a142a5cfae69599804.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-ba062d31c437b1fc3e65.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-f7a3af166de6c2c7d3d5.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-8c2e74bb2b6bffaebe37.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-1effc25689b3dfd3c9ed.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-dd34d9b14dfb3c040ade.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -314,7 +314,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -16,7 +16,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -6,7 +6,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -6,7 +6,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>597-HASH.js</strong></summary>

```diff
@@ -431,7 +431,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -4125,7 +4124,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-6fd2c2da65cda01d840f.js"
+      href="/_next/static/chunks/webpack-102fa5e26cf75cc1e382.js"
       as="script"
     />
     <link
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/597-43fe3bf983c91163dca3.js"
+      href="/_next/static/chunks/597-dd7bc23aa02b36cbd90c.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-8683bd742a84c1edd48c.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-6fd2c2da65cda01d840f.js"
+      src="/_next/static/chunks/webpack-102fa5e26cf75cc1e382.js"
       async=""
     ></script>
     <script
@@ -66,7 +66,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/597-43fe3bf983c91163dca3.js"
+      src="/_next/static/chunks/597-dd7bc23aa02b36cbd90c.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-6fd2c2da65cda01d840f.js"
+      href="/_next/static/chunks/webpack-102fa5e26cf75cc1e382.js"
       as="script"
     />
     <link
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/597-43fe3bf983c91163dca3.js"
+      href="/_next/static/chunks/597-dd7bc23aa02b36cbd90c.js"
       as="script"
     />
     <link
@@ -63,7 +63,7 @@
       src="/_next/static/chunks/polyfills-8683bd742a84c1edd48c.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-6fd2c2da65cda01d840f.js"
+      src="/_next/static/chunks/webpack-102fa5e26cf75cc1e382.js"
       async=""
     ></script>
     <script
@@ -71,7 +71,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/c [...]

2021-04-26 13:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14s | -108ms |
| buildDurationCached | 4.8s | 4.4s | -408ms |
| nodeModulesSize | 46.6 MB | 43.8 MB | -2.81 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.425 | 2.445 | ⚠️ +0.02 |
| / avg req/sec | 1030.73 | 1022.5 | ⚠️ -8.23 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.201 | 1.209 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2081.91 | 2068.43 | ⚠️ -13.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 597-HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| 778-HASH.js gzip | 7.12 kB | 7.12 kB | ✓ |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 151 B | 151 B | ✓ |
| webpack-HASH.js gzip | 993 B | 993 B | ✓ |
| Overall change | 60.8 kB | 60.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.3 kB | 1.3 kB | ✓ |
| _error-HASH.js gzip | 3.68 kB | 3.68 kB | ✓ |
| amp-HASH.js gzip | 558 B | 558 B | ✓ |
| css-HASH.js gzip | 363 B | 363 B | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 243 B | 243 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 336 B | 336 B | ✓ |
| withRouter-HASH.js gzip | 334 B | 334 B | ✓ |
| 99a142a5cfae..804.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.52 kB | 9.52 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 390 B | 395 B | ⚠️ +5 B |
| Overall change | 390 B | 395 B | ⚠️ +5 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 611 B | 611 B | ✓ |
| link.html gzip | 615 B | 617 B | ⚠️ +2 B |
| withRouter.html gzip | 606 B | 607 B | ⚠️ +1 B |
| Overall change | 1.83 kB | 1.83 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -2,15 +2,15 @@ self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
   "/": ["static\u002Fchunks\u002Fpages\u002Findex-fec729acd14e4a5583b2.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-55112c9d838f988b054d.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-8d376292e26889ef827a.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-89a5460cada4d99b567f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-f6147d0abffd0f5c90d0.js"],
   "/css": [
     "static\u002Fcss\u002F99a142a5cfae69599804.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-ba062d31c437b1fc3e65.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-f7a3af166de6c2c7d3d5.js"
   ],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-8c2e74bb2b6bffaebe37.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-1effc25689b3dfd3c9ed.js"
   ],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-dd34d9b14dfb3c040ade.js"],
   "/routerDirect": [
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -314,7 +314,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -16,7 +16,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>css-HASH.js</strong></summary>

```diff
@@ -6,7 +6,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>hooks-HASH.js</strong></summary>

```diff
@@ -6,7 +6,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>597-HASH.js</strong></summary>

```diff
@@ -431,7 +431,6 @@
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -4123,7 +4122,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-ed1890aadeae3a71879e.js"
+      href="/_next/static/chunks/webpack-fa076b490c12c76ba3da.js"
       as="script"
     />
     <link
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/597-c155dff4a57343f91259.js"
+      href="/_next/static/chunks/597-3b1fec0120311666f1b3.js"
       as="script"
     />
     <link
@@ -58,7 +58,7 @@
       src="/_next/static/chunks/polyfills-8683bd742a84c1edd48c.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-ed1890aadeae3a71879e.js"
+      src="/_next/static/chunks/webpack-fa076b490c12c76ba3da.js"
       async=""
     ></script>
     <script
@@ -66,7 +66,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/597-c155dff4a57343f91259.js"
+      src="/_next/static/chunks/597-3b1fec0120311666f1b3.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -7,7 +7,7 @@
     <noscript data-n-css=""></noscript>
     <link
       rel="preload"
-      href="/_next/static/chunks/webpack-ed1890aadeae3a71879e.js"
+      href="/_next/static/chunks/webpack-fa076b490c12c76ba3da.js"
       as="script"
     />
     <link
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/597-c155dff4a57343f91259.js"
+      href="/_next/static/chunks/597-3b1fec0120311666f1b3.js"
       as="script"
     />
     <link
@@ -63,7 +63,7 @@
       src="/_next/static/chunks/polyfills-8683bd742a84c1edd48c.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-ed1890aadeae3a71879e.js"
+      src="/_next/static/chunks/webpack-fa076b490c12c76ba3da.js"
       async=""
     ></script>
     <script
@@ -71,7 +71,7 @@
       async=""
     ></script>
     <script
-      src="/_next/st [...]

2021-04-26 13:49 UTC, ijjk commented
## Failing test suites <!--2584202374-->
Commit: ccb6814a40330ce7493c75d8cdec8637371c78d5

**test/acceptance/ReactRefreshLogBox.dev.test.js** 
-  > server-side only compilation errors

<details>
<summary>Expand output</summary>

  ● server-side only compilation errors

    ScriptTimeoutError: script timeout
      (Session info: headless chrome=90.0.4430.72)

      72 |
      73 |             // Wait for application to re-hydrate:
    > 74 |             await browser.executeAsyncScript(function () {
         |             ^
      75 |               var callback = arguments[arguments.length - 1]
      76 |               if (window.__NEXT_HYDRATED) {
      77 |                 callback()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
          at runMicrotasks (<anonymous>)
      at Proxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.patch (acceptance/helpers.js:74:13)
      at Object.<anonymous> (acceptance/ReactRefreshLogBox.dev.test.js:1387:3)

</details>

2021-06-06 12:07 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.5s | -124ms |
| buildDurationCached | 3.2s | 3.3s | ⚠️ +135ms |
| nodeModulesSize | 46.6 MB | 43.9 MB | -2.71 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.714 | 2.745 | ⚠️ +0.03 |
| / avg req/sec | 921.22 | 910.89 | ⚠️ -10.33 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.6 | 1.75 | ⚠️ +0.15 |
| /error-in-render avg req/sec | 1562.43 | 1428.49 | ⚠️ -133.94 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 571 B | 571 B | ✓ |
| link.html gzip | 579 B | 579 B | ✓ |
| withRouter.html gzip | 567 B | 567 B | ✓ |
| Overall change | 1.72 kB | 1.72 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -6103,7 +6103,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -6380,7 +6379,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      href="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       as="script"
     />
     <link
@@ -57,7 +57,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      src="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      href="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       as="script"
     />
     <link
@@ -62,7 +62,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      src="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       async=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -17,7 +17,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      href="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       as="script"
     />
     <link
@@ -57,7 +57,7 @@
       async=""
     ></script>
     <script
-      src="/_next/static/chunks/main-6917b0dd70409e5a0172.js"
+      src="/_next/static/chunks/main-ed045d4a25ca92daacb5.js"
       async=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.3s | ⚠️ +54ms |
| buildDurationCached | 4.3s | 4.3s | -17ms |
| nodeModulesSize | 46.6 MB | 43.9 MB | -2.71 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 39.3 kB | 39.3 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 60.3 kB | 60.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.07 kB | 3.07 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 334 B | 334 B | ✓ |
| hooks-HASH.js gzip | 890 B | 890 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 333 B | 333 B | ✓ |
| withRouter-HASH.js gzip | 330 B | 330 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.31 kB | 8.31 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | -2 B |
| 404.html | 2.44 kB | 2.44 kB | ✓ |
| 500.html | 2.43 kB | 2.43 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.63 kB | 1.63 kB | ✓ |
| css.html | 1.81 kB | 1.81 kB | ✓ |
| hooks.html | 1.69 kB | 1.69 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.4 kB | 17.4 kB | ✓ |
| routerDirect.js | 17.4 kB | 17.4 kB | ✓ |
| withRouter.js | 17.4 kB | 17.4 kB | ✓ |
| Overall change | 107 kB | 107 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>We [...]

2021-06-19 15:23 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.9s | ⚠️ +95ms |
| buildDurationCached | 3.2s | 3s | -162ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.366 | 2.319 | -0.05 |
| / avg req/sec | 1056.48 | 1078.04 | +21.56 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.308 | 1.337 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1911.98 | 1869.45 | ⚠️ -42.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 532 B | 532 B | ✓ |
| withRouter.html gzip | 514 B | 514 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -6096,7 +6096,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -6373,7 +6372,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.7s | -54ms |
| buildDurationCached | 4.3s | 4.3s | -38ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | -2 B |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.5s | -116ms |
| buildDurationCached | 4.7s | 4.5s | -161ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.349 | 2.374 | ⚠️ +0.02 |
| / avg req/sec | 1064.23 | 1053. [...]

2021-06-19 16:37 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.1s | -4ms |
| buildDurationCached | 3.3s | 3.3s | ⚠️ +15ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.556 | 2.583 | ⚠️ +0.03 |
| / avg req/sec | 978.23 | 968.05 | ⚠️ -10.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.608 | 1.649 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1554.72 | 1515.95 | ⚠️ -38.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 532 B | 532 B | ✓ |
| withRouter.html gzip | 514 B | 514 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -6096,7 +6096,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -6373,7 +6372,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-f7adf56f2601c8465f9f.js"
+      src="/_next/static/chunks/main-c7a0480fa95a7f94a0d5.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 16s | 15.9s | -99ms |
| buildDurationCached | 4.5s | 4.6s | ⚠️ +80ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ⚠️ +2 B |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.6s | ⚠️ +347ms |
| buildDurationCached | 5s | 5s | -11ms |
| nodeModulesSize | 49.2 MB | 46.5 MB | -2.73 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.56 | 2.583 | ⚠️ +0.02 |
| / avg req/sec | 976.62 [...]

2021-07-01 04:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.6s | -42ms |
| buildDurationCached | 3.4s | 3.3s | -50ms |
| nodeModulesSize | 49.3 MB | 46.5 MB | -2.74 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.49 | 2.498 | ⚠️ +0.01 |
| / avg req/sec | 1003.96 | 1000.6 | ⚠️ -3.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.489 | 1.418 | -0.07 |
| /error-in-render avg req/sec | 1678.52 | 1763.13 | +84.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 810 B | 810 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 803 B | 803 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 526 B | 526 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.42 kB | 8.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 525 B | 525 B | ✓ |
| link.html gzip | 537 B | 537 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -6102,7 +6102,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
       var assign = Object.assign.bind(Object);
       module.exports = assign;
       module.exports.default = module.exports;
-      //# sourceMappingURL=object-assign.js.map
 
       /***/
     },
@@ -6379,7 +6378,6 @@ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLI
         }
         return page;
       }
-      //# sourceMappingURL=denormalize-page-path.js.map
 
       /***/
     },
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4aac7c58023fe877c9e3.js"
+      src="/_next/static/chunks/main-a205a5c08bf6e40a716f.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4aac7c58023fe877c9e3.js"
+      src="/_next/static/chunks/main-a205a5c08bf6e40a716f.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-4aac7c58023fe877c9e3.js"
+      src="/_next/static/chunks/main-a205a5c08bf6e40a716f.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| buildDuration | 12s | 11.9s | -90ms |
| buildDurationCached | 4.9s | 4.8s | -91ms |
| nodeModulesSize | 49.3 MB | 46.5 MB | -2.74 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.496 | 2.528 | ⚠️ +0.03 |
| / avg req/sec | 1001.73 | 989.11 | ⚠️ -12.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.437 | 1.474 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1739.97 | 1695.59 | ⚠️ -44.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.4 kB | 13.4 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 757 B | 757 B | ✓ |
| Overall change | 63.9 kB | 63.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.83 kB | 3.83 kB | ✓ |
| amp-HASH.js gzip | 531 B | 531 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip | 292 B | 292 B | ✓ |
| e025d2764813..52f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 9.26 kB | 9.26 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| _buildManifest.js gzip | 422 B | 420 B | -2 B |
| Overall change | 422 B | 420 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | apollonian/next.js fix-24349-debug-warnings | Change |
| - | - | - | - |
| index.html gzip | 567 B | 566 B | -1 B |
| link.html gzip | 580 B | 579 B | -1 B |
| withRouter.html gzip | 561 B | 559 B | -2 B |
| Overall change | 1.71 kB | 1.7 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -2,15 +2,15 @@ self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
   "/": ["static\u002Fchunks\u002Fpages\u002Findex-b460df3d63326fbb06a1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5225b5d6d91905cc2b11.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-0ad2d0a4438cb20bed36.js"
    [...]

2021-07-01 04:39 UTC, ijjk commented
## Failing test suites <!--3130208312-->
Commit: a0b55d0cf7faa249907730a87c985bab7e3b3d2a

**test/integration/font-optimization/test/index.test.js** 
- Font Optimization > with-google > Font optimization for SSR apps > should minify the css
- Font Optimization > with-google > Font optimization for emulated serverless apps > should minify the css
- Font Optimization > with-google > Font optimization for serverless apps > should minify the css

<details>
<summary>Expand output</summary>

  ● Font Optimization › with-google › Font optimization for SSR apps › should minify the css

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "https://fonts.googleapis.com/css2?family=Modak": "@font-face{font-family:'Modak';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/modak/v8/EJRYQgs1XtIEsnME.woff) format('woff')}@font-face{font-family:'Modak';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/modak/v8/EJRYQgs1XtIEskMB-hR77LKVTy8.woff2) format('woff2');unicode-range:U+0900-097F,U+1CD0-1CF6,U+1CF8-1CF9,U+200C-200D,U+20A8,U+20B9,U+25CC,U+A830-A839,U+A8E0-A8FB}@font-face{font-family:'Modak';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/modak/v8/EJRYQgs1XtIEskMO-hR77LKVTy8.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Modak';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/modak/v8/EJRYQgs1XtIEskMA-hR77LKV.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}",
        "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap": "@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff) format('woff')}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlvAA.woff) format('woff')}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtvAA.woff) format('woff')}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2) format('woff2');unicode-range:U+1F00-1FFF}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfCRc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfABc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfCBc4AMP6lbBP.woff2) format('woff2');unicode-range:U+1F00-1FFF}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfBxc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfCxc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfChc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfCRc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfABc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfCBc4AMP6lbBP.woff2) format('woff2');unicode-range:U+1F00-1FFF}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfBxc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0370-03FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfCxc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfChc4AMP6lbBP.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto';font-style:normal;font-weight:900;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmYUtfBBc4AMP6lQ.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}",
        "https://fonts.googleapis.com/css2?family=Roboto:wght@700": [...]

2022-03-25 00:07 UTC, airtonix commented
> Overall sourcemap generation should only happen during the development build, it should be excluded from the production build.

Umm why? and how do we then debug code in production?

2022-04-15 11:05 UTC, timneutkens commented
> > Overall sourcemap generation should only happen during the development build, it should be excluded from the production build.
> 
> Umm why? and how do we then debug code in production?

This has nothing to do with user code / debugging in production. it's about 3 internal packages that are only used in Next.js internal code and can't be used directly.

2022-05-22 23:48 UTC, ijjk reviewed
Hi, this appears to be stale as we no longer use `taskfile-babel` so I'm gonna close this, thanks though!

2022-05-22 23:48 UTC, closed without merging