Update emotion examples with new API for SSR and React endpoint
vercel/next.js pull request #2456
Opened 2017-07-04 01:14 UTC by hamlim

This PR fixes this issue [#80](https://github.com/tkh44/emotion/issues/80) opened up at https://github.com/tkh44/emotion.

The `emotion/server` export changed names and the react `styled` imports changed as well. I also manually bumped the version of emotion in the `package.json` file.

It looks like something in my config changed the indentation significantly. Not sure what could have caused that but if anyone has tips on how to resolve let me know!

2017-07-04 19:11 UTC, tkh44 requested changes
It looks like the file formatting is off. You should be able to format the code with `npm run lint`

2017-07-05 21:10 UTC, hamlim commented on examples/with-emotion/pages/index.js
> +      <Animated animation={bounce}>Let's bounce.</Animated>
Looks like prettier made this change to one line, I can revert this back if you'd like. cc @tkh44

2017-07-05 21:11 UTC, hamlim commented
Fixed the tabs vs spaces issue, this should be good to be reviewed again @tkh44.

2017-07-05 21:41 UTC, tkh44 approved these changes

2017-07-06 05:44 UTC, timneutkens approved these changes
Nice! 💯

2017-07-06 05:44 UTC, merged