Fix Link when used with an <a> styled-component.
vercel/next.js pull request #2475
Opened 2017-07-05 23:41 UTC by victor-borges

Fixes the `next/link` bug #1942.

2017-07-06 16:43 UTC, timneutkens commented on package.json
> +  "version": "3.0.1-beta.9",
please don't upgrade the version in a PR.

2017-07-06 16:44 UTC, timneutkens commented on .gitignore
> +.idea
You can do this in a global gitignore file. But oh well, we've seen this so many times. I want to take it in @arunoda

2017-07-06 18:20 UTC, victor-borges commented on package.json
> +  "version": "3.0.1-beta.9",
Sorry. It was my first external project contribution. 
I'm still learning the rules.

2017-07-07 04:09 UTC, arunoda commented on .gitignore
> +.idea
Remove this from this PR and if needed create a new PR.

2017-07-07 04:13 UTC, arunoda requested changes
Check my comments.

2017-07-07 04:13 UTC, arunoda commented on .gitignore
> +.idea
Remove this from this PR and if needed create a new PR.

2017-07-07 04:13 UTC, arunoda commented on lib/link.js
> +    if ((child.type === 'a' || (child.type === 'function' && child.type.target === 'a')) &&
I don't like doing any special handling for `styled-component`. I know `styled-component` is pretty good. But this is kind a hack and they could change the `target` field into something else.

And styled-component is just a one solution in this space.

---

But we need to add support for this.

So, I suggest to do it like this:

```js
<Link href="/about" passHref>
  <StyledLink />
</Link>
```

2017-07-08 04:18 UTC, closed without merging

2017-07-08 11:35 UTC, victor-borges commented on lib/link.js
> +    if ((child.type === 'a' || (child.type === 'function' && child.type.target === 'a')) &&
It's amazing. Simple and clear.