chore: add test coverage
vercel/next.js pull request #259
Opened 2016-11-15 08:35 UTC by bcoe

Adds test coverage using `nyc` and `babel-plugin-istanbul`, see #244

<img width="770" alt="screen shot 2016-11-15 at 12 35 24 am" src="https://cloud.githubusercontent.com/assets/194609/20298547/6c28ad46-aacb-11e6-8b8f-904e4b706008.png">

## a few notes about this pull request

* I've switched to using `babel-core/register`, which is easier to wire up with `babel-plugin-istanbul`.
* I've moved babel settings into `.babelrc`, and in turn load these in `gulpfile.js`; both `babel-register`, and the build process need these same settings, and it seemed worthwhile to consolidate them.
* I've introduced a few more dependencies:
  * `coveralls`: used to pipe lcov report to coveralls.io.
  * `read-pkg-up`: used to load the parent package.json (this is necessary because in test files are under `lib/`, but after building they are located in `dist/lib`.
* I added a couple more tests, mainly to ensure that coverage was being computed accurately.

## enabling coverage badge

To get the coverage bade working, someone with admin access to this repo will need to enable this project on https://coveralls.io/

2016-11-15 18:36 UTC, bcoe commented
Just a quick update, I've added a few scripts in this pull request:

* `npm test`: runs tests through gulp, pretty much the same as the old behavior.
* `npm run ava`: run ava in isolation, this is good thing to have as we build out tests, so that we don't need to run the full suite each time; I was for instance doing this while testing:
  
<img width="876" alt="screen shot 2016-11-15 at 10 34 05 am" src="https://cloud.githubusercontent.com/assets/194609/20318427/12f1a350-ab1f-11e6-9f53-38d401c1b503.png">

* `npm run html-report`: output a pretty HTML report, which makes it easier to hunt down lines of code missing coverage:

<img width="628" alt="screen shot 2016-11-15 at 10 35 13 am" src="https://cloud.githubusercontent.com/assets/194609/20318483/3dcdf20e-ab1f-11e6-8f9a-e58808cdb3ff.png">

* `npm run coveralls`: pipe coverage output, from the last test run, to coveralls -- this is called in `.travis.yml`.

2016-11-16 07:39 UTC, nkzawa commented
Thanks, LGTM ! 😄

2016-11-17 16:01 UTC, rauchg requested changes

2016-11-17 16:47 UTC, bcoe commented
@rauchg I agree that this felt a bit weird; part of me wants to set NODE_ENV=test in nyc, but this feels like it's not flexible enough -- I've instead pulled in the neat little plugin `gulp-process-env`, which feels pretty elegant.

2016-11-18 02:00 UTC, arunoda commented on gulpfile.js
> +  process.env.NODE_ENV = 'test'
I think this is fine.
But we could do this too.

```
process.env.NODE_ENV = process.env.NODE_ENV || 'test'
```

2016-11-21 12:42 UTC, arunoda commented
Guys, I wonder the state of this PR with the potential decision(https://github.com/zeit/next.js/issues/278) to move to Jest.

2016-11-21 13:16 UTC, rauchg commented
I want to merge this sooner rather than later. Shouldn't be hard to substitute the runner, since we're basically making assertions of snapshots already

2016-11-22 18:28 UTC, bcoe commented
@rauchg @arunoda rebased again, in case you do decide to land this; I'd be happy to help with the Jest switch over when the time comes -- but I would like to dig into whether there's a way to make Jest's use of `babel-plugin-istanbul` play nice with `nyc` ... it would be nice to have access to the lovely advanced reporting features.

2016-11-23 17:24 UTC, nkzawa commented
LGTM

2016-12-02 01:37 UTC, merged

2016-12-02 01:54 UTC, bcoe commented
@nkzawa @rauchg follow up, make sure you registry the project here:

https://coveralls.io/r/zeit/next.js?branch=master

and kick off a build on `master`, otherwise the bade won't populate.

2016-12-02 02:10 UTC, nkzawa commented
@bcoe registered, thanks!