Add runtime to hotUpdateMainFilename
vercel/next.js pull request #26256
Opened 2021-06-17 10:54 UTC by timneutkens

Updates the hotUpdateChunk to include `[runtime]` for web workers support.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

- [ ] Make sure the linting passes

2021-06-17 11:06 UTC, ijjk commented
## Failing test suites <!--3019115715-->
Commit: 3e08d5ae6acb25c1116e64784dc9362efd63fd6e

**test/integration/config/test/index.test.js** 
- Configuration > should log webpack version correctly
- Configuration > should disable X-Powered-By header support
- Configuration > renders css imports
- Configuration > renders non-js imports from node_modules
- Configuration > renders server config on the server only
- Configuration > renders public config on the server only
- Configuration > renders the build id in development mode
- Configuration > correctly imports a package that defines `module` but no `main` in package.json
- Configuration > should have config available on the client
- Configuration > should update css styles using hmr
- Configuration > should update sass styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › should log webpack version correctly

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should disable X-Powered-By header support

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders css imports

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders non-js imports from node_modules

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders server config on the server only

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders public config on the server only

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › renders the build id in development mode

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › correctly imports a package that defines `module` but no `main` in package.json

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should have config available on the client

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update css styles using hmr

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

  ● Configuration › should update sass styles using hmr

    FetchError: request to http://localhost:38685/next-config failed, reason: connect ECONNREFUSED 127.0.0.1:38685

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1461:11)

</details>

2021-06-17 11:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 12.3s | 12.6s | ⚠️ +293ms |
| buildDurationCached | 3.1s | 3s | -57ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | -151 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.4 | 2.381 | -0.02 |
| / avg req/sec | 1041.6 | 1049.85 | +8.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.517 | 1.518 | 0 |
| /error-in-render avg req/sec | 1647.65 | 1646.6 | ⚠️ -1.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.1s | -313ms |
| buildDurationCached | 4.1s | 3.8s | -233ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | -151 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | -2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | -61ms |
| buildDurationCached | 4.2s | 4.4s | ⚠️ +225ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | -151 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.403 | 2.295 | -0.11 |
| / avg req/sec | 1040.19 | 1089.19 | +49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.401 | 1.556 | ⚠️ +0.16 |
| /error-in-render avg req/sec | 1784.18 | 1606.86 | ⚠️ -177.32 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B [...]

2021-06-17 12:12 UTC, adamjkester5 requested changes
**don't like**

2021-06-17 12:15 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 13s | 13s | ⚠️ +40ms |
| buildDurationCached | 3.2s | 3.1s | -33ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +102 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.355 | 2.32 | -0.04 |
| / avg req/sec | 1061.51 | 1077.71 | +16.2 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.317 | 1.334 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1898.76 | 1873.38 | ⚠️ -25.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 15s | 14.7s | -306ms |
| buildDurationCached | 4.3s | 4.3s | -31ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +102 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 804 B | ✓ |
| Overall change | 63 kB | 63 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 11.7s | 11.6s | -106ms |
| buildDurationCached | 4.7s | 4.7s | ⚠️ +31ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +102 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.428 | 2.359 | -0.07 |
| / avg req/sec | 1029.49 | 1059.96 | +30.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.324 | 1.32 | 0 |
| /error-in-render avg req/sec | 1887.95 | 1894.21 | +6.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| 677f882d2ed8..HASH.js gzip | 13.3 kB | 13.3 kB | ✓ |
| framework.HASH.js gzip | 41.8 kB | 41.8 kB | ✓ |
| main-HASH.js gzip | 7.99 kB | 7.99 kB | ✓ |
| webpack-HASH.js gzip | 751 B | 751 B | ✓ |
| Overall change | 63.8 kB | 63.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.3 kB | 31.3 kB | ✓ |
| Overall change | 31.3 kB | 31.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.07 kB | 1.07 kB | ✓ |
| _error-HASH.js gzip | 3.84 kB | 3.84 kB | ✓ |
| amp-HASH.js gzip | 536 B | 536 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| hooks-HASH.js gzip | 910 B | 910 B | ✓ |
| index-HASH.js gzip | 227 B | 227 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 295 B | 295 B | ✓ |
| withRouter-HASH.js gzip [...]

2021-06-17 12:16 UTC, ijjk commented
## Failing test suites <!--3019635837-->
Commit: 31aeb4c38904026e0c975e363b5b939edc52942b

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should detect the changes and display it
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect the changes and display it

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is the hot AMP page."
    Received: "replaced it!"

      320 |         browser = await webdriver(dynamicAppPort, '/hmr/test')
      321 |         const text = await browser.elementByCss('p').text()
    > 322 |         expect(text).toBe('This is the hot AMP page.')
          |                      ^
      323 |
      324 |         const hmrTestPagePath = join(
      325 |           __dirname,

      at Object.<anonymous> (integration/amphtml/test/index.test.js:322:22)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1623932140990"
    Received: "1623932151626"

      431 |         while (i < checks) {
      432 |           const curText = await browser.elementByCss('span').text()
    > 433 |           expect(curText).toBe(origDate)
          |                           ^
      434 |           await waitFor(1000)
      435 |           i++
      436 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:433:27)

</details>

2021-06-17 12:58 UTC, ijjk commented
## Failing test suites <!--3020012005-->
Commit: a5249e6ce4417ac0117c9b9c310dc4cc5ee34d46

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should detect the changes and display it
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect the changes and display it

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is the hot AMP page."
    Received: "replaced it!"

      320 |         browser = await webdriver(dynamicAppPort, '/hmr/test')
      321 |         const text = await browser.elementByCss('p').text()
    > 322 |         expect(text).toBe('This is the hot AMP page.')
          |                      ^
      323 |
      324 |         const hmrTestPagePath = join(
      325 |           __dirname,

      at Object.<anonymous> (integration/amphtml/test/index.test.js:322:22)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1623934654241"
    Received: "1623934664943"

      431 |         while (i < checks) {
      432 |           const curText = await browser.elementByCss('span').text()
    > 433 |           expect(curText).toBe(origDate)
          |                           ^
      434 |           await waitFor(1000)
      435 |           i++
      436 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:433:27)

</details>

2021-06-17 12:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 11.7s | 12s | ⚠️ +348ms |
| buildDurationCached | 2.8s | 3s | ⚠️ +175ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.115 | 2.186 | ⚠️ +0.07 |
| / avg req/sec | 1182.11 | 1143.74 | ⚠️ -38.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.204 | 1.241 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 2076.06 | 2013.95 | ⚠️ -62.11 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 534 B | -2 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.3s | -147ms |
| buildDurationCached | 3.8s | 3.8s | ⚠️ +33ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ⚠️ +2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ⚠️ +2 B |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | -2 B |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | -1ms |
| buildDurationCached | 4.3s | 4.1s | -130ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-h [...]

2021-06-17 16:09 UTC, ijjk approved these changes, later dismissed

2021-06-17 16:23 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 10.9s | 11.1s | ⚠️ +123ms |
| buildDurationCached | 2.7s | 2.7s | -22ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 1.991 | 2.049 | ⚠️ +0.06 |
| / avg req/sec | 1255.73 | 1220.34 | ⚠️ -35.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.122 | 1.124 | 0 |
| /error-in-render avg req/sec | 2228.03 | 2224.26 | ⚠️ -3.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 534 B | -2 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.4s | -15ms |
| buildDurationCached | 3.6s | 3.6s | -11ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 391 B | 391 B | ✓ |
| Overall change | 391 B | 391 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ⚠️ +2 B |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 9.7s | 9.8s | ⚠️ +53ms |
| buildDurationCached | 3.9s | 3.9s | -47ms |
| nodeModulesSize | 46.4 MB | 46.4 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Cha [...]

2021-06-17 16:26 UTC, ijjk commented
## Failing test suites <!--3022036119-->
Commit: b9c27e6820acdefca96b0548902ee053f34e1ed4

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should detect the changes and display it
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should detect the changes and display it

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is the hot AMP page."
    Received: "replaced it!"

      320 |         browser = await webdriver(dynamicAppPort, '/hmr/test')
      321 |         const text = await browser.elementByCss('p').text()
    > 322 |         expect(text).toBe('This is the hot AMP page.')
          |                      ^
      323 |
      324 |         const hmrTestPagePath = join(
      325 |           __dirname,

      at Object.<anonymous> (integration/amphtml/test/index.test.js:322:22)
          at runMicrotasks (<anonymous>)

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1623947120611"
    Received: "1623947131307"

      431 |         while (i < checks) {
      432 |           const curText = await browser.elementByCss('span').text()
    > 433 |           expect(curText).toBe(origDate)
          |                           ^
      434 |           await waitFor(1000)
      435 |           i++
      436 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:433:27)

</details>

2021-06-18 12:34 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 11.3s | 11.3s | -13ms |
| buildDurationCached | 2.7s | 2.7s | -23ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.055 | 1.937 | -0.12 |
| / avg req/sec | 1216.63 | 1290.76 | +74.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.163 | 1.134 | -0.03 |
| /error-in-render avg req/sec | 2149 | 2204.56 | +55.56 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.6s | ⚠️ +220ms |
| buildDurationCached | 3.6s | 3.6s | -64ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ⚠️ +2 B |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ⚠️ +2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 9.8s | 9.9s | ⚠️ +111ms |
| buildDurationCached | 3.8s | 4.1s | ⚠️ +298ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +205 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change  [...]

2021-06-18 12:36 UTC, ijjk commented
## Failing test suites <!--3029439260-->
Commit: 21a785aa451c0932ac47b2153cc5d2f2bc4e0998

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1624019721040"
    Received: "1624019731833"

      425 |         while (i < checks) {
      426 |           const curText = await browser.elementByCss('span').text()
    > 427 |           expect(curText).toBe(origDate)
          |                           ^
      428 |           await waitFor(1000)
      429 |           i++
      430 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:427:27)

</details>

2021-06-18 14:19 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.5s | -56ms |
| buildDurationCached | 2.8s | 2.8s | ⚠️ +31ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +657 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.08 | 2.107 | ⚠️ +0.03 |
| / avg req/sec | 1201.69 | 1186.59 | ⚠️ -15.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.157 | 1.191 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2160.37 | 2099.88 | ⚠️ -60.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.1s | -231ms |
| buildDurationCached | 3.9s | 3.8s | -167ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +657 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | -2 B |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 10.3s | 10.3s | -77ms |
| buildDurationCached | 4.1s | 4.2s | ⚠️ +68ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +657 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Ch [...]

2021-06-18 14:21 UTC, ijjk commented
## Failing test suites <!--3030283550-->
Commit: 577dcc6dc55ba8a6ac76b13c48200cc62f3b6e00

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1624026014556"
    Received: "1624026025077"

      425 |         while (i < checks) {
      426 |           const curText = await browser.elementByCss('span').text()
    > 427 |           expect(curText).toBe(origDate)
          |                           ^
      428 |           await waitFor(1000)
      429 |           i++
      430 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:427:27)

</details>

2021-06-18 14:26 UTC, timneutkens commented on packages/next/client/dev/amp-dev.js
> +        : `${hotUpdatePath}${curHash}..hot-update.json`
Double dot:
```suggestion
        : `${hotUpdatePath}${curHash}.hot-update.json`
```

2021-06-18 14:28 UTC, timneutkens commented
Reported @adamjkester5 as a spam bot.

2021-06-18 14:38 UTC, ijjk commented
## Failing test suites <!--3030425027-->
Commit: 8d0b5ec28a7c76d324ed8cfcdf120d17b386e98a

**test/integration/amphtml/test/index.test.js** 
- AMP Usage > AMP dev mode > should not reload unless the page is edited for an AMP page

<details>
<summary>Expand output</summary>

  ● AMP Usage › AMP dev mode › should not reload unless the page is edited for an AMP page

    expect(received).toBe(expected) // Object.is equality

    Expected: "1624027037813"
    Received: "1624027048424"

      425 |         while (i < checks) {
      426 |           const curText = await browser.elementByCss('span').text()
    > 427 |           expect(curText).toBe(origDate)
          |                           ^
      428 |           await waitFor(1000)
      429 |           i++
      430 |         }

      at Object.<anonymous> (integration/amphtml/test/index.test.js:427:27)

</details>

2021-06-18 14:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 13s | 12.9s | -157ms |
| buildDurationCached | 3.1s | 3.1s | ⚠️ +3ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +655 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.429 | 2.522 | ⚠️ +0.09 |
| / avg req/sec | 1029.24 | 991.46 | ⚠️ -37.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.559 | 1.557 | 0 |
| /error-in-render avg req/sec | 1604.06 | 1605.26 | +1.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 14.8s | 14.7s | -99ms |
| buildDurationCached | 4.1s | 4.3s | ⚠️ +227ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +655 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | -2 B |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | -2 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.4s | -357ms |
| buildDurationCached | 4.9s | 4.5s | -385ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +655 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | [...]

2021-06-18 16:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.5s | ⚠️ +346ms |
| buildDurationCached | 3.4s | 3.5s | ⚠️ +96ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.628 | 2.671 | ⚠️ +0.04 |
| / avg req/sec | 951.41 | 935.84 | ⚠️ -15.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.663 | 1.757 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1503.62 | 1422.79 | ⚠️ -80.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 16.7s | 16.5s | -238ms |
| buildDurationCached | 4.6s | 4.9s | ⚠️ +262ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.6s | ⚠️ +86ms |
| buildDurationCached | 5.1s | 5s | -144ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - [...]

2021-06-18 16:38 UTC, ijjk approved these changes

2021-06-18 16:50 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.4s | -196ms |
| buildDurationCached | 3.2s | 3.4s | ⚠️ +227ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.412 | 2.358 | -0.05 |
| / avg req/sec | 1036.67 | 1060.1 | +23.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.425 | 1.37 | -0.05 |
| /error-in-render avg req/sec | 1754.45 | 1825.41 | +70.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 532 B | -3 B |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>webpack-HASH.js</strong></summary>

```diff
@@ -178,7 +178,7 @@
   /******/
 
   /******/ /******/ !(function() {
-    /******/ __webpack_require__.p = "";
+    /******/ __webpack_require__.p = "/_next/";
     /******/
   })(); /* webpack/runtime/jsonp chunk loading */
   /******/
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -11,7 +11,7 @@
       src="/_next/static/chunks/polyfills-78af6fe89161f65f5762.js"
     ></script>
     <script
-      src="/_next/static/chunks/webpack-16fb5e52861014c05b14.js"
+      src="/_next/static/chunks/webpack-c14d70924bc10b27e8cb.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.3s | ⚠️ +8ms |
| buildDurationCached | 4.5s | 4.4s | -39ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 20.2 kB | 20.2 kB | ✓ |
| webpack-HASH.js gzip | 804 B | 810 B | ⚠️ +6 B |
| Overall change | 63 kB | 63 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31.1 kB | 31.1 kB | ✓ |
| Overall change | 31.1 kB | 31.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _app-HASH.js gzip | 801 B | 801 B | ✓ |
| _error-HASH.js gzip | 3.17 kB | 3.17 kB | ✓ |
| amp-HASH.js gzip | 527 B | 527 B | ✓ |
| css-HASH.js gzip | 330 B | 330 B | ✓ |
| hooks-HASH.js gzip | 903 B | 903 B | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.65 kB | 1.65 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 8.41 kB | 8.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _buildManifest.js gzip | 392 B | 392 B | ✓ |
| Overall change | 392 B | 392 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| _error.js | 16.9 kB | 16.9 kB | ✓ |
| 404.html | 1.98 kB | 1.98 kB | ✓ |
| 500.html | 1.96 kB | 1.96 kB | ✓ |
| amp.amp.html | 10.8 kB | 10.8 kB | ✓ |
| amp.html | 1.17 kB | 1.17 kB | ✓ |
| css.html | 1.35 kB | 1.35 kB | ✓ |
| hooks.html | 1.23 kB | 1.23 kB | ✓ |
| index.js | 17.2 kB | 17.2 kB | ✓ |
| link.js | 17.5 kB | 17.5 kB | ✓ |
| routerDirect.js | 17.3 kB | 17.3 kB | ✓ |
| withRouter.js | 17.3 kB | 17.3 kB | ✓ |
| Overall change | 105 kB | 105 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| buildDuration | 12.1s | 12s | -163ms |
| buildDurationCached | 4.9s | 4.8s | -74ms |
| nodeModulesSize | 49.2 MB | 49.2 MB | ⚠️ +670 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js fix/update-runtime-hot-chunk-name | Change |
| - | - | - | - |
| / failed req [...]

2021-06-18 17:12 UTC, merged