Update the with-graphql-react example
vercel/next.js pull request #26435
Opened 2021-06-21 15:02 UTC by jaydenseric

- Completely new example for [`graphql-react`](https://github.com/jaydenseric/graphql-react) v15 and [`next-graphql-react`](https://github.com/jaydenseric/next-graphql-react) v11, that:
  - Uses the [Countries GraphQL API](https://github.com/trevorblades/countries) instead of the [GraphQL Pokémon API](https://github.com/lucasbento/graphql-pokemon) that has had significant outages.
  - Demonstrates using Next.js [dynamic route](https://nextjs.org/docs/routing/dynamic-routes) parameters in GraphQL query variables.
  - Demonstrates using [`next-server-context`](https://github.com/jaydenseric/next-server-context) to set a HTTP response status code (e.g. 404) for the server side rendered page according to GraphQL query results.
- Added a package `engines` field.
- Tweaked the maximum [`graphql-react`](https://github.com/jaydenseric/graphql-react) bundle size mentioned in the readme. The slightly larger maximum reflects measurement changes (KB vs kB, [webpack](https://webpack.js.org) vs [esbuild](https://esbuild.github.io), etc.) and extras exported in the new API; the more composable new API is actually more bundle efficient.
- Updated the [Relay](https://relay.dev) link URL in the readme.

2022-07-01 14:48 UTC, Demmonius commented
Hi @divmain @ijjk @leerob @lfades @shuding @timneutkens 
Would it be possible to merge this pull-request? I could not find out why the example was not working, until I found [this issue](https://github.com/jaydenseric/graphql-react/issues/58)?

2022-07-06 13:24 UTC, balazsorban44 requested changes
Could we convert this to TypeScript? See https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

I am not sure about the polyfills and `engines`. Why do we need this? :thinking:

2022-07-06 13:26 UTC, balazsorban44 commented
@Demmonius please refrain from tagging most of the Next.js team at once in the future. :pray: There is no need.

2022-09-30 00:12 UTC, balazsorban44 commented
Hi, this PR seems to be a bit out-of-date with our [example guidelines](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md), so I am going to close it. If you have the intention to bring it up-to-date, please do! Thanks for the work either way! :pray: :green_heart:

2022-09-30 00:12 UTC, closed without merging