NextJs Pwa Code Example
vercel/next.js pull request #26613
Opened 2021-06-25 16:59 UTC by sharozraees802

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.

## Documentation / Examples

- [ ] Make sure the linting passes

2021-07-02 00:20 UTC, hsh2001 requested changes
Nice example! Please see my suggestion.

2021-07-02 00:20 UTC, hsh2001 commented on examples/next_pwa_app/README.md
> +```code
```suggestion
```js
```

before: 
```code
console.log(this.name);
```

after:
```js
console.log(this.name);
```

2021-07-02 00:20 UTC, hsh2001 commented on examples/next_pwa_app/README.md
> +## Pwa in next Js
```suggestion
## PWA in next Js
```

2021-07-02 00:20 UTC, hsh2001 commented on examples/next_pwa_app/README.md
> +This is a [Next-Pwa](https://www.npmjs.com/package/next-pwa) install and the create a next.Config.js file add Code
```suggestion
This is a [next-pwa](https://www.npmjs.com/package/next-pwa) install and the create a next.Config.js file add Code
```

The package name is `next-pwa` in lowercase right?

2022-09-30 00:17 UTC, balazsorban44 requested changes
Can we bring this example up-to-date with the [examples guidelines](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)? If not, that is understandable, let's close it for now and revisit later on. :pray: :green_heart: Thanks for the work either way!

2022-11-28 11:46 UTC, balazsorban44 commented
Closing as we actually already have an example: https://github.com/vercel/next.js/blob/canary/examples/progressive-web-app

Which might need deprecation: https://github.com/vercel/next.js/issues/43439

2022-11-28 11:46 UTC, closed without merging