Material UI Next example: Use module-scoped singleton
vercel/next.js pull request #2679
Opened 2017-07-28 18:17 UTC by sbking

The `material-ui-next` example stores a singleton instance of its JSS context on the global object. Because ES6 module imports resolve to the same reference when imported into multiple files, this singleton object can simply be stored in the module itself to avoid polluting the global namespace.

2017-07-29 12:38 UTC, timneutkens commented
@oliviertassinari could you check it? 😄

2017-07-29 13:15 UTC, oliviertassinari commented
I have had issue of duplicated modules with code spliting in the past, especially with hot reloading. That was problematique with redux as stateful. Here I would expect the styling solution to be resilient to that issue. In the doubt, I would rather keep the logic.

2017-07-30 06:15 UTC, sbking commented
@oliviertassinari The SheetsRegistry should only be needed on the server, if that makes a difference. I'm not sure why the browser-specific logic is there. Both the Material UI docs and JSS docs indicate that it is only needed on the server:

https://github.com/cssinjs/jss/blob/master/docs/js-api.md#style-sheets-registry

2017-07-30 10:32 UTC, oliviertassinari commented
> not sure why the browser-specific logic is there.

It's here for simplicity. Given how next.js work we would have to create a code branch to handle the client differentely. That's always something we can do 👍.

Yes, on the client side, only the theme is needed. If for some reason the module is duplicated, the theme change. The side effect is the following, we unmount all the styles with the old theme and remount them with the new theme. That's bad for performance.

2017-07-30 19:03 UTC, oliviertassinari requested changes
I would keep the logic unless we have the guarantee the modules can't be duplicated.

2017-07-30 20:22 UTC, timneutkens commented
@oliviertassinari I'm ok with that 👌

2017-07-30 20:22 UTC, closed without merging

2017-07-30 20:22 UTC, timneutkens commented
@sbking thank you so much for your contribution ❤️

2017-08-16 01:04 UTC, sbking commented
@oliviertassinari 

> Yes, on the client side, only the theme is needed. If for some reason the module is duplicated, the theme change. The side effect is the following, we unmount all the styles with the old theme and remount them with the new theme. That's bad for performance.

This approach seems to prevent HMR for themes from working, so I have to reload the page if I change my theme. For me, hot style updates are very important during development. Is the `createMuiTheme` function really that heavy? I'm now using it in the render method of my `withRoot` and I don't notice any performance impact when changing pages.

2017-08-16 07:28 UTC, oliviertassinari commented
> This approach seems to prevent HMR for themes from working

Yes, I think that it does prevent it as we store the theme in a global variable. It's not the theme object creation that is slow, it's the style sheet injection/removal in the page that can takes time.
I don't know what's the best fix here.

2017-08-16 16:56 UTC, sbking commented
@oliviertassinari Alright, I think that the solution I will go with for now is to create the theme every render in development, but use the singleton global during production.

2017-08-16 17:37 UTC, oliviertassinari commented
@sbking As I'm migrating the documentation of Material-UI to next.js, I'm experimenting new solutions.

2017-08-16 18:00 UTC, sbking commented
@oliviertassinari That's great to hear! One thing that would be really awesome as well is a solution that can support the nested themes/`MuiThemeProviders` as shown in the Material UI 1.0 docs, if possible. It's one of the features that made me fall in love with Material UI.