Examples: Jotai
vercel/next.js pull request #27940
Opened 2021-08-11 06:32 UTC by Thisen

## Documentation / Examples

- [X] Make sure the linting passes

This adds an example using Jotai with Next.js. It uses the new hook `useHydrateAtoms` to hydrate atoms with values from the server.

2021-08-11 15:14 UTC, leerob requested changes

2021-08-11 15:14 UTC, leerob commented on examples/with-jotai/README.md
> +Jotai uses the `useHydrateAtoms` hook to hydrate the value of an atom, for values that comes from the server.
```suggestion
- Jotai is a primitive and flexible state management library for React.
- Jotai is TypeScript oriented and aims to expose a minimalistic API for dealing with state in a data-flow graph way.
- Jotai uses the `useHydrateAtoms` hook to hydrate the value of an atom, for values that come from the server.
```

2021-08-11 15:14 UTC, leerob commented on examples/with-jotai/pages/_app.tsx
> +export default MyApp
```suggestion
export default function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}
```

2021-08-13 16:04 UTC, leerob approved these changes

2021-08-14 04:00 UTC, ijjk approved these changes

2021-08-14 04:06 UTC, merged