Support node-sass@6
vercel/next.js pull request #28710
Opened 2021-09-01 14:34 UTC by adrienharnay

This features supports node-sass@6, which supports node@16.

Addresses the discussion https://github.com/vercel/next.js/discussions/28704#discussioncomment-1265193

2021-09-01 16:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.7s | -151ms |
| buildDurationCached | 2.9s | 2.9s | -10ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.291 | 2.291 | ✓ |
| / avg req/sec | 1091.04 | 1091.21 | +0.17 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.263 | 1.27 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1979.83 | 1968.63 | ⚠️ -11.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 491 B | 491 B | ✓ |
| Overall change | 491 B | 491 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 540 B | 540 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 10.5s | 10.5s | -25ms |
| buildDurationCached | 4.6s | 4.7s | ⚠️ +134ms |
| nodeModulesSize | 61.7 MB | 61.7 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.328 | 2.296 | -0.03 |
| / avg req/sec | 1073.84 | 1088.72 | +14.88 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.269 | 1.271 | 0 |
| /error-in-render avg req/sec | 1970.78 | 1967.49 | ⚠️ -3.29 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 586 B | 586 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: 088d7c9c57d77bfcbc4f1daf8fe74622ae5e36c2

2021-09-01 16:12 UTC, ijjk commented
## Failing test suites <!--3654322038-->
Commit: 088d7c9c57d77bfcbc4f1daf8fe74622ae5e36c2

**test/integration/config/test/index.test.js** 
- Configuration > renders css imports
- Configuration > renders non-js imports from node_modules
- Configuration > renders server config on the server only
- Configuration > renders public config on the server only
- Configuration > renders the build id in development mode
- Configuration > correctly imports a package that defines `module` but no `main` in package.json
- Configuration > should have config available on the client
- Configuration > should update css styles using hmr
- Configuration > should update sass styles using hmr

<details>
<summary>Expand output</summary>

  ● Configuration › renders css imports

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=92.0.4515.131)

      417 |     } catch (err) {
      418 |       await waitFor(1000)
    > 419 |       lastErr = err
          |                    ^
      420 |     }
      421 |   }
      422 |   console.error('TIMED OUT CHECK: ', { regex, content, lastErr })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.check (lib/next-test-utils.js:419:23)
      at Object.<anonymous> (integration/config/test/index.test.js:57:13)

  ● Configuration › renders non-js imports from node_modules

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=92.0.4515.131)

      417 |     } catch (err) {
      418 |       await waitFor(1000)
    > 419 |       lastErr = err
          |                    ^
      420 |     }
      421 |   }
      422 |   console.error('TIMED OUT CHECK: ', { regex, content, lastErr })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.check (lib/next-test-utils.js:419:23)
      at Object.<anonymous> (integration/config/test/index.test.js:69:13)

  ● Configuration › renders server config on the server only

    expect(received).toBe(expected) // Object.is equality

    Expected: "secret"
    Received: ""

      77 |       if (browser) {
      78 |         await browser.close()
    > 79 |       }
         |        ^
      80 |     }
      81 |   })
      82 |

      at Object.<anonymous> (integration/config/test/index.test.js:79:42)

  ● Configuration › renders public config on the server only

    expect(received).toBe(expected) // Object.is equality

    Expected: "/static"
    Received: ""

      81 |   })
      82 |
    > 83 |   test('renders non-js imports from node_modules', async () => {
         |                                                ^
      84 |     let browser
      85 |     try {
      86 |       browser = await webdriver(context.appPort, '/webpack-css')

      at Object.<anonymous> (integration/config/test/index.test.js:83:48)

  ● Configuration › renders the build id in development mode

    expect(received).toBe(expected) // Object.is equality

    Expected: "development"
    Received: ""

      85 |     try {
      86 |       browser = await webdriver(context.appPort, '/webpack-css')
    > 87 |       await check(
         |                   ^
      88 |         () =>
      89 |           browser
      90 |             .elementByCss('.hello-world')

      at Object.<anonymous> (integration/config/test/index.test.js:87:38)

  ● Configuration › correctly imports a package that defines `module` but no `main` in package.json

    expect(received).toBe(expected) // Object.is equality

    Expected: "OK"
    Received: ""

      89 |           browser
      90 |             .elementByCss('.hello-world')
    > 91 |             .getComputedCss('background-color'),
         |                                                ^
      92 |         'rgba(0, 0, 255, 1)'
      93 |       )
      94 |     } finally {

      at Object.<anonymous> (integration/config/test/index.test.js:91:48)

  ● Configuration › should have config available on the client

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#server-only"}
      (Session info: headless chrome=92.0.4515.131)

      93 |       )
      94 |     } finally {
    > 95 |       if (browser) {
         |                     ^
      96 |         await browser.close()
      97 |       }
      98 |     }

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/config/test/index.test.js:95:28)

  ● Configuration › should update css styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=92.0.4515.131)

      106 |   test('renders public config on the server only', async () => {
      107 |     const $ = await get$('/next-config')
    > 108 |     expect($('#server-and-client').text()).toBe('/static')
          |                              ^
      109 |   })
      110 |
      111 |   test('renders the build id in development mode', async () => {

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at integration/config/test/index.test.js:108:30
      at Object.check (lib/next-test-utils.js:419:23)
      at Object.<anonymous> (integration/config/test/index.test.js:107:13)

  ● Configuration › should update sass styles using hmr

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".hello-world"}
      (Session info: headless chrome=92.0.4515.131)

      417 |     } catch (err) {
      418 |       await waitFor(1000)
    > 419 |       lastErr = err
          |                    ^
      420 |     }
      421 |   }
      422 |   console.error('TIMED OUT CHECK: ', { regex, content, lastErr })

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.check (lib/next-test-utils.js:419:23)
      at Object.<anonymous> (integration/config/test/index.test.js:140:13)

</details>

2021-09-02 08:30 UTC, timneutkens requested changes
Looks like this is breaking a bunch of tests.

2021-09-07 08:30 UTC, adrienharnay commented
Hi @timneutkens, indeed it does! I will investigate but have never touched this part of the code before, so any help would be appreciated :)

2021-09-07 09:18 UTC, adrienharnay commented
@timneutkens It seems I also needed to bump sass-loader to 10.2.0, which still supports Webpack@4, but also supports Node@16.
I ran some of the test suites that failed locally and they seem to pass know! Could you please approve the workflow to see if all the suites pass?
Thanks in advance :pray:

2021-09-07 10:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.2s | -186ms |
| buildDurationCached | 3.2s | 3.2s | ⚠️ +25ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.399 | 2.385 | -0.01 |
| / avg req/sec | 1042.11 | 1048.17 | +6.06 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.306 | 1.291 | -0.02 |
| /error-in-render avg req/sec | 1913.67 | 1936.69 | +23.02 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 541 B | 541 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 534 B | 534 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 10s | 10.1s | ⚠️ +111ms |
| buildDurationCached | 4.2s | 4.2s | -49ms |
| nodeModulesSize | 49.1 MB | 49.1 MB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.423 | 2.425 | 0 |
| / avg req/sec | 1031.9 | 1031.03 | ⚠️ -0.87 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.314 | 1.294 | -0.02 |
| /error-in-render avg req/sec | 1902.02 | 1932.26 | +30.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 596 B | 596 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: b0869b98057cb3415f8e88a47a8ffdfd86a32fd0

2021-09-07 10:49 UTC, ijjk commented
## Failing test suites <!--3700131680-->
Commit: b0869b98057cb3415f8e88a47a8ffdfd86a32fd0

**test/integration/next-dynamic-css/test/index.test.js** 
- next/dynamic > dev mode > should load page correctly
- next/dynamic > production mode > should load page correctly

<details>
<summary>Expand output</summary>

  ● next/dynamic › dev mode › should load page correctly

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"#__next div:nth-child(2)"}
      (Session info: headless chrome=92.0.4515.159)

      15 | let app
      16 | let appPort
    > 17 | const appDir = join(__dirname, '../')
         |                ^
      18 |
      19 | function runTests() {
      20 |   it('should load page correctly', async () => {

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/next-dynamic-css/test/index.test.js:17:16)

  ● next/dynamic › production mode › should load page correctly

    command failed with code 1

      177 |     })
      178 |   })
    > 179 | }
          |  ^
      180 |
      181 | export function runNextCommandDev(argv, stdOut, opts = {}) {
      182 |   const nextDir = path.dirname(require.resolve('next/package'))

      at ChildProcess.<anonymous> (lib/next-test-utils.js:179:31)

</details>

2021-09-07 12:20 UTC, timneutkens commented
I've updated the precompiled dependency (sass-loader), then the tests should pass 👍

2021-09-07 12:29 UTC, adrienharnay commented
Thank you! Could you please tell me how you did it? This way I will be able to do it myself next time :)

2021-09-07 12:32 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +230ms |
| buildDurationCached | 3.7s | 3.7s | ⚠️ +2ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.684 | 2.834 | ⚠️ +0.15 |
| / avg req/sec | 931.56 | 882.07 | ⚠️ -49.49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.518 | 1.594 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1647.33 | 1568.82 | ⚠️ -78.51 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 541 B | 541 B | ✓ |
| link.html gzip | 553 B | 553 B | ✓ |
| withRouter.html gzip | 534 B | 534 B | ✓ |
| Overall change | 1.63 kB | 1.63 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 11.9s | 11.4s | -441ms |
| buildDurationCached | 4.9s | 5.1s | ⚠️ +263ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.817 | 2.857 | ⚠️ +0.04 |
| / avg req/sec | 887.61 | 875 | ⚠️ -12.61 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.534 | 1.531 | 0 |
| /error-in-render avg req/sec | 1629.71 | 1632.93 | +3.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 596 B | 596 B | ✓ |
| withRouter.html gzip | 577 B | 577 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: ed3c042309cfd2b8041bd5423ba8b36922741fdd

2021-09-07 13:32 UTC, timneutkens commented
> Thank you! Could you please tell me how you did it? This way I will be able to do it myself next time :)

We generally run these ourselves to ensure there's no compilation difference 👍

2021-09-07 14:02 UTC, adrienharnay commented
I am under the impression the 2 remaining tests are not failing because of my changes. Can you confirm?

2021-09-08 15:06 UTC, timneutkens commented
Correct!

2021-09-08 15:06 UTC, timneutkens approved these changes
Thanks! This looks good to land now 👍

2021-09-08 15:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 11.8s | 11.9s | ⚠️ +52ms |
| buildDurationCached | 3.1s | 3s | -86ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.09 | 2.339 | ⚠️ +0.25 |
| / avg req/sec | 1196.14 | 1069.06 | ⚠️ -127.08 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.126 | 1.255 | ⚠️ +0.13 |
| /error-in-render avg req/sec | 2220.17 | 1991.76 | ⚠️ -228.41 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 9.6s | 9.5s | -138ms |
| buildDurationCached | 4s | 4.1s | ⚠️ +65ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.379 | 2.415 | ⚠️ +0.04 |
| / avg req/sec | 1050.88 | 1035.01 | ⚠️ -15.87 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.27 | 1.256 | -0.01 |
| /error-in-render avg req/sec | 1968.53 | 1990.02 | +21.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: b36e82341e5a1fd7f33c5596cc9fc02d81045360

2021-09-08 17:17 UTC, ijjk commented
## Failing test suites <!--3715462368-->
Commit: bc7ffb789b7bff1f163e2d31ecb24d7ef1ec5a3d

**test/integration/config-devtool-dev/test/index.test.js** 
- devtool set in development mode in next config > should warn and revert when a devtool is set in development mode

<details>
<summary>Expand output</summary>

  ● devtool set in development mode in next config › should warn and revert when a devtool is set in development mode

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      11 | import webdriver from 'next-webdriver'
      12 | import { join } from 'path'
    > 13 |
         | ^
      14 | jest.setTimeout(1000 * 30)
      15 |
      16 | const appDir = join(__dirname, '../')

      at integration/config-devtool-dev/test/index.test.js:13:5
      at Object.<anonymous> (integration/config-devtool-dev/test/index.test.js:12:1)

</details>

2021-09-08 17:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +167ms |
| buildDurationCached | 3.6s | 3.6s | -73ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.761 | 2.804 | ⚠️ +0.04 |
| / avg req/sec | 905.32 | 891.62 | ⚠️ -13.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.499 | 1.482 | -0.02 |
| /error-in-render avg req/sec | 1667.43 | 1687.38 | +19.95 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 745.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 23.3 kB | 23.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 67.2 kB | 67.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 979 B | 979 B | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 329 B | 329 B | ✓ |
| dynamic-HASH.js gzip | 2.67 kB | 2.67 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 4.14 kB | 4.14 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ✓ |
| routerDirect..HASH.js gzip | 318 B | 318 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 320 B | 320 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 13 kB | 13 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 539 B | 539 B | ✓ |
| link.html gzip | 552 B | 552 B | ✓ |
| withRouter.html gzip | 533 B | 533 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Webpack 4 Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 11.6s | ⚠️ +1ms |
| buildDurationCached | 4.8s | 4.8s | -15ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +277 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.797 | 2.781 | -0.02 |
| / avg req/sec | 893.88 | 898.8 | +4.92 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.497 | 1.517 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1670.45 | 1647.55 | ⚠️ -22.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| 16.HASH.js gzip | 186 B | 186 B | ✓ |
| 677f882d2ed8..HASH.js gzip | 14.1 kB | 14.1 kB | ✓ |
| framework.HASH.js gzip | 41.9 kB | 41.9 kB | ✓ |
| main-HASH.js gzip | 10.7 kB | 10.7 kB | ✓ |
| webpack-HASH.js gzip | 1.19 kB | 1.19 kB | ✓ |
| Overall change | 68.1 kB | 68.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 964 B | 964 B | ✓ |
| _error-HASH.js gzip | 3.8 kB | 3.8 kB | ✓ |
| amp-HASH.js gzip | 552 B | 552 B | ✓ |
| css-HASH.js gzip | 333 B | 333 B | ✓ |
| dynamic-HASH.js gzip | 2.87 kB | 2.87 kB | ✓ |
| head-HASH.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks-HASH.js gzip | 924 B | 924 B | ✓ |
| index-HASH.js gzip | 231 B | 231 B | ✓ |
| link-HASH.js gzip | 1.64 kB | 1.64 kB | ✓ |
| routerDirect..HASH.js gzip | 298 B | 298 B | ✓ |
| script-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| withRouter-HASH.js gzip | 295 B | 295 B | ✓ |
| 30809af5c834..565.css gzip | 125 B | 125 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 500 B | 500 B | ✓ |
| Overall change | 500 B | 500 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | adrienharnay/next.js feat/support-node-sass-6 | Change |
| - | - | - | - |
| index.html gzip | 585 B | 585 B | ✓ |
| link.html gzip | 597 B | 597 B | ✓ |
| withRouter.html gzip | 578 B | 578 B | ✓ |
| Overall change | 1.76 kB | 1.76 kB | ✓ |

</details>

</details>
Commit: bc7ffb789b7bff1f163e2d31ecb24d7ef1ec5a3d

2021-09-09 09:00 UTC, merged

2022-01-25 22:23 UTC, seve commented
I can't seem to find this commit on [v11.1.3](https://github.com/vercel/next.js/releases/v11.1.3).  Was this PR purposefully omitted from the [v12.0.1 backport](https://github.com/vercel/next.js/releases/v12.0.5)? The release notes are a bit vague, but looking deeper into it, it looks like only #32092 is featured in 11.1.3.

In order to get node v16 support is an update to at least 12.0.5?

2022-02-10 11:17 UTC, balazsorban44 commented
Please see https://github.com/vercel/next.js/issues/34139#issuecomment-1034290706