Enable SWC by default when there is no custom Babel config
vercel/next.js pull request #29811
Opened 2021-10-11 13:12 UTC by timneutkens

Enables `next-swc-loader` by default which leverages `next-swc` to compile individual JavaScript and TypeScript files. Opt-out is automatic when custom Babel configuration is found, it will fall back to the existing Babel setup so there's no difference there when you have a custom Babel configuration (fully backwards compatible).

`next-swc` is a custom compiled version of SWC that is built based on the Rust crates for SWC. It includes Next.js-specific transforms like styled-jsx and tree shaking of data fetching methods that allow you to use server-only dependencies in `getStaticProps`/`getServerSideProps`.

~The last transform for AMP support is currently being ported by @padmaia~ (Complete)

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [x] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

2021-10-13 16:58 UTC, styfle submitted a review, later dismissed

2021-10-17 11:47 UTC, ijjk commented
## Failing test suites <!--4076123541-->
Commit: 25ff27beb6e6295791e21f1fdc92fc61e1871028

**test/integration/custom-error/test/index.test.js** 
- Custom _error > dev mode 1 > should not warn with /_error and /404 when rendering error first

<details>
<summary>Expand output</summary>

  ● Custom _error › dev mode 1 › should not warn with /_error and /404 when rendering error first

    expect(received).toContain(expected) // indexOf

    Expected substring: "Syntax error"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1634471203790\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1634471203790\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1634471203790\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1634471203790\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1634471203790\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1634471203790\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleBuildError\",\"message\":\"Module build failed (from ../../../packages/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError: error: Unexpected eof\\n --\\u003e /home/runner/work/next.js/next.js/test/integration/custom-error/pages/404.js:1:20\\n  |\\n1 | export default \\u003ch1\\u003e\\n  |                    ^\\n\\n\\n\\nCaused by:\\n    0: failed to process js file\\n    1: failed to parse module\",\"stack\":\"ModuleBuildError: Module build failed (from ../../../packages/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError: error: Unexpected eof\\n --\\u003e /home/runner/work/next.js/next.js/test/integration/custom-error/pages/404.js:1:20\\n  |\\n1 | export default \\u003ch1\\u003e\\n  |                    ^\\n\\n\\n\\nCaused by:\\n    0: failed to process js file\\n    1: failed to parse module\\n    at processResult (/home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:53004:19)\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:53105:5\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:138253:11\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:138105:18\\n    at context.callback (/home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:137978:13)\\n    at /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/loaders/next-swc-loader.js:118:9\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      47 |       const html = await renderViaHTTP(appPort, '/404')
      48 |       await fs.remove(page404)
    > 49 |       expect(html).toContain('Syntax error')
         |                    ^
      50 |       expect(stderr).not.toMatch(customErrNo404Match)
      51 |     })
      52 |   })

      at Object.<anonymous> (integration/custom-error/test/index.test.js:49:20)

</details>

2021-10-17 11:51 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 18.7s | 13.3s | -5.5s |
| buildDurationCached | 3.8s | 4s | ⚠️ +227ms |
| nodeModulesSize | 198 MB | 198 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.347 | 4.259 | -0.09 |
| / avg req/sec | 575.12 | 586.97 | +11.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.287 | 2.402 | ⚠️ +0.12 |
| /error-in-render avg req/sec | 1093.27 | 1040.8 | ⚠️ -52.47 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | N/A | N/A |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 26.7 kB | ⚠️ +1.78 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.52 kB | ⚠️ +31 B |
| 675-HASH.js gzip | N/A | 10.8 kB | N/A |
| Overall change | 71.9 kB | 81.4 kB | ⚠️ +9.56 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 1.23 kB | ⚠️ +252 B |
| _error-HASH.js gzip | 3.11 kB | 195 B | -2.92 kB |
| amp-HASH.js gzip | 553 B | 312 B | -241 B |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.73 kB | 2.44 kB | -285 B |
| head-HASH.js gzip | 2.37 kB | 351 B | -2.02 kB |
| hooks-HASH.js gzip | 918 B | 633 B | -285 B |
| image-HASH.js gzip | 5.86 kB | 558 B | -5.3 kB |
| index-HASH.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-HASH.js gzip | 1.66 kB | 1.88 kB | ⚠️ +218 B |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 385 B | -1 B |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 9.34 kB | -10.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 490 B | 513 B | ⚠️ +23 B |
| Overall change | 490 B | 513 B | ⚠️ +23 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 538 B | 538 B | ✓ |
| link.html gzip | 550 B | 551 B | ⚠️ +1 B |
| withRouter.html gzip | 531 B | 531 B | ✓ |
| Overall change | 1.62 kB | 1.62 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,34 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-62b6d914325f07931441.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-5465a03ec8001cf52192.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-76b1d1cad2fa670990e7.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-971c9d7976475fd8ecd9.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-d9d56e14336c2d5493ff.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-ac328e77dde10022dc84.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-7fa8f6299881aeef4d92.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-3a3f2ee26479962d56c1.js"
+    "static\u002Fchunks\u002F675-9c6edfe56b83ffcb92d8.js",
+    "static\u002Fchunks\u002Fpages\u002Fimage-24dfc0766459a85ca885.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d5bdd3af9bbbd881abda.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0c3a69578ed98df5d7be.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-11366980389598d0fd29.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-7faf010ab7dedd43f8cc.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,54 +1,115 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 915: /***/ function(
       __unused_webpack_module,
-      exports,
+      __unused_webpack_exports,
       __webpack_require__
     ) {
-      "use strict";
-
-      var _classCallCheck = __webpack_require__(4575);
-
-      var _createClass = __webpack_require__(3913);
-
-      var _inherits = __webpack_require__(2205);
-
-      var _possibleConstructorReturn = __webpack_require__(8585);
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(4596);
+        }
+      ]);
+      if (false) {
+      }
 
-      var _getPrototypeOf = __webpack_require__(9754);
+      /***/
+    },
 
-      var _regeneratorRuntime = __webpack_require__(7757);
+    /***/ 4596: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
 
-      function _createSuper(Derived) {
-        var hasNativeReflectConstruct = _isNativeReflectConstruct();
-        return function _createSuperInternal() {
-          var Super = _getPrototypeOf(Derived),
-            result;
-          if (hasNativeReflectConstruct) {
-            var NewTarget = _getPrototypeOf(this).constructor;
-            result = Reflect.construct(Super, arguments, NewTarget);
-          } else {
-            result = Super.apply(this, arguments);
-          }
-          return _possibleConstructorReturn(this, result);
-        };
+      var _regeneratorRuntime = _interopRequireDefault1(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
       }
-
-      function _isNativeReflectConstruct() {
-        if (typeof Reflect === "undefined" || !Reflect.construct) return false;
-        if (Reflect.construct.sham) return false;
-        if (typeof Proxy === "funct [...]

2021-10-18 09:24 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 14.7s | 10.7s | -3.9s |
| buildDurationCached | 3.6s | 3.4s | -167ms |
| nodeModulesSize | 194 MB | 194 MB | -16 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.683 | 3.551 | -0.13 |
| / avg req/sec | 678.7 | 704.07 | +25.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.892 | 1.839 | -0.05 |
| /error-in-render avg req/sec | 1321.41 | 1359.63 | +38.22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | N/A | N/A |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 26.7 kB | ⚠️ +1.78 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.52 kB | ⚠️ +31 B |
| 675-HASH.js gzip | N/A | 10.8 kB | N/A |
| Overall change | 71.9 kB | 81.4 kB | ⚠️ +9.57 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 1.23 kB | ⚠️ +252 B |
| _error-HASH.js gzip | 3.11 kB | 195 B | -2.92 kB |
| amp-HASH.js gzip | 553 B | 312 B | -241 B |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.73 kB | 2.44 kB | -285 B |
| head-HASH.js gzip | 2.37 kB | 351 B | -2.02 kB |
| hooks-HASH.js gzip | 918 B | 633 B | -285 B |
| image-HASH.js gzip | 5.86 kB | 558 B | -5.3 kB |
| index-HASH.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-HASH.js gzip | 1.66 kB | 1.88 kB | ⚠️ +218 B |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 385 B | -1 B |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 9.34 kB | -10.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 490 B | 513 B | ⚠️ +23 B |
| Overall change | 490 B | 513 B | ⚠️ +23 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 539 B | 537 B | -2 B |
| link.html gzip | 551 B | 551 B | ✓ |
| withRouter.html gzip | 533 B | 531 B | -2 B |
| Overall change | 1.62 kB | 1.62 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,34 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-62b6d914325f07931441.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-5465a03ec8001cf52192.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-76b1d1cad2fa670990e7.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-971c9d7976475fd8ecd9.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-d9d56e14336c2d5493ff.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-ac328e77dde10022dc84.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-7fa8f6299881aeef4d92.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-3a3f2ee26479962d56c1.js"
+    "static\u002Fchunks\u002F675-9c6edfe56b83ffcb92d8.js",
+    "static\u002Fchunks\u002Fpages\u002Fimage-24dfc0766459a85ca885.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d5bdd3af9bbbd881abda.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0c3a69578ed98df5d7be.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-11366980389598d0fd29.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-7faf010ab7dedd43f8cc.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,54 +1,115 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 915: /***/ function(
       __unused_webpack_module,
-      exports,
+      __unused_webpack_exports,
       __webpack_require__
     ) {
-      "use strict";
-
-      var _classCallCheck = __webpack_require__(4575);
-
-      var _createClass = __webpack_require__(3913);
-
-      var _inherits = __webpack_require__(2205);
-
-      var _possibleConstructorReturn = __webpack_require__(8585);
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(4596);
+        }
+      ]);
+      if (false) {
+      }
 
-      var _getPrototypeOf = __webpack_require__(9754);
+      /***/
+    },
 
-      var _regeneratorRuntime = __webpack_require__(7757);
+    /***/ 4596: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
 
-      function _createSuper(Derived) {
-        var hasNativeReflectConstruct = _isNativeReflectConstruct();
-        return function _createSuperInternal() {
-          var Super = _getPrototypeOf(Derived),
-            result;
-          if (hasNativeReflectConstruct) {
-            var NewTarget = _getPrototypeOf(this).constructor;
-            result = Reflect.construct(Super, arguments, NewTarget);
-          } else {
-            result = Super.apply(this, arguments);
-          }
-          return _possibleConstructorReturn(this, result);
-        };
+      var _regeneratorRuntime = _interopRequireDefault1(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
       }
-
-      function _isNativeReflectConstruct() {
-        if (typeof Reflect === "undefined" || !Reflect.construct) return false;
-        if (Reflect.construct.sham) return false;
-        if (typeof Proxy [...]

2021-10-18 14:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 17.8s | 12.6s | -5.3s |
| buildDurationCached | 4.1s | 4s | -84ms |
| nodeModulesSize | 195 MB | 195 MB | -9 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.12 | 4.14 | ⚠️ +0.02 |
| / avg req/sec | 606.77 | 603.82 | ⚠️ -2.95 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.11 | 2.071 | -0.04 |
| /error-in-render avg req/sec | 1184.6 | 1207.17 | +22.57 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | N/A | N/A |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 26.8 kB | ⚠️ +1.79 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.52 kB | ⚠️ +31 B |
| 675-HASH.js gzip | N/A | 10.8 kB | N/A |
| Overall change | 71.9 kB | 81.4 kB | ⚠️ +9.57 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 1.23 kB | ⚠️ +252 B |
| _error-HASH.js gzip | 3.11 kB | 195 B | -2.92 kB |
| amp-HASH.js gzip | 553 B | 312 B | -241 B |
| css-HASH.js gzip | 328 B | 328 B | ✓ |
| dynamic-HASH.js gzip | 2.73 kB | 2.44 kB | -285 B |
| head-HASH.js gzip | 2.37 kB | 351 B | -2.02 kB |
| hooks-HASH.js gzip | 918 B | 633 B | -285 B |
| image-HASH.js gzip | 5.86 kB | 558 B | -5.3 kB |
| index-HASH.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-HASH.js gzip | 1.66 kB | 1.88 kB | ⚠️ +218 B |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 386 B | 385 B | -1 B |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 9.34 kB | -10.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 490 B | 513 B | ⚠️ +23 B |
| Overall change | 490 B | 513 B | ⚠️ +23 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 539 B | 536 B | -3 B |
| link.html gzip | 551 B | 550 B | -1 B |
| withRouter.html gzip | 533 B | 530 B | -3 B |
| Overall change | 1.62 kB | 1.62 kB | -7 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,34 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-62b6d914325f07931441.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-5465a03ec8001cf52192.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-76b1d1cad2fa670990e7.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-971c9d7976475fd8ecd9.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-d9d56e14336c2d5493ff.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-ac328e77dde10022dc84.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-7fa8f6299881aeef4d92.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-3a3f2ee26479962d56c1.js"
+    "static\u002Fchunks\u002F675-9c6edfe56b83ffcb92d8.js",
+    "static\u002Fchunks\u002Fpages\u002Fimage-24dfc0766459a85ca885.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-d5bdd3af9bbbd881abda.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0c3a69578ed98df5d7be.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-11366980389598d0fd29.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-7faf010ab7dedd43f8cc.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,54 +1,115 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 915: /***/ function(
       __unused_webpack_module,
-      exports,
+      __unused_webpack_exports,
       __webpack_require__
     ) {
-      "use strict";
-
-      var _classCallCheck = __webpack_require__(4575);
-
-      var _createClass = __webpack_require__(3913);
-
-      var _inherits = __webpack_require__(2205);
-
-      var _possibleConstructorReturn = __webpack_require__(8585);
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(4596);
+        }
+      ]);
+      if (false) {
+      }
 
-      var _getPrototypeOf = __webpack_require__(9754);
+      /***/
+    },
 
-      var _regeneratorRuntime = __webpack_require__(7757);
+    /***/ 4596: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
 
-      function _createSuper(Derived) {
-        var hasNativeReflectConstruct = _isNativeReflectConstruct();
-        return function _createSuperInternal() {
-          var Super = _getPrototypeOf(Derived),
-            result;
-          if (hasNativeReflectConstruct) {
-            var NewTarget = _getPrototypeOf(this).constructor;
-            result = Reflect.construct(Super, arguments, NewTarget);
-          } else {
-            result = Super.apply(this, arguments);
-          }
-          return _possibleConstructorReturn(this, result);
-        };
+      var _regeneratorRuntime = _interopRequireDefault1(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
       }
-
-      function _isNativeReflectConstruct() {
-        if (typeof Reflect === "undefined" || !Reflect.construct) return false;
-        if (Reflect.construct.sham) return false;
-        if (typeof Prox [...]

2021-10-18 20:08 UTC, ijjk commented
## Failing test suites <!--4088487346-->
Commit: 7c2ff41ceee96ce2b56a56dbf9096d2c959f7004

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should detect syntax errors and recover
- basic HMR > Error Recovery > should show the error on all pages
- basic HMR > Error Recovery > should recover after undefined exported as default
- basic HMR > Error Recovery > should recover after an error reported via SSR
- basic HMR > Hot Module Reloading > editing a page > should update styles in a dynamic component correctly

<details>
<summary>Expand output</summary>

  ● basic HMR › Hot Module Reloading › editing a page › should update styles in a dynamic component correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      265 |
      266 |           expect(editedFontSize).toBe('200px')
    > 267 |           expect(browserHtml.includes('font-size:200px;')).toBe(true)
          |                                                            ^
      268 |           expect(browserHtml.includes('font-size:100px;')).toBe(false)
      269 |
      270 |           const editedHtml = await renderViaHTTP(

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:267:60)

  ● basic HMR › Error Recovery › should detect syntax errors and recover

    expect(received).toMatch(expected)

    Expected pattern: /Unterminated JSX contents/
    Received string:  "./pages/hmr/about2.js
    Error: error: Unexpected eof
     --> /tmp/next-test-1634587588365-590/pages/hmr/about2.js:7:3
      |
    7 | }
      |   ^·
    Caused by:
        0: failed to process js file
        1: failed to parse module"

      342 |
      343 |         expect(await hasRedbox(browser)).toBe(true)
    > 344 |         expect(await getRedboxSource(browser)).toMatch(
          |                                                ^
      345 |           /Unterminated JSX contents/
      346 |         )
      347 |

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:344:48)

  ● basic HMR › Error Recovery › should show the error on all pages

    expect(received).toMatch(expected)

    Expected pattern: /Unterminated JSX contents/
    Received string:  "./pages/hmr/about2.js
    Error: error: Unexpected eof
     --> /tmp/next-test-1634587588365-590/pages/hmr/about2.js:7:3
      |
    7 | }
      |   ^·
    Caused by:
        0: failed to process js file
        1: failed to parse module"

      381 |
      382 |         expect(await hasRedbox(browser)).toBe(true)
    > 383 |         expect(await getRedboxSource(browser)).toMatch(
          |                                                ^
      384 |           /Unterminated JSX contents/
      385 |         )
      386 |

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:383:48)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      603 |         await next.patchFile(aboutPage, aboutContent)
      604 |
    > 605 |         if (browser) {
          |                       ^
      606 |           await check(
      607 |             () => getBrowserBodyText(browser),
      608 |             /This is the about page/

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:605:23)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    TIMED OUT: /an-expected-error-in-gip/

    null

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:495:17)

</details>

2021-10-19 15:34 UTC, ijjk commented
## Failing test suites <!--4097944464-->
Commit: cdb5bf432e7fd65569f80abfcfdc5f4701e9c2b1

**test/integration/custom-error/test/index.test.js** 
- Custom _error > dev mode 1 > should not warn with /_error and /404 when rendering error first

<details>
<summary>Expand output</summary>

  ● Custom _error › dev mode 1 › should not warn with /_error and /404 when rendering error first

    expect(received).toContain(expected) // indexOf

    Expected substring: "Syntax error"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"next-head-count\" content=\"2\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1634657619902\"></script><script src=\"/_next/static/chunks/fallback/webpack.js?ts=1634657619902\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/main.js?ts=1634657619902\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_app.js?ts=1634657619902\" defer=\"\"></script><script src=\"/_next/static/chunks/fallback/pages/_error.js?ts=1634657619902\" defer=\"\"></script><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"></div><script src=\"/_next/static/chunks/fallback/react-refresh.js?ts=1634657619902\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":500}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"ModuleBuildError\",\"message\":\"Module build failed (from ../../../packages/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError: error: Unexpected eof\\n --\\u003e /home/runner/work/next.js/next.js/test/integration/custom-error/pages/404.js:1:20\\n  |\\n1 | export default \\u003ch1\\u003e\\n  |                    ^\\n\\n\\n\\nCaused by:\\n    0: failed to process js file\\n    1: Syntax Error\",\"stack\":\"ModuleBuildError: Module build failed (from ../../../packages/next/dist/build/webpack/loaders/next-swc-loader.js):\\nError: error: Unexpected eof\\n --\\u003e /home/runner/work/next.js/next.js/test/integration/custom-error/pages/404.js:1:20\\n  |\\n1 | export default \\u003ch1\\u003e\\n  |                    ^\\n\\n\\n\\nCaused by:\\n    0: failed to process js file\\n    1: Syntax Error\\n    at processResult (/home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:53004:19)\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:53105:5\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:138253:11\\n    at /home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:138105:18\\n    at context.callback (/home/runner/work/next.js/next.js/packages/next/dist/compiled/webpack/bundle5.js:137978:13)\\n    at /home/runner/work/next.js/next.js/packages/next/dist/build/webpack/loaders/next-swc-loader.js:118:9\"},\"gip\":true,\"scriptLoader\":[]}</script></body></html>"

      47 |       const html = await renderViaHTTP(appPort, '/404')
      48 |       await fs.remove(page404)
    > 49 |       expect(html).toContain('Syntax error')
         |                    ^
      50 |       expect(stderr).not.toMatch(customErrNo404Match)
      51 |     })
      52 |   })

      at Object.<anonymous> (integration/custom-error/test/index.test.js:49:20)

</details>

2021-10-20 06:22 UTC, timneutkens commented
Current failing suites as per @ijjk's changes:

```
test/integration/typeof-window-replace/test/index.test.js
test/integration/custom-error/test/index.test.js
test/integration/pnpm-support/test/index.test.js
test/integration/auto-export/test/index.test.js
test/integration/router-is-ready/test/index.test.js
```

2021-10-21 11:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 12.7s | 8.8s | -3.9s |
| buildDurationCached | 3s | 2.8s | -126ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +437 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.888 | 2.852 | -0.04 |
| / avg req/sec | 865.72 | 876.48 | +10.76 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.387 | 1.371 | -0.02 |
| /error-in-render avg req/sec | 1801.97 | 1823.8 | +21.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | N/A | N/A |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-a993820..123b.js gzip | 26.1 kB | N/A | N/A |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.45 kB | -29 B |
| main-7a86f05..5e87.js gzip | N/A | 27.8 kB | N/A |
| Overall change | 73 kB | 71.7 kB | -1.31 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | N/A | N/A |
| _error-d828d..2954.js gzip | 3.06 kB | N/A | N/A |
| amp-5388d1f5..4ce9.js gzip | 551 B | N/A | N/A |
| css-10424225..367a.js gzip | 329 B | 327 B | -2 B |
| dynamic-9821..3cd4.js gzip | 2.67 kB | N/A | N/A |
| head-1df323b..d261.js gzip | 2.32 kB | N/A | N/A |
| hooks-ab0016..b093.js gzip | 917 B | N/A | N/A |
| image-c3cc30..4e2a.js gzip | 5.87 kB | N/A | N/A |
| index-95c8cb..6970.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-05c99e7..35ec.js gzip | 1.66 kB | N/A | N/A |
| routerDirect..6659.js gzip | 319 B | 321 B | ⚠️ +2 B |
| script-d94ba..ed05.js gzip | 386 B | 383 B | -3 B |
| withRouter-7..8b2e.js gzip | 317 B | 318 B | ⚠️ +1 B |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| _app-e2cfdd4..f20e.js gzip | N/A | 1.23 kB | N/A |
| _error-6679c..c50e.js gzip | N/A | 194 B | N/A |
| amp-e55eb6be..a860.js gzip | N/A | 312 B | N/A |
| dynamic-3814..830e.js gzip | N/A | 2.38 kB | N/A |
| head-0b292cc..7d7c.js gzip | N/A | 350 B | N/A |
| hooks-a534e8..efa1.js gzip | N/A | 635 B | N/A |
| image-258b59..8ae1.js gzip | N/A | 4.45 kB | N/A |
| link-a8a0a12..1f88.js gzip | N/A | 1.87 kB | N/A |
| Overall change | 19.8 kB | 13.2 kB | -6.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 459 B | ⚠️ +1 B |
| Overall change | 458 B | 459 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 538 B | 535 B | -3 B |
| link.html gzip | 549 B | 547 B | -2 B |
| withRouter.html gzip | 530 B | 527 B | -3 B |
| Overall change | 1.62 kB | 1.61 kB | -8 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-843adaf946d87644.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c781952f352e4219.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b11421da95e6cd65.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
   "/css": [
     "static\u002Fcss\u002Fb05d9375ec06fe1b.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-3082f38ec4aa6063.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-99ad492aad2c14e4.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-e9949e65f81038fb.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-a9a93d991a2a6a9c.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-e040764724fe6a41.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a4027db8f96167d6.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-f632234727179322.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-ace0158746a527c7.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-df7921033b292f8a.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c65470edc1e9d9b6.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-070ef9975918e033.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-3ab6a24eae9d4d66.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app-de3f211ea2b76ae1.js</strong></summary>

```diff
@@ -0,0 +1,268 @@
+(self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
+  [888],
+  {
+    /***/ 915: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6029: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
+
+      var _regeneratorRuntime = _interopRequireDefault(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
+      }
+      function _classCallCheck(instance, Constructor) {
+        if (!(instance instanceof Constructor)) {
+          throw new TypeError("Cannot call a class as a function");
+        }
+      }
+      function _defineProperties(target, props) {
+        for (var i = 0; i < props.length; i++) {
+          var descriptor = props[i];
+          descriptor.enumerable = descriptor.enumerable || false;
+          descriptor.configurable = true;
+          if ("value" in descriptor) descriptor.writable = true;
+          Object.defineProperty(target, descriptor.key, descriptor);
+        }
+      }
+      function _createClass(Constructor, protoProps, staticProps) {
+        if (protoProps) _defineProperties(Construc [...]

2021-10-21 12:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 17.2s | 11.6s | -5.6s |
| buildDurationCached | 3.7s | 3.6s | -96ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +451 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.017 | 4.261 | ⚠️ +0.24 |
| / avg req/sec | 622.3 | 586.75 | ⚠️ -35.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.247 | 2.346 | ⚠️ +0.1 |
| /error-in-render avg req/sec | 1112.64 | 1065.63 | ⚠️ -47.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | N/A | N/A |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-a993820..123b.js gzip | 26.1 kB | N/A | N/A |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.45 kB | -29 B |
| main-7a86f05..5e87.js gzip | N/A | 27.8 kB | N/A |
| Overall change | 73 kB | 71.7 kB | -1.31 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | N/A | N/A |
| _error-d828d..2954.js gzip | 3.06 kB | N/A | N/A |
| amp-5388d1f5..4ce9.js gzip | 551 B | N/A | N/A |
| css-10424225..367a.js gzip | 329 B | 327 B | -2 B |
| dynamic-9821..3cd4.js gzip | 2.67 kB | N/A | N/A |
| head-1df323b..d261.js gzip | 2.32 kB | N/A | N/A |
| hooks-ab0016..b093.js gzip | 917 B | N/A | N/A |
| image-c3cc30..4e2a.js gzip | 5.87 kB | N/A | N/A |
| index-95c8cb..6970.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-05c99e7..35ec.js gzip | 1.66 kB | N/A | N/A |
| routerDirect..6659.js gzip | 319 B | 321 B | ⚠️ +2 B |
| script-d94ba..ed05.js gzip | 386 B | 383 B | -3 B |
| withRouter-7..8b2e.js gzip | 317 B | 318 B | ⚠️ +1 B |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| _app-e2cfdd4..f20e.js gzip | N/A | 1.23 kB | N/A |
| _error-6679c..c50e.js gzip | N/A | 194 B | N/A |
| amp-e55eb6be..a860.js gzip | N/A | 312 B | N/A |
| dynamic-3814..830e.js gzip | N/A | 2.38 kB | N/A |
| head-0b292cc..7d7c.js gzip | N/A | 350 B | N/A |
| hooks-a534e8..efa1.js gzip | N/A | 635 B | N/A |
| image-258b59..8ae1.js gzip | N/A | 4.45 kB | N/A |
| link-a8a0a12..1f88.js gzip | N/A | 1.87 kB | N/A |
| Overall change | 19.8 kB | 13.2 kB | -6.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 459 B | ⚠️ +1 B |
| Overall change | 458 B | 459 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 538 B | 535 B | -3 B |
| link.html gzip | 549 B | 547 B | -2 B |
| withRouter.html gzip | 530 B | 527 B | -3 B |
| Overall change | 1.62 kB | 1.61 kB | -8 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-843adaf946d87644.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c781952f352e4219.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b11421da95e6cd65.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
   "/css": [
     "static\u002Fcss\u002Fb05d9375ec06fe1b.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-3082f38ec4aa6063.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-99ad492aad2c14e4.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-e9949e65f81038fb.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-a9a93d991a2a6a9c.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-e040764724fe6a41.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a4027db8f96167d6.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-f632234727179322.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-ace0158746a527c7.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-df7921033b292f8a.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c65470edc1e9d9b6.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-070ef9975918e033.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-3ab6a24eae9d4d66.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app-de3f211ea2b76ae1.js</strong></summary>

```diff
@@ -0,0 +1,268 @@
+(self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
+  [888],
+  {
+    /***/ 915: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6029: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
+
+      var _regeneratorRuntime = _interopRequireDefault(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
+      }
+      function _classCallCheck(instance, Constructor) {
+        if (!(instance instanceof Constructor)) {
+          throw new TypeError("Cannot call a class as a function");
+        }
+      }
+      function _defineProperties(target, props) {
+        for (var i = 0; i < props.length; i++) {
+          var descriptor = props[i];
+          descriptor.enumerable = descriptor.enumerable || false;
+          descriptor.configurable = true;
+          if ("value" in descriptor) descriptor.writable = true;
+          Object.defineProperty(target, descriptor.key, descriptor);
+        }
+      }
+      function _createClass(Constructor, protoProps, staticProps) {
+        if (protoProps) _defineProper [...]

2021-10-21 12:45 UTC, ijjk commented
## Failing test suites <!--4120068971-->
Commit: 916e8714d7e3c7ed4b48085ff86ccbbb9a0105d2

**test/integration/pnpm-support/test/index.test.js** 
- pnpm support > should build with dependencies installed via pnpm

<details>
<summary>Expand output</summary>

  ● pnpm support › should build with dependencies installed via pnpm

    Command failed with exit code 1 (EPERM): /home/runner/work/next.js/next.js/node_modules/.bin/pnpm run build

      21 | const runPnpm = async (cwd, ...args) => {
      22 |   try {
    > 23 |     const result = await execa(pnpmExecutable, [...args], { cwd })
         |                    ^
      24 |     return result
      25 |   } catch (err) {
      26 |     console.log({ stdout: err.stdout, stderr: err.stderr })

      at makeError (../node_modules/execa/lib/error.js:58:11)
      at handlePromise (../node_modules/execa/index.js:112:26)
      at runPnpm (integration/pnpm-support/test/index.test.js:23:20)
      at integration/pnpm-support/test/index.test.js:140:34
      at usingTempDir (integration/pnpm-support/test/index.test.js:35:12)
      at Object.<anonymous> (integration/pnpm-support/test/index.test.js:97:5)

</details>

2021-10-21 12:47 UTC, ijjk commented
## Failing test suites <!--4120068971-->
Commit: 916e8714d7e3c7ed4b48085ff86ccbbb9a0105d2

**test/integration/next-dynamic-css/test/index.test.js** 
- next/dynamic > dev mode > should load page correctly

<details>
<summary>Expand output</summary>

  ● next/dynamic › dev mode › should load page correctly

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#__next div:nth-child(2)"
    ============================================================

      201 |     return this.chain(() => {
      202 |       return page
    > 203 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      204 |         .then(async (el) => {
      205 |           // it seems selenium waits longer and tests rely on this behavior
      206 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:203:10

</details>

2021-10-21 20:22 UTC, ijjk commented
## Failing test suites <!--4125071625-->
Commit: c5d68d973ffaeb4d6bd9c7d637d8291d1ae27d3f

**test/integration/auto-export/test/index.test.js** 
- Auto Export > dev > Refreshes query on mount

<details>
<summary>Expand output</summary>

  ● Auto Export › dev › Refreshes query on mount

    expect(received).toMatch(expected)

    Expected pattern: /post.*post-1/
    Received string:  "<div id=\"__next\"><p>post: </p></div><script src=\"/_next/static/chunks/react-refresh.js?ts=1634847736742\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/[post]\",\"query\":{},\"buildId\":\"development\",\"nextExport\":true,\"autoExport\":true,\"isFallback\":false,\"scriptLoader\":[]}</script><div id=\"__next-build-watcher\" style=\"position: fixed; bottom: 10px; right: 20px; width: 0px; height: 0px; z-index: 99999;\"></div><next-route-announcer><p aria-live=\"assertive\" id=\"__next-route-announcer__\" role=\"alert\" style=\"border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; width: 1px; white-space: nowrap; overflow-wrap: normal;\"></p></next-route-announcer>"

      35 |     const browser = await webdriver(appPort, '/post-1')
      36 |     const html = await browser.eval('document.body.innerHTML')
    > 37 |     expect(html).toMatch(/post.*post-1/)
         |                  ^
      38 |     expect(html).toMatch(/nextExport/)
      39 |   })
      40 |

      at Object.<anonymous> (integration/auto-export/test/index.test.js:37:18)

</details>

2021-10-21 23:23 UTC, ijjk commented
## Failing test suites <!--4126459160-->
Commit: 54e5cc5bcf02aed8f756ee823fb8b38b29a863a6

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover from errors in the render function
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:424:9)

  ● basic HMR › Error Recovery › should recover from errors in the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:454:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:509:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:613:8)

</details>

2021-10-22 01:39 UTC, ijjk commented
## Failing test suites <!--4127254943-->
Commit: afe22a17141edd4a6ece5fbdd900fa97a31a4920

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Error Recovery > should recover from errors in the render function
- basic HMR > Error Recovery > should recover after undefined exported as default

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should recover from errors in the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:454:9)

  ● basic HMR › Error Recovery › should recover after undefined exported as default

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after undefined exported as default 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about7"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      599 |         await next.patchFile(aboutPage, aboutContent)
      600 |
    > 601 |         if (browser) {
          |                       ^
      602 |           await check(
      603 |             () => getBrowserBodyText(browser),
      604 |             /This is the about page/

      at Object.<anonymous> (development/basic-basepath/hmr.test.ts:601:23)

</details>

2021-10-22 01:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 15.8s | 10s | -5.8s |
| buildDurationCached | 3.4s | 3.2s | -195ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +437 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.532 | 3.691 | ⚠️ +0.16 |
| / avg req/sec | 707.8 | 677.31 | ⚠️ -30.49 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.873 | 2.029 | ⚠️ +0.16 |
| /error-in-render avg req/sec | 1334.84 | 1232.05 | ⚠️ -102.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | N/A | N/A |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-2d2c447..b00a.js gzip | 26.1 kB | N/A | N/A |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.45 kB | -29 B |
| main-d7c140e..a131.js gzip | N/A | 27.8 kB | N/A |
| Overall change | 73 kB | 71.7 kB | -1.31 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | N/A | N/A |
| _error-d828d..2954.js gzip | 3.06 kB | N/A | N/A |
| amp-5388d1f5..4ce9.js gzip | 551 B | N/A | N/A |
| css-10424225..367a.js gzip | 329 B | 327 B | -2 B |
| dynamic-9821..3cd4.js gzip | 2.67 kB | N/A | N/A |
| head-1df323b..d261.js gzip | 2.32 kB | N/A | N/A |
| hooks-ab0016..b093.js gzip | 917 B | N/A | N/A |
| image-c3cc30..4e2a.js gzip | 5.87 kB | N/A | N/A |
| index-95c8cb..6970.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-05c99e7..35ec.js gzip | 1.66 kB | N/A | N/A |
| routerDirect..6659.js gzip | 319 B | 321 B | ⚠️ +2 B |
| script-d94ba..ed05.js gzip | 386 B | 383 B | -3 B |
| withRouter-7..8b2e.js gzip | 317 B | 318 B | ⚠️ +1 B |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| _app-e2cfdd4..f20e.js gzip | N/A | 1.23 kB | N/A |
| _error-6679c..c50e.js gzip | N/A | 194 B | N/A |
| amp-e55eb6be..a860.js gzip | N/A | 312 B | N/A |
| dynamic-3814..830e.js gzip | N/A | 2.38 kB | N/A |
| head-0b292cc..7d7c.js gzip | N/A | 350 B | N/A |
| hooks-a534e8..efa1.js gzip | N/A | 635 B | N/A |
| image-258b59..8ae1.js gzip | N/A | 4.45 kB | N/A |
| link-a8a0a12..1f88.js gzip | N/A | 1.87 kB | N/A |
| Overall change | 19.8 kB | 13.2 kB | -6.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 459 B | ⚠️ +1 B |
| Overall change | 458 B | 459 B | ⚠️ +1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 536 B | 535 B | -1 B |
| link.html gzip | 548 B | 548 B | ✓ |
| withRouter.html gzip | 529 B | 529 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-843adaf946d87644.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c781952f352e4219.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b11421da95e6cd65.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
   "/css": [
     "static\u002Fcss\u002Fb05d9375ec06fe1b.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-3082f38ec4aa6063.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-99ad492aad2c14e4.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-e9949e65f81038fb.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-a9a93d991a2a6a9c.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-e040764724fe6a41.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-a4027db8f96167d6.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-f632234727179322.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-ace0158746a527c7.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-df7921033b292f8a.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c65470edc1e9d9b6.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-070ef9975918e033.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-3ab6a24eae9d4d66.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app-de3f211ea2b76ae1.js</strong></summary>

```diff
@@ -0,0 +1,268 @@
+(self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
+  [888],
+  {
+    /***/ 915: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6029: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
+
+      var _regeneratorRuntime = _interopRequireDefault(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
+      }
+      function _classCallCheck(instance, Constructor) {
+        if (!(instance instanceof Constructor)) {
+          throw new TypeError("Cannot call a class as a function");
+        }
+      }
+      function _defineProperties(target, props) {
+        for (var i = 0; i < props.length; i++) {
+          var descriptor = props[i];
+          descriptor.enumerable = descriptor.enumerable || false;
+          descriptor.configurable = true;
+          if ("value" in descriptor) descriptor.writable = true;
+          Object.defineProperty(target, descriptor.key, descriptor);
+        }
+      }
+      function _createClass(Constructor, protoProps, staticProps) {
+        if (protoProps) _defineProperties( [...]

2021-10-22 12:34 UTC, sokra requested changes

2021-10-22 14:08 UTC, styfle submitted a review, later dismissed

2021-10-22 15:22 UTC, styfle submitted a review, later dismissed

2021-10-22 16:46 UTC, styfle submitted a review, later dismissed

2021-10-23 00:04 UTC, ijjk commented
## Failing test suites <!--4137503969-->
Commit: b600ef766e5373932ee09f0152631843697b8a20

**test/integration/with-electron/test/index.test.js** 
- Parse Relative Url > File Protocol via Electron > app init
- Parse Relative Url > File Protocol via Electron > should render the home page
- Parse Relative Url > File Protocol via Electron > should do navigations via Link
- Parse Relative Url > File Protocol via Electron > should do back to home page via Link
- Parse Relative Url > File Protocol via Electron > should do navigations via Router

<details>
<summary>Expand output</summary>

  ● Parse Relative Url › File Protocol via Electron › app init

    command failed with code 1

      174 |         code !== 0
      175 |       ) {
    > 176 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      177 |       }
      178 |
      179 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:176:23)

  ● Parse Relative Url › File Protocol via Electron › should render the home page

    command failed with code 1

      174 |         code !== 0
      175 |       ) {
    > 176 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      177 |       }
      178 |
      179 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:176:23)

  ● Parse Relative Url › File Protocol via Electron › should do navigations via Link

    command failed with code 1

      174 |         code !== 0
      175 |       ) {
    > 176 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      177 |       }
      178 |
      179 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:176:23)

  ● Parse Relative Url › File Protocol via Electron › should do back to home page via Link

    command failed with code 1

      174 |         code !== 0
      175 |       ) {
    > 176 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      177 |       }
      178 |
      179 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:176:23)

  ● Parse Relative Url › File Protocol via Electron › should do navigations via Router

    command failed with code 1

      174 |         code !== 0
      175 |       ) {
    > 176 |         return reject(new Error(`command failed with code ${code}`))
          |                       ^
      177 |       }
      178 |
      179 |       resolve({

      at ChildProcess.<anonymous> (lib/next-test-utils.js:176:23)

</details>

2021-10-23 01:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 13.6s | 9.6s | -4.1s |
| buildDurationCached | 3.3s | 2.8s | -470ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +8.75 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.155 | 3.217 | ⚠️ +0.06 |
| / avg req/sec | 792.42 | 777.11 | ⚠️ -15.31 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.546 | 1.497 | -0.05 |
| /error-in-render avg req/sec | 1617.28 | 1669.58 | +52.3 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | N/A | N/A |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-167207f..648c.js gzip | 26.1 kB | N/A | N/A |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.45 kB | -29 B |
| main-ccee221..2413.js gzip | N/A | 27.7 kB | N/A |
| Overall change | 72.9 kB | 71.5 kB | -1.39 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | N/A | N/A |
| _error-d828d..2954.js gzip | 3.06 kB | N/A | N/A |
| amp-5388d1f5..4ce9.js gzip | 551 B | N/A | N/A |
| css-10424225..367a.js gzip | 329 B | 327 B | -2 B |
| dynamic-9821..3cd4.js gzip | 2.67 kB | N/A | N/A |
| head-1df323b..d261.js gzip | 2.32 kB | N/A | N/A |
| hooks-ab0016..b093.js gzip | 917 B | N/A | N/A |
| image-a42113..a670.js gzip | 5.84 kB | N/A | N/A |
| index-95c8cb..6970.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-05c99e7..35ec.js gzip | 1.66 kB | N/A | N/A |
| routerDirect..6659.js gzip | 319 B | 321 B | ⚠️ +2 B |
| script-d94ba..ed05.js gzip | 386 B | 383 B | -3 B |
| withRouter-7..8b2e.js gzip | 317 B | 318 B | ⚠️ +1 B |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| _app-e2cfdd4..f20e.js gzip | N/A | 1.23 kB | N/A |
| _error-6679c..c50e.js gzip | N/A | 194 B | N/A |
| amp-e55eb6be..a860.js gzip | N/A | 312 B | N/A |
| dynamic-3814..830e.js gzip | N/A | 2.38 kB | N/A |
| head-0b292cc..7d7c.js gzip | N/A | 350 B | N/A |
| hooks-a534e8..efa1.js gzip | N/A | 635 B | N/A |
| image-ca3f45..562f.js gzip | N/A | 4.42 kB | N/A |
| link-a8a0a12..1f88.js gzip | N/A | 1.87 kB | N/A |
| Overall change | 19.7 kB | 13.1 kB | -6.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 537 B | 534 B | -3 B |
| link.html gzip | 548 B | 546 B | -2 B |
| withRouter.html gzip | 528 B | 529 B | ⚠️ +1 B |
| Overall change | 1.61 kB | 1.61 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-843adaf946d87644.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c781952f352e4219.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b11421da95e6cd65.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
   "/css": [
     "static\u002Fcss\u002Fb05d9375ec06fe1b.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-3082f38ec4aa6063.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-99ad492aad2c14e4.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-e9949e65f81038fb.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-a9a93d991a2a6a9c.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-e040764724fe6a41.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-946fb8ae39ba1dc3.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-f632234727179322.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-1ff0b3abcb3d2628.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-df7921033b292f8a.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c65470edc1e9d9b6.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-070ef9975918e033.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-3ab6a24eae9d4d66.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app-de3f211ea2b76ae1.js</strong></summary>

```diff
@@ -0,0 +1,268 @@
+(self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
+  [888],
+  {
+    /***/ 915: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6029: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
+
+      var _regeneratorRuntime = _interopRequireDefault(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
+      }
+      function _classCallCheck(instance, Constructor) {
+        if (!(instance instanceof Constructor)) {
+          throw new TypeError("Cannot call a class as a function");
+        }
+      }
+      function _defineProperties(target, props) {
+        for (var i = 0; i < props.length; i++) {
+          var descriptor = props[i];
+          descriptor.enumerable = descriptor.enumerable || false;
+          descriptor.configurable = true;
+          if ("value" in descriptor) descriptor.writable = true;
+          Object.defineProperty(target, descriptor.key, descriptor);
+        }
+      }
+      function _createClass(Constructor, protoProps, staticProps) {
+        if (protoProps) _defineProperties(Constructor.prototype, pr [...]

2021-10-23 01:11 UTC, ijjk commented
## Failing test suites <!--4137763078-->
Commit: 1ce70bf6453482802a2fe2c192769a7cb4f038d8

**test/integration/dist-dir/test/index.test.js** 
- distDir > should handle null/undefined distDir

<details>
<summary>Expand output</summary>

  ● distDir › should handle null/undefined distDir

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 378

      63 |     await fs.writeFile(nextConfig, origNextConfig)
      64 |
    > 65 |     expect(stderr.length).toBe(0)
         |                           ^
      66 |   })
      67 | })
      68 |

      at Object.<anonymous> (integration/dist-dir/test/index.test.js:65:27)

</details>

2021-10-23 01:11 UTC, ijjk commented
## Failing test suites <!--4137763078-->
Commit: 1ce70bf6453482802a2fe2c192769a7cb4f038d8

**test/development/basic/hmr.test.ts** 
- basic HMR > Error Recovery > should detect runtime errors on the module scope
- basic HMR > Error Recovery > should recover after exporting an invalid page
- basic HMR > Error Recovery > should recover after a bad return from the render function
- basic HMR > Error Recovery > should recover after an error reported via SSR

<details>
<summary>Expand output</summary>

  ● basic HMR › Error Recovery › should detect runtime errors on the module scope

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:439:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:524:9)

  ● basic HMR › Error Recovery › should recover after exporting an invalid page

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `basic HMR Error Recovery should recover after exporting an invalid page 1`

    - Snapshot  - 3
    + Received  + 1

       1 of 1 unhandled error
    - Server Error
    + Unhandled Runtime Error

      Error: The default export is not a React Component in page: "/hmr/about5"
    -
    - This error happened while generating the page. Any console logs will be displayed in the terminal window.

      502 |
      503 |         expect(await hasRedbox(browser)).toBe(true)
    > 504 |         expect(await getRedboxHeader(browser)).toMatchInlineSnapshot(`
          |                                                ^
      505 |           " 1 of 1 unhandled error
      506 |           Server Error
      507 |

      at Object.<anonymous> (development/basic/hmr.test.ts:504:48)

  ● basic HMR › Error Recovery › should recover after a bad return from the render function

    TIMED OUT: /This is the about page/

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:572:9)

  ● basic HMR › Error Recovery › should recover after an error reported via SSR

    TIMED OUT: /an-expected-error-in-gip/

    null

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (development/basic/hmr.test.ts:502:17)

</details>

2021-10-23 01:14 UTC, styfle submitted a review, later dismissed

2021-10-23 01:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| buildDuration | 12.3s | 8.6s | -3.7s |
| buildDurationCached | 2.8s | 2.7s | -45ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +8.74 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.818 | 2.859 | ⚠️ +0.04 |
| / avg req/sec | 887.08 | 874.5 | ⚠️ -12.58 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.337 | 1.339 | 0 |
| /error-in-render avg req/sec | 1870.29 | 1866.48 | ⚠️ -3.81 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| 651.cd440d20..0b23.js gzip | 2.96 kB | N/A | N/A |
| 831.695e33f6..205f.js gzip | 179 B | 179 B | ✓ |
| framework-89..a097.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-167207f..648c.js gzip | 26.1 kB | N/A | N/A |
| webpack-f09b..493e.js gzip | 1.47 kB | 1.45 kB | -29 B |
| main-ccee221..2413.js gzip | N/A | 27.7 kB | N/A |
| Overall change | 72.9 kB | 71.5 kB | -1.39 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _app-9fb8765..c13d.js gzip | 979 B | N/A | N/A |
| _error-d828d..2954.js gzip | 3.06 kB | N/A | N/A |
| amp-5388d1f5..4ce9.js gzip | 551 B | N/A | N/A |
| css-10424225..367a.js gzip | 329 B | 327 B | -2 B |
| dynamic-9821..3cd4.js gzip | 2.67 kB | N/A | N/A |
| head-1df323b..d261.js gzip | 2.32 kB | N/A | N/A |
| hooks-ab0016..b093.js gzip | 917 B | N/A | N/A |
| image-a42113..a670.js gzip | 5.84 kB | N/A | N/A |
| index-95c8cb..6970.js gzip | 260 B | 263 B | ⚠️ +3 B |
| link-05c99e7..35ec.js gzip | 1.66 kB | N/A | N/A |
| routerDirect..6659.js gzip | 319 B | 321 B | ⚠️ +2 B |
| script-d94ba..ed05.js gzip | 386 B | 383 B | -3 B |
| withRouter-7..8b2e.js gzip | 317 B | 318 B | ⚠️ +1 B |
| 9a34b27eb3f9..27d.css gzip | 125 B | 125 B | ✓ |
| _app-e2cfdd4..f20e.js gzip | N/A | 1.23 kB | N/A |
| _error-6679c..c50e.js gzip | N/A | 194 B | N/A |
| amp-e55eb6be..a860.js gzip | N/A | 312 B | N/A |
| dynamic-3814..830e.js gzip | N/A | 2.38 kB | N/A |
| head-0b292cc..7d7c.js gzip | N/A | 350 B | N/A |
| hooks-a534e8..efa1.js gzip | N/A | 635 B | N/A |
| image-ca3f45..562f.js gzip | N/A | 4.42 kB | N/A |
| link-a8a0a12..1f88.js gzip | N/A | 1.87 kB | N/A |
| Overall change | 19.7 kB | 13.1 kB | -6.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | timneutkens/next.js add/test-enable-swcloader | Change |
| - | - | - | - |
| index.html gzip | 537 B | 534 B | -3 B |
| link.html gzip | 548 B | 546 B | -2 B |
| withRouter.html gzip | 528 B | 529 B | ⚠️ +1 B |
| Overall change | 1.61 kB | 1.61 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-843adaf946d87644.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-c781952f352e4219.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-b11421da95e6cd65.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
   "/css": [
     "static\u002Fcss\u002Fb05d9375ec06fe1b.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-3082f38ec4aa6063.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-99ad492aad2c14e4.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-e9949e65f81038fb.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-a9a93d991a2a6a9c.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-e040764724fe6a41.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-946fb8ae39ba1dc3.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-f632234727179322.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-1ff0b3abcb3d2628.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-977f59da15f34551.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-df7921033b292f8a.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-c65470edc1e9d9b6.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-070ef9975918e033.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-3ab6a24eae9d4d66.js</strong></summary>

```diff
deleted
```
</details>
<details>
<summary>Diff for <strong>_app-de3f211ea2b76ae1.js</strong></summary>

```diff
@@ -0,0 +1,268 @@
+(self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
+  [888],
+  {
+    /***/ 915: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
+      /***/
+    },
+
+    /***/ 6029: /***/ function(
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) {
+      "use strict";
+
+      var _regeneratorRuntime = _interopRequireDefault(
+        __webpack_require__(5666)
+      );
+      function _assertThisInitialized(self) {
+        if (self === void 0) {
+          throw new ReferenceError(
+            "this hasn't been initialised - super() hasn't been called"
+          );
+        }
+        return self;
+      }
+      function _classCallCheck(instance, Constructor) {
+        if (!(instance instanceof Constructor)) {
+          throw new TypeError("Cannot call a class as a function");
+        }
+      }
+      function _defineProperties(target, props) {
+        for (var i = 0; i < props.length; i++) {
+          var descriptor = props[i];
+          descriptor.enumerable = descriptor.enumerable || false;
+          descriptor.configurable = true;
+          if ("value" in descriptor) descriptor.writable = true;
+          Object.defineProperty(target, descriptor.key, descriptor);
+        }
+      }
+      function _createClass(Constructor, protoProps, staticProps) {
+        if (protoProps) _defineProperties(Constructor.prototype, proto [...]

2021-10-23 03:00 UTC, styfle submitted a review, later dismissed

2021-10-23 08:21 UTC, merged