Update most Apollo Server examples to Apollo Server 3
vercel/next.js pull request #30082
Opened 2021-10-19 23:17 UTC by glasser

Previously, most of the examples used Apollo Server 2. As a maintainer of Apollo
Server, we frequently found that users would start with one of these examples,
try to upgrade to Apollo Server 3, and get confused when it didn't work. Apollo
Server 3 has a more explicit lifecycle that requires awaiting a `start` method
on startup, and users often put this in the wrong place.  The
`api-routes-graphql` package did use Apollo Server 3 and did call `start`, but
only awaits it when the first request comes in rather than at the top level.

Additionally, all the examples use `apollo-server-micro`. While this package is
technically a maintained part of the Apollo Server project, it is not as fully
featured or battle-tested as the most popular package,
`apollo-server-express`. For example, it doesn't have the same default CORS
behavior has the other Apollo Server framework integrations, and doesn't have a
way to drain servers gracefully on shutdown. (Future Apollo Server features may
target `apollo-server-express` before other integrations as well.) Because
Next.js can easily use Express middleware with just a few lines of integration
code (documented at
https://nextjs.org/docs/api-routes/api-middlewares#connectexpress-middleware-support),
Next.js users would be best served by using the most mainstream ApolloServer
implementation rather than the least maintained one.

So this PR:
- Changes all examples from using `apollo-server-micro` v2 to
  `apollo-server-express` v3
- Uses top level await (enabled in next.config.js) for proper startup handling
- Upgrades other packages like `graphql` and `@graphql-tools/schema`, and
  installs them where relevant
- Removes special CORS handling from `examples/api-routes-graphql` because
  `apollo-server-express` has better CORS defaults. (If the default is not good
  enough for this example, pass a `cors` option to `getMiddleware` instead of
  doing CORS manually. The value of the `cors` option is equivalent to the
  argument to the npm `cors` package's middleware.)

This leaves the `with-apollo-neo4j-graphql` example alone, as I could not get it
to work properly before or after upgrading Apollo Server.

## Documentation / Examples

- [x] Make sure the linting passes

2021-10-20 07:59 UTC, elrumordelaluz requested changes
I think is missing to add `express` into `package.json` as a _dependency_ based on [this section](https://www.apollographql.com/docs/apollo-server/migration/#peer-deps-instead-of-direct-deps) of the Migration to v3 docs:

>In Apollo Server 3, these packages have peer dependencies on their corresponding framework packages. This means that you need to install a version of that package of your choice yourself in your app (though most likely that was already the case).

2021-10-20 17:29 UTC, glasser commented
@elrumordelaluz Hmm, I did run them and they worked for me, but you're right that there is a runtime dependency on express (for `express.Router()`. Let me see why they worked for me and add the dependencies.

2021-10-29 22:55 UTC, glasser commented
So there's no recommended path for doing initialization on startup in a Next.js app? Only when a request comes in?  I suppose I can try to change these examples to use ensureStarted; it just seems like a shame that anyone using Next.js in a more stateful server would end up with worse error handling.

My honest goal here is to stop getting bug reports on my project from folks who try to upgrade these examples and do it incorrectly, so I'm down to do whatever changes are necessary to get this merged. I can't tell if anyone who's responded yet is a project owner — I see that nobody has enabled CI for this PR yet.

2021-10-30 11:17 UTC, EarthlingDavey commented
@glasser I've been following in the background. I don't really know enough about this to comment on your work. But it seems like you have a good goal, so I appreciate the work you've put in. And will likely use whatever solution is reached in this PR. FWIW I use apollo-server-micro with apollo 3 on a server, not Vercel.

Anyways it may help to tag @ijjk ( Code owner of 20 files in this pull request ). Hope you folks can reach an agreement that is good for everyone. Good luck and thank you :)

2021-11-04 13:51 UTC, tsvetann commented
@glasser thanks for your efforts. Could you please add to the examples how to add `graphql-upload`. it is not quite clear how to merge your updated examples here with the instructions provided on the [Apollo website](https://www.apollographql.com/docs/apollo-server/data/file-uploads/). On another note do you have time & plans to provide example with `apollo-server-fastify`?

2021-11-05 22:40 UTC, marklawlor commented
This PR is blocked by https://github.com/vercel/next.js/issues/31054

2021-11-05 23:48 UTC, glasser commented
@marklawlor can you help me understand the impact of that statement on this PR?

@tsvetann Adding graphql-upload examples would be an appropriate thing for the graphql-upload team to do, I think. I don't think most users end up using graphql-upload, which is part of why we removed it from being bundled in AS3.

I don't think it would be productive to add examples for how to use next with apollo-server-fastify, for the same reason as apollo-server-micro: an easy-to-use introductory example should guide people towards the highest quality most popular best maintained least likely to be converted to "community" maintenance version of Apollo Server, which is apollo-server-express.

2021-11-06 02:57 UTC, marklawlor commented
@glasser NextJS 12 is switching from Babel to SWC. Top level await does not appear to be configurable under SWC, so if you update to Next 12 you need to opt out of it (continue using Babel).

Whether this is actually blocked is a call for prefer examples to use SWC unless they rely on a specific Babel plugin.

2021-11-07 02:22 UTC, glasser commented
@marklawlor OK. So you are saying that while the current version of NextJS allows you to create API route servers that do async work on startup with "restart the process on failure" semantics, the next version won't?

2021-11-07 21:12 UTC, sajadghawami commented
@glasser 

no, it will. from my understanding they are planning to [implement the missing functionalities](https://github.com/vercel/next.js/discussions/30174) such as [top-level-await](https://github.com/vercel/next.js/issues/31054).

also, i updated my app based on your apollo server 3 examples and it works like a charm with nextjs@11 - thanks :).

2021-11-08 17:57 UTC, glasser commented
OK, so that means that this is a reasonable approach for this repo then?

I'm not sure I know what is left to do in order to help this PR to get merged. (For example, I'm not sure which suggestions above are from maintainers deciding whether this PR should be merged and which are from other helpful community members.) I also would love a maintainer to "approve running workflows" so I can see if CI passes!

2021-11-08 18:17 UTC, tettoffensive commented
@glasser I think all these comments are from helpful community members. I appreciate the work you've done. At least it works for me for now in NextJS 11.

2021-11-09 07:23 UTC, elrumordelaluz commented
Also for me works in v11 and in v12 bypassing the _top level await_ part.

2021-11-12 14:39 UTC, TomHsiao1260 commented
Hi, I've read this issue and follow the example guide to build my GraphQL server. However, the SSG part accidentally fail in the build process. Any suggestion? I also provide a link for someone who want to reproduce this issue. Thanks in advance!
https://github.com/TomHsiao1260/next-graphql-example

2021-11-29 11:36 UTC, TomHsiao1260 commented
> Hi, I've read this issue and follow the example guide to build my GraphQL server. Both SSG and SSR work well in development mode. However, the SSG part accidentally fail in the build process. Any suggestion? I also provide a link for someone who want to reproduce this issue. Thanks in advance!
> 
> https://github.com/TomHsiao1260/next-graphql-example

Any suggestion?

2021-12-07 13:11 UTC, prichodko commented
@TomHsiao1260 API routes are meant to be consumed from the outside and not from within a Next.js app. You are essentially adding another network request and introducing more latency, instead of just calling your logic directly. `GetServerSideProps` and `GetStaticProps` are both using Node.js runtime.

2022-01-06 13:39 UTC, eric-burel commented
Hi, I don't get the middleware thing, my current code would look like this:

```ts
});
await server.start();

app.set("trust proxy", true);
const gqlPath = "/api/graphql";
// setup cors
app.use(gqlPath, cors(corsOptions));
// init the db
app.use(gqlPath, mongoConnection(mongoUri));

server.applyMiddleware({ app, path: "/api/graphql" });

export const config = {
  api: {
    bodyParser: false,
  },
};

export default app;

```

So I return the Express app, not a handler. Does that make a difference with your demo?

2022-01-07 01:12 UTC, glasser commented
@eric-burel I don't think so because I think that NextJS handlers are async functions rather than Express-style req/res/fn things — thus the runMiddleware which I copied from the docs into the examples.

2022-01-07 07:52 UTC, eric-burel commented
Ok then it would be interesting to have a Next.js maintainer opinion on this. Here is my own setup, exposing the Express server instead of a handler: https://github.com/VulcanJS/vulcan-next/blob/devel/src/pages/api/graphql.ts

2022-02-19 21:00 UTC, apuyou commented
Hi, I needed this badly this week so I created the following based on the samples provided by @glasser and the apollo-server-lambda package: https://github.com/apuyou/apollo-server-nextjs
It seems to run great on Vercel but obviously is new work. It assumes that API routes are serverless so doesn't need top-level await.
If that's useful for the community, I'll probably update the tests and improve the documentation.

2022-03-17 17:21 UTC, tettoffensive commented
@apuyou Did you get this running with Next.js 12? I was trying to upgrade, using the example with `apollo-server-express` but getting errors when I refresh the page (I'm guessing due to incompatibility between Next.js 12 and apollo-server. I may just abandon the upgrade.

2022-03-17 20:53 UTC, apuyou commented
> @apuyou Did you get this running with Next.js 12? I was trying to upgrade, using the example with `apollo-server-express` but getting errors when I refresh the page (I'm guessing due to incompatibility between Next.js 12 and apollo-server. I may just abandon the upgrade.

Yes, this works for me on Next.js 12. However, it mostly fixes issues linked to upgrading Apollo and not Next.js, so I am not sure about yours :/

2022-03-31 20:12 UTC, tettoffensive commented
> https://github.com/apuyou/apollo-server-nextjs

Thanks @apuyou. It did fix my issue

2022-04-11 17:40 UTC, roberte777 commented
Looks like some good changes that would be helpful to our team. Stumbled upon this looking for a way to integrate graphql subscriptions into nextjs. Using this method (apollo-server-express instead of micro) could I implement subscriptions? Or am I unable to do it this way because nextjs is weird about websockets?

Our team is currently thinking about running our next applications with a custom server instead in order to implement graphql subscriptions with websockets. Any input on this topic would be greatly appreciated. We are a small team without a lot of experience.

2022-04-12 07:09 UTC, eric-burel commented
> Looks like some good changes that would be helpful to our team. Stumbled upon this looking for a way to integrate graphql subscriptions into nextjs. Using this method (apollo-server-express instead of micro) could I implement subscriptions? Or am I unable to do it this way because nextjs is weird about websockets?
> 
> Our team is currently thinking about running our next applications with a custom server instead in order to implement graphql subscriptions with websockets. Any input on this topic would be greatly appreciated. We are a small team without a lot of experience.

I would advise against a custom server, you are killing Next.js performance. That's pattern is something you would have found in Meteor apps for instance. 
I think it's a valid and normal pattern to run Next.js app with a "satellite" Express server (or whatever) for long running tasks such as handling websockets, or cron jobs. You'd want to focus on how to efficiently reuse your code between Next and other apps, eg via a monorepo, instead of trying to fit everything in Next.js.

2022-05-02 16:17 UTC, httpete commented
Hit exactly this - and your snip works perfectly with v3 and next 12. I did nothing but copy the code, npm the deps, and fire.

2022-07-08 05:09 UTC, glasser commented
I don't use Next.JS. My only motivation here is to stop the sea of people showing up at our repo complaining about the fact that they can't figure out how to upgrade from AS2 to AS3 in Next, and also to stop people from using the least feature-complete Apollo Server flavor (apollo-server-micro) for no reason.

For what it's worth, we're nearing the end of development on Apollo Server 4, which provides an actual stable API for building web framework integrations instead of having a set of 9 fixed integrations hardcoded in core.  Additionally, it will provide a simple API for folks who really want the "serverless" experience of "I'm not allowed to do any work on startup that might possibly fail, or if I do that it should just make every single subsequent request fail instead of preventing the server from starting in the first place". So given that this has already sat open for 9 months, maybe we might as well just wait for AS4.

I can't say I'm a big fan of #38315, if for no other reason than that it still uses apollo-server-micro for no reason.

It certainly does seem reasonable to have fewer AS examples in this repo; it sure was a pain to update all of them.

2022-09-21 13:00 UTC, sajadghawami commented
@apuyou just tried your [apollo-server-nextjs](https://github.com/apuyou/apollo-server-nextjs) and perfectly works.

Maybe you want to update this merge-request to include your changes? That way there should not be any external dependency and this MR can finally be merged. Thoughts?

2022-10-04 16:06 UTC, apuyou commented
@sajadghawami Thank you for your interest!

I think we should probably wait for Apollo Server 4 to be released before updating this. AS4 is much easier to integrate with other frameworks and avoids depending on the integration being updated on each AS release.

I have created a v4 branch that uses this integration for https://github.com/apuyou/apollo-server-nextjs (it currently works with the Alpha but not the RC).
On my side, I may do a final update for AS3 to include recent security updates, but then will focus on AS4.

2022-10-04 18:03 UTC, glasser commented
@apuyou Very cool to see! I was planning to come back here and replace this PR with an AS4 one, but it's even better if actual Next users do so.

My thought would be that I'd make two examples: one that uses top-level await and `server.start()` (to have "startup errors crash the process" semantics), and one that doesn't use top-level await and uses `server. startInBackgroundHandlingStartupErrorsByLoggingAndFailingAllRequests()` (to have "startup errors mean all requests will 500" semantics). Folks can choose their example based on whether they're comfortable turning on top-level await and whether they find fail-fast startup error handling important.

2022-10-04 18:05 UTC, ChristianIvicevic commented
> one that uses top-level await

Next.js doesn't support top-level await at all in latest versions due to SWC.

2022-10-04 18:12 UTC, glasser commented
yeah, it continues to be incomprehensible to me why you'd build a server platform that doesn't allow you to do possibly-failing work at startup before you start listening for connections, but hey, what do I know, Next.js is quite popular so I must be missing something!  So I guess we would just make a single example that uses `server. startInBackgroundHandlingStartupErrorsByLoggingAndFailingAllRequests()`.

2022-10-05 07:36 UTC, eric-burel commented
> yeah, it continues to be incomprehensible to me why you'd build a server platform that doesn't allow you to do possibly-failing work at startup before you start listening for connections

To be correct, it's a limitation of SWC. The problem is more that it's being pushed as the default solution while it's clearly limited compared to Babel, missing top-level await being the biggest drawback. I still use Babel happily to this day and will switch only when SWC is mature.

2022-10-06 11:21 UTC, daniel-johnsson commented
Anyone stumble upon this thread looking for a solution to increase the body limit and be able to use multipart upload using `graphql-upload` here is the solution that made it work for me going from `apollo-server-micro` to `apollo-server-express`:

``` javascript
function runMiddleware(
  req: NextApiRequest,
  res: NextApiResponse<any>,
  fn: Router
) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result) => {
      if (result instanceof Error) {
        return reject(result);
      }

      return resolve(result);
    });
  });
}

const apolloServer = new ApolloServer({
  schema,
  dataSources: () => dataSources,
  context: contextFunction,
  plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
});

const startServer = apolloServer.start();

async function handler(req: NextApiRequest, res: NextApiResponse<any>) {
  await startServer;

  const contentType = req.headers["content-type"];
  if (contentType && contentType.startsWith("multipart/form-data")) {
    req.body = await processRequest(req, res);
  }
  const apolloMiddleware = apolloServer.getMiddleware({
    path: "/api/graphql",
    bodyParserConfig: {
      limit: "50mb",
    },
  });

  return runMiddleware(req, res, apolloMiddleware);
}
export default handler;

export const config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
};
```

2022-10-06 11:24 UTC, sajadghawami commented
@daniel-johnsson thank you! the `processRequest` function is missing though :)

2022-10-06 12:43 UTC, daniel-johnsson commented
@sajadghawami  `processRequest` is an exported function from `graphql-upload`
`import { processRequest } from "graphql-upload";`

2022-11-14 12:13 UTC, closed without merging

2022-11-16 00:58 UTC, glasser commented
The only thing better than a project merging your PR is a project merging somebody else's superior PR :) Thanks @idoob and @kodiakhq!

2022-11-21 13:12 UTC, EarthlingDavey commented
> The only thing better than a project merging your PR is a project merging somebody else's superior PR :) Thanks @idoob and @kodiakhq!

Very humble. Thanks to yourself also @glasser