Implement Middleware RFC
vercel/next.js pull request #30081
Opened 2021-10-19 22:33 UTC by javivelasco

This PR adds support for [Middleware as per RFC ](https://github.com/vercel/next.js/discussions/29750). 

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes

2021-10-19 23:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| buildDuration | 11.6s | 12.2s | ⚠️ +651ms |
| buildDurationCached | 2.8s | 2.7s | -34ms |
| nodeModulesSize | 195 MB | 196 MB | ⚠️ +522 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.696 | 2.761 | ⚠️ +0.06 |
| / avg req/sec | 927.45 | 905.44 | ⚠️ -22.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.265 | 1.268 | 0 |
| /error-in-render avg req/sec | 1976.24 | 1971.13 | ⚠️ -5.11 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 2.74 kB | -278 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 27.3 kB | ⚠️ +2.28 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | -1 B |
| Overall change | 71.9 kB | 73.9 kB | ⚠️ +2 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 979 B | ⚠️ +2 B |
| _error-HASH.js gzip | 3.11 kB | 2.83 kB | -277 B |
| amp-HASH.js gzip | 553 B | 551 B | -2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 2.67 kB | -55 B |
| head-HASH.js gzip | 2.37 kB | 2.09 kB | -277 B |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.67 kB | -224 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ⚠️ +3 B |
| routerDirect..HASH.js gzip | 320 B | 319 B | -1 B |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 317 B | -2 B |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.1 kB | -832 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| index.html gzip | 538 B | 546 B | ⚠️ +8 B |
| link.html gzip | 550 B | 557 B | ⚠️ +7 B |
| withRouter.html gzip | 532 B | 540 B | ⚠️ +8 B |
| Overall change | 1.62 kB | 1.64 kB | ⚠️ +23 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,33 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-cb1865344b5f4c2fb9b1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-4ab7f3fee53814edcefc.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-dcba8dbcc08f722a3744.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-abb90d4fd0438c9acb21.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8ca90971eb23b66158ae.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7b16dda7b4ede9b66fa.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-bf79a138d8e688b555b9.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-917f4897ddae8f4497b1.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-8aab34b89d4550b940ef.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-8b0763ffcf5bfe998a56.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6b6565ccfa1d16752c35.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-9028194f7770951161c7.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-f945eb2325ed595c0b8c.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 2741: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
 
       var _react = _interopRequireDefault(__webpack_require__(7294));
 
-      var _utils = __webpack_require__(9151);
+      var _utils = __webpack_require__(9475);
 
       function asyncGeneratorStep(
         gen,
@@ -220,7 +220,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(6871);
+          return __webpack_require__(2741);
         }
       ]);
       if (false) {
@@ -235,7 +235,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(7356);
+      return __webpack_exec__(915), __webpack_exec__(9898);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,107 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [820, 558],
+  [820, 651],
   {
-    /***/ 3646: /***/ function(
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      var arrayLikeToArray = __webpack_require__(7228);
-
-      function _arrayWithoutHoles(arr) {
-        if (Array.isArray(arr)) return arrayLikeToArray(arr);
-      }
-
-      module.exports = _arrayWithoutHoles;
-      (module.exports["default"] = module.exports),
-        (module.exports.__esModule = true);
-
-      /***/
-    },
-
-    /***/ 9713: /***/ function(module) {
-      function _defineProperty(obj, key, value) {
-        if (key in obj) {
-          Object.defineProperty(obj, key, {
-            value: value,
-            enumerable: true,
-            configurable: true,
-            writable: true
-          });
-        } else {
-          obj[key] = value;
-        }
-
-        return obj;
-      }
-
-      module.exports = _defineProperty;
-      (module.exports["default"] = modul [...]

2021-10-19 23:28 UTC, ijjk commented
## Failing test suites <!--4102282528-->
Commit: 161e1ba56b1ef0bc41a6cff3e51163a1ac51a6db

**test/integration/create-next-app/index.test.js** 
- create next app > should use npm as the package manager on supplying --use-npm with example

<details>
<summary>Expand output</summary>

  ● create next app › should use npm as the package manager on supplying --use-npm with example

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      369 |   })
      370 |
    > 371 |   it('should use npm as the package manager on supplying --use-npm with example', async () => {
          |   ^
      372 |     await usingTempDir(async (cwd) => {
      373 |       const projectName = 'use-npm'
      374 |       const res = await run(

      at integration/create-next-app/index.test.js:371:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

</details>

2021-10-20 00:15 UTC, ijjk commented
## Failing test suites <!--4102561387-->
Commit: e9a3ed7ca81187b9e856a3c936aee1a15c8d9f4d

**test/integration/gssp-ssr-change-reloading/test/index.test.js** 
- GS(S)P Server-Side Change Reloading > should not reload page when client-side is changed too GSP
- GS(S)P Server-Side Change Reloading > should not reload page when client-side is changed too GSSP

<details>
<summary>Expand output</summary>

  ● GS(S)P Server-Side Change Reloading › should not reload page when client-side is changed too GSP

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "count": 1,
        "params": Object {
          "post": "first",
        },
    -   "random": 0.8980539014579085,
    +   "random": 0.8518152302127557,
      }

      55 |     await browser.eval(() => (window.beforeChange = 'hi'))
      56 |
    > 57 |     const props = JSON.parse(await browser.elementByCss('#props').text())
         |                   ^
      58 |     expect(props.count).toBe(1)
      59 |
      60 |     const page = new File(join(appDir, 'pages/gsp-blog/[post].js'))

      at Object.<anonymous> (integration/gssp-ssr-change-reloading/test/index.test.js:57:19)

  ● GS(S)P Server-Side Change Reloading › should not reload page when client-side is changed too GSSP

    TIMED OUT: change me

    changed

      437 |
      438 |   if (hardError) {
    > 439 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      440 |   }
      441 |   return false
      442 | }

      at Object.check (lib/next-test-utils.js:439:11)
      at Object.<anonymous> (integration/gssp-ssr-change-reloading/test/index.test.js:158:5)

</details>

2021-10-20 03:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| buildDuration | 15.1s | 16s | ⚠️ +822ms |
| buildDurationCached | 3.6s | 3.4s | -183ms |
| nodeModulesSize | 195 MB | 196 MB | ⚠️ +522 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.364 | 3.525 | ⚠️ +0.16 |
| / avg req/sec | 743.19 | 709.23 | ⚠️ -33.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.579 | 1.694 | ⚠️ +0.12 |
| /error-in-render avg req/sec | 1583.17 | 1476.04 | ⚠️ -107.13 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 2.74 kB | -278 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 27.3 kB | ⚠️ +2.28 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | -1 B |
| Overall change | 71.9 kB | 73.9 kB | ⚠️ +2 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 979 B | ⚠️ +2 B |
| _error-HASH.js gzip | 3.11 kB | 2.83 kB | -277 B |
| amp-HASH.js gzip | 553 B | 551 B | -2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 2.67 kB | -55 B |
| head-HASH.js gzip | 2.37 kB | 2.09 kB | -277 B |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.67 kB | -224 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ⚠️ +3 B |
| routerDirect..HASH.js gzip | 320 B | 319 B | -1 B |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 317 B | -2 B |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.1 kB | -832 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| index.html gzip | 538 B | 546 B | ⚠️ +8 B |
| link.html gzip | 550 B | 557 B | ⚠️ +7 B |
| withRouter.html gzip | 532 B | 540 B | ⚠️ +8 B |
| Overall change | 1.62 kB | 1.64 kB | ⚠️ +23 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,33 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-cb1865344b5f4c2fb9b1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-4ab7f3fee53814edcefc.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-dcba8dbcc08f722a3744.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-abb90d4fd0438c9acb21.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8ca90971eb23b66158ae.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7b16dda7b4ede9b66fa.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-bf79a138d8e688b555b9.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-917f4897ddae8f4497b1.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-8aab34b89d4550b940ef.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-8b0763ffcf5bfe998a56.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6b6565ccfa1d16752c35.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-9028194f7770951161c7.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-f945eb2325ed595c0b8c.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 2741: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
 
       var _react = _interopRequireDefault(__webpack_require__(7294));
 
-      var _utils = __webpack_require__(9151);
+      var _utils = __webpack_require__(9475);
 
       function asyncGeneratorStep(
         gen,
@@ -220,7 +220,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(6871);
+          return __webpack_require__(2741);
         }
       ]);
       if (false) {
@@ -235,7 +235,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(7356);
+      return __webpack_exec__(915), __webpack_exec__(9898);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,107 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [820, 558],
+  [820, 651],
   {
-    /***/ 3646: /***/ function(
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      var arrayLikeToArray = __webpack_require__(7228);
-
-      function _arrayWithoutHoles(arr) {
-        if (Array.isArray(arr)) return arrayLikeToArray(arr);
-      }
-
-      module.exports = _arrayWithoutHoles;
-      (module.exports["default"] = module.exports),
-        (module.exports.__esModule = true);
-
-      /***/
-    },
-
-    /***/ 9713: /***/ function(module) {
-      function _defineProperty(obj, key, value) {
-        if (key in obj) {
-          Object.defineProperty(obj, key, {
-            value: value,
-            enumerable: true,
-            configurable: true,
-            writable: true
-          });
-        } else {
-          obj[key] = value;
-        }
-
-        return obj;
-      }
-
-      module.exports = _defineProperty;
-      (module.exports["default"] [...]

2021-10-20 08:18 UTC, sokra requested changes
I feel like a few test cases for HMR and _middleware would make sense here to check for the developer experience.

2021-10-20 10:30 UTC, sokra requested changes

2021-10-20 11:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| buildDuration | 17.6s | 17.6s | -23ms |
| buildDurationCached | 4.1s | 3.9s | -195ms |
| nodeModulesSize | 195 MB | 196 MB | ⚠️ +520 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.919 | 4.139 | ⚠️ +0.22 |
| / avg req/sec | 637.92 | 603.94 | ⚠️ -33.98 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.004 | 2.208 | ⚠️ +0.2 |
| /error-in-render avg req/sec | 1247.23 | 1132.43 | ⚠️ -114.8 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 2.74 kB | -278 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 27.3 kB | ⚠️ +2.28 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | -1 B |
| Overall change | 71.9 kB | 73.9 kB | ⚠️ +2 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 979 B | ⚠️ +2 B |
| _error-HASH.js gzip | 3.11 kB | 2.83 kB | -277 B |
| amp-HASH.js gzip | 553 B | 551 B | -2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 2.67 kB | -55 B |
| head-HASH.js gzip | 2.37 kB | 2.09 kB | -277 B |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.67 kB | -224 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ⚠️ +3 B |
| routerDirect..HASH.js gzip | 320 B | 319 B | -1 B |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 317 B | -2 B |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.1 kB | -832 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| index.html gzip | 538 B | 546 B | ⚠️ +8 B |
| link.html gzip | 550 B | 557 B | ⚠️ +7 B |
| withRouter.html gzip | 532 B | 540 B | ⚠️ +8 B |
| Overall change | 1.62 kB | 1.64 kB | ⚠️ +23 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,33 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-cb1865344b5f4c2fb9b1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-4ab7f3fee53814edcefc.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-dcba8dbcc08f722a3744.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-abb90d4fd0438c9acb21.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8ca90971eb23b66158ae.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7b16dda7b4ede9b66fa.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-bf79a138d8e688b555b9.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-917f4897ddae8f4497b1.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-8aab34b89d4550b940ef.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-8b0763ffcf5bfe998a56.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6b6565ccfa1d16752c35.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-9028194f7770951161c7.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-f945eb2325ed595c0b8c.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 2741: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
 
       var _react = _interopRequireDefault(__webpack_require__(7294));
 
-      var _utils = __webpack_require__(9151);
+      var _utils = __webpack_require__(9475);
 
       function asyncGeneratorStep(
         gen,
@@ -220,7 +220,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(6871);
+          return __webpack_require__(2741);
         }
       ]);
       if (false) {
@@ -235,7 +235,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(7356);
+      return __webpack_exec__(915), __webpack_exec__(9898);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,107 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [820, 558],
+  [820, 651],
   {
-    /***/ 3646: /***/ function(
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      var arrayLikeToArray = __webpack_require__(7228);
-
-      function _arrayWithoutHoles(arr) {
-        if (Array.isArray(arr)) return arrayLikeToArray(arr);
-      }
-
-      module.exports = _arrayWithoutHoles;
-      (module.exports["default"] = module.exports),
-        (module.exports.__esModule = true);
-
-      /***/
-    },
-
-    /***/ 9713: /***/ function(module) {
-      function _defineProperty(obj, key, value) {
-        if (key in obj) {
-          Object.defineProperty(obj, key, {
-            value: value,
-            enumerable: true,
-            configurable: true,
-            writable: true
-          });
-        } else {
-          obj[key] = value;
-        }
-
-        return obj;
-      }
-
-      module.exports = _defineProperty;
-      (module.exports["default"] = m [...]

2021-10-20 14:04 UTC, ijjk commented
## Failing test suites <!--4108946769-->
Commit: 510e0d8435298a96595aa954c008b5077ff3b1e6

**test/production/required-server-files.test.ts** 
- should set-up next > should bubble error correctly for gip page
- should set-up next > should bubble error correctly for gssp page

<details>
<summary>Expand output</summary>

  ● should set-up next › should bubble error correctly for gip page

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      580 |     const res = await fetchViaHTTP(appPort, '/api/error')
      581 |     expect(res.status).toBe(500)
    > 582 |     expect(await res.text()).toBe('error')
          |                          ^
      583 |     expect(errors.length).toBe(1)
      584 |     expect(errors[0]).toContain('some error from /api/error')
      585 |   })

      at Object.<anonymous> (production/required-server-files.test.ts:582:26)

  ● should set-up next › should bubble error correctly for gssp page

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 2

      592 |       {
      593 |         headers: {
    > 594 |           'x-matched-path': '/optional-ssp/[[...rest]]',
          |                           ^
      595 |         },
      596 |       }
      597 |     )

      at Object.<anonymous> (production/required-server-files.test.ts:594:27)

</details>

2021-10-20 15:00 UTC, styfle submitted a review, later dismissed

2021-10-20 15:14 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| buildDuration | 15.1s | 16.4s | ⚠️ +1.3s |
| buildDurationCached | 3.4s | 3.7s | ⚠️ +297ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +521 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.515 | 3.694 | ⚠️ +0.18 |
| / avg req/sec | 711.22 | 676.82 | ⚠️ -34.4 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.83 | 1.999 | ⚠️ +0.17 |
| /error-in-render avg req/sec | 1366.38 | 1250.49 | ⚠️ -115.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 2.74 kB | -278 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 27.3 kB | ⚠️ +2.28 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | -1 B |
| Overall change | 71.9 kB | 73.9 kB | ⚠️ +2 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 979 B | ⚠️ +2 B |
| _error-HASH.js gzip | 3.11 kB | 2.83 kB | -277 B |
| amp-HASH.js gzip | 553 B | 551 B | -2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 2.67 kB | -55 B |
| head-HASH.js gzip | 2.37 kB | 2.09 kB | -277 B |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.67 kB | -224 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ⚠️ +3 B |
| routerDirect..HASH.js gzip | 320 B | 319 B | -1 B |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 317 B | -2 B |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.1 kB | -832 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| index.html gzip | 539 B | 547 B | ⚠️ +8 B |
| link.html gzip | 551 B | 558 B | ⚠️ +7 B |
| withRouter.html gzip | 532 B | 541 B | ⚠️ +9 B |
| Overall change | 1.62 kB | 1.65 kB | ⚠️ +24 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,33 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-cb1865344b5f4c2fb9b1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-4ab7f3fee53814edcefc.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-dcba8dbcc08f722a3744.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-abb90d4fd0438c9acb21.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8ca90971eb23b66158ae.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7b16dda7b4ede9b66fa.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-bf79a138d8e688b555b9.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-917f4897ddae8f4497b1.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-8aab34b89d4550b940ef.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-8b0763ffcf5bfe998a56.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6b6565ccfa1d16752c35.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-9028194f7770951161c7.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-f945eb2325ed595c0b8c.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 2741: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
 
       var _react = _interopRequireDefault(__webpack_require__(7294));
 
-      var _utils = __webpack_require__(9151);
+      var _utils = __webpack_require__(9475);
 
       function asyncGeneratorStep(
         gen,
@@ -220,7 +220,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(6871);
+          return __webpack_require__(2741);
         }
       ]);
       if (false) {
@@ -235,7 +235,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(7356);
+      return __webpack_exec__(915), __webpack_exec__(9898);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,107 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [820, 558],
+  [820, 651],
   {
-    /***/ 3646: /***/ function(
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      var arrayLikeToArray = __webpack_require__(7228);
-
-      function _arrayWithoutHoles(arr) {
-        if (Array.isArray(arr)) return arrayLikeToArray(arr);
-      }
-
-      module.exports = _arrayWithoutHoles;
-      (module.exports["default"] = module.exports),
-        (module.exports.__esModule = true);
-
-      /***/
-    },
-
-    /***/ 9713: /***/ function(module) {
-      function _defineProperty(obj, key, value) {
-        if (key in obj) {
-          Object.defineProperty(obj, key, {
-            value: value,
-            enumerable: true,
-            configurable: true,
-            writable: true
-          });
-        } else {
-          obj[key] = value;
-        }
-
-        return obj;
-      }
-
-      module.exports = _defineProperty;
-      (module.exports["default [...]

2021-10-20 16:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| buildDuration | 15.7s | 16.5s | ⚠️ +805ms |
| buildDurationCached | 3.5s | 3.7s | ⚠️ +210ms |
| nodeModulesSize | 195 MB | 195 MB | ⚠️ +521 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.701 | 3.806 | ⚠️ +0.1 |
| / avg req/sec | 675.56 | 656.87 | ⚠️ -18.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.972 | 2.061 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1267.9 | 1213.26 | ⚠️ -54.64 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| 558.HASH.js gzip | 3.02 kB | 2.74 kB | -278 B |
| 779.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 25 kB | 27.3 kB | ⚠️ +2.28 kB |
| webpack-HASH.js gzip | 1.49 kB | 1.49 kB | -1 B |
| Overall change | 71.9 kB | 73.9 kB | ⚠️ +2 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _app-HASH.js gzip | 977 B | 979 B | ⚠️ +2 B |
| _error-HASH.js gzip | 3.11 kB | 2.83 kB | -277 B |
| amp-HASH.js gzip | 553 B | 551 B | -2 B |
| css-HASH.js gzip | 328 B | 329 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.73 kB | 2.67 kB | -55 B |
| head-HASH.js gzip | 2.37 kB | 2.09 kB | -277 B |
| hooks-HASH.js gzip | 918 B | 918 B | ✓ |
| image-HASH.js gzip | 5.89 kB | 5.67 kB | -224 B |
| index-HASH.js gzip | 260 B | 260 B | ✓ |
| link-HASH.js gzip | 1.66 kB | 1.66 kB | ⚠️ +3 B |
| routerDirect..HASH.js gzip | 320 B | 319 B | -1 B |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 317 B | -2 B |
| bb14e60e810b..30f.css gzip | 125 B | 125 B | ✓ |
| Overall change | 19.9 kB | 19.1 kB | -832 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| _buildManifest.js gzip | 492 B | 492 B | ✓ |
| Overall change | 492 B | 492 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js add-nextjs-middleware | Change |
| - | - | - | - |
| index.html gzip | 539 B | 547 B | ⚠️ +8 B |
| link.html gzip | 551 B | 558 B | ⚠️ +7 B |
| withRouter.html gzip | 532 B | 541 B | ⚠️ +9 B |
| Overall change | 1.62 kB | 1.65 kB | ⚠️ +24 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,33 +1,33 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-b90032992c9b33402f59.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-cb1865344b5f4c2fb9b1.js"],
   "/_error": [
-    "static\u002Fchunks\u002Fpages\u002F_error-5fc7609ba2d7d30ff4e6.js"
+    "static\u002Fchunks\u002Fpages\u002F_error-4ab7f3fee53814edcefc.js"
   ],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-6df01f9496d5b32f1b30.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-dcba8dbcc08f722a3744.js"],
   "/css": [
     "static\u002Fcss\u002F59de118426c393f58653.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-e5d9641a48cea07ea0d8.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-abb90d4fd0438c9acb21.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-5ab15ee7c2f1d7071742.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-8ca90971eb23b66158ae.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-3438f380e58241b81e3c.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-f7b16dda7b4ede9b66fa.js"],
   "/hooks": [
-    "static\u002Fchunks\u002Fpages\u002Fhooks-c1f9675770bff0c63be8.js"
+    "static\u002Fchunks\u002Fpages\u002Fhooks-bf79a138d8e688b555b9.js"
   ],
   "/image": [
-    "static\u002Fchunks\u002Fpages\u002Fimage-917f4897ddae8f4497b1.js"
+    "static\u002Fchunks\u002Fpages\u002Fimage-8aab34b89d4550b940ef.js"
   ],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-962a2a330709d57cd073.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-8b0763ffcf5bfe998a56.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-0b53270e1ceea2be8c0d.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-6b6565ccfa1d16752c35.js"
   ],
   "/script": [
-    "static\u002Fchunks\u002Fpages\u002Fscript-be8bf7491d63e05f4c4d.js"
+    "static\u002Fchunks\u002Fpages\u002Fscript-9028194f7770951161c7.js"
   ],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-a12483804a57bd25f921.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-f945eb2325ed595c0b8c.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 6871: /***/ function(
+    /***/ 2741: /***/ function(
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -68,7 +68,7 @@
 
       var _react = _interopRequireDefault(__webpack_require__(7294));
 
-      var _utils = __webpack_require__(9151);
+      var _utils = __webpack_require__(9475);
 
       function asyncGeneratorStep(
         gen,
@@ -220,7 +220,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/_app",
         function() {
-          return __webpack_require__(6871);
+          return __webpack_require__(2741);
         }
       ]);
       if (false) {
@@ -235,7 +235,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(7356);
+      return __webpack_exec__(915), __webpack_exec__(9898);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,107 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
-  [820, 558],
+  [820, 651],
   {
-    /***/ 3646: /***/ function(
-      module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      var arrayLikeToArray = __webpack_require__(7228);
-
-      function _arrayWithoutHoles(arr) {
-        if (Array.isArray(arr)) return arrayLikeToArray(arr);
-      }
-
-      module.exports = _arrayWithoutHoles;
-      (module.exports["default"] = module.exports),
-        (module.exports.__esModule = true);
-
-      /***/
-    },
-
-    /***/ 9713: /***/ function(module) {
-      function _defineProperty(obj, key, value) {
-        if (key in obj) {
-          Object.defineProperty(obj, key, {
-            value: value,
-            enumerable: true,
-            configurable: true,
-            writable: true
-          });
-        } else {
-          obj[key] = value;
-        }
-
-        return obj;
-      }
-
-      module.exports = _defineProperty;
-      (module.exports["default [...]

2021-10-20 16:59 UTC, styfle submitted a review, later dismissed

2021-10-20 17:16 UTC, sokra approved these changes
Looks good. It's probably not the end of it, but I think we should get that as soon as possible on canary...

2021-10-20 17:18 UTC, ijjk approved these changes

2021-10-20 17:36 UTC, styfle approved these changes

2021-10-20 17:52 UTC, merged