Ensure isServer is true when compiling middleware
vercel/next.js pull request #30242
Opened 2021-10-24 19:52 UTC by timneutkens

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

2021-10-24 20:17 UTC, sokra requested changes

2021-10-24 22:08 UTC, ijjk approved these changes

2021-10-24 22:29 UTC, styfle approved these changes

2021-10-25 00:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| buildDuration | 20.9s | 21.3s | ⚠️ +420ms |
| buildDurationCached | 4.1s | 4s | -40ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +109 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.66 | 3.663 | 0 |
| / avg req/sec | 682.97 | 682.54 | ⚠️ -0.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.972 | 1.946 | -0.03 |
| /error-in-render avg req/sec | 1267.71 | 1284.57 | +16.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.7 kB | 27.7 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.5 kB | 71.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| buildDuration | 17.8s | 17.1s | -680ms |
| buildDurationCached | 4.2s | 4.7s | ⚠️ +492ms |
| nodeModulesSize | 196 MB | 196 MB | ⚠️ +109 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.91 | 3.654 | -0.26 |
| / avg req/sec | 639.43 | 684.23 | +44.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.964 | 1.96 | 0 |
| /error-in-render avg req/sec | 1272.95 | 1275.39 | +2.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.8 kB | 27.8 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| polyfills-a4..dd70.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 621 B | 621 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.9 kB | 1.9 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js fix/middleware-swc | Change |
| - | - | - | - |
| index.html gzip | 534 B | 534 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 923d50cd3cfaca68edb53e95a075ba715967f439

2021-10-25 00:15 UTC, ijjk commented
## Failing test suites <!--4146566764-->
Commit: 923d50cd3cfaca68edb53e95a075ba715967f439

**test/e2e/basepath.test.ts** 
- basePath > should use urls with basepath in router events for hash changes
- basePath > should use urls with basepath in router events for failed route change

<details>
<summary>Expand output</summary>

  ● basePath › should use urls with basepath in router events for hash changes

    expect(received).toEqual(expected) // deep equality

    - Expected  -  0
    + Received  + 21

    @@ -1,7 +1,28 @@
      Array [
        Array [
    +     "routeChangeStart",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
    +     "beforeHistoryChange",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
    +     "routeChangeComplete",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
          "hashChangeStart",
          "/docs/hello#some-hash",
          Object {
            "shallow": false,
          },

      713 |
      714 |         const eventLog = await browser.eval('window._getEventLog()')
    > 715 |         expect(eventLog).toEqual([
          |                          ^
      716 |           [
      717 |             'hashChangeStart',
      718 |             `${basePath}/hello#some-hash`,

      at Object.<anonymous> (e2e/basepath.test.ts:715:26)

  ● basePath › should use urls with basepath in router events for failed route change

    expect(received).toEqual(expected) // deep equality

    - Expected  -  0
    + Received  + 21

    @@ -1,8 +1,29 @@
      Array [
        Array [
          "routeChangeStart",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
    +     "beforeHistoryChange",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
    +     "routeChangeComplete",
    +     "/docs/hello",
    +     Object {
    +       "shallow": true,
    +     },
    +   ],
    +   Array [
    +     "routeChangeStart",
          "/docs/error-route",
          Object {
            "shallow": false,
          },
        ],

      769 |
      770 |         const eventLog = await browser.eval('window._getEventLog()')
    > 771 |         expect(eventLog).toEqual([
          |                          ^
      772 |           ['routeChangeStart', `${basePath}/error-route`, { shallow: false }],
      773 |           [
      774 |             'routeChangeError',

      at Object.<anonymous> (e2e/basepath.test.ts:771:26)

</details>

2021-10-25 01:05 UTC, merged