Account for `assetPrefix` when initializing HMR connection
vercel/next.js pull request #30632
Opened 2021-10-29 17:30 UTC by genetschneider

## Bug

- Fixes issue [#30328](https://github.com/vercel/next.js/issues/30328)

## Changes
- Ensure `assetPrefix` is used by HMR properly
- - Allow local proxy servers (local cdn url) as assetPrefix when doing HMR

2021-11-02 16:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 24.3s | 22.6s | -1.7s |
| buildDurationCached | 4.8s | 4.9s | ⚠️ +162ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +624 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.16 | 4.379 | ⚠️ +0.22 |
| / avg req/sec | 600.96 | 570.89 | ⚠️ -30.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.067 | 2.237 | ⚠️ +0.17 |
| /error-in-render avg req/sec | 1209.21 | 1117.47 | ⚠️ -91.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 533 B | 533 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 25.3s | 24.9s | -459ms |
| buildDurationCached | 4.7s | 5s | ⚠️ +341ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +624 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.752 | 3.774 | ⚠️ +0.02 |
| / avg req/sec | 666.32 | 662.47 | ⚠️ -3.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.976 | 1.968 | -0.01 |
| /error-in-render avg req/sec | 1265.47 | 1270.01 | +4.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: c2f65c6877c52f72d7483bdc8d38fbd90ec3d6d9

2021-11-02 17:39 UTC, ijjk requested changes
Hi, can you please add a test for this to ensure it is working as expected? Existing tests for the HMR connection can be found [here](https://github.com/vercel/next.js/blob/canary/test/integration/ondemand/test/index.test.js)

2021-11-02 17:49 UTC, ijjk commented
## Failing test suites <!--4234733690-->
Commit: 690fcfc4a75a04acd3f6924faf59b3df9b51ea7b

**test/integration/create-next-app/index.test.js** 
- create next app > empty directory
- create next app > should support typescript flag
- create next app > should fall back to default template
- create next app > should allow an example named default
- create next app > should create a project in the current directory
- create next app > should ask the user for a name for the project if none supplied

<details>
<summary>Expand output</summary>

  ● create next app › empty directory

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      39 |   // stdin is piped instead of inherited on windows
      40 |   if (process.platform !== 'win32') {
    > 41 |     it('empty directory', async () => {
         |     ^
      42 |       await usingTempDir(async (cwd) => {
      43 |         const projectName = 'empty-directory'
      44 |         const res = await run([projectName], { cwd })

      at integration/create-next-app/index.test.js:41:5
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should support typescript flag

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       99 |   })
      100 |
    > 101 |   it('should support typescript flag', async () => {
          |   ^
      102 |     await usingTempDir(async (cwd) => {
      103 |       const projectName = 'typescript'
      104 |       const res = await run([projectName, '--typescript'], { cwd })

      at integration/create-next-app/index.test.js:101:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should fall back to default template

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      238 |   // stdin is piped instead of inherited on windows
      239 |   if (process.platform !== 'win32') {
    > 240 |     it('should fall back to default template', async () => {
          |     ^
      241 |       await usingTempDir(async (cwd) => {
      242 |         const projectName = 'fail-example'
      243 |         const res = await run(

      at integration/create-next-app/index.test.js:240:5
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should allow an example named default

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      263 |   }
      264 |
    > 265 |   it('should allow an example named default', async () => {
          |   ^
      266 |     await usingTempDir(async (cwd) => {
      267 |       const projectName = 'default-example'
      268 |       const res = await run([projectName, '--example', 'default'], { cwd })

      at integration/create-next-app/index.test.js:265:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should create a project in the current directory

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      312 |   })
      313 |
    > 314 |   it('should create a project in the current directory', async () => {
          |   ^
      315 |     await usingTempDir(async (cwd) => {
      316 |       const res = await run(['.'], { cwd })
      317 |       expect(res.exitCode).toBe(0)

      at integration/create-next-app/index.test.js:314:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

  ● create next app › should ask the user for a name for the project if none supplied

    thrown: "Exceeded timeout of 90000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      330 |   })
      331 |
    > 332 |   it('should ask the user for a name for the project if none supplied', async () => {
          |   ^
      333 |     await usingTempDir(async (cwd) => {
      334 |       const projectName = 'test-project'
      335 |       const res = await run([], { cwd, input: `${projectName}\n` })

      at integration/create-next-app/index.test.js:332:3
      at Object.<anonymous> (integration/create-next-app/index.test.js:24:1)

</details>

2021-11-03 19:04 UTC, ijjk commented
## Failing test suites <!--4247849805-->
Commit: 54907a2161af96936217733e7290aad79fb3bb30

**test/integration/build-indicator/test/index.test.js** 
- Build Activity Indicator > Enabled > Shows the build indicator when a page is built during navigation
- Build Activity Indicator > Enabled > Shows build indicator when page is built from modifying

<details>
<summary>Expand output</summary>

  ● Build Activity Indicator › Enabled › Shows the build indicator when a page is built during navigation

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      1 | /* eslint-env jest */
      2 |
    > 3 | import fs from 'fs-extra'
        |                          ^
      4 | import { join } from 'path'
      5 | import webdriver from 'next-webdriver'
      6 | import { findPort, launchApp, killApp, waitFor } from 'next-test-utils'

      at Object.<anonymous> (integration/build-indicator/test/index.test.js:3:26)

  ● Build Activity Indicator › Enabled › Shows build indicator when page is built from modifying

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      4 | import { join } from 'path'
      5 | import webdriver from 'next-webdriver'
    > 6 | import { findPort, launchApp, killApp, waitFor } from 'next-test-utils'
        |                                                       ^
      7 |
      8 | const appDir = join(__dirname, '..')
      9 | const nextConfig = join(appDir, 'next.config.js')

      at Object.<anonymous> (integration/build-indicator/test/index.test.js:6:55)

</details>

2021-11-03 19:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 24.5s | 22.4s | -2.2s |
| buildDurationCached | 4.7s | 4.8s | ⚠️ +12ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.43 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.917 | 3.617 | -0.3 |
| / avg req/sec | 638.18 | 691.27 | +53.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.32 | 2.001 | -0.32 |
| /error-in-render avg req/sec | 1077.4 | 1249.66 | +172.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 24.3s | 26.1s | ⚠️ +1.8s |
| buildDurationCached | 4.5s | 4.8s | ⚠️ +223ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.43 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.691 | 3.899 | ⚠️ +0.21 |
| / avg req/sec | 677.27 | 641.26 | ⚠️ -36.01 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.97 | 2.269 | ⚠️ +0.3 |
| /error-in-render avg req/sec | 1269.04 | 1101.8 | ⚠️ -167.24 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: ca1fa67cf27001a40faecbd1aaf6fc101845735b

2021-11-03 20:01 UTC, ijjk commented
## Failing test suites <!--4248478978-->
Commit: da6808e1c0ff121d269932466dac9cd9789842bc

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Hot Module Reloading > editing a page > should update styles correctly

<details>
<summary>Expand output</summary>

  ● basic HMR › Hot Module Reloading › editing a page › should update styles correctly

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".hmr-style-page p"
    ============================================================

      250 |     return this.chain(() => {
      251 |       return page
    > 252 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      253 |         .then(async (el) => {
      254 |           // it seems selenium waits longer and tests rely on this behavior
      255 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:252:10

</details>

2021-11-03 20:03 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 18.6s | 18.8s | ⚠️ +258ms |
| buildDurationCached | 3.9s | 4s | ⚠️ +67ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.67 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3 | 2.951 | -0.05 |
| / avg req/sec | 833.45 | 847.18 | +13.73 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.398 | 1.379 | -0.02 |
| /error-in-render avg req/sec | 1788.3 | 1813.2 | +24.9 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 20.1s | 19.9s | -182ms |
| buildDurationCached | 4s | 3.9s | -65ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.67 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.983 | 2.903 | -0.08 |
| / avg req/sec | 838.04 | 861.11 | +23.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.393 | 1.359 | -0.03 |
| /error-in-render avg req/sec | 1794.86 | 1839.19 | +44.33 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: da6808e1c0ff121d269932466dac9cd9789842bc

2021-11-03 20:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 23.2s | 23.7s | ⚠️ +523ms |
| buildDurationCached | 4.9s | 4.7s | -150ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.68 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.869 | 3.713 | -0.16 |
| / avg req/sec | 646.22 | 673.31 | +27.09 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.159 | 1.968 | -0.19 |
| /error-in-render avg req/sec | 1157.99 | 1270.44 | +112.45 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 23.6s | 23.8s | ⚠️ +219ms |
| buildDurationCached | 5.2s | 4.6s | -647ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.68 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.822 | 3.776 | -0.05 |
| / avg req/sec | 654.03 | 661.99 | +7.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.004 | 2.032 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1247.73 | 1230.29 | ⚠️ -17.44 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 521 B | 521 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 515 B | 515 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 12708a16643d9a259293ae9ae98db324d374b108

2021-11-03 22:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 19.1s | 19.8s | ⚠️ +696ms |
| buildDurationCached | 4.1s | 4.1s | -14ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.67 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.346 | 3.527 | ⚠️ +0.18 |
| / avg req/sec | 747.17 | 708.88 | ⚠️ -38.29 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.741 | 1.7 | -0.04 |
| /error-in-render avg req/sec | 1436.22 | 1470.32 | +34.1 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 534 B | 534 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 20.8s | 20.7s | -112ms |
| buildDurationCached | 4.1s | 4.1s | -6ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.67 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.331 | 3.236 | -0.09 |
| / avg req/sec | 750.5 | 772.57 | +22.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.75 | 1.719 | -0.03 |
| /error-in-render avg req/sec | 1428.68 | 1454.06 | +25.38 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

</details>
Commit: 57e8443e000f463df6e4949df436d3c5619cf520

2021-11-03 22:57 UTC, ijjk commented
## Failing test suites <!--4249952976-->
Commit: 57e8443e000f463df6e4949df436d3c5619cf520

**test/integration/preload-viewport/test/index.test.js** 
- Prefetching Links in viewport > should not prefetch already loaded scripts

<details>
<summary>Expand output</summary>

  ● Prefetching Links in viewport › should not prefetch already loaded scripts

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      397 |     expect(hrefs).toEqual([...new Set(hrefs)])
      398 |
    > 399 |     // Verify encoding
          |     ^
      400 |     expect(hrefs.some((e) => e.includes(`%5Bhello%5D-`))).toBe(true)
      401 |   })
      402 |

      at Object.<anonymous> (integration/preload-viewport/test/index.test.js:399:5)

</details>

2021-11-04 08:49 UTC, ijjk commented
## Failing test suites <!--4253383410-->
Commit: e4085069e4a54373d765d1aeca5e71f80020e22b

**test/development/basic-basepath/hmr.test.ts** 
- basic HMR > Hot Module Reloading > editing a page > should update styles correctly

<details>
<summary>Expand output</summary>

  ● basic HMR › Hot Module Reloading › editing a page › should update styles correctly

    page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".hmr-style-page p"
    ============================================================

      250 |     return this.chain(() => {
      251 |       return page
    > 252 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      253 |         .then(async (el) => {
      254 |           // it seems selenium waits longer and tests rely on this behavior
      255 |           // so we wait for the load event fire before returning

      at lib/browsers/playwright.ts:252:10

</details>

2021-11-04 08:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 25.6s | 24.1s | -1.4s |
| buildDurationCached | 5.1s | 4.9s | -269ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.68 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.103 | 3.919 | -0.18 |
| / avg req/sec | 609.32 | 637.95 | +28.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.179 | 2.018 | -0.16 |
| /error-in-render avg req/sec | 1147.56 | 1238.81 | +91.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 71.9 kB | 71.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.23 kB | 1.23 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 520 B | 520 B | ✓ |
| link.html gzip | 531 B | 531 B | ✓ |
| withRouter.html gzip | 513 B | 513 B | ✓ |
| Overall change | 1.56 kB | 1.56 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| buildDuration | 25.7s | 25.2s | -579ms |
| buildDurationCached | 5s | 4.8s | -184ms |
| nodeModulesSize | 293 MB | 293 MB | ⚠️ +1.68 kB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.974 | 4.026 | ⚠️ +0.05 |
| / avg req/sec | 629.15 | 620.9 | ⚠️ -8.25 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.071 | 1.964 | -0.11 |
| /error-in-render avg req/sec | 1206.87 | 1272.66 | +65.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.2 kB | 28.2 kB | ✓ |
| webpack-HASH.js gzip | 1.43 kB | 1.43 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.22 kB | 1.22 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.46 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 334f979574ae..6f4.css gzip | 106 B | 106 B | ✓ |
| Overall change | 13.1 kB | 13.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | genetschneider/next.js-1 asset-prefix-fast-refresh | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 517 B | 517 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

</details>
Commit: e4085069e4a54373d765d1aeca5e71f80020e22b

2021-11-04 09:34 UTC, merged

2021-11-09 02:25 UTC, KingPengZero commented
12.0.3-canary.5

I also encountered this problem. How did you solve it

For nginx configuration, localhost is OK, but the dev domain name will report an error

2021-11-18 19:03 UTC, drewlustro commented
@KingPengZero – did you find a solution? We're experiencing the same issue.

- Custom dev domain
- https
- nginx proxy
- `assetPrefix = /talent/;`