bug: allow schema-relative url in links
vercel/next.js pull request #31119
Opened 2021-11-07 22:27 UTC by SethFalco

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

## Relates Issues
* Fixes https://github.com/vercel/next.js/issues/30947

This change considers `//` at the start of the URL to be a valid match for `urlProtoMatch` and separates it from the rest of the URL. This way, Next.js will stop rejecting schema-relative URLs.

> ```
> <a href="//example.com">Scheme-relative URL</a>
> ```
> — https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2021-11-08 10:59 UTC, timneutkens requested changes
Can you add an integration test for this?

2021-11-09 08:20 UTC, SethFalco commented
I've tried to add an integration test, but the process is confusing me. ^-^'

So when you say integration tests, you meant you want one in the `production`, `development`, or `e2e` folder, right?
Since it says in the test README:

> integration: … We should not add any more tests here.
> — https://github.com/vercel/next.js/blob/canary/test/readme.md

So I've been looking in the `e2e` directory to try and add one. But I can't run any of the existing e2e tests. ^-^'

```
$ yarn testheadless --testPathPattern "e2e/prerender-crawler.test.ts"
…
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
  console.error
    Failed to create next instance Error: next build failed with code 1
        at ChildProcess.<anonymous> (/home/seth/Documents/repos/dependency/next.js/test/lib/next-modes/next-start.ts:63:26)
        at ChildProcess.emit (node:events:390:28)
        at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

      126 |     return nextInstance!
      127 |   } catch (err) {
    > 128 |     console.error('Failed to create next instance', err)
          |             ^
      129 |     try {
      130 |       await nextInstance.destroy()
      131 |     } catch (_) {}

      at Object.createNext (lib/e2e-utils.ts:128:13)
      at e2e/prerender-crawler.test.ts:9:12
```

Any hints to what I'm doing wrong here?

<details>
  <summary>Just keeping the test I was trying to add if you'd care to look at it already:</summary>

<pre><code>
import { createNext } from 'e2e-utils'
import { check } from 'next-test-utils'
import webdriver from 'next-webdriver'
import { NextInstance } from 'test/lib/next-modes/base'

describe('should set-up next', () => {
  let next: NextInstance

  beforeAll(async () => {
    next = await createNext({
      files: {
        'pages/index.js': `
          import React from 'react'
          import Link from 'next/link'

          export default function Page() {
            return (
              &lt;&gt;
                &lt;Link href="//example.org"&gt;
                  &lt;a&gt;&#47;&#47;example.org&lt;/a&gt;
                &lt;/Link&gt;
              &lt;/&gt;
            )
          }
        `
      },
    })
  })
  afterAll(() => next.destroy())

  it('scheme-relative urls should not have the starting // merged', async () => {
    const browser = await webdriver(next.url, '/')

    await check(
      async () => {
        const links = await browser.elementsByCss('a[href]')
        const link = links[0];
        const href = await link.getAttribute('href')

        return href === '//example.org'
      },
      {
        test(result) {
          return result === true
        },
      }
    )
  })
})

</code></pre>
</details>

2021-11-15 18:40 UTC, SethFalco commented
For now I've added a test, but have not executed it locally.
If it looks alright to you, it could be useful if I could see it run in GitHub Actions at least. ^-^'

2021-11-15 20:14 UTC, ijjk requested changes
Hi, I'm not sure we want to allow protocol relative links like this as this can cause issues and doesn't make sense in the context of `next/link` since it's meant for client-transitions. We also have tests checking that this triggers errors here https://github.com/vercel/next.js/blob/b2046400086fcfc18d77a4695f71fae1a4e4dbc4/test/integration/repeated-slashes/test/index.test.js#L286

2021-11-15 21:03 UTC, SethFalco commented
In our case, the usage is usually for relative links as you described, but there are just some a few cases where we want to take the user to a similar page on another domain. As the behavior was unexpected, I just thought it made more sense to fix it here.

As scheme-relative URLs are indeed widely recognized/supported, and your implementation already supports absolute URLs, it would be odd not to support them in my opinion.

I won't push if the consensus is against my proposal, but in my opinion it simply should accept valid URLs.

2021-11-25 00:52 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 21.3s | 21.4s | ⚠️ +88ms |
| buildDurationCached | 4.1s | 4s | -64ms |
| nodeModulesSize | 345 MB | 345 MB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.367 | 3.511 | ⚠️ +0.14 |
| / avg req/sec | 742.57 | 712.09 | ⚠️ -30.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.607 | 1.617 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1555.25 | 1545.7 | ⚠️ -9.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | ⚠️ +2 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.45 kB | 4.45 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4160,7 +4160,7 @@
             : (0, _utils).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
+        var urlProtoMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
         var urlAsStringNoProto = urlProtoMatch
           ? urlAsString.substr(urlProtoMatch[0].length)
           : urlAsString;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-966353a8b06621ca.js"
+      src="/_next/static/chunks/main-aabd0055606ed9cf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-966353a8b06621ca.js"
+      src="/_next/static/chunks/main-aabd0055606ed9cf.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-966353a8b06621ca.js"
+      src="/_next/static/chunks/main-aabd0055606ed9cf.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 23s | 23s | -13ms |
| buildDurationCached | 4.1s | 4s | -98ms |
| nodeModulesSize | 345 MB | 345 MB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.46 | 3.48 | ⚠️ +0.02 |
| / avg req/sec | 722.45 | 718.32 | ⚠️ -4.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.667 | 1.627 | -0.04 |
| /error-in-render avg req/sec | 1499.35 | 1536.55 | +37.2 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ⚠️ +2 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.47 kB | 4.47 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 533 B | 531 B | -2 B |
| link.html gzip | 546 B | 544 B | -2 B |
| withRouter.html gzip | 527 B | 525 B | -2 B |
| Overall change | 1.61 kB | 1.6 kB | -6 B |

</details>

#### Diffs
<details>
<summary>Diff for <str [...]

2021-11-25 00:57 UTC, ijjk commented
## Failing test suites <!--4459559343-->
Commit: 2887dc201cab986fffcc907707ec1b1711efb05e

**test/e2e/relative-scheme-url.test.ts** 
- should set-up next > scheme-relative urls should not have the starting // merged

<details>
<summary>Expand output</summary>

  ● should set-up next › scheme-relative urls should not have the starting // merged

    TIMED OUT: [object Object]

    false

      479 |     if (!this.originalContent) {
      480 |       this.originalContent = content
    > 481 |     }
          |      ^
      482 |     writeFileSync(this.path, content, 'utf8')
      483 |   }
      484 |

      at Object.check (lib/next-test-utils.js:481:15)
      at Object.<anonymous> (e2e/relative-scheme-url.test.ts:36:9)

</details>

2022-03-29 17:16 UTC, ijjk commented
## Failing test suites <!--5848372741-->
Commit: 29e659028dccd3c0eb80de13ff8e0a5d6300c2f3

`yarn testheadless test/development/acceptance/ReactRefresh.test.ts` 
- ReactRefresh > can edit a component without losing state
- ReactRefresh > cyclic dependencies

<details>
<summary>Expand output</summary>

  ● ReactRefresh › can edit a component without losing state

    expect(received).toBe(expected) // Object.is equality

    Expected: "Count: 1"
    Received: "1"

      61 |     expect(
      62 |       await session.evaluate(() => document.querySelector('p').textContent)
    > 63 |     ).toBe('Count: 1')
         |       ^
      64 |     await session.evaluate(() => document.querySelector('button').click())
      65 |     expect(
      66 |       await session.evaluate(() => document.querySelector('p').textContent)

      at Object.<anonymous> (development/acceptance/ReactRefresh.test.ts:63:7)

  ● ReactRefresh › cyclic dependencies

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello. 200"
    Received: "Hello. 100"

      187 |     expect(
      188 |       await session.evaluate(() => document.querySelector('p').textContent)
    > 189 |     ).toBe('Hello. 200')
          |       ^
      190 |     expect(didFullRefresh).toBe(false)
      191 |
      192 |     didFullRefresh = !(await session.patch(

      at Object.<anonymous> (development/acceptance/ReactRefresh.test.ts:189:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-04-02 08:26 UTC, ijjk commented
## Failing test suites <!--5904422981-->
Commit: 695bd00febd54cc636430760a9bb3957c1558cc6

`yarn testheadless test/integration/repeated-slashes/test/index.test.js` 
- 404 handling > custom _error > next dev > should handle slashes in next/link correctly
- 404 handling > custom _error > next dev > should handle slashes in router push correctly
- 404 handling > custom _error > production > next export > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next export > should handle slashes in router push correctly
- 404 handling > custom _error > production > next start > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next start > should handle slashes in router push correctly
- 404 handling > pages/404 > next dev > should handle slashes in next/link correctly
- 404 handling > pages/404 > next dev > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next export > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next export > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next start > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next start > should handle slashes in router push correctly

<details>
<summary>Expand output</summary>

  ● 404 handling › custom _error › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: \/\/google\.com/

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)

  ● 404 handling › custom _error › production › next start › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: \/\/google\.com/

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next start › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)

  ● 404 handling › custom _error › production › next export › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: \/\/google\.com/

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next export › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)

  ● 404 handling › pages/404 › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: \/\/google\.com/

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › pages/404 › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Objec [...]

2022-04-02 08:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.4s | ⚠️ +164ms |
| buildDurationCached | 6.1s | 6.1s | -52ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.946 | 2.962 | ⚠️ +0.02 |
| / avg req/sec | 848.58 | 844.13 | ⚠️ -4.45 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.209 | 1.191 | -0.02 |
| /error-in-render avg req/sec | 2068.06 | 2098.55 | +30.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | -1 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
+        var urlProtoMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
         var urlAsStringNoProto = urlProtoMatch
           ? urlAsString.slice(urlProtoMatch[0].length)
           : urlAsString;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18s | 18s | -24ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +89ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.964 | 2.958 | -0.01 |
| / avg req/sec | 843.58 | 845.13 | +1.55 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.24 | 1.215 | -0.02 |
| /error-in-render avg req/sec | 2016.35 | 2057 | +40.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7  [...]

2022-04-02 08:52 UTC, ijjk commented
## Failing test suites <!--5904576217-->
Commit: 7f3726af8adf5eb0e7af10022bea546e3aa6e88e

`yarn testheadless test/integration/react-streaming-and-server-components/test/switchable-runtime.test.js` 
- Switchable runtime (prod) > should build /node-rsc-isr as an isr page with the nodejs runtime

<details>
<summary>Expand output</summary>

  ● Switchable runtime (prod) › should build /node-rsc-isr as an isr page with the nodejs runtime

    expect(received).toBeLessThan(expected)

    Expected: < 1648889518511
    Received:   1648889518511

      114 |     expect(html3).toContain('Runtime: Node.js')
      115 |
    > 116 |     expect(renderedAt2).toBeLessThan(renderedAt3)
          |                         ^
      117 |   })
      118 |
      119 |   it('should build /edge as a dynamic page with the edge runtime', async () => {

      at Object.<anonymous> (integration/react-streaming-and-server-components/test/switchable-runtime.test.js:116:25)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-04-02 08:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.9s | 15.8s | -81ms |
| buildDurationCached | 6.2s | 6.2s | ⚠️ +30ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.193 | 3.204 | ⚠️ +0.01 |
| / avg req/sec | 783.08 | 780.39 | ⚠️ -2.69 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.438 | 1.389 | -0.05 |
| /error-in-render avg req/sec | 1738.96 | 1799.57 | +60.61 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | -1 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
+        var urlProtoMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
         var urlAsStringNoProto = urlProtoMatch
           ? urlAsString.slice(urlProtoMatch[0].length)
           : urlAsString;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18.6s | 18.6s | ⚠️ +1ms |
| buildDurationCached | 6.2s | 6.2s | ⚠️ +6ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.183 | 3.225 | ⚠️ +0.04 |
| / avg req/sec | 785.34 | 775.1 | ⚠️ -10.24 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.432 | 1.434 | 0 |
| /error-in-render avg req/sec | 1745.23 | 1743.45 | ⚠️ -1.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -453 [...]

2022-04-02 13:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.4s | ⚠️ +91ms |
| buildDurationCached | 6.4s | 6.3s | -100ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.247 | 3.214 | -0.03 |
| / avg req/sec | 769.98 | 777.88 | +7.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.462 | 1.459 | 0 |
| /error-in-render avg req/sec | 1710.17 | 1713.94 | +3.77 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | -1 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
+        var urlProtoMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
         var urlAsStringNoProto = urlProtoMatch
           ? urlAsString.slice(urlProtoMatch[0].length)
           : urlAsString;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 19.3s | 19.2s | -170ms |
| buildDurationCached | 6.2s | 6.2s | ⚠️ +38ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.284 | 3.235 | -0.05 |
| / avg req/sec | 761.28 | 772.79 | +11.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.528 | 1.482 | -0.05 |
| /error-in-render avg req/sec | 1635.64 | 1687.29 | +51.65 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@ [...]

2022-04-02 13:32 UTC, ijjk commented
## Failing test suites <!--5905767828-->
Commit: f00f363f068421ecce1ed718a744ee4185c05646

`yarn testheadless test/integration/repeated-slashes/test/index.test.js` 
- 404 handling > custom _error > next dev > should handle slashes in next/link correctly
- 404 handling > custom _error > next dev > should handle slashes in router push correctly
- 404 handling > custom _error > production > next export > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next export > should handle slashes in router push correctly
- 404 handling > custom _error > production > next start > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next start > should handle slashes in router push correctly
- 404 handling > pages/404 > next dev > should handle slashes in next/link correctly
- 404 handling > pages/404 > next dev > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next export > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next export > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next start > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next start > should handle slashes in router push correctly

<details>
<summary>Expand output</summary>

  ● 404 handling › custom _error › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)

  ● 404 handling › custom _error › production › next start › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next start › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)
          at runMicrotasks (<anonymous>)

  ● 404 handling › custom _error › production › next export › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next export › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)
          at runMicrotasks (<anonymous>)

  ● 404 handling › pages/404 › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › pages/404 › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/google.com"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(awa [...]

2022-04-03 04:34 UTC, ijjk commented
## Failing test suites <!--5909535142-->
Commit: 369b77841c00a86f9c6bae6b747190180fd26b9c

`yarn testheadless test/integration/repeated-slashes/test/index.test.js` 
- 404 handling > custom _error > next dev > should handle slashes in next/link correctly
- 404 handling > custom _error > next dev > should handle slashes in router push correctly
- 404 handling > custom _error > production > next export > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next export > should handle slashes in router push correctly
- 404 handling > custom _error > production > next start > should handle slashes in next/link correctly
- 404 handling > custom _error > production > next start > should handle slashes in router push correctly
- 404 handling > pages/404 > next dev > should handle slashes in next/link correctly
- 404 handling > pages/404 > next dev > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next export > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next export > should handle slashes in router push correctly
- 404 handling > pages/404 > production > next start > should handle slashes in next/link correctly
- 404 handling > pages/404 > production > next start > should handle slashes in router push correctly

<details>
<summary>Expand output</summary>

  ● 404 handling › custom _error › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/teapot"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:343:62)

  ● 404 handling › custom _error › production › next start › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next start › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/another"
    Received: null

      346 |       )
      347 |       expect(await browser.eval('window.location.hash')).toBe(item.hash || '')
    > 348 |       expect(await browser.eval('window.next.router.pathname')).toBe(item.page)
          |                                                                 ^
      349 |     }
      350 |   })
      351 |

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:348:65)

  ● 404 handling › custom _error › production › next export › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › custom _error › production › next export › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/another"
    Received: null

      346 |       )
      347 |       expect(await browser.eval('window.location.hash')).toBe(item.hash || '')
    > 348 |       expect(await browser.eval('window.next.router.pathname')).toBe(item.page)
          |                                                                 ^
      349 |     }
      350 |   })
      351 |

      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:348:65)

  ● 404 handling › pages/404 › next dev › should handle slashes in next/link correctly

    TIMED OUT: /Invalid href passed to next\/router: https:\/\/google\.com\/\//

    Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com?hello=1, repeated forward-slashes (//) or backslashes \ are not valid in the href, Invalid href passed to next/router: \/\/google.com#hello, repeated forward-slashes (//) or backslashes \ are not valid in the href

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/repeated-slashes/test/index.test.js:301:7)

  ● 404 handling › pages/404 › next dev › should handle slashes in router push correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: "/teapot"
    Received: "/"

      341 |         })`
      342 |       )
    > 343 |       expect(await browser.eval('window.location.pathname')).toBe(item.pathname)
          |                                                              ^
      344 |       expect(await browser.eval('window.location.search')).toBe(
      345 |         item.search || ''
      346 |       )

      at Object.<anonymo [...]

2022-04-03 04:37 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 16.5s | 16.6s | ⚠️ +117ms |
| buildDurationCached | 6.4s | 6.3s | -33ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.316 | 3.311 | 0 |
| / avg req/sec | 753.82 | 754.95 | +1.13 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.49 | 1.489 | 0 |
| /error-in-render avg req/sec | 1678.21 | 1678.79 | +0.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.4 kB | -1 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | -1 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 533 B | ⚠️ +2 B |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 525 B | 527 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.61 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
+        var urlProtoMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
         var urlAsStringNoProto = urlProtoMatch
           ? urlAsString.slice(urlProtoMatch[0].length)
           : urlAsString;
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-3cbfbb3526a951bc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 19.4s | 19.5s | ⚠️ +94ms |
| buildDurationCached | 6.3s | 6.3s | -60ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.326 | 3.307 | -0.02 |
| / avg req/sec | 751.59 | 755.98 | +4.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.486 | 1.474 | -0.01 |
| /error-in-render avg req/sec | 1681.99 | 1695.52 | +13.53 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.59 kB | 5.59 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.33 kB | 2.33 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.8 kB | 15.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | -1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4534,7 +4534,7 @@
       [...]

2022-04-03 09:19 UTC, ijjk commented
## Failing test suites <!--5910642471-->
Commit: c8c5293fa64a035643b041e9e54240ac1a310dd0

`yarn testheadless test/integration/custom-routes/test/index.test.js` 
- Custom routes > server mode > should handle external beforeFiles rewrite correctly

<details>
<summary>Expand output</summary>

  ● Custom routes › server mode › should handle external beforeFiles rewrite correctly

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      89 |       console.error('Invalid response', html)
      90 |     }
    > 91 |     expect(res.status).toBe(200)
         |                        ^
      92 |     expect(html).toContain('Vercel')
      93 |
      94 |     const browser = await webdriver(appPort, '/nav')

      at Object.<anonymous> (integration/custom-routes/test/index.test.js:91:24)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-04-03 09:22 UTC, SethFalco commented
Sorry for the push spam, seems I made quite a few mistakes there. ^-^'

Just going to explain some changes!

```ts
url.match(/^\/(?!\/)/) !== null
```

`/` is relative, but `//` is schema-relative which while still relative is not necessarily local.
So, match a `/` at the start, but only if it's not followed by another `/`.

```ts
// absolute and scheme-relative urls can be local if they are on the same origin
const locationOrigin = getLocationOrigin()
const resolved = new URL(url, locationOrigin)
```

Updated the comment to mention scheme-relative.
If we did `new URL('//gitlab.com', 'https://github.com')` it'd return `https://gitlab.com`. (To match the scheme.)

```ts
const urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//)
```

Match the `//` at the start as part of the `urlSchemeMatch`, even if no scheme was specified, so scheme-relative links are just matched as `//`.

I also renamed it to `urlSchemeMatch` as I felt this better represents what it stores, since it includes the `//` or just `//` on its own. The terms `protocol` and `scheme` mostly overlap in this context, so favoring the term `scheme` from `scheme-relative` which is now allowed makes sense to me. (And also distances it from the [`URL#protocol`](https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol) property which stops at the colon (`:`).)

Just let me know if you think the variable name change is unfavorable.

---

Meanwhile, I'm not sure what the failing test in this like push is regarding. 🤔 
That test is passing for me locally.

2022-04-03 09:27 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 20.1s | 20s | -35ms |
| buildDurationCached | 7.5s | 7.6s | ⚠️ +53ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.24 | 4.206 | -0.03 |
| / avg req/sec | 589.65 | 594.33 | +4.68 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.137 | 2.2 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1169.61 | 1136.35 | ⚠️ -33.26 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.5 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.48 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 530 B | -1 B |
| link.html gzip | 545 B | 544 B | -1 B |
| withRouter.html gzip | 525 B | 524 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-718f90fbc72e2fee.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-718f90fbc72e2fee.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-2413143f15cbe12b.js"
+      src="/_next/static/chunks/main-718f90fbc72e2fee.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 23.4s | 23.7s | ⚠️ +273ms |
| buildDurationCached | 7.9s | 8s | ⚠️ +177ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.277 | 4.29 | ⚠️ +0.01 |
| / avg req/sec | 584.47 | 582.69 | ⚠️ -1.78 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.185 | 2.237 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1144.2 | 1117.66 | ⚠️ -26.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +12 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ [...]

2022-04-04 21:24 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 19.5s | 19.8s | ⚠️ +295ms |
| buildDurationCached | 7.4s | 7.4s | -49ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.725 | 3.739 | ⚠️ +0.01 |
| / avg req/sec | 671.12 | 668.6 | ⚠️ -2.52 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.707 | 1.66 | -0.05 |
| /error-in-render avg req/sec | 1464.3 | 1506.31 | +42.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.5 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.52 kB | 5.52 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.7 kB | 15.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 21.8s | 22.3s | ⚠️ +538ms |
| buildDurationCached | 7.2s | 7.5s | ⚠️ +325ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.795 | 3.841 | ⚠️ +0.05 |
| / avg req/sec | 658.73 | 650.93 | ⚠️ -7.8 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.66 | 1.722 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1505.59 | 1451.77 | ⚠️ -53.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +12 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.j [...]

2022-04-05 19:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.5s | ⚠️ +146ms |
| buildDurationCached | 6.2s | 6.1s | -52ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.997 | 2.997 | ✓ |
| / avg req/sec | 834.04 | 834.08 | +0.04 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.198 | 1.226 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2087.27 | 2038.72 | ⚠️ -48.55 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.4 kB | 28.5 kB | ⚠️ +17 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.1 kB | ⚠️ +17 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.52 kB | 5.52 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.7 kB | 15.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-29d269f0411823e2.js"
+      src="/_next/static/chunks/main-efc5a03af69c8b74.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18.1s | 18.4s | ⚠️ +329ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +44ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.01 | 3.031 | ⚠️ +0.02 |
| / avg req/sec | 830.43 | 824.93 | ⚠️ -5.5 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.204 | 1.222 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2075.73 | 2045.37 | ⚠️ -30.36 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +12 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js [...]

2022-04-05 20:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15s | -198ms |
| buildDurationCached | 6.1s | 6s | -88ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.917 | 2.928 | ⚠️ +0.01 |
| / avg req/sec | 856.97 | 853.76 | ⚠️ -3.21 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.173 | 1.193 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2132.09 | 2095.9 | ⚠️ -36.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.2 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.52 kB | 5.52 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.7 kB | 15.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 545 B | 546 B | ⚠️ +1 B |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b9430164b0f7c068.js"
+      src="/_next/static/chunks/main-3d49d7d37955b041.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b9430164b0f7c068.js"
+      src="/_next/static/chunks/main-3d49d7d37955b041.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-b9430164b0f7c068.js"
+      src="/_next/static/chunks/main-3d49d7d37955b041.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 17.7s | 17.9s | ⚠️ +210ms |
| buildDurationCached | 6s | 6s | -5ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.932 | 2.918 | -0.01 |
| / avg req/sec | 852.77 | 856.62 | +3.85 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.195 | 1.223 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2092.71 | 2044.02 | ⚠️ -48.69 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _ [...]

2022-04-06 00:44 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.1s | -116ms |
| buildDurationCached | 5.9s | 5.9s | ⚠️ +26ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.899 | 2.966 | ⚠️ +0.07 |
| / avg req/sec | 862.42 | 842.75 | ⚠️ -19.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.169 | 1.189 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 2138.45 | 2102.67 | ⚠️ -35.78 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.2 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 17.8s | 18s | ⚠️ +225ms |
| buildDurationCached | 6s | 6s | ⚠️ +47ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.924 | 2.912 | -0.01 |
| / avg req/sec | 854.93 | 858.56 | +3.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.172 | 1.203 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 2133.95 | 2078.77 | ⚠️ -55.18 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +10 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 k [...]

2022-04-06 14:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16.2s | ⚠️ +152ms |
| buildDurationCached | 6.3s | 6.2s | -83ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.19 | 3.234 | ⚠️ +0.04 |
| / avg req/sec | 783.68 | 773.05 | ⚠️ -10.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.455 | 1.417 | -0.04 |
| /error-in-render avg req/sec | 1717.7 | 1764.71 | +47.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.5 kB | 28.5 kB | ⚠️ +16 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.1 kB | 72.2 kB | ⚠️ +16 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-46a1f19b7b7698c4.js"
+      src="/_next/static/chunks/main-f046d480b8eb92ea.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 19.2s | 19s | -174ms |
| buildDurationCached | 6.2s | 6.3s | ⚠️ +28ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.213 | 3.23 | ⚠️ +0.02 |
| / avg req/sec | 777.98 | 774.08 | ⚠️ -3.9 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.465 | 1.477 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1706.64 | 1692.81 | ⚠️ -13.83 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.8 kB | 28.8 kB | ⚠️ +10 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.7 kB | 72.7 kB | ⚠️ +10 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB |  [...]

2022-04-07 07:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 19.3s | 19s | -270ms |
| buildDurationCached | 7.3s | 7.3s | ⚠️ +34ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.76 | 3.746 | -0.01 |
| / avg req/sec | 664.85 | 667.36 | +2.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.615 | 1.683 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1548.29 | 1485.6 | ⚠️ -62.69 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +18 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 532 B | 531 B | -1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 525 B | 526 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-75aa0c6099ddb4e5.js"
+      src="/_next/static/chunks/main-d11a7a9ff7e9750f.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-75aa0c6099ddb4e5.js"
+      src="/_next/static/chunks/main-d11a7a9ff7e9750f.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-75aa0c6099ddb4e5.js"
+      src="/_next/static/chunks/main-d11a7a9ff7e9750f.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 21.6s | 21.8s | ⚠️ +200ms |
| buildDurationCached | 7.4s | 7.4s | -33ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.803 | 3.749 | -0.05 |
| / avg req/sec | 657.36 | 666.87 | +9.51 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.64 | 1.687 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1524.37 | 1482.18 | ⚠️ -42.19 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179  [...]

2022-04-07 15:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.9s | ⚠️ +492ms |
| buildDurationCached | 6s | 5.8s | -212ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.164 | 3.278 | ⚠️ +0.11 |
| / avg req/sec | 790.05 | 762.66 | ⚠️ -27.39 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.333 | 1.524 | ⚠️ +0.19 |
| /error-in-render avg req/sec | 1875.83 | 1640.58 | ⚠️ -235.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +18 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 530 B | 532 B | ⚠️ +2 B |
| link.html gzip | 544 B | 545 B | ⚠️ +1 B |
| withRouter.html gzip | 524 B | 526 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-47d6ccedfaedb33e.js"
+      src="/_next/static/chunks/main-b5d65f1ea9b070cc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-47d6ccedfaedb33e.js"
+      src="/_next/static/chunks/main-b5d65f1ea9b070cc.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-47d6ccedfaedb33e.js"
+      src="/_next/static/chunks/main-b5d65f1ea9b070cc.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18s | 18.1s | ⚠️ +71ms |
| buildDurationCached | 6.2s | 6.2s | ⚠️ +46ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.091 | 3.263 | ⚠️ +0.17 |
| / avg req/sec | 808.8 | 766.17 | ⚠️ -42.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.305 | 1.241 | -0.06 |
| /error-in-render avg req/sec | 1916.3 | 2014.96 | +98.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB [...]

2022-04-07 17:32 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.9s | 15.8s | -35ms |
| buildDurationCached | 6.1s | 6.1s | -57ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.228 | 3.251 | ⚠️ +0.02 |
| / avg req/sec | 774.38 | 769.01 | ⚠️ -5.37 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.348 | 1.38 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1854.9 | 1811.69 | ⚠️ -43.21 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +18 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 544 B | 545 B | ⚠️ +1 B |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18.8s | 18.6s | -140ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +103ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.24 | 3.26 | ⚠️ +0.02 |
| / avg req/sec | 771.55 | 766.98 | ⚠️ -4.57 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.345 | 1.388 | ⚠️ +0.04 |
| /error-in-render avg req/sec | 1858.23 | 1800.88 | ⚠️ -57.35 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB [...]

2022-04-07 21:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18.7s | 18.8s | ⚠️ +77ms |
| buildDurationCached | 7.4s | 7.2s | -189ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.83 | 3.823 | -0.01 |
| / avg req/sec | 652.81 | 653.99 | +1.18 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.671 | 1.606 | -0.06 |
| /error-in-render avg req/sec | 1495.78 | 1556.24 | +60.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +18 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +18 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 544 B | 545 B | ⚠️ +1 B |
| withRouter.html gzip | 524 B | 525 B | ⚠️ +1 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,14 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (
+          url.match(/^\/(?!\/)/) !== null ||
+          url.startsWith("#") ||
+          url.startsWith("?")
+        )
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4538,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4553,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-73cab4cce3e523a8.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 21.5s | 21.7s | ⚠️ +165ms |
| buildDurationCached | 7.3s | 7.3s | ⚠️ +18ms |
| nodeModulesSize | 477 MB | 477 MB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.854 | 3.934 | ⚠️ +0.08 |
| / avg req/sec | 648.59 | 635.52 | ⚠️ -13.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.657 | 1.685 | ⚠️ +0.03 |
| /error-in-render avg req/sec | 1509.08 | 1483.69 | ⚠️ -25.39 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB |  [...]

2022-04-08 06:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | ⚠️ +30ms |
| buildDurationCached | 6s | 6s | -46ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.975 | 2.992 | ⚠️ +0.02 |
| / avg req/sec | 840.31 | 835.67 | ⚠️ -4.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.158 | 1.141 | -0.02 |
| /error-in-render avg req/sec | 2159.81 | 2191.77 | +31.96 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 524 B | 526 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,10 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (/^\/(?!\/)/.test(url) || url.startsWith("#") || url.startsWith("?"))
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,9 +4534,9 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoProto = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
         var urlParts = urlAsStringNoProto.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
@@ -4549,7 +4549,8 @@
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
             urlAsStringNoProto
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-0b208bad994d549d.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-0b208bad994d549d.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-0b208bad994d549d.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 17.8s | 17.5s | -232ms |
| buildDurationCached | 6s | 6s | ⚠️ +3ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +20 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.027 | 2.97 | -0.06 |
| / avg req/sec | 825.79 | 841.89 | +16.1 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.159 | 1.156 | 0 |
| /error-in-render avg req/sec | 2157.77 | 2163.43 | +5.66 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +9 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | [...]

2022-04-08 18:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.1s | ⚠️ +9ms |
| buildDurationCached | 6.2s | 6.1s | -81ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.066 | 3.039 | -0.03 |
| / avg req/sec | 815.45 | 822.52 | +7.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.182 | 1.176 | -0.01 |
| /error-in-render avg req/sec | 2115.56 | 2125.56 | +10 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ⚠️ +11 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ⚠️ +11 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.64 kB | 5.64 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 544 B | 546 B | ⚠️ +2 B |
| withRouter.html gzip | 524 B | 526 B | ⚠️ +2 B |
| Overall change | 1.6 kB | 1.6 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -4448,10 +4448,10 @@
       }
       function isLocalURL(url) {
         // prevent a hydration mismatch on href for url with anchor refs
-        if (url.startsWith("/") || url.startsWith("#") || url.startsWith("?"))
+        if (/^\/(?!\/)/.test(url) || url.startsWith("#") || url.startsWith("?"))
           return true;
         try {
-          // absolute urls can be local if they are on the same origin
+          // absolute and scheme-relative urls can be local if they are on the same origin
           var locationOrigin = (0, _utils).getLocationOrigin();
           var resolved = new URL(url, locationOrigin);
           return (
@@ -4534,11 +4534,11 @@
             : (0, _formatUrl).formatWithValidation(href);
         // repeated slashes and backslashes in the URL are considered
         // invalid and will never match a Next.js page/file
-        var urlProtoMatch = urlAsString.match(/^[a-zA-Z]{1,}:\/\//);
-        var urlAsStringNoProto = urlProtoMatch
-          ? urlAsString.slice(urlProtoMatch[0].length)
+        var urlSchemeMatch = urlAsString.match(/^(?:[a-zA-Z]+:)?\/\//);
+        var urlAsStringNoScheme = urlSchemeMatch
+          ? urlAsString.slice(urlSchemeMatch[0].length)
           : urlAsString;
-        var urlParts = urlAsStringNoProto.split("?");
+        var urlParts = urlAsStringNoScheme.split("?");
         if ((urlParts[0] || "").match(/(\/\/|\\)/)) {
           console.error(
             "Invalid href passed to next/router: ".concat(
@@ -4547,9 +4547,10 @@
             )
           );
           var normalizedUrl = (0, _utils).normalizeRepeatedSlashes(
-            urlAsStringNoProto
+            urlAsStringNoScheme
           );
-          urlAsString = (urlProtoMatch ? urlProtoMatch[0] : "") + normalizedUrl;
+          urlAsString =
+            (urlSchemeMatch ? urlSchemeMatch[0] : "") + normalizedUrl;
         }
         // Return because it cannot be routed by the Next.js router
         if (!isLocalURL(urlAsString)) {
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-57ecebdd38e8e5a5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-57ecebdd38e8e5a5.js"
       defer=""
     ></script>
     <script
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -19,7 +19,7 @@
       defer=""
     ></script>
     <script
-      src="/_next/static/chunks/main-26c4d970f7a13427.js"
+      src="/_next/static/chunks/main-57ecebdd38e8e5a5.js"
       defer=""
     ></script>
     <script
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| buildDuration | 18.1s | 18s | -135ms |
| buildDurationCached | 6.1s | 6s | -87ms |
| nodeModulesSize | 478 MB | 478 MB | ⚠️ +24 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.014 | 3.025 | ⚠️ +0.01 |
| / avg req/sec | 829.45 | 826.31 | ⚠️ -3.14 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.195 | 1.188 | -0.01 |
| /error-in-render avg req/sec | 2092.9 | 2104.63 | +11.73 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ⚠️ +9 B |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ⚠️ +9 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | SethFalco/next.js 30947-schema-relative-urls | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | ve [...]

2022-04-11 09:41 UTC, balazsorban44 commented
Please stop force pushing (unless pushing actual changes, but a regular commit might be better anyway, to see the history), as it creates some noise on the PR (I counted 20+ so far) and generally has no effect on the speed we review changes.

If you are trying to run the test suites, you can do so locally: https://github.com/vercel/next.js/blob/canary/contributing.md#testing :+1:

2022-04-11 10:40 UTC, SethFalco commented
> Please stop force pushing (unless pushing actual changes, but a regular commit might be better anyway, to see the history), as it creates some noise on the PR (I counted 20+ so far) and generally has no effect on the speed we review PRs.

Ahh sorry, I was just checking back here occasionally and whenever the `This branch is out-of-date with the base branch` was displayed on GitHub, I clicked `Rebase branch`.

![image](https://user-images.githubusercontent.com/22801583/162723519-b588b08c-4adc-4cbb-a33e-f55d6729e9a1.png)

Figured it'd be handy to:
1. Know CI still passes with latest changes.
2. So whoever reviews it doesn't have to. ^-^'

I realized it was coming off a bit spammy with how long the comment section has gotten though, sorry about that!

2022-05-22 05:31 UTC, ijjk requested changes
Hi, as mentioned previously I don't think we want to support this as this could open the door to accidental open-redirects and is modifying the behavior of our tests ensuring open-redirects aren't occurring. 

A wrapper component around `next/link` could be added in your application to manually add the actual protocol to the `href` making this safer and allowing the schema to be relative to the current context.

2022-05-22 05:31 UTC, closed without merging

2022-05-22 06:45 UTC, SethFalco commented
@ijjk Fair enough, just one last question!

Would you be happier with this if I didn't modify existing behavior and tests? For example, if I added a prop to `next/link` like `allowSchemaRelative`? Defaults to `false` and nothing changes for any existing code or tests, pass `true` and it'll do what we see in this PR?

If not, that's no problem. I'll just handle it in my application! Just thought it was worth asking.

2022-05-22 10:17 UTC, SethFalco commented
I opted to update the commit with the 2nd proposal though, have any thoughts on it?
I think the only thing left would be deciding what should happen when a non-allowed URL type is used, and adding tests.

https://github.com/SethFalco/next.js/commit/0f8c1e02ad013ec40301787df41d974328c29ad8

This makes it, so a developer can do the following to further limit URLs that are passed in. For example, if they only expect domain relative URLs, it can include both scheme and absolute URLs then:

```js
import Link, { LinkType } from 'next/link'

export default function Nav() {
  return (
    <Link href="/" passHref linkTypes={[LinkType.DomainRelative]}>
      <a>
        <FormattedMessage defaultMessage="Home" description="Nav: Index name"/>
      </a>
    </Link>
  );
}

```

2022-05-23 15:54 UTC, ijjk commented
I think providing separate linkTypes like that increases the room for accidentally navigating incorrectly and potential open-redirects and the safest bet is to be explicit with providing the protocol or keep the href relative. Feel free to open an RFC on the ideas discussion thread to get feedback though!