Clarify with commas
vercel/next.js pull request #31224
Opened 2021-11-09 20:07 UTC by TurekBot

Adds a few commas where they could improve the clarity of the sentence.

- [X] Make sure the linting passes by running `yarn lint`

2021-11-09 20:08 UTC, styfle commented on docs/routing/introduction.md
> +In the example above, we have multiple links; each one maps a path (`href`) to a known page:
```suggestion
In the example above, we have multiple links. Each one maps a path (`href`) to a known page:
```

2021-11-10 00:54 UTC, styfle submitted a review, later dismissed

2021-11-15 12:37 UTC, timneutkens approved these changes, later dismissed

2021-11-15 12:46 UTC, molebox requested changes, later dismissed

2021-11-15 12:46 UTC, molebox commented on docs/routing/introduction.md
> +In the example above, we have multiple links. Each one maps a path (`href`) to a known page:
```suggestion
The example above uses multiple links. Each one maps a path (`href`) to a known page:
```

2021-11-15 13:04 UTC, timneutkens approved these changes

2021-11-15 14:03 UTC, styfle approved these changes

2021-11-15 14:37 UTC, merged