Add example with cookies-next package
vercel/next.js pull request #31243
Opened 2021-11-10 12:13 UTC by andreizanik

Add example with cookies-next package

2022-06-27 15:08 UTC, balazsorban44 requested changes
Thanks, could you have a read of https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples and make the changes necessary? :pray:

Let me know if you need any help!

2022-06-28 12:44 UTC, andreizanik commented
> Thanks, could you convert this to TypeScript to match our [example guidelines](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)? 🙏
> 
> Let me know if you need any help!

Done!

2022-06-29 11:51 UTC, balazsorban44 commented on examples/with-cookies-next/.gitignore
> +.vercel
```suggestion
.vercel

# typescript
*.tsbuildinfo
```

2022-06-29 12:00 UTC, balazsorban44 commented on examples/with-cookies-next/package.json
> +    "@types/react": "^18.0.14",
`@types/node` should be added as well

2022-06-30 10:05 UTC, balazsorban44 commented on examples/with-cookies-next/README.md
> +Deploy the example using [Vercel](https://vercel.com?utm_source=github&utm_medium=readme&utm_campaign=next-example):
```suggestion
## Deploy your own

Deploy the example using [Vercel](https://vercel.com?utm_source=github&utm_medium=readme&utm_campaign=next-example) or preview live with [StackBlitz](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-cookies-next)
```

Let's make this consistent with other examples

2022-06-30 10:05 UTC, balazsorban44 submitted a review, later dismissed
Thanks!

2022-06-30 10:53 UTC, andreizanik commented
> Thanks!

There was a problem with automatic checks due to the style code. I fixed it.
I also changed the function name to match the cookie container idiom (as of the latest release of the package).

Please check the pull request again

2022-07-06 14:33 UTC, balazsorban44 approved these changes, later dismissed

2022-07-06 16:52 UTC, andreizanik commented
I get a new problem with auto check 

Build, test, and deploy / lint (pull_request) 
```
lerna notice cli v4.0.0
lerna info ci enabled
lerna ERR! EWORKSPACES Yarn workspaces need to be defined in the root package.json.
lerna ERR! EWORKSPACES See: https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#--use-workspaces
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "lint-typescript" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

I followed the link and realized what I need to add `"workspaces": ["packages/*"]` to package.json 
with this line i get no error locally 

I also found that the prettier finds an error in the `file/examples/cms-tina/.tina/__generated__/schema.gql` 

But this file has a comment
```
# DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
```

After that I did not add any edits, because I do not know how to do it right. I think i need advice

2022-07-22 15:28 UTC, ijjk approved these changes

2022-07-22 15:32 UTC, merged