Fix HMR for middleware #30791
vercel/next.js pull request #31548
Opened 2021-11-17 17:17 UTC by javivelasco

Fixes #30791

The issue is that with Middleware we are introducing client compilation on a new layer. When a middleware changes (or is dropped after some time), Webpack reorganizes non-user modules as they are duplicated across different layer. This is currently triggering a full reload.

This also brings tests for HMR:
- Refresh on a Middleware change
- HMR works after a middleware compilation change.

2021-11-17 17:19 UTC, shuding approved these changes, later dismissed
🤯

2021-11-17 17:31 UTC, ijjk commented
## Failing test suites <!--4385847391-->
Commit: 6094af5a74bfad1fe94e2785fe279041e8f1fb4b

**test/integration/css-minify/test/index.test.js** 
- css-minify > should minify correctly by removing whitespace

<details>
<summary>Expand output</summary>

  ● css-minify › should minify correctly by removing whitespace

    command failed with code 1
    info  - Checking validity of types...
    error - ESLint: Plugin "react" was conflicted between "../../test/.eslintrc.json » eslint-config-next" and "../../.eslintrc.json".
    info  - Creating an optimized production build...
    Failed to compile.

    ./styles/global.css
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .a {
    |   --var-1: 0;
    |   --var-2: 0;

    Import trace for requested module:
    ./pages/_app.js


    > Build failed because of webpack errors

      215 | }
      216 |
    > 217 | export function runNextCommandDev(argv, stdOut, opts = {}) {
          |                               ^
      218 |   const nextDir = path.dirname(require.resolve('next/package'))
      219 |   const nextBin = path.join(nextDir, 'dist/bin/next')
      220 |   const cwd = opts.cwd || nextDir

      at ChildProcess.<anonymous> (lib/next-test-utils.js:217:31)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      398 |   return new Promise((resolve, reject) => {
      399 |     const newArgs = [
    > 400 |       ...args,
          |               ^
      401 |       function (err, res) {
      402 |         if (err) return reject(err)
      403 |         resolve(res)

      at Object.killApp (lib/next-test-utils.js:400:32)
      at integration/css-minify/test/index.test.js:30:35

</details>

2021-11-17 19:02 UTC, timneutkens requested changes
Looks like this is breaking css handling 🤔

2021-11-18 13:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24.9s | ⚠️ +1.1s |
| buildDurationCached | 4.9s | 5.5s | ⚠️ +542ms |
| nodeModulesSize | 338 MB | 338 MB | ⚠️ +812 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.944 | 4.186 | ⚠️ +0.24 |
| / avg req/sec | 633.92 | 597.29 | ⚠️ -36.63 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.772 | 2.009 | ⚠️ +0.24 |
| /error-in-render avg req/sec | 1411.18 | 1244.17 | ⚠️ -167.01 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ⚠️ +1 B |
| _error-HASH.js gzip | 194 B | 195 B | ⚠️ +1 B |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 330 B | ⚠️ +3 B |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | -1 B |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 637 B | ⚠️ +2 B |
| image-HASH.js gzip | 4.44 kB | 4.44 kB | -5 B |
| index-HASH.js gzip | 263 B | 260 B | -3 B |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | -3 B |
| routerDirect..HASH.js gzip | 321 B | 317 B | -4 B |
| script-HASH.js gzip | 383 B | 382 B | -1 B |
| withRouter-HASH.js gzip | 318 B | 317 B | -1 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | -11 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 522 B | -1 B |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 515 B | -1 B |
| Overall change | 1.57 kB | 1.57 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1,25 +1,25 @@
 self.__BUILD_MANIFEST = {
   __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
-  "/": ["static\u002Fchunks\u002Fpages\u002Findex-22405fb865808942.js"],
-  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-97db2c91e74bb63f.js"],
-  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-8c7b17a56b7abb6e.js"],
+  "/": ["static\u002Fchunks\u002Fpages\u002Findex-538d4ef4dfefdafa.js"],
+  "/_error": ["static\u002Fchunks\u002Fpages\u002F_error-88e9c8803ca8c8f6.js"],
+  "/amp": ["static\u002Fchunks\u002Fpages\u002Famp-5b560ebfbb415023.js"],
   "/css": [
     "static\u002Fcss\u002F94fdbc56eafa2039.css",
-    "static\u002Fchunks\u002Fpages\u002Fcss-deb2f2a41a5bf511.js"
+    "static\u002Fchunks\u002Fpages\u002Fcss-e866a80f7d9a00bc.js"
   ],
   "/dynamic": [
-    "static\u002Fchunks\u002Fpages\u002Fdynamic-0ead1841ed0002db.js"
+    "static\u002Fchunks\u002Fpages\u002Fdynamic-aa3c46633624f3e4.js"
   ],
-  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
-  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-2a8b03d7b35abada.js"],
-  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-fa969765a079642e.js"],
+  "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-2e203ef347a4269e.js"],
+  "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8cc8dd0406ae511f.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-adf3fc74a490008a.js"],
+  "/link": ["static\u002Fchunks\u002Fpages\u002Flink-4c9b1a96b6646f44.js"],
   "/routerDirect": [
-    "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
+    "static\u002Fchunks\u002Fpages\u002FrouterDirect-239a858e7c4675a5.js"
   ],
-  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-52713a82413f16bb.js"],
+  "/script": ["static\u002Fchunks\u002Fpages\u002Fscript-72736f3e70cfa9cc.js"],
   "/withRouter": [
-    "static\u002Fchunks\u002Fpages\u002FwithRouter-50f69b5840cc7abf.js"
+    "static\u002Fchunks\u002Fpages\u002FwithRouter-2b5b9cb30c6e2872.js"
   ],
   sortedPages: [
     "\u002F",
```
</details>
<details>
<summary>Diff for <strong>_app-HASH.js</strong></summary>

```diff
@@ -1,23 +1,6 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [888],
   {
-    /***/ 915: /***/ function(
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/_app",
-        function() {
-          return __webpack_require__(6029);
-        }
-      ]);
-      if (false) {
-      }
-
-      /***/
-    },
-
     /***/ 6029: /***/ function(
       __unused_webpack_module,
       exports,
@@ -272,6 +255,23 @@
       App.getInitialProps = appGetInitialProps;
       exports["default"] = App; //# sourceMappingURL=_app.js.map
 
+      /***/
+    },
+
+    /***/ 463: /***/ function(
+      __unused_webpack_module,
+      __unused_webpack_exports,
+      __webpack_require__
+    ) {
+      (window.__NEXT_P = window.__NEXT_P || []).push([
+        "/_app",
+        function() {
+          return __webpack_require__(6029);
+        }
+      ]);
+      if (false) {
+      }
+
       /***/
     }
   },
@@ -281,7 +281,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [774, 179], function() {
-      return __webpack_exec__(915), __webpack_exec__(387);
+      return __webpack_exec__(463), __webpack_exec__(387);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>_error-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [820],
   {
-    /***/ 4977: /***/ function(
+    /***/ 7003: /***/ function(
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -24,7 +24,7 @@
       return __webpack_require__((__webpack_require__.s = moduleId));
     };
     /******/ __webpack_require__.O(0, [888, 774, 179], function() {
-      return __webpack_exec__(4977);
+      return __webpack_exec__(7003);
     });
     /******/ var __webpack_exports__ = __webpack_require__.O();
     /******/ _N_E = __webpack_exports__;
```
</details>
<details>
<summary>Diff for <strong>amp-HASH.js</strong></summary>

```diff
@@ -11,23 +11,6 @@
       /***/
     },
 
-    /***/ 6071: /***/ function(
-      __unused_webpack_module,
-      __unused_webpack_exports,
-      __webpack_require__
-    ) {
-      (window.__NEXT_P = window.__NEXT_P || []).push([
-        "/amp",
-        function() {
-          return __webpack_require__(1910) [...]

2021-11-18 13:53 UTC, ijjk commented
## Failing test suites <!--4395832868-->
Commit: 9f7c4f40eb94cb93792b7f1a3c6dd315bb2a1c8c

**test/integration/middleware/with-eval/test/index.test.js** 
- Middleware usage of dynamic code evaluation > dev mode > shows a warning when running code with eval
- Middleware usage of dynamic code evaluation > production mode > should have middleware warning during build

<details>
<summary>Expand output</summary>

  ● Middleware usage of dynamic code evaluation › dev mode › shows a warning when running code with eval

    expect(received).toContain(expected) // indexOf

    Expected substring: "Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware"
    Received string:    "warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
    wait  - compiling /_middleware...
    event - compiled client and server successfully in 173 ms (185 modules)
    "

      39 |     afterAll(() => killApp(context.app))
      40 |
    > 41 |     it('shows a warning when running code with eval', async () => {
         |                            ^
      42 |       const res = await fetchViaHTTP(context.appPort, `/using-eval`)
      43 |       const json = await res.json()
      44 |       await waitFor(500)

      at Object.<anonymous> (integration/middleware/with-eval/test/index.test.js:41:28)

  ● Middleware usage of dynamic code evaluation › production mode › should have middleware warning during build

    expect(received).toContain(expected) // indexOf

    Expected substring: "Failed to compile"
    Received string:    "error - ESLint: Plugin \"react\" was conflicted between \"../../test/.eslintrc.json » eslint-config-next\" and \"../../.eslintrc.json\".
    warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
    "

      70 |
      71 |   describe('production mode', () => {
    > 72 |     let buildResult
         |                    ^
      73 |
      74 |     beforeAll(async () => {
      75 |       buildResult = await nextBuild(context.appDir, undefined, {

      at Object.<anonymous> (integration/middleware/with-eval/test/index.test.js:72:40)

</details>

2021-11-18 15:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| buildDuration | 23.3s | 23.3s | -38ms |
| buildDurationCached | 4.4s | 4.5s | ⚠️ +111ms |
| nodeModulesSize | 338 MB | 338 MB | ⚠️ +682 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.902 | 3.996 | ⚠️ +0.09 |
| / avg req/sec | 640.68 | 625.63 | ⚠️ -15.05 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.065 | 2.148 | ⚠️ +0.08 |
| /error-in-render avg req/sec | 1210.71 | 1163.65 | ⚠️ -47.06 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.45 kB | ⚠️ +1 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-2a8b03d7b35abada.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-fa969765a079642e.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function() {
-          return __webpack_require__(3155);
+          return __webpack_require__(5924);
         }
       ]);
       if (false) {
@@ -969,7 +969,7 @@
       /***/
     },
 
-    /***/ 3155: /***/ function(
+    /***/ 5924: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| buildDuration | 25.3s | 24.8s | -441ms |
| buildDurationCached | 4.5s | 4.5s | ⚠️ +22ms |
| nodeModulesSize | 338 MB | 338 MB | ⚠️ +682 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.878 | 3.983 | ⚠️ +0.1 |
| / avg req/sec | 644.58 | 627.74 | ⚠️ -16.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.152 | 2.198 | ⚠️ +0.05 |
| /error-in-render avg req/sec | 1161.92 | 1137.32 | ⚠️ -24.6 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.47 kB | ⚠️ +1 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 516 B | 516 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-2a8b03d7b35abada.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-fa969765a079642e.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24 [...]

2021-11-18 18:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| buildDuration | 21.8s | 21s | -847ms |
| buildDurationCached | 4.1s | 4.2s | ⚠️ +49ms |
| nodeModulesSize | 338 MB | 338 MB | ⚠️ +679 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.808 | 3.564 | -0.24 |
| / avg req/sec | 656.44 | 701.38 | +44.94 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.073 | 1.991 | -0.08 |
| /error-in-render avg req/sec | 1206.17 | 1255.71 | +49.54 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 635 B | 635 B | ✓ |
| image-HASH.js gzip | 4.44 kB | 4.45 kB | ⚠️ +1 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 1.87 kB | 1.87 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.3 kB | 13.3 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 535 B | 535 B | ✓ |
| withRouter.html gzip | 517 B | 517 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-2a8b03d7b35abada.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-fa969765a079642e.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function() {
-          return __webpack_require__(3155);
+          return __webpack_require__(5924);
         }
       ]);
       if (false) {
@@ -969,7 +969,7 @@
       /***/
     },
 
-    /***/ 3155: /***/ function(
+    /***/ 5924: /***/ function(
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| buildDuration | 23.9s | 22.6s | -1.2s |
| buildDurationCached | 4s | 4.1s | ⚠️ +115ms |
| nodeModulesSize | 338 MB | 338 MB | ⚠️ +679 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.663 | 3.944 | ⚠️ +0.28 |
| / avg req/sec | 682.49 | 633.85 | ⚠️ -48.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.921 | 2.102 | ⚠️ +0.18 |
| /error-in-render avg req/sec | 1301.64 | 1189.59 | ⚠️ -112.05 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 28.6 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.5 kB | 72.5 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 622 B | 622 B | ✓ |
| image-HASH.js gzip | 4.46 kB | 4.47 kB | ⚠️ +1 B |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 1.91 kB | 1.91 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 459 B | -1 B |
| Overall change | 460 B | 459 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | javivelasco/next.js fix-30791 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 523 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 517 B | 517 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-7100d3b2a548f0e4.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-ff60bc61acd2698b.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-2a8b03d7b35abada.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-91f7c5ff8695376c.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-fa969765a079642e.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-76232dd6bc335a24.js"
```
</de [...]

2021-11-18 18:19 UTC, timneutkens approved these changes

2021-11-18 18:23 UTC, merged