typo fixed
vercel/next.js pull request #32800
Opened 2021-12-24 18:45 UTC by ar-pavel

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

2021-12-24 19:25 UTC, balazsorban44 approved these changes

2021-12-24 22:07 UTC, styfle reviewed
I think this is intentional since the two method signatures are

- redirect(path)
- redirect(status, path)

2021-12-25 00:30 UTC, ijjk commented on docs/api-routes/response-helpers.md
> +- `res.redirect([status], path)` - Redirects to a specified path or URL. `status` must be a valid [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). If not specified, `statu
This does not appear to be a typo as this syntax `[param,]` is used to denote an optional argument, similar documentation can be seen [here](http://expressjs.com/en/5x/api.html#res.redirect)

2021-12-25 00:31 UTC, ijjk requested changes
Yeah as per above this is intentional and similar syntax for documenting an optional argument can be seen [here](http://expressjs.com/en/5x/api.html#res.redirect)

2021-12-25 00:31 UTC, closed without merging