Update Advanced Error Page section in custom-error-page.md
vercel/next.js pull request #32873
Opened 2021-12-28 12:04 UTC by glenngijsberts

## Description
Update More Advanced Error Page Customizing section in custom-error-page.md, by using `getServerSideProps` instead of `getInitialProps`.

Tested locally in my own project and seems to be working as expected. However, on the same docs page there is an example that is using `getServerSideProps` for the page where the `Error` component is being used so i'm wondering: is there a reason why the example of the custom `Error` page isn't using `getServerSideProps`? I was thinking that it maybe had the same constraint as the custom `Document` & `App` pages, where Next.js Data Fetching methods like `getServerSideProps` are not supported.

If there are no constraints, this update seems good to me, because it aligns with the latest practices of Next.js. Otherwise maybe a good idea to add the same line as https://nextjs.org/docs/advanced-features/custom-app#caveats where it says that those data fetching methods are not supported.

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

2021-12-29 16:12 UTC, ijjk requested changes
Hi, `getServerSideProps` isn't fully compatible as a replacement for `getInitialProps` with `_error` here as we don't provide the `err` in the `context` passed to `getServerSideProps` so I don't think we should update to recommend this in the documentation here currently. We also don't have tests covering support for `getServerSideProps` in `_error` currently.

2021-12-29 18:55 UTC, glenngijsberts commented
@ijjk right, was already thinking something like that is the case. WDYT about adding a "caveats" section with this info included? Like there is for `_document` and `_app`?

2022-01-01 17:19 UTC, ijjk commented
Yeah might be good to add a caveat mentioning that `getServerSideProps` is not officially supported in `_error`

2022-01-05 02:47 UTC, balazsorban44 commented
@glenngijsberts are you interested in updating the Caveats section?

2022-01-07 12:34 UTC, glenngijsberts commented
@balazsorban44 @ijjk yes! I'll make sure to update that, and i'll close this :)

2022-01-07 12:34 UTC, closed without merging