Fix a typo in docs on data fetching
vercel/next.js pull request #33004
Opened 2022-01-04 22:27 UTC by DerGut

While reading the docs, I stumbled over this phrasing. It seems to have been introduced with the whole [section](https://nextjs.org/docs/basic-features/data-fetching#reading-files-use-processcwd) on _Reading files: Use process.cwd()_ with https://github.com/vercel/next.js/pull/11084.

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

2022-01-04 22:34 UTC, styfle approved these changes

2022-01-04 23:02 UTC, leerob requested changes
Let's pause until this ships: https://github.com/vercel/next.js/pull/30615

2022-01-05 02:52 UTC, balazsorban44 approved these changes

2022-01-13 15:44 UTC, timneutkens approved these changes

2022-01-15 02:50 UTC, balazsorban44 commented
The section is now gone since #30615 has been merged. But thank you for the PR anyway!

2022-01-15 02:50 UTC, closed without merging

2022-01-18 11:21 UTC, DerGut commented
Alright, thanks! 👌🏻