Fix ambiguous flags in Dockerfile example
vercel/next.js pull request #33417
Opened 2022-01-18 06:16 UTC by vertti

At least with Docker xx this Dockerfile fails to both `adduser` and `addgroup` commands due to ambiguous flags. The error message for example for `addgroup` is:

```
#5 0.292 Option g is ambiguous (gecos, gid, group)
#5 0.292 Option s is ambiguous (shell, system)
```
This PR switches both commands to use the long-format flags. I think they are also more understandable for the readers of the Dockerfile.

2022-01-18 15:41 UTC, balazsorban44 approved these changes

2022-01-20 12:02 UTC, balazsorban44 requested changes
Thanks, I just tested it (Ubuntu 21.10, Docker 20.10.12), and FWIW, I did not get the warning, but I think agree that it's still better for readability anyway.

Had a small comment only, could you address it?

2022-01-20 12:02 UTC, balazsorban44 commented on examples/with-docker/Dockerfile
> +RUN adduser --system --uid 1001 nextjs
```suggestion
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
```

Let's have the flags in the same order as well

2022-02-05 21:20 UTC, ijjk approved these changes

2022-02-05 21:26 UTC, merged