Update authentication.md
vercel/next.js pull request #33483
Opened 2022-01-20 03:01 UTC by tharakabimal

Switched the example links

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

2022-01-20 11:08 UTC, balazsorban44 requested changes
Why are the two changes the opposite of each other?

The [repo's README](https://github.com/vvo/iron-session) shows the current URL, not the one you recommend. :thinking:

@vvo could you verify which one is correct?

2022-01-20 13:42 UTC, tharakabimal commented
Hey @vvo according to the doc [this](https://next-with-iron-session.vercel.app/profile-sg) is not supposed to show the loader.
![image](https://user-images.githubusercontent.com/3351988/150349535-2326943e-aa1a-457d-8d5d-37ce94ede750.png)

2022-01-20 17:02 UTC, vvo requested changes
You can accept the request changes

2022-01-21 04:14 UTC, leerob approved these changes

2022-01-21 11:21 UTC, merged