feat(cli): auto build next production build
vercel/next.js pull request #33970
Opened 2022-02-04 04:13 UTC by j-mendez

run next build if production instance not found

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

2022-02-04 04:14 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +    .catch(async (err) => {
```suggestion
    .catch((err) => {
```

2022-02-04 04:15 UTC, j-mendez commented on packages/next/cli/next-start.ts
```suggestion
import { existsSync } from 'fs'
```

2022-02-04 04:16 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +import { existsSync } from 'fs'
```suggestion
import { existsSync } from 'fs'

```

2022-02-04 04:21 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +    await nextBuild(args)
```suggestion
    await nextBuild(args as string[])
```

2022-02-04 04:23 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +    await nextBuild(args as string[])
we need `await` in order for the server to start after the build finishes or else it errors.

2022-02-04 04:47 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +const nextStart: cliCommand = async (argv) => {
```suggestion
const nextStart: cliCommand = async (argv: unknown) => {
```

2022-02-04 05:01 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +const nextStart: cliCommand = async (argv: unknown) => {
```suggestion
const nextStart: cliCommand = async (argv) => {
```

2022-02-04 05:03 UTC, j-mendez commented on packages/next/cli/next-start.ts
> +    await nextBuild(args as string[])
```suggestion
    // @ts-ignore
    await nextBuild(args)
```

2022-02-04 05:08 UTC, ijjk commented
## Failing test suites <!--5175341728-->
Commit: fe761eb007012c8432dde6ec30aa186d1dc1fdb1

**test/integration/404-page-app/test/index.test.js** 
- 404 Page Support with _app > production mode > should not output static 404 if _app has getInitialProps
- 404 Page Support with _app > production mode > should still use 404 page

<details>
<summary>Expand output</summary>

  ● 404 Page Support with _app › production mode › should not output static 404 if _app has getInitialProps

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:35431/404
    =========================== logs ===========================
    navigating to "http://localhost:35431/404", waiting until "load"
    ============================================================

      124 |       this.activeTrace = encodeURIComponent(url)
      125 |     }
    > 126 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      127 |   }
      128 |
      129 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:126:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:84:3)
      at Object.<anonymous> (integration/404-page-app/test/index.test.js:42:23)

  ● 404 Page Support with _app › production mode › should still use 404 page

    FetchError: request to http://localhost:35431/abc failed, reason: connect ECONNREFUSED 127.0.0.1:35431

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      379 | // Kill a launched app
      380 | export async function killApp(instance) {
    > 381 |   await killProcess(instance.pid)
          |                              ^
      382 | }
      383 |
      384 | export async function startApp(app) {

      at Object.killApp (lib/next-test-utils.js:381:30)
      at integration/404-page-app/test/index.test.js:25:27

</details>

2022-02-04 05:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 17.2s | 17.9s | ⚠️ +736ms |
| buildDurationCached | 7s | 6.8s | -190ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +491 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.424 | 3.399 | -0.02 |
| / avg req/sec | 730.25 | 735.51 | +5.26 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.565 | 1.578 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1597.58 | 1583.99 | ⚠️ -13.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 20.8s | 21.4s | ⚠️ +613ms |
| buildDurationCached | 6.9s | 6.9s | -20ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +491 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.362 | 3.431 | ⚠️ +0.07 |
| / avg req/sec | 743.63 | 728.72 | ⚠️ -14.91 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.546 | 1.538 | -0.01 |
| /error-in-render avg req/sec | 1616.66 | 1625.91 | +9.25 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: fe761eb007012c8432dde6ec30aa186d1dc1fdb1

2022-02-04 05:32 UTC, ijjk commented
## Failing test suites <!--5175486389-->
Commit: 11ef68531d74107eab80baf00954dad1eb2ce191

**test/integration/404-page-app/test/index.test.js** 
- 404 Page Support with _app > production mode > should not output static 404 if _app has getInitialProps
- 404 Page Support with _app > production mode > should still use 404 page

<details>
<summary>Expand output</summary>

  ● 404 Page Support with _app › production mode › should not output static 404 if _app has getInitialProps

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:35599/404
    =========================== logs ===========================
    navigating to "http://localhost:35599/404", waiting until "load"
    ============================================================

      124 |       this.activeTrace = encodeURIComponent(url)
      125 |     }
    > 126 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      127 |   }
      128 |
      129 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:126:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:84:3)
      at Object.<anonymous> (integration/404-page-app/test/index.test.js:42:23)

  ● 404 Page Support with _app › production mode › should still use 404 page

    FetchError: request to http://localhost:35599/abc failed, reason: connect ECONNREFUSED 127.0.0.1:35599

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      379 | // Kill a launched app
      380 | export async function killApp(instance) {
    > 381 |   await killProcess(instance.pid)
          |                              ^
      382 | }
      383 |
      384 | export async function startApp(app) {

      at Object.killApp (lib/next-test-utils.js:381:30)
      at integration/404-page-app/test/index.test.js:25:27

</details>

2022-02-04 05:46 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 17.4s | 17.3s | -53ms |
| buildDurationCached | 6.9s | 6.9s | ⚠️ +8ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +484 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.207 | 3.257 | ⚠️ +0.05 |
| / avg req/sec | 779.63 | 767.56 | ⚠️ -12.07 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.455 | 1.445 | -0.01 |
| /error-in-render avg req/sec | 1718.55 | 1729.53 | +10.98 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 21.3s | 21.3s | ⚠️ +46ms |
| buildDurationCached | 6.8s | 7.1s | ⚠️ +309ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +484 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.193 | 3.162 | -0.03 |
| / avg req/sec | 782.91 | 790.72 | +7.81 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.443 | 1.448 | 0 |
| /error-in-render avg req/sec | 1732.57 | 1726.53 | ⚠️ -6.04 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 11ef68531d74107eab80baf00954dad1eb2ce191

2022-02-04 12:09 UTC, nicholascapo requested changes
Need to discuss more in https://github.com/axioscode/axios/pull/1617

2022-02-04 13:54 UTC, ijjk commented
## Failing test suites <!--5180053031-->
Commit: 33dd30f25cf8c1a454311349cfac02b152374a07

**test/integration/404-page-app/test/index.test.js** 
- 404 Page Support with _app > production mode > should not output static 404 if _app has getInitialProps
- 404 Page Support with _app > production mode > should still use 404 page

<details>
<summary>Expand output</summary>

  ● 404 Page Support with _app › production mode › should not output static 404 if _app has getInitialProps

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:44981/404
    =========================== logs ===========================
    navigating to "http://localhost:44981/404", waiting until "load"
    ============================================================

      124 |       this.activeTrace = encodeURIComponent(url)
      125 |     }
    > 126 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      127 |   }
      128 |
      129 |   back(): BrowserInterface {

      at Playwright.loadPage (lib/browsers/playwright.ts:126:16)
      at Object.webdriver [as default] (lib/next-webdriver.ts:84:3)
      at Object.<anonymous> (integration/404-page-app/test/index.test.js:42:23)

  ● 404 Page Support with _app › production mode › should still use 404 page

    FetchError: request to http://localhost:44981/abc failed, reason: connect ECONNREFUSED 127.0.0.1:44981

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)


  ● Test suite failed to run

    TypeError: Cannot read property 'pid' of undefined

      379 | // Kill a launched app
      380 | export async function killApp(instance) {
    > 381 |   await killProcess(instance.pid)
          |                              ^
      382 | }
      383 |
      384 | export async function startApp(app) {

      at Object.killApp (lib/next-test-utils.js:381:30)
      at integration/404-page-app/test/index.test.js:25:27

</details>

2022-02-04 14:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 19.9s | 20.5s | ⚠️ +630ms |
| buildDurationCached | 7.7s | 7.6s | -118ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +469 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.999 | 4.151 | ⚠️ +0.15 |
| / avg req/sec | 625.19 | 602.23 | ⚠️ -22.96 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.21 | 2.28 | ⚠️ +0.07 |
| /error-in-render avg req/sec | 1131.46 | 1096.7 | ⚠️ -34.76 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.3 kB | 27.3 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.37 kB | 1.37 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 24.5s | 24.6s | ⚠️ +123ms |
| buildDurationCached | 7.6s | 7.6s | -35ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +469 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.037 | 3.959 | -0.08 |
| / avg req/sec | 619.24 | 631.43 | +12.19 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.283 | 2.242 | -0.04 |
| /error-in-render avg req/sec | 1095.19 | 1115.01 | +19.82 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 33dd30f25cf8c1a454311349cfac02b152374a07

2022-02-04 14:34 UTC, nicholascapo submitted a review, later dismissed

2022-02-05 18:10 UTC, ijjk commented
## Failing test suites <!--5190939492-->
Commit: 9d2f08bde6104c48b74a16f9897d68b96c6fde3e

`yarn testheadless test/integration/amphtml-custom-validator/test/index.test.js` 
- AMP Custom Validator > should build and start successfully

<details>
<summary>Expand output</summary>

  ● AMP Custom Validator › should build and start successfully

    FetchError: request to http://localhost:38003/ failed, reason: connect ECONNREFUSED 127.0.0.1:38003

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-02-05 18:21 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.7s | ⚠️ +225ms |
| buildDurationCached | 6s | 5.7s | -238ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +472 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.069 | 3.027 | -0.04 |
| / avg req/sec | 814.49 | 825.96 | +11.47 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.347 | 1.258 | -0.09 |
| /error-in-render avg req/sec | 1855.72 | 1987.15 | +131.43 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 18.5s | 17.8s | -718ms |
| buildDurationCached | 5.9s | 5.7s | -153ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +472 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.016 | 3.168 | ⚠️ +0.15 |
| / avg req/sec | 828.97 | 789.14 | ⚠️ -39.83 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.307 | 1.298 | -0.01 |
| /error-in-render avg req/sec | 1912.75 | 1926.24 | +13.49 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 9d2f08bde6104c48b74a16f9897d68b96c6fde3e

2022-02-06 00:21 UTC, ijjk commented
## Failing test suites <!--5192171896-->
Commit: 0d9b04cdbf8a0893e8b0d7bee5b5e362cbf7d1f2

`yarn testheadless test/integration/404-page/test/index.test.js` 
- 404 Page Support > should not cache for custom 404 page with gssp and revalidate disabled
- 404 Page Support > should not cache for custom 404 page with gssp and revalidate enabled
- 404 Page Support > should not cache for custom 404 page without gssp
- 404 Page Support > falls back to _error correctly without pages/404
- 404 Page Support > shows error with getInitialProps in pages/404 build
- 404 Page Support > shows error with getInitialProps in pages/404 dev
- 404 Page Support > does not show error with getStaticProps in pages/404 build
- 404 Page Support > does not show error with getStaticProps in pages/404 dev
- 404 Page Support > shows error with getServerSideProps in pages/404 build
- 404 Page Support > shows error with getServerSideProps in pages/404 dev
- 404 Page Support > server mode > should use pages/404
- 404 Page Support > server mode > should set correct status code with pages/404
- 404 Page Support > server mode > should use pages/404 for .d.ts file
- 404 Page Support > server mode > should not error when visited directly
- 404 Page Support > server mode > should render _error for a 500 error still
- 404 Page Support > server mode > should output 404.html during build
- 404 Page Support > serverless mode > should use pages/404
- 404 Page Support > serverless mode > should set correct status code with pages/404
- 404 Page Support > serverless mode > should use pages/404 for .d.ts file
- 404 Page Support > serverless mode > should not error when visited directly
- 404 Page Support > serverless mode > should render _error for a 500 error still
- 404 Page Support > serverless mode > should output 404.html during build

<details>
<summary>Expand output</summary>

  ● 404 Page Support › server mode › should use pages/404

    FetchError: request to http://localhost:33621/abc failed, reason: connect ECONNREFUSED 127.0.0.1:33621

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › server mode › should set correct status code with pages/404

    FetchError: request to http://localhost:33621/abc failed, reason: connect ECONNREFUSED 127.0.0.1:33621

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › server mode › should use pages/404 for .d.ts file

    FetchError: request to http://localhost:33621/invalidExtension failed, reason: connect ECONNREFUSED 127.0.0.1:33621

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › server mode › should not error when visited directly

    FetchError: request to http://localhost:33621/404 failed, reason: connect ECONNREFUSED 127.0.0.1:33621

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › server mode › should render _error for a 500 error still

    FetchError: request to http://localhost:33621/err failed, reason: connect ECONNREFUSED 127.0.0.1:33621

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › server mode › should output 404.html during build

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      59 |     it('should output 404.html during build', async () => {
      60 |       const page = getPageFileFromPagesManifest(appDir, '/404')
    > 61 |       expect(page.endsWith('.html')).toBe(true)
         |                                      ^
      62 |     })
      63 |
      64 |     it('should add /404 to pages-manifest correctly', async () => {

      at Object.<anonymous> (integration/404-page/test/index.test.js:61:38)

  ● 404 Page Support › serverless mode › should use pages/404

    FetchError: request to http://localhost:40479/abc failed, reason: connect ECONNREFUSED 127.0.0.1:40479

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › serverless mode › should set correct status code with pages/404

    FetchError: request to http://localhost:40479/abc failed, reason: connect ECONNREFUSED 127.0.0.1:40479

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › serverless mode › should use pages/404 for .d.ts file

    FetchError: request to http://localhost:40479/invalidExtension failed, reason: connect ECONNREFUSED 127.0.0.1:40479

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › serverless mode › should not error when visited directly

    FetchError: request to http://localhost:40479/404 failed, reason: connect ECONNREFUSED 127.0.0.1:40479

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › serverless mode › should render _error for a 500 error still

    FetchError: request to http://localhost:40479/err failed, reason: connect ECONNREFUSED 127.0.0.1:40479

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › serverless mode › should output 404.html during build

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      59 |     it('should output 404.html during build', async () => {
      60 |       const page = getPageFileFromPagesManifest(appDir, '/404')
    > 61 |       expect(page.endsWith('.html')).toBe(true)
         |                                      ^
      62 |     })
      63 |
      64 |     it('should add /404 to pages-manifest correctly', async () => {

      at Object.<anonymous> (integration/404-page/test/index.test.js:61:38)

  ● 404 Page Support › should not cache for custom 404 page with gssp and revalidate disabled

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › should not cache for custom 404 page with gssp and revalidate enabled

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › should not cache for custom 404 page without gssp

    FetchError: request to http://localhost:38227/404 failed, reason: connect ECONNREFUSED 127.0.0.1:38227

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

  ● 404 Page Support › falls back to _error correctly without pages/404

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › shows error with getInitialProps in pages/404 build

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › shows error with getInitialProps in pages/404 dev

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › does not show error with getStaticProps in pages/404 build

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › does not show error with getStaticProps in pages/404 dev

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/universalify/index.js:21:54

  ● 404 Page Support › shows error with getServerSideProps in pages/404 build

    dest already exists.

      at ../node_modules/fs-extra/lib/move/move.js:41:31
      at ../node_modules/fs-extra/node_modules/un [...]

2022-02-06 00:53 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 21.9s | 21.7s | -227ms |
| buildDurationCached | 8.4s | 8.2s | -119ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +433 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.749 | 4.847 | ⚠️ +0.1 |
| / avg req/sec | 526.47 | 515.77 | ⚠️ -10.7 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.297 | 2.448 | ⚠️ +0.15 |
| /error-in-render avg req/sec | 1088.49 | 1021.22 | ⚠️ -67.27 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.2 kB | 71.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 326 B | 326 B | ✓ |
| dynamic-HASH.js gzip | 2.37 kB | 2.37 kB | ✓ |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 919 B | 919 B | ✓ |
| image-HASH.js gzip | 4.94 kB | 4.94 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.19 kB | 2.19 kB | ✓ |
| routerDirect..HASH.js gzip | 321 B | 321 B | ✓ |
| script-HASH.js gzip | 383 B | 383 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 26.4s | 26.4s | -91ms |
| buildDurationCached | 8.2s | 8.2s | -10ms |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +433 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.832 | 4.873 | ⚠️ +0.04 |
| / avg req/sec | 517.37 | 513.01 | ⚠️ -4.36 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.24 | 2.335 | ⚠️ +0.09 |
| /error-in-render avg req/sec | 1116.3 | 1070.71 | ⚠️ -45.59 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| 450.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 27.4 kB | 27.4 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.3 kB | 71.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 180 B | 180 B | ✓ |
| amp-HASH.js gzip | 305 B | 305 B | ✓ |
| css-HASH.js gzip | 321 B | 321 B | ✓ |
| dynamic-HASH.js gzip | 2.36 kB | 2.36 kB | ✓ |
| head-HASH.js gzip | 342 B | 342 B | ✓ |
| hooks-HASH.js gzip | 911 B | 911 B | ✓ |
| image-HASH.js gzip | 4.97 kB | 4.97 kB | ✓ |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.21 kB | 2.21 kB | ✓ |
| routerDirect..HASH.js gzip | 314 B | 314 B | ✓ |
| script-HASH.js gzip | 375 B | 375 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.3 kB | 14.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | j-mendez/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 0d9b04cdbf8a0893e8b0d7bee5b5e362cbf7d1f2

2022-02-06 15:10 UTC, ijjk requested changes
Hi, features like this require an existing RFC/feature request before opening a PR to allow discussion as mentioned in the PR template:

> Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR

I'm gonna close this pending the above, also I don't think we will want to mix `next build` into `next start` as this could make debugging deployment issues where `next build` was expected to be run but failed and then `next start` attempts re-running it.

2022-02-06 15:10 UTC, closed without merging

2022-02-06 15:13 UTC, j-mendez commented
@ijjk ahh that makes sense. So we would need a temp file to be created on next build to tell track that next js is amidst a build and then in next start check if that fill exist.