dynamic imports fix  for non webpack environments.
vercel/next.js pull request #3414
Opened 2017-12-07 20:35 UTC by PrudviGali

Added issue description in .

Featured detection condition comes handy rather than `typeof window` because of webpack specific methods `require.resolveWeak` and `resolve.ensure`.

2017-12-07 23:02 UTC, arunoda commented
Oh! I didn't see this: https://github.com/zeit/next.js/pull/3414
(Was thinking it's something else)

Sorry for that.
Looks interesting.

2017-12-07 23:05 UTC, arunoda approved these changes

2017-12-07 23:05 UTC, arunoda commented on server/build/babel/plugins/handle-import.js
> +    typeof require.resolveWeak !== 'function' ?
Could you add a comment where why we use this rather a simple `window` check.
It's better for someone who's reading the code.

2017-12-07 23:29 UTC, arunoda requested changes
Changing the status.

2017-12-08 00:53 UTC, PrudviGali commented
@arunoda No problem. I should have added documentation in the first place.

Anyhow added the requested changes.

2017-12-08 01:36 UTC, PrudviGali reviewed
Added requested changes

2017-12-08 01:50 UTC, arunoda approved these changes

2017-12-08 01:50 UTC, arunoda commented
@PrudviGali this looks great.
Thanks.

2017-12-08 01:50 UTC, merged

2017-12-08 01:51 UTC, PrudviGali commented
@arunoda Cool. Thanks.

2017-12-08 03:37 UTC, timneutkens commented
Very nice, thanks @PrudviGali!