ignoring all .env files
vercel/next.js pull request #34471
Opened 2022-02-17 12:31 UTC by dephraiim

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

2022-02-17 21:06 UTC, balazsorban44 requested changes, later dismissed
Hi, and thanks! We wouldn't want to ignore **all** `.env` files, only those that end with `.local`.

As per our docs, you could change it to `.env*.local` instead: https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables

2022-02-17 21:06 UTC, balazsorban44 commented on packages/create-next-app/templates/default/gitignore
> +.env*
```suggestion
.env*.local
```

2022-02-17 21:07 UTC, balazsorban44 commented on packages/create-next-app/templates/typescript/gitignore
> +.env*
```suggestion
.env*.local
```

2022-02-18 19:20 UTC, ijjk approved these changes

2022-02-18 21:26 UTC, merged