Allows to generate eslint reports using --output-file
vercel/next.js pull request #35154
Opened 2022-03-08 17:48 UTC by zomars

## Feature

- [x] Implements an existing feature request or RFC.

2022-03-09 18:26 UTC, housseindjirdeh commented
This would definitely be useful to have! Unfortunately, the ESLint Node API doesn't support `--output-file` as an option (see the list of options [here](https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions)).

If you would still like to see this flag supported, you'll need to include it as a [top-level option](https://github.com/vercel/next.js/blob/canary/packages/next/cli/next-lint.ts#L19) and then provide some custom logic for it within the `runLintCheck` method. You can see a similar example of how I added support for the `--quiet` flag in this [commit](https://github.com/vercel/next.js/pull/26280/commits/8866553ad55af772ba8d49504652381c4b78ceff).

If this is too much work to do, you can always fallback to using the default ESLint CLI to achieve your outcome (`npx eslint pages -format json --output-file test.json`).

Let me know if you have any thoughts or questions!

2022-03-09 18:26 UTC, housseindjirdeh requested changes
This would definitely be useful to have! Unfortunately, the ESLint Node API doesn't support `--output-file` as an option (see the list of options [here](https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions)).

If you would still like to see this flag supported, you'll need to include it as a [top-level option](https://github.com/vercel/next.js/blob/canary/packages/next/cli/next-lint.ts#L19) and then provide some custom logic for it within the `runLintCheck` method. You can see a similar example of how I added support for the `--quiet` flag in this [commit](https://github.com/vercel/next.js/pull/26280/commits/8866553ad55af772ba8d49504652381c4b78ceff).

If this is too much work to do, you can always fallback to using the default ESLint CLI to achieve your outcome (`npx eslint pages -format json --output-file test.json`).

Let me know if you have any thoughts or questions!

2022-03-30 14:08 UTC, housseindjirdeh commented
@zomars Friendly ping :)

Any chance you can work on this PR per my previous comment? I'll close this for the meantime, but happy to re-open it if you decide to work on it!

2022-03-30 14:08 UTC, closed without merging

2022-03-30 14:20 UTC, zomars commented
I can't seem to be able to reopen this PR

2022-04-22 02:27 UTC, pepoeverton commented
Hello folks @housseindjirdeh @zomars 
@zomars are you or someone else working on this PR? I'm working on a task that needs `eslint output`, so i can work on this PR if no one is on it!

2022-04-22 03:04 UTC, zomars commented
> Hello folks @housseindjirdeh @zomars 
> 
> @zomars are you or someone else working on this PR? I'm working on a task that needs `eslint output`, so i can work on this PR if no one is on it!
> 
> 

Hi @pepoeverton I haven't been able to work on this unfortunately.

2022-04-22 15:18 UTC, housseindjirdeh commented
@pepoeverton Thank you, yes please feel free to work on this! Let me know if you need me to open this PR but it'll probably be easier to submit a new one :)

2022-04-30 03:25 UTC, pepoeverton commented
Hi Folks, I just opened this [PR](https://github.com/vercel/next.js/pull/36420) that allows this flag, so feel free to review and comment if it needs some changes!