Switch lazy loading strategy to use native lazy loading by default
vercel/next.js pull request #35319
Opened 2022-03-14 23:19 UTC by cramforce

- Safari shipped support today and so all major browsers now support it.
- Falls back to `IntersectionObserver` based loading if the `lazyRoot` or `lazyBoundary` arguments are provided.
- Should improve performance in the case where lazy loaded images are actually visible quickly, by not making the HTTP fetch depend on hydration.

2022-03-14 23:30 UTC, ijjk commented
## Failing test suites <!--5658451946-->
Commit: 39c84701a2f896338a9c0c565f8d65bc903d8544

`yarn testheadless test/integration/async-modules/test/index.test.js` 
- Async modules > production mode > can render async AMP pages

<details>
<summary>Expand output</summary>

  ● Async modules › production mode › can render async AMP pages

    TIMED OUT: just now

    10 seconds ago

      474 |
      475 |   if (hardError) {
    > 476 |     throw new Error('TIMED OUT: ' + regex + '\n\n' + content)
          |           ^
      477 |   }
      478 |   return false
      479 | }

      at Object.check (lib/next-test-utils.js:476:11)
      at Object.<anonymous> (integration/async-modules/test/index.test.js:85:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-03-14 23:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| buildDuration | 15.9s | 16.3s | ⚠️ +385ms |
| buildDurationCached | 6.2s | 5.9s | -362ms |
| nodeModulesSize | 378 MB | 378 MB | ⚠️ +772 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.192 | 3.252 | ⚠️ +0.06 |
| / avg req/sec | 783.28 | 768.64 | ⚠️ -14.64 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.401 | 1.409 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 1784.55 | 1773.97 | ⚠️ -10.58 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.6 kB | 71.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.48 kB | 5.51 kB | ⚠️ +32 B |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.26 kB | 2.26 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.2 kB | 15.2 kB | ⚠️ +32 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 526 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -12,7 +12,7 @@ self.__BUILD_MANIFEST = {
   ],
   "/head": ["static\u002Fchunks\u002Fpages\u002Fhead-c58ed3c0b240dfa3.js"],
   "/hooks": ["static\u002Fchunks\u002Fpages\u002Fhooks-8642d114a09c62c5.js"],
-  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-8d15772e2d93d854.js"],
+  "/image": ["static\u002Fchunks\u002Fpages\u002Fimage-aa3b7585dcfbee9a.js"],
   "/link": ["static\u002Fchunks\u002Fpages\u002Flink-0b3d72804dab6202.js"],
   "/routerDirect": [
     "static\u002Fchunks\u002Fpages\u002FrouterDirect-00527c3f2207a902.js"
```
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -145,7 +145,7 @@
           _lazyRoot = _param.lazyRoot,
           lazyRoot = _lazyRoot === void 0 ? null : _lazyRoot,
           _lazyBoundary = _param.lazyBoundary,
-          lazyBoundary = _lazyBoundary === void 0 ? "200px" : _lazyBoundary,
+          lazyBoundary = _lazyBoundary === void 0 ? null : _lazyBoundary,
           className = _param.className,
           quality = _param.quality,
           width = _param.width,
@@ -247,17 +247,22 @@
         if (true && loadedImageURLs.has(src)) {
           isLazy = false;
         }
+        var canUseNativeLoadingStrategy = !(lazyRoot || lazyBoundary);
+        if (canUseNativeLoadingStrategy && isLazy) {
+          loading = "lazy";
+        }
         var ref1 = _slicedToArray(
             (0, _useIntersection).useIntersection({
               rootRef: lazyRoot,
-              rootMargin: lazyBoundary,
-              disabled: !isLazy
+              rootMargin: lazyBoundary || "200px",
+              disabled: !isLazy || canUseNativeLoadingStrategy
             }),
             2
           ),
           setIntersection = ref1[0],
           isIntersected = ref1[1];
-        var isVisible = !isLazy || isIntersected;
+        var shouldRenderFullImgAttr =
+          !isLazy || canUseNativeLoadingStrategy || isIntersected;
         var wrapperStyle = {
           boxSizing: "border-box",
           display: "block",
@@ -374,9 +379,10 @@
         var imgAttributes = {
           src: emptyDataURL,
           srcSet: undefined,
-          sizes: undefined
+          sizes: undefined,
+          loading: undefined
         };
-        if (isVisible) {
+        if (shouldRenderFullImgAttr) {
           imgAttributes = generateImgAttrs({
             config: config,
             src: src,
@@ -384,6 +390,7 @@
             layout: layout,
             width: widthInt,
             quality: qualityInt,
+            loading: canUseNativeLoadingStrategy ? loading : undefined,
             sizes: sizes,
             loader: loader
           });
@@ -427,7 +434,7 @@
               onLoadingCompleteRef
             );
           },
-          [srcString, layout, placeholder, isVisible]
+          [srcString, layout, placeholder, shouldRenderFullImgAttr]
         );
         var imgElementArgs = _objectSpread(
           {
@@ -743,13 +750,15 @@
           layout = param.layout,
           width = param.width,
           quality = param.quality,
+          loading = param.loading,
           sizes = param.sizes,
           loader = param.loader;
         if (unoptimized) {
           return {
             src: src,
             srcSet: undefined,
-            sizes: undefined
+            sizes: undefined,
+            loading: loading
           };
         }
         var ref2 = getWidths(config, width, layout, sizes),
@@ -757,6 +766,7 @@
           kind = ref2.kind;
         var last = widths.length - 1;
         return {
+          loading: loading,
           sizes: !sizes && kind === "w" ? "100vw" : sizes,
           srcSet: widths
             .map(function(w, i) {
@@ -944,6 +954,7 @@
                     layout: layout,
                     width: widthInt,
                     quality: qualityInt,
+                    loading: loading,
                     sizes: sizes,
                     loader: loader
                   }),
```
</details>
</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| buildDuration | 19.1s | 19.5s | ⚠️ +411ms |
| buildDurationCached | 6.1s | 6.2s | ⚠️ +138ms |
| nodeModulesSize | 378 MB | 378 MB | ⚠️ +772 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | cramforce/next.js native-lazy | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.139 | 3.075 | -0.06 |
| / avg req/sec | 796.33 | 813 | +16.67 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.373 | 1.373 | ✓ |
| /error-in [...]

2022-03-15 05:58 UTC, SukkaW commented
Probably a very bad idea. The browsers' implementations load images way too eagerly.

You can check out my demo: https://lab.skk.moe/native-lazyload-demo

2022-03-15 14:42 UTC, cramforce commented
Would you mind updating the demo to give the images dimensions (As in `width` and `height`)? I think what happens is that because the initial layout is performed with each images being 0x0 pixels, the lazy algorithm assumes they are all in the same position and hence loads them at once.

(I copied your HTML with the JS really quick here https://thread-cake-nannyberry.glitch.me/)

2022-03-15 15:20 UTC, cramforce commented
I just tried latest stable Safari on MacOS and it I'm getting support:
<img width="308" alt="Screen Shot 2022-03-15 at 8 20 02 AM" src="https://user-images.githubusercontent.com/89679/158411145-3142527a-986c-472d-b695-1abffa8209cc.png">

2022-04-01 18:17 UTC, styfle requested changes
Due to this being a breaking change (Safari and other older browsers will lose lazy-loading), I think it should first ship behind an experimental flag in `next.config.js`, the same way we are shipping `layout="raw"` support. This would give users the opportunity to try out the bleeding-edge at the expense of poor Safari support (which is [15% global usage](https://caniuse.com/loading-lazy-attr) today). Once adoption increases, we can look at making this the default 👍

2022-05-22 04:20 UTC, ijjk reviewed
Is this able to be closed in favor of the native lazy loading introduced in https://github.com/vercel/next.js/pull/36985?

2022-05-22 14:20 UTC, styfle commented
Yep, closing!

2022-05-22 14:20 UTC, closed without merging