Move CI build cache instructions to deployment docs
vercel/next.js pull request #35418
Opened 2022-03-17 22:34 UTC by htunnicliff

This PR moves the instructions for configuring CI providers to preserve Next.js's build cache out of the _No Cache Detected_ error message and into the _Deployment_ docs. 

This change is beneficial because it makes the CI configuration examples visible in the context of other helpful documentation for deploying Next.js.

The relocated instructions are now linked on the _No Cache Detected_ error message page.

---

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

2022-03-18 23:12 UTC, styfle submitted a review, later dismissed
Thanks!

2022-03-19 15:08 UTC, leerob requested changes
Agreed that we want to surface these steps outside of the errors page (good catch!) but we'll want to either:

1. Move this into its own page (it's long)
2. Condense and link to instructions from providers (I worry these are already out of date)

We're working to restructure this page of the docs as well, so let me think about this a bit more while we figure that out. Appreciate the contribution.

2022-03-19 16:45 UTC, htunnicliff commented
@leerob that makes a lot of sense. 

I wonder if it would be helpful to add a provider-agnostic strategy for invalidating `.next/cache`? If that strategy was defined here, it could make these docs more evergreen since users could refer to provider-specific docs with the intended invalidation strategy in mind. 

E.g. "invalidate the Next.js cache if dependencies change or source files change" etc.

2022-04-04 17:52 UTC, htunnicliff commented
Hey @leerob! Do you think it would be alright in the meantime to have this update go through as is? Reason being that folks can still benefit from this information being in the docs, even if it is eventually reorganized. 

Right now, this info doesn't exist in the docs anywhere, so just adding it in the first place would be really helpful.

2022-04-04 19:53 UTC, leerob commented
- Let's make it a separate page "Advanced Features -> CI Build Caching"
    - There is a [manifest file](https://github.com/vercel/next.js/blob/canary/docs/manifest.json) that outlines the structure
- Update the link in the errors page to use this new page

2022-04-10 18:47 UTC, htunnicliff commented
@leerob I was able to incorporate your requested changes – feel free to take a look and merge whenever you are ready!

2022-04-18 18:11 UTC, htunnicliff commented
@leerob / @timneutkens – I think this PR is ready to go! 🚀 

Please let me know if there are any other changes I should make!

2022-05-11 22:52 UTC, htunnicliff commented
Hi folks! Would you like me to close this PR? It has been several months and I haven't heard from anyone, so I'll plan on closing this PR a week from today if there is no word.

2022-05-11 23:03 UTC, leerob submitted a review, later dismissed
Thank you! Sorry for the delay.

2022-05-11 23:05 UTC, styfle commented on docs/advanced-features/ci-build-caching.md
> +> If your CI is not configured to persist `.next/cache` between builds, you may see a [No Cache Detected](https://github.com/vercel/next.js/tree/canary/errors/no-cache.md) error.
```suggestion
> If your CI is not configured to persist `.next/cache` between builds, you may see a [No Cache Detected](https://nextjs.org/docs/messages/no-cache) error.
```

2022-05-11 23:11 UTC, styfle approved these changes
Thanks!

2022-05-13 03:23 UTC, leerob approved these changes

2022-05-13 13:56 UTC, merged