add Polka server example
vercel/next.js pull request #3588
Opened 2018-01-18 15:31 UTC by mcansh

https://github.com/lukeed/polka

2018-01-18 17:29 UTC, sergiodxa requested changes
Is polka a server with the same API as express?

2018-01-18 17:29 UTC, sergiodxa commented on examples/custom-server-polka/package.json
> +    "next": "4.4.0-canary.3",
Don't use canary, use `latest`

2018-01-18 17:29 UTC, sergiodxa commented on examples/custom-server-polka/package.json
> +  "author": "Logan McAnsh <logan@mcan.sh> (https://mcan.sh)",
Remove author, version and name, just scripts and dependencies, keep it simple.

2018-01-18 17:40 UTC, mcansh commented
in a lot of ways, yeah -> https://github.com/lukeed/polka#comparisons

2018-01-19 04:06 UTC, sergiodxa approved these changes

2018-01-24 09:27 UTC, lukeed commented
Cool! Thanks guys 😃 🎉 I was gunna be adding a `with-nextjs` example too 😉

2018-01-31 07:58 UTC, timneutkens commented
@mcansh please run `npm run lint -- --fix` (or `yarn lint --fix`) on your branch, then I'll merge 🙏

2018-01-31 08:00 UTC, timneutkens commented
Actualy I've just ran the lint fixer, will merge when the tests pass. Thanks for your contribution 🙏

2018-01-31 08:24 UTC, merged