Dynamic imports with  named components
vercel/next.js pull request #3590
Opened 2018-01-18 21:29 UTC by PrudviGali

This pull request is a feature allowing dynamic imports to import specific components not just default from the module.

Current code allows only default exports to be imported to the outer world.

Usage should look like:
`dynamic(import('./moduleName'), { namedComp: 'ComponentName', });`

By this, it will import only 'ComponentName' from the module. It will be useful for structures which are having multiple exports from a single file.

2018-02-20 20:25 UTC, khrome83 requested changes
Looks good. Just allows ability to have a higher level of specificity.

Can we add to readme this additional functionality?

2018-03-31 14:52 UTC, arunoda requested changes
This PR looks great.
Try to do these:

* [ ] have a look at the suggestions I made
* [ ] document this feature in the README
* [ ] add a test case for this case

2018-03-31 14:52 UTC, arunoda commented on lib/dynamic.js
> +      this.compName = options.component ? options.component : undefined
We don't need this expression. Use `options.componentName` instead. It's clear and does the job.

2018-03-31 14:52 UTC, arunoda commented on lib/dynamic.js
> +        const AsyncComponent = this.compName ? m[this.compName] : m.default
Add the `m.default || m` part as well.

2018-04-12 10:07 UTC, herrstucki commented
Extracting exports based on string keys is non-standard and impossible to type with TS/Flow (which hints at a bad pattern IMHO).

Making standard `import('./whatever').then(m => m.MyComponent)` syntax should be the way to achieve this.

Related #2940

2018-04-12 10:25 UTC, timneutkens commented
@herrstucki is actually right, it should be like `dynamic(import('./whatever').then(m => m.MyComponent))`

2018-04-12 10:25 UTC, closed without merging