Refactor eslint-plugin-next node-attributes
vercel/next.js pull request #36040
Opened 2022-04-09 19:50 UTC by hyesungoh

## Feature
- [x] Telemetry added. In case of a feature if it's used or not.

Hello there. I'm always using it thankfully.

by the way I think the method below is highly readable

```js
// before
return !!Object.keys(this.attributes).length

// after
return Boolean(Object.keys(this.attributes)).length
```

I wonder why you wrote like `before code`.

It may be that I'm not good enough to think that reason.

Thanks to read this pr and your service.

2022-04-09 22:20 UTC, ijjk requested changes
Hi, thanks for the PR, we don't have a lint rule specific to whether `!!` is used or `Boolean` so I think people tend to prefer the shorthand `!!`. 

It seems there is a typo here as the `.length` and `.hasValue` checks need to be inside of the `Boolean` which may be a reason to continue using the shorthand as it's easier to avoid that kind of typo.

2022-04-09 22:26 UTC, hyesungoh commented
> Hi, thanks for the PR, we don't have a lint rule specific to whether `!!` is used or `Boolean` so I think people tend to prefer the shorthand `!!`.
> 
> It seems there is a typo here as the `.length` and `.hasValue` checks need to be inside of the `Boolean` which may be a reason to continue using the shorthand as it's easier to avoid that kind of typo.

I changed you said 😄 
Thanks to answer me ! I learned alot.

2022-04-09 22:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | ⚠️ +71ms |
| buildDurationCached | 6s | 6.1s | ⚠️ +24ms |
| nodeModulesSize | 478 MB | 478 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.004 | 3.048 | ⚠️ +0.04 |
| / avg req/sec | 832.16 | 820.32 | ⚠️ -11.84 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.161 | 1.168 | ⚠️ +0.01 |
| /error-in-render avg req/sec | 2153.48 | 2139.62 | ⚠️ -13.86 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28 kB | 28 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 71.7 kB | 71.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.05 kB | 3.05 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.68 kB | 5.68 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.32 kB | 2.32 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 387 B | 387 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.9 kB | 15.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 460 B | 460 B | ✓ |
| Overall change | 460 B | 460 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 524 B | 524 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| buildDuration | 18s | 17.8s | -136ms |
| buildDurationCached | 6s | 6s | ⚠️ +38ms |
| nodeModulesSize | 478 MB | 478 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 2.99 | 3.025 | ⚠️ +0.03 |
| / avg req/sec | 836 | 826.52 | ⚠️ -9.48 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.18 | 1.173 | -0.01 |
| /error-in-render avg req/sec | 2118.05 | 2130.94 | +12.89 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.3 kB | 42.3 kB | ✓ |
| main-HASH.js gzip | 28.3 kB | 28.3 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 72.2 kB | 72.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 313 B | 313 B | ✓ |
| css-HASH.js gzip | 325 B | 325 B | ✓ |
| dynamic-HASH.js gzip | 3.03 kB | 3.03 kB | ✓ |
| head-HASH.js gzip | 351 B | 351 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.74 kB | 5.74 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.38 kB | 2.38 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 388 B | 388 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | hyesungoh/next.js refactor/node-attributes | Change |
| - | - | - | - |
| index.html gzip | 531 B | 531 B | ✓ |
| link.html gzip | 544 B | 544 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 7a7097a8ef63b6a90ce19263d322d447c6df7361

2022-04-11 09:58 UTC, balazsorban44 commented
Thanks for the PR, but I don't think this adds any value. The code snippets have the same effect.

2022-04-11 09:58 UTC, closed without merging