Adding Typescript and Mantine example
vercel/next.js pull request #36294
Opened 2022-04-20 04:34 UTC by triyanox

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `yarn lint`

2022-04-22 10:48 UTC, balazsorban44 commented on examples/with-typescript-mantine/README.md
> +This is a really simple project that show the usage of Next.js with TypeScript and Mantine.
```suggestion
This is a simple project that shows the usage of Next.js with TypeScript and Mantine.
```

2022-04-22 10:49 UTC, balazsorban44 commented on examples/with-typescript-mantine/README.md
> +- [with-typescript](https://github.com/vercel/next.js/tree/canary/examples/with-typescript)
```suggestion
```

I don't think this is a useful note, let's remove it.

2022-04-22 10:50 UTC, balazsorban44 commented on examples/with-typescript-mantine/package.json
> +    "next": "12.1.5",
```suggestion
    "next": "latest",
```

2022-04-22 10:51 UTC, balazsorban44 commented on examples/with-typescript-mantine/pages/api/hello.ts
> +// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
This file does not seem to showcase Mantine, I would remove it to keep the example focused on its goal.

2022-04-22 10:53 UTC, balazsorban44 requested changes
Thanks! I added some comments.

I think we can just call the folder `with-mantine` and drop `-typescript`, as we plan to only add TS examples whenever possible, as mentioned in https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

2022-04-25 12:39 UTC, balazsorban44 submitted a review, later dismissed
Thanks!

2022-04-26 20:23 UTC, triyanox commented
I have made some changes to pass all the test including the failing linting test due to code formatting !

2022-04-27 12:21 UTC, balazsorban44 approved these changes

2022-04-27 12:36 UTC, merged