add method to measure Interaction to Next Paint (INP)
vercel/next.js pull request #36490
Opened 2022-04-26 21:16 UTC by kyliau

Please do not review for now, POC for INP measurement

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `yarn lint`

2022-04-26 21:47 UTC, ijjk commented
## Failing test suites <!--6272635189-->
Commit: a238eb5a9a1afa3e43468e95d377f5e554048fe1

`yarn testheadless test/integration/styled-jsx-plugin/test/index.test.js` 
- styled-jsx using in node_modules > production mode > should serve a page correctly

<details>
<summary>Expand output</summary>

  ● styled-jsx using in node_modules › production mode › should serve a page correctly

    FetchError: request to http://localhost:38467/ failed, reason: socket hang up

      at ClientRequest.<anonymous> (../node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-04-26 21:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.7s | ⚠️ +319ms |
| buildDurationCached | 5.6s | 5.9s | ⚠️ +241ms |
| nodeModulesSize | 481 MB | 482 MB | ⚠️ +1.21 MB |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.01 | 2.996 | -0.01 |
| / avg req/sec | 830.7 | 834.44 | +3.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.277 | 1.292 | ⚠️ +0.02 |
| /error-in-render avg req/sec | 1957.69 | 1935.69 | ⚠️ -22 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.6 kB | 29.2 kB | ⚠️ +536 B |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.8 kB | ⚠️ +536 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 309 B | 309 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.63 kB | 2.63 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 319 B | 319 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | kyliau/next.js web-vitals-inp | Change |
| - | - | - | - |
| index.html gzip | 531 B | 532 B | ⚠️ +1 B |
| link.html gzip | 545 B | 545 B | ✓ |
| withRouter.html gzip | 526 B | 525 B | -1 B |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1816,11 +1816,12 @@
           return;
         }
         isRegistered = true;
-        (0, _webVitals).getCLS(onReport);
-        (0, _webVitals).getFID(onReport);
-        (0, _webVitals).getFCP(onReport);
-        (0, _webVitals).getLCP(onReport);
-        (0, _webVitals).getTTFB(onReport);
+        (0, _webVitals).onCLS(onReport);
+        (0, _webVitals).onFID(onReport);
+        (0, _webVitals).onFCP(onReport);
+        (0, _webVitals).onLCP(onReport);
+        (0, _webVitals).onTTFB(onReport);
+        (0, _webVitals).onINP(onReport);
       };
       exports["default"] = _default;
       if (
@@ -9177,321 +9178,451 @@
       var __dirname = "/";
       (function() {
         var e = {
-          106: function(e, t) {
-            !(function(e, l) {
-              true ? l(t) : 0;
+          106: function(e, n) {
+            !(function(e, o) {
+              true ? o(n) : 0;
             })(this, function(e) {
               "use strict";
-              var t,
-                l,
+              var n,
+                o,
                 g,
-                h,
-                a = function(e, t) {
+                T,
+                w,
+                L = !1,
+                c = function(e) {
+                  addEventListener(
+                    "pageshow",
+                    function(n) {
+                      n.persisted && ((L = !0), e(n));
+                    },
+                    !0
+                  );
+                },
+                u = function() {
+                  return (
+                    window.performance &&
+                    ((performance.getEntriesByType &&
+                      performance.getEntriesByType("navigation")[0]) ||
+                      (function() {
+                        var e = performance.timing,
+                          n = { entryType: "navigation", startTime: 0 };
+                        for (var o in e)
+                          "navigationStart" !== o &&
+                            "toJSON" !== o &&
+                            (n[o] = Math.max(e[o] - e.navigationStart, 0));
+                        return n;
+                      })())
+                  );
+                },
+                f = function(e, n) {
+                  var o = u();
                   return {
                     name: e,
-                    value: void 0 === t ? -1 : t,
+                    value: void 0 === n ? -1 : n,
                     delta: 0,
                     entries: [],
                     id: "v2-"
                       .concat(Date.now(), "-")
-                      .concat(Math.floor(8999999999999 * Math.random()) + 1e12)
+                      .concat(Math.floor(8999999999999 * Math.random()) + 1e12),
+                    navigationType: L ? "back_forward_cache" : o && o.type
                   };
                 },
-                o = function(e, t) {
+                s = function(e, n, o) {
                   try {
                     if (PerformanceObserver.supportedEntryTypes.includes(e)) {
-                      if (
-                        "first-input" === e &&
-                        !("PerformanceEventTiming" in self)
-                      )
-                        return;
-                      var l = new PerformanceObserver(function(e) {
-                        return e.getEntries().map(t);
+                      var g = new PerformanceObserver(function(e) {
+                        n(e.getEntries());
                       });
-                      return l.observe({ type: e, buffered: !0 }), l;
+                      return (
+                        g.observe(
+                          Object.assign({ type: e, buffered: !0 }, o || {})
+                        ),
+                        g
+                      );
                     }
                   } catch (e) {}
                 },
-                u = function(e, t) {
-                  var l = function n(l) {
-                    ("pagehide" !== l.type &&
+                d = function(e, n) {
+                  var o = function t(o) {
+                    ("pagehide" !== o.type &&
                       "hidden" !== document.visibilityState) ||
-                      (e(l),
-                      t &&
-                        (removeEventListener("visibilitychange", n, !0),
-                        removeEventListener("pagehide", n, !0)));
+                      (e(o),
+                      n &&
+                        (removeEventListener("visibilitychange", t, !0),
+                        removeEventListener("pagehide", t, !0)));
                   };
-                  addEventListener("visibilitychange", l, !0),
-                    addEventListener("pagehide", l, !0);
-                },
-                c = function(e) {
-                  addEventListener(
-     [...]

2022-05-23 18:43 UTC, kyliau commented
@timneutkens @ijjk PR is ready for review, could you please take a look? Thank you!

2022-05-25 08:09 UTC, timneutkens requested changes, later dismissed
Can you add a test for this in `test/integration/relay-analytics`

2022-06-01 20:26 UTC, kyliau commented
I upgraded `playwright-chromium` from 1.14.1 to 1.17.2 because the Events Timing API used to measure INP is only available in Chromium >= v98.

2022-06-07 17:30 UTC, ijjk approved these changes
Thanks!

2022-06-07 18:28 UTC, merged