Fix wrong conversion to JPEG instead of PNG when WEBP/AVIF is not supported (fixes images with alpha channels)
vercel/next.js pull request #36611
Opened 2022-05-01 22:43 UTC by thexpand

Change the fallback contentType from JPEG to PNG.
This way even if the unsupported contentType (webp/avif) has an alpha channel, it won't turn black.

Fixes #35674 

It's in direct relation and extension to a previously resolved issue #20794 fixed by PR #35190

2022-05-02 09:48 UTC, balazsorban44 commented
I think this might not be the right approach as PNGs are generally bigger than JPEGs and would penalize use cases where transparency is not an issue.

We should somehow detect if an image has transparency and only convert it to PNG if it does instead.

2022-05-02 13:02 UTC, styfle requested changes
Did you compare the size before and after?

This will likely increase the size so its not desirable.

Instead, the image should be analyzed for transparency/alpha and only use PNG in that case.

Lastly, we need tests to prove this is working as expected.

2022-05-02 13:24 UTC, thexpand commented
@styfle Is there a standard way somewhere else in `next/image` or in `next` in general to detect transparency in an image? If there is, probably it's better to reuse it, otherwise, we'll have to analyze the bytes data stream with DataView somehow.

2022-05-02 19:27 UTC, styfle commented
I don't think we have any existing logic for this behavior

2023-06-15 04:18 UTC, ijjk reviewed
Going to close this as stale, feel free to open fresh PR considering above feedback if interested!

2023-06-15 04:18 UTC, closed without merging