Update renderOpts.dev handling and fix check
vercel/next.js pull request #36666
Opened 2022-05-03 21:59 UTC by ijjk

Seems `renderOpts.dev` is set a bit later than we want so this moves setting that to `base-server` and also fixes the check for pre-warming `_app` and `_document`.

2022-05-03 22:03 UTC, huozhi approved these changes, later dismissed

2022-05-03 22:17 UTC, sokra commented on packages/next/server/next-server.ts
> +      } catch (_) {}
The try catch won't help here, since it's a promise rejection...
`loadComponents` will not throw, but returns a rejected promise.

2022-05-03 22:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| buildDuration | 16s | 16s | ⚠️ +42ms |
| buildDurationCached | 6.3s | 6.2s | -89ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +58 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.759 | 3.731 | -0.03 |
| / avg req/sec | 665.11 | 670.1 | +4.99 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.393 | 1.321 | -0.07 |
| /error-in-render avg req/sec | 1795.25 | 1891.99 | +96.74 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 28.7 kB | 28.7 kB | ✓ |
| webpack-HASH.js gzip | 1.44 kB | 1.44 kB | ✓ |
| Overall change | 72.3 kB | 72.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.71 kB | 5.71 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.64 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| index.html gzip | 533 B | 533 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| buildDuration | 18.2s | 18.2s | ⚠️ +38ms |
| buildDurationCached | 6.3s | 6.2s | -79ms |
| nodeModulesSize | 475 MB | 475 MB | ⚠️ +58 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.753 | 3.721 | -0.03 |
| / avg req/sec | 666.14 | 671.86 | +5.72 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.384 | 1.443 | ⚠️ +0.06 |
| /error-in-render avg req/sec | 1806.64 | 1732.85 | ⚠️ -73.79 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.2 kB | 42.2 kB | ✓ |
| main-HASH.js gzip | 29.1 kB | 29.1 kB | ✓ |
| webpack-HASH.js gzip | 1.45 kB | 1.45 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 312 B | 312 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 3.08 kB | 3.08 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 921 B | 921 B | ✓ |
| image-HASH.js gzip | 5.76 kB | 5.76 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.76 kB | 2.76 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.5 kB | 16.5 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | ijjk/next.js fix/app-doc-check | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 543 B | 543 B | ✓ |
| withRouter.html gzip | 527 B | 527 B | ✓ |
| Overall change | 1.6 kB | 1.6 kB | ✓ |

</details>

</details>
Commit: 220bed00e61f55f650a394a4a4860881774a13ba

2022-05-03 22:23 UTC, sokra requested changes, later dismissed

2022-05-03 22:23 UTC, sokra commented on packages/next/server/next-server.ts
> +      } catch (_) {}
```
    const [DocumentMod, AppMod, ComponentMod, AppServerMod] = await Promise.all([
        Promise.resolve().then(() => requirePage('/_document', distDir, serverless)),
        Promise.resolve().then(() => requirePage('/_app', distDir, serverless)),
        Promise.resolve().then(() => requirePage(pathname, distDir, serverless)),
        serverComponents ? requirePage('/_app.server', distDir, serverless) : null,
    ]);
```

in `loadComponents` helped for me

2022-05-03 22:56 UTC, ijjk commented
## Failing test suites <!--6364619052-->
Commit: 3470850543fecd9aad8b7e0e256c524a9e9a0576

`yarn testheadless test/e2e/root-dir/index.test.ts` 
- root dir > should serve from root
- root dir > should include layouts when no direct parent layout
- root dir > should not include parent when not in parent directory with route in directory
- root dir > should include parent document when no direct parent layout
- root dir > should not include parent when not in parent directory
- root dir > should serve nested parent
- root dir > should serve dynamic parameter
- root dir > should include document html and body
- root dir > server components > should not serve .server.js as a path
- root dir > server components > should not serve .client.js as a path
- root dir > server components > should serve shared component

<details>
<summary>Expand output</summary>

  ● root dir › should serve from root

    expect(received).toContain(expected) // indexOf

    Expected substring: "hello from root/dashboard"
    Received string:    "<!DOCTYPE html><html><head><style data-next-hide-fouc=\"true\">body{display:none}</style><noscript data-next-hide-fouc=\"true\"><style>body{display:block}</style></noscript><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"3\"/><noscript data-n-css=\"\"></noscript><link rel=\"preload\" href=\"/_next/static/chunks/webpack.js?ts=1651618565836\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/main.js?ts=1651618565836\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_app.js?ts=1651618565836\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_error.js?ts=1651618565836\" as=\"script\"/><noscript id=\"__next_css__DO_NOT_USE__\"></noscript></head><body><div id=\"__next\"><div style=\"font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>
                    body { margin: 0; color: #000; background: #fff; }
                    .next-error-h1 {
                      border-right: 1px solid rgba(0, 0, 0, .3);
                    }
                    @media (prefers-color-scheme: dark) {
                      body { color: #fff; background: #000; }
                      .next-error-h1 {
                        border-right: 1px solid rgba(255, 255, 255, .3);
                      }
                    }</style><h1 class=\"next-error-h1\" style=\"display:inline-block;margin:0;margin-right:20px;padding:10px 23px 10px 0;font-size:24px;font-weight:500;vertical-align:top\">404<!-- --></h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">This page could not be found<!-- -->.<!-- --></h2></div></div></div></div><script src=\"/_next/static/chunks/react-refresh.js?ts=1651618565836\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"gip\":true,\"scriptLoader\":[]}</script><script nomodule=\"\" src=\"/_next/static/chunks/polyfills.js?ts=1651618565836\"></script><script src=\"/_next/static/chunks/webpack.js?ts=1651618565836\"></script><script src=\"/_next/static/chunks/main.js?ts=1651618565836\"></script><script src=\"/_next/static/chunks/pages/_app.js?ts=1651618565836\"></script><script src=\"/_next/static/chunks/pages/_error.js?ts=1651618565836\"></script><script src=\"/_next/static/development/_buildManifest.js?ts=1651618565836\"></script><script src=\"/_next/static/development/_ssgManifest.js?ts=1651618565836\"></script><script src=\"/_next/static/development/_middlewareManifest.js?ts=1651618565836\"></script></body></html>"

      47 |   it('should serve from root', async () => {
      48 |     const html = await renderViaHTTP(next.url, '/dashboard')
    > 49 |     expect(html).toContain('hello from root/dashboard')
         |                  ^
      50 |   })
      51 |
      52 |   it('should include layouts when no direct parent layout', async () => {

      at Object.<anonymous> (e2e/root-dir/index.test.ts:49:18)

  ● root dir › should include layouts when no direct parent layout

    expect(received).toBe(expected) // Object.is equality

    Expected: "Dashboard"
    Received: "404"

      54 |     const $ = cheerio.load(html)
      55 |     // Should not be nested in dashboard
    > 56 |     expect($('h1').text()).toBe('Dashboard')
         |                            ^
      57 |     // Should include the page text
      58 |     expect($('p').text()).toBe('hello from root/dashboard/integrations')
      59 |   })

      at Object.<anonymous> (e2e/root-dir/index.test.ts:56:28)

  ● root dir › should not include parent when not in parent directory with route in directory

    expect(received).toBeTruthy()

    Received: false

      65 |
      66 |     // Should be nested in /root.js
    > 67 |     expect($('html').hasClass('this-is-the-document-html')).toBeTruthy()
         |                                                             ^
      68 |     expect($('body').hasClass('this-is-the-document-body')).toBeTruthy()
      69 |
      70 |     // Should not be nested in dashboard

      at Object.<anonymous> (e2e/root-dir/index.test.ts:67:61)

  ● root dir › should include parent document when no direct parent layout

    expect(received).toBeTruthy()

    Received: false

      80 |
      81 |     // Root has to provide it's own document
    > 82 |     expect($('html').hasClass('this-is-the-document-html')).toBeTruthy()
         |                                                             ^
      83 |     expect($('body').hasClass('this-is-the-document-body')).toBeTruthy()
      84 |   })
      85 |

      at Object.<anonymous> (e2e/root-dir/index.test.ts:82:61)

  ● root dir › should not include parent when not in parent directory

    expect(received).toBeFalsy()

    Received: "404"

      88 |     const $ = cheerio.load(html)
      89 |     // Should not be nested in dashboard
    > 90 |     expect($('h1').text()).toBeFalsy()
         |                            ^
      91 |     // Should include the page text
      92 |     expect($('p').text()).toBe('hello from root/dashboard/changelog')
      93 |   })

      at Object.<anonymous> (e2e/root-dir/index.test.ts:90:28)

  ● root dir › should serve nested parent

    expect(received).toBe(expected) // Object.is equality

    Expected: "Dashboard"
    Received: "404"

       97 |     const $ = cheerio.load(html)
       98 |     // Should be nested in dashboard
    >  99 |     expect($('h1').text()).toBe('Dashboard')
          |                            ^
      100 |     // Should be nested in deployments
      101 |     expect($('h2').text()).toBe('Deployments hello')
      102 |   })

      at Object.<anonymous> (e2e/root-dir/index.test.ts:99:28)

  ● root dir › should serve dynamic parameter

    expect(received).toBe(expected) // Object.is equality

    Expected: "hello from root/dashboard/deployments/[id]. ID is: 123"
    Received: ""

      106 |     const $ = cheerio.load(html)
      107 |     // Should include the page text with the parameter
    > 108 |     expect($('p').text()).toBe(
          |                           ^
      109 |       'hello from root/dashboard/deployments/[id]. ID is: 123'
      110 |     )
      111 |   })

      at Object.<anonymous> (e2e/root-dir/index.test.ts:108:27)

  ● root dir › should include document html and body

    expect(received).toBeTruthy()

    Received: false

      115 |     const $ = cheerio.load(html)
      116 |
    > 117 |     expec [...]

2022-05-04 00:25 UTC, ijjk commented
## Failing test suites <!--6364944236-->
Commit: 4c6c3629adc9f2b22d32e70af664300ee3366231

`yarn testheadless test/integration/react-streaming-and-server-components/test/index.test.js` 
- Edge runtime dev > should render 500 error correctly
- Node.js runtime dev > should render 500 error correctly

<details>
<summary>Expand output</summary>

  ● Node.js runtime dev › should render 500 error correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "Error: oops"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>Application error: a client-side exception has occurred</title><meta name=\"next-head-count\" content=\"3\"/><meta name=\"next-font-preconnect\"/><noscript data-n-css=\"\"></noscript><link rel=\"preload\" href=\"/_next/static/chunks/webpack.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/main.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_error.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>
                    body { margin: 0; color: #000; background: #fff; }
                    .next-error-h1 {
                      border-right: 1px solid rgba(0, 0, 0, .3);
                    }
                    @media (prefers-color-scheme: dark) {
                      body { color: #fff; background: #000; }
                      .next-error-h1 {
                        border-right: 1px solid rgba(255, 255, 255, .3);
                      }
                    }</style><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">Application error: a client-side exception has occurred (see the browser console for more information)<!-- -->.<!-- --></h2></div></div></div></div><script src=\"/_next/static/chunks/react-refresh.js\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Internal Server Error.\",\"message\":\"500 - Internal Server Error.\",\"statusCode\":500},\"customServer\":true,\"gip\":true,\"scriptLoader\":[]}</script><script nomodule=\"\" src=\"/_next/static/chunks/polyfills.js\"></script><script src=\"/_next/static/chunks/webpack.js\" async=\"\"></script><script src=\"/_next/static/chunks/main.js\" async=\"\"></script><script src=\"/_next/static/chunks/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/chunks/pages/_error.js\" async=\"\"></script><script src=\"/_next/static/development/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js\" async=\"\"></script><script src=\"/_next/static/development/_middlewareManifest.js\" async=\"\"></script></body></html>"

      34 |       if (env === 'dev') {
      35 |         // In dev mode it should show the error popup.
    > 36 |         expect(html).toContain('Error: oops')
         |                      ^
      37 |       } else {
      38 |         expect(html).toContain('custom-500-page')
      39 |       }

      at integration/react-streaming-and-server-components/test/basic.js:36:22
          at async Promise.all (index 1)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/basic.js:41:5)

  ● Edge runtime dev › should render 500 error correctly

    expect(received).toContain(expected) // indexOf

    Expected substring: "Error: oops"
    Received string:    "<!DOCTYPE html><html><head><meta name=\"viewport\" content=\"width=device-width\"/><meta charSet=\"utf-8\"/><title>Application error: a client-side exception has occurred</title><meta name=\"next-head-count\" content=\"3\"/><meta name=\"next-font-preconnect\"/><noscript data-n-css=\"\"></noscript><link rel=\"preload\" href=\"/_next/static/chunks/webpack.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/main.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_app.js\" as=\"script\"/><link rel=\"preload\" href=\"/_next/static/chunks/pages/_error.js\" as=\"script\"/></head><body><div id=\"__next\"><div style=\"font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>
                    body { margin: 0; color: #000; background: #fff; }
                    .next-error-h1 {
                      border-right: 1px solid rgba(0, 0, 0, .3);
                    }
                    @media (prefers-color-scheme: dark) {
                      body { color: #fff; background: #000; }
                      .next-error-h1 {
                        border-right: 1px solid rgba(255, 255, 255, .3);
                      }
                    }</style><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:inherit;margin:0;padding:0\">Application error: a client-side exception has occurred (see the browser console for more information)<!-- -->.<!-- --></h2></div></div></div></div><script src=\"/_next/static/chunks/react-refresh.js\"></script><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"development\",\"isFallback\":false,\"err\":{\"name\":\"Internal Server Error.\",\"message\":\"500 - Internal Server Error.\",\"statusCode\":500},\"customServer\":true,\"gip\":true,\"scriptLoader\":[]}</script><script nomodule=\"\" src=\"/_next/static/chunks/polyfills.js\"></script><script src=\"/_next/static/chunks/webpack.js\" async=\"\"></script><script src=\"/_next/static/chunks/main.js\" async=\"\"></script><script src=\"/_next/static/chunks/pages/_app.js\" async=\"\"></script><script src=\"/_next/static/chunks/pages/_error.js\" async=\"\"></script><script src=\"/_next/static/development/_buildManifest.js\" async=\"\"></script><script src=\"/_next/static/development/_ssgManifest.js\" async=\"\"></script><script src=\"/_next/static/development/_middlewareManifest.js\" async=\"\"></script></body></html>"

      34 |       if (env === 'dev') {
      35 |         // In dev mode it should show the error popup.
    > 36 |         expect(html).toContain('Error: oops')
         |                      ^
      37 |       } else {
      38 |         expect(html).toContain('custom-500-page')
      39 |       }

      at integration/react-streaming-and-server-components/test/basic.js:36:22
          at runMicrotasks (<anonymous>)
          at async Promise.all (index 1)
      at Object.<anonymous> (integration/react-streaming-and-server-components/test/basic.js:41:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-05-05 16:07 UTC, huozhi approved these changes

2022-05-05 16:11 UTC, merged