Update script.md
vercel/next.js pull request #37084
Opened 2022-05-21 02:10 UTC by valse

The Script with the `beforeInteractive` strategy must be in the `_document.js` `Head` otherwise it fails to load.

2022-05-23 09:09 UTC, timneutkens requested changes
<Script> should definitely not be in the custom <Head> components so this sounds more like a bug that should be investigated. Could you open an issue with a reproduction / test case?

2022-05-24 19:29 UTC, icyJoseph commented
Hi,

I think this was fixed on https://github.com/vercel/next.js/pull/37000 - Tried to jump at fixing it myself, but the tests passed... so I checked `git blame` and found that PR 😄

2022-05-25 06:18 UTC, valse commented
> Though it does seem like #37000 expects the Script to be inside Head.

Hi, exactly... I'm using it and I had to move it inside Head so why I made this PR.

2022-05-26 18:21 UTC, housseindjirdeh approved these changes
Sorry for the confusion folks, the newer behavior of <Script> that @janicklas-ralph added does make it so that it needs to be inserted in the document <Head> (but not in page <Head> components).

Thanks for adding this documentation fix 👍

2022-05-29 02:00 UTC, ijjk reviewed
As discussed with @housseindjirdeh and @janicklas-ralph in Slack this restriction isn't desired and we will patch this in a follow-up PR so that inserting scripts in `Head` isn't required so I'm gonna close this but thanks for raising this PR!

2022-05-29 02:00 UTC, closed without merging