Update of @babel/core
vercel/next.js pull request #37145
Opened 2022-05-23 23:52 UTC by 7iomka

Update of @babel/core to fix Type-only import specifiers issue

Fixes [#37016](https://github.com/vercel/next.js/issues/37016)

2022-05-24 07:16 UTC, SukkaW requested changes
It seems that you forgot to update the `yarn.lock`.

You should use `yarn` to upgrade a dependency so the dependency change is reflected in the lockfile.

2022-05-24 12:32 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.9s | ⚠️ +201ms |
| buildDurationCached | 6.3s | 6.3s | -27ms |
| nodeModulesSize | 494 MB | 494 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.874 | 3.805 | -0.07 |
| / avg req/sec | 645.36 | 657.1 | +11.74 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.367 | 1.317 | -0.05 |
| /error-in-render avg req/sec | 1828.44 | 1897.9 | +69.46 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 29.2 kB | 29.2 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 73 kB | 73 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.36 kB | 1.36 kB | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 308 B | 308 B | ✓ |
| css-HASH.js gzip | 327 B | 327 B | ✓ |
| dynamic-HASH.js gzip | 2.71 kB | 2.71 kB | ✓ |
| head-HASH.js gzip | 359 B | 359 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.73 kB | 5.73 kB | ✓ |
| index-HASH.js gzip | 263 B | 263 B | ✓ |
| link-HASH.js gzip | 2.65 kB | 2.65 kB | ✓ |
| routerDirect..HASH.js gzip | 320 B | 320 B | ✓ |
| script-HASH.js gzip | 391 B | 391 B | ✓ |
| withRouter-HASH.js gzip | 318 B | 318 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 458 B | 458 B | ✓ |
| Overall change | 458 B | 458 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 546 B | 546 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Default Build with SWC</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 18s | 18s | ⚠️ +70ms |
| buildDurationCached | 6.4s | 6.4s | -24ms |
| nodeModulesSize | 494 MB | 494 MB | ✓ |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall increase ✓</summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 3.857 | 3.877 | ⚠️ +0.02 |
| / avg req/sec | 648.25 | 644.82 | ⚠️ -3.43 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 1.356 | 1.353 | 0 |
| /error-in-render avg req/sec | 1843.04 | 1847.41 | +4.37 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| 925.HASH.js gzip | 178 B | 178 B | ✓ |
| framework-HASH.js gzip | 42.7 kB | 42.7 kB | ✓ |
| main-HASH.js gzip | 29.7 kB | 29.7 kB | ✓ |
| webpack-HASH.js gzip | 1.54 kB | 1.54 kB | ✓ |
| Overall change | 74 kB | 74 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 1.35 kB | 1.35 kB | ✓ |
| _error-HASH.js gzip | 179 B | 179 B | ✓ |
| amp-HASH.js gzip | 311 B | 311 B | ✓ |
| css-HASH.js gzip | 324 B | 324 B | ✓ |
| dynamic-HASH.js gzip | 2.89 kB | 2.89 kB | ✓ |
| head-HASH.js gzip | 357 B | 357 B | ✓ |
| hooks-HASH.js gzip | 920 B | 920 B | ✓ |
| image-HASH.js gzip | 5.82 kB | 5.82 kB | ✓ |
| index-HASH.js gzip | 261 B | 261 B | ✓ |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | ✓ |
| routerDirect..HASH.js gzip | 322 B | 322 B | ✓ |
| script-HASH.js gzip | 392 B | 392 B | ✓ |
| withRouter-HASH.js gzip | 317 B | 317 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16.3 kB | 16.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 457 B | 457 B | ✓ |
| Overall change | 457 B | 457 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | 7iomka/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 532 B | 532 B | ✓ |
| link.html gzip | 547 B | 547 B | ✓ |
| withRouter.html gzip | 528 B | 528 B | ✓ |
| Overall change | 1.61 kB | 1.61 kB | ✓ |

</details>

</details>
Commit: 896bda40a17892d4f403c60f672837bbc60ea166

2022-05-24 22:36 UTC, ijjk commented
## Failing test suites <!--6645589692-->
Commit: 339837414cdf72956ed76da1f170f62364edc107

`yarn testheadless test/integration/app-document-add-hmr/test/index.test.js` 
- _app/_document add HMR > should HMR when _app is added
- _app/_document add HMR > should HMR when _document is added

<details>
<summary>Expand output</summary>

  ● _app/_document add HMR › should HMR when _app is added

    browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-907428/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

      56 |       browser = await firefox.launch({ headless })
      57 |     } else {
    > 58 |       browser = await chromium.launch({ headless, devtools: !headless })
         |                                ^
      59 |     }
      60 |     context = await browser.newContext({ locale })
      61 |   }

      at Playwright.setup (lib/browsers/playwright.ts:58:32)
      at Object.webdriver [as default] (lib/next-webdriver.ts:95:17)
      at Object.<anonymous> (integration/app-document-add-hmr/test/index.test.js:23:36)
      at TestScheduler.scheduleTests (../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (../node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (../node_modules/@jest/core/build/cli/index.js:261:3)

  ● _app/_document add HMR › should HMR when _document is added

    browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-907428/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝

      56 |       browser = await firefox.launch({ headless })
      57 |     } else {
    > 58 |       browser = await chromium.launch({ headless, devtools: !headless })
         |                                ^
      59 |     }
      60 |     context = await browser.newContext({ locale })
      61 |   }

      at Playwright.setup (lib/browsers/playwright.ts:58:32)
      at Object.webdriver [as default] (lib/next-webdriver.ts:95:17)
      at Object.<anonymous> (integration/app-document-add-hmr/test/index.test.js:61:36)
      at TestScheduler.scheduleTests (../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (../node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (../node_modules/@jest/core/build/cli/index.js:261:3)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2022-05-31 01:00 UTC, ijjk approved these changes

2022-05-31 01:00 UTC, merged