fix: support @import url in css with experimental.urlImports
vercel/next.js pull request #37387
Opened 2022-06-02 04:11 UTC by await-ovo

fixes #37327 

Just move absolute urls in @import directly into the runtime code like `css-loader` does.

Currently, importing css directly in js like the following will still report an error:

```
import 'https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css'
```
> Using webpack + css-loader + style-loader directly will also have this problem.

I'm not quite sure if this usage is going to be supported, and if it is. We might need to change the [stringifyRequest](https://github.com/webpack-contrib/style-loader/blob/master/src/utils.js#L16) method in the `style-loader` and `css-loader`, so that their runtime files are resolved correctly, I tried to fix the error, but without success.

## Bug

- [x] Related issues linked using `fixes #number`
- [x] Integration tests added
- [x] Errors have helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-06-15 09:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| buildDuration | 20.6s | 20.8s | ⚠️ +133ms |
| buildDurationCached | 7.3s | 7.6s | ⚠️ +332ms |
| nodeModulesSize | 1.85 GB | 1.85 GB | -786 B |

</details>

<details>
<summary><strong>Page Load Tests</strong> Overall decrease ⚠️</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| / failed reqs | 0 | 0 | ✓ |
| / total time (seconds) | 4.874 | 4.938 | ⚠️ +0.06 |
| / avg req/sec | 512.89 | 506.27 | ⚠️ -6.62 |
| /error-in-render failed reqs | 0 | 0 | ✓ |
| /error-in-render total time (seconds) | 2.262 | 2.257 | 0 |
| /error-in-render avg req/sec | 1105.25 | 1107.73 | +2.48 |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| 437.HASH.js gzip | 179 B | 179 B | ✓ |
| framework-HASH.js gzip | 42 kB | 42 kB | ✓ |
| main-HASH.js gzip | 29.9 kB | 29.9 kB | -4 B |
| webpack-HASH.js gzip | 1.53 kB | 1.54 kB | ⚠️ +4 B |
| Overall change | 73.6 kB | 73.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| _app-HASH.js gzip | 827 B | 825 B | -2 B |
| _error-HASH.js gzip | 194 B | 194 B | ✓ |
| amp-HASH.js gzip | 495 B | 496 B | ⚠️ +1 B |
| css-HASH.js gzip | 328 B | 327 B | -1 B |
| dynamic-HASH.js gzip | 2.39 kB | 2.39 kB | -2 B |
| head-HASH.js gzip | 359 B | 355 B | -4 B |
| hooks-HASH.js gzip | 419 B | 418 B | -1 B |
| image-HASH.js gzip | 5.25 kB | 5.25 kB | -1 B |
| index-HASH.js gzip | 263 B | 264 B | ⚠️ +1 B |
| link-HASH.js gzip | 2.4 kB | 2.4 kB | ⚠️ +2 B |
| routerDirect..HASH.js gzip | 322 B | 321 B | -1 B |
| script-HASH.js gzip | 392 B | 390 B | -2 B |
| withRouter-HASH.js gzip | 320 B | 318 B | -2 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 14.1 kB | 14.1 kB | -12 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| _buildManifest.js gzip | 459 B | 459 B | ✓ |
| Overall change | 459 B | 459 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 517 B | 517 B | ✓ |
| Overall change | 1.57 kB | 1.57 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | await-ovo/next.js fix-css-import-url | Change |
| - | - | - | - |
| middleware-m..st.json gzip | 209 B | 209 B | ✓ |
| middleware.js gzip | 16.9 kB | 16.9 kB | -4 B |
| edge-runtime..pack.js gzip | 1.79 kB | 1.79 kB | ✓ |
| Overall change | 18.9 kB | 18.9 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [826],
   {
-    /***/ 776: /***/ (
+    /***/ 457: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -14,7 +14,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_dist_server_web_adapter__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        222
+        35
       );
 
       // The condition is true when the "process" module is provided
@@ -24,7 +24,7 @@
         __webpack_require__.g.process = process;
       }
 
-      var mod = __webpack_require__(724);
+      var mod = __webpack_require__(623);
       var handler = mod.middleware || mod.default;
 
       if (typeof handler !== "function") {
@@ -50,7 +50,7 @@
       /***/
     },
 
-    /***/ 724: /***/ (
+    /***/ 623: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -62,7 +62,7 @@
         /* harmony export */
       });
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(
-        335
+        897
       );
       /* harmony import */ var next_server__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/ __webpack_require__.n(
         next_server__WEBPACK_IMPORTED_MODULE_0__
@@ -75,7 +75,7 @@
       /***/
     },
 
-    /***/ 734: /***/ (__unused_webpack_module, exports) => {
+    /***/ 242: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -97,7 +97,7 @@
       /***/
     },
 
-    /***/ 893: /***/ (__unused_webpack_module, exports) => {
+    /***/ 936: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -135,7 +135,7 @@
       /***/
     },
 
-    /***/ 142: /***/ (__unused_webpack_module, exports) => {
+    /***/ 846: /***/ (__unused_webpack_module, exports) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -167,7 +167,7 @@
       /***/
     },
 
-    /***/ 777: /***/ (
+    /***/ 893: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -178,8 +178,8 @@
         value: true
       });
       exports.addLocale = addLocale;
-      var _addPathPrefix = __webpack_require__(774);
-      var _pathHasPrefix = __webpack_require__(841);
+      var _addPathPrefix = __webpack_require__(466);
+      var _pathHasPrefix = __webpack_require__(590);
       function addLocale(path, locale, defaultLocale) {
         if (
           locale &&
@@ -198,7 +198,7 @@
       /***/
     },
 
-    /***/ 774: /***/ (
+    /***/ 466: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -209,7 +209,7 @@
         value: true
       });
       exports.addPathPrefix = addPathPrefix;
-      var _parsePath = __webpack_require__(70);
+      var _parsePath = __webpack_require__(422);
       function addPathPrefix(path, prefix) {
         if (!path.startsWith("/") || !prefix) {
           return path;
@@ -221,7 +221,7 @@
       /***/
     },
 
-    /***/ 114: /***/ (
+    /***/ 458: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -232,7 +232,7 @@
         value: true
       });
       exports.addPathSuffix = addPathSuffix;
-      var _parsePath = __webpack_require__(70);
+      var _parsePath = __webpack_require__(422);
       function addPathSuffix(path, suffix) {
         if (!path.startsWith("/") || !suffix) {
           return path;
@@ -244,16 +244,20 @@
       /***/
     },
 
-    /***/ 36: /***/ (__unused_webpack_module, exports, __webpack_require__) => {
+    /***/ 613: /***/ (
+      __unused_webpack_module,
+      exports,
+      __webpack_require__
+    ) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
         value: true
       });
       exports.formatNextPathnameInfo = formatNextPathnameInfo;
-      var _addPathPrefix = __webpack_require__(774);
-      var _addPathSuffix = __webpack_require__(114);
-      var _addLocale = __webpack_require__(777);
+      var _addPathPrefix = __webpack_require__(466);
+      var _addPathSuffix = __webpack_require__(458);
+      var _addLocale = __webpack_require__(893);
       function formatNextPathnameInfo(info) {
         let pathname = ( [...]

2022-08-26 18:57 UTC, victorcarvalhosp commented
Hi team, do you have some eta for this fix to be available on nextjs?

2022-09-08 06:38 UTC, sokra requested changes

2022-09-08 06:38 UTC, sokra commented on test/integration/url-imports/test/index.test.js
> +            `url("https://github.com/vercel/next.js/raw/canary/test/integration/url/public/vercel.png")`
That's not what should happen here. By using `urlImports` is should bundle the `url()` referenced resource. So it must have an url pointing to localhost. If this results in an external url the test is actually broken.

2022-09-08 06:38 UTC, sokra commented on test/integration/url-imports/test/index.test.js
> +                    `@import url('https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css')`
Same. This should point to localhost.

2022-09-08 06:38 UTC, sokra commented on packages/next/build/webpack/config/blocks/css/loaders/file-resolve.ts
>    }
Returning false for a http url is incorrect when urlImports is enabled. It need to return true, since it should try to resolve the http url.

2023-06-15 04:18 UTC, ijjk reviewed
Going to close this as stale, if this is still a concern feel free to open a discussion to investigate further!

2023-06-15 04:18 UTC, closed without merging