Add example with link to oficial example of "Material-ui with Typescript"
vercel/next.js pull request #37499
Opened 2022-06-07 08:00 UTC by henriqueholtz

## Documentation / Examples

- Add example with link to oficial example of "Material-ui with Typescript"

I'm following this similar [PR 34035](https://github.com/vercel/next.js/pull/34035).

2022-06-14 12:13 UTC, balazsorban44 requested changes
We already have a Material UI example, let's just add a link to that README: https://github.com/vercel/next.js/tree/canary/examples/with-material-ui

2022-06-14 16:35 UTC, henriqueholtz commented
> We already have a Material UI example, let's just add a link to that README: https://github.com/vercel/next.js/tree/canary/examples/with-material-ui

@balazsorban44  Thanks for this appointment.

I've update my branch, and apply your suggestion [into this commit](https://github.com/vercel/next.js/pull/37499/commits/e70be802c0ece9424394fd1dc6387fef8cc2f1dc)

Please let me know if it's ok from now. Thanks!

2022-06-20 13:07 UTC, balazsorban44 commented
Hi, it looks like you accidentally did a lot of changes to the core. These should be reverted, as the only file that needs to change is this one: https://github.com/vercel/next.js/blob/canary/examples/with-material-ui/README.md

If it's easier, you can close this PR and create a new one with only the necessary changes.

2022-06-20 13:11 UTC, balazsorban44 commented on examples/with-material-ui/README.md
> +### 2 - [Oficial example - ( Typescript )](https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript)
```suggestion
These examples are maintained outside of the Next.js repository:

1. Official [TypeScript example](https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript)
2. Official [JavaScript example](https://github.com/mui/material-ui/tree/master/examples/nextjs)
```

Let's recommend TypeScript first. :+1:

2022-06-20 13:32 UTC, closed without merging