Add a Plasmic example
vercel/next.js pull request #37522
Opened 2022-06-07 19:25 UTC by ryscheng

This adds a new example under `cms-plasmic/`. It serves as a general-purpose example that should be able to work with any Plasmic project, which can be set via environment variables.

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-06-14 12:17 UTC, balazsorban44 commented on examples/cms-plasmic/package.json
> +  }
```suggestion
    "start": "next start"
  },
  "dependencies": {
    "@plasmicapp/loader-nextjs": "1.0.136",
    "next": "latest",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "devDependencies": {
    "@types/node": "17.0.41",
    "@types/react": "18.0.12",
    "typescript": "4.7.3"
  }
```

2022-06-14 12:18 UTC, balazsorban44 commented on examples/cms-plasmic/pages/[[...catchall]].tsx
> +import * as React from 'react'
```suggestion
```

I don't see a reference to `React` and this is not necessary anymore.

2022-06-14 12:19 UTC, balazsorban44 commented on examples/cms-plasmic/pages/[[...catchall]].tsx
> +import { PLASMIC, PREVIEW_PLASMIC } from '../plasmic-init'
I think it would be useful to distinguish between `import` and `import type` here. What do you think?

2022-06-14 12:21 UTC, balazsorban44 commented on examples/cms-plasmic/pages/api/hello.js
> +}
Not needed, please remove this file.

2022-06-14 12:21 UTC, balazsorban44 commented on examples/cms-plasmic/pages/api/preview.ts
> +import process from 'process'
```suggestion
```

2022-06-14 12:23 UTC, balazsorban44 commented on examples/cms-plasmic/pages/api/preview.ts
> +  res.end()
```suggestion
  res.redirect(pageMeta.path)
```

See: https://nextjs.org/docs/api-routes/response-helpers

2022-06-14 12:24 UTC, balazsorban44 commented on examples/cms-plasmic/styles/Home.module.css
> +.container {
I don't see this file is imported, let's remove it. Same with `/public/vercel.svg`

2022-06-14 12:25 UTC, balazsorban44 requested changes
Thanks, I added a few comments, could you address those?

2022-06-15 01:50 UTC, ryscheng commented
@balazsorban44 Thanks so much for the thoughtful review!
I just amended the commit to include your suggestions, do you mind taking another look?
Thanks!

2022-06-22 14:52 UTC, balazsorban44 approved these changes
Thanks!

2022-06-22 15:19 UTC, merged