Add a Makeswift example
vercel/next.js pull request #38018
Opened 2022-06-25 19:35 UTC by apledger

This adds an example of how to use Makeswift with Next.js under `cms-makeswift/`.

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-06-26 11:25 UTC, balazsorban44 requested changes
Thanks, just some small suggestions.

2022-06-26 11:25 UTC, balazsorban44 commented on examples/cms-makeswift/package.json
> +    "lint": "next lint"
```suggestion
    "start": "next start"
```

2022-06-26 11:25 UTC, balazsorban44 commented on examples/cms-makeswift/package.json
> +    "react-dom": "18.1.0"
```suggestion
    "react": "18.2.0",
    "react-dom": "18.2.0"
```

2022-06-26 11:25 UTC, balazsorban44 commented on examples/cms-makeswift/.env
> +MAKESWIFT_API_HOST=https://api.makeswift.com
Let's rename this file to `.env.local.example` to match other examples and be sure that API_KEY's won't be accidentally committed.

2022-06-26 11:25 UTC, balazsorban44 commented on examples/cms-makeswift/README.md
> +3. Update the `.env` file to include your Makeswift site's API key:
```suggestion
3. Rename the `.env.local.example` file to `.env.local` and include your Makeswift site's API key:
```

2022-06-27 14:01 UTC, apledger commented
Thanks for the review @balazsorban44. Fixed all issues.

2022-06-27 21:59 UTC, balazsorban44 commented on docs/advanced-features/preview-mode.md
> +    <li><a href="https://github.com/vercel/next.js/tree/canary/examples/cms-makeswift">Makeswift Example</a> (<a href="https://makeswift-examples-basic-typescript.vercel.app/">Demo</a>)</li>
Not a blocker to merge the PR, but do you want to redeploy this on https://next-blog-makeswift.vercel.app instead for consistency?

2022-06-27 22:02 UTC, balazsorban44 submitted a review, later dismissed

2022-06-27 22:02 UTC, balazsorban44 commented on examples/cms-makeswift/README.md
> +[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https://github.com/vercel/next.js/tree/canary/examples/DIRECTORY_NAME&project-name=cms-makeswift&
```suggestion
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https://github.com/vercel/next.js/tree/canary/examples/cms-makeswift&project-name=cms-makeswift&repository-name=cms-makeswift)
```

2022-06-27 22:02 UTC, balazsorban44 commented on examples/cms-makeswift/README.md
> +### [https://nextjs-makeswift-example.vercel.app/](https://nextjs-makeswift-example.vercel.app/)
See also: https://github.com/vercel/next.js/pull/38018/files#r907833127

Up to you where to point, but at least the README and the link in the docs should probably link to the same example. :+1:

2022-06-29 18:20 UTC, leerob approved these changes

2022-06-29 18:25 UTC, merged