Convert api-routes example to TypeScript
vercel/next.js pull request #38083
Opened 2022-06-28 00:55 UTC by maxproske

Converted API Routes example over to TypeScript to match the Contribution guidelines.

## Documentation / Examples

- [X] Make sure the linting passes by running `pnpm lint`
- [X] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-07-06 12:51 UTC, balazsorban44 requested changes
Let's consider https://github.com/vercel/next.js/pull/38091#discussion_r911320691 on this and all future PRs!

2022-07-06 15:55 UTC, maxproske commented
Thanks @balazsorban44 - I made your requested change.

I thought `function` over `const` only applied to pages, but I'll consider components going forward.

2022-07-08 11:31 UTC, balazsorban44 commented on examples/api-routes/pages/api/people/[id].ts
> +}
This should probably be called something else to not clash with the native `Error` class.

2022-07-08 16:28 UTC, maxproske commented
@balazsorban44 Thanks! Made your requested change, and ready for re-review!

Can I also get confirmation that you recommend `export default function` over split `const`/`export` for components, in addition to pages and API routes in examples?

2022-07-11 10:33 UTC, balazsorban44 approved these changes
Thanks!

As for https://github.com/vercel/next.js/pull/38083#issuecomment-1179169825, I think, for consistency's sake, we should use `function` over `const/let` uniformly, yes. `default` exports might not be necessary though (unless a page or API route), because a file could export multiple things, but these are stylistic details and a grey area what we should enforce vs. prefer.

So (in my opinion) use `function` whenever possible, but at the minimum for API Routes and pages. Rest should be at least consistent throughout the example. :+1:

2022-07-11 10:40 UTC, merged

2022-07-11 12:20 UTC, balazsorban44 commented
Opened https://github.com/vercel/next.js/pull/38511 to discuss the above and add it to the contributing guidelines