fix(examples/with-playwritght): use PORT env variable and fall back to 3000
vercel/next.js pull request #38107
Opened 2022-06-28 13:45 UTC by thebergamo

## Documentation / Examples

- [x] Related issues linked using `fixes #37952`
- [x] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-06-29 12:09 UTC, balazsorban44 requested changes
Thanks, there was an unnecessary change, let's revert that so we can merge this!

2022-06-29 12:15 UTC, thebergamo commented on examples/with-playwright/README.md
> +```bash
Just for context, I got this spark while preparing this PR. 😛

2022-07-06 14:24 UTC, balazsorban44 commented on examples/with-playwright/README.md
> +```bash
We might do that, but let's do it in a different PR then, consistently across all examples. :+1:

2022-07-07 08:16 UTC, thebergamo commented
@balazsorban44 `readme.md` changes reverted.

2022-07-08 10:41 UTC, balazsorban44 approved these changes

2022-07-08 10:54 UTC, merged