feat(next/build): send next-swc plugins telemetry
vercel/next.js pull request #38116
Opened 2022-06-28 17:32 UTC by kwonoj

* Requires prerequisite PR https://github.com/vercel/next-telemetry/pull/84

This PR adds telemetry to send list of the experimental swc plugins from next.config.js. Implementation largely mimics existing plugins telemetry for next_package (https://github.com/vercel/next.js/blob/canary/packages/next/telemetry/events/plugins.ts), with small modification to read swc plugin package instead.

One notable difference is swc plugin telemetry can be sent without version. This is due to swc plugins can be specified with absolute path without any npm pkg resolutions.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have helpful link attached, see `contributing.md`

## Feature

- [x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-06-28 17:54 UTC, padmaia approved these changes, later dismissed

2022-06-28 18:57 UTC, ijjk requested changes
Should we add a test for this to the telemetry test suite? 

x-ref: https://github.com/vercel/next.js/blob/canary/test/integration/telemetry/test/index.test.js

Requesting changes so this doesn't land until the mentioned prerequisite PR is landed.

2022-06-28 18:58 UTC, kwonoj commented
> Should we add a test for this to the telemetry test suite?

I think so, will try to add one.

2022-06-30 16:30 UTC, kwonoj commented
@ijjk upstream PR is now resolved, this PR is good to review I believe.

2022-06-30 18:25 UTC, ijjk approved these changes

2022-06-30 19:05 UTC, merged