Cosmic CMS updates
vercel/next.js pull request #38163
Opened 2022-06-29 18:47 UTC by tonyspiro

## Updates

- Update packages
- Convert to TypeScript

2022-07-06 14:26 UTC, balazsorban44 commented on examples/cms-cosmic/components/alert.tsx
> +export default Alert
```suggestion
```

2022-07-06 14:29 UTC, balazsorban44 commented on examples/cms-cosmic/pages/api/exit-preview.ts
> +export default exit
this seems to be an unnecessary change

2022-07-06 14:29 UTC, balazsorban44 commented on examples/cms-cosmic/pages/api/preview.ts
> +const preview = async (req, res) => {
this seems to be an unnecessary change, let's revert

2022-07-06 14:29 UTC, balazsorban44 commented on examples/cms-cosmic/pages/posts/[slug].tsx
> +export const getStaticPaths = async () => {
this seems to be an unnecessary change, let's revert

2022-07-06 14:32 UTC, balazsorban44 requested changes
Thanks. Generally, I think we would like to keep the `function` declarations. See https://github.com/vercel/next.js/pull/38091#discussion_r911320691

So let's revert those changes. :+1:

2022-07-23 14:51 UTC, tonyspiro commented
> Thanks. Generally, I think we would like to keep the `function` declarations. See [#38091 (comment)](https://github.com/vercel/next.js/pull/38091#discussion_r911320691)
> 
> So let's revert those changes. 👍

@balazsorban44 this should be ready for re review, thank you!

2022-08-12 19:37 UTC, tonyspiro commented
Any update @balazsorban44?

2022-08-12 19:48 UTC, balazsorban44 approved these changes

2022-08-12 19:49 UTC, balazsorban44 commented
Thanks!

2022-08-24 03:22 UTC, tonyspiro commented
Any update on this @balazsorban44?

2022-09-29 22:46 UTC, balazsorban44 commented
Hi @tonyspiro, it seems like your branch does not allow our bot (or me) to merge this PR. Can you make sure you allow contributors to edit so we can merge it?

2022-09-29 22:52 UTC, tonyspiro commented
> Hi @tonyspiro, it seems like your branch does not allow our bot (or me) to merge this PR. Can you make sure you allow contributors to edit so we can merge it?

I just added you to the repo. Please let me know if you need anything else.

2022-09-30 01:06 UTC, balazsorban44 commented
Update @tonyspiro

Turns out it's because of this: https://github.com/orgs/community/discussions/5634

The GitHub UI says there are merge conflicts, but I am not able to see them. Can you fix those? :pray:

![image](https://user-images.githubusercontent.com/18369201/193168260-7ff5d66c-54a1-4529-9956-88ca6ca56170.png)

2022-10-01 04:46 UTC, closed without merging