docs: add trpc to examples
vercel/next.js pull request #38272
Opened 2022-07-03 07:32 UTC by zorrolisto

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

Nice to have nextjs up to date always!

2022-07-06 13:36 UTC, balazsorban44 requested changes
Thanks, I would like to defer to @KATT here. I wonder if tRPC already has an official example, and it would make sense to add a single README.md file here that points to their example. This would make sure that we are in sync with the latest recommendations by the tRPC team.

2022-07-06 18:13 UTC, KATT reviewed
I love how minimal this example is, @zorrolisto, do you wanna add it to https://github.com/trpc/trpc?

We could instead do a README.md with a few links:

- https://github.com/trpc/examples-next-prisma-starter
- https://github.com/trpc/examples-next-prisma-starter-websockets
- [... your minimal example if you add it 🙃]

2022-07-06 19:22 UTC, zorrolisto commented
thanks 🙏, so I need to remove the directories and files, and only left one README.md with the links right? @KATT

2022-07-06 19:40 UTC, balazsorban44 commented
That's correct!

2022-07-08 10:32 UTC, balazsorban44 commented on examples/with-trpc/README.md
> +# Next.js + TRPC
```suggestion
# Next.js + tRPC
```

2022-07-08 10:32 UTC, balazsorban44 commented on examples/with-trpc/README.md
> +## Next.js prisma starter
```suggestion
## Next.js + tRPC + Prisma starter
```

2022-07-08 10:32 UTC, balazsorban44 commented on examples/with-trpc/README.md
> +## Next.js prisma starter websockets
```suggestion
## Next.js + tRPC + Prisma starter with websockets
```

2022-07-08 10:33 UTC, balazsorban44 commented on examples/with-trpc/README.md
> +## Next.js and TRPC minimal implementation
```suggestion
## Next.js and tRPC minimal implementation
```

2022-07-08 10:33 UTC, balazsorban44 approved these changes

2022-07-08 11:00 UTC, merged