docs: add note about middleware being disabled
vercel/next.js pull request #38299
Opened 2022-07-04 14:54 UTC by pheew

Found out while experimenting with middleware that it doesn't run when `useFileSystemPublicRoutes` is set to false. This PR adds a note about this.

https://github.com/vercel/next.js/blob/3eb9caeb6a81dc101beeefdc2046da0777761119/packages/next/server/router.ts#L229-L231

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-07-04 18:35 UTC, leerob requested changes
I don't think this should be added this high up in the documentation. To be honest, I'm not sure what this config option does, so most folks won't be either.

Maybe we need docs specifically for this config option?

2022-07-05 07:16 UTC, pheew commented
I would say it's very important for documentation to be complete. It's very frustrating to have to read the source to find out about these types of exceptions. It took me a good few hours to figure out it wasn't our custom server but the setting in `next.config.js` that caused the middleware to not run. 

I'm not sure what the reasoning is behind disabling middleware when this setting is set to `false`. We're using a custom server (which is the main use-case of the `useFileSystemPublicRoutes` setting) but would still like to use middleware because of the possibility to do rewrites at runtime.

2022-07-06 03:11 UTC, leerob commented
To be clear, I'm not saying we shouldn't document it – just suggesting a different place. Could you talk more about why you need `useFileSystemPublicRoutes`? Sounds like it should be in the custom server documentation, then 👍

2022-07-06 08:28 UTC, pheew commented
> To be clear, I'm not saying we shouldn't document it – just suggesting a different place. 

Yeah understood 👍 

> Could you talk more about why you need `useFileSystemPublicRoutes`? Sounds like it should be in the custom server documentation, then 👍

We're running a custom server and our physical file paths don't match the actual routes / urls. Setting `useFileSystemPublicRoutes` to `false` makes sure the paths aren't exposed as routes publicly by next but still built as part of the build toolchain.

Do you know what the reasoning is behind not attaching the middleware route when it's set to `false` in the code I linked in the PR description? https://github.com/vercel/next.js/blob/3eb9caeb6a81dc101beeefdc2046da0777761119/packages/next/server/router.ts#L229-L231

2023-05-06 23:55 UTC, leerob commented
Closing this as stale, thank you for the suggestion regardless 🙏

2023-05-06 23:55 UTC, closed without merging