adding with-axiom example
vercel/next.js pull request #38300
Opened 2022-07-04 15:26 UTC by schehata

## Documentation / Examples

- [ X ] Make sure the linting passes by running `pnpm lint`
- [ X ] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

This PR adds an example for using next.js with axiom.

2022-07-06 14:11 UTC, balazsorban44 requested changes
Let's convert to TypeScript. See: https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

2022-07-08 10:48 UTC, balazsorban44 commented on examples/with-axiom/package.json
> +    "react-dom": "^18.0.0",
```suggestion
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

2022-07-08 10:49 UTC, balazsorban44 commented on examples/with-axiom/package.json
> +    "typescript": "^4.6.3"
```suggestion
    "typescript": "^4.7.4"
```

2022-07-08 10:49 UTC, balazsorban44 commented on examples/with-axiom/pages/_app.tsx
> +type props = {}
```suggestion
```

This seems to be unused

2022-07-08 10:51 UTC, balazsorban44 commented on examples/with-axiom/middleware.ts
> +async function middleware(_req: NextRequest) {
```suggestion
import { NextResponse } from 'next/server'
import { log, withAxiom } from 'next-axiom'

async function middleware() {
```

2022-07-08 10:52 UTC, balazsorban44 commented on examples/with-axiom/.gitignore
> +.vercel
```suggestion
.vercel

# typescript
*.tsbuildinfo
```

2022-07-08 10:53 UTC, balazsorban44 requested changes
Let's also add a `tsconfig.json` (running `next dev` will generate one)

2022-07-08 10:53 UTC, balazsorban44 commented on examples/with-axiom/README.md
> +## How to use
There should probably be only one `How to use` section

2022-07-12 08:37 UTC, schehata commented
> Let's also add a `tsconfig.json` (running `next dev` will generate one)

added. (thanks for the tip, saved my time :D)

2022-07-25 09:20 UTC, schehata commented
@balazsorban44 is there something that needs to be updated?

2022-08-30 16:40 UTC, steven-tey submitted a review, later dismissed
LGTM! Thanks for the PR! :)

2022-09-01 12:51 UTC, balazsorban44 submitted a review, later dismissed

2022-09-01 14:18 UTC, balazsorban44 approved these changes

2022-09-01 14:50 UTC, merged