Extend contributing
vercel/next.js pull request #38975
Opened 2022-07-24 19:55 UTC by maxproske

Extended the example contribution guidelines for consistency, and learnings I've made as a new contributor.

## Documentation / Examples

- [X] Make sure the linting passes by running `pnpm lint`
- [X] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-07-24 19:57 UTC, maxproske commented on contributing.md
> +- Examples should not add custom ESLint or Prettier configurations (we have specific templates for those)
x-ref: https://github.com/vercel/next.js/pull/38504#discussion_r917839211

2022-07-24 19:57 UTC, maxproske commented on contributing.md
> +- TypeScript `strict` mode should be set to `false` in `tsconfig.json`
x-ref: https://github.com/vercel/next.js/pull/37676#issuecomment-1154894519

2022-07-24 19:57 UTC, maxproske commented on contributing.md
> +- TypeScript examples should not use `prop-types`
x-ref: https://github.com/vercel/next.js/pull/38021#issuecomment-1166491276

2022-07-24 19:57 UTC, maxproske commented on contributing.md
> +- Type definition files should be inside the `interfaces` directory. `.d.ts` modules should be in the root directory
This is a tricky one. The Next.js and React docs don't appear to recommend a location for type definition files. Should the Contribution docs reccomend a directory for consistency? There are currently 13 examples that include type definition files:

- `interfaces/*.ts` 6 examples (including `with-typescript`, mostly from me copying this pattern)
- `types/*.ts`: 1 example (including `with-typescript-types`, and my preference)
- `*.d.ts`: 3 examples (e.g. `environment.d.ts` for environment variables and other globals)
- `components/types.ts`: 1 example (co-located with components?)
- `lib/types.ts`: 1 example 
- `@types/*.ts`: 1 example

2022-07-24 20:01 UTC, maxproske commented on contributing.md
> +
x-ref: https://github.com/vercel/next.js/pull/38395

2022-07-26 13:00 UTC, balazsorban44 requested changes
Thanks for clarifying some of these! I added some comments. In general, we don't want to push our opinions too much when unnecessary, but most of your suggestions make sense! :+1:

2022-07-27 06:40 UTC, maxproske commented on contributing.md
> +- Type definition files should be inside the `interfaces` directory. `.d.ts` modules should be in the root directory
Makes sense! I'll remove it for now.

2022-11-19 08:50 UTC, closed without merging