Fix #3900 return 404 on asset hash mismatch in prod
vercel/next.js pull request #3941
Opened 2018-03-05 21:44 UTC by timteeling

Per #3900 I'm looking to have Next.js respond with a 404 when someone requests a hash from an asset that doesn't exist in production instead of what it currently does which is 500 Internal server error.

Currently, `handleBuildHash` in `server/index.js` throws an error regardless of environment, so I'm looking at tweaking it to send a 404 in production.

**Example:**
200 -> https://custom-server-koa-wxksegmzhf.now.sh/_next/7c048a193f99703d6180e88866b6e06b/app.js

500 Internal server error -> https://custom-server-koa-wxksegmzhf.now.sh/_next/OLD_HASH_VALUE/app.js

Thanks for your time!

2018-03-06 11:45 UTC, arunoda commented on server/index.js
> -      throw new Error(`Invalid Build File Hash(${hash}) for chunk: ${filename}`)
Here's console.log the ^^ message and do `return this.send404(res)`.
In the dev mode, there's no buildId and it's been handled in few lines before.

2018-03-06 11:46 UTC, arunoda requested changes
This is a good one and we need to do 404 instead 500. But I'm looking for a different implementation.

2018-03-06 11:46 UTC, arunoda commented on server/index.js
> -      throw new Error(`Invalid Build File Hash(${hash}) for chunk: ${filename}`)
Here's console.log the ^^ message and do return this.send404(res).
In the dev mode, there's no buildId and it's been handled in few lines before.

2018-03-06 15:34 UTC, timteeling commented
Thanks @arunoda 

It looks like https://github.com/zeit/next.js/pull/3793 changed how this is handled pretty significantly: https://github.com/zeit/next.js/blob/canary/server/index.js#L177

I tweaked `renderScriptError` now instead to return a 404 instead of 500 when `INVALID_BUILD_ID` is the error message

2018-03-28 10:39 UTC, omaksi commented
I'd like to +1 this, is there something that still needs to be improved to get this released?

2018-03-31 07:01 UTC, timneutkens approved these changes
Awesome, just verified the code 👍 thanks Tim 🙏

2018-03-31 07:01 UTC, merged

2018-03-31 07:53 UTC, omaksi commented
Thanks guys, any estimate on when could this be released on npm?