fix: allow `next.config.js` overwrite `cache-control` header
vercel/next.js pull request #39707
Opened 2022-08-18 02:11 UTC by u3u

fixes #21827 #22319 #28557

https://nextjs.org/docs/api-reference/next.config.js/headers#cache-control

>You cannot set `Cache-Control` headers in `next.config.js` file as these will be overwritten in production to ensure that API Routes and static assets are cached effectively.

In the documentation it is described that `cache-control` cannot be overridden and will affect static resources, but in fact static resources will set their own `cache-control`, so it does not seem to affect them.

https://github.com/vercel/next.js/blob/9c416341048a4467d8bcd147c1d5c399fa1ab17a/packages/next/server/next-server.ts#L428-L451

I use `getHeader('Cache-Control')` to check if the user has set their cache, which by default is the same behavior as before.
By the way `hasHeader` is `undefined` in some cases, I don't know why. (#34929 #37338)

2022-09-13 09:24 UTC, juulieen commented
I would be interested in the merge of this PR too 👍

2022-10-03 17:24 UTC, bejarano-tech commented
> Fixes #21827, fixes #22319 #28557
> 
> https://nextjs.org/docs/api-reference/next.config.js/headers#cache-control
> 
> > You cannot set `Cache-Control` headers in `next.config.js` file as these will be overwritten in production to ensure that API Routes and static assets are cached effectively.
> 
> In the documentation it is described that `cache-control` cannot be overridden and will affect static resources, but in fact static resources will set their own `cache-control`, so it does not seem to affect them.
> 
> https://github.com/vercel/next.js/blob/9c416341048a4467d8bcd147c1d5c399fa1ab17a/packages/next/server/next-server.ts#L428-L451
> 
> I use `getHeader('Cache-Control')` to check if the user has set their cache, which by default is the same behavior as before. By the way `hasHeader` is `undefined` in some cases, I don't know why. (#34929 #37338)

Hi, `hasHeader` is `undefined` when you have fallback: false in getStaticPaths

2023-02-15 14:13 UTC, meotimdihia commented
@ijjk this feature is important for everyone who uses self-hosted + Cloudflare.

2023-02-21 15:27 UTC, dbbk commented
Any movement on this?

2023-03-06 10:00 UTC, stefanobrambilla requested changes
hi all, any news about this PR???

2023-05-25 15:15 UTC, cweekly commented
Maintainers, please, could you review this change?

2023-07-08 17:55 UTC, mgray-bemyduo commented
@timneutkens  @stefanobrambilla @ijjk @shuding @huozhi @feedthejim 
Can one of you please review this? It's been sitting here for almost a year and this bug is open because of it https://github.com/vercel/next.js/issues/22319
next-intl is not able to be used with server components until this is resolved. Please see here: https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components

2023-08-30 11:59 UTC, tarun-lilly approved these changes

2024-09-04 11:51 UTC, kmrachko commented
Adding one more voice to the crowd of people affected by that issue - please review it and either provide a clear explanation on why it's undesirable - or get it merged.

2024-09-09 19:58 UTC, closed without merging

2024-09-09 20:17 UTC, ijjk reviewed
Hi, went ahead and landed this against latest changes with added tests in https://github.com/vercel/next.js/pull/69802 thanks for looking into this!