support environment variables without exposing on client
vercel/next.js pull request #399
Opened 2016-12-15 21:43 UTC by matthewmueller

This addresses #159 – only inserts environment variables that are being used, so it doesn't overexpose or anything. Production will provide a default `NODE_ENV=production`, but that can be overridden if you want.

2016-12-15 22:36 UTC, arunoda requested changes

2016-12-15 22:36 UTC, arunoda commented on server/build/webpack.js
> +const env = Object.keys(process.env).reduce(function (o, k) {
This is not secure, it's easy for somebody to know this hack it. Specially, using third party libraries.

So, I suggest to follow what CRA does for this. [See](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/env.js#L15).

I think using `NEXT_` as the prefix is a good idea.

2016-12-15 22:36 UTC, arunoda commented on server/build/webpack.js
> +  o['process.env.' + k] = JSON.stringify(process.env[k])
Now user must use `process.env.NEXT_FOO` in order to use it.
But this doesn't work.

```js
const { NEXT_FOO} = process.env
```

CRA also have a fix for that. Try to use something like that.

2016-12-16 16:15 UTC, matthewmueller commented
@arunoda maybe we're talking about different levels of security, but from what I understand, the client will only get a build with the environment variables that it uses. The server will only serve components that have the specified environment variables baked in. 

I'm basically trying to achieve exactly what https://github.com/hughsk/envify is doing. I think having to prefix everything should be a last option though.

2016-12-16 16:48 UTC, arunoda commented
What if there's some piece of third party module do something like this: 

`console.log(process.env.SOME_SEC_ENV_VAR)`

We don't know what's inside the env vars and the people who write the code and people who run that is different. So, if there's need to something to expose to the client side, that's a total responsibility of the people who run that code.

That's why we need to prefix env vars. So, they must set them explicitly.

2016-12-16 16:56 UTC, matthewmueller commented
Yah, I guess I find that threat level to be greatly outweighed by the convenience of mapping your environment variables directly. 

Usually either it's your teammates running the code with shared environment variables or it's the server. 

The only thing I can think of where this would be an issue is running some open source code, but you should know what you're running beforehand anyway.

2016-12-16 17:07 UTC, arunoda commented
@matthewmueller there could be many reasons we can't come up with.
We don't need to make it less secure. (Even there might be less chance it might happen)

So, prefixing is the way how others deals with this. (Specially CRA, Storybook )

2016-12-21 09:27 UTC, ericf commented on server/build/webpack.js
> +const env = Object.keys(process.env).reduce(function (o, k) {
I agree with the prefix, otherwise someone might expose something they didn't mean to.

2016-12-21 09:33 UTC, ericf commented
I was trying out Next 2.0 Beta tonight, and released with the new custom Webpack config setting env vars can now be accomplished via `next.config.js`: https://github.com/zeit/next.js/issues/159#issuecomment-268476743

That said, I'd still like to see a first-class solution that doesn't involve dealing with Webpack directly. Once nice feature of CRA's env support is reading a `.env` file during development. I'd like that see that be part of the first-class env feature.

2016-12-21 11:35 UTC, arunoda commented
@ericf I'm never a fan of `.env` file of CRA.
There's so many simple ways we could do it when exposing ENV vars are supported like this.

2016-12-28 21:12 UTC, rauchg commented
Is this something we can purely do from webpack extensions, without having to support first-class? I'd like to not have to add support for envs whitelisting really. That should be 100% up to the dev

2016-12-28 21:30 UTC, matthewmueller commented
yah, i think so, need to test is but on the client, the next.config.js would replace the variables, on the server, it would just be a part of process.env.*

i do think this is essential for any client-side web app (something that you'd need day 2 of building any web app), but definitely it in the webpack config is easy enough, so i'll close for now.

2016-12-28 21:30 UTC, closed without merging