docs(examples): refresh `cms-prismic` example
vercel/next.js pull request #40121
Opened 2022-08-31 02:22 UTC by angeloashmore

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

**Note**: `pnpm lint` fails on code unrelated to the changes in this PR.

This PR updates the [Prismic](https://prismic.io/) CMS example (`examples/cms-prismic`) to use the latest Prismic libraries, tools, and conventions.

- Uses `npx @slicemachine/init` to bootstrap new Prismic accounts and content repositories.

- Uses [Slice Machine](https://prismic.io/docs/technologies/slice-machine) to model content.

- Uses [Slices](https://prismic.io/docs/technologies/slice) to write post content.

- Uses the latest versions of the following packages:

  - `@prismicio/client`
  - `@prismicio/helpers`
  - `@prismicio/react`
  - `@prismicio/next`

- Adds generated TypeScript types for Prismic content. The example remains as a JavaScript codebase (i.e. not TypeScript), but makes use of the types via JSDoc.

2022-09-13 11:26 UTC, balazsorban44 requested changes
Nice work! Could we turn this example into TypeScript? This is preferred as pointed out in our contributing document: https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

2022-09-13 22:18 UTC, angeloashmore commented
@balazsorban44 Certainly!

Out of curiosity, do you have any insight on how non-TypeScript developers use these examples projects? Does using TypeScript in examples pose a challenge to these developers?

2022-09-29 22:11 UTC, balazsorban44 commented
@angeloashmore we believe that everyone should start off with TypeScript. Not only it gives a better developer experience but will catch many bugs before going to production. Types can be stripped away, and it would still be valid TypeScript, as it is just a superset of JavaScript, so developers who do not want TypeScript can just do so after cloning the example.

2022-09-29 22:13 UTC, balazsorban44 approved these changes

2022-10-01 04:06 UTC, merged