[Docs] Migrated image-component example to typescript
vercel/next.js pull request #40153
Opened 2022-09-01 12:46 UTC by HaNdTriX

## Changelog

- migrated example to typescript
- abstracted layout stuff to make example more readable
- adjust layout

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm lint`
- [x] The examples guidelines are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples)

2022-09-01 14:21 UTC, balazsorban44 commented on examples/image-component/package.json
>      "react-dom": "^17.0.2"
Could we bump these?
```suggestion
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

2022-09-01 14:26 UTC, balazsorban44 requested changes
Thanks, added some comments. Could you address those?

2022-09-02 08:38 UTC, HaNdTriX commented
@balazsorban44 Thanks for your review!

2022-09-02 15:16 UTC, styfle commented on examples/image-component/styles/globals.css
> +}
These don't seem specific to typescript

2022-09-02 15:23 UTC, styfle requested changes
This breaks the background image demo 

I suggest creating the first PR that is just JS => TS. 

The create a second PR that makes style changes.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/229881/188182203-aa6bee7d-ea09-4d18-b2b8-6c832fcb4465.png">

2022-09-03 10:20 UTC, HaNdTriX commented
> This breaks the background image demo

Good catch! I have fixed this issue. Next time I will keep the git history clean I promise 😜.

2022-09-04 08:25 UTC, HaNdTriX commented
closing in favour of https://github.com/vercel/next.js/pull/40204

2022-09-04 08:25 UTC, closed without merging