Set `__NEXT_NEW_LINK_BEHAVIOR` in Jest tests when `newNextLinkBehavior` is true
vercel/next.js pull request #40702
Opened 2022-09-20 01:32 UTC by TomerAberbach

Fixes #40463

Could use some help figuring out where to add a test! I looked around and found [`jest-next-swc.test.ts`](https://github.com/vercel/next.js/blob/canary/test/unit/jest-next-swc.test.ts), but I don't think I can use that to test this fix. Anyways, from my local testing this PR seems to fix the issue.

2022-09-20 14:09 UTC, timneutkens requested changes, later dismissed
Hey! This is the right place to add a test: `test/production/jest/index.test.ts`

2022-09-21 12:29 UTC, terrymun commented
This is some awesome news @TomerAberbach :) thank you so much for looking into this, much appreciated!

2022-09-21 23:15 UTC, TomerAberbach commented
> This is some awesome news @TomerAberbach :) thank you so much for looking into this, much appreciated!

No problem! I probably should have mentioned, in the meantime you should be able to work around the issue by manually setting the `__NEXT_NEW_LINK_BEHAVIOR` environment variable to `true` for your Jest tests.

2022-09-22 05:36 UTC, ijjk approved these changes
Thanks!

2022-09-22 05:36 UTC, merged