Run next/link codemod for Next.js 13 on examples
vercel/next.js pull request #41913
Opened 2022-10-26 22:55 UTC by timneutkens

- Run link codemod on examples
- Run prettier

Ensures the examples show `<Link>` usage correctly.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

2022-10-27 00:49 UTC, styfle commented on examples/api-routes-rest/pages/index.tsx
> +          <Link href="/user/[id]" as={`/user/${user.id}`} legacyBehavior>
Does this one need to be legacy? Looks like the child is already correct

2022-10-27 00:49 UTC, styfle commented on examples/auth0/components/header.tsx
>                <a>Home</a>
Seems like a bug: i would expect this anchor to be removed

2022-10-27 20:21 UTC, balazsorban44 requested changes
There are some edge cases that seemingly haven't fully been considered by the codemod, so we might want to fix that first and add some tests. We could fix https://github.com/vercel/next.js/issues/41925 at the same time too

2022-10-29 21:39 UTC, styfle commented on examples/auth0/components/header.tsx
>                <a>Home</a>
Do we know why a style tag would affect the link? Seems like emitted HTML should be the same since “Link” becomes “a” with the new behavior.

2022-10-30 19:09 UTC, styfle approved these changes

2022-10-30 19:15 UTC, styfle commented
@balazsorban44 @timneutkens Lets merge this? 

Seems like the issues it will fix are greater than the issues it introduces. 

For example, it should close

- https://github.com/vercel/next.js/pull/42114
- https://github.com/vercel/next.js/pull/42181

2022-10-30 20:00 UTC, merged