update font optimization page
vercel/next.js pull request #42266
Opened 2022-10-31 22:29 UTC by ismaelrumzan

Update to using `pages/` instead of `app/`

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

2022-11-01 13:16 UTC, hanneslund requested changes

2022-11-01 13:16 UTC, hanneslund commented on docs/basic-features/font-optimization.md
> +```js:pages/index.js
Should the example use the font in a component that the page renders, to make it clear that you don't have to call the font function in the actual page for it to work? What do you think?
```js:pages/index.js
import Header from "../components/header.js"

export default function Home() {
  return (
    <>
        <Header>Test</Header>
        <p>Hello World</p>
    </>
  );
}
```

```js:components/header.js
import { inter } from "../styles/fonts.js"

export default function Header({ children }) {
  return <h1 className={inter.className}>{children}</h1>;
}
```

2022-11-01 15:52 UTC, delbaoliveira submitted a review, later dismissed

2022-11-01 15:52 UTC, delbaoliveira commented on docs/basic-features/font-optimization.md
> +To use the font in all your pages, add it to `_app.js` or `_app.tsx` under `/pages` as shown below:
```suggestion
To use the font in all your pages, add it to [`_app.js` file](https://nextjs.org/docs/advanced-features/custom-app) under `/pages` as shown below:
```

2022-11-02 14:04 UTC, delbaoliveira commented on docs/basic-features/font-optimization.md
> +````
```suggestion
```
```

2022-11-02 14:04 UTC, delbaoliveira commented on docs/basic-features/font-optimization.md
> +````
```suggestion
```

2022-11-02 14:15 UTC, timneutkens approved these changes

2022-11-02 14:25 UTC, timneutkens approved these changes

2022-11-02 14:25 UTC, merged