refactor example - blog-with-example
vercel/next.js pull request #42640
Opened 2022-11-08 17:20 UTC by ademilter

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

2022-11-08 17:23 UTC, leerob commented
Is it deployed anywhere we can test?

2022-11-08 17:24 UTC, ademilter commented
@leerob yeap, https://blog-with-comment.vercel.app

2022-11-08 19:57 UTC, siggy17 commented
Can confirm I was able to log in and leave a comment!

2022-11-09 02:25 UTC, balazsorban44 commented on examples/blog-with-comment/.env.local.example
> +NEXTAUTH_URL=http://localhost:3000
```suggestion
```

It's not, it's the default value. It shows up as a warning, but it is a bug in `next-auth`. Will try to address here: https://github.com/nextauthjs/next-auth/pull/5763

2022-11-09 02:26 UTC, balazsorban44 commented on examples/blog-with-comment/README.md
> +using Upstash and NextAuth.
```suggestion
This project adds commenting functionality to the [Next.js blog application](https://github.com/vercel/next.js/tree/canary/examples/blog)
using Upstash and NextAuth.js.
```

2022-11-09 02:26 UTC, balazsorban44 commented on examples/blog-with-comment/README.md
> +user can delete their own comment. Also admin user can delete any comment.
```suggestion
The comment box requires NextAuth.js authentication for users to add new comments. A
user can delete their own comment. Also, admin users can delete any comment.
```

2022-11-09 02:27 UTC, balazsorban44 commented on examples/blog-with-comment/README.md
> +## `1` Set up project
For this section, let's follow other example readmes like: https://github.com/vercel/next.js/tree/canary/examples/hello-world#how-to-use

2022-11-09 02:28 UTC, balazsorban44 commented on examples/blog-with-comment/README.md
> +Environment Variables** and set them to
```suggestion
**Important**: When you import your project on Vercel, make sure to click on ** Environment Variables** and set them to
```

2022-11-09 02:29 UTC, balazsorban44 commented on examples/blog-with-comment/hooks/useComment.ts
>          },
It looks like auth is not required anymore?

2022-11-09 02:30 UTC, balazsorban44 commented on examples/blog-with-comment/hooks/useComment.ts
>          },
https://github.com/vercel/next.js/pull/42640/files#r1017342306

2022-11-09 02:30 UTC, balazsorban44 commented on examples/blog-with-comment/lib/createComment.ts
> +  )) as Session
```suggestion
  const session = await unstable_getServerSession(
    req,
    res,
    authOptions
  )
```

2022-11-09 02:31 UTC, balazsorban44 commented on examples/blog-with-comment/lib/createComment.ts
> +import { NextAuthOptions } from 'next-auth'
```suggestion
```

2022-11-09 02:31 UTC, balazsorban44 commented on examples/blog-with-comment/lib/createComment.ts
> +import type { Comment, Session } from '../types'
```suggestion
import type { Comment } from '../types'
```

2022-11-09 02:32 UTC, balazsorban44 commented on examples/blog-with-comment/lib/deleteComment.ts
> +import { Session } from '../types'
```suggestion
```

2022-11-09 02:32 UTC, balazsorban44 commented on examples/blog-with-comment/lib/deleteComment.ts
> +  )) as Session
```suggestion
  const session = await unstable_getServerSession(
    req,
    res,
    authOptions
  )
```

2022-11-09 02:32 UTC, balazsorban44 commented on examples/blog-with-comment/lib/deleteComment.ts
> +import { NextAuthOptions } from 'next-auth'
```suggestion
```

2022-11-09 02:35 UTC, balazsorban44 commented on examples/blog-with-comment/pages/api/auth/[...nextauth].js
> +    },
```suggestion
    async session({ session, user }) {
      session.user.role = session.user.email === process.env.ADMIN_EMAIL
        ? 'admin'
        : 'user'
      return session
    },
```

2022-11-09 02:35 UTC, balazsorban44 commented on examples/blog-with-comment/pages/api/auth/[...nextauth].js
> +export const authOptions = {
```suggestion
export const authOptions: NextAuthOptions = {
```

2022-11-09 02:37 UTC, balazsorban44 requested changes
Thanks, I added some suggestions that should further simplify this example.

2022-11-09 02:39 UTC, balazsorban44 commented on examples/blog-with-comment/package.json
> +    "prettier": "^2.7.1",
```suggestion
```

2022-11-09 02:39 UTC, balazsorban44 commented on examples/blog-with-comment/package.json
>      "@auth0/auth0-react": "^1.12.0",
```suggestion
```

2023-02-23 04:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| buildDuration | 40.7s | 39.8s | -912ms |
| buildDurationCached | 15.7s | 11.4s | -4.3s |
| nodeModulesSize | 111 MB | 111 MB | ⚠️ +32 B |
| nextStartRea..uration (ms) | 298ms | 288ms | -10ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| 246.HASH.js gzip | 181 B | 181 B | ✓ |
| 843-HASH.js gzip | 65.8 kB | 65.8 kB | ✓ |
| main-app-HASH.js gzip | 204 B | 204 B | ✓ |
| main-HASH.js gzip | 79 kB | 79 kB | -1 B |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| Overall change | 147 kB | 147 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 179 B | 178 B | -1 B |
| amp-HASH.js gzip | 482 B | 483 B | ⚠️ +1 B |
| css-HASH.js gzip | 803 B | 803 B | ✓ |
| dynamic-HASH.js gzip | 2.27 kB | 2.27 kB | -2 B |
| edge-ssr-HASH.js gzip | 259 B | 258 B | -1 B |
| head-HASH.js gzip | 830 B | 828 B | -2 B |
| hooks-HASH.js gzip | 850 B | 848 B | -2 B |
| image-HASH.js gzip | 4.33 kB | 4.32 kB | -2 B |
| index-HASH.js gzip | 253 B | 253 B | ✓ |
| link-HASH.js gzip | 2.76 kB | 2.75 kB | -4 B |
| routerDirect..HASH.js gzip | 781 B | 781 B | ✓ |
| script-HASH.js gzip | 859 B | 856 B | -3 B |
| withRouter-HASH.js gzip | 781 B | 781 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.7 kB | 15.7 kB | -16 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 484 B | -1 B |
| Overall change | 485 B | 484 B | -1 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| index.html gzip | 489 B | 490 B | ⚠️ +1 B |
| link.html gzip | 504 B | 506 B | ⚠️ +2 B |
| withRouter.html gzip | 483 B | 487 B | ⚠️ +4 B |
| Overall change | 1.48 kB | 1.48 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | -5 B |
| page.js gzip | 94.7 kB | 94.8 kB | ⚠️ +18 B |
| Overall change | 223 kB | 223 kB | ⚠️ +13 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | hiddenest/next.js canary | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 588 B | 586 B | -2 B |
| middleware-r..fest.js gzip | 145 B | 144 B | -1 B |
| middleware.js gzip | 26.5 kB | 26.5 kB | ⚠️ +9 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 29 kB | 29 kB | ⚠️ +6 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,81 +7,81 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js"
   ],
   rootMainFiles: [
-    "static/chunks/webpack-778ee737b42dbd09.js",
-    "static/chunks/843-1ac90fbadcf50fb2.js",
-    "static/chunks/main-app-b041559968d205e4.js"
+    "static/chunks/webpack-078d588fd47873c4.js",
+    "static/chunks/983-3b20f93cd23b1c97.js",
+    "static/chunks/main-app-f68e193b03e7d2bc.js"
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/index-72f4ed6964652f6a.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/index-a1c4d9d8497dbefb.js"
     ],
     "/_app": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/_app-02fdba2e11c62c3b.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/_app-b68f71a961b48916.js"
     ],
     "/_error": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/_error-c6d6c7c386122218.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/_error-a22ef5f48ba8184b.js"
     ],
     "/amp": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/amp-b62e7c28809c13e0.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/amp-eaaa44ffdc03cc2c.js"
     ],
     "/css": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-36a39dbaff01b205.js"
+      "static/chunks/pages/css-f537b6a4daa0415d.js"
     ],
     "/dynamic": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/dynamic-dbb2ff3d32b913f9.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/dynamic-e47195a0fa3d3ead.js"
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/edge-ssr-a57e88de1ff426bd.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/edge-ssr-18640e2c6cb99ab4.js"
     ],
     "/head": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/head-b5894c626904a778.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/head-f756eefe15b9eed2.js"
     ],
     "/hooks": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/hooks-874b5779f127e436.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/hooks-74323ca92508884f.js"
     ],
     "/image": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/image-4a7835c4e7d52fda.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/image-00185e15271bf249.js"
     ],
     "/link": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-54d202f51c7115c3.js",
-      "static/chunks/pages/link-2843620f3fd1a35c.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-cd2a534a9be925ef.js",
+      "static/chunks/pages/link-b3714a44ebdb3150.js"
     ],
     "/routerDirect": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/c [...]

2023-06-15 02:51 UTC, leerob commented
Closing this as stale, but open to reviewing a new PR if you're interested in continuing this forward!

2023-06-15 02:51 UTC, closed without merging