initial commit
vercel/next.js pull request #42898
Opened 2022-11-14 14:29 UTC by notrab

This PR adds the `with-grafbase` example. `with-` prefix can be removed to follow guidelines but unsure if this is outdated since all other examples include this for similar services.

## Documentation / Examples

- [x] Make sure the linting passes by running `pnpm build && pnpm lint`
- [x] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

2022-11-14 15:56 UTC, balazsorban44 commented on examples/with-grafbase/.env.example
> +GRAFBASE_API_KEY=
Assuming this is a secret, `.env.local.example` is more appropriate for a file name.

2022-11-14 15:57 UTC, balazsorban44 commented on examples/with-grafbase/.eslintrc.json
> +  "extends": "next/core-web-vitals"
Should be removed as per https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md

2022-11-14 15:57 UTC, balazsorban44 commented on examples/with-grafbase/package.json
> +    "eslint-config-next": "13.0.3",
```suggestion
```

2022-11-14 15:57 UTC, balazsorban44 commented on examples/with-grafbase/package.json
> +    "lint": "next lint",
```suggestion
```

2022-11-14 15:58 UTC, balazsorban44 commented on examples/with-grafbase/package.json
> +    "next": "13.0.3",
```suggestion
    "next": "latest",
```

2022-11-15 09:59 UTC, notrab commented
Thanks for reviewing @balazsorban44. I didn't quite finish pushing changes yesterday hence the draft PR so most of your comments should be resolved in that.

2022-11-15 10:34 UTC, balazsorban44 requested changes
Can you make sure that linting passes? https://github.com/vercel/next.js/actions/runs/3469499938/jobs/5796602833

you can run `pnpm prettier --write examples/with-grafbase` and commit the changed files

2022-11-15 10:35 UTC, balazsorban44 commented on examples/with-grafbase/package.json
> +  "version": "0.1.0",
```suggestion
```

2022-11-15 12:45 UTC, notrab commented
@balazsorban44 all done 🙌🏻

2022-11-15 15:22 UTC, balazsorban44 approved these changes

2022-11-15 15:22 UTC, balazsorban44 commented
Thanks!

2022-11-15 18:18 UTC, merged