Pass searchParams prop to head
vercel/next.js pull request #43305
Opened 2022-11-23 15:47 UTC by itrelease

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

2022-11-24 10:11 UTC, timneutkens commented on test/e2e/check-searchparams-in-head/app/head.js
> +export default function HomePage({ searchParams }) {
Specifically https://github.com/vercel/next.js/tree/canary/test/e2e/app-dir/head

2022-11-24 10:11 UTC, timneutkens requested changes
Blocking merge on a review from @sebmarkbage

2022-11-24 10:46 UTC, itrelease commented on test/e2e/check-searchparams-in-head/app/head.js
> +export default function HomePage({ searchParams }) {
I've encountered weird behaviour. When I'm creating new nextjs app and link imports from source code I see that everything works, but when I run test `searchParams` are missing (not only for head files but also for page files) and `query` is always an empty object

2023-02-05 21:41 UTC, closed without merging

2023-02-06 17:10 UTC, gaspardip commented
> It should only be passed if the resolved head.ts file is at the same level as page.ts, but we have some new APIs coming that will solve this anyway.

mind to share a workaround while these new APIs are coming out?