automatically map jest paths to ts paths
vercel/next.js pull request #43313
Opened 2022-11-23 22:32 UTC by philihp

This resolves the comment

```js
// Handle module aliases (this will be automatically configured for you soon)
```

by making it happen, with the `ts-jest` package.

2022-11-23 22:39 UTC, timneutkens requested changes
Resolving those paths should be part of next/jest. ts-jest can't be used as it would differ from the resolving logic you get from Next.js.

2022-11-24 01:49 UTC, philihp commented
Is Next.js doing any resolving logic? It looks like the paths in this example are defined in tsconfig, at
https://github.com/vercel/next.js/blob/v13.0.5/examples/with-jest/tsconfig.json#L19-L21

2023-01-01 15:22 UTC, timneutkens commented
Hey! Sorry I missed your message. Next.js has a tsconfig.json resolver for webpack that lives here: https://github.com/vercel/next.js/blob/ec25b4742b1087e76f2b3378d41a8ab0f6686ca4/packages/next/build/webpack/plugins/jsconfig-paths-plugin.ts
However for the Jest case we'll probably want to use SWC's built-in `paths` resolving option instead as Jest doesn't have resolver plugins afaik.

2023-06-15 02:51 UTC, leerob commented
Closing based on the previous comment 🙏

2023-06-15 02:51 UTC, closed without merging

2023-06-16 07:32 UTC, philihp commented
SGTM, thanks for all your work on Next.js!