Fix IPv6 hostname formatting in CLI
vercel/next.js pull request #43491
Opened 2022-11-29 06:40 UTC by akshitsinha

Checks if CLI `--hostname` parameter is an IPv6 IP address, and formats it correctly in `stdout`.

**Before** / **After**
<img width="800" alt="Untitled" src="https://user-images.githubusercontent.com/34775769/204454298-c30e8492-fbd2-4cfc-af31-ce9c12aca7a9.png">

Fixes #21979

2022-12-12 09:25 UTC, JanKaifer requested changes
Thanks for the PR, could you try adding tests covering this?
And it would be great if you could achieve this without the nested `? :` operators - it's a little hard to read.

2022-12-16 14:46 UTC, JanKaifer requested changes
Thanks for following up. Just a small nitpick to make the intention a bit clearer and we are good to go.

2022-12-16 14:46 UTC, JanKaifer commented on packages/next/server/lib/start-server.ts
> +        hostname = hostname === '::' ? `[${hostname}1]` : `[${hostname}]`
```suggestion
        if (hostname === '::') hostname = '::1'
        hostname = `[${hostname}]`
```

2022-12-16 18:33 UTC, akshitsinha commented on packages/next/server/lib/start-server.ts
> +        hostname = hostname === '::' ? `[${hostname}1]` : `[${hostname}]`
Should be good now. 👍

2022-12-17 23:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| buildDuration | 36.9s | 36.8s | -113ms |
| buildDurationCached | 10.2s | 11s | ⚠️ +797ms |
| nodeModulesSize | 95 MB | 95 MB | ⚠️ +2.44 kB |
| nextStartRea..uration (ms) | 276ms | 272ms | -4ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| 246.HASH.js gzip | 181 B | 181 B | ✓ |
| 437-HASH.js gzip | 64.5 kB | 64.5 kB | -6 B |
| main-app-HASH.js gzip | 206 B | 205 B | -1 B |
| main-HASH.js gzip | 79.1 kB | 79.1 kB | ✓ |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| Overall change | 146 kB | 146 kB | -6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 179 B | 178 B | -1 B |
| amp-HASH.js gzip | 482 B | 483 B | ⚠️ +1 B |
| css-HASH.js gzip | 803 B | 804 B | ⚠️ +1 B |
| dynamic-HASH.js gzip | 2.29 kB | 2.29 kB | -3 B |
| edge-ssr-HASH.js gzip | 259 B | 258 B | -1 B |
| head-HASH.js gzip | 830 B | 828 B | -2 B |
| hooks-HASH.js gzip | 850 B | 848 B | -2 B |
| image-HASH.js gzip | 4.25 kB | 4.25 kB | ✓ |
| index-HASH.js gzip | 253 B | 253 B | ✓ |
| link-HASH.js gzip | 2.68 kB | 2.68 kB | -3 B |
| routerDirect..HASH.js gzip | 781 B | 781 B | ✓ |
| script-HASH.js gzip | 859 B | 856 B | -3 B |
| withRouter-HASH.js gzip | 781 B | 781 B | ✓ |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 15.6 kB | 15.6 kB | -13 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 483 B | -2 B |
| Overall change | 485 B | 483 B | -2 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| index.html gzip | 490 B | 490 B | ✓ |
| link.html gzip | 505 B | 505 B | ✓ |
| withRouter.html gzip | 484 B | 486 B | ⚠️ +2 B |
| Overall change | 1.48 kB | 1.48 kB | ⚠️ +2 B |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| edge-ssr.js gzip | 110 kB | 110 kB | -5 B |
| page.js gzip | 98.4 kB | 98.4 kB | -1 B |
| Overall change | 209 kB | 209 kB | -6 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | akshitsinha/next.js ipv6fix | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 586 B | 585 B | -1 B |
| middleware-r..fest.js gzip | 145 B | 144 B | -1 B |
| middleware.js gzip | 27.2 kB | 27.2 kB | -1 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 29.7 kB | 29.7 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,81 +7,81 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js"
   ],
   rootMainFiles: [
-    "static/chunks/webpack-778ee737b42dbd09.js",
-    "static/chunks/437-ff60c979a5ae56b7.js",
-    "static/chunks/main-app-12a4424998444d69.js"
+    "static/chunks/webpack-078d588fd47873c4.js",
+    "static/chunks/745-3123b95ecb3ba326.js",
+    "static/chunks/main-app-1cfbd6c767615cfe.js"
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/index-72f4ed6964652f6a.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/index-a1c4d9d8497dbefb.js"
     ],
     "/_app": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/_app-02fdba2e11c62c3b.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/_app-b68f71a961b48916.js"
     ],
     "/_error": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/_error-c6d6c7c386122218.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/_error-a22ef5f48ba8184b.js"
     ],
     "/amp": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/amp-b62e7c28809c13e0.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/amp-eaaa44ffdc03cc2c.js"
     ],
     "/css": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-860762b9808f5e42.js"
+      "static/chunks/pages/css-ce50591629177489.js"
     ],
     "/dynamic": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/dynamic-16c73801272b45fa.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/dynamic-fa1df0b4842534e4.js"
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/edge-ssr-a57e88de1ff426bd.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/edge-ssr-18640e2c6cb99ab4.js"
     ],
     "/head": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/head-b5894c626904a778.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/head-f756eefe15b9eed2.js"
     ],
     "/hooks": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/hooks-874b5779f127e436.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/hooks-74323ca92508884f.js"
     ],
     "/image": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/image-854b6400b5b29f63.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/image-a27f28e834bc3106.js"
     ],
     "/link": [
-      "static/chunks/webpack-778ee737b42dbd09.js",
-      "static/chunks/main-2540897785a35a2b.js",
-      "static/chunks/pages/link-64f5c14f89f65607.js"
+      "static/chunks/webpack-078d588fd47873c4.js",
+      "static/chunks/main-d5a14d0f206abb2a.js",
+      "static/chunks/pages/link-2dd5f16503707acd.js"
     ],
     "/routerDirect": [
-      "static/chunks/webpack-778ee [...]

2022-12-19 09:43 UTC, JanKaifer submitted a review, later dismissed

2023-01-09 06:14 UTC, akshitsinha commented
I've resolved any merge conflicts of the past few weeks. Let me know if I'm missing anything for this to be merged. Thanks.

2023-01-09 07:40 UTC, JanKaifer reviewed
Hey sorry it's taking so long. I'll make sure we merge this quickly.

2023-01-09 07:40 UTC, JanKaifer commented on packages/next/src/cli/next-dev.ts
>            const appUrl = `http://${app.hostname}:${app.port}`
We don't need to change this?

2023-01-10 08:53 UTC, JanKaifer commented on packages/next/src/cli/next-dev.ts
>            const appUrl = `http://${app.hostname}:${app.port}`
Great. lets <picture data-single-emoji=":shipit:" title=":shipit:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..wVxnRUcaGpoyL4p7.1KKOM9OBc5yzVReOm2XStRYsk7z9PDeqRuEzKnIugIy4LPhYC0Dm_07FhdV7DNujGjQ5Y84I9rzzAc2hScc9GFP8OIp3TiTzOhIN-027XKReIA.5axmcXEYGzOfekFt3Ei1kg" alt=":shipit:" align="absmiddle"></picture>

2023-01-10 09:18 UTC, timneutkens approved these changes
Looks good!

2023-01-10 10:06 UTC, merged