Allow onClick on next/link component's child
vercel/next.js pull request #4474
Opened 2018-05-25 18:53 UTC by mmiszy

Allo `onClick` on `next/link` child. This should not be a breaking change, but it's a very useful feature. Real-life use cases include: analytics or closing menu on navigation.

- [x] allow optional `onClick` on `next/link` component's child
- [x] call original `child.props.onClick(e)` before `this.linkClicked(e)`
- [x] add integration tests

Fixes #1490

2018-05-25 21:22 UTC, timneutkens commented on lib/link.js
> +        if (child.props && typeof child.props.onClick === 'function') {
Smart 👍

2018-05-25 21:24 UTC, timneutkens requested changes
Besides the tests failing and preventDefault not being handled this PR looks great to me 👍

2018-05-25 23:48 UTC, mmiszy commented
Yes, about those tests… I'm not sure why they failed ;) I'll dig into that tomorrow.
Thanks for the review!

2018-05-26 10:13 UTC, timneutkens commented
If you want to run a single test you can do it like this:

```
yarn testonly --testPathPattern "basic" -t "delete a page and add it back"
```

Where `basic` is the test suite (integration/basic) and `delete a page and add it back` is the specific test you want to run.

2018-05-26 21:05 UTC, brandonjcreek commented
Keeping my eye on this.  This is one of those minor pain points of Next that creep up on me more often times than not.

2018-05-27 18:44 UTC, timneutkens approved these changes
💯 awesome 👌

2018-05-27 18:47 UTC, merged

2018-05-27 18:47 UTC, timneutkens commented
Thank you very much!

2018-05-27 22:01 UTC, mmiszy commented
Thank YOU 👍