Removed deprecated React life cycle methods
vercel/next.js pull request #4533
Opened 2018-06-04 08:12 UTC by dipiash

First fix for #4479

2018-06-06 16:02 UTC, assimelha approved these changes
Working perfectly

2018-06-07 10:03 UTC, timneutkens requested changes
For all these PRs we'd need to do add the `react-lifecycles-compat` polyfill, to be compatible with older versions. I'd like to do that for the tests even.

2018-08-23 06:37 UTC, piuccio commented on test/integration/basic/pages/stateful.js
> +      return {answer: 42}
why not just setting 42 in the constructor?

2018-08-23 16:18 UTC, timneutkens commented
I believe we should remove the test for this, as it's an anti-pattern when doing SSR. I'll do it sometime in the future.

2018-08-23 16:18 UTC, closed without merging