Support generateMetadata export
vercel/next.js pull request #45401
Opened 2023-01-30 09:58 UTC by huozhi

## Feature

- [x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [x] [e2e](https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md#writing-tests-for-nextjs) tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md)

2023-01-30 10:09 UTC, ijjk commented
## Failing test suites <!--10657395946-->
Commit: 1929f5f00db2406e9384ad18ec8cde6103e2be43

`pnpm testheadless test/e2e/app-dir/metadata/metadata.test.ts` 
- app dir - metadata > metadata > basic > should apply metadata when navigating client-side

<details>
<summary>Expand output</summary>

  ● app dir - metadata › metadata › basic › should apply metadata when navigating client-side

    expect(received).toBe(expected) // Object.is equality

    Expected: "origin-when-crossorigin"
    Received: undefined

      47 |           expect(values).toEqual(content)
      48 |         } else {
    > 49 |           expect(values[0]).toBe(content)
         |                             ^
      50 |         }
      51 |       }
      52 |

      at checkMeta (e2e/app-dir/metadata/metadata.test.ts:49:29)
      at Object.<anonymous> (e2e/app-dir/metadata/metadata.test.ts:281:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2023-01-31 18:33 UTC, shuding commented on test/e2e/app-dir/metadata/app/apple/page.tsx
> +  return metadata
Can you add tests to confirm that it receives these 2 arguments?

2023-01-31 20:02 UTC, shuding submitted a review, later dismissed

2023-01-31 20:09 UTC, timneutkens requested changes
This doesn't handle the cache() deduping yet it seems. Will double check first.

2023-02-01 08:36 UTC, timneutkens requested changes
Checked and added some tests that are failing 👍

2023-02-01 11:54 UTC, timneutkens approved these changes

2023-02-01 11:54 UTC, merged