Add serverless example hosted on AWS Lambda
vercel/next.js pull request #4609
Opened 2018-06-14 17:29 UTC by PR1YANKPAT3L

I was able to get next.js working with serverless as requested by #4482.
This example uses with-react-i18next as a scenario where the express server is not initialized right away.

2018-06-14 17:49 UTC, timneutkens commented
Can we use `hello-world` as a base? 🤔 To not make things overly complex.

2018-06-14 19:11 UTC, PR1YANKPAT3L commented
@timneutkens Updated example with simple hello-world.

2018-06-14 21:39 UTC, timneutkens requested changes
I guess the i18n code can be removed then

2018-06-14 22:15 UTC, priyankpat reviewed
Remove i18n code from the example and updated README instructions.

2018-06-15 09:19 UTC, timneutkens commented on examples/with-aws-serverless/server.js
> +const handle = app.getRequestHandler()
`app.prepare()` is missing here.

2018-06-24 17:16 UTC, Skaronator requested changes

2018-06-24 17:16 UTC, Skaronator commented on examples/with-aws-serverless/serverless.yml
> +    events:
You can merge `nextJsRootApp` and `nextJsAnyApp` events - just change the events to this:

```diff
    events:
     - http: ANY {proxy+}
+    - http: ANY /
```

2018-06-24 17:34 UTC, Skaronator commented on examples/with-aws-serverless/serverless.yml
> +  exclude:
Please add `yarn.lock` as well.

2018-06-24 17:52 UTC, Skaronator commented on examples/with-aws-serverless/.babelrc
> +  }
Remove space before `}`

2018-06-24 17:58 UTC, Skaronator requested changes

2018-06-24 17:58 UTC, Skaronator commented on examples/with-aws-serverless/serverless.yml
> +  runtime: nodejs6.10
You should change this to Node 8.10 (better performance & cost less)

2018-06-29 01:30 UTC, lolcoolkat commented
I'm assuming we'll be waiting for https://github.com/zeit/next.js/issues/4496 in order for this to work, right?  :D

2018-06-29 10:17 UTC, Skaronator commented
It works without #4496 like any other node.js server with next. (Just not as fast as with #4496)

2018-07-01 14:53 UTC, lolcoolkat commented
@Skaronator I tried to test this out.. however it didn't work? After I deployed the application and went to the site.. and tried to click the link.. it gave a "Forbidden" message? Any ideas on that?

2018-07-01 15:05 UTC, Skaronator commented
Check out this repo: https://github.com/mitchellhuang/future

The files you need should be: lambda.js, next.config.js and server.js + serverless config

2018-07-01 16:14 UTC, lolcoolkat commented
@Skaronator Is the domain with the api gateway required? :)

2018-07-01 17:05 UTC, lolcoolkat commented
Is the CloudFront distribution created automatically? It outputted a Cloudfront url but didn't actually create it? Please check this http://i.prntscr.com/TXTMfnbIScKTNN8sE9GLJw.png

2018-07-01 17:08 UTC, Skaronator commented
CloudFront is not required. (I think it doesn't even work since it is just a CDN)

Looks like you're trying to deploy mitchellhuang/future but I've never done that. Only copyed the relevant parts out of it.

2018-07-02 01:05 UTC, lolcoolkat commented
@Skaronator idk still couldn't get it working even after putting your stuff in.. the index page works fine..but after I click a link to go to a new route it just says Forbidden. I guess i'll just wait until an official example is released.

2018-07-26 08:31 UTC, skriems commented
I think I've found the culprit here @PR1YANKPAT3L . If you open up your browsers dev tools you'll notice that scripts fail to load from `<url>/_next/...` and the reason for that is, that the `provider.stage` defined in the `serverless.yml` file gets appended to the URL. So basically you need to use an `assetPrefix` here.
Since this is unique to the Lambda environment you can use an env var in your `serverless.yml` and have your `app.setAssetPrefix` in `server.js` based on that env var.

Note that this is not needed if you would use a custom domain via `serverless-custom-domain`. I'm looking into that now.

I've deployed the material-ui nextjs example to Lambda in this repo
https://github.com/skriems/next-material

Best

2018-07-27 04:57 UTC, lolcoolkat commented
@skriems Your repo worked great for me! 

**Note**: To get the repo working through Cloudfront and a custom domain, you need to remove the following from the server.js file:

```
if (process.env.LAMBDA) {
  // `assetPrefix` needs to match `serverless.yml:provider.stage
  let assetPrefix = dev ? '/dev' : '/prod'
  app.setAssetPrefix(assetPrefix)
}
```

At least that's what I had to do :)

2018-07-28 12:30 UTC, Skaronator commented
Weird... I'm using a custom domain via `serverless-domain-manager` (not a subdomain) and everything just works without modifying the assetPrefix.

2018-07-28 14:06 UTC, skriems commented
How odd. I just tried again without adding a prefix and with `basePath: ''` but I get those 403's. Is it related to the region and/or `endpointType` ?

2018-07-28 14:47 UTC, Skaronator commented
Ah the  `execute-api.eu-central-1.amazonaws.com` endpoint has a `/prod` which mess up the whole path while the custom domain doesn't have it. Thanks to this mapping:
![image](https://user-images.githubusercontent.com/2886913/43357694-ef2cc864-9285-11e8-8786-effcf159034c.png)

2018-07-28 14:52 UTC, skriems commented
exactly that's the problem. Any opinion on how this should be included/documented in the example?

2018-07-28 14:54 UTC, Skaronator commented
It might be better to use [Lambda@Edge](https://aws.amazon.com/de/lambda/edge/) instead of Lambda with APIGateway but Serverless doesn't support it yet due to a bug in CloudFormation.

https://github.com/serverless/serverless/pull/4796

2018-09-04 22:33 UTC, Enalmada commented
@skriems [next-material](https://github.com/skriems/next-material) serverless example worked great.  If the requested changes in this pull are not being acted on promptly, can we just get that into the next.js examples section?      

Also, I see a few serverless example request tickets imply that there might be good reason for a next.js example to handle the "scenario where the express server is not initialized right away."   Can any of the serverless hackers in this thread confirm if a serverless example based on "with-react-i18next" would be different in any fundamental way than one based on "hello-world"?  Does the [next-material](https://github.com/skriems/next-material) example use an express server not initialized right away?

2018-09-20 16:33 UTC, romainquellec commented
> between 150ms and 2.5s when "warm".

If you have 2.5s of response time, you did something wrong with your lambda. Waiting for https://github.com/zeit/next.js/issues/4496 though !

2018-09-20 16:35 UTC, romainquellec commented
also, why serverless-http over aws-serverless-express ?

2018-09-20 18:43 UTC, Enalmada commented
> If you have 2.5s of response time, you did something wrong with your lambda. 

@romainquellec It is certainly possible and testing was extremely unscientific.  So everyone can do their own testing I will elaborate slightly:  If I refresh my serverless next.js example quickly (once a second) the responses definitely tend to average closer to 150ms.   If I wait a few minutes between each refresh (small enough interval that containers should be warm, trying to replicate my actual site traffic pattern), responses vary wildly between 150ms and 2.5s.  YMMV and this is just food for thought as I was just messing around.

2018-12-10 15:55 UTC, timneutkens commented
I'm going to close this PR in favor of the work we're doing towards making Next.js output single-route lambdas.

2018-12-10 15:55 UTC, closed without merging