Merge url query with exportPathMap
vercel/next.js pull request #4678
Opened 2018-06-26 22:07 UTC by lucleray

In this PR, I worked on #4615

From the issue :
> One thing we might consider is merging and showing a warning for keys not defined in exportPathMap

The behaviour after this PR is the following :

```js
// next.config.js
module.exports = {
  exportPathMap: () => ({
    '/': { page: '/', query: { a: 'blue' } }
  })
}
```

| url called | `ctx.query` | warning ? |
|-|-|-|
| `/` | `{ a: 'blue' }` | |
| `/?a=red` | `{ a: 'blue' }` | |
| `/?b=green` | `{ a: 'blue', b: 'green' }` | `... parameter 'b' missing in exportPathMap` |

Is that the expected behaviour ? If not, I'll update the PR to shape the expected behavior.

2018-06-27 08:38 UTC, timneutkens commented on server/index.js
> +            const mergedQuery = Object.assign({}, urlQuery, query)
Lets do `{...urlQuery, ...query}` instead of `Object.assign`

2018-06-27 09:09 UTC, timneutkens approved these changes
Let's add a test for this new behavior 👍 can be added in test/integration/export

2018-06-27 09:11 UTC, timneutkens requested changes
My review was actually a request changes

2018-06-27 15:55 UTC, timneutkens commented
I actually gave the wrong directory, `static` already has tests for `next export`.

2018-06-27 16:07 UTC, lucleray commented
@timneutkens I added the tests for the 3 scenario in the PR's description.

I ran into the following problems while writing the tests :

### 1. `launchApp` / `killApp`
If I used `launchApp` from the `next-test-utils`, it was harder to catch `console.warn` call and the app wouldn't shut down properly.

`killApp` does kill the PID of the spawned process, here :
https://github.com/zeit/next.js/blob/7fcfb8bde91af096af6905ec8c426934f667f0b6/test/lib/next-test-utils.js#L102-L104

But it does not kill the PID of the "subprocess" spawned by the spawned process 💣 
Basically, `launchApp` spawn a new process : `next`, which spawns another new process : `next-dev`
They get PID and PID+1 (for example 44013 and 44014).
`killApp` only kills PID, but not PID+1. They would need to be both killed for `killApp` to work properly.

### 2. `startApp` / `stopApp` 
There is a bug in `stopApp`, I think.

More precisely here :

https://github.com/zeit/next.js/blob/7fcfb8bde91af096af6905ec8c426934f667f0b6/test/lib/next-test-utils.js#L116-L121

`app` is never touched.

### What I did

So I ended up simply using `start` and `stop` from `server/next`. Not sure it's the best thing to do for integration test. Let me know 🙂

2018-06-27 16:08 UTC, lucleray commented
@timneutkens 
Oh, ok, I can move the tests to `static`

2018-06-27 16:50 UTC, timneutkens commented
You actually don't have to test the console.log calls, just check loading the page with a querystring and `query` defined and see if it works. We don't test console.log side effects as they will most likely change in the future and can't break anything.

2018-06-27 22:30 UTC, lucleray commented
I fixed the tests, I removed the test for console.log.

2018-06-28 06:37 UTC, timneutkens approved these changes
Looks great 👍

2018-06-28 06:37 UTC, merged