Added delta to reportWebVitals
vercel/next.js pull request #46908
Opened 2023-03-08 08:17 UTC by bordeo

### Adding a feature

- Exposes the `delta` value for `reportWebVitals`

Closes #44953 #36148

2023-03-08 08:44 UTC, timneutkens requested changes
Can you add a test for this change?

2023-03-09 08:10 UTC, bordeo commented
Test added and template updated

2023-05-09 09:11 UTC, timneutkens reviewed
Hey! Seems this is missing support for `useReportWebVitals`, once that is added this should be good to land 👍

2026-04-08 13:38 UTC, closed without merging

2026-04-08 13:39 UTC, timneutkens commented
Going to close this PR as it's outdated.