allow multi-threading while exporting static files
vercel/next.js pull request #4765
Opened 2018-07-11 15:57 UTC by bkniffler

This PR will
- allow nextjs export to use all available CPU cores for rendering & writing pages by using child_process
- make use of promise-limit to allow each thread to concurrently write multiple paths
- show a fancy progress bar while processing pages

The performance gain for my MacBook with 4 CPU cores went from ~25 pages per second to ~75 pages per second. Beefy CI machines with lots of cores should profit even more.

2018-07-11 22:09 UTC, timneutkens approved these changes
This looks great! could you move the files related to exporting inside `server` to a new top-level directory called `export`, that way we split out export/server as they're not the same thing 👍

The `render` file can be kept in `server` for now, I'm just talking about `server/export.js` and `server/export-worker.js`

2018-07-11 22:10 UTC, timneutkens requested changes
I actually meant request changes

2018-07-11 22:15 UTC, timneutkens commented on server/export-worker.js
> +const promiseLimit = require('promise-limit')
Could you replace `promise-limit` with `async-sema` https://github.com/zeit/async-sema

The install size for async-sema is half of promise-limit and it has more feature (should we use it further in Next.js in the future)

2018-07-11 23:44 UTC, timneutkens commented
Amazing job! Will review it in the morning 👍🏻👌🏻

2018-07-12 00:21 UTC, timneutkens commented
Seems like travis failed because we run tests on node 6, as per #4639's breaking changes feel free to update travis.yml to use node 8

2018-07-12 08:16 UTC, timneutkens commented
> you stated I can update travis to node8 but I also needed to update appveyor due to async-sema

Yeah that's alright

> not related to my PR: The test directory for export is called static. Shouldn't it be export?

I agree, I've been meaning to change that, lets do it after webpack 4 lands as I'm fixing a lot of tests there.

2018-09-14 13:02 UTC, Atsman commented
And what is the current status?)

2018-09-21 15:47 UTC, bkniffler commented
I've updated this PR to reflect the requested change :) anything else needed for merge?

2018-12-10 23:47 UTC, timneutkens commented
@bkniffler sorry for the delay in getting back to you, so since you first created this PR the codebase has changed quite a bit, and `next export` is now in it's own directory. If you could open a new PR with your changes I'd be super happy to merge it (this time without delays) 🙏

2018-12-10 23:48 UTC, timneutkens commented
@bkniffler if you could also send me a DM on spectrum that'd be awesome: https://spectrum.chat/users/timneutkens

2018-12-12 12:28 UTC, closed without merging

2018-12-12 12:33 UTC, timneutkens commented
Awesome!