Fix: fixed incorrect classification of dependencies types (dev vs non-dev) when using create-next-app
vercel/next.js pull request #48076
Opened 2023-04-07 12:39 UTC by notEpsilon

## What?
this PR fixes the problem that dependencies like (typescript, tailwindcss, postcss, autoprefixer, eslint, ...) are installed as normal `dependencies`, not `devDependencies`.

## Why?
this is the `package.json` generated by running `npx create-next-app@latest` with `typescript`, `eslint`, and `tailwindcss` included.

![Screenshot (400)](https://user-images.githubusercontent.com/58993233/230604474-84a4de91-7b3c-44b6-9545-7f3942f6d842.png)

which **contradicts** with the **recommended**  approaches from official sites as shown below.

* **Tailwindcss**

![Screenshot (402)](https://user-images.githubusercontent.com/58993233/230605836-d50aa9c9-b7c7-401a-9b81-3e71f63eeb78.png)

* **Typescript**

![Screenshot (403)](https://user-images.githubusercontent.com/58993233/230606098-1bd2edaf-d46b-4066-a92d-b1a293007896.png)

* **ESLint**

![Screenshot (404)](https://user-images.githubusercontent.com/58993233/230606838-cabc093e-e785-4c90-9543-cfc41234bd31.png)

## How?
just separated the `devDependencies` from `dependencies` and added them into an array for installation with the `devDependencies` option marked as `true`.

2023-04-07 15:23 UTC, ijjk requested changes
Hi, this is on purpose as the separation is no longer necessary since Next.js has proper tracing for production dependencies via `output: 'standalone'` and leveraging `devDependencies` still causes un-necessary dependencies to be included in production installs.

2023-04-07 15:23 UTC, closed without merging

2023-04-11 02:34 UTC, tbveloso commented
> Hi, this is on purpose as the separation is no longer necessary since Next.js has proper tracing for production dependencies via `output: 'standalone'` and leveraging `devDependencies` still causes un-necessary dependencies to be included in production installs.

Does this apply to any library? Prettier, etc...?

2023-04-23 19:52 UTC, Divlo commented
> Hi, this is on purpose as the separation is no longer necessary since Next.js has proper tracing for production dependencies

@ijjk Even if it is no longer necessary, it is cleaner to separate dependencies clearly.
Can this be reconsidered? Also what are the advantages to include everything in dependencies, I see none, and instead has one disadvantage is to create confusion.

2023-05-02 23:01 UTC, notEpsilon commented
Does this mean that i shouldn't install any dependency as a `devDependency` ?