fix(next_core): do not apply user config to internal assets
vercel/next.js pull request #48210
Opened 2023-04-10 19:10 UTC by kwonoj

### What?
This is necessary changes for the WEB-862, however dependent to https://github.com/vercel/turbo/pull/4521.

2023-04-17 09:07 UTC, alexkirsz reviewed
Can we test this somehow? The way it's written now, I would expect us to break this unexpectedly in the future.

2023-04-17 09:07 UTC, alexkirsz commented on packages/next-swc/crates/next-core/src/next_client/context.rs
> +            // We will not apply any user defined transforms
```suggestion
            // If the module is an internal asset (i.e overlay, fallback) coming from the embedded FS,
            // don't apply user defined transforms.
```

2023-04-17 09:07 UTC, alexkirsz commented on packages/next-swc/crates/next-core/src/next_client/context.rs
> +                })
```suggestion
                ModuleOptionsContext {
                    enable_typescript_transform: Some(TypescriptTransformOptions::default().cell()),
                    ..module_options_context.clone()
                }
```

2023-04-17 14:55 UTC, kwonoj commented
> Can we test this somehow? The way it's written now, I would expect us to break this unexpectedly in the future.

Mind share the scope we want to test? For the happy path (that user having offending config) there are tests like https://github.com/vercel/next.js/blob/canary/test/development/basic/emotion-swc/jsconfig.json#L3 confirms behavior. Otherwise for the negative path (if internal asset fails to render) it caused hard fail so any of integration test would fail.

2023-04-19 16:42 UTC, sokra requested changes
Could you add a test case for the bug

2023-04-19 16:42 UTC, sokra commented on packages/next-swc/crates/next-core/src/next_client/context.rs
> +                ContextCondition::InPath(next_js_fs().root()),
There are more paths that are affected. `turbopack-dev` has an filesystem too

2023-04-19 17:04 UTC, kwonoj commented
> Could you add a test case for the bug

@sokra As wrote above, I'm thinking existing integration test (emotion) could be a happy path verification for this instead of making some duplicated test under next-dev-tests. Thoughts? or we should duplicate?

2023-04-19 17:23 UTC, sokra commented
> I'm thinking existing integration test (emotion) could be a happy path verification for this instead of making some duplicated test under [next-dev-tests](https://linear.app/vercel/issue/NEXT-dev-tests).

I'm fine with that. Does they pass for that PR? Where can I see that?

I think it shouldn't pass as there is the filesystem for turbopack-dev missing. So I wonder if it's passing?

2023-04-19 17:26 UTC, kwonoj commented
> Does they pass for that PR? Where can I see that?

It passed locally, so I'm planning to prep PR like this https://github.com/vercel/turbo/pull/4610 after landing this.

> I think it shouldn't pass as there is the filesystem for turbopack-dev missing. So I wonder if it's passing?

No, it passed. I believe that's cause of user config that affects the internal output (`jsxImportSource`) is not being used by any assets under `turbopack-dev` anyway.

2023-04-20 18:10 UTC, sokra commented
> Regardless, my question still remains: shouldn't turbopack-* need to control how turbopack-dev being transformed? otherwise say any consumer other than [next-dev](https://linear.app/vercel/issue/NEXT-dev) in the future they can control (and break) how those assets being compiled by their own configs.

probably yes.

> jsxImportSource

I would also say a tsconfig.json should only affect files in that directory/package and doesn't have global effects.

e.g. in a monorepo you could have multiple packages with different tsconfigs.json which have different jsxImportSources.

2023-04-20 18:12 UTC, kwonoj commented
> probably yes.

Yes, I'm trying to make a PR to turbopack to this.

> I would also say a tsconfig.json should only affect files in that directory/package and doesn't have global effects.

Yes, agreed too. What should be changed in this PR?

2023-04-20 18:14 UTC, sokra commented
I think there are two types or configuration that should apply differently.

* global configuration that applies to all modules (potentially bringing their own filtering)
    * `ModuleOptionContext`
    * `ResolveOptionContext`
* local configuration that only applies to a certain context (usually a directory)
    * `tsconfig.json`
    * `package.json` (e. g. `browser` alias field, `sideEffects: false` flag, `type: "module"`

2023-04-20 18:19 UTC, kwonoj commented
It sounds like it's another changes we want to how to deal with configs - while this PR specifically aims for `excluding` any user level configs for the internal assets. Am I reading something incorrect that this PR should include all of suggested changes?

2023-04-26 20:24 UTC, sokra commented
> Am I reading something incorrect that this PR should include all of suggested changes?

Let's make that a follow-up PR

2023-04-26 20:24 UTC, sokra approved these changes

2023-04-26 21:15 UTC, jridgewell approved these changes, later dismissed
Alternatively, we can pass the `Asset` instead of the `FileSystemPathVc`, which would allow us to detect that the asset is a virtual one (either our internal assets, or a asset we dynamically construct).

2023-04-27 14:38 UTC, sokra commented
> which would allow us to detect that the asset is a virtual one (either our internal assets, or a asset we dynamically construct).

We had this before, but that's not that great since in future other plugins could use virtual assets too and they shouldn't be affected.

2023-04-27 14:47 UTC, sokra approved these changes

2023-04-29 05:40 UTC, sokra approved these changes, later dismissed

2023-05-01 16:24 UTC, ijjk commented
## Failing test suites <!--12567015132-->
Commit: 2cdf8941eed6911e6a6a1f19e9dc1111e5064c06

`pnpm testheadless test/development/acceptance-app/dynamic-error.test.ts` 
- dynamic = "error" in devmode > should show error overlay when dynamic is forced

<details>
<summary>Expand output</summary>

  ● dynamic = "error" in devmode › should show error overlay when dynamic is forced

    Application is in inconsistent state: timeout.

      76 |           }
      77 |           if (status !== 'pending') {
    > 78 |             throw new Error(`Application is in inconsistent state: ${status}.`)
         |                   ^
      79 |           }
      80 |
      81 |           await new Promise((resolve) => setTimeout(resolve, 30))

      at Object.patch (development/acceptance-app/helpers.ts:78:19)
      at Object.<anonymous> (development/acceptance-app/dynamic-error.test.ts:17:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2023-05-02 03:09 UTC, padmaia approved these changes

2023-05-02 04:49 UTC, merged