Refactor require hooks
vercel/next.js pull request #48506
Opened 2023-04-17 22:44 UTC by shuding

Similar to #48297, but without the React channel branching logic to make it easier to land. Since we have #48478 reverted, we only need to consider `pages` and `app` inside the require hook.

> This PR aims to improve the current require hook by implementing two key changes. Firstly, it ensures that the initialization occurs at the top of the module level for correctness. Secondly, we now set the NEXT_PREBUNDLED_REACT environment variable at the process level to ensure that we don't mix the two types of rendering processes and we always resolve the correct React package.
>
> These improvements are made possible by the changes introduced in PR https://github.com/vercel/next.js/pull/47857.
> 
> Closes [NEXT-231](https://linear.app/vercel/issue/NEXT-231).

2023-04-17 22:50 UTC, ijjk commented
## Failing test suites <!--12298560964-->
Commit: 7e5135d46674d0e5f1242945adb6e7d8360d6e16

`pnpm testheadless test/production/app-dir-hide-suppressed-error-during-next-export/index.test.ts` 
- app-dir-hide-suppressed-error-during-next-export > should not log suppressed error when exporting static page

<details>
<summary>Expand output</summary>

  ● app-dir-hide-suppressed-error-during-next-export › should not log suppressed error when exporting static page

    expect(received).toInclude(expected)

    Expected string to include:
      "Page build time error"
    Received:
      "yarn run v1.22.19
    $ /tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.bin/next build
    warn  - You have enabled experimental feature (appDir) in next.config.js.
    warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.·
    info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
    info  - Creating an optimized production build...
    info  - Using locally built binary of @next/swc
    info  - Compiled successfully
    info  - Linting and checking validity of types...
    info  - Collecting page data...
    node:internal/bootstrap/node:412
          return _process;
          ^·
    RangeError: Maximum call stack size exceeded

      19 |   it('should not log suppressed error when exporting static page', async () => {
      20 |     await expect(next.start()).rejects.toThrow('next build failed')
    > 21 |     expect(next.cliOutput).toInclude('Page build time error')
         |                            ^
      22 |     expect(next.cliOutput).toInclude('occurred prerendering page "/"')
      23 |     expect(next.cliOutput).toInclude(
      24 |       'Export encountered errors on following paths'

      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:46:5)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at Function.resolve (../node:internal/modules/cjs/helpers:116:19)·
      Node.js v18.16.0
      Static worker unexpectedly exited with code: 1 and signal: null
      node:internal/bootstrap/node:412
            return _process;
            ^·
      RangeError: Maximum call stack size exceeded
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:46:5)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at Function.resolve (../node:internal/modules/cjs/helpers:116:19)·
      Node.js v18.16.0
      node:internal/bootstrap/node:412
            return _process;
            ^·
      RangeError: Maximum call stack size exceeded
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:46:5)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at Function.resolve (../node:internal/modules/cjs/helpers:116:19)·
      Node.js v18.16.0
      node:internal/bootstrap/node:412
            return _process;
            ^·
      RangeError: Maximum call stack size exceeded
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:46:5)
      at ../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:94:9
      at overrideReact (../../tmp/next-install-74007b108e8c5a0c177d94df17d2b9a873a07e4d90d3b68b6f4dde6f943b5ca7/node_modules/.pnpm/file+..+next-repo-9bf3dd358fe89aac2788ab275a246048_a2cxvwm5pqnrnryoc576nnsnla/node_modules/next/dist/server/require-hook.js:50:25)
      at ../../tmp/next-i [...]

2023-04-18 09:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| buildDuration | 1m 5.1s | 1m 1s | -4.2s |
| buildDurationCached | 15.3s | 13.8s | -1.4s |
| nodeModulesSize | 113 MB | 113 MB | ⚠️ +3.37 kB |
| nextStartRea..uration (ms) | 549ms | 568ms | ⚠️ +19ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| 846-HASH.js gzip | 23 kB | 23 kB | -13 B |
| 869.HASH.js gzip | 181 B | 180 B | -1 B |
| 974ec2d0-HASH.js gzip | 50.2 kB | 50.2 kB | ✓ |
| main-app-HASH.js gzip | 214 B | 217 B | ⚠️ +3 B |
| main-HASH.js gzip | 84.7 kB | 84.7 kB | -8 B |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | ✓ |
| framework-HASH.js gzip | N/A | 597 B | N/A |
| Overall change | 160 kB | 161 kB | ⚠️ +578 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 180 B | 179 B | -1 B |
| amp-HASH.js gzip | 504 B | 501 B | -3 B |
| css-HASH.js gzip | 801 B | 328 B | -473 B |
| dynamic-HASH.js gzip | 2.32 kB | 1.86 kB | -455 B |
| edge-ssr-HASH.js gzip | 259 B | 259 B | ✓ |
| head-HASH.js gzip | 828 B | 354 B | -474 B |
| hooks-HASH.js gzip | 849 B | 367 B | -482 B |
| image-HASH.js gzip | 4.47 kB | 4.03 kB | -443 B |
| index-HASH.js gzip | 252 B | 254 B | ⚠️ +2 B |
| link-HASH.js gzip | 2.81 kB | 2.37 kB | -442 B |
| routerDirect..HASH.js gzip | 781 B | 311 B | -470 B |
| script-HASH.js gzip | 858 B | 391 B | -467 B |
| withRouter-HASH.js gzip | 782 B | 307 B | -475 B |
| 85e02e95b279..7e3.css gzip | 107 B | 107 B | ✓ |
| Overall change | 16 kB | 11.8 kB | -4.18 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| _buildManifest.js gzip | 486 B | 527 B | ⚠️ +41 B |
| Overall change | 486 B | 527 B | ⚠️ +41 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| index.html gzip | 549 B | 489 B | -60 B |
| link.html gzip | 558 B | 524 B | -34 B |
| withRouter.html gzip | 545 B | 506 B | -39 B |
| Overall change | 1.65 kB | 1.52 kB | -133 B |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall decrease ✓</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| edge-ssr.js gzip | 133 kB | 77 kB | -56.2 kB |
| page.js gzip | 120 kB | 120 kB | -24 B |
| Overall change | 253 kB | 197 kB | -56.2 kB |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js shu/czko | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 607 B | 629 B | ⚠️ +22 B |
| middleware-r..fest.js gzip | 145 B | 144 B | -1 B |
| middleware.js gzip | 20.8 kB | 20.8 kB | ⚠️ +5 B |
| edge-runtime..pack.js gzip | 1.83 kB | 1.83 kB | ✓ |
| Overall change | 23.4 kB | 23.4 kB | ⚠️ +26 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware-b..-manifest.js</strong></summary>

```diff
@@ -7,82 +7,91 @@ self.__BUILD_MANIFEST = {
     "static/BUILD_ID/_ssgManifest.js",
   ],
   rootMainFiles: [
-    "static/chunks/webpack-d9965445ebce461e.js",
-    "static/chunks/974ec2d0-4c2565133a55f6e5.js",
-    "static/chunks/846-d4aa414de7b694f8.js",
-    "static/chunks/main-app-47129a8c4cef6f97.js",
+    "static/chunks/webpack-8451e80629c17cac.js",
+    "static/chunks/39549b6b-3b590f20ccacdf78.js",
+    "static/chunks/992-cdddea117e718987.js",
+    "static/chunks/main-app-7083e2db548310ad.js",
   ],
   pages: {
     "/": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/index-96b4df8f97c0f01a.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/pages/index-b21e2d2005e858d6.js",
     ],
     "/_app": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/_app-39c49a32fdfb4902.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/pages/_app-fd2fd11c0153c1f4.js",
     ],
     "/_error": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/_error-d79135b4d7090152.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/pages/_error-65d572d29e2548b7.js",
     ],
     "/amp": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/amp-4f82750ed7628465.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/pages/amp-17ae5f0b78cf6cf6.js",
     ],
     "/css": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/framework-c601afd235646144.js",
       "static/css/94fdbc56eafa2039.css",
-      "static/chunks/pages/css-5e256e56d8e26951.js",
+      "static/chunks/pages/css-def6640896bfc8ae.js",
     ],
     "/dynamic": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/dynamic-f9b20c01d3c6f1ed.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/framework-c601afd235646144.js",
+      "static/chunks/pages/dynamic-74b989e16656971a.js",
     ],
     "/edge-ssr": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/edge-ssr-36372aa7b0810cd4.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/pages/edge-ssr-53842fa626eeba30.js",
     ],
     "/head": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/head-bba3641f74516a0d.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/framework-c601afd235646144.js",
+      "static/chunks/pages/head-5379f346c867bad3.js",
     ],
     "/hooks": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/hooks-5bc49a85e3a1ebb1.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1054a67d5faf.js",
+      "static/chunks/framework-c601afd235646144.js",
+      "static/chunks/pages/hooks-de95c57c7e37a962.js",
     ],
     "/image": [
-      "static/chunks/webpack-d9965445ebce461e.js",
-      "static/chunks/main-d8b17b854bb0315d.js",
-      "static/chunks/pages/image-2aa38dd88b51ac96.js",
+      "static/chunks/webpack-8451e80629c17cac.js",
+      "static/chunks/main-189c1 [...]

2023-04-21 16:08 UTC, shuding commented on test/development/app-render-error-log/app-render-error-log.test.ts
> +      expect(cliOutput).toInclude('at EdgePage (./app/edge/page.tsx')
The line numbers here were not correct in the first place - I assume that it has something to do with our SWC generated code / sourcemaps.

2023-04-21 16:43 UTC, ijjk approved these changes
Looks good, thanks!

2023-04-21 16:46 UTC, huozhi requested changes
Looks good, hold for release

2023-04-21 22:19 UTC, merged

2023-05-02 14:31 UTC, dominikzogg commented
I use hooks in a monorepo with a symlink to a shared folder embedded as. I guess this change is broke it.
Its broken since 13.3.2

{
  "workspaces": [
    "shared"
  ]}