refactor(next-core): extract custom transforms
vercel/next.js pull request #48899
Opened 2023-04-26 23:45 UTC by kwonoj

#### What
Part 1 for WEB-848. 

This PR implements initial path to enable relay compiler option in Turbopack. PR is based on approach WEB-955, that passing custom plugin transform itself instead of trying to pass down configuration into turbopack. In result, this PR requires counterpart turbopack PR at .

PR also refactors next-shared's transform bit, as we have grown number of custom transforms.

2023-04-27 21:17 UTC, kwonoj commented on packages/next-swc/crates/next-core/src/next_shared/transforms/relay.rs
> +        program.visit_mut_with(&mut resolver(
@kdy1 It doesn't seem like this is the correct way.

I tried to pass `ctx.unresolved_mark` and let it be applied, like

```
let ctxt = SyntaxContext::empty().apply_mark(unresolved_mark);
let ident = Ident::new("require".into(), Span::new(...).with_ctxt(ctxt.unwrap()));
```

But weirdly it gives error

```
    Panic: PanicInfo { payload: Any { .. }, message: Some(assertion failed: `(left != right)`
      left: `Mark(0)`,
     right: `Mark(0)`), location: Location { file: "/Users/ojkwon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.31.5/src/syntax_pos/hygiene.rs", line: 375, col: 13 }, can_unwind: true }
```

Probably I'm doing something wrong?

2023-05-02 17:58 UTC, sokra requested changes

2023-05-02 18:15 UTC, kwonoj commented on packages/next-swc/crates/next-core/src/next_shared/transforms/mod.rs
> +}
This is preserving existing logic, not a new one for the relay. May need further refactoring to remove the place it uses this.

2023-05-02 18:44 UTC, sokra commented
needs rebase

2023-05-09 15:45 UTC, sokra approved these changes

2023-05-09 15:53 UTC, ijjk commented
## Failing test suites <!--12778004384-->
Commit: 27f6f932e7e18d7384de4c4c2d90329cc0ae045a

`pnpm testheadless test/e2e/middleware-dynamic-basepath-matcher/test/index.test.ts` 
- Middleware custom matchers basePath > should match query path

<details>
<summary>Expand output</summary>

  ● Middleware custom matchers basePath › should match query path

    expect(received).toBe(expected) // Object.is equality

    Expected: "another-page"
    Received: "random"

      51 |     await browser.elementById('linkelement').click()
      52 |     const anotherPagePath = await browser.elementById('router-path').text()
    > 53 |     expect(anotherPagePath).toBe('another-page')
         |                             ^
      54 |   })
      55 | })
      56 |

      at Object.<anonymous> (e2e/middleware-dynamic-basepath-matcher/test/index.test.ts:53:29)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2023-05-09 17:47 UTC, ijjk approved these changes

2023-05-09 18:09 UTC, merged