[Example] cms-payload
vercel/next.js pull request #49616
Opened 2023-05-10 15:48 UTC by JessChowdhury

This PR adds `cms-payload` to the examples folder. The demo provides a NextJS frontend, built with Payload, which can be deployed together in a single instance.

### Improving Documentation or adding/fixing Examples

- [ ] The "examples guidelines" are followed from our contributing doc https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md
- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`. See https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md

2023-05-18 19:57 UTC, dvakatsiienko commented
The CI pipeline fails because of a change to **package.json**.
#49997

2023-05-30 13:57 UTC, JessChowdhury commented
> The CI pipeline fails because of a change to **package.json**. #49997

I didn't change an existing package.json, only added a new one within this self contained example.

2023-06-15 15:15 UTC, leerob approved these changes, later dismissed

2023-06-15 15:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 7dde3dd6a760639b7f60ff89fae60be2d3e3d760

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-15 15:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 7dde3dd6a760639b7f60ff89fae60be2d3e3d760

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-15 15:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 7dde3dd6a760639b7f60ff89fae60be2d3e3d760

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-15 15:25 UTC, balazsorban44 commented on examples/cms-payload/package.json
> +    "eslint-config-next": "13.1.1",
```suggestion
```

2023-06-15 15:25 UTC, balazsorban44 commented on examples/cms-payload/package.json
> +    "lint": "next lint",
```suggestion
```

2023-06-15 15:25 UTC, balazsorban44 commented on examples/cms-payload/package.json
> +  "description": "Demo of Payload deployed as Vercel functions within NextJS",
```suggestion
  "description": "Demo of Payload and Next.js",
```

2023-06-15 15:27 UTC, balazsorban44 commented on examples/cms-payload/app/(payload)/admin/[...slug]/page.tsx
> +export default PayloadAdmin;
```suggestion
// Need to render the same component for anything within /admin
export { default } from "../page"
```

A handy tip.

2023-06-15 15:28 UTC, balazsorban44 commented on examples/cms-payload/app/(site)/[slug]/page.tsx
> +import React from 'react'
This import seems to be unused. You don't need to import `React` anymore if you don't reference it, let's drop it here, and all other places as well. :+1:

2023-06-15 15:31 UTC, balazsorban44 requested changes, later dismissed
Thanks!

There are linting errors, please run `pnpm prettier -w examples/cms-payload` to make sure these are addressed.

2023-06-15 16:00 UTC, JessChowdhury commented on examples/cms-payload/nodemon.json
> +  "exec": "ts-node payload/server.ts"
I removed this file as we were no longer using it.

2023-06-16 02:17 UTC, leerob submitted a review, later dismissed

2023-06-16 13:15 UTC, ijjk approved these changes, later dismissed

2023-06-16 14:32 UTC, merged