Update with-redux example to app router
vercel/next.js pull request #49994
Opened 2023-05-18 13:21 UTC by dvakatsiienko

### What?

Update **with-redux** example.

### Why?

**with-redux** example have:
- outdated packages
- outdated approaches and relies on **pages** directory

Since **app router** is stable now and is recommended to use, I've updated this example.

### How?

An update includes:
- move example to **app router**
- update **package.json** deps to the latest versions
- modernize jest by switching from **ts-node** to **@swc/jest**
- fix and overhaul **tests**
- modernize **redux** infra
- overhaul example **source code quality**

2023-05-18 13:52 UTC, dvakatsiienko commented
Hi, @leerob @steven-tey 

It seems that Github Actions CI got broken at [Socket Security: Pull Request Alerts](https://github.com/vercel/next.js/pull/49994/checks?check_run_id=13581495697) and it blocks CI pipeline to advance.

This happens for multiple PR's related to **examples** directory. [I've created an issue for that](https://github.com/vercel/next.js/issues/49997).

2023-06-15 02:24 UTC, leerob requested changes
It would be great to simplify this example. Remote saas, remove testing, and focus specifically on Next.js + Redux only in the most minimal, yet complete, example.

2023-06-15 08:48 UTC, dvakatsiienko commented
Sounds like a good idea, I'll simplify it.

2023-06-15 15:48 UTC, dvakatsiienko commented
@leerob I've removed tests and sass, see if all good now.

2023-06-15 16:21 UTC, balazsorban44 commented on examples/with-redux/package.json
> +    "next": "13.4.5",
```suggestion
    "next": "latest",
```

2023-06-15 16:23 UTC, balazsorban44 requested changes
Let's drop `src` as well, to match other examples.

2023-06-15 16:24 UTC, balazsorban44 commented on examples/with-redux/package.json
> +    "waait": "1.0.5"
let's drop `waait` in favor of `await new Promise(r => setTimeout(r, 500));
`

2023-06-15 16:24 UTC, balazsorban44 commented on examples/with-redux/package.json
> +    "waait": "1.0.5"
```suggestion
    "react-redux": "8.1.0"
```

2023-06-15 16:24 UTC, balazsorban44 commented on examples/with-redux/src/app/api/identity-count/route.ts
> +  await waait(500)
```suggestion

export async function POST(req: Request, res: Response) {
  const body = await req.json()
  const { amount = 1 } = body

  // simulate IO latency
  await new Promise(r => setTimeout(r, 500))
```

2023-06-15 16:26 UTC, balazsorban44 requested changes, later dismissed
Let's not add barrel files (`index.ts` files that are just re-exports), feels like adding complexity instead of reducing it.

2023-06-15 16:27 UTC, balazsorban44 commented on examples/with-redux/package.json
> +    "classnames": "2.3.2",
```suggestion
```

2023-06-15 16:27 UTC, balazsorban44 commented on examples/with-redux/src/app/components/Nav.tsx
> +import cx from 'classnames'
```suggestion
```

2023-06-15 16:28 UTC, balazsorban44 commented on examples/with-redux/src/app/components/Nav.tsx
> +        className={cx(styles.link, { [styles.active]: pathname === '/' })}
```suggestion
        className={`${styles.link} ${pathname === '/' ? styles.active : ''}`}
```

2023-06-15 16:29 UTC, balazsorban44 commented on examples/with-redux/src/app/components/Nav.tsx
> +        })}
```suggestion
        className={`${styles.link} ${pathname === '/verify' ? styles.active : ''}}
```

2023-06-15 21:16 UTC, dvakatsiienko commented
@balazsorban44 removed `src` folder, and barrel files.

2023-06-16 01:55 UTC, leerob approved these changes

2023-06-16 01:56 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: eec78254223b0c8817f3e588b224afdee56442a3

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-16 01:56 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: eec78254223b0c8817f3e588b224afdee56442a3

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-16 02:00 UTC, merged