Chore: update with-supabase example to App Router
vercel/next.js pull request #51335
Opened 2023-06-15 07:10 UTC by dijonmusters

2023-06-15 15:12 UTC, balazsorban44 requested changes, later dismissed
Thanks, left some small feedback to adhere to https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md

In addition, could you also convert the example to TypeScript? Thanks!

2023-06-15 15:12 UTC, balazsorban44 commented on examples/with-supabase/package.json
> +    "next": "13.4.5",
```suggestion
    "next": "latest",
```

2023-06-15 15:12 UTC, balazsorban44 commented on examples/with-supabase/package.json
> +    "eslint-config-next": "13.4.5",
```suggestion
```

2023-06-15 15:12 UTC, balazsorban44 commented on examples/with-supabase/package.json
> +    "lint": "next lint"
```suggestion
    "start": "next start"
```

2023-06-15 15:12 UTC, balazsorban44 commented on examples/with-supabase/tailwind.config.js
> +    './components/**/*.{js,ts,jsx,tsx,mdx}',
```suggestion
```

2023-06-15 15:14 UTC, balazsorban44 commented on examples/with-supabase/package.json
> +  "version": "0.1.0",
```suggestion
```

2023-06-15 17:11 UTC, viniciusanchieta approved these changes

2023-06-15 22:41 UTC, leerob reviewed
Could we use TypeScript in this example please?

2023-06-16 01:00 UTC, dijonmusters commented
@balazsorban44 and @leerob thanks for the review 🙌 

Example is now TS 👍

2023-06-16 01:44 UTC, leerob commented on examples/with-supabase/tailwind.config.js
> +        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
Is this still needed?

2023-06-16 01:44 UTC, leerob reviewed
Is there a deploy example I can test this out?

2023-06-16 01:50 UTC, dijonmusters commented
> Is there a deploy example I can test this out?

https://with-supabase.vercel.app

2023-06-16 01:52 UTC, dijonmusters commented on examples/with-supabase/tailwind.config.js
> +        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
Good catch! Have removed 👍

2023-06-16 02:16 UTC, leerob approved these changes

2023-06-16 02:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c0389fbd2c1121e340eb25144bfcaa88e9b5a7b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-16 02:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 0c0389fbd2c1121e340eb25144bfcaa88e9b5a7b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-16 13:04 UTC, ijjk approved these changes

2023-06-16 13:05 UTC, ijjk approved these changes

2023-06-16 13:16 UTC, merged