Compile away next/link proptypes in production
vercel/next.js pull request #5155
Opened 2018-09-13 13:51 UTC by timneutkens

This saves 7KB as prop-types-exact is not needed in production.

2018-09-13 19:48 UTC, HaNdTriX approved these changes

2018-09-13 21:32 UTC, HaNdTriX requested changes
~~This fix somehow only works in devmode. In production I get the warning:~~

~~`Error: Cannot find module 'prop-types-exact'`~~

My fault. I forgot to run `yarn` 😬

2018-09-13 21:37 UTC, HaNdTriX approved these changes

2018-09-14 09:28 UTC, Florian-R commented
Just curious, any reason to not use [transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) instead?

2018-09-14 09:33 UTC, timneutkens commented
> Just curious, any reason to not use transform-react-remove-prop-types instead?

We already do, but Next.js doesn't run babel over node_modules, so they're only removed from your own code.

2018-09-14 09:34 UTC, merged

2018-09-14 09:35 UTC, timneutkens commented
@dzienisz what's the reason for 👎?