`docs`: fix generated app icons file extensions
vercel/next.js pull request #51562
Opened 2023-06-20 13:30 UTC by bigyanse

The file extensions of the generated file extensions section are not what it's supposed to be or not what documentation has specified.

2023-06-20 17:01 UTC, delbaoliveira requested changes

2023-06-20 17:01 UTC, delbaoliveira commented on docs/01-getting-started/02-project-structure.mdx
>  | [`icon`](/docs/app/api-reference/file-conventions/metadata/app-icons#icon)                                      | `.png` `.svg`                       | App Icon file            |
```suggestion
| [`icon`](/docs/app/api-reference/file-conventions/metadata/app-icons#icon)                                      |  `.ico` `.jpg`  `.jpeg` `.png` `.svg`                       | App Icon file            |
```

Thanks @bigyanse! It looks like the one above for the static `icon` is missing some files, let's add these. `icon.ico` might look weird, but it's supported :)

2023-06-20 18:40 UTC, leerob approved these changes, later dismissed

2023-06-22 13:19 UTC, delbaoliveira submitted a review, later dismissed

2023-06-23 10:26 UTC, huozhi approved these changes

2023-06-23 10:34 UTC, merged