Export `RedirectType` from `next/navigation`
vercel/next.js pull request #51864
Opened 2023-06-27 08:18 UTC by joshuajaco

This PR adds an export for `RedirectType` to `next/navigation`.
This allows you to import it together with `redirect`, instead of importing from `next/dist/client/components/redirect`

before:

```tsx
import { redirect } from 'next/navigation';
import { RedirectType } from 'next/dist/client/components/redirect';

redirect('/foo', RedirectType.replace);
```

after:

```tsx
import { redirect, RedirectType } from 'next/navigation';

redirect('/foo', RedirectType.replace);
```

2023-06-27 08:20 UTC, feedthejim approved these changes

2023-06-27 08:21 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 411ef7ace0af81c4ad803d3e6efa4cd1c17f5039

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-27 08:21 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 411ef7ace0af81c4ad803d3e6efa4cd1c17f5039

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-07-05 16:03 UTC, joshuajaco commented
Anything left for me to do here? Not sure what happened.

2023-07-06 09:48 UTC, timneutkens requested changes
This PR is missing integration tests.

2023-08-29 19:00 UTC, ztanner commented
Closing as this landed in https://github.com/vercel/next.js/pull/54729

2023-08-29 19:00 UTC, closed without merging