Fix broken request handler
vercel/next.js pull request #51939
Opened 2023-06-28 17:19 UTC by gwer

Hi!

In previous versions (13.4.2 and earlier) in the custom server I could do the following:
```
const parsedUrl = parse(req.url, true);
const { pathname } = parsedUrl;

if (pathname === '/c') {
  await handle(req, res, parse('/b', true));
} else {
  await handle(req, res, parsedUrl);
}
```

Of course, you can replace `handle` with `app.render` in the attached example, but in practice it is convenient to put the definition of `parsedUrl` into middleware and substitute the necessary `parsedUrl` in exceptional situations.

This was broken in #49805.

I'm not sure if this use of request handler is expected, but it has always worked and people have used it (probably due to lack of documentation about the difference between `app.render` and `app.getRequestHandler()`). So the change looks breaking, and I don't think it should appear in minor versions.

2023-06-28 17:20 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 5b54bc8f9ba2e5ed908e2918a565c86da3756e0d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-06-28 17:20 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 5b54bc8f9ba2e5ed908e2918a565c86da3756e0d

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-07-20 16:26 UTC, gwer commented
Kuchiyose no Jutsu!

2023-07-26 12:05 UTC, gwer commented
@timneutkens, @shuding, What do you think?

2023-07-26 13:21 UTC, timneutkens requested changes
Change looks good to me, just missing a test to make sure it doesn't break in the future. Could you add an integration tests for that? Then it's good to land 👍

2023-07-26 18:31 UTC, gwer commented
I've added a test. Please let me know if there is anything else that needs to be changed

2023-07-27 08:12 UTC, timneutkens submitted a review, later dismissed
Thanks, looks good now 💯 Great work!

2023-07-27 08:32 UTC, timneutkens commented
Seems the linting is failing

2023-07-27 10:06 UTC, gwer commented
Linting is ok now. Some checks are still failed, but i'm not sure if is it's my fault.

2023-07-30 07:02 UTC, gwer commented
@timneutkens, I'm sorry to bother you, but let's get this over with before new conflicts arise :-)

2023-08-01 09:08 UTC, timneutkens commented
@gwer I'm still seeing failed tests. Triggered a rerun to make sure it wasn't a flake.

2023-08-01 09:20 UTC, gwer commented
> All checks have passed

^_^

2023-08-01 11:29 UTC, timneutkens approved these changes
Thanks! Great PR 💯

2023-08-01 11:51 UTC, merged