docs: update typescript plugin section for vscode prompt
vercel/next.js pull request #52111
Opened 2023-07-02 22:04 UTC by jenewland1999

Hey Next.js Team, 👋🏻

I noticed Next.js apps scaffolded with create-next-app weren't prompting me for the TypeScript workspace version in VS Code. After digging through the repo, I stumbled on this https://github.com/vercel/next.js/pull/49133 PR from Tim. While this PR explains why it was removed, I'm not sure the docs were ever updated to reflect this change.

This PR aims to address that with a simple note in the TypeScript Plugin section of the TypeScript docs page.

2023-07-06 09:16 UTC, delbaoliveira requested changes
Thank you!

2023-07-06 09:16 UTC, delbaoliveira commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +> Prior to v13.4.0 VS Code would prompt users to set the TypeScript version when running `npm run dev` for the first time. However, this was removed until such time a better solution is implemented.
```suggestion
> Prior to v13.4.0, VS Code would prompt users to enable the plugin when running `npm run dev` for the first time. However, this caused issues for some users and was removed until a better solution is implemented. Please follow the steps above to manually enable the plugin. 
```

I realise "prompt users to set the TypeScript version" is strictly accurate, but the secondary effect is what users need to know here IMO :pray:

2023-07-06 09:16 UTC, delbaoliveira approved these changes, later dismissed

2023-07-09 22:46 UTC, leerob commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +You can enable the plugin in VSCode by:
```suggestion
You can enable the plugin in VS Code by:
```

2023-07-09 22:46 UTC, leerob commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +> Prior to v13.4.0, VS Code would prompt users to enable the plugin when running `npm run dev` for the first time. However, this caused issues for some users and was removed until a better solution i
```suggestion
```

I actually don't think we need to say this at all.

2023-07-09 22:47 UTC, leerob commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +>
```suggestion
```

2023-07-09 22:47 UTC, leerob approved these changes

2023-07-09 23:12 UTC, merged