"Clarify the 'Existing Projects' section of the TypeScript docs:
vercel/next.js pull request #52944
Opened 2023-07-20 14:30 UTC by ShaunFerris

> Add a sentence to the instructions for using typescript in an existing project instructing the user to copy the `paths` compiler option from the existing jsconfig file to the new tsconfig file.
> Not doing so causes absolute imports from project directories to break, and gives "Module Not Found" messages that the docs do not have a case for solving"

2023-07-20 14:44 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 396c2cbaac56377d060b246a096b396afa8d876e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-07-20 14:44 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 396c2cbaac56377d060b246a096b396afa8d876e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-07-20 14:44 UTC, styfle commented on docs/02-app/01-building-your-application/06-configuring/01-typescript.mdx
> +Add TypeScript to your project by renaming a file to `.ts` / `.tsx`. Run `next dev` and `next build` to automatically install the necessary dependencies and add a `tsconfig.json` file with the recomm
```suggestion
Add TypeScript to your project by renaming a file to `.ts` / `.tsx`. Run `next dev` and `next build` to automatically install the necessary dependencies and add a `tsconfig.json` file with the recommended config options. 

If you already had a `jsconfig.json` file, copy the `paths` compiler option from the old `jsconfig.json` into the new `tsconfig.json` file, and delete the old `jsconfig.json` file.
```

2023-07-20 19:53 UTC, styfle approved these changes

2023-07-20 21:36 UTC, styfle requested changes
Please fix the lint error

2023-07-21 07:12 UTC, ShaunFerris commented
> Please fix the lint error

Hi, sorry, I am relatively new to this and am not sure what is causing the lint error or how to fix it. Please advise when you get a chance.

2023-07-21 08:55 UTC, ShaunFerris commented
> Please fix the lint error

Hi,
I have run the linting script this time so hopefully the check will not fail. It may be worth linking to the contributing documentation from the Docs Contribution Guide, as there is currently no mention of getting the dev environment setup or running the lint script there.

2023-07-21 12:08 UTC, styfle approved these changes
Thanks!

2023-07-21 12:53 UTC, ShaunFerris commented
If any maintainer could offer advice on why these checks might be failing I would appreciate it. I apologize if I'm missing something obvious, Cheers!

2023-07-21 13:16 UTC, styfle commented
GitHub is having an outage https://www.githubstatus.com/incidents/6503rcn8s34s

2023-07-21 14:30 UTC, styfle commented
The "Validate Docs" was broken in a previous PR. 

I think the check is actually wrong because the link looks correct. cc @delbaoliveira

2023-07-21 14:48 UTC, styfle commented
> It may be worth linking to the contributing documentation from the Docs Contribution Guide, as there is currently no mention of getting the dev environment setup or running the lint script there.

It would be great if you could submit another PR to improve that guide now that you have gone through the process and know what's missing. Thanks!

2023-07-21 15:07 UTC, ShaunFerris commented
> > It may be worth linking to the contributing documentation from the Docs Contribution Guide, as there is currently no mention of getting the dev environment setup or running the lint script there.
> 
> Thanks for pointing that out!c It would be great if you could submit another PR to improve that guide now that you have gone through the process and know what's missing. Thanks!

Cool I was thinking that I would do that, but just to clarify while I have you here, do you think the line "To contribute, you can edit the files directly on GitHub or clone the repo and edit the files locally." should be changed to remove the option of editing directly on github, as you cant run the linter from githubs editor? (Unless I am missing something).

Cheers for the feedback, I am keen to continue contributing!

2023-07-21 15:09 UTC, merged

2023-07-21 15:27 UTC, styfle commented
> as you cant run the linter from github

Maybe that's the real problem. I bet there is a way to automatically run lint in an action and commit the result.

2023-07-21 17:59 UTC, styfle commented
I checked the PR template and I see that it does mention prettier fix here: https://github.com/vercel/next.js/blob/e048f4ef037d7eaff765adb2867d219a43a333d9/.github/pull_request_template.md#L9