chore(docs): replace getStaticProps with static rendering in app deploy documentation
vercel/next.js pull request #53039
Opened 2023-07-22 11:14 UTC by AntoineBourin

### What?

- Deploy documentation in `App router` is talking about `getStaticProps` function. As this function doesn't exist anymore in this router version, we can replace it with the Static Rendering link.

### Why?

- `getStaticProps` function doesn't exist in the `App Router` context.

### How?

- See doc : `getStaticProps` replaced by link to Static Rendering documentation to let users see how to build static pages.

2023-07-22 11:16 UTC, AntoineBourin commented
Maybe we can include `using generateStaticParams for dynamic segments` ?

2023-07-22 11:16 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 082fecdae545e4774a7b92997d71c843f62144ba

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-07-24 17:04 UTC, styfle requested changes
The comment at the top indicates this document is shared:

> The content of this doc is shared between the app and pages router. You can use the `<PagesOnly>Content</PagesOnly>` component to add content that is specific to the Pages Router. Any shared content should not be wrapped in a component.

So we need two different links: one with `<PagesOnly>Content</PagesOnly>` and one with `<AppOnly>Content</AppOnly>`

2023-07-24 17:39 UTC, AntoineBourin commented
@styfle Thanks ! Did not see the comment ! 
Documentation updated.

2023-07-25 00:15 UTC, styfle submitted a review, later dismissed
I'm not sure if this will work since its splitting up the `<li>` instead of wrapping the `<ul>`.

We can try it and revert if it causes a problem.

2023-07-27 10:06 UTC, timneutkens approved these changes, later dismissed
Looks good! Thanks!

2023-07-27 10:10 UTC, timneutkens requested changes
Seems like the linting messes up the formatting here. Could you have a look at that?

2023-08-24 01:01 UTC, leerob commented on docs/02-app/01-building-your-application/07-deploying/index.mdx
> -- HTML files for pages using `getStaticProps` or [Automatic Static Optimization](/docs/pages/building-your-application/rendering/automatic-static-optimization)
I'd say let's just make this more generic for both:

- HTML files for static pages

2023-09-02 23:52 UTC, leerob commented
Closing as stale from https://github.com/vercel/next.js/pull/53039#discussion_r1303677101, but open to a new PR 🙏

2023-09-02 23:52 UTC, closed without merging