Clarify requirements for running examples
vercel/next.js pull request #53143
Opened 2023-07-25 04:25 UTC by mayank1513

- to avoid #53037 kind of issues.

2023-07-25 22:45 UTC, balazsorban44 requested changes

2023-07-25 22:45 UTC, balazsorban44 commented on contributing/examples/run-example-apps.md
> +> Before you can run the example, you need to install all the dependencies with `pnpm i` and build the `next.js` by running `yarn build` or `pnpm run build` in the root directory.
```suggestion
> Before running any of the examples, you need to install dependencies via `pnpm install` and build the repository packages by running `pnpm build` in the root directory.
```

2023-07-25 22:46 UTC, balazsorban44 approved these changes

2023-07-27 08:33 UTC, timneutkens approved these changes

2023-07-29 05:59 UTC, ijjk approved these changes

2023-07-29 05:59 UTC, merged