feature: Adding ESLint rule to prevent usage document or other browser APIs outside of useEffect
vercel/next.js pull request #53431
Opened 2023-08-01 10:21 UTC by aacevski

### Related issues
https://github.com/vercel/next.js/issues/27051

### What?
I have created a new eslint rule which will check if the developer is using the browser API in a server component.

### Why?
The reason for doing this is to prevent the developer to cause a potential crash in his server component when using any of the browser API outside of a `useEffect`.

This also takes into consideration client components, where I explicitly check for the `use client` keyword, in that case it is allowed to use the browser API since we have access to that API in a client component.

### How?

Firstly, I check if there is `use client` in the file content, if so, the rule is ignored since it is a client component.

Secondly, I have a while loop which finds the top most parent function / arrow function and check if it's a React component.

Last but not least, I check if the current identifier is part of the browser API's array, if so, it should show an error.

2023-08-01 15:28 UTC, Sanjay-shankar approved these changes
Good to go

2023-08-04 13:43 UTC, Dragate requested changes
I believe Promise API (including fetch) should not disallowed in a server component.

2023-08-04 13:43 UTC, Dragate commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'fetch',
```suggestion

```

2023-08-07 13:14 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'navigator.geolocation',
```suggestion
```
You have already `navigator` at line 12

2023-08-07 13:15 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'history',
```suggestion
```
Duplicate at line 14

2023-08-07 13:15 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'navigator.serviceWorker',
```suggestion
```

2023-08-07 13:15 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'navigator.clipboard',
```suggestion
```

2023-08-07 13:16 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +  'navigator.mediaDevices.getUserMedia',
```suggestion 
```

2023-08-07 13:19 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +    const isClientSideComponent = text.includes('use client')
```suggestion
```
This check is redundant since you already check comments

2023-08-07 13:20 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +    const isUseClientCommented = allComments.some((comment) =>
```suggestion
    const hasUseClientComment = allComments.some((comment) =>
```

2023-08-07 13:21 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +          browserAPIs.includes(node.name) &&
```suggestion
          browserAPIs.includes(node.name) &&
```
This check can be moved before `parentFunction` assignment

2023-08-07 13:22 UTC, B2o5T commented on packages/eslint-plugin-next/src/rules/no-browser-api-server-component.ts
> +const browserAPIs = [
```suggestion
const browserAPIs = new Set([
```
Using `Set` is better for performance

2023-09-24 15:04 UTC, leerob commented
Could you address the open PR comments, please? 🙏

2024-04-25 16:38 UTC, closed without merging