feat(examples): Migrate 'with-mongoose' example to TypeScript with total type safety
vercel/next.js pull request #53603
Opened 2023-08-05 08:49 UTC by Thenextgen1

### What?
I kindly request the maintainers to review this Pull Request, which aims to migrate the `with-mongoose` example to TypeScript with total type safety.

### Why?
By doing so, we enhance the overall quality and maintainability of the example, aligning it with modern best practices for type-safe codebases.

### How?
I have thoroughly tested the changes to ensure they do not introduce regressions and maintain compatibility with the existing codebase.

2023-08-07 10:33 UTC, balazsorban44 commented on examples/with-mongodb-mongoose/pages/[id]/edit.tsx
> +  console.log(id)
```suggestion
```

2023-08-07 10:33 UTC, balazsorban44 approved these changes

2023-08-07 10:42 UTC, balazsorban44 requested changes
Could you make sure linting passes? You can run: `pnpm prettier --write examples/with-mongodb-mongoose` and commit the result.

2023-08-07 15:17 UTC, Thenextgen1 commented
> Could you make sure linting passes? You can run: `pnpm prettier --write examples/with-mongodb-mongoose` and commit the result.

I have done that

2023-08-07 15:19 UTC, Thenextgen1 commented
> Could you make sure linting passes? You can run: `pnpm prettier --write examples/with-mongodb-mongoose` and commit the result.

Sure, I have done that

2023-08-07 18:28 UTC, styfle commented on examples/with-mongodb-mongoose/models/Pet.ts
> +export interface IPet extends mongoose.Document {
> Do **NOT** use `I` as a prefix for interface names.

https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names

2023-08-07 18:30 UTC, styfle commented on examples/with-mongodb-mongoose/models/Pet.ts
> +export interface IPet extends mongoose.Document {
Instead you could do `typeof Pet` to get the type, right?

2023-08-09 10:42 UTC, B2o5T commented on examples/with-mongodb-mongoose/pages/[id]/index.tsx
> +  serializedPet._id = (serializedPet._id as ObjectId).toString()
This is not needed since you already stringify and parse object ?

2023-08-09 10:44 UTC, B2o5T commented on examples/with-mongodb-mongoose/pages/index.tsx
> +  return { props: { pets: pets } }
```suggestion
  return { props: { pets } }
```

2023-08-09 10:46 UTC, B2o5T commented on examples/with-mongodb-mongoose/components/Form.tsx
> +    console.log(errs)
```suggestion
```

2023-08-31 15:54 UTC, balazsorban44 approved these changes

2023-09-01 14:34 UTC, merged