fix(debugger): accept arbitrary ip an port as NODE_OPTIONS
vercel/next.js pull request #53683
Opened 2023-08-07 15:09 UTC by HelmerBarcos

What?
This enables debugging sessions from a remote host. This is helpful while debugging a Next.js application that runs inside a Docker container.

This fixes:
- https://github.com/vercel/next.js/issues/53127
- https://github.com/vercel/next.js/issues/47083

Why?
It was an attempt to fix the bug, but it didn't work.

2023-08-09 21:16 UTC, vleeuwenmenno commented
Is there a version we can use that does not have the bug that is fixed in this PR?
This PR needs priority ...

2023-08-21 15:20 UTC, timmywil commented
Agreed, would be great to prioritize this issue and get a fix in 13.4.20.

2023-08-31 16:00 UTC, wyattjoh requested changes

2023-10-17 10:57 UTC, mkoreo commented
> Is there a version we can use that does not have the bug that is fixed in this PR? This PR needs priority ...

Indeed, this issue has been going on for 7-8 months now in which it is completely impossible to debug next.js in a docker container. Is it possible to give the review of these 10 lines of code priority?

2023-10-17 11:05 UTC, timneutkens commented
The PR was already reviewed but the comments were not addressed yet, so this can't be landed as-is. Feel free to open a new PR based on this one to fix that, happy to land it when the comments are addressed.

2023-10-23 16:27 UTC, HelmerBarcos commented on test/integration/cli/test/index.test.js
> +
Thanks. I just did the changes

2023-10-23 16:49 UTC, HelmerBarcos commented
@timneutkens  @wyattjoh  How I said I had a lot of work to do. But now the MR should be ready to merge

2023-11-07 10:50 UTC, gaac510 commented
> Is there a version we can use that does not have the bug that is fixed in this PR?

Hope it's OK to ask this question again, since this PR appears to be held up again.

2023-11-09 11:51 UTC, HelmerBarcos commented
Any updates for this MRs?

2023-11-12 09:25 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c2473a2ddaab1ca7b9c707d00dd1050323e7c1d8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-11-12 09:25 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c2473a2ddaab1ca7b9c707d00dd1050323e7c1d8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-11-14 13:29 UTC, simonstatonbynd commented
Any update on this? Currently there is no way to debug a NextJS application in a docker container. This has been going on for quite some time...

2023-11-14 13:37 UTC, simonstaton commented
Any update on this? Currently it's impossible to debug a NextJS application running in a docker container.

For anyone facing the same issue, there is a temporary workaround to define the inspect argument twice initially with only the port `--inspect=9229 --inspect=0.0.0.0`

2023-11-14 13:39 UTC, simonstaton approved these changes

2023-11-20 15:43 UTC, HelmerBarcos commented
Should I do anything? I don't see any approvals or changes requested after 1 month.

2023-12-02 10:10 UTC, mkoreo commented
@timneutkens Hey, could you have another look at this PR? I believe @HelmerBarcos has addressed the remarks.

2023-12-21 18:04 UTC, HelmerBarcos commented on test/integration/cli/test/index.test.js
> +
@wyattjoh, do I need to do anything else? This MR could be beneficial for many developers who prefer not to debug using console logs.

2024-01-20 13:44 UTC, HelmerBarcos commented
Im closing this. PR and opening a new one.

2024-01-20 13:44 UTC, closed without merging