fix: removed lucide aliases
vercel/next.js pull request #53789
Opened 2023-08-09 10:12 UTC by jguddas

#53483 introduced support for lucide aliases in next.js, to not have to maintain this mapping in two places lucide will have a file for every alias.

https://github.com/lucide-icons/lucide/pull/1486

2023-08-13 20:18 UTC, jguddas commented on packages/next/src/server/config.ts
> -          'modularize-import-loader?name={{ member }}&from=default&as=default&join=../esm/icons/sparkles!lucide-react',
Now there is a `/esm/icons/sparkles.js` file containining a simple reexport from `sparkles`.

```js
/**
 * lucide-react v0.267.0 - ISC
 */

export { default } from './sparkles.js';
//# sourceMappingURL=stars.js.map
```

https://www.npmjs.com/package/lucide-react?activeTab=code

2023-08-20 02:25 UTC, jd-carroll commented
@ztanner we are really excited to use #54016 but will not be able to use the latest due to this issue.  Any chance we can get this PR merged soon?

2023-08-22 16:10 UTC, shuding requested changes
Can we fix the wrong transform rule instead of removing all of them? This breaks the optimization for older versions of Lucide React.

2023-08-22 17:17 UTC, jguddas commented
> This breaks the optimization for older versions of Lucide React.

@shuding old versions of lucide are already broken, since they use `./icons` rather than `../esm/icons`.

There are only very view versions that have both `../esm/icons` but don't have the aliases i.e. `../esm/icons/stars.js` that @ericfennis and I added so we don't have to maintain them in both places.

Keeping those aliases here will break as soon as we add a `starts` icon to lucide for example.

If there are 250 or 253 prerelease versions of lucide that don't work is IMO okay considering this problem.

2023-08-25 20:29 UTC, closed without merging