style: standardize number of quotation marks
vercel/next.js pull request #54409
Opened 2023-08-22 22:45 UTC by hamirmahal

fixes #54402.

2023-08-22 22:47 UTC, hamirmahal commented on packages/create-next-app/templates/app-tw/ts/.prettierrc.json
> +}
```suggestion
// Feel free to delete or ignore this file if you're not using `prettier`.
{
  "singleQuote": false
}
```
I wanted to add a comment like this but I think `.json` files don't allow comments.

2023-08-22 22:48 UTC, hamirmahal commented on packages/create-next-app/templates/app-tw/ts/.prettierrc.json
> +}
```suggestion
// Feel free to delete or ignore this file if you're not using `prettier`.
{
  "singleQuote": false
}
```
I wanted to add a comment like this, but `.json` files don't allow comments.

2023-10-03 16:04 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 242881e2a4a036756411c5b14096d23b80b697f4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-10-03 17:37 UTC, hamirmahal commented
oh, gosh

2023-10-10 19:50 UTC, styfle requested changes
I'm not sure this is appropriate to add since the templates don't ship with `prettier` installed.

Also, if it was added to this template, it should be added to all templates.

2023-10-10 22:32 UTC, hamirmahal commented
> Also, if it was added to this template, it should be added to all templates.

Ah, I agree. I addressed this just now.

2023-10-11 13:33 UTC, styfle commented
> I wanted to add this change because I noticed fresh Next.js apps would have changes from formatting on save

Presumably if you added prettier as a dependency then you would also add the prettierrc file to configure as you wish.

2023-10-11 19:38 UTC, hamirmahal commented
Hmm... do you think it makes more sense to ship `prettier` with Next.js?

2023-10-11 19:38 UTC, hamirmahal commented
I was going for the smallest possible change that solves the original problem I was facing, which is that a fresh clone of Next.js will have changes just from doing Ctrl + S on a file, due to [Next.js templates not shipping with `prettier` defaults](https://github.com/vercel/next.js/blob/c8b2d1b44a9f9376eee7bc6c26e84bd7f5c03354/.prettierrc.json),

2023-10-11 19:41 UTC, styfle commented
> Next.js will have changes just from doing Ctrl + S on a file,

Thats only if you have the prettier extension installed, right?

It would format differently if you used a different formatter on save.

2023-10-11 19:48 UTC, hamirmahal commented
> Thats only if you have the prettier extension installed, right?

That's correct, yes.

2023-10-11 19:48 UTC, hamirmahal commented
And it'll only happen if someone's using `prettier` with the default settings, unless we add the `.prettierrc` files from this pull request, in which case it won't happen at all.

2023-10-12 14:42 UTC, balazsorban44 requested changes
Using overrides:
https://prettier.io/docs/en/configuration.html#configuration-overrides

I suggest we just override `packages/create-next-app/templates` to the defaults here: https://github.com/vercel/next.js/blob/canary/.prettierrc.json

2023-10-12 22:15 UTC, hamirmahal commented
Are you saying to override `packages/create-next-app/templates/` so they conform to `prettier`'s default formatting?

2023-10-12 22:15 UTC, hamirmahal commented
That'll be a much larger `diff` for this pull request, since we'd have to modify all the template files to match `prettier`'s default formatting, since the templates files all seem to currently conform to [`.prettierrc.json`](https://github.com/vercel/next.js/blob/canary/.prettierrc.json).

2023-11-19 20:50 UTC, hamirmahal commented
Just bumping this again since I had to add

```
{
  "singleQuote": true,
  "semi": false
}
```

to a `.prettierrc.json` file in a new Next app to prevent any formatting changes when saving `app/page.tsx`

2023-11-19 20:54 UTC, hamirmahal commented
> Using overrides: https://prettier.io/docs/en/configuration.html#configuration-overrides
> 
> I suggest we just override `packages/create-next-app/templates` to the defaults here: https://github.com/vercel/next.js/blob/canary/.prettierrc.json

I think that's what the files in this pull request are doing; please correct me if I'm mistaken.

2023-11-19 21:17 UTC, kachkaev commented
👋 folks! WDYT of doing the opposite: formatting templates with default Prettier config? That would mean double quotes and semicolons. Quotes are a hot topic – https://github.com/prettier/prettier/issues/4102 (I am personally [in favour of double quotes](https://github.com/prettier/prettier/issues/4102#issuecomment-383016258)). The case for semicolons [is pretty straightforward](https://webreflection.medium.com/an-open-letter-to-javascript-leaders-regarding-no-semicolons-82cec422d67d): they simplify the life of newcomers and avoid confusion in a few edge cases. 

Next.js repo has its own history, so it’s fine to keep the existing preferences as is. But the templates is what a lot of folks interact with, so it’s best to keep the formatted using Prettier defaults.

2024-01-04 14:35 UTC, styfle commented
> WDYT of doing the opposite, i.e. formatting templates with the default Prettier config

Thats probably a better idea because then we don't need the config.

However, are the default settings the same for prettier/dprint/biome/etc?

2024-01-04 23:59 UTC, hamirmahal commented
> > WDYT of doing the opposite, i.e. formatting templates with the default Prettier config
> 
> Thats probably a better idea because then we don't need the config.

The pull request now uses the default `prettier` config.

2024-01-04 23:59 UTC, hamirmahal commented
> > WDYT of doing the opposite, i.e. formatting templates with the default Prettier config
> 
> Thats probably a better idea because then we don't need the config.

This pull request now uses the default `prettier` config.

2024-01-07 04:01 UTC, JounQin commented
> Thats probably a better idea because then we don't need the config.

> However, are the default settings the same for prettier/dprint/biome/etc?

That's a good point, and prettier was born earlier, so I believe other formatting tools should adapt prettier's defaults, instead of reversing.

2024-01-11 23:01 UTC, closed without merging