Moved nanoid use from next-server to next/build
vercel/next.js pull request #5441
Opened 2018-10-12 16:02 UTC by slaskis

Another (more proper?) solution to #5427

Is this what you had in mind @timneutkens ?

2018-10-12 16:04 UTC, slaskis commented on packages/next/build/index.js
> +  if (buildId == null) {
`==` is intentional here to catch `null` or `undefined` (either would mess up any potential string methods)

or would you prefer to make this more explicit like `typeof buildId == "string"`?

2018-11-02 18:51 UTC, timneutkens requested changes
Could just be me, but shouldn't there be a package.json update too?

2018-11-02 20:12 UTC, slaskis commented
I don't think so. The reason for #5427 was to move nanoid to server but this PR just leaves it where it was.

2018-11-02 22:19 UTC, timneutkens commented
Ah I see 👍

2018-11-02 22:19 UTC, merged

2018-11-02 22:19 UTC, timneutkens commented
Thanks!