Update revalidatePath.mdx
vercel/next.js pull request #54631
Opened 2023-08-27 14:29 UTC by krychaxp

add if statement, because typescript throws error: revalidatePath require `string`, but `searchParams.get('path')` returns `string|null` type

2023-08-27 14:29 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: e286b806841961c084d2e25955f6aaec6abf53c2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-08-28 13:34 UTC, leerob commented on docs/02-app/02-api-reference/04-functions/revalidatePath.mdx
> +    message: "Missing 'path'",
```suggestion
    message: 'Missing path to revalidate',
```

2023-08-28 13:34 UTC, leerob requested changes, later dismissed
Could you add these changes the JS codeblock below as well?

2023-08-28 18:37 UTC, krychaxp commented
> Could you add these changes the JS codeblock below as well?

added :D

2023-08-28 20:33 UTC, ijjk approved these changes

2023-08-28 20:33 UTC, merged