(Examples) update Grafbase example
vercel/next.js pull request #54705
Opened 2023-08-29 08:17 UTC by vinaykulk621

2023-08-29 08:17 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: fa13b37c7fe900148970ea53475aad9a7f4b5dc2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-08-30 11:06 UTC, balazsorban44 requested changes
Thanks, remember to run `pnpm lint` when updating an example

2023-08-30 11:06 UTC, balazsorban44 commented on examples/with-grafbase/app/layout.tsx
> +import type { Metadata } from "next";
```suggestion
import type { Metadata } from "next"
```

2023-08-30 11:06 UTC, balazsorban44 commented on examples/with-grafbase/app/layout.tsx
> +};
```suggestion
}
```

2023-08-30 11:06 UTC, balazsorban44 commented on examples/with-grafbase/app/layout.tsx
> +  );
```suggestion
  )
```

2023-09-04 14:02 UTC, vinaykulk621 commented
@balazsorban44  Any updates on this??

2023-09-04 14:05 UTC, balazsorban44 submitted a review, later dismissed

2023-09-04 14:05 UTC, balazsorban44 commented
Thanks, note that you don't need to keep merging `canary`, it won't result in a faster merge. :+1:

2023-09-26 02:52 UTC, leerob approved these changes, later dismissed

2023-09-26 02:56 UTC, leerob commented
Linting is failing here, FYI

2023-09-26 13:10 UTC, vinaykulk621 commented
@leerob Fixed linting errors

2023-09-26 14:59 UTC, leerob approved these changes

2023-09-26 15:00 UTC, leerob submitted a review, later dismissed

2023-09-26 17:11 UTC, vinaykulk621 commented
@leerob this time i fixed it believe me, please!!

2023-09-26 19:22 UTC, leerob approved these changes, later dismissed

2023-09-27 03:11 UTC, leerob approved these changes, later dismissed

2023-09-27 03:25 UTC, leerob commented
Did you fix the Prettier errors? It's still failing. Are you validating locally? 🙏

2023-09-27 04:43 UTC, vinaykulk621 commented
I am validating in github codespace here is the video on how i am trying to do


Nothing seems to change here tho 

https://github.com/vercel/next.js/assets/94120295/52de6341-8d71-44fe-a2e8-9ff327751147




i tried running `pnpm lint` at the root directory but it's not working either 


![image](https://github.com/vercel/next.js/assets/94120295/c69ae335-b006-4588-ada8-bdf083e601aa)

I tried to changing the `pnpm` version but it does not seem to work here.
It goes back to `8.6.1` even though i run `pnpm i -g pnpm@8.7.1`

 
i thought i should run it in the example directory where i am making changes but the example do not include lint script in `package.json`. 

You could say i really have no idea where i should run `pnpm lint`.
Here in [linting.md](https://github.com/vercel/next.js/blob/canary/contributing/repository/linting.md#linting) it is not specfied where i should i run this command when i update an examples.

Please help🙏🏻.

2023-09-27 13:50 UTC, manovotny commented
@vinaykulk621 run `corepack enable pnpm` to get the pnpm versions in sync. Then, run `pnpm prettier-fix` from the root of the project and commit the changes.

2023-09-30 15:06 UTC, leerob approved these changes

2023-09-30 15:08 UTC, merged