fix redirect bug in example
vercel/next.js pull request #54914
Opened 2023-09-02 06:48 UTC by DanielBiegler

`pathname` already includes a slash which results in a bad redirect

2023-09-02 16:31 UTC, leerob reviewed
https://github.com/vercel/next.js/blob/canary/examples/app-dir-i18n-routing/middleware.ts#L54

2023-09-04 14:08 UTC, balazsorban44 approved these changes

2023-09-04 15:40 UTC, leerob requested changes
Please see my comment above :pray:

2023-09-04 15:41 UTC, leerob requested changes
Please see my comment above :pray:

2023-09-05 07:34 UTC, DanielBiegler commented on docs/02-app/01-building-your-application/01-routing/13-internationalization.mdx
> +      new URL(`/${locale}${pathname}`, request.url)
@leerob you want to change this into the following?:

```suggestion
      new URL(`/${locale}${pathname.startsWith('/') ? '' : '/'}${pathname}`, request.url)
```

2023-10-09 10:49 UTC, DanielBiegler commented
![image](https://github.com/vercel/next.js/assets/14810858/50df430d-008b-4976-8c9d-76cfc3381e4f)

2023-10-09 10:49 UTC, closed without merging