Add alinea to server-external-packages.json
vercel/next.js pull request #55006
Opened 2023-09-05 10:43 UTC by benmerckx

### What?

Adds `@alinea/generated` to the external package list

### Why?

The next major version of [`alinea`](https://github.com/alineacms/alinea) will generate this package at build time which should not end up in a cache (much like the `@prisma/client` package)

2023-09-05 10:43 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 284b8a0be4fb82534a018b63a8ff4b3b346490f0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-09-05 10:43 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 284b8a0be4fb82534a018b63a8ff4b3b346490f0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-09-03 18:36 UTC, ijjk requested changes
Hi, this doesn't appear to be a valid package https://www.npmjs.com/package/@alinea/generated

2025-11-27 10:34 UTC, timneutkens approved these changes
Checked further and this package is generated by the CMS library, you will likely want to claim it on npm as well though to make that clearer. It's under the scope that you own so at least it can't be taken by anyone else.

2025-11-27 16:28 UTC, merged