Allow dynamic i18n output for public directory
vercel/next.js pull request #55137
Opened 2023-09-08 10:17 UTC by pekarja5

Changes in #52492 made `public` folder accessible only on default domain if using i18n. This PR allows access to public directory contents from all i18n domains as the original solution did. 

Fixes #54765

2023-09-08 10:17 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: acf43f4d59a2ba93c80fe8b96874b0fe8a7e4814

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-09-08 10:17 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: acf43f4d59a2ba93c80fe8b96874b0fe8a7e4814

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-09-15 08:29 UTC, mayank1513 approved these changes

2023-09-20 07:15 UTC, bobbonius commented
Hi there! My colleague created the issue you're referencing and I was wondering if I could be of any assistance to get this through? We want to go to next 13 but this issue is holding us back at the moment.

2023-09-20 08:24 UTC, pekarja5 commented
@bobbonius There is nothing to do apart from waiting for it to get merged. The fix is really simple as it is just one line edit.  It is already approved so i hope it will get merged and released soon.

2023-09-22 11:13 UTC, bobbonius commented
> There is nothing to do apart from waiting for it to get merged. The fix is really simple as it is just one line edit. It is already approved so i hope it will get merged and released soon.

Thanks!

2023-09-29 09:14 UTC, aledovskikh commented
Hey! When it'll be released? Looks like this is some kind of critical bug

2023-10-03 10:05 UTC, chrisneven approved these changes

2023-10-03 10:32 UTC, chrisneven commented
This is blocking us as well at the moment. It would be really nice if we could get this one true!

2023-10-03 10:41 UTC, chrisneven commented
@ijjk, maybe you can take a look at this? Since you made the change initially

Thanks in advance!

2023-10-14 10:34 UTC, timneutkens requested changes
This PR is missing tests, please have a look at and follow the PR template to ensure the changes can be reviewed correctly.

2023-10-18 09:00 UTC, pekarja5 commented
@timneutkens Does the test suite even supports testing access to multiple domains? I could not find any test with such functionality.

The goal is to make the test access files in `public` directory from multiple defined locale domains. If anyone has any tips how to make such test feel free to give me some ideas.

2023-10-30 12:49 UTC, aledovskikh commented
Is there any chance to fix and merge it to nearest release? 
We can't upgrade NextJS upper than 13.4.7, because of this bug

2023-11-09 19:52 UTC, glenngijsberts commented
@pekarja5  could you please update the description of this PR? 

@timneutkens sorry for tagging again, but any chance you can give some guidance on how to test this (personally I don't know)?

2023-11-10 09:31 UTC, pekarja5 commented
@glenngijsberts Some changes in particular?

2023-11-13 10:28 UTC, glenngijsberts commented
@pekarja5 like Tim said, follow the PR template please. You can start creating a PR (without actually creating it) to see what the template is.

2024-01-09 12:37 UTC, persocon commented
lol, just upgraded my nextjs version to 14 and now i'm having this exact problem, when will this PR be updated and merged? 🙏

2024-01-17 01:34 UTC, ijjk requested changes
Hi, this would match all locales and not jut the locale domains/default locale. Continuing fix/tests in https://github.com/vercel/next.js/pull/60749

2024-01-17 21:41 UTC, closed without merging