Fixed HOSTNAME env variable in Dockerfile
vercel/next.js pull request #55450
Opened 2023-09-15 17:50 UTC by DragosMocrii

### What?
Changed the HOSTNAME env variable in Dockerfile for each environment from `localhost` to `0.0.0.0`

### Why?
Using `localhost` as the hostname running the node server will not make the server accessible outside of the container. Using `0.0.0.0` ensure the server is accessible. (Read more: https://serverfault.com/a/1084918)

2023-09-16 11:00 UTC, DuCanhGH commented
The default for `.next/standalone/server.js` is now `0.0.0.0`, so you may as well delete `ENV HOSTNAME` altogether.

2023-09-16 17:11 UTC, DragosMocrii commented
> The default for `.next/standalone/server.js` is now `0.0.0.0`, so you may as well delete `ENV HOSTNAME` altogether.

You are right in that the default hostname value for the standalone server is 0.0.0.0, however the current value used in the dockerfile is incorrect, so for one using this example the server will fail to be accessible from the outside of the container.

2023-09-17 00:28 UTC, DuCanhGH commented
@DragosMocrii well I mentioned deleting that value, right? Sometimes the deployment platform just provides `HOSTNAME` for you (otherwise the default value `0.0.0.0` should just work), and you'd only need to have `ENV HOSTNAME 0.0.0.0` if that value isn't actually meant to be a hostname. Though, maybe adding a comment like this would be nice:
```
# Uncomment the following line if `process.env.HOSTNAME` is not provided by your provider
# or it is an invalid value for a hostname.
# ENV HOSTNAME 0.0.0.0
```
This is just my suggestion though, feel free to do it how you want :) It'd be nice if you could change this for other Docker examples as well (they should be close to this example).

2023-09-19 12:31 UTC, leerob requested changes
Hostname is not needed. It can be removed entirely. Could you update this please?

2023-09-19 15:56 UTC, DragosMocrii commented
@DuCanhGH sorry, I missed your initial point. I've made the updates per your suggestion.

@leerob updated

2023-09-26 02:44 UTC, leerob commented on examples/with-docker/Dockerfile
> +# Uncomment the following line if you'd like to change the default value
Let's just remove it entirely, no commented out block. Thank you!

2023-09-26 02:47 UTC, leerob commented
Closing as dupe of https://github.com/vercel/next.js/pull/55239.

2023-09-26 02:47 UTC, closed without merging