docs: Add alternative installation method using bun
vercel/next.js pull request #55909
Opened 2023-09-24 15:32 UTC by Mutesa-Cedric

as many developers are moving to bun, its a good idea that it also be included as an installation method.

2023-09-25 16:05 UTC, styfle requested changes
We already updated the `create-next-app` docs so lets link there instead

https://nextjs.org/docs/app/api-reference/create-next-app

2023-09-25 16:06 UTC, styfle commented on docs/01-getting-started/01-installation.mdx
>  We recommend starting a new Next.js app using `create-next-app`, which sets up everything automatically for you. To create a project, run:
```suggestion
We recommend starting a new Next.js app using [`create-next-app`](/docs/app/api-reference/create-next-app), which sets up everything automatically for you. To create a project, run:
```

2023-09-25 16:06 UTC, styfle commented on docs/01-getting-started/01-installation.mdx
> +
```suggestion
```

2023-09-25 16:07 UTC, styfle submitted a review, later dismissed

2023-09-26 02:40 UTC, leerob commented on docs/01-getting-started/01-installation.mdx
> +.
This needs to be removed

2023-09-26 10:00 UTC, balazsorban44 approved these changes

2023-09-26 10:01 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f5e0822006b2cad04c40e2b3674c63cf22980029

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-09-26 10:01 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f5e0822006b2cad04c40e2b3674c63cf22980029

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-09-26 15:28 UTC, merged