chore(pnpm): allow pnpm versions above 8.7.1 in engines field
vercel/next.js pull request #56476
Opened 2023-10-05 11:00 UTC by Willem-Jaap

The PNPM version in the package.json's engines field is limited to `8.7.1`, previously changed in [#54873](https://github.com/vercel/next.js/pull/54873/files).

This PR allows versions above 8.7.1 to be used too.
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

It's quite limiting to only allow one specific (patch) version of pnpm.

For developers using [corepack](https://pnpm.io/installation#using-corepack) the `packageManager` field will be used still.

2023-10-05 11:00 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: a6e8922ea31acdb821ac066b4ec6ad04e54446ab

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-10-05 11:21 UTC, timneutkens requested changes
This is intentional as it's for the Next.js internals, not for users of Next.js. Using a different version of the package manager will result in a different lockfile output.

2023-10-05 12:44 UTC, Willem-Jaap commented
I'm aware that this is for development of the Next.js internals, however there is no direct reference to a pnpm version other than the [lockfileVersion](https://github.com/vercel/next.js/blob/524b31513a58e58e15862ac8aa3f27da8a47a267/pnpm-lock.yaml#L1C23-L1C23)

I'm using pnpm version 8.8.0 which does not make any changes to the lockfile when installing.
Maybe we could specify a version range like: `"pnpm": ">=8.7.0 <8.9.0"`

If this creates the possibility for expected or unstable behaviour feel free to close this PR

2023-10-06 09:39 UTC, frans-slabbekoorn approved these changes
lgtm!

2023-10-06 12:26 UTC, styfle commented
This is intended. It’s not just about the lockfile, it’s about any changes. Maybe we could allow semver patch but not semver minor because that means there are new features. We have thousands of contributors to Next.js so we can’t debug every version of pnpm to confirm if it works so it’s best to lock the version down to ensure everyone has the same experience contributing to Next.js. 

I’m going to close this PR and I think we need to update pnpm soon. Perhaps we could have a bot do this periodically.

2023-10-06 12:26 UTC, closed without merging