Add .yarn/install-state.gz to .gitignore
vercel/next.js pull request #56637
Opened 2023-10-10 05:51 UTC by leung018

### Reason for making this change
https://yarnpkg.com/getting-started/qa#:~:text=yarn%2Finstall%2Dstate.,your%20workspaces%20all%20over%20again.
In the official documentation of `yarn`, it is stated that `.yarn/install-state.gz` is an optimization file that developer shouldn't ever have to commit. However, currently, when running `create-next-app`, `.yarn/install-state.gz` is being commited.

### Remaining work
I apologize for only modifying one template initially to initiate the discussion first.

If this change is agreed upon,  it should be synchronized with other `.gitignore` templates. Would it be possible to follow a similar approach as in https://github.com/vercel/next.js/pull/47241? I would appreciate any assistance in syncing this change.

2023-10-10 19:47 UTC, styfle requested changes
Please add this to all the templates

2023-10-18 15:41 UTC, styfle approved these changes
Great, thanks! 🎉

2023-10-18 15:45 UTC, ijjk commented
## Failing test suites <!--17369585362-->
Commit: 91f7312096034225d3aa915877cce11f043ddda3

`pnpm test test/integration/css-features/test/index.test.js` 
- Custom Properties: Pass-Through IE11 > production mode > should have compiled successfully

<details>
<summary>Expand output</summary>

  ● Custom Properties: Pass-Through IE11 › production mode › should have compiled successfully

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      21 |
      22 |     it('should have compiled successfully', () => {
    > 23 |       expect(code).toBe(0)
         |                    ^
      24 |       expect(stdout).toMatch(/Compiled successfully/)
      25 |     })
      26 |

      at Object.<anonymous> (integration/css-features/test/index.test.js:23:20)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2023-10-18 15:47 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| buildDuration | 10.4s | 10.4s | N/A |
| buildDurationCached | 6.3s | 6.2s | N/A |
| nodeModulesSize | 174 MB | 174 MB | ✓ |
| nextStartRea..uration (ms) | 515ms | 517ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| 199-HASH.js gzip | 27.5 kB | 27.5 kB | N/A |
| 3f784ff6-HASH.js gzip | 53.3 kB | 53.3 kB | ✓ |
| 99.HASH.js gzip | 182 B | 182 B | ✓ |
| framework-HASH.js gzip | 45.3 kB | 45.3 kB | ✓ |
| main-app-HASH.js gzip | 254 B | 252 B | N/A |
| main-HASH.js gzip | 32.9 kB | 32.9 kB | N/A |
| webpack-HASH.js gzip | 1.75 kB | 1.75 kB | N/A |
| Overall change | 98.8 kB | 98.8 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| _app-HASH.js gzip | 206 B | 205 B | N/A |
| _error-HASH.js gzip | 182 B | 180 B | N/A |
| amp-HASH.js gzip | 506 B | 505 B | N/A |
| css-HASH.js gzip | 322 B | 323 B | N/A |
| dynamic-HASH.js gzip | 2.57 kB | 2.57 kB | N/A |
| edge-ssr-HASH.js gzip | 260 B | 259 B | N/A |
| head-HASH.js gzip | 350 B | 350 B | ✓ |
| hooks-HASH.js gzip | 369 B | 369 B | ✓ |
| image-HASH.js gzip | 4.35 kB | 4.35 kB | N/A |
| index-HASH.js gzip | 256 B | 256 B | ✓ |
| link-HASH.js gzip | 2.64 kB | 2.63 kB | N/A |
| routerDirect..HASH.js gzip | 312 B | 311 B | N/A |
| script-HASH.js gzip | 385 B | 384 B | N/A |
| withRouter-HASH.js gzip | 307 B | 308 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.08 kB | 1.08 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| index.html gzip | 527 B | 529 B | N/A |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| edge-ssr.js gzip | 93.6 kB | 93.6 kB | N/A |
| page.js gzip | 154 kB | 154 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | leung018/next.js update-create-next-app-gitignore | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 622 B | N/A |
| middleware-r..fest.js gzip | 150 B | 151 B | N/A |
| middleware.js gzip | 22.5 kB | 22.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.92 kB | 1.92 kB | ✓ |
| Overall change | 1.92 kB | 1.92 kB | ✓ |

</details>

</details>
Commit: 91f7312096034225d3aa915877cce11f043ddda3

2023-10-18 16:34 UTC, merged

2023-10-18 16:37 UTC, leung018 commented
Thanks for the review and merge!