make static css immutable
vercel/next.js pull request #5675
Opened 2018-11-14 19:48 UTC by Enalmada

css is currently max-age 0 which means it won't be cached by cdn.  This fixes that along with 
https://github.com/zeit/next-plugins/pull/335

Resolves
https://github.com/zeit/next.js/issues/5464

2018-11-14 21:15 UTC, kachkaev commented
Also related to https://github.com/zeit/next-plugins/issues/243

2018-11-14 22:20 UTC, timneutkens approved these changes
wrong button.

2018-11-14 22:21 UTC, timneutkens requested changes
I don't think this is needed when we have https://github.com/zeit/next-plugins/pull/335 🤔

2018-11-14 22:34 UTC, timneutkens commented
I don't think we should put the implementation detail of a Next.js plugin inside of the Next.js core, especially when it doesn't add anything in this case because you've fixed the root cause of the issue.

2018-11-14 22:36 UTC, Enalmada commented
Well, I only added this when the other thing didn't seem to work.  But now you have me second guessing my sanity.

2018-11-15 08:21 UTC, timneutkens commented
> but commons and page specific css for pages requires this change or else it isn't immutable

This doesn't exist in next-css.

2018-11-15 18:09 UTC, Enalmada commented
Interesting.  So my pages are following the "with-reasonml" example and my reason-react pages call [bindings like this](https://github.com/thangngoc89/bs-ant-design/blob/master/src/Antd_Button.re#L5) that are require antd less/css from node_modules like this:
`[%bs.raw {|require("antd/lib/menu/style")|}];`
Perhaps that is making Next.js/webpack chunk things in unexpected ways that don't go through next-css?

Ultimately the ant design styles that get required for each of my pages ends up being served maxage=0 by next.js in a chunk for each page like this: `.next/static/css/static\qfHVEQIBeZTs5GFjgVDub\pages\index.js.b2aa1ebf.chunk.css`.  Everything served out of "BUILD_ID/pages" by nextjs could/should be immutable though right?  Perhaps this fix is appropriate then to handle this use case?

2018-11-21 18:50 UTC, Enalmada commented
Example reproduction here:  https://github.com/Enalmada/next-reason-boilerplate
(Note that the [custom server is working around the issue](https://github.com/Enalmada/next-reason-boilerplate/blob/master/server.js#L154) by adding immutable to all next/static/css)

I am using ant design and their [babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import).   I am under the impression that is just automatically adding requires for css I need and I assumed next-css would handle it from there but perhaps not, perhaps require calls skip next-css.  The css still ends up being served by nextjs so I think this fix is the only way to handle it.

2018-12-10 23:03 UTC, timneutkens commented
Asked @kylemh and @jhoffmcd to have a look at this to make sure this is the correct fix 👍

2018-12-11 04:37 UTC, jhoffmcd commented
@Enalmada just to catch me up, we think that there is an interop issue with the ReasonML integration that is causing the undesirable output of the css bundle under `static/css`, and the fix is to include `css` string check in the immutable assignment. Does this sound about right? Just getting up to speed on the thread so far.

2018-12-11 19:02 UTC, jhoffmcd commented
@Enalmada can you double check the version of `next-css` you are using on the example repo?

The version you have installed on https://github.com/Enalmada/next-reason-boilerplate:
https://github.com/zeit/next-plugins/blob/%40zeit/next-css%401.0.1/packages/next-css/css-loader-config.js

The version with the path change to `static/chunks/`:
https://github.com/zeit/next-plugins/blob/%40zeit/next-css%401.0.2-canary.2/packages/next-css/css-loader-config.js

2018-12-11 19:44 UTC, Enalmada commented
@jhoffmcd I updated the example repo with next-css:1.0.2-canary.2 and when running in production mode, it unfortunately only fixes one of 5 css files:
![image](https://user-images.githubusercontent.com/1892132/49825017-460c3080-fd38-11e8-928f-bc7ffdb2ccee.png)

4 css files are still being served out of "/_next/static/css" rather than "/_next/static/chunks" and thus missing the fix in 1.0.2-canary.2.  The mystery is what is the right way to get immutable on the rest of them.  I am assuming the way they are being loaded is skipping next-css and a fix like this pull request is necessary but perhaps that assumption is wrong and they should end up being processed by next-css in a way I don't yet understand how to enable.

2018-12-11 21:04 UTC, jhoffmcd commented
@Enalmada Is is possible to get a reproduction with a smaller sub set of dependancies? The boilerplate you have set up integrates a large number of libraries and tooling and I would like to understand the source of the problem before we modify core behavior.

Running canary versions of next and next-plugins alone, I cannot reproduce this outcome. If you think its `antd` and `babel-plugin-import` lets try a minimal version with those things and a custom server implementation and see if we get the same result.

2018-12-11 23:42 UTC, Enalmada commented
Ok I take it back with egg on my face...you are right!  Earlier I updated `@zeit/next-css` but I now notice that there is a @zeit/next-less in my dependencies I forgot to update from 1.0.1.  When i upgrade that to 1.0.2-canary.2 I can't reproduce the problem anymore.   So something in the canary did indeed fix this and all plugins need update rather than just next-css.  Thank you so much for the time you put into trying to reproduce this.

2018-12-11 23:42 UTC, closed without merging