Co/add stytch pages router
vercel/next.js pull request #56759
Opened 2023-10-12 17:22 UTC by chris-stytch

2023-10-12 17:22 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f022d7f26a264f353898b3b41446672ef57a67dd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-10-12 17:22 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f022d7f26a264f353898b3b41446672ef57a67dd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-10-12 17:22 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f022d7f26a264f353898b3b41446672ef57a67dd

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-11-01 00:10 UTC, leerob requested changes

2023-11-01 00:10 UTC, leerob commented on examples/auth-with-stytch/src/pages/_app.js
> +        <title>Stytch Next.js Example</title>
Could we move this to the App Router?

2023-11-01 00:10 UTC, leerob commented on examples/auth-with-stytch/package.json
> +  "version": "0.1.0",
```suggestion
```

2023-11-01 00:10 UTC, leerob commented on examples/auth-with-stytch/package.json
> +    "@next/font": "13.2.3",
This is built-in now

2023-11-01 00:10 UTC, leerob commented on examples/auth-with-stytch/next.config.js
> +  reactStrictMode: true,
This can be removed now

2024-08-15 16:47 UTC, leerob commented
Closing as stale (there are outstanding comments + merge conflicts) but we're open to reviewing a new PR to update this example! 🙏

2024-08-15 16:47 UTC, closed without merging