Add option to next.config docs
vercel/next.js pull request #57444
Opened 2023-10-25 20:05 UTC by molebox

Adds docs for PPR to `next.config` section

2023-10-25 20:17 UTC, delbaoliveira requested changes

2023-10-25 20:17 UTC, delbaoliveira commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +{/* The content of this doc is shared between the app and pages router. You can use the `<PagesOnly>Content</PagesOnly>` component to add content that is specific to the Pages Router. Any shared cont
You can delete this
```suggestion
```

2023-10-25 20:17 UTC, delbaoliveira commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +<AppOnly>
```suggestion
```

2023-10-25 20:17 UTC, delbaoliveira commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +</AppOnly>
```suggestion
```

2023-10-25 20:17 UTC, delbaoliveira commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +Experimental support for Partial Prerendering (PPR). PPR is available in Next.js 14 and allows static portions of a page to be pre-generated and served from the cache with dynamic holes streamed in a
```suggestion
Experimental support for Partial Prerendering (PPR). PPR is available in Next.js 14 and allows static portions of a route to be pre-generated and served from the cache with dynamic holes streamed in a single HTTP request.
```

2023-10-26 13:46 UTC, delbaoliveira approved these changes, later dismissed

2023-10-26 15:31 UTC, leerob commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +title: ppr (experimental)
```suggestion
title: Partial Prerendering
```

2023-10-26 15:31 UTC, leerob commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +description: Enable Partial Prerendering (PPR) in Next.js 14.
```suggestion
description: Learn how to enable Partial Prerendering (experimental) in Next.js 14.
```

2023-10-26 15:31 UTC, leerob commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +Experimental support for Partial Prerendering (PPR). PPR is available in Next.js 14 and allows static portions of a route to be pre-generated and served from the cache with dynamic holes streamed in
```suggestion
Partial Prerendering allows static portions of a route to be prerendered and served from the cache with dynamic holes streamed in, all in a single HTTP request.
```

2023-10-26 15:31 UTC, leerob commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +You can enable PPR in your Next.js project by setting the experimental `ppr` flag:
```suggestion
You can enable Partial Prerendering by setting the experimental `ppr` flag:
```

2023-10-26 15:31 UTC, leerob commented on docs/02-app/02-api-reference/05-next-config-js/partial-prerendering.mdx
> +Learn more about PPR in the [Next.js learn course](/learn/dashboard-app/partial-prerendering).
```suggestion
Learn more about Partial Prerendering in the [Next.js Learn course](/learn/dashboard-app/partial-prerendering).
```

2023-10-26 15:32 UTC, leerob commented
Prefer "Partial Prerendering" over PPR for awhile. Maybe we'll get to an acronym some day.

2023-10-26 15:33 UTC, delbaoliveira approved these changes

2023-10-26 15:46 UTC, leerob commented
Going to fast follow with this 🙏 Will come back.

2023-10-26 15:46 UTC, closed without merging