Switch to using ${window.location.hostname} instead of localhost
vercel/next.js pull request #58150
Opened 2023-11-07 21:48 UTC by aausch

### What?

Switch to using ${window.location.hostname} instead of hardcoding localhost for the with-redux example

### Why?

workaround for CORS issue when accessing the local site via `127.0.0.1:3000` instead of `localhost:3000`

### How?

Switched to a templated string instead of a hard coded one, and referencing `window.location.hostname` instead of a hardcoded `localhost`

2023-11-08 07:03 UTC, imranbarbhuiya requested changes

2023-11-08 07:03 UTC, imranbarbhuiya commented on examples/with-redux/lib/redux/slices/counterSlice/fetchIdentityCount.ts
> +  const response = await fetch(`http://${$window.location.hostname}:3000/api/identity-count`, {
```suggestion
  const response = await fetch(`/api/identity-count`, {
```

Ig this should also work. I'll also use proper port and hostname

2024-03-08 01:14 UTC, samcx approved these changes
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lgtm/8755dd1e0f708009.png" alt=":lgtm:" align="absmiddle"></picture>

2024-03-08 01:15 UTC, samcx requested changes
Looks like there are conflicts!

2024-03-13 17:55 UTC, samcx commented
Looks like the example has drastically since this <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>, so I will be closing this.

2024-03-13 17:55 UTC, closed without merging