fix(turbopack): treat .mdx as valid ecma asset
vercel/next.js pull request #58985
Opened 2023-11-27 21:17 UTC by kwonoj

### What

Pairing with https://github.com/vercel/turbo/pull/6602, enables ecma-related transform support in mdx. notably fixes test cases in https://github.com/vercel/next.js/pull/58968 .

With turbopack side fix, still modularize imports are not being applied as we limite it to .js* extension only. PR expands it to include mdx if mdx is enabled.

2023-11-27 21:25 UTC, ijjk commented
## Failing test suites <!--18539228557-->
Commit: d09ab59305e97e57c2f81b75a47f795593b8d73c

`pnpm test-dev test/e2e/app-dir/mdx/mdx.test.ts` 
- mdx with-mdx-rs > app directory > should work in initial html
- mdx with-mdx-rs > app directory > should work using browser
- mdx with-mdx-rs > app directory > should work in initial html with mdx import
- mdx with-mdx-rs > app directory > should work using browser with mdx import
- mdx with-mdx-rs > app directory > should allow overriding components
- mdx with-mdx-rs > app directory > should allow importing client components

<details>
<summary>Expand output</summary>

  ● mdx with-mdx-rs › app directory › should work in initial html

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello World"
    Received: ""

      23 |         it('should work in initial html', async () => {
      24 |           const $ = await next.render$('/')
    > 25 |           expect($('h1').text()).toBe('Hello World')
         |                                  ^
      26 |           expect($('p').text()).toBe('This is MDX!')
      27 |         })
      28 |

      at Object.toBe (e2e/app-dir/mdx/mdx.test.ts:25:34)

  ● mdx with-mdx-rs › app directory › should work using browser

    expect(received).toBe(expected) // Object.is equality

    Expected: "Hello World"
    Received: "Server Error"

      29 |         it('should work using browser', async () => {
      30 |           const browser = await next.browser('/')
    > 31 |           expect(await browser.elementByCss('h1').text()).toBe('Hello World')
         |                                                           ^
      32 |           expect(await browser.elementByCss('p').text()).toBe('This is MDX!')
      33 |         })
      34 |

      at Object.toBe (e2e/app-dir/mdx/mdx.test.ts:31:59)

  ● mdx with-mdx-rs › app directory › should work in initial html with mdx import

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is a title"
    Received: ""

      35 |         it('should work in initial html with mdx import', async () => {
      36 |           const $ = await next.render$('/import')
    > 37 |           expect($('h1').text()).toBe('This is a title')
         |                                  ^
      38 |           expect($('p').text()).toBe('This is a paragraph')
      39 |         })
      40 |

      at Object.toBe (e2e/app-dir/mdx/mdx.test.ts:37:34)

  ● mdx with-mdx-rs › app directory › should work using browser with mdx import

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is a title"
    Received: "Server Error"

      41 |         it('should work using browser with mdx import', async () => {
      42 |           const browser = await next.browser('/import')
    > 43 |           expect(await browser.elementByCss('h1').text()).toBe(
         |                                                           ^
      44 |             'This is a title'
      45 |           )
      46 |           expect(await browser.elementByCss('p').text()).toBe(

      at Object.toBe (e2e/app-dir/mdx/mdx.test.ts:43:59)

  ● mdx with-mdx-rs › app directory › should allow overriding components

    page.evaluate: TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

      at eval (eval at evaluate (:197:30)../, <anonymous>:2:31)
      at UtilityScript.evaluate (../<anonymous>:199:17)
      at UtilityScript.<anonymous> (../<anonymous>:1:44)
      at ElementHandle.evaluate [as getComputedCss] (lib/browsers/playwright.ts:265:19)
      at getComputedCss (lib/browsers/playwright.ts:309:17)
      at Object.<anonymous> (e2e/app-dir/mdx/mdx.test.ts:53:18)

  ● mdx with-mdx-rs › app directory › should allow importing client components

    expect(received).toBe(expected) // Object.is equality

    Expected: "This is a client component"
    Received: ""

      58 |         it('should allow importing client components', async () => {
      59 |           const $ = await next.render$('/')
    > 60 |           expect($('h2').text()).toBe('This is a client component')
         |                                  ^
      61 |         })
      62 |       })
      63 |

      at Object.toBe (e2e/app-dir/mdx/mdx.test.ts:60:34)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2023-11-27 21:45 UTC, sokra approved these changes, later dismissed

2023-11-27 21:56 UTC, kdy1 submitted a review, later dismissed

2023-11-27 23:38 UTC, sokra requested changes
The turbopack bump is not correct. It's missing updates to the package.json and package-lock.json. Please use the next-link script to correctly update.

2023-11-28 11:18 UTC, sokra approved these changes

2023-11-28 12:54 UTC, timneutkens approved these changes

2023-11-28 12:54 UTC, merged