Move App Router client-side constants to separate file
vercel/next.js pull request #59239
Opened 2023-12-04 10:46 UTC by timneutkens

## What?

Noticed constants.js was included in the client-side bundle. This ensures only the needed constants are included.

## How?

Created a separate file for client-side constants.

2023-12-04 10:46 UTC, timneutkens commented
Current dependencies on/for this PR:
* canary
  * **PR #59239** <a href="https://app.graphite.dev/github/pr/vercel/next.js/59239?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/59239?utm_source=stack-comment).

2023-12-04 11:13 UTC, feedthejim requested changes

2023-12-04 13:30 UTC, timneutkens commented on packages/next/src/shared/lib/app-router-client-constants.ts
> +export const NEXT_DID_POSTPONE_HEADER = 'x-nextjs-postponed'
Those are not used in the client-side. I only moved the client-side variables. Adding those here would increase client-side bundle size needlessly.

2023-12-04 15:59 UTC, feedthejim commented on packages/next/src/shared/lib/app-router-client-constants.ts
> +export const NEXT_DID_POSTPONE_HEADER = 'x-nextjs-postponed'
I was referring to the ones when we annotate a fetch with the prefetch/rsc headers

2023-12-06 11:06 UTC, huozhi approved these changes

2023-12-06 11:07 UTC, merged