allow custom types for `.svg` image imports (instead of default `any`)
vercel/next.js pull request #59855
Opened 2023-12-21 17:25 UTC by stefanprobst

currently, the built-in image import types referenced in `next-env.d.ts` type `.svg` imports as `any` (see [here](https://github.com/vercel/next.js/blob/canary/packages/next/image-types/global.d.ts#L10-L19)):

```ts
declare module '*.svg' {
  /**
   * Use `any` to avoid conflicts with
   * `@svgr/webpack` plugin or
   * `babel-plugin-inline-react-svg` plugin.
   */
  const content: any

  export default content
}
```

this pr adds a new `customImageTypes` experimental option - as suggested by @ijjk [here](https://github.com/vercel/next.js/pull/30060#pullrequestreview-1064489359) - which disables the built-in image import types, and allows users to provide their own types (via e.g. `custom-image-types.d.ts`)

x-ref: https://github.com/vercel/next.js/pull/30060

2023-12-21 17:26 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 82e64df93c8e4ad73090823fd5dfec7134c909b4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2023-12-21 17:26 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 82e64df93c8e4ad73090823fd5dfec7134c909b4

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-01-03 21:40 UTC, styfle commented on packages/next/src/lib/verify-typescript-setup.ts
> +      imageImportsEnabled: !disableStaticImages && !customImageTypes,
What is the difference between `customImageTypes` and `disableStaticImages`. Why not use the existing `disableStaticImages` instead?

2024-01-03 21:53 UTC, styfle requested changes
I don't think you need a config option to override types.

Add a new file like `additional.d.ts`:

```ts
declare module '*.svg' {
  const content: { foo: string, bar: number }
  export default content
}
```

Then update tsconfig.json to include it:

```js
  "include": [
    "additional.d.ts",
    "next-env.d.ts",
    ".next/types/**/*.ts",
    "**/*.ts",
    "**/*.tsx",
  ],
```

See my previous comment here: https://github.com/vercel/next.js/pull/30060#discussion_r732243330

2024-01-03 22:22 UTC, stefanprobst commented
@styfle unfortunately, this won't work - see https://github.com/stefanprobst/issue-next-svg-types/commit/e318c80b94035d9d90c0219634770fa9a7d09986 for a reproduction

![Screenshot_20240103_232026](https://github.com/vercel/next.js/assets/20753323/81a90f43-0dfc-48b0-b3e3-27ac0a7b28da)

2024-01-03 22:45 UTC, styfle commented
@stefanprobst Thats odd. I just tried with the latest `next@14.0.4` and it worked.

I had to put `additional.d.ts` as the first include in tsconfig.json, like this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "additional.d.ts",
    "next-env.d.ts",
    ".next/types/**/*.ts",
    "**/*.ts",
    "**/*.tsx",
  ],
  "exclude": [
    "node_modules"
  ]
}
```

2024-01-03 22:52 UTC, styfle commented
Looks like it the difference is `skipLibCheck`. 

It works when true (which I believe is what TS recommends because its true when you run `tsc --init`).

2024-01-03 22:56 UTC, stefanprobst commented
i set `skipLibCheck` to false in the issue repro, otherwise `.d.ts` files will not be typechecked (`skipLibCheck` also skips local `.d.ts` files).

with `skipLibCheck: true` i still only get `any` for `.svg` imports, not what is defined in `additional.d.ts`.

2024-01-03 23:11 UTC, closed without merging

2024-01-03 23:47 UTC, styfle commented
Thanks! I'll talk to the docs team to see how we can surface this information. It seems like this previous call-out was removed for some reason https://github.com/vercel/next.js/pull/30060#discussion_r732243330 so at the very least, we can add it back.