Check for .json file extension before JSON parse. Was throwing when r…
vercel/next.js pull request #601
Opened 2017-01-01 16:26 UTC by msand

…eading js files. Related to #597

2017-01-01 16:46 UTC, nkzawa commented on server/read-page.js
> +  if (f.slice(-5) === '.json') {
I think this is always `.json` ? @arunoda

2017-01-01 20:40 UTC, arunoda commented on server/read-page.js
> +  if (f.slice(-5) === '.json') {
We need to have `.js` as well. In order to support `dist`. Loading SSR files.

2017-01-01 20:43 UTC, arunoda commented on server/read-page.js
> +  if (f.slice(-5) === '.json') {
Oh! wait. But for here, it's always `.json`. 
If there's no `.json` file, we need to throw an error.
Then I think we don't need a change here.

2017-01-01 22:43 UTC, ryancole commented
Just tested `msand:fix-windows-error`, and it does indeed cause the error to go away. I'm on Windows 10.

2017-01-01 23:09 UTC, arunoda requested changes

2017-01-01 23:09 UTC, arunoda commented on server/read-page.js
> +  let content = await fs.readFile(f, 'utf8')
@msand Would you mind removing all the changes done to this page.
We always need to read `.json` files so if there's no `.json` file, that's an error.

2017-01-02 04:08 UTC, arunoda commented
Took this PR with https://github.com/zeit/next.js/pull/611

2017-01-02 04:08 UTC, closed without merging

2017-01-02 09:07 UTC, msand commented on server/read-page.js
> +  let content = await fs.readFile(f, 'utf8')
Alright, I figured as much, should've made a separate pr to begin with. Thanks