fix: x-forwarded-port header is 'undefined' when no port in url
vercel/next.js pull request #60484
Opened 2024-01-10 17:48 UTC by yuvalotem

### What?
following this change https://github.com/vercel/next.js/pull/57815 `x-forwarded-port` header value is 'undefined' if the url has no port

### Why?
x-forwarded-port 'undefined' makes other http-proxy throw 405 error for invalid header value

### How?
Give default 80 port if the URL has no port

2024-03-06 20:15 UTC, Ethan-Arrowood requested changes
This is looking good @yuvalotem - can you come up with a test for it perhaps? You may be able to modify an existing one too. I will also look into this and then we can land your changes. Thank you!

2024-03-11 16:15 UTC, ijjk commented
## Failing test suites <!--21599643160-->
Commit: 7188a799428d214e08564b3879abd14b4ac70b61

`pnpm test-dev test/development/app-hmr/hmr.test.ts`
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (edge)

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (edge)

    page.goto: Timeout 60000ms exceeded.
    Call log:
      - navigating to "http://localhost:44767/env/edge", waiting until "load"

      274 |     opts?.beforePageLoad?.(page)
      275 |
    > 276 |     await page.goto(url, { waitUntil: 'load' })
          |                ^
      277 |   }
      278 |
      279 |   back(options): BrowserInterface {

      at BrowserInterface.goto (lib/browsers/playwright.ts:276:16)
      at webdriver (lib/next-webdriver.ts:129:3)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:77:25)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-03-11 20:13 UTC, Ethan-Arrowood approved these changes
I cannot determine a way to test this issue using a local Next.js server (even a custom one). 

I've created https://github.com/vercel/vercel/pull/11254 to test this e2e. I've asserted that the currently described behavior in https://github.com/vercel/next.js/issues/61133 is valid (see commented output https://github.com/vercel/vercel/pull/11254#issuecomment-1989332557).

Once this is landed, we can verify the new test passes and then land it to prevent regressions.

2024-03-12 16:33 UTC, Ethan-Arrowood requested changes

2024-03-12 16:33 UTC, Ethan-Arrowood commented on packages/next/src/server/base-server.ts
> +      const isHttps = !!(originalRequest.socket as TLSSocket)?.encrypted
```suggestion
      const isHttps = !!(originalRequest?.socket as TLSSocket)?.encrypted
```

This should fix the broken tests.

2024-03-12 16:41 UTC, Ethan-Arrowood approved these changes

2024-03-12 16:45 UTC, merged