upgrade @types/react-dom to v18.2.18 to import `useFormState` for server actions
vercel/next.js pull request #60822
Opened 2024-01-18 15:03 UTC by taishikato

### Adding or Updating Examples

I can't import `useFormState` from `react-dom` with `@types/react-dom@18.2.5`, so I upgrade it to the latest version of it.

2024-01-18 18:13 UTC, GuiBibeau approved these changes

2024-01-18 20:26 UTC, samcx requested changes
If you can upgrade the other packages as well that will be great!

2024-01-19 04:13 UTC, taishikato commented
Hey @samcx, I just upgraded other packages too 👍

2024-01-19 04:15 UTC, samcx approved these changes
<picture data-single-emoji=":lgtm:" title=":lgtm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lgtm/8755dd1e0f708009.png" alt=":lgtm:" align="absmiddle"></picture>

2024-01-19 04:19 UTC, merged