add new nextjs typings with samples
vercel/next.js pull request #6102
Opened 2019-01-22 12:01 UTC by calendee

The current `examples/with-typescript` is not using the latest type definitions currently available on DefinitelyTyped project for next.

Added new list page examples that demonstrate how to use the new Types for both stateless functional components and classes.  Also modified examples for list to demonstrate typings for `getInitialProps`.

2019-01-22 12:21 UTC, timneutkens approved these changes

2019-01-22 14:50 UTC, resir014 requested changes
Hey, this looks good to me. Just a few styling changes needed, though.

2019-01-22 14:50 UTC, resir014 commented on examples/with-typescript/components/ListItem.tsx
> +export interface IProps {
Can we change these `interface`s to `type`s instead?

2019-01-22 14:50 UTC, resir014 commented on examples/with-typescript/components/Layout.tsx
> +    <div>
Let's keep the two-space indentation in all files to keep the diffs clean.

2019-01-22 14:50 UTC, resir014 commented on examples/with-typescript/pages/list-class.tsx
> +interface IListClassProps {
Same here for `type`s v. `interface`s.

2019-01-22 19:24 UTC, calendee commented
Anyone know how/why coverage would have changed with this PR?  I did delete an unused file `examples/with-typescript/pages/list.tsx`.  However, I don't see any coverage tests for it.  

When I view the coverage changes, I don't see any changes that affect the `examples` directory at all.

Any idea on how to fix this or overcome the required checks for it?

2019-01-23 02:34 UTC, resir014 approved these changes
Yep, looks good!

2019-01-23 11:37 UTC, timneutkens approved these changes

2019-01-23 11:37 UTC, merged