Add dot to regex chars in rewrites.mdx
vercel/next.js pull request #61095
Opened 2024-01-24 16:18 UTC by yannbolliger

The rewrites doc was missing the `.` character when specifying which characters were used for regex matching.

2024-01-24 21:30 UTC, samcx requested changes

2024-01-24 21:30 UTC, samcx commented on docs/02-app/02-api-reference/05-next-config-js/rewrites.mdx
> +The following characters `(`, `)`, `{`, `}`, `.`, `:`, `*`, `+`, `?` are used for regex path matching, so when used in the `source` as non-special values they must be escaped by adding `\\` before th
```suggestion
The following characters `(`, `)`, `{`, `}`, `[`, `]`, `|`, `\`, `^`, `.`, `:`, `*`, `+`, `-`, `?`, `$` are used for regex path matching, so when used in the `source` as non-special values they must be escaped by adding `\\` before them:
```

2024-01-26 02:08 UTC, adminess approved these changes

2024-01-26 02:09 UTC, adminess approved these changes

2024-01-26 02:38 UTC, samcx approved these changes
<picture data-single-emoji=":lgtm:" title=":lgtm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lgtm/8755dd1e0f708009.png" alt=":lgtm:" align="absmiddle"></picture>

2024-01-26 02:41 UTC, merged