Expand test for AsyncLocalStorage to avoid throwing in old chrome
vercel/next.js pull request #61873
Opened 2024-02-09 20:40 UTC by karlkeefer

Simpler/cleaner alternative to #61872.
Attempting to fix bug https://github.com/vercel/next.js/discussions/58818#discussioncomment-8422873

2024-04-30 12:03 UTC, mikl commented
@ijjk this problem is a real pain in the neck when you have customers using old devices, any chance it could be expedited?

2024-06-13 09:01 UTC, Sjlver commented
We currently use a `globalThis` polyfill because of this issue. @timneutkens, it would be great if one of the reviewers could approve this one-line change.

2024-06-14 01:57 UTC, ijjk requested changes
Hi, it looks like we can't update this PR/run checks as contributions from contributors is disabled.

2024-06-17 19:25 UTC, karlkeefer commented
@ijjk I couldn't find a relevant setting in github that matches your description - in lieu of that I sent you an admin invite for our fork. If that doesn't accomplish the need can you point me in the right direction for the appropriate setting?

Apologies for the hassle - I gave it a proper shake!

2024-06-18 13:33 UTC, ijjk commented
## Failing test suites <!--25035358490-->
Commit: 71b95f75c5e84b13c12f008a878863dd21a1119b

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/metadata/metadata.test.ts` (PPR)
- app dir - metadata > twitter > should support twitter card summary_large_image when image present

<details>
<summary>Expand output</summary>

  ● app dir - metadata › twitter › should support twitter card summary_large_image when image present

    expect(received).toContain(expected) // indexOf

    Expected value: "Twitter Title"
    Received array: []

      36 |           expect(values).not.toContain(undefined)
      37 |         } else {
    > 38 |           expect(values).toContain(expected)
         |                          ^
      39 |         }
      40 |       }
      41 |     }

      at toContain (e2e/app-dir/metadata/metadata.test.ts:38:26)
          at async Promise.all (index 0)
      at e2e/app-dir/metadata/metadata.test.ts:133:7
      at Object.<anonymous> (e2e/app-dir/metadata/metadata.test.ts:792:7)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-06-18 13:35 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| buildDuration | 19.3s | 16.6s | N/A |
| buildDurationCached | 9.3s | 8.7s | N/A |
| nodeModulesSize | 359 MB | 359 MB | ⚠️ +136 B |
| nextStartRea..uration (ms) | 426ms | 445ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| 3377.HASH.js gzip | 168 B | 168 B | ✓ |
| 6561-HASH.js gzip | 36 kB | 36 kB | N/A |
| 7908-HASH.js gzip | 5.06 kB | 5.07 kB | N/A |
| 7ba1ee62-HASH.js gzip | 51.7 kB | 51.7 kB | N/A |
| framework-HASH.js gzip | 56.7 kB | 56.7 kB | N/A |
| main-app-HASH.js gzip | 222 B | 218 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 168 B | 168 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 192 B | 191 B | N/A |
| amp-HASH.js gzip | 511 B | 511 B | ✓ |
| css-HASH.js gzip | 340 B | 342 B | N/A |
| dynamic-HASH.js gzip | 2.53 kB | 2.52 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 266 B | N/A |
| head-HASH.js gzip | 361 B | 363 B | N/A |
| hooks-HASH.js gzip | 389 B | 389 B | ✓ |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 327 B | 324 B | N/A |
| script-HASH.js gzip | 395 B | 394 B | N/A |
| withRouter-HASH.js gzip | 322 B | 321 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.47 kB | 1.47 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| _buildManifest.js gzip | 485 B | 482 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| index.html gzip | 523 B | 521 B | N/A |
| link.html gzip | 537 B | 536 B | N/A |
| withRouter.html gzip | 520 B | 517 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| edge-ssr.js gzip | 125 kB | 125 kB | N/A |
| page.js gzip | 167 kB | 167 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 661 B | 660 B | N/A |
| middleware-r..fest.js gzip | 155 B | 154 B | N/A |
| middleware.js gzip | 29.5 kB | 29.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 1.03 kB | 1.03 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 184 kB | 184 kB | ✓ |
| app-page-exp..prod.js gzip | 112 kB | 112 kB | ✓ |
| app-page-tur..prod.js gzip | 123 kB | 123 kB | ✓ |
| app-page-tur..prod.js gzip | 119 kB | 119 kB | ✓ |
| app-page.run...dev.js gzip | 178 kB | 178 kB | ✓ |
| app-page.run..prod.js gzip | 108 kB | 108 kB | ✓ |
| app-route-ex...dev.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route-ex..prod.js gzip | 18.8 kB | 18.8 kB | ✓ |
| app-route-tu..prod.js gzip | 18.8 kB | 18.8 kB | ✓ |
| app-route-tu..prod.js gzip | 18.6 kB | 18.6 kB | ✓ |
| app-route.ru...dev.js gzip | 24.6 kB | 24.6 kB | ✓ |
| app-route.ru..prod.js gzip | 18.6 kB | 18.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| pages.runtim...dev.js gzip | 22.1 kB | 22.1 kB | ✓ |
| pages.runtim..prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| server.runti..prod.js gzip | 51.7 kB | 51.7 kB | ✓ |
| Overall change | 1.09 MB | 1.09 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | HealthLearn/next.js avoid-throwing-on-undefined-globalThis | Change |
| - | - | - | - |
| 0.pack gzip | 1.67 MB | 1.67 MB | N/A |
| index.pack gzip | 129 kB | 129 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 353: /***/ (
+    /***/ 1874: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610_react_vrduafyijdumnv5m4yyxi35vzu/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsxNFA0u%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610_react_66pum5zqjmu66dbgsbrnmwmucy/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsxNFA0u%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -70,35 +70,35 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610_react_vrduafyijdumnv5m4yyxi35vzu/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(1567);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610_react_vrduafyijdumnv5m4yyxi35vzu/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __webpack_require__(8537);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610_react_vrduafyijdumnv5m4yyxi35vzu/node_module [...]

2024-06-18 13:51 UTC, ijjk approved these changes

2024-06-18 14:05 UTC, merged

2024-06-18 17:58 UTC, karlkeefer commented
Thanks @ijjk 🙌