Updating Cloudinary Video Resources
vercel/next.js pull request #61959
Opened 2024-02-12 19:34 UTC by colbyfayock

### What?

Updates the Cloudinary bullets and links under the Video Optimization.

https://nextjs.org/docs/app/building-your-application/optimizing/videos#cloudinary-integration

### Why?

More relevant direct link to the Cloudinary-supported Next.js SDK along with an additional link to the Video solution itself.

2024-02-12 19:42 UTC, samcx requested changes

2024-02-12 19:42 UTC, samcx commented on docs/02-app/01-building-your-application/06-optimizing/02-videos.mdx
> +- Includes a `<CldVideoPlayer>` component for [drop-in video support](https://next.cloudinary.dev/cldvideoplayer/basic-usage)
```suggestion
- Includes a `<CldVideoPlayer>` component for [drop-in video support](https://next.cloudinary.dev/cldvideoplayer/basic-usage).
```

2024-02-12 19:42 UTC, samcx commented on docs/02-app/01-building-your-application/06-optimizing/02-videos.mdx
> +- Find [examples](https://github.com/cloudinary-community/cloudinary-examples/?tab=readme-ov-file#nextjs) of integrating Cloudinary with Next.js including [Adaptive Bitrate Streaming](https://github.
```suggestion
- Find [examples](https://github.com/cloudinary-community/cloudinary-examples/?tab=readme-ov-file#nextjs) of integrating Cloudinary with Next.js including [Adaptive Bitrate Streaming](https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/nextjs-cldvideoplayer-abr).
```

2024-02-12 19:43 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 10e82aa01d39eaa158911269c4f39913b91d800f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-02-12 19:43 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 10e82aa01d39eaa158911269c4f39913b91d800f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-02-12 19:46 UTC, samcx approved these changes
Thank you for submitting a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>!

<picture data-single-emoji=":lgtm:" title=":lgtm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lgtm/8755dd1e0f708009.png" alt=":lgtm:" align="absmiddle"></picture>

2024-02-22 18:01 UTC, colbyfayock commented
hey just checking in to make sure you're not waiting on me for anything! thanks

2024-02-22 18:59 UTC, samcx commented
@colbyfayock Not waiting for anything! Looks like this fell in the test blackhole—will re-run this and hopefully it merges!

2024-02-22 19:01 UTC, merged

2024-02-22 19:09 UTC, colbyfayock commented
haha thanks @samcx 🙏