fix(example): fixes styled-components example
vercel/next.js pull request #6207
Opened 2019-02-05 01:53 UTC by rouzbeh84

currently gives `TypeError: sheet.seal is not a function` as `Object.seal()` needs the desired object passed in I believe. This seemed to work so submitting the fix 👍

2019-02-05 12:47 UTC, timneutkens commented
cc @probablyup

2019-02-05 13:42 UTC, mxstbr requested changes
This needs to be `sheet.complete()` in v4 I believe. This has nothing to do with `Object.seal`.

2019-02-05 15:20 UTC, probablyup commented
Actually it is `.seal()`: https://github.com/styled-components/styled-components/blob/9b81695d35074974c42b943a82456c9ae4b42500/packages/styled-components/src/models/ServerStyleSheet.js#L31

2019-02-05 15:21 UTC, probablyup commented
You shouldn't have to call `seal()` manually through except in an error scenario.

2019-02-05 16:22 UTC, timneutkens commented
Thank you @probablyup @mxstbr 🙏 🙏

2019-02-05 16:22 UTC, closed without merging

2019-02-07 16:15 UTC, rouzbeh84 commented
Thanks @timneutkens, @probablyup, and @mxstbr for checking! Will update project deps instead 🙏

2019-05-31 13:13 UTC, DevAbas commented
thanks @rouzbeh84 it worked for me.