Add Error when using publicRuntimeConfig with target serverless and add buildVars
vercel/next.js pull request #6212
Opened 2019-02-05 19:35 UTC by dav-is

Adds err.sh link when using `publicRuntimeConfig` with `target=serverless`
Adds `buildVars` for adding to webpack define plugin through `next.config.js`

2019-02-06 06:11 UTC, timneutkens commented on packages/next/build/webpack-config.js
> +            ...{ [`process.${key}`]: JSON.stringify(config.env[key]) }
Shouldn't this be `process.env.${key}` 🤔

2019-02-06 06:11 UTC, timneutkens commented on packages/next/build/webpack-config.js
> +            ...{ [`process.${key}`]: JSON.stringify(config.env[key]) }
We should use `process.env.` because otherwise Typescript / Flow etc will not recognize it as a valid format.

2019-02-07 00:18 UTC, developit approved these changes

2019-02-07 00:19 UTC, developit commented
LGTM - question though: I know convention indicates defines should be `process.env.*`, but in this case, is there a way to skip prefixing for a field?  I've seen a common technique be to define something like an `SSR` global (`if (SSR) {}`).

2019-02-07 00:22 UTC, dav-is commented
@developit is there an API you'd suggest? 

We could do a regex if the key started with an `_` then it shouldn't have `process.env` added to it.

2019-02-07 10:34 UTC, timneutkens commented
@developit I don't think we should introduce the option for users to add global variables like that, especially with type checking / linting that can become an issue. Next.js provides `process.browser` automatically (but undocumented), mostly because we saw a lot of users do this because webpack provides it automatically, except the way that is handled in webpack it mean that extra code is shipped instead of replacing at build time.

2019-02-07 22:06 UTC, timneutkens requested changes
Could you add a test for this in `test/integration/config`

2019-02-08 13:38 UTC, merged

2019-02-09 19:17 UTC, marcinczenko commented
I have some observations about this approach. 

1. There is a duplication between `env` in `now.json` and `env` in `next.config.js`. Understanding the difference between the two is tricky for me and will be even more tricky to new users.

2. As indicated, the `env` setting in `next.config.js` is only **build configuration**, which is basically the same as using `env` (not even `build.env` - if I add this to the equation my brain starts overheating), which currently already makes all environment variables available on the server side, which means you can tunnel it to the client using `getInitialProps`.

3. `env` in `now.json` works with secretes. `env` in `next.config.js` does not - at least not directly and this is not document in README. One way to make it work would be first to declare the secret in `env` in `now.json` and then refer to `process.env` in `env` section in `next.config.js`:
  \
  in `now.json`:
    ```
    "env": {
      "MY_SECRET": "@my-secret"
    }
    ```
    in `next.config.js`:
    ```
    env: {
      mySecret: process.env.MY_SECRET
    }
    ```
    I cannot validate this setup when deploying, because if I try this, my build finishes successfully but then hangs forever on `initialising` stage. I will update this comment if I get that resolved. So, at the current stage I am not even sure if there is any way of forwarding tunnels to the frontend using the combination of `env` in `now.json` and `next.config.js`.

What is then really advantage of having `env` in `next.config.js`?  The only advantage seems to be that you do not have to tunnel the envs via `getInitialProps`, but only for values you do not mind exposing in your commit.

2019-02-10 01:02 UTC, revskill10 commented
@marcinczenko In the last point, i think it should just work with `build.env` , not `env`.

2019-02-10 01:17 UTC, marcinczenko commented
Thanks @revskill10. I will check `build.env` option. I must be missing a lot form how internals work, so I would agree with your argument about necessity of having `env` option in `next.config.js` in order to avoid using workarounds based on `babel-transform-inline-environment-variables`. It feels dirty, but if there is no better way or this is temporary quick win, it should be fine.

2019-02-10 01:29 UTC, marcinczenko commented
@revskill10 confirmed. `build.env` works.

2019-02-12 19:28 UTC, cmcaboy commented
I may be missing something here, but it appears that the config key reference is only for build time env variables? Are there no solutions for run time variables with serverless?

2019-02-12 23:17 UTC, cmcaboy commented
I was able to fix this by tunneling the process.env.<Variable> down through getInitialProps to the client.