fix(turbopack): Remove error overlay when issue is resolved
vercel/next.js pull request #62983
Opened 2024-03-07 09:35 UTC by kdy1

### What?

Remove error entries about `_error`.

### Why?

To make the error overlay disappear when the error is fixed.

I tried skipping related entries by using continue from https://github.com/vercel/next.js/blob/5f3b13584ce87eac00f8b801c24a5de14a0a3ed9/packages/next/src/server/dev/hot-reloader-turbopack.ts#L675-L684, but it resulted in it page being rendered in the background while error overlay does not disappear.

We need to remove the errors from `/_error` page to make the error overlay disappear, so I tried removing them from the map and it worked.

### How?

Closes PACK-2405

2024-03-07 09:42 UTC, ijjk commented
## Failing test suites <!--21476424202-->
Commit: 37089665e3c488d990c589040ae2792df129dd9d

`TURBOPACK=1 pnpm test test/integration/build-indicator/test/index.test.js` (turbopack)
- Build Activity Indicator > Enabled > Shows build indicator when page is built from modifying

<details>
<summary>Expand output</summary>

  ● Build Activity Indicator › Enabled › Shows build indicator when page is built from modifying

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: undefined

       97 |       const wasVisible = await browser.eval('window.showedBuilder')
       98 |
    >  99 |       expect(wasVisible).toBe(true)
          |                          ^
      100 |       await fs.writeFile(pagePath, origContent, 'utf8')
      101 |       await browser.close()
      102 |     })

      at Object.toBe (integration/build-indicator/test/index.test.js:99:26)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-03-07 09:45 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.8s | ⚠️ +179ms |
| buildDurationCached | 7.3s | 6.1s | N/A |
| nodeModulesSize | 198 MB | 198 MB | ⚠️ +9.8 kB |
| nextStartRea..uration (ms) | 429ms | 429ms | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 30.5 kB | 30.5 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | N/A |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 239 B | 242 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 45.4 kB | 45.4 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 541 B | 542 B | N/A |
| withRouter.html gzip | 524 B | 523 B | N/A |
| Overall change | 529 B | 529 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.1 kB | 95.1 kB | N/A |
| page.js gzip | 3.07 kB | 3.07 kB | ✓ |
| Overall change | 3.07 kB | 3.07 kB | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 626 B | 625 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 96.5 kB | 96.5 kB | ✓ |
| app-page-tur..prod.js gzip | 98.2 kB | 98.2 kB | ✓ |
| app-page-tur..prod.js gzip | 92.7 kB | 92.7 kB | ✓ |
| app-page.run...dev.js gzip | 149 kB | 149 kB | ✓ |
| app-page.run..prod.js gzip | 91.2 kB | 91.2 kB | ✓ |
| app-route-ex...dev.js gzip | 21.3 kB | 21.3 kB | ✓ |
| app-route-ex..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 15 kB | 15 kB | ✓ |
| app-route-tu..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| app-route.ru...dev.js gzip | 20.9 kB | 20.9 kB | ✓ |
| app-route.ru..prod.js gzip | 14.8 kB | 14.8 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.8 kB | 9.8 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.52 kB | 9.52 kB | ✓ |
| pages-turbo...prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| pages.runtim...dev.js gzip | 22.9 kB | 22.9 kB | ✓ |
| pages.runtim..prod.js gzip | 22.3 kB | 22.3 kB | ✓ |
| server.runti..prod.js gzip | 50.5 kB | 50.5 kB | ✓ |
| Overall change | 947 kB | 947 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/pack-2405 | Change |
| - | - | - | - |
| 0.pack gzip | 1.56 MB | 1.56 MB | N/A |
| index.pack gzip | 106 kB | 105 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 37089665e3c488d990c589040ae2792df129dd9d

2024-03-12 07:33 UTC, sokra commented on packages/next/src/server/dev/hot-reloader-turbopack.ts
> +        }
This will just always reload the page on HMR events

2024-03-13 17:59 UTC, ForsakenHarmony commented on packages/next/src/server/dev/hot-reloader-turbopack.ts
> +        currentEntryIssues.delete(getEntryKey('pages', 'server', '_error'))
This feels wrong to me, I also don't think `app` has a `_error` route.

We might just want to subscribe to changes of the `_error` page.

2024-03-13 17:59 UTC, ForsakenHarmony requested changes

2024-03-13 17:59 UTC, ForsakenHarmony commented on packages/next/src/server/dev/hot-reloader-turbopack.ts
> +        currentEntryIssues.delete(getEntryKey('pages', 'server', '_error'))
This feels wrong to me, I also don't think `app` has a `_error` route.

We might just want to subscribe to changes of the `_error` page.

2024-03-13 18:18 UTC, ForsakenHarmony approved these changes
Pushed my suggestion above as that seemed like the easiest way to show what I meant

2024-03-14 04:31 UTC, merged