docs: refer the image configuration options at next.config.js options
vercel/next.js pull request #63712
Opened 2024-03-26 11:34 UTC by devjiwonchoi

Closes #62793

2024-03-26 11:35 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c47514a00b8ddf95d1f230891ef612e2f0daceff

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-03-26 11:35 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c47514a00b8ddf95d1f230891ef612e2f0daceff

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-03-26 15:03 UTC, styfle requested changes
This seems to bury the lede.

We need to keep the code snippet.

2024-03-26 15:25 UTC, devjiwonchoi commented
Thank you for reviewing!

2024-03-26 15:37 UTC, devjiwonchoi commented on docs/02-app/02-api-reference/01-components/image.mdx
> +</AppOnly>
```suggestion
</PagesOnly>
```

2024-03-29 01:44 UTC, styfle commented on docs/02-app/02-api-reference/01-components/image.mdx
> +    loaderFile: './my/image/loader.mjs',
```suggestion
    loaderFile: './my/image/loader.js',
```

2024-03-29 01:44 UTC, styfle commented on docs/02-app/02-api-reference/01-components/image.mdx
> +```js filename="loader.mjs"
```suggestion
```js filename="my/image/loader.js"
```

2024-03-29 01:44 UTC, styfle commented on docs/02-app/02-api-reference/01-components/image.mdx
> +```js
```suggestion
```js filename="my/image/loader.js"
```

2024-03-29 01:45 UTC, styfle commented on docs/02-app/02-api-reference/05-next-config-js/images.mdx
> +    loaderFile: './my/image/loader.mjs',
```suggestion
    loaderFile: './my/image/loader.js',
```

2024-03-29 01:45 UTC, styfle commented on docs/02-app/02-api-reference/05-next-config-js/images.mdx
> +```js filename="loader.mjs"
```suggestion
```js filename="my/image/loader.js"
```

2024-03-29 01:46 UTC, styfle commented on docs/02-app/02-api-reference/05-next-config-js/images.mdx
> +```js filename="loader.mjs"
```suggestion
```js filename="my/image/loader.js"
```

2024-03-29 01:47 UTC, styfle approved these changes
Thanks!

2024-03-29 01:49 UTC, merged