default fetchCache to force-no-store when force-dynamic is set
vercel/next.js pull request #64145
Opened 2024-04-06 14:09 UTC by ztanner

Closes NEXT-2067

2024-04-06 14:09 UTC, ztanner commented
* **#64145** <a href="https://app.graphite.dev/github/pr/vercel/next.js/64145?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ztanner and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-06 14:14 UTC, ijjk commented
## Failing test suites <!--22491992327-->
Commit: 4309ac93f17a4cd755cfab58e4ab3a436ea5d5ad

`TURBOPACK=1 pnpm test test/integration/eslint/test/next-lint.test.js` (turbopack)
- Next Lint > First Time Setup  > installs eslint and eslint-config-next as devDependencies if missing with yarn
- Next Lint > First Time Setup  > creates .eslintrc.json file with a default configuration
- Next Lint > First Time Setup  > shows a successful message when completed

<details>
<summary>Expand output</summary>

  ● Next Lint › First Time Setup  › installs eslint and eslint-config-next as devDependencies if missing with yarn

    ENOENT: no such file or directory, open '/tmp/brmc6dxsa9m/package.json'



  ● Next Lint › First Time Setup  › creates .eslintrc.json file with a default configuration

    ENOENT: no such file or directory, open '/tmp/c11oafka9q/package.json'



  ● Next Lint › First Time Setup  › shows a successful message when completed

    ENOENT: no such file or directory, open '/tmp/zoolvqhy53/package.json'



</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-04-06 14:15 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14.2s | ⚠️ +224ms |
| buildDurationCached | 7.5s | 6.4s | N/A |
| nodeModulesSize | 199 MB | 199 MB | ⚠️ +14.6 kB |
| nextStartRea..uration (ms) | 381ms | 399ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.04 kB | 5.04 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 241 B | N/A |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99 kB | 99 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.21 kB | 4.21 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.57 kB | 6.57 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 484 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| index.html gzip | 529 B | 529 B | ✓ |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 523 B | 524 B | N/A |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.4 kB | 95.4 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 624 B | 623 B | N/A |
| middleware-r..fest.js gzip | 151 B | 151 B | ✓ |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 990 B | 990 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 170 kB | 170 kB | ✓ |
| app-page-exp..prod.js gzip | 97 kB | 97 kB | ✓ |
| app-page-tur..prod.js gzip | 98.8 kB | 98.8 kB | ✓ |
| app-page-tur..prod.js gzip | 93 kB | 93 kB | ✓ |
| app-page.run...dev.js gzip | 144 kB | 144 kB | ✓ |
| app-page.run..prod.js gzip | 91.5 kB | 91.5 kB | ✓ |
| app-route-ex...dev.js gzip | 21.4 kB | 21.4 kB | N/A |
| app-route-ex..prod.js gzip | 15.1 kB | 15.1 kB | N/A |
| app-route-tu..prod.js gzip | 15.1 kB | 15.1 kB | N/A |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | N/A |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | N/A |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | N/A |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 22.5 kB | ✓ |
| pages.runtim...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| pages.runtim..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| server.runti..prod.js gzip | 51.1 kB | 51.1 kB | ✓ |
| Overall change | 843 kB | 843 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js 04-06-default_fetchCache_to_force-no-store_when_force-dynamic_is_set | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | ⚠️ +233 B |
| index.pack gzip | 106 kB | 106 kB | N/A |
| Overall change | 1.58 MB | 1.58 MB | ⚠️ +233 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..ntime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-ex..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route-tu..time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>app-route.ru..time.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 4309ac93f17a4cd755cfab58e4ab3a436ea5d5ad

2024-04-08 15:22 UTC, ijjk requested changes
This makes sense to me but holding as discussed

2024-04-12 22:48 UTC, ijjk approved these changes

2024-04-13 17:05 UTC, merged