add node example to open graph image docs
vercel/next.js pull request #64305
Opened 2024-04-10 18:17 UTC by souporserious

### What?

Adds a Node.js example for using assets with `ImageResponse` to create og images.

### Why?

The only examples available use `new URL` and `fetch` which does not work when the runtime is using Node.js.

2024-04-10 18:18 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c2a04704dfac3aa3069b27d65e7d2b810060a275

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-04-15 10:49 UTC, delbaoliveira requested changes
Thank you @souporserious, while we're here, could we also add the Edge runtime example: https://vercel.com/docs/functions/og-image-generation/og-image-examples#using-a-local-image

This is less about the runtime, but more on how to import local images using the different runtimes.

2024-04-15 10:49 UTC, delbaoliveira commented on docs/02-app/02-api-reference/02-file-conventions/01-metadata/opengraph-image.mdx
> +This example uses the Node runtime to fetch a local image on the file system and pass it as an `ArrayBuffer` to an `img` element `src`:
```suggestion
This example uses the Node.js runtime to fetch a local image on the file system and pass it as an `ArrayBuffer` to an `src` attribute of an `<img>` element. 
```

2024-04-15 10:49 UTC, delbaoliveira commented on docs/02-app/02-api-reference/02-file-conventions/01-metadata/opengraph-image.mdx
> +#### Using Node runtime with local assets
```suggestion
#### Using Node.js runtime with local assets
```

2024-04-15 22:13 UTC, souporserious commented
@delbaoliveira yeah, no problem! Updated the examples to showcase Edge runtime as well 😊

2024-04-18 12:49 UTC, delbaoliveira approved these changes
Thank you @souporserious 🙏🏼

2024-04-18 13:23 UTC, merged