add stuff
vercel/next.js pull request #64461
Opened 2024-04-14 09:48 UTC by feedthejim

2024-04-14 09:52 UTC, ijjk commented
## Failing test suites <!--22740143971-->
Commit: 7dee65d7cfbad416fd724ecbcd860af7435b8950

`TURBOPACK=1 pnpm test test/integration/create-next-app/templates/pages.test.ts` (turbopack)
- create-next-app --no-app (Pages Router) > should create JavaScript project with --js flag
- create-next-app --no-app (Pages Router) > should create TypeScript project with --ts flag
- create-next-app --no-app (Pages Router) > should create project inside "src" directory with --src-dir flag
- create-next-app --no-app (Pages Router) > should create TailwindCSS project with --tailwind flag

<details>
<summary>Expand output</summary>

  ● create-next-app --no-app (Pages Router) › should create JavaScript project with --js flag

    FetchError: request to http://localhost:33043/ failed, reason: connect ECONNREFUSED 127.0.0.1:33043

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● create-next-app --no-app (Pages Router) › should create TypeScript project with --ts flag

    FetchError: request to http://localhost:35123/ failed, reason: connect ECONNREFUSED 127.0.0.1:35123

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● create-next-app --no-app (Pages Router) › should create project inside "src" directory with --src-dir flag

    FetchError: request to http://localhost:38749/ failed, reason: connect ECONNREFUSED 127.0.0.1:38749

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

  ● create-next-app --no-app (Pages Router) › should create TailwindCSS project with --tailwind flag

    FetchError: request to http://localhost:37931/ failed, reason: connect ECONNREFUSED 127.0.0.1:37931

      at ClientRequest.<anonymous> (../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js:1491:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-04-14 09:55 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| buildDuration | 14.4s | 14.3s | N/A |
| buildDurationCached | 7.8s | 6.6s | N/A |
| nodeModulesSize | 199 MB | 199 MB | N/A |
| nextStartRea..uration (ms) | 383ms | 406ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| 2453-HASH.js gzip | 31.4 kB | 31.4 kB | N/A |
| 3304.HASH.js gzip | 181 B | 181 B | ✓ |
| 3f784ff6-HASH.js gzip | 53.7 kB | 53.7 kB | ✓ |
| 8299-HASH.js gzip | 5.1 kB | 5.1 kB | N/A |
| framework-HASH.js gzip | 45.2 kB | 45.2 kB | ✓ |
| main-app-HASH.js gzip | 242 B | 242 B | ✓ |
| main-HASH.js gzip | 32.2 kB | 32.2 kB | N/A |
| webpack-HASH.js gzip | 1.68 kB | 1.68 kB | N/A |
| Overall change | 99.3 kB | 99.3 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| _app-HASH.js gzip | 196 B | 197 B | N/A |
| _error-HASH.js gzip | 184 B | 184 B | ✓ |
| amp-HASH.js gzip | 505 B | 505 B | ✓ |
| css-HASH.js gzip | 324 B | 325 B | N/A |
| dynamic-HASH.js gzip | 2.5 kB | 2.5 kB | N/A |
| edge-ssr-HASH.js gzip | 258 B | 258 B | ✓ |
| head-HASH.js gzip | 352 B | 352 B | ✓ |
| hooks-HASH.js gzip | 370 B | 371 B | N/A |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | ✓ |
| index-HASH.js gzip | 259 B | 259 B | ✓ |
| link-HASH.js gzip | 2.67 kB | 2.67 kB | N/A |
| routerDirect..HASH.js gzip | 314 B | 312 B | N/A |
| script-HASH.js gzip | 386 B | 386 B | ✓ |
| withRouter-HASH.js gzip | 309 B | 309 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 6.63 kB | 6.63 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| _buildManifest.js gzip | 483 B | 485 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| index.html gzip | 530 B | 529 B | N/A |
| link.html gzip | 541 B | 541 B | ✓ |
| withRouter.html gzip | 525 B | 523 B | N/A |
| Overall change | 541 B | 541 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| edge-ssr.js gzip | 95.6 kB | 94.5 kB | N/A |
| page.js gzip | 3.06 kB | 3.06 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 625 B | 625 B | ✓ |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 25.5 kB | 25.5 kB | N/A |
| edge-runtime..pack.js gzip | 839 B | 839 B | ✓ |
| Overall change | 1.46 kB | 1.46 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 171 kB | 171 kB | ✓ |
| app-page-exp..prod.js gzip | 97.5 kB | 97.5 kB | ✓ |
| app-page-tur..prod.js gzip | 99.2 kB | 99.2 kB | ✓ |
| app-page-tur..prod.js gzip | 93.5 kB | 93.5 kB | ✓ |
| app-page.run...dev.js gzip | 145 kB | 145 kB | ✓ |
| app-page.run..prod.js gzip | 92 kB | 92 kB | ✓ |
| app-route-ex...dev.js gzip | 21.5 kB | 21.5 kB | ✓ |
| app-route-ex..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 15.2 kB | 15.2 kB | ✓ |
| app-route-tu..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| app-route.ru...dev.js gzip | 21.1 kB | 21.1 kB | ✓ |
| app-route.ru..prod.js gzip | 14.9 kB | 14.9 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 22.5 kB | 21.4 kB | N/A |
| pages.runtim...dev.js gzip | 23.1 kB | 22.1 kB | N/A |
| pages.runtim..prod.js gzip | 22.5 kB | 21.4 kB | N/A |
| server.runti..prod.js gzip | 51.3 kB | 51.3 kB | N/A |
| Overall change | 829 kB | 829 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js feedthejim/pages-render-optimisations | Change |
| - | - | - | - |
| 0.pack gzip | 1.58 MB | 1.58 MB | ⚠️ +340 B |
| index.pack gzip | 106 kB | 107 kB | N/A |
| Overall change | 1.58 MB | 1.58 MB | ⚠️ +340 B |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages-turbo...time.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.dev.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>pages.runtime.prod.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>server.runtime.prod.js</strong></summary>

Diff too large to display
</details>

</details>

</details>
Commit: 7dee65d7cfbad416fd724ecbcd860af7435b8950

2024-04-14 10:20 UTC, shuding commented on packages/next/src/server/render.tsx
> +  const content = prefix + documentResult.contentHTML + renderTargetSuffix
Makes sense!

2024-04-14 10:21 UTC, shuding approved these changes

2024-04-14 21:30 UTC, wyattjoh requested changes, later dismissed

2024-04-14 21:30 UTC, wyattjoh commented on test/unit/isolated/require-page.test.ts
> +    }
This seems wrong, as if `requirePage` does not throw, then this test will still pass. The previous `.toThrow` should be used here.

2024-04-16 07:47 UTC, timneutkens commented on packages/next/webpack.config.js
> +        'renderOpts.dev': JSON.stringify(dev),
This is a bit weird, similarly the `this.serverOptions.experimentalTestProxy` and `this.minimalMode` / `this.renderOpts.dev` are weird too, maybe these should be changed to `process.env.NEXT_INTERNAL_X` instead, not required for this PR though.

2024-04-16 07:47 UTC, timneutkens approved these changes

2024-04-16 12:25 UTC, merged