correctly rethrow instrumentation loading error
vercel/next.js pull request #65251
Opened 2024-05-01 21:02 UTC by iscekic

we can't assume the thrown error will have a settable message property
if we do, we end up with an entirely different error thrown

```
Failed to prepare server TypeError: Cannot set property message of [object Object] which has only a getter
    at NextNodeServer.prepareImpl
```

2024-05-01 21:02 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 85713645e3cb2a2a6023640bdf9345513694c45e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-05-02 05:05 UTC, AbhiShake1 requested changes

2024-05-02 05:05 UTC, AbhiShake1 commented on packages/next/src/server/next-server.ts
> +          throw new Error(`An error occurred while loading the instrumentation hook: ${err}`)
could you add a test to catch this `err` object?

2024-05-02 10:49 UTC, iscekic commented
@AbhiShake1 I don't have the time to get the test suite running normally right now - I did improve the line however, using the [mdn-blessed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) way of rethrowing errors.

2024-05-02 11:46 UTC, AbhiShake1 approved these changes

2024-05-02 11:47 UTC, AbhiShake1 commented
> @AbhiShake1 I don't have the time to get the test suite running locally right now - I did improve the line however, using the [mdn-blessed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) way of rethrowing errors.

That should make it better. Thanks

2024-08-21 16:25 UTC, huozhi approved these changes
`cause` is a good fit here, thanks!

2024-08-21 16:32 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| buildDuration | 18.4s | 15.7s | N/A |
| buildDurationCached | 8.6s | 7.5s | N/A |
| nodeModulesSize | 356 MB | 356 MB | N/A |
| nextStartRea..uration (ms) | 428ms | 430ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| 1921-HASH.js gzip | 37.9 kB | 37.9 kB | N/A |
| 1995.HASH.js gzip | 169 B | 169 B | ✓ |
| 66c22fe9-HASH.js gzip | 51.9 kB | 51.9 kB | N/A |
| 9018-HASH.js gzip | 5.19 kB | 5.19 kB | N/A |
| framework-HASH.js gzip | 56.7 kB | 56.7 kB | ✓ |
| main-app-HASH.js gzip | 224 B | 223 B | N/A |
| main-HASH.js gzip | 32.5 kB | 32.6 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 56.9 kB | 56.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 193 B | N/A |
| _error-HASH.js gzip | 193 B | 192 B | N/A |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 342 B | 342 B | ✓ |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 264 B | N/A |
| head-HASH.js gzip | 363 B | 364 B | N/A |
| hooks-HASH.js gzip | 391 B | 392 B | N/A |
| image-HASH.js gzip | 4.39 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 269 B | 268 B | N/A |
| link-HASH.js gzip | 2.82 kB | 2.81 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 326 B | N/A |
| script-HASH.js gzip | 396 B | 396 B | ✓ |
| withRouter-HASH.js gzip | 325 B | 324 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 748 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| index.html gzip | 521 B | 522 B | N/A |
| link.html gzip | 534 B | 536 B | N/A |
| withRouter.html gzip | 517 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 173 kB | 173 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 667 B | 669 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 29.7 kB | 29.7 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| 928-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 928.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 309 kB | 309 kB | ✓ |
| app-page-exp..prod.js gzip | 122 kB | 122 kB | ✓ |
| app-page-tur..prod.js gzip | 135 kB | 135 kB | ✓ |
| app-page-tur..prod.js gzip | 130 kB | 130 kB | ✓ |
| app-page.run...dev.js gzip | 298 kB | 298 kB | ✓ |
| app-page.run..prod.js gzip | 118 kB | 118 kB | ✓ |
| app-route-ex...dev.js gzip | 30.7 kB | 30.7 kB | ✓ |
| app-route-ex..prod.js gzip | 20.7 kB | 20.7 kB | ✓ |
| app-route-tu..prod.js gzip | 20.7 kB | 20.7 kB | ✓ |
| app-route-tu..prod.js gzip | 20.5 kB | 20.5 kB | ✓ |
| app-route.ru...dev.js gzip | 32.4 kB | 32.4 kB | ✓ |
| app-route.ru..prod.js gzip | 20.5 kB | 20.5 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.62 kB | 9.62 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.5 kB | 11.5 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| pages.runtim...dev.js gzip | 27.5 kB | 27.5 kB | ✓ |
| pages.runtim..prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| server.runti..prod.js gzip | 57 kB | 57 kB | ✓ |
| Overall change | 1.42 MB | 1.42 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | iscekic/next.js correctly-rethrow-instrumentation-load-error | Change |
| - | - | - | - |
| 0.pack gzip | 1.49 MB | 1.49 MB | ⚠️ +1.61 kB |
| index.pack gzip | 126 kB | 127 kB | ⚠️ +241 B |
| Overall change | 1.62 MB | 1.62 MB | ⚠️ +1.85 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 4457: /***/ (
+    /***/ 9810: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-1eaccd82-20240816_re_5yc7ktq4kyrrvzaq2fultvg3y4/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsmd59yI%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-1eaccd82-20240816_re_kxzj53dvrxjpf46fi64kfjrpy4/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsmd59yI%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -66,35 +66,35 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-1eaccd82-20240816_re_5yc7ktq4kyrrvzaq2fultvg3y4/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(7113);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-1eaccd82-20240816_re_5yc7ktq4kyrrvzaq2fultvg3y4/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __web [...]

2024-08-21 22:23 UTC, ijjk approved these changes

2024-08-21 22:34 UTC, merged