chore: Update example to use the correct param
vercel/next.js pull request #65591
Opened 2024-05-09 23:07 UTC by brunorodmoreira

Fix the instructions in https://nextjs.org/docs/messages/middleware-upgrade-guide#no-more-page-match-data. The current `pattern.exec` doesn't contain the correct parameter type and also there's no import of `URLPattern`.

2024-05-09 23:08 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 89f0dc4c85a4b73cd2d0514b4fe12bd80cd66def

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-05-10 22:12 UTC, samcx requested changes

2024-05-10 22:12 UTC, samcx commented on errors/middleware-upgrade-guide.mdx
>      ({ pathname }) => pathname.groups,
We should add a type to `pathname` here too so it's not an `any` type!

2024-06-11 18:15 UTC, samcx commented
@brunorodmoreira Closing due to inactivity! Let me know if you wish to re-open this.

2024-06-11 18:15 UTC, closed without merging