Docs: Add note about Favicon Caching in Vercel
vercel/next.js pull request #65755
Opened 2024-05-14 18:35 UTC by columk1

### What?

This PR adds a note to inform users of Vercel's build cache, which makes it difficult to replace favicon files once deployed.

### Why?

There are many posts about issues replacing favicons on Stack Overflow, Reddit, Github etc. Many solutions involve renaming favicon.ico in the app folder to icon.ico, which works well but it's not clear why from what is said in the docs.  

The docs don't mention that Vercel caches the favicon in the build cache and will not replace the file unless the build cache is invalidated or a different file is pointed to in the metadata.

Using any of the cache invalidation options at the link below will allow a favicon file to be updated after it has been deployed.

https://vercel.com/docs/deployments/troubleshoot-a-build#managing-build-cache

2024-05-14 18:36 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 1a068a3e8f571004e53692aee9c79ca966c51717

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-05-25 21:09 UTC, leerob requested changes
Is there a reproduction for this issue? So you are saying the file itself has changed, but it still cached?

2024-06-04 00:12 UTC, samcx commented
@columk1 I actually came across this issue myself! We should instead look to fix this issue instead of adding it as the expected behavior. We are taking a look!

2024-06-04 10:28 UTC, eps1lon commented
Current thinking is that this is a Next.js bug not a Vercel bug. You should encounter the same problem on any hosting provider with a build cache.

2024-06-06 12:46 UTC, columk1 commented
> @columk1 I actually came across this issue myself! We should instead look to fix this issue instead of adding it as the expected behavior. We are taking a look!

Okay, that makes more sense. Thank you.

2024-06-11 15:19 UTC, closed without merging