Introduce Forbidden and the UI Error abstraction
vercel/next.js pull request #65993
Opened 2024-05-20 18:21 UTC by panteliselef

### Background
[Expanding from this PR](https://github.com/vercel/next.js/pull/63302). This PR is a refactor of the current `notFound()` utility and its dependencies. In order to make future additions easier this PR proposes the concept of a UI Error. UI Errors like `notFound` and `forbidden` provide an isomorphic utility that triggers (throws) the error, but it is handled differently based on context.

### What?

Similar to the notFound() function and the `notFound.js` file, this PR follows the convention and introduces the `forbidden()` function along side the `forbiddden.js` file.

### Why?

While the available `notFound` and `redirect` functions can get you a long way, there is only so much you can do with them.

Developers need a way to handle the authorization state of a user across the multiple "contexts" next has, by that I am referring to components, api routes, and server actions. For this case the `403 Forbidden` status code can be used. 

(We would like to support 401 errors as well)

### How?

As a guide, I used the existing implementation of `notFound` and `redirect`.
- Handle 403 errors in components, api routes, server actions, and parallel routes.
- Handle missing `forbidden` files. In this case we display a default one.
- `ForbiddenErrorBoundary` and `Forbidden` have been introduced in order to catch and display the 403 error.

_To verify that the changes are working the PR includes a minimal set of e2e tests._

### How to use ?

Protect a page from a user who does not have the privilege to access it.

```tsx
// app/team/subscription/page.tsx
import { forbidden } from "next/navigation";

export default function Page(){
  const user = auth() // grap user from headers()

  if(!user.isAdmin) {
    forbidden()
  }

  return <></>;
}

// app/team/subscription/forbidden.tsx
export default function Forbidden(){
  return (
    <>
      <p>Not an admin</p>
     <>
  );
}
```

Protect an API route from a user who does not have the privilege to access it.

```tsx
import { forbidden } from "next/navigation";

export const GET = () => {
  const user = auth() // grap user from headers()

  if(!user.isAdmin) {
    forbidden() // -> Returns a 403 response with empty body
  }
  
  return new Response(JSON.strigify({ hasAccess: true }), {statusCode: 200})
};

```

### What's next 
- [More e2e tests](https://github.com/panteliselef/next.js/pull/3/files) have been written but not pushed in order to make the review easier.
- See how [the unauthorized helper](https://github.com/panteliselef/next.js/pull/2) will look like if this PR is accepted.
- I've added a few comments with questions. I kindly ask the reviewers to take a look at those as they might be important for implementing the feature correctly.

2024-05-20 18:21 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: ae07013b6c650914b745113a91dc43bf30ec7b68

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-05-20 19:00 UTC, ijjk commented
## Failing test suites <!--23981137665-->
Commit: c3baf8be8412ec916f33e6eb90413ed5e974ff17

`TURBOPACK=1 pnpm test-start test/e2e/app-dir/forbidden-default/forbidden-default.test.ts` (turbopack)
- forbidden-default > should be able to navigate to page calling forbidden
- forbidden-default > should be able to navigate to page with calling forbidden in metadata
- forbidden-default > should render default forbidden for group routes if forbidden is not defined

<details>
<summary>Expand output</summary>

  ● forbidden-default › should be able to navigate to page calling forbidden

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      35 |   })
      36 |
    > 37 |   it('should be able to navigate to page calling forbidden', async () => {
         |   ^
      38 |     const browser = await next.browser('/')
      39 |
      40 |     await browser.elementByCss('#navigate-forbidden').click()

      at it (e2e/app-dir/forbidden-default/forbidden-default.test.ts:37:3)
      at Object.describe (e2e/app-dir/forbidden-default/forbidden-default.test.ts:4:1)

  ● forbidden-default › should be able to navigate to page with calling forbidden in metadata

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      47 |   })
      48 |
    > 49 |   it('should be able to navigate to page with calling forbidden in metadata', async () => {
         |   ^
      50 |     const browser = await next.browser('/')
      51 |
      52 |     await browser.elementByCss('#metadata-layout-forbidden').click()

      at it (e2e/app-dir/forbidden-default/forbidden-default.test.ts:49:3)
      at Object.describe (e2e/app-dir/forbidden-default/forbidden-default.test.ts:4:1)

  ● forbidden-default › should render default forbidden for group routes if forbidden is not defined

    thrown: "Exceeded timeout of 60000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      59 |   })
      60 |
    > 61 |   it('should render default forbidden for group routes if forbidden is not defined', async () => {
         |   ^
      62 |     const browser = await next.browser('/group-dynamic/123')
      63 |     expect(await browser.elementByCss('#page').text()).toBe(
      64 |       'group-dynamic [id]'

      at it (e2e/app-dir/forbidden-default/forbidden-default.test.ts:61:3)
      at Object.describe (e2e/app-dir/forbidden-default/forbidden-default.test.ts:4:1)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-05-20 19:01 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| buildDuration | 27.2s | 23.1s | N/A |
| buildDurationCached | 16.1s | 12.6s | N/A |
| nodeModulesSize | 347 MB | 348 MB | ⚠️ +274 kB |
| nextStartRea..uration (ms) | 510ms | 720ms | ⚠️ +210ms |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| 2141-HASH.js gzip | 33.5 kB | 34.1 kB | ⚠️ +629 B |
| 2592-HASH.js gzip | 5.06 kB | 5.06 kB | N/A |
| 48cf7de5-HASH.js gzip | 51 kB | 51 kB | N/A |
| 6539.HASH.js gzip | 169 B | 169 B | ✓ |
| framework-HASH.js gzip | 56 kB | 56 kB | N/A |
| main-app-HASH.js gzip | 219 B | 221 B | N/A |
| main-HASH.js gzip | 32.3 kB | 32.3 kB | N/A |
| webpack-HASH.js gzip | 1.7 kB | 1.7 kB | N/A |
| Overall change | 33.7 kB | 34.3 kB | ⚠️ +629 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 191 B | 192 B | N/A |
| amp-HASH.js gzip | 511 B | 510 B | N/A |
| css-HASH.js gzip | 341 B | 341 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.53 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 266 B | N/A |
| head-HASH.js gzip | 363 B | 365 B | N/A |
| hooks-HASH.js gzip | 392 B | 392 B | ✓ |
| image-HASH.js gzip | 4.27 kB | 4.27 kB | N/A |
| index-HASH.js gzip | 268 B | 266 B | N/A |
| link-HASH.js gzip | 2.69 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 326 B | N/A |
| script-HASH.js gzip | 396 B | 395 B | N/A |
| withRouter-HASH.js gzip | 325 B | 321 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.03 kB | 1.03 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| _buildManifest.js gzip | 481 B | 483 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| index.html gzip | 522 B | 520 B | N/A |
| link.html gzip | 537 B | 534 B | N/A |
| withRouter.html gzip | 518 B | 517 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| edge-ssr.js gzip | 124 kB | 124 kB | N/A |
| page.js gzip | 184 kB | 184 kB | ⚠️ +615 B |
| Overall change | 184 kB | 184 kB | ⚠️ +615 B |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 657 B | 658 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 29.5 kB | 29.5 kB | N/A |
| edge-runtime..pack.js gzip | 1.02 kB | 1.02 kB | ✓ |
| Overall change | 1.02 kB | 1.02 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| app-page-exp...dev.js gzip | 180 kB | 180 kB | ⚠️ +339 B |
| app-page-exp..prod.js gzip | 111 kB | 111 kB | ⚠️ +270 B |
| app-page-tur..prod.js gzip | 120 kB | 121 kB | ⚠️ +273 B |
| app-page-tur..prod.js gzip | 97.7 kB | 98 kB | ⚠️ +290 B |
| app-page.run...dev.js gzip | 163 kB | 163 kB | ⚠️ +340 B |
| app-page.run..prod.js gzip | 96.4 kB | 96.7 kB | ⚠️ +292 B |
| app-route-ex...dev.js gzip | 24.3 kB | 24.5 kB | ⚠️ +185 B |
| app-route-ex..prod.js gzip | 18.2 kB | 18.4 kB | ⚠️ +182 B |
| app-route-tu..prod.js gzip | 18.2 kB | 18.4 kB | ⚠️ +182 B |
| app-route-tu..prod.js gzip | 18 kB | 18.2 kB | ⚠️ +182 B |
| app-route.ru...dev.js gzip | 24.1 kB | 24.3 kB | ⚠️ +185 B |
| app-route.ru..prod.js gzip | 18 kB | 18.2 kB | ⚠️ +182 B |
| pages-api-tu..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.82 kB | 9.82 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.55 kB | 9.55 kB | ✓ |
| pages-turbo...prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| pages.runtim...dev.js gzip | 22 kB | 22 kB | ✓ |
| pages.runtim..prod.js gzip | 21.5 kB | 21.5 kB | ✓ |
| server.runti..prod.js gzip | 52 kB | 52 kB | ✓ |
| Overall change | 1.03 MB | 1.04 MB | ⚠️ +2.9 kB |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | panteliselef/next.js elef/introduce-error-builder | Change |
| - | - | - | - |
| 0.pack gzip | 1.66 MB | 1.68 MB | ⚠️ +21.3 kB |
| index.pack gzip | 129 kB | 129 kB | ⚠️ +880 B |
| Overall change | 1.79 MB | 1.81 MB | ⚠️ +22.2 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 178: /***/ (
+    /***/ 6644: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,12 +30,13 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-beta-04b058868c-20240508_rea_x6nrtfoohwvncerarvzrfulp2u/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsaMlP27%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-beta-04b058868c-20240508_rea_dbavudu66yewnjanau4b4qzpou/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsaMlP27%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
         AppRouter: () => entry_base /* AppRouter */.WY,
         ClientPageRoot: () => entry_base /* ClientPageRoot */.b1,
+        ForbiddenBoundary: () => entry_base /* ForbiddenBoundary */.oe,
         GlobalError: () => error_boundary /* default */.ZP,
         LayoutRouter: () => entry_base /* LayoutRouter */.yO,
         NotFoundBoundary: () => entry_base /* NotFoundBoundary */.O4,
@@ -71,24 +72,24 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-beta-04b058868c-20240508_rea_x6nrt [...]

2024-06-10 14:50 UTC, panteliselef commented
@ijjk Could u approve the CI run ?

2024-06-10 19:00 UTC, panteliselef commented
Hello @ijjk, and sorry for spamming u. I see that the `forbidden` tests fail when run with turbopack, but without it they pass. Any ideas what could be going wrong ?

Locally any test i run with `TURBOPACK=1` or `pnpm test-start-turbo` fails (even on canary, not just this branch). Any hints on how to address that ?

2024-06-11 16:01 UTC, ijjk reviewed
If `next-app-loader` is changed the equivalent handling in turbopack needs to be updated for support there as well. It can be found here https://github.com/vercel/next.js/blob/3cf225c8ee23f707e50292ed25cc227d940012bc/packages/next-swc/crates/next-core/src/app_structure.rs#L798

2024-07-09 14:36 UTC, leerob requested changes
Could we add some documentation here please? 

We'll likely need updates in:

- https://nextjs.org/docs/app/building-your-application/routing/error-handling
- https://nextjs.org/docs/app/api-reference/file-conventions/forbidden (new?)

2024-07-11 12:00 UTC, panteliselef commented
@leerob I'll start working on those.
Seems like https://nextjs.org/docs/app/building-your-application/routing/error-handling does not refer to not-found so probably i can skip that.

Instead i think we need a [similar page](https://nextjs.org/docs/app/api-reference/functions/not-found)  for the `forbidden()` function

2024-07-11 17:15 UTC, gnoff reviewed
So the approach of this PR is to generalize the not found and forbidden in an abstraction but this doesn't quite achieve what I was hoping we could/would. There is still a separate boundary for each of these functions when what we really want to achieve is a single boundary. We also ideally eventually would roll redirect boundary behavior into this component.

I went through the PR with @huozhi and he will end up doing more review and providing additional feedback. But one thing that this PR also needs before we can land is a more comprehensive test suite. The current one doesn't actually use `forbidden.ts` nor does it exercise the new methods in server actions and route handlers.

What I'd like to see is a removal of abstractions rather than the creation of new ones (ui-error-boundary and friends). But maybe before jumping into this work let's give @huozhi a chance to provide guidance or communicate a plan on what we will do internally before/after landing this

2024-07-21 09:59 UTC, panteliselef commented on packages/next/src/client/components/ui-errors-boundaries.tsx
> +}
Combining all boundaries into one should be possible. It's something that I experimented with, but dropped it. It definitely makes sense and I'll include it.

2024-07-21 10:05 UTC, panteliselef commented
Hey @gnoff, thanks for reviewing,  the single boundary makes sense, I'll make this change.

As the I mention in the description, there are more tests available [here](https://github.com/panteliselef/next.js/pull/3/files), I have just not included them in this PR in order to make the review easier, I will include those in this PR shortly. I will also make sure the server actions and route handlers are included.

> What I'd like to see is a removal of abstractions rather than the creation of new ones (ui-error-boundary and friends). But maybe before jumping into this work let's give @huozhi a chance to provide guidance or communicate a plan on what we will do internally before/after landing this.

@huozhi please let me know how to do feel about the "UI error" concept. Should I drop it ? Should we refactor ?

2024-07-21 13:15 UTC, panteliselef commented
@gnoff Regarding the introductions to the Public API with `forbidden()` and `forbidden.jsx|tsx` are we ok ?

2024-09-25 09:55 UTC, huozhi commented
:wave: Hey, thanks for the PR!
We've reviewed the forbidden() API implementation internally, and here are our thoughts:

We noticed some duplication of not-found logic when implementing the new `forbidden()` API. There's a significant potential to reuse underlaying error boundaries and error handling logic from `notFound` to manage the new HTTP errors like 403 `Forbidden` or 401 Unauthorized. We aim for a more lightweight approach that covers both server rendering and also client error boundaries side efficiently.

Currently, the PR encapsulates these errors as UI errors, creating a new layer similar to notFound errors. However, these could be merged into a general error boundary. Additionally, on the server side it's still missing handling for 403 HTTP responses.

Next.js have various scenarios and compositions need to be thoroughly tested, such as dynamic / static rendering, API routes, pages router, PPR, the custom forbidden error boundary `forbidden.js` . The tests from the PR primarily cover the default forbidden, but leaving a few critical scenarios. We assume it requires more refinement and iterations there.

Given these points, we believe it would beneficial if we could take over the work and and refine the implementation later to ensure these HTTP errors handling can be extended in the future effortlessly. I'll get another PR for this feature 🙏 

We greatly appreciate your contribution and your efforts in pushing the standards forward!a

2024-09-25 14:15 UTC, panteliselef commented
Hey @huozhi thanks for the reply. Letting Vercel take the lead on this one makes sense.

A single error boundary was introduced [here](https://github.com/vercel/next.js/pull/65993/commits/0b8a76f1392d09e66bd705e20a5c6c1373960329).

I also never got to push [these](test: Add forbidden e2e test)[test: Add forbidden e2e test](https://github.com/vercel/next.js/pull/65993/commits/54275a32df15c6dd50ffa889ad29fc5823d8fa19) and [these](https://github.com/vercel/next.js/pull/65993/commits/55b1e60fdbac0df6e39c26ba8b7aaa978eeda874) tests, they do cover more cases, but not sure if it's every single one you are interested in.

Will you be interested in opening a GH discussion, and let people have a peek into the API you are thinking of shipping ?

2024-10-01 14:33 UTC, closed without merging