Incremental Static Regeneration - docs update explaining surprising behavior
vercel/next.js pull request #66151
Opened 2024-05-24 00:44 UTC by karlkeefer

The _requirement_ to export a `generateStaticParams` to get static cache behavior _after_ build time was _really_ surprising behavior for me, and I think others:
* https://github.com/vercel/next.js/issues/62195#issuecomment-1952091312
* https://github.com/vercel/next.js/discussions/57961#discussioncomment-8491488

Potentially this is a bug, and not something that should be fixed with documentation?
I don't understand next.js caching enough to make that determination, so instead I'm proposing these changes to docs which might be encountered by folks who are surprised by this cache behavior.

One point in favor of this being a bug: The CLI reports that a route is `SSG` enabled in the build output, but doesn't actually cache post-build page renders if this export is missing.

@awinogrodzki made a demo repo showing this behavior, as described [here](https://github.com/vercel/next.js/discussions/57961#discussioncomment-7468144).

2024-05-24 00:44 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: c0505afb7b3c39ecbe35cc3aaf278285e6fbf9b2

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-06-04 20:55 UTC, samcx approved these changes
Thank you for submitting a PR!

<picture data-single-emoji=":lgtm:" title=":lgtm:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lgtm/8755dd1e0f708009.png" alt=":lgtm:" align="absmiddle"></picture>.

> One point in favor of this being a bug: The CLI reports that a route is SSG enabled in the build output, but doesn't actually cache post-build page renders if this export is missing.

Good callout! We need to I think we need to improve our CLI output here.

> The requirement to export a generateStaticParams to get static cache behavior after build time was really surprising behavior for me, and I think others:

Hmm, maybe somewhat! The behavior is similar to Pages Router—if you only had a dynamic page, it would not opt you into ISR—you would have to use `getStaticPath`s. Similarly, you have to use `generateStaticParams` here.

A possible discussion to have is whether `revalidate` should just enable it, without an empty `generateStaticParams`. <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>

2024-06-05 02:47 UTC, leerob requested changes, later dismissed
Would love to get @delbaoliveira's opinion here before merging 🙏

2024-06-05 06:37 UTC, karlkeefer commented
@samcx I think my confusion here may stem from he fact that I didn't use pages router before.

As more folks use next-js after app router is the recommended default, the level of surprise among users may rise ;)

Thanks for taking a look at the PR 🙌

2024-06-05 06:42 UTC, samcx commented
> As more folks use next-js after app router is the recommended default, the level of surprise among users may rise ;)

@karlkeefer Makes sense and noted! We are working to improve the App Router's caching story which will most likely improving the Route Segment Config, so we could end up improving this to cause less confusion.

I'll defer to Delba for further review on this <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>  <picture data-single-emoji=":blob_bowing:" title=":blob_bowing:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/blob_bowing/3e13f8dbc67a5ea6.png" alt=":blob_bowing:" align="absmiddle"></picture>

2024-06-07 15:48 UTC, delbaoliveira requested changes

2024-06-07 15:48 UTC, delbaoliveira commented on docs/02-app/02-api-reference/02-file-conventions/route-segment-config.mdx
> +> - Even though this defaults to true, your pages won't be cached unless your layout or page also makes use of `generateStaticParams`, even if it only returns an empty array.
```suggestion
> - To statically render all paths the first time they're visited, you'll need to return an empty array in `generateStaticParams`. 
```

2024-06-07 15:48 UTC, delbaoliveira commented on docs/02-app/02-api-reference/04-functions/generate-static-params.mdx
> +> - You must include `generateStaticParams` even if you only want pages to be cached *after* build time.
```suggestion
> - You must include `generateStaticParams` with an [empty array](#all-paths-at-runtime) if you want to statically render all paths at runtime. 
```

2024-06-07 15:50 UTC, delbaoliveira commented
Thank you for raising this @karlkeefer, I've pushed a commit to rephrase a few things. 

@samcx maybe not supplying `generateStaticParams` should be the equivalent of supplying an empty array. But I'll defer that to your team :)

2024-06-10 14:24 UTC, delbaoliveira approved these changes

2024-06-10 15:41 UTC, samcx approved these changes

2024-06-10 15:48 UTC, merged

2024-06-12 21:49 UTC, rijk commented
> A possible discussion to have is whether revalidate should just enable it, without an empty generateStaticParams. :frog-eyes:

Or setting `export const dynamic = 'force-static'`. Having those options available but not actually making a route static, unless you add a `generateStaticParams` function that returns an empty array is the kind of DX that makes someone lose their mind.

2024-06-14 18:49 UTC, samcx commented
@rijk Thanks for the feedback!

Actually not 100% with `export const dynamic = 'force-static`—taking a look <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>

2024-06-20 09:18 UTC, samcx commented
@rijk It turns out you can use `force-static`! I'll be updating our <picture data-single-emoji=":nextjs-spin:" title=":nextjs-spin:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs-spin/44e0f484b546dd9d.gif" alt=":nextjs-spin:" align="absmiddle"></picture> <picture data-single-emoji=":docs:" title=":docs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/docs/172e1b9b7d137b8a.png" alt=":docs:" align="absmiddle"></picture> again <picture data-single-emoji=":blob_bowing:" title=":blob_bowing:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/blob_bowing/3e13f8dbc67a5ea6.png" alt=":blob_bowing:" align="absmiddle"></picture>