fix hreflang is wrong in head displayed as hrefLang
vercel/next.js pull request #66983
Opened 2024-06-18 09:07 UTC by jillsomer

setting `alternates` `languages` results in `<link rel="alternate" hrefLang="en" ` output it should be `hreflang` google complains about this in lighthouse

2024-06-18 09:07 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f3672d3bd0310f91cbab04b6a1e561e431eda565

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-06-18 09:07 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: f3672d3bd0310f91cbab04b6a1e561e431eda565

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-06-18 13:29 UTC, Netail commented
Some tests need to be adjusted for this change

2024-06-26 10:50 UTC, eps1lon requested changes
Thank you.

Looks like this needs adjustments to types. Ideally we already have a test for this that needs adjustments. If not, please add one.

2024-09-16 09:30 UTC, hdodov commented
This is related to https://github.com/vercel/next.js/discussions/39226, for reference.

2024-09-16 14:32 UTC, Netail commented
Shouldn't react handle these camelCase attributes? 

fyi; the AlternateLink component uses a type from @types/react, which uses camelcase too

2024-09-16 17:16 UTC, Netail commented
Related; https://github.com/vercel/next.js/issues/58700

2025-03-03 18:00 UTC, ijjk requested changes
Hi, as mentioned above this is a react issue and not Next.js specific, if we land this as is it will have warnings and such that can't be resolved without upstream fix. 

We will need to investigate this in react itself to properly resolve.

2025-03-03 18:00 UTC, closed without merging

2025-03-04 05:00 UTC, falihnaufal17 commented
> Hi, as mentioned above this is a react issue and not Next.js specific, if we land this as is it will have warnings and such that can't be resolved without upstream fix.
> 
> We will need to investigate this in react itself to properly resolve.

so, is there any alternative action items for us to solve this hrefLang issue?

2025-03-04 17:47 UTC, ijjk commented
I would encourage following up with the above linked react issue or creating a new one there with additional context. It seems the actual crawlers/parsers that aren't handling `hrefLang` haven't been identified which is also important.