Bump cookie and type to 0.6.0
vercel/next.js pull request #67360
Opened 2024-07-01 22:31 UTC by torresgol10

Bump `cookie` and `@types/cookie` to 0.6.0, The updated version has speed improvements

2024-07-01 22:31 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: fa9ceba26e62ef9e5f5c692102881778e20fa3a8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-01 22:31 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: fa9ceba26e62ef9e5f5c692102881778e20fa3a8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-10-07 21:03 UTC, CopyJosh commented
If bumping, this may need to be bumped further to at least `0.7.0` but preferably to `0.7.2` because of some [fixes](https://github.com/jshttp/cookie/releases)

https://avd.aquasec.com/nvd/2024/cve-2024-47764/

2024-10-07 22:11 UTC, torresgol10 commented
Thanks @CopyJosh for the security warning, this PR is already updated, pls @ijjk  can you check it?

2024-10-09 00:26 UTC, ijjk reviewed
Same as https://github.com/vercel/next.js/pull/68134#pullrequestreview-2355743557

2024-10-10 19:02 UTC, torresgol10 commented
I think it is ready

2024-10-12 02:52 UTC, ijjk commented
## Failing test suites <!--29533102281-->
Commit: 04f1c21f1eb17feef9e4ba307f7854a6b03e1f29

`pnpm test test/unit/split-cookies-string.test.ts`
- splitCookiesString > with a multiple cookies > should parse with all the options
- splitCookiesString > with a single cookie > should parse with all the options

<details>
<summary>Expand output</summary>

  ● splitCookiesString › with a single cookie › should parse with all the options

    TypeError: option domain is invalid

      5 |  * Copyright(c) 2015 Douglas Christopher Wilson
      6 |  * MIT Licensed
    > 7 |  */r.parse=parse;r.serialize=serialize;var i=Object.prototype.toString;var t=Object.prototype.hasOwnProperty;var a=/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;var n=/^("?)[\u0021\u0023-\u002B\u002D-\u003A\u003C-\u005B\u005D-\u007E]*\1$/;var o=/^([.]?[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$/i;var s=/^[\u0020-\u003A\u003D-\u007E]*$/;function parse(e,r){if(typeof e!=="string"){throw new TypeError("argument str must be a string")}var i={};var a=e.length;if(a<2)return i;var n=r&&r.decode||decode;var o=0;var s=0;var d=0;do{s=e.indexOf("=",o);if(s===-1)break;d=e.indexOf(";",o);if(d===-1){d=a}else if(s>d){o=e.lastIndexOf(";",s-1)+1;continue}var u=startIndex(e,o,s);var p=endIndex(e,s,u);var f=e.slice(u,p);if(!t.call(i,f)){var c=startIndex(e,s+1,d);var v=endIndex(e,d,c);if(e.charCodeAt(c)===34&&e.charCodeAt(v-1)===34){c++;v--}var l=e.slice(c,v);i[f]=tryDecode(l,n)}o=d+1}while(o<a);return i}function startIndex(e,r,i){do{var t=e.charCodeAt(r);if(t!==32&&t!==9)return r}while(++r<i);return i}function endIndex(e,r,i){while(r>i){var t=e.charCodeAt(--r);if(t!==32&&t!==9)return r+1}return i}function serialize(e,r,i){var t=i&&i.encode||encodeURIComponent;if(typeof t!=="function"){throw new TypeError("option encode is invalid")}if(!a.test(e)){throw new TypeError("argument name is invalid")}var d=t(r);if(!n.test(d)){throw new TypeError("argument val is invalid")}var u=e+"="+d;if(!i)return u;if(null!=i.maxAge){var p=Math.floor(i.maxAge);if(!isFinite(p)){throw new TypeError("option maxAge is invalid")}u+="; Max-Age="+p}if(i.domain){if(!o.test(i.domain)){throw new TypeError("option domain is invalid")}u+="; Domain="+i.domain}if(i.path){if(!s.test(i.path)){throw new TypeError("option path is invalid")}u+="; Path="+i.path}if(i.expires){var f=i.expires;if(!isDate(f)||isNaN(f.valueOf())){throw new TypeError("option expires is invalid")}u+="; Expires="+f.toUTCString()}if(i.httpOnly){u+="; HttpOnly"}if(i.secure){u+="; Secure"}if(i.partitioned){u+="; Partitioned"}if(i.priority){var c=typeof i.priority==="string"?i.priority.toLowerCase():i.priority;switch(c){case"low":u+="; Priority=Low";break;case"medium":u+="; Priority=Medium";break;case"high":u+="; Priority=High";break;default:throw new TypeError("option priority is invalid")}}if(i.sameSite){var v=typeof i.sameSite==="string"?i.sameSite.toLowerCase():i.sameSite;switch(v){case true:u+="; SameSite=Strict";break;case"lax":u+="; SameSite=Lax";break;case"strict":u+="; SameSite=Strict";break;case"none":u+="; SameSite=None";break;default:throw new TypeError("option sameSite is invalid")}}return u}function decode(e){return e.indexOf("%")!==-1?decodeURIComponent(e):e}function isDate(e){return i.call(e)==="[object Date]"}function tryDecode(e,r){try{return r(e)}catch(r){return e}}})();module.exports=e})();
        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^

      at Object.serialize (../packages/next/dist/compiled/cookie/index.js:7:1589)
      at serialize (unit/split-cookies-string.test.ts:9:12)
          at Array.map (<anonymous>)
      at map (unit/split-cookies-string.test.ts:8:33)
      at Object.generateCookies (unit/split-cookies-string.test.ts:59:36)

  ● splitCookiesString › with a multiple cookies › should parse with all the options

    TypeError: option domain is invalid

      5 |  * Copyright(c) 2015 Douglas Christopher Wilson
      6 |  * MIT Licensed
    > 7 |  */r.parse=parse;r.serialize=serialize;var i=Object.prototype.toString;var t=Object.prototype.hasOwnProperty;var a=/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;var n=/^("?)[\u0021\u0023-\u002B\u002D-\u003A\u003C-\u005B\u005D-\u007E]*\1$/;var o=/^([.]?[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$/i;var s=/^[\u0020-\u003A\u003D-\u007E]*$/;function parse(e,r){if(typeof e!=="string"){throw new TypeError("argument str must be a string")}var i={};var a=e.length;if(a<2)return i;var n=r&&r.decode||decode;var o=0;var s=0;var d=0;do{s=e.indexOf("=",o);if(s===-1)break;d=e.indexOf(";",o);if(d===-1){d=a}else if(s>d){o=e.lastIndexOf(";",s-1)+1;continue}var u=startIndex(e,o,s);var p=endIndex(e,s,u);var f=e.slice(u,p);if(!t.call(i,f)){var c=startIndex(e,s+1,d);var v=endIndex(e,d,c);if(e.charCodeAt(c)===34&&e.charCodeAt(v-1)===34){c++;v--}var l=e.slice(c,v);i[f]=tryDecode(l,n)}o=d+1}while(o<a);return i}function startIndex(e,r,i){do{var t=e.charCodeAt(r);if(t!==32&&t!==9)return r}while(++r<i);return i}function endIndex(e,r,i){while(r>i){var t=e.charCodeAt(--r);if(t!==32&&t!==9)return r+1}return i}function serialize(e,r,i){var t=i&&i.encode||encodeURIComponent;if(typeof t!=="function"){throw new TypeError("option encode is invalid")}if(!a.test(e)){throw new TypeError("argument name is invalid")}var d=t(r);if(!n.test(d)){throw new TypeError("argument val is invalid")}var u=e+"="+d;if(!i)return u;if(null!=i.maxAge){var p=Math.floor(i.maxAge);if(!isFinite(p)){throw new TypeError("option maxAge is invalid")}u+="; Max-Age="+p}if(i.domain){if(!o.test(i.domain)){throw new TypeError("option domain is invalid")}u+="; Domain="+i.domain}if(i.path){if(!s.test(i.path)){throw new TypeError("option path is invalid")}u+="; Path="+i.path}if(i.expires){var f=i.expires;if(!isDate(f)||isNaN(f.valueOf())){throw new TypeError("option expires is invalid")}u+="; Expires="+f.toUTCString()}if(i.httpOnly){u+="; HttpOnly"}if(i.secure){u+="; Secure"}if(i.partitioned){u+="; Partitioned"}if(i.priority){var c=typeof i.priority==="string"?i.priority.toLowerCase():i.priority;switch(c){case"low":u+="; Priority=Low";break;case"medium":u+="; Priority=Medium";break;case"high":u+="; Priority=High";break;default:throw new TypeError("option priority is invalid")}}if(i.sameSite){var v=typeof i.sameSite==="string"?i.sameSite.toLowerCase():i.sameSite;switch(v){case true:u+="; SameSite=Strict";break;case"lax":u+="; SameSite=Lax";break;case"strict":u+="; SameSite=Strict";break;case"none":u+="; SameSite=None";b [...]

2024-10-12 02:53 UTC, ijjk approved these changes, later dismissed

2024-10-12 02:56 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| buildDuration | 20.2s | 17.2s | N/A |
| buildDurationCached | 16.4s | 14.2s | N/A |
| nodeModulesSize | 371 MB | 371 MB | ⚠️ +123 kB |
| nextStartRea..uration (ms) | 452ms | 442ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| 4053-HASH.js gzip | 5.27 kB | 5.27 kB | ✓ |
| 6569-HASH.js gzip | 43.7 kB | 43.7 kB | N/A |
| 6f96a7ca-HASH.js gzip | 52.6 kB | 52.6 kB | N/A |
| 7653.HASH.js gzip | 169 B | 169 B | ✓ |
| framework-HASH.js gzip | 57.4 kB | 57.4 kB | N/A |
| main-app-HASH.js gzip | 235 B | 233 B | N/A |
| main-HASH.js gzip | 32.8 kB | 32.8 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 5.44 kB | 5.44 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| _app-HASH.js gzip | 194 B | 193 B | N/A |
| _error-HASH.js gzip | 191 B | 192 B | N/A |
| amp-HASH.js gzip | 509 B | 511 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 266 B | 265 B | N/A |
| head-HASH.js gzip | 365 B | 364 B | N/A |
| hooks-HASH.js gzip | 392 B | 392 B | ✓ |
| image-HASH.js gzip | 4.4 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 269 B | 268 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.77 kB | N/A |
| routerDirect..HASH.js gzip | 327 B | 328 B | N/A |
| script-HASH.js gzip | 396 B | 395 B | N/A |
| withRouter-HASH.js gzip | 323 B | 324 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 498 B | 498 B | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| _buildManifest.js gzip | 748 B | 749 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| index.html gzip | 519 B | 523 B | N/A |
| link.html gzip | 533 B | 537 B | N/A |
| withRouter.html gzip | 514 B | 518 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 130 kB | ⚠️ +327 B |
| page.js gzip | 188 kB | 188 kB | ⚠️ +347 B |
| Overall change | 317 kB | 318 kB | ⚠️ +674 B |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 667 B | 671 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 30.7 kB | 31 kB | ⚠️ +338 B |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 31.7 kB | 32 kB | ⚠️ +338 B |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 313 kB | 313 kB | ⚠️ +348 B |
| app-page-exp..prod.js gzip | 120 kB | 120 kB | ⚠️ +339 B |
| app-page-tur..prod.js gzip | 133 kB | 134 kB | ⚠️ +349 B |
| app-page-tur..prod.js gzip | 128 kB | 129 kB | ⚠️ +334 B |
| app-page.run...dev.js gzip | 304 kB | 304 kB | ⚠️ +318 B |
| app-page.run..prod.js gzip | 115 kB | 116 kB | ⚠️ +330 B |
| app-route-ex...dev.js gzip | 35 kB | 35.3 kB | ⚠️ +349 B |
| app-route-ex..prod.js gzip | 23.6 kB | 24 kB | ⚠️ +358 B |
| app-route-tu..prod.js gzip | 23.7 kB | 24 kB | ⚠️ +358 B |
| app-route-tu..prod.js gzip | 23.4 kB | 23.8 kB | ⚠️ +352 B |
| app-route.ru...dev.js gzip | 36.6 kB | 36.9 kB | ⚠️ +346 B |
| app-route.ru..prod.js gzip | 23.4 kB | 23.8 kB | ⚠️ +352 B |
| pages-api-tu..prod.js gzip | 9.61 kB | 9.93 kB | ⚠️ +313 B |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.8 kB | ⚠️ +343 B |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.92 kB | ⚠️ +313 B |
| pages-turbo...prod.js gzip | 20.9 kB | 21.2 kB | ⚠️ +330 B |
| pages.runtim...dev.js gzip | 26.5 kB | 26.9 kB | ⚠️ +344 B |
| pages.runtim..prod.js gzip | 20.9 kB | 21.2 kB | ⚠️ +330 B |
| server.runti..prod.js gzip | 59.7 kB | 60.1 kB | ⚠️ +358 B |
| Overall change | 1.44 MB | 1.45 MB | ⚠️ +6.46 kB |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | torresgol10/next.js bump-cookie-next | Change |
| - | - | - | - |
| 0.pack gzip | 1.84 MB | 1.85 MB | ⚠️ +3.95 kB |
| index.pack gzip | 143 kB | 142 kB | N/A |
| Overall change | 1.84 MB | 1.85 MB | ⚠️ +3.95 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 6683: /***/ (
+    /***/ 9977: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-70fb1363-20241010_re_ej6p4ob2iqs5g3c6x2lcn37z5e/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsLzGVES%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-70fb1363-20241010_re_5nmd7l34pjgqifaws33tkiz5ni/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsLzGVES%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -80,35 +80,35 @@
         workUnitAsyncStorage: () => entry_base /* workUnitAsyncStorage */.Sz,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-70fb1363-20241010_re_ej6p4ob2iqs5g3c6x2lcn37z5e/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(5521);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-70fb1363-20241010_re_ [...]

2024-11-22 11:14 UTC, torresgol10 commented
Hi @ijjk , I had to upgrade to the latest version of “cookie”, it already integrates the “type” into the dependency so I deleted “@types/cookie”.

I have reworked the files to use the new type.

The test that was failing is because it is not a domain, it was passing a “URL”, I have changed it to a domain.

2024-11-22 15:30 UTC, CopyJosh commented
Just as another note, in case it's not a given for those of us not able to update to Next 15 yet, may I request that this could be bumped onto Next 14 too plz?

2025-01-03 19:17 UTC, torresgol10 commented
@ijjk  @samcx @timneutkens Can this be accelerated?

I think it's important, try to merge it but every time I log in there is always conclicto, the resuelvos but never merge.

If I solve the conclusions, will it merge fast?

2025-01-03 19:35 UTC, samcx commented
@torresgol10 Unfortunately, conflicts will happen, especially since it's been some time. Is it possible to try fixing the conflicts again?

2025-01-03 19:37 UTC, torresgol10 commented
Hi @samcx, Thank you very much, I'll get to work on resolving the issues.

2025-01-06 20:02 UTC, torresgol10 commented
@samcx  Everything is already updated

2025-01-06 21:12 UTC, ijjk commented
## Failing test suites <!--32738389820-->
Commit: 9e55ee9d1d16c25bb1eb8f70e18d8599d4f8b7a9

`pnpm test test/integration/typescript/test/index.test.js` (turbopack)
- TypeScript Features > default behavior > should render the cookies page with cookies

<details>
<summary>Expand output</summary>

  ● TypeScript Features › default behavior › should render the cookies page with cookies

    expect(received).toBe(expected) // Object.is equality

    Expected: "{\"key\":\"value\"}"
    Received: ""

      60 |         }
      61 |       )
    > 62 |       expect($('#cookies').text()).toBe(`{"key":"value"}`)
         |                                    ^
      63 |     })
      64 |
      65 |     it('should render the generics page', async () => {

      at Object.toBe (integration/typescript/test/index.test.js:62:36)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2025-01-06 21:24 UTC, ijjk requested changes
It looks like there are still failing tests with this change: https://github.com/vercel/next.js/actions/runs/12640352702/job/35220704277?pr=67360#step:29:210

2025-01-08 19:52 UTC, samcx commented
@torresgol10 When you run the `pnpm types-and-precompiled` command, you come across this error.

```
Error: test/unit/split-cookies-string.test.ts(1,15): error TS2305: Module '"next/dist/compiled/cookie"' has no exported member 'SerializeOptions'.
Error: test/unit/split-cookies-string.test.ts(3,10): error TS2305: Module '"next/dist/compiled/cookie"' has no exported member 'serialize'.
```

2025-01-08 19:53 UTC, torresgol10 commented
@samcx  I'm working on this right now

2025-01-08 21:37 UTC, torresgol10 commented
@samcx I have already solved the previous error, I have installed the same version of “cookie” in the root as in “next”, so the error was removed, but when I run the command that you told me, I have other errors that are not produced by my change for example an error “error TS2305: Module ‘”next/dist/server/web/spec-extension/revalidate“’ has no exported member ‘unstable_expirePath’”.

2025-01-09 12:05 UTC, torresgol10 commented
Hi @samcx, I have already detected solved the main problem, the problem was that “cookie” now checks that the “maxAge” is an int, and in the test it was a string, when checking it and using the cookie.parse.

Before making the checks we convert it to the format we need.

2025-01-10 19:17 UTC, torresgol10 commented
@samcx  I see there is a new error in another test, I start working on it

2025-03-24 19:02 UTC, torresgol10 commented
Hi @samcx , I could not solve it but I think it is important to finish it, could you help me.

2025-11-23 20:57 UTC, closed without merging