Add --no-subfolders argument to next export
vercel/next.js pull request #6752
Opened 2019-03-22 12:40 UTC by martpie

Fix #5955

This is a WIP

- [x] make it work
- [ ] next.config.js support
- [ ] documentation update
- [ ] add tests

This Pull Requests add a `--no-subfolders` argument to `next export`:

Let's take this tree of pages:

```
pages/
├── posts/
│   ├── index.js
│   └── single.js
├── index.js
└── about.js
```

### `next export` result

```
out/
├── about/
│   └── index.html
├── posts/
│   ├── single/
│   │      └── index.html
│   └── index.html
└── index.html

```

### `next export --no-subfolders`

```
out/
├── posts/
│   └── single.html
├── about.html
├── index.html
└── posts.html
```

## What does it solve?

On Caddy or Netlify, the default routing/try_files is quite opinionated compared to solutions like nginx. When trying to access `/about` on a classic Next.js export with these services, the user is actually redirected to:

<img width="374" alt="Screen Shot 2019-03-22 at 12 08 34" src="https://user-images.githubusercontent.com/1311607/54823243-8704d100-4ca7-11e9-86d9-45e532de5243.png">

This is bad for canonical links, SEO, and it triggers my OCD a lot.

Nuxt.js faced this problem and fixed it with the `generate.subFolders` option in `nuxt.config.js`: https://nuxtjs.org/api/configuration-generate#subfolders

This solution is heavily inspired by it.

---

This is a proof of concept, I will be happy to change the naming and continue to add tests and documentation once I get the approval of one of the maintainers of Next.js.

2019-03-22 12:42 UTC, timneutkens commented
This is sort of the same as https://github.com/zeit/next.js/pull/6664 right?

2019-03-22 12:44 UTC, timneutkens commented
@Timer what do you think?

2019-03-22 12:54 UTC, martpie commented
I did not know #6664, if a flag already exists, I should use this one indeed. Should I remove the CLI flag as well then, and only base this feature on `next.config.js`'s `experimental.exportTrailingSlash`? (though the naming of this flag feels weird now)

2019-03-22 13:29 UTC, timneutkens requested changes
Let's keep it under `experimental.exportTrailingSlash` for now as the option will be the default in the next major release. No need for a cli flag.

2019-03-25 09:47 UTC, martpie commented
Should I wait for @Timer's feedback or can I start editing the docs and tests?

2019-03-25 10:15 UTC, timneutkens commented
@martpie you can implement it, I've already discussed it with @Timer, I think he forgot to ping back here 👍

2019-04-12 09:18 UTC, martpie commented
Et voilà, documentation updated and tests added. @Timer @timneutkens

2019-04-13 11:28 UTC, timneutkens approved these changes
Looks fine to me! @Timer will have the final call 👌

2019-04-22 16:55 UTC, merged

2019-04-22 16:55 UTC, timneutkens commented
Thanks!

2019-04-23 09:54 UTC, iamstarkov commented
what I the default value?

2019-04-23 11:24 UTC, martpie commented
The default value is true. You have to set it to `false` to make it work.

2019-04-23 11:31 UTC, iamstarkov commented
ok, thank you