Update head.mdx, remove `or wrapped into maximum one level of `<React.Fragment>`
vercel/next.js pull request #67667
Opened 2024-07-11 13:46 UTC by dimaMachina

one-level fragments don't work, only arrays

2024-07-11 13:46 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 7d186b11ca5096da3fec859546182986e64b6d6b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-11 13:46 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 7d186b11ca5096da3fec859546182986e64b6d6b

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-11 13:48 UTC, dimaMachina commented on docs/03-pages/02-api-reference/01-components/head.mdx
> +or arrays—otherwise the tags won't be correctly picked up on client-side navigations.
```suggestion
or arrays — otherwise the tags won't be correctly picked up on client-side navigations.
```

2024-07-11 14:25 UTC, eps1lon reviewed
Could you check if we have tests for those scenario that highlight that Fragments don't work?

2024-09-16 20:33 UTC, ijjk requested changes
One level of fragment is supposed to be supported and we have a related test for it here https://github.com/vercel/next.js/blob/canary/test/development/pages-dir/client-navigation/rendering.test.ts#L62

2024-09-16 20:33 UTC, closed without merging