refactor(webpack/loaders): replace `indexOf === 0` with `startsWith`
vercel/next.js pull request #68116
Opened 2024-07-24 15:52 UTC by Juneezee

It is more readable to call `startsWith` than to call `indexOf === 0` and compare the result with zero to determine whether a string starts with a given prefix.

Only these 4 lines of code still call `indexOf === 0`.

2024-07-24 15:53 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 0bce62b045b684d0a2d2b1371509ddda89eb90a9

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-08-01 04:33 UTC, Juneezee commented
friendly ping @ijjk @samcx

2024-08-01 08:22 UTC, imranbarbhuiya requested changes
nvm, just tested. there's not much diff

2024-08-01 19:54 UTC, samcx approved these changes

2024-08-01 20:00 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| buildDuration | 17.8s | 15s | N/A |
| buildDurationCached | 8.5s | 7.5s | N/A |
| nodeModulesSize | 353 MB | 353 MB | N/A |
| nextStartRea..uration (ms) | 424ms | 436ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| 2318-HASH.js gzip | 5.19 kB | 5.19 kB | ✓ |
| 4701-HASH.js gzip | 37.3 kB | 37.3 kB | N/A |
| 5054.HASH.js gzip | 168 B | 169 B | N/A |
| 6052e2ca-HASH.js gzip | 51.9 kB | 51.9 kB | N/A |
| framework-HASH.js gzip | 56.8 kB | 56.8 kB | ✓ |
| main-app-HASH.js gzip | 224 B | 224 B | ✓ |
| main-HASH.js gzip | 32.1 kB | 32.1 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 62.2 kB | 62.2 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 192 B | N/A |
| _error-HASH.js gzip | 193 B | 192 B | N/A |
| amp-HASH.js gzip | 512 B | 509 B | N/A |
| css-HASH.js gzip | 342 B | 343 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 364 B | 365 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.39 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 268 B | 269 B | N/A |
| link-HASH.js gzip | 2.81 kB | 2.81 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 396 B | 394 B | N/A |
| withRouter-HASH.js gzip | 324 B | 324 B | ✓ |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.02 kB | 1.02 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 749 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| index.html gzip | 520 B | 522 B | N/A |
| link.html gzip | 534 B | 537 B | N/A |
| withRouter.html gzip | 519 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| edge-ssr.js gzip | 127 kB | 127 kB | N/A |
| page.js gzip | 168 kB | 168 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 666 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 29.6 kB | 29.6 kB | N/A |
| edge-runtime..pack.js gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 1.18 kB | 1.18 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| 928-experime...dev.js gzip | 310 B | 310 B | ✓ |
| 928.runtime.dev.js gzip | 301 B | 301 B | ✓ |
| app-page-exp...dev.js gzip | 236 kB | 236 kB | N/A |
| app-page-exp..prod.js gzip | 120 kB | 120 kB | ✓ |
| app-page-tur..prod.js gzip | 132 kB | 132 kB | ✓ |
| app-page-tur..prod.js gzip | 128 kB | 128 kB | ✓ |
| app-page.run...dev.js gzip | 231 kB | 231 kB | N/A |
| app-page.run..prod.js gzip | 117 kB | 117 kB | ✓ |
| app-route-ex...dev.js gzip | 23.1 kB | 23.1 kB | ✓ |
| app-route-ex..prod.js gzip | 18.8 kB | 18.8 kB | ✓ |
| app-route-tu..prod.js gzip | 18.8 kB | 18.8 kB | ✓ |
| app-route-tu..prod.js gzip | 18.6 kB | 18.6 kB | ✓ |
| app-route.ru...dev.js gzip | 24.4 kB | 24.4 kB | ✓ |
| app-route.ru..prod.js gzip | 18.6 kB | 18.6 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.6 kB | 9.6 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.87 kB | 9.87 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.59 kB | 9.59 kB | ✓ |
| pages-turbo...prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| pages.runtim...dev.js gzip | 22.2 kB | 22.2 kB | ✓ |
| pages.runtim..prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| server.runti..prod.js gzip | 56.7 kB | 56.7 kB | ✓ |
| Overall change | 771 kB | 771 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | Juneezee/next.js refactor/replace-indexOf-with-startsWith | Change |
| - | - | - | - |
| 0.pack gzip | 1.42 MB | 1.42 MB | ⚠️ +1.06 kB |
| index.pack gzip | 121 kB | 121 kB | ⚠️ +773 B |
| Overall change | 1.54 MB | 1.54 MB | ⚠️ +1.83 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 5195: /***/ (
+    /***/ 6585: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3208e73e-20240730_re_s3gitrr3qfayhaiqo6mg4kjsm4/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsxcPLMi%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3208e73e-20240730_re_glzdnwncgtmzypiltvd7r6clfq/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsxcPLMi%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -69,35 +69,35 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3208e73e-20240730_re_s3gitrr3qfayhaiqo6mg4kjsm4/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(5734);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3208e73e-20240730_re_s3gitrr3qfayhaiqo6mg4kjsm4/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __webpack_require__(8258);
 [...]

2024-08-01 21:36 UTC, merged