handle empty query param issue in url redirects #68039
vercel/next.js pull request #68157
Opened 2024-07-25 12:44 UTC by archanaagivale30

Empty Query Param in redirect url causes 500 error issue #68039 .
Fixed issue #68039 .
Also added test case for same.

cc @samcx

2024-07-25 12:44 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: e9067d1f1c1899520c07adfb27e6dc66129dd087

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-31 00:07 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| buildDuration | 16.6s | 34.8s | ⚠️ +18.2s |
| buildDurationCached | 9.7s | 7.9s | N/A |
| nodeModulesSize | 357 MB | 369 MB | ⚠️ +11.7 MB |
| nextStartRea..uration (ms) | 426ms | 425ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| 1780.HASH.js gzip | 167 B | 167 B | ✓ |
| 5453-HASH.js gzip | 37.5 kB | N/A | N/A |
| 7514-HASH.js gzip | 5.19 kB | 5.05 kB | N/A |
| a7a62840-HASH.js gzip | 51.9 kB | 51.7 kB | N/A |
| framework-HASH.js gzip | 56.7 kB | 56.7 kB | N/A |
| main-app-HASH.js gzip | 225 B | 226 B | N/A |
| main-HASH.js gzip | 32.1 kB | 32 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.77 kB | N/A |
| 8268-HASH.js gzip | N/A | 82.2 kB | N/A |
| Overall change | 167 B | 167 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 31 kB | 31 kB | ✓ |
| Overall change | 31 kB | 31 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 508 B | 510 B | N/A |
| css-HASH.js gzip | 341 B | 341 B | ✓ |
| dynamic-HASH.js gzip | 2.52 kB | 2.52 kB | ✓ |
| edge-ssr-HASH.js gzip | 264 B | 266 B | N/A |
| head-HASH.js gzip | 362 B | 363 B | N/A |
| hooks-HASH.js gzip | 391 B | 390 B | N/A |
| image-HASH.js gzip | 4.4 kB | 4.26 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.81 kB | 2.69 kB | N/A |
| routerDirect..HASH.js gzip | 326 B | 325 B | N/A |
| script-HASH.js gzip | 396 B | 397 B | N/A |
| withRouter-HASH.js gzip | 322 B | 321 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.62 kB | 3.62 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 746 B | 748 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 536 B | 536 B | ✓ |
| withRouter.html gzip | 519 B | 519 B | ✓ |
| Overall change | 1.58 kB | 1.58 kB | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 127 kB | 127 kB | N/A |
| page.js gzip | 168 kB | 194 kB | ⚠️ +25.8 kB |
| Overall change | 168 kB | 194 kB | ⚠️ +25.8 kB |

</details>

<details>
<summary><strong>Middleware size</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 669 B | 671 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 29.7 kB | 29.7 kB | N/A |
| edge-runtime..pack.js gzip | 1.03 kB | 1.18 kB | ⚠️ +150 B |
| Overall change | 1.03 kB | 1.18 kB | ⚠️ +150 B |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| 928-experime...dev.js gzip | 310 B | 310 B | ✓ |
| 928.runtime.dev.js gzip | 301 B | 301 B | ✓ |
| app-page-exp...dev.js gzip | 236 kB | 233 kB | N/A |
| app-page-exp..prod.js gzip | 120 kB | 142 kB | ⚠️ +21.2 kB |
| app-page-tur..prod.js gzip | 132 kB | 153 kB | ⚠️ +20.9 kB |
| app-page-tur..prod.js gzip | 128 kB | 149 kB | ⚠️ +21.2 kB |
| app-page.run...dev.js gzip | 231 kB | 227 kB | N/A |
| app-page.run..prod.js gzip | 117 kB | 138 kB | ⚠️ +21.4 kB |
| app-route-ex...dev.js gzip | 23.1 kB | 23.4 kB | ⚠️ +303 B |
| app-route-ex..prod.js gzip | 18.8 kB | 18.8 kB | N/A |
| app-route-tu..prod.js gzip | 18.8 kB | 18.8 kB | N/A |
| app-route-tu..prod.js gzip | 18.6 kB | 18.6 kB | N/A |
| app-route.ru...dev.js gzip | 24.4 kB | 24.6 kB | ⚠️ +244 B |
| app-route.ru..prod.js gzip | 18.6 kB | 18.6 kB | N/A |
| pages-api-tu..prod.js gzip | 9.6 kB | 9.6 kB | ✓ |
| pages-api.ru...dev.js gzip | 9.87 kB | 9.87 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.59 kB | 9.59 kB | ✓ |
| pages-turbo...prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| pages.runtim...dev.js gzip | 22.2 kB | 22.1 kB | N/A |
| pages.runtim..prod.js gzip | 21.6 kB | 21.6 kB | ✓ |
| server.runti..prod.js gzip | 56.7 kB | 56.7 kB | N/A |
| 928-experime..prod.js gzip | N/A | 310 B | N/A |
| 928-turbo-ex..prod.js gzip | N/A | 312 B | N/A |
| 928-turbo.ru..prod.js gzip | N/A | 304 B | N/A |
| 928.runtime.prod.js gzip | N/A | 302 B | N/A |
| Overall change | 618 kB | 703 kB | ⚠️ +85.3 kB |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | archanaagivale30/next.js fix_issue_68039 | Change |
| - | - | - | - |
| 0.pack gzip | 1.42 MB | 2.04 MB | ⚠️ +622 kB |
| index.pack gzip | 120 kB | 143 kB | ⚠️ +23 kB |
| Overall change | 1.54 MB | 2.19 MB | ⚠️ +645 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 5327: /***/ (
+    /***/ 8938: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610__zehaskxadtwcczqqbmt6koh6bq/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsbeDKa9%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610__uulzbengwsfwhwaa2ambxampcy/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsbeDKa9%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -69,35 +69,35 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-6230622a1a-20240610__zehaskxadtwcczqqbmt6koh6bq/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(649 [...]

2024-07-31 18:21 UTC, flippidippi commented
@archanaagivale30 should I close mine? https://github.com/vercel/next.js/pull/68081
I'm not sure why my CI isn't working

I just solved it a little differently with an if statement instead of reassignment

2024-08-02 08:27 UTC, archanaagivale30 commented
> @archanaagivale30 should I close mine? #68081 I'm not sure why my CI isn't working
> 
> I just solved it a little differently with an if statement instead of reassignment

@samcx whats your thoughts?

2024-09-04 07:16 UTC, archanaagivale30 commented
@samcx is there any changes we need in this PR ?
cc @huozhi

2024-09-09 17:39 UTC, ijjk requested changes
Hi, the provided test case appears to pass fine without the changes in the PR, is this already fixed on canary?

2024-09-10 05:16 UTC, archanaagivale30 commented
> Hi, the provided test case appears to pass fine without the changes in the PR, is this already fixed on canary?

hi @ijjk the issue is not fixed on canary branch. I cross-checked it just now again.

2024-09-10 15:15 UTC, ijjk reviewed
Could we update the test case to ensure that it fails without the changes in this PR?

2024-09-11 12:20 UTC, archanaagivale30 commented
@ijjk I updated the test case to ensure it fails without the changes in this PR.

2024-09-11 16:12 UTC, ijjk approved these changes
Thanks!

2024-09-11 16:12 UTC, merged

2024-09-24 08:13 UTC, lauri865 commented
@ijjk, will this be backported to Next 14? Had some pretty major headaches with this.

2024-09-25 20:37 UTC, lauri865 commented
@ijjk, just updated to the latest canary, and the issue I mentioned is unfortunately still there.

2024-09-25 21:14 UTC, ijjk commented
@lauri865 that sounds like a different issue, `?raw` and `?raw=` should be equivalent unless the parsing library being used on the upstream is differentiating them for some reason.

2024-09-25 23:42 UTC, lauri865 commented
Disagree that it has anything to do with Vite. You may be right in that the query param value is the same, but the shape of the URL is different. And when doing rewrites, these things should not happen, since it's not visible and can cause difficult to debug issues.

2024-09-25 23:56 UTC, ijjk commented
> Disagree that it has anything to do with Vite

I'm not sure I follow, you linked a Vite asset import docs link. These aren't related to rewrites.

2024-09-26 00:00 UTC, lauri865 commented
It's just an example of how rewrite breaks a completely unrelated feature. It could well be a custom API that checks the shape of the URL rather than the query param values. It's a common practice to use rewrites to reverse proxy paths to other services.