Clarify width and height properties in Image component docs
vercel/next.js pull request #68248
Opened 2024-07-28 16:23 UTC by Tim-Zj

### Clarify width and height properties in Image component docs

This PR updates the documentation for the `width` and `height` properties of the Image component to clarify that these attributes represent the intrinsic dimensions of the image and do not determine the rendered size, which is controlled by CSS. This clarification aligns the documentation with the behavior of the HTML `<img>` tag.

Fixes issue #68228.

2024-07-28 16:23 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: e85bbf8ecff7daa9bb48653bea2cef4b06aca2d8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-28 16:23 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: e85bbf8ecff7daa9bb48653bea2cef4b06aca2d8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-28 16:23 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: e85bbf8ecff7daa9bb48653bea2cef4b06aca2d8

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-07-29 07:06 UTC, Willem-Jaap requested changes

2024-07-29 07:06 UTC, Willem-Jaap commented on docs/02-app/02-api-reference/01-components/image.mdx
> +The `width` property represents the _intrisic_ image width in pixels.This property is used to infer the correct aspect ratio of the image and avoid layout shift during loading. It does not determine
```suggestion
The `width` property represents the _intrisic_ image width in pixels. This property is used to infer the correct aspect ratio of the image and avoid layout shift during loading. It does not determine the rendered size of the image, which is controlled by CSS, similar to the `width` attribute in the HTML `<img>` tag.
```

2024-07-29 07:06 UTC, Willem-Jaap commented on docs/02-app/02-api-reference/01-components/image.mdx
> +The `height` property represents the _intrisic_ image height in pixels.This property is used to infer the correct aspect ratio of the image and avoid layout shift during loading. It does not determin
```suggestion
The `height` property represents the _intrisic_ image height in pixels. This property is used to infer the correct aspect ratio of the image and avoid layout shift during loading. It does not determine the rendered size of the image, which is controlled by CSS, similar to the `height` attribute in the HTML `<img>` tag.
```

2024-09-16 20:19 UTC, ijjk approved these changes

2024-09-16 20:26 UTC, merged