fix: swallow error when fetching registry
vercel/next.js pull request #68522
Opened 2024-08-05 06:49 UTC by devjiwonchoi

2024-08-05 06:49 UTC, devjiwonchoi commented
* **#68522** <a href="https://app.graphite.dev/github/pr/vercel/next.js/68522?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devjiwonchoi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-05 09:22 UTC, eps1lon requested changes
We should only swallow where we expect the error. We expect it in a very specific situation according to the PR desc so we should only swallow in those.

We should never swallow any error. There might be other runtime errors in here.

2024-08-05 19:51 UTC, eps1lon commented
Shouldn't we instead use a separate function that ignores the npm config and use that in the specific instance were we errored? Silently ignoring the config will be hard to debug if we ignore the registry in a place where we shouldn't.

It's important to be very accurate here because regressions may remain undetected until months later somebody realizes some download is taking longer because we stopped using the configured registry.

2024-08-06 07:51 UTC, devjiwonchoi commented on packages/next/src/lib/helpers/get-registry.ts
> +        `Failed to get registry from "${pkgManager}".\n\n${err.message}`
![Screenshot 2024-08-06 at 4 47 59 PM](https://github.com/user-attachments/assets/02813836-b81c-4581-9f12-854b9bfb3eb5)

2024-08-06 08:09 UTC, devjiwonchoi commented
@eps1lon What do you think of passing `--no-workspace` for non-workspaces?
I could just nest it down to the `catch` and add only if `ENOWORKSPACES` error.

2024-08-06 18:00 UTC, eps1lon commented on packages/next/src/lib/helpers/get-registry.ts
> +    }
Can we start using `cause` i.e. `throw new Error(`your message here`, { cause: error })`? This'll also make sure we handle the cases where non-errors are thrown.

2024-08-06 18:08 UTC, eps1lon commented on packages/next/src/lib/helpers/get-registry.ts
> +    if (err instanceof Error) {
why is this check still needed?

2024-08-06 18:08 UTC, eps1lon commented on packages/next/src/lib/helpers/get-registry.ts
> +  // x-ref: https://github.com/npm/statusboard/issues/371#issue-920669998
New implementation has way more confidence given the explainer. This is valueable context, thank you!

2024-08-06 18:11 UTC, devjiwonchoi commented on packages/next/src/lib/helpers/get-registry.ts
> +    if (err instanceof Error) {
should be removed..

2024-08-06 18:12 UTC, eps1lon approved these changes

2024-08-07 06:46 UTC, merged