Added an HTTP2 server example
vercel/next.js pull request #6856
Opened 2019-04-02 02:39 UTC by shahzeb1

As requested in this issue: https://github.com/zeit/next.js/issues/6850

This is a basic HTTP2 server which can handle the `/` and `/about` routes. 

The Readme includes [specific instruction](https://github.com/shahzeb1/next.js/blob/31877720f076b49b39a167deb0ba8650d0052dda/examples/with-http2/README.md#download-manually) about how to generate the public/private keys used for this demo server.

2019-04-02 13:31 UTC, timneutkens commented on examples/with-http2/package.json
> +  "author": "Shahzeb Khan <https://github.com/shahzeb1>",
Can you make sure the package.json matches other examples? We generally leave out the author, repository, add in a license etc.

2019-04-02 13:31 UTC, timneutkens requested changes
Added one small comment

2019-04-02 17:45 UTC, shahzeb1 commented
Went ahead and made the `package.json` match the one located in the `hello-world` example.

2019-04-02 18:19 UTC, shahzeb1 commented
Also as far as I can tell, the ziet.next.js test that just failed doesn't have to do with my commits. I'm not sure why it would fail this PR.

2019-04-03 09:28 UTC, timneutkens approved these changes
Awesome! Thank you!

2019-04-03 09:31 UTC, merged