fix: Update docs to useFormStatus for pending
vercel/next.js pull request #69163
Opened 2024-08-21 21:42 UTC by timodwhit

The third parameter seems to have been removed from useActionState() and requires useFormStatus

<!-- Thanks for opening a PR! Your contribution is much appreciated.
To make sure your PR is handled as smoothly as possible we request that you follow the checklist sections below.
Choose the right checklist for the change(s) that you're making:

## For Contributors

### Improving Documentation

- Run `pnpm prettier-fix` to fix formatting issues before opening the PR.
- Read the Docs Contribution Guide to ensure your contribution follows the docs guidelines: https://nextjs.org/docs/community/contribution-guide

2024-08-21 21:43 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: fc0456f8336bd536c6ea518733acf87228e21fe7

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-08-22 08:49 UTC, eps1lon requested changes
> The third parameter seems to have been removed from useActionState() 

It is still there. If you're not seeing it, confirm you're on the latest React/Next.js Canary. If you're still not seeing it, please file a bug report. 

The current docs describe the desired state and should remain

2024-08-22 08:49 UTC, closed without merging

2024-08-22 10:00 UTC, timodwhit commented
According to the react 19 docs: https://19.react.dev/reference/react/useActionState#useactionstate

> Returns 
>
> useActionState returns an array with exactly two values:
>
> The current state. During the first render, it will match the initialState you have passed. After the action is invoked, it will match the value returned by the action.
> A new action that you can pass as the action prop to your form component or formAction prop to any button component within the form.

Unless, it is somewhere else or do those docs need the PR?

2024-08-22 12:05 UTC, eps1lon commented
react.dev needs a PR