docs: assert missing types for next-config-ts
vercel/next.js pull request #69188
Opened 2024-08-22 15:26 UTC by devjiwonchoi

2024-08-22 15:26 UTC, devjiwonchoi commented
* **#69188** <a href="https://app.graphite.dev/github/pr/vercel/next.js/69188?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devjiwonchoi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-22 21:48 UTC, samcx requested changes

2024-08-22 21:48 UTC, samcx commented on docs/02-app/02-api-reference/05-next-config-js/reactCompiler.mdx
> +```ts filename="next.config.ts"
Let's use both the switcher (`ts` and `js`) option!

2024-08-23 05:56 UTC, samcx approved these changes

2024-08-23 05:58 UTC, devjiwonchoi commented
### Merge activity

* **Aug 23, 1:58 AM EDT**: @devjiwonchoi started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/69188).

2024-08-23 05:58 UTC, merged