Set busboy defParamCharset to utf8
vercel/next.js pull request #70348
Opened 2024-09-23 14:54 UTC by jaredhan418

### Fixing a bug
Fix https://github.com/vercel/next.js/issues/70335

### What?
 see https://github.com/vercel/next.js/issues/70335
### Why?

### How?
As for fetch standard, I think it should make filename decode with utf-8 by default https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set

2024-09-23 14:56 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: d34cce1a677c025e161671a2a7ed3916cab3bd9c

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-09-24 20:50 UTC, ijjk requested changes
Hi, could we add a regression test for this to verify it resolves the issue?

2024-09-25 03:24 UTC, jaredhan418 commented
> Hi, could we add a regression test for this to verify it resolves the issue?

create a test file named `action-handler.test.ts` at same place ?

2024-09-25 05:05 UTC, ijjk reviewed
Just a new test assertion/page inside of `test/e2e/app-dir/actions` works!

2024-09-25 05:28 UTC, jaredhan418 commented
> Just a new test assertion/page inside of `test/e2e/app-dir/actions` works!

Cool, will do.

2024-09-28 16:53 UTC, jaredhan418 commented
Test case updated @ijjk

2024-09-28 20:58 UTC, ijjk approved these changes
Thanks!

2024-09-28 21:05 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| buildDuration | 20s | 17.4s | N/A |
| buildDurationCached | 16.4s | 14s | N/A |
| nodeModulesSize | 371 MB | 371 MB | ⚠️ +1.43 kB |
| nextStartRea..uration (ms) | 445ms | 446ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| 1623-HASH.js gzip | 41.8 kB | 41.8 kB | N/A |
| 3383-HASH.js gzip | 5.26 kB | 5.25 kB | N/A |
| 5952.HASH.js gzip | 169 B | 169 B | ✓ |
| 946e5feb-HASH.js gzip | 52.8 kB | 52.8 kB | ✓ |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 231 B | 228 B | N/A |
| main-HASH.js gzip | 32.7 kB | 32.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 52.9 kB | 52.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 191 B | 192 B | N/A |
| amp-HASH.js gzip | 512 B | 512 B | ✓ |
| css-HASH.js gzip | 343 B | 343 B | ✓ |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 364 B | 365 B | N/A |
| hooks-HASH.js gzip | 390 B | 391 B | N/A |
| image-HASH.js gzip | 4.41 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 268 B | 267 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | N/A |
| routerDirect..HASH.js gzip | 326 B | 327 B | N/A |
| script-HASH.js gzip | 395 B | 397 B | N/A |
| withRouter-HASH.js gzip | 323 B | 322 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.42 kB | 1.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 748 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| index.html gzip | 523 B | 521 B | N/A |
| link.html gzip | 537 B | 534 B | N/A |
| withRouter.html gzip | 519 B | 516 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 181 kB | 181 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 669 B | 670 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 30 kB | 30 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 319 kB | 319 kB | N/A |
| app-page-exp..prod.js gzip | 126 kB | 126 kB | N/A |
| app-page-tur..prod.js gzip | 139 kB | 139 kB | N/A |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | N/A |
| app-page.run...dev.js gzip | 309 kB | 309 kB | N/A |
| app-page.run..prod.js gzip | 121 kB | 121 kB | N/A |
| app-route-ex...dev.js gzip | 34.1 kB | 34.1 kB | ✓ |
| app-route-ex..prod.js gzip | 22.7 kB | 22.7 kB | ✓ |
| app-route-tu..prod.js gzip | 22.7 kB | 22.7 kB | ✓ |
| app-route-tu..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| app-route.ru...dev.js gzip | 35.8 kB | 35.8 kB | ✓ |
| app-route.ru..prod.js gzip | 22.4 kB | 22.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.62 kB | 9.62 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.5 kB | 11.5 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| pages.runtim...dev.js gzip | 26.5 kB | 26.5 kB | ✓ |
| pages.runtim..prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| server.runti..prod.js gzip | 57.4 kB | 57.4 kB | ✓ |
| Overall change | 317 kB | 317 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | jaredhan418/next.js jaredhan418-patch-1 | Change |
| - | - | - | - |
| 0.pack gzip | 1.66 MB | 1.66 MB | N/A |
| index.pack gzip | 131 kB | 131 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 5732: /***/ (
+    /***/ 2836: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3edc000d-20240926_re_okha6m53pf4dodtmle7pje5faa/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsZDshTb%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3edc000d-20240926_re_ixusczm6ngtdvmbk5ko4spdqvu/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsZDshTb%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -76,35 +76,35 @@
         tree: () => tree,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3edc000d-20240926_re_okha6m53pf4dodtmle7pje5faa/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(5663);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3edc000d-20240926_re_okha6m53pf4dodtmle7pje5faa/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __webpack_require__(9386);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-3edc000d-20240926_re_okha6m53pf4dodtmle7pje5faa/node_modules/next/dist/esm/build/webpa [...]

2024-09-28 21:08 UTC, ijjk commented
## Failing test suites <!--28971289215-->
Commit: 61cbc7c5a23dc4ebc7f82315bee7a0b97b83dadf

`TURBOPACK=1 pnpm test-start test/production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts` (turbopack)
- app-dir - server-action-period-hash-custom-key > should have different manifest if the encryption key from process env is changed
- app-dir - server-action-period-hash-custom-key > should have different manifest if the encryption key from process env is same

<details>
<summary>Expand output</summary>

  ● app-dir - server-action-period-hash-custom-key › should have different manifest if the encryption key from process env is changed

    expect(received).not.toEqual(expected) // deep equality

    Expected: not ["81e52064757b1e34218e39676e6c7b2e5308976d", "8f1c262d3399e85740ee631e51483f7b9e199431"]

      18 |     expect(keysA).toEqual(keysB)
      19 |   } else {
    > 20 |     expect(keysA).not.toEqual(keysB)
         |                       ^
      21 |   }
      22 | }
      23 |

      at toEqual (production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts:20:23)
      at Object.compareServerActionManifestKeys (production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts:42:5)

  ● app-dir - server-action-period-hash-custom-key › should have different manifest if the encryption key from process env is same

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
    -   "8f1c262d3399e85740ee631e51483f7b9e199431",
        "81e52064757b1e34218e39676e6c7b2e5308976d",
    +   "8f1c262d3399e85740ee631e51483f7b9e199431",
      ]

      16 |
      17 |   if (equal) {
    > 18 |     expect(keysA).toEqual(keysB)
         |                   ^
      19 |   } else {
      20 |     expect(keysA).not.toEqual(keysB)
      21 |   }

      at toEqual (production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts:18:19)
      at Object.compareServerActionManifestKeys (production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts:56:5)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-09-29 02:15 UTC, jaredhan418 commented
> ## Failing test suites
> Commit: [61cbc7c](https://github.com/vercel/next.js/commit/61cbc7c5a23dc4ebc7f82315bee7a0b97b83dadf)
> 
> `TURBOPACK=1 pnpm test-start test/production/app-dir/server-action-period-hash/server-action-period-hash-custom-key.test.ts` (turbopack)
> 
> * app-dir - server-action-period-hash-custom-key > should have different manifest if the encryption key from process env is changed
> * app-dir - server-action-period-hash-custom-key > should have different manifest if the encryption key from process env is same
> 
> Expand output
> Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
> 
> `pnpm test-dev test/e2e/app-dir/navigation/navigation.test.ts`
> 
> * app dir - navigation > navigation between pages and app > should not contain _rsc query while navigating from app to pages
> 
> Expand output
> Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
> 
> `TURBOPACK=1 pnpm test-start test/production/app-dir/server-action-period-hash/server-action-period-hash.test.ts` (turbopack)
> 
> * app-dir - server-action-period-hash > should have same manifest between continuous two builds
> 
> Expand output
> Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).
> 
> `pnpm test-dev test/e2e/app-dir/logging/fetch-logging.test.ts`
> 
> * app-dir - logging > with fetches verbose logging > when logging.fetches.hmrRefreshes is true > should log requests for HMR refreshes
> 
> Expand output
> Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

It seems that failure occurred not by my commit? @ijjk

2024-09-30 15:29 UTC, merged