fix: Do not omit alt on getImgProps return type, ImgProps
vercel/next.js pull request #70608
Opened 2024-09-30 08:20 UTC by icyJoseph

### What?

Small type tweak, asked for in https://github.com/vercel/next.js/discussions/70443

### Why?

The `alt` prop is required on the call to `getImgProps`, and the implementation, returns it back to the caller, however, the type signature of the return type for `getImgProps`, omits the `alt` prop, which means that users have to manually apply the `alt` prop. 

That is to say, that in this example, tweaked from the docs:

```jsx
import { getImageProps } from 'next/image'
 
export default function Page() {
  const common = { alt: 'Theme Example', width: 800, height: 400 }
  const {
    props: { srcSet: dark },
  } = getImageProps({ ...common, src: '/dark.png' })
  const {
    props: { srcSet: light, ...rest },
  } = getImageProps({ ...common, src: '/light.png' })
 
  return (
    <picture>
      <source media="(prefers-color-scheme: dark)" srcSet={dark} />
      <source media="(prefers-color-scheme: light)" srcSet={light} />
      {/* the alt prop is here, but as far as TypeScript is concerned, it is not */}
      <SomeCustomImageComponent {...rest} /> 
    </picture>
  )
}
``` 

So users have to do:

```jsx
      <SomeCustomImageComponent {...rest} alt={common.alt} /> 
```

See more at, https://github.com/vercel/next.js/discussions/70443

### How?

Remove `alt` from the Omit union.

```tsx
export type ImgProps = Omit<ImageProps, 'src'  | 'alt' | 'loader'> & { /* other stuff */ }
```

Fixes https://github.com/vercel/next.js/discussions/70443

2024-09-30 08:20 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 036776884cdd1c6b7f2e775d1397cecc86714393

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-10-01 18:07 UTC, ijjk requested changes
Hi, could we add a test case where this is failing without the change?

2024-10-01 19:21 UTC, icyJoseph commented
Åhh yes! A bit odd that I missed that, fix coming soon.

2024-10-01 21:51 UTC, ijjk commented
A full example showing how you mean for it to be used in an integration test would be more ideal so we capture use case

2024-10-02 16:19 UTC, styfle commented
> however, the type signature of the return type for getImgProps, omits the alt prop

Is this just a TS type issue? If so then you can probably update an existing TS test to confirm it fails and that your PR fixes it.


https://github.com/vercel/next.js/blob/0bfa3ec15f0ae0e4e62d1ff69801452a3eda639b/test/unit/next-image-get-img-props.test.ts#L17

2024-10-02 19:44 UTC, icyJoseph commented
Good suggestion! So without the changes of this PR, having a test such as:

```ts
    const { props } = getImageProps({
      alt: 'a nice desc',
      id: 'my-image',
      src: '/test.png',
      width: 100,
      height: 200,
    })

    expect(props.alt).toBeString()
    expect(props.id).toBeString()
    // rest of type expectations
```

Causes this TS error, at IDE/text-editor level:

<img width="833" alt="Screenshot 2024-10-02 at 21 36 10" src="https://github.com/user-attachments/assets/4da74831-7998-4fa0-a203-28b3a8de117f">

Does the repository have any type testing tool installed? Otherwise, I guess, this is alright, and, though the test run (`pnpm test`) doesn't seem to evaluate types, the `pnpm typescript` command does catch it:

```console
➜ pnpm typescript

> nextjs-project@0.0.0 typescript /Users/joseph/dev-exp/next.js
> tsc --noEmit

test/unit/next-image-get-img-props.test.ts:50:18 - error TS2339: Property 'alt' does not exist on type 'ImgProps'.

50     expect(props.alt).toBeString()
                    ~~~
```

Re-applying the fix, clears the text editor error highlight and the output of `pnpm typescript`

2024-10-02 19:56 UTC, ijjk commented
## Failing test suites <!--29135379250-->
Commit: 093283c70d8c5c4aeb2d8b4b266c3779f0d7bdab

`TURBOPACK=1 pnpm test-dev test/development/app-hmr/hmr.test.ts` (turbopack)
- app-dir-hmr > filesystem changes > should update server components after navigating to a page with a different runtime
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (node)
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (node-module-var)
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (edge)
- app-dir-hmr > filesystem changes > should update server components pages when env files is changed (edge-module-var)
- app-dir-hmr > filesystem changes > can navigate cleanly to a page that requires a change in the Webpack runtime

<details>
<summary>Expand output</summary>

  ● app-dir-hmr › filesystem changes › should update server components after navigating to a page with a different runtime

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [{"message": "[Fast Refresh] rebuilding", "source": "log"}, {"message": "[Fast Refresh] rebuilding", "source": "log"}, {"message": "[Fast Refresh] rebuilding", "source": "log"}]
    Received: []

      75 |             // To ignore this flakiness, we just assert on subset matches.
      76 |             // Once the  bug is fixed, each "rebuilding" should be paired with a "done in" exactly.
    > 77 |             expect(fastRefreshLogs).toEqual(
         |                                     ^
      78 |               expect.arrayContaining([
      79 |                 { source: 'log', message: '[Fast Refresh] rebuilding' },
      80 |                 { source: 'log', message: '[Fast Refresh] rebuilding' },

      at toEqual (development/app-hmr/hmr.test.ts:77:37)
      at fn (lib/next-test-utils.ts:806:20)
      at Object.<anonymous> (development/app-hmr/hmr.test.ts:69:11)

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (node)

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [ObjectContaining {"message": "[Fast Refresh] rebuilding", "source": "log"}]
    Received: [{"message": "%cDownload the React DevTools for a better development experience: https://react.dev/link/react-devtools font-weight:bold", "source": "info"}, {"message": "Next.js page already hydrated", "source": "log"}, {"message": "connected to ws at ws://localhost:35439/_next/webpack-hmr", "source": "log"}, {"message": "received ws message {\"action\":\"appIsrManifest\",\"data\":{\"/folder-renamed\":false,\"/does-not-exist\":false,\"/env/node\":false}}", "source": "log"}, {"message": "received ws message {\"action\":\"turbopack-connected\",\"data\":{\"sessionId\":2508668990948203}}", "source": "log"}, {"message": "received ws message {\"action\":\"sync\",\"errors\":[],\"warnings\":[],\"hash\":\"\",\"versionInfo\":{\"staleness\":\"fresh\",\"installed\":\"15.0.0-canary.176\"},\"debug\":{}}", "source": "log"}, {"message": "received ws message {\"action\":\"serverComponentChanges\"}", "source": "log"}, {"message": "received ws message {\"action\":\"appIsrManifest\",\"data\":{\"/does-not-exist\":false,\"/folder-renamed\":false}}", "source": "log"}]

      150 |         const logs = await browser.log()
      151 |         await retry(async () => {
    > 152 |           expect(logs).toEqual(
          |                        ^
      153 |             expect.arrayContaining([
      154 |               expect.objectContaining({
      155 |                 message: '[Fast Refresh] rebuilding',

      at toEqual (development/app-hmr/hmr.test.ts:152:24)
      at fn (lib/next-test-utils.ts:806:20)
      at development/app-hmr/hmr.test.ts:151:9

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (node-module-var)

    expect(received).toBe(expected) // Object.is equality

    Expected: "mac"
    Received: "ipad"

      145 |       async (page) => {
      146 |         const browser = await next.browser(`/env/${page}`)
    > 147 |         expect(await browser.elementByCss('p').text()).toBe('mac')
          |                                                        ^
      148 |         await next.patchFile(envFile, 'MY_DEVICE="ipad"')
      149 |
      150 |         const logs = await browser.log()

      at toBe (development/app-hmr/hmr.test.ts:147:56)

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (edge)

    expect(received).toBe(expected) // Object.is equality

    Expected: "mac"
    Received: "ipad"

      145 |       async (page) => {
      146 |         const browser = await next.browser(`/env/${page}`)
    > 147 |         expect(await browser.elementByCss('p').text()).toBe('mac')
          |                                                        ^
      148 |         await next.patchFile(envFile, 'MY_DEVICE="ipad"')
      149 |
      150 |         const logs = await browser.log()

      at toBe (development/app-hmr/hmr.test.ts:147:56)

  ● app-dir-hmr › filesystem changes › should update server components pages when env files is changed (edge-module-var)

    expect(received).toBe(expected) // Object.is equality

    Expected: "mac"
    Received: "ipad"

      145 |       async (page) => {
      146 |         const browser = await next.browser(`/env/${page}`)
    > 147 |         expect(await browser.elementByCss('p').text()).toBe('mac')
          |                                                        ^
      148 |         await next.patchFile(envFile, 'MY_DEVICE="ipad"')
      149 |
      150 |         const logs = await browser.log()

      at toBe (development/app-hmr/hmr.test.ts:147:56)

  ● app-dir-hmr › filesystem changes › can navigate cleanly to a page that requires a change in the Webpack runtime

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [{"message": "[Fast Refresh] rebuilding", "source": "log"}, {"message": "[Fast Refresh] rebuilding", "source": "log"}, {"message": "[Fast Refresh] rebuilding", "source": "log"}]
    Received: [{"message": "%cDownload the React DevTools for a better development experience: https://react.dev/link/react-devtools font-weight:bold", "source": "info"}, {"message": "Next.js page already hydrated", "source": "log"}, {"message": "connected to ws at ws://localhost:35439/_next/webpack-hmr", "source": "log"}, {"message": "received ws message {\"action\":\"appIsrManifest\",\"data\":{\"/env/node-module-var\":false,\"/does-not-exist\":false,\"/folder-renamed\":false,\"/bundler-runtime-changes\":false}}", "source": "log"}, {"message": "received ws message {\"action\":\"turbopack-connected\",\"data\":{\"sessionId\":2508668990948203}}", "source": "log"}, {"message": "received ws message {\"action\":\"sync\",\"errors\":[],\"warnings\":[],\"hash\":\"\",\"versionInfo\":{\"staleness\":\"fresh\",\"installed\":\"15.0.0-canary.176\"},\"debug\":{}}", "source": "log"}, {"message": "received ws message {\"action\":\"appIsrManifest\",\"data\":{\"/bundler-runtime-changes\":false,\"/folder-renamed\":false,\"/does-not-exist\":false,\"/env/node-module-var\":false}}", "source": "log"}]

      219 |         // FIXME: logging "rebuilding" multiple times instead of closing it of with "done in"
      220 |         // Should just not branch here and have the same logs as Webpack.
    > 221 |         expect(logs).toEqual(
          |                      ^
      222 |           expect.arrayContaining([
      223 |             {
      224 |               message: '[Fast Refresh] rebuilding',

      at Object.toEqual (development/app-hmr/hmr.test.ts:221:22)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-10-02 20:51 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| buildDuration | 17.7s | 18.9s | ⚠️ +1.2s |
| buildDurationCached | 15.4s | 13.2s | N/A |
| nodeModulesSize | 369 MB | 371 MB | ⚠️ +1.7 MB |
| nextStartRea..uration (ms) | 432ms | 415ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| 1623-HASH.js gzip | 41.9 kB | 41.8 kB | N/A |
| 3383-HASH.js gzip | 5.26 kB | 5.25 kB | N/A |
| 5952.HASH.js gzip | 169 B | 169 B | ✓ |
| 946e5feb-HASH.js gzip | 52.8 kB | 52.8 kB | ✓ |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 231 B | 228 B | N/A |
| main-HASH.js gzip | 32.7 kB | 32.7 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 52.9 kB | 52.9 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 191 B | 192 B | N/A |
| amp-HASH.js gzip | 512 B | 512 B | ✓ |
| css-HASH.js gzip | 343 B | 343 B | ✓ |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 364 B | 365 B | N/A |
| hooks-HASH.js gzip | 390 B | 391 B | N/A |
| image-HASH.js gzip | 4.41 kB | 4.4 kB | N/A |
| index-HASH.js gzip | 268 B | 267 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | N/A |
| routerDirect..HASH.js gzip | 326 B | 327 B | N/A |
| script-HASH.js gzip | 395 B | 397 B | N/A |
| withRouter-HASH.js gzip | 323 B | 322 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.42 kB | 1.42 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| _buildManifest.js gzip | 749 B | 748 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| index.html gzip | 524 B | 523 B | N/A |
| link.html gzip | 538 B | 536 B | N/A |
| withRouter.html gzip | 520 B | 517 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 184 kB | 181 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 668 B | N/A |
| middleware-r..fest.js gzip | 156 B | 155 B | N/A |
| middleware.js gzip | 30 kB | 30 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 309 kB | 319 kB | ⚠️ +10.2 kB |
| app-page-exp..prod.js gzip | 118 kB | 126 kB | ⚠️ +7.65 kB |
| app-page-tur..prod.js gzip | 132 kB | 139 kB | ⚠️ +7.72 kB |
| app-page-tur..prod.js gzip | 127 kB | 134 kB | ⚠️ +7.68 kB |
| app-page.run...dev.js gzip | 299 kB | 309 kB | ⚠️ +10.2 kB |
| app-page.run..prod.js gzip | 114 kB | 122 kB | ⚠️ +7.66 kB |
| app-route-ex...dev.js gzip | 33.8 kB | 34.1 kB | ⚠️ +276 B |
| app-route-ex..prod.js gzip | 22.7 kB | 22.7 kB | N/A |
| app-route-tu..prod.js gzip | 22.7 kB | 22.7 kB | N/A |
| app-route-tu..prod.js gzip | 22.4 kB | 22.4 kB | N/A |
| app-route.ru...dev.js gzip | 35.5 kB | 35.8 kB | ⚠️ +271 B |
| app-route.ru..prod.js gzip | 22.4 kB | 22.4 kB | N/A |
| pages-api-tu..prod.js gzip | 9.62 kB | 9.62 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.5 kB | 11.5 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 20.9 kB | 20.9 kB | N/A |
| pages.runtim...dev.js gzip | 26.5 kB | 26.5 kB | N/A |
| pages.runtim..prod.js gzip | 20.9 kB | 20.9 kB | N/A |
| server.runti..prod.js gzip | 57.5 kB | 57.4 kB | N/A |
| Overall change | 1.2 MB | 1.25 MB | ⚠️ +51.6 kB |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | icyJoseph/next.js fix/typescript-get-img-props-alt-text | Change |
| - | - | - | - |
| 0.pack gzip | 1.81 MB | 1.67 MB | N/A |
| index.pack gzip | 139 kB | 131 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>dynamic-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2739],
   {
-    /***/ 1543: /***/ (
+    /***/ 2307: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/dynamic",
         function () {
-          return __webpack_require__(1872);
+          return __webpack_require__(4622);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7703: /***/ (module, exports, __webpack_require__) => {
+    /***/ 588: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -51,7 +51,7 @@
         __webpack_require__(4630)
       );
       const _loadablesharedruntime = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(1264)
+        __webpack_require__(6443)
       );
       const isServerSide = "object" === "undefined";
       // Normalize loader to return the module as form { default: Component } for `React.lazy`.
@@ -152,11 +152,7 @@
       /***/
     },
 
-    /***/ 7264: /***/ (
-      __unused_webpack_module,
-      exports,
-      __webpack_require__
-    ) => {
+    /***/ 55: /***/ (__unused_webpack_module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -179,7 +175,7 @@
       /***/
     },
 
-    /***/ 1264: /***/ (
+    /***/ 6443: /***/ (
       __unused_webpack_module,
       exports,
       __webpack_require__
@@ -221,7 +217,7 @@ WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
       const _react = /*#__PURE__*/ _interop_require_default._(
         __webpack_require__(4630)
       );
-      const _loadablecontextsharedruntime = __webpack_require__(7264);
+      const _loadablecontextsharedruntime = __webpack_ [...]

2024-10-02 22:08 UTC, ijjk approved these changes

2024-10-02 22:08 UTC, merged