feat(Metadata): add support for pinterest meta tag
vercel/next.js pull request #70873
Opened 2024-10-06 18:10 UTC by mezotv

Adds support for Pinterest's Rich Pin Data meta tag, while future-proofing for additional Pinterest tags.

This currently works like so

```js
pinterest: {
  richPin: true
}
  ```
 And would resolve to:
 
```html
 <meta property="pinterest-rich-pin" content="true" />
 ```

Here is pinterests docs on the topic: https://help.pinterest.com/en/business/article/rich-pins

2024-10-09 17:16 UTC, vignesh1507 approved these changes
Agree with the changes.

2024-11-04 08:03 UTC, mezotv commented
Hey @ijjk what are the chances of this being looked at?

2025-03-11 12:41 UTC, huozhi requested changes

2025-03-11 12:41 UTC, huozhi commented on packages/next/src/lib/metadata/generate/basic.tsx
> +  return MetaFilter([
let's change this to early assertions to avoid using MetaFilter for extra work

```
export function PinterestMeta({
  pinterest,
}: {
  pinterest: ResolvedMetadata['pinterest']
}) {
  if (!pinterest || !pinterest.richPin) return null

  const { richPin } = pinterest

  return <meta property="pinterest-rich-pin" content={richPin.toString()} />
}
```

2025-03-11 12:41 UTC, huozhi commented on readme.md
> -packages/next/README.md
this change is unexpected

2025-03-11 12:41 UTC, huozhi commented on packages/next/src/lib/metadata/generate/basic.tsx
> +export function PinterestMeta({
The render part of this component is missing, yu need to render it in `packages/next/src/lib/metadata/metadata.tsx` and please also add an e2e test case for it in metadata.test.ts

2025-03-11 16:09 UTC, mezotv commented
I tried removing the changes made to the readme but the pre commit hook didn't allow that, so nothing I can do.

2025-03-11 16:21 UTC, huozhi commented
I can't push changes to this pr, I opened another one to complete the implementation and fix the tests #76988

2025-03-11 16:51 UTC, mezotv commented
> I can't push changes to this pr, I opened another one to complete the implementation and fix the tests #76988

Sounds good!

2025-03-11 17:30 UTC, closed without merging