Prepare `select_part`
vercel/next.js pull request #71241
Opened 2024-10-14 05:56 UTC by kdy1

2024-10-14 05:56 UTC, kdy1 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/next.js/71241?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#71241** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71241?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#71237** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71237?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#71236** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71236?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#71126** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#71234** <a href="https://app.graphite.dev/github/pr/vercel/next.js/71234?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kdy1 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 06:14 UTC, ijjk commented
## Failing test suites <!--29574155303-->
Commit: fd28860b7e61557ae611345ccb204a20bef4fe4f

`__NEXT_EXPERIMENTAL_PPR=true pnpm test-dev test/e2e/app-dir/actions/app-action.test.ts` (PPR)
- app-dir action handling > should forward action request to a worker that contains the action handler (edge)

<details>
<summary>Expand output</summary>

  ● app-dir action handling › should forward action request to a worker that contains the action handler (edge)

    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#other-page')

      423 |     return this.chain(() => {
      424 |       return page
    > 425 |         .waitForSelector(selector, { timeout, state: 'attached' })
          |          ^
      426 |         .then(async (el) => {
      427 |           // it seems selenium waits longer and tests rely on this behavior
      428 |           // so we wait for the load event fire before returning

      at waitForSelector (lib/browsers/playwright.ts:425:10)
      at e2e/app-dir/actions/app-action.test.ts:844:7

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-10-14 06:14 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| buildDuration | 41.4s | 35.9s | N/A |
| buildDurationCached | 34.6s | 29.8s | N/A |
| nodeModulesSize | 371 MB | 371 MB | ✓ |
| nextStartRea..uration (ms) | 930ms | 807ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 307bebc6-HASH.js gzip | 52.6 kB | 52.6 kB | N/A |
| 3620-HASH.js gzip | 43.7 kB | 43.7 kB | N/A |
| 801.HASH.js gzip | 168 B | 169 B | N/A |
| 8962-HASH.js gzip | 5.26 kB | 5.26 kB | N/A |
| framework-HASH.js gzip | 57.4 kB | 57.4 kB | N/A |
| main-app-HASH.js gzip | 232 B | 230 B | N/A |
| main-HASH.js gzip | 32.8 kB | 32.8 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| _app-HASH.js gzip | 192 B | 192 B | ✓ |
| _error-HASH.js gzip | 193 B | 192 B | N/A |
| amp-HASH.js gzip | 509 B | 509 B | ✓ |
| css-HASH.js gzip | 341 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 266 B | 266 B | ✓ |
| head-HASH.js gzip | 365 B | 364 B | N/A |
| hooks-HASH.js gzip | 392 B | 391 B | N/A |
| image-HASH.js gzip | 4.41 kB | 4.41 kB | N/A |
| index-HASH.js gzip | 267 B | 268 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | N/A |
| routerDirect..HASH.js gzip | 327 B | 327 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 324 B | 322 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.64 kB | 3.64 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| _buildManifest.js gzip | 748 B | 750 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| index.html gzip | 521 B | 523 B | N/A |
| link.html gzip | 536 B | 537 B | N/A |
| withRouter.html gzip | 518 B | 519 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 188 kB | 188 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 672 B | N/A |
| middleware-r..fest.js gzip | 154 B | 156 B | N/A |
| middleware.js gzip | 30.7 kB | 30.7 kB | ✓ |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 31.5 kB | 31.5 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 973-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 973.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 314 kB | 314 kB | ✓ |
| app-page-exp..prod.js gzip | 120 kB | 120 kB | ✓ |
| app-page-tur..prod.js gzip | 134 kB | 134 kB | ✓ |
| app-page-tur..prod.js gzip | 128 kB | 128 kB | ✓ |
| app-page.run...dev.js gzip | 304 kB | 304 kB | ✓ |
| app-page.run..prod.js gzip | 116 kB | 116 kB | ✓ |
| app-route-ex...dev.js gzip | 35 kB | 35 kB | ✓ |
| app-route-ex..prod.js gzip | 23.6 kB | 23.6 kB | ✓ |
| app-route-tu..prod.js gzip | 23.7 kB | 23.7 kB | ✓ |
| app-route-tu..prod.js gzip | 23.4 kB | 23.4 kB | ✓ |
| app-route.ru...dev.js gzip | 36.6 kB | 36.6 kB | ✓ |
| app-route.ru..prod.js gzip | 23.4 kB | 23.4 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.61 kB | 9.61 kB | ✓ |
| pages-turbo...prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| pages.runtim...dev.js gzip | 26.5 kB | 26.5 kB | ✓ |
| pages.runtim..prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| server.runti..prod.js gzip | 60.1 kB | 60.1 kB | ✓ |
| Overall change | 1.44 MB | 1.44 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 0.pack gzip | 1.84 MB | 1.84 MB | ⚠️ +1.37 kB |
| index.pack gzip | 144 kB | 142 kB | N/A |
| Overall change | 1.84 MB | 1.84 MB | ⚠️ +1.37 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 9332: /***/ (
+    /***/ 6649: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-cd22717c-20241013_re_a5fwrzcgiqxq7kbo7kpyzjc5ji/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsCd8b7r%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-cd22717c-20241013_re_zq6nvqen5pqfmm5xeouxrlc4aq/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsCd8b7r%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -82,35 +82,35 @@
         workUnitAsyncStorage: () => entry_base /* workUnitAsyncStorage */.Sz,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-cd22717c-20241013_re_a5fwrzcgiqxq7kbo7kpyzjc5ji/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(6622);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-cd22717c-20241013_re_a5fwrzcgiqxq7kbo7kpyzjc5ji/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __webpack_require__(3395);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-cd22717c-20241013_re_a5fwrzcgiqxq7kbo7kpyzjc5ji [...]

2024-10-14 10:54 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs
> +    ignore_side_effect_of_entry: Vc<bool>,
```suggestion
    ignore_side_effect_of_entry: bool,
```

2024-10-14 10:54 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs
> +        vdbg!(&*module.ident().to_string().await?);
```suggestion
```

2024-10-14 15:02 UTC, kdy1 commented
### Merge activity

* **Oct 15, 12:02 AM GMT+9**: [Graphite](https://app.graphite.dev/github/pr/vercel/next.js/71241) disabled "merge when ready" on this PR due to: a merge conflict with the target branch; resolve the conflict and try again..

2024-10-17 07:33 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/tree_shake/asset.rs
> +        }
should be in turbopack/lib.rs

2024-10-17 07:35 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/tree_shake/asset.rs
> +    pub side_effects: Vc<SideEffects>,
Doesn't need to be a Vc. Could be just a Vec

2024-10-17 07:36 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/tree_shake/asset.rs
> +pub(super) struct SideEffectsModule {
could be in a separate file

2024-10-31 04:32 UTC, ijjk commented
## Failing test suites <!--30318212034-->
Commit: 31c37d28742bd09b681471db8bad5f51a975427c

`pnpm test test/integration/app-dir-export/test/dynamic-missing-gsp-prod.test.ts` (turbopack)
- app dir - with output export - dynamic missing gsp prod > production mode > should error when dynamic route is missing generateStaticParams

<details>
<summary>Expand output</summary>

  ● app dir - with output export - dynamic missing gsp prod › production mode › should error when dynamic route is missing generateStaticParams

    expect(received).toMatch(expected)

    Expected substring: "Page \"/another/[slug]\" is missing \"generateStaticParams()\" so it cannot be used with \"output: export\" config."
    Received string:    " ⚠ Linting is disabled.
     ⚠ Turbopack build collected 1 warnings:
    Page: {\"type\":\"app\",\"side\":\"server\",\"page\":\"/another/[slug]/page\"}
    ./test/integration/app-dir-export/app/another/[slug]/page.js:3:24
    Unable to parse config export in source file
      1 | import Link from 'next/link'
      2 |
    > 3 | export const dynamic = undefined
        |                        ^^^^^^^^^
      4 |
      5 | function noop() {
      6 |   return [{ slug: 'first' }, { slug: 'second' }]·
    The exported configuration object in a source file needs to have a very specific format from which some properties can be statically parsed at compiled-time.·
    https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config··
    Error: Module [project]/packages/next/dist/esm/server/response-cache/types.js [app-route] (ecmascript) <export CachedRouteKind> was instantiated because it was required from module [project]/packages/next/dist/esm/server/response-cache/types.js { side effect 0 => \"[project]/packages/next/dist/esm/server/response-cache/index.js [app-route] (ecmascript) <module evaluation>\" } [app-route] (ecmascript, side effects) <export CachedRouteKind>, but the module factory is not available. It might have been deleted in an HMR update.

      557 |                 invariant(source, (source)=>`Unknown source type: ${source?.type}`);
      558 |         }
    > 559 |         throw new Error(`Module ${id} was instantiated ${instantiationReason}, but the module factory is not available. It might have been deleted in an HMR update.`);
          |               ^
      560 |     }
      561 |     let parents;
      562 |     switch(source.type){

      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:559:15)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)
      at esmImport (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:132:20)
      at [project]/packages/next/dist/esm/server/response-cache/types.js { side effect 0 => \"[project]/packages/next/dist/esm/server/response-cache/index.js [app-route] (ecmascript) <module evaluation>\" } [app-route] (ecmascript, side effects) <export CachedRouteKind> (integration/app-dir-export/.next/server/chunks/[root of the server]__fe2291._.js:1:131049)
      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:589:23)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)
      at esmImport (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:132:20)
      at [project]/packages/next/dist/esm/server/lib/patch-fetch.js [app-route] (ecmascript) <internal part 24> (integration/app-dir-export/.next/server/chunks/[root of the server]__fe2291._.js:1:149788)
      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:589:23)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)·
      > Build error occurred
      Error: Failed to collect page data for /api/json
      at <unknown> (../packages/next/dist/build/utils.js:1233:15) {
        type: 'Error'
      }
      "
      at toMatch (integration/app-dir-export/test/utils.ts:186:29)
      at Object.<anonymous> (integration/app-dir-export/test/dynamic-missing-gsp-prod.test.ts:8:9)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

`pnpm test test/integration/app-dir-export/test/start.test.ts` (turbopack)
- app dir - with output export (next start) > production mode > should error during next start with output export

<details>
<summary>Expand output</summary>

  ● app dir - with output export (next start) › production mode › should error during next start with output export

    command failed with code 1 signal null
     ⚠ Linting is disabled.
       ▲ Next.js 15.0.3-canary.2 (Turbopack)

       Creating an optimized production build ...
       Building (0/11) ...
       Building (2/11) 
       Building (5/11) 
       Building (8/11) 
     ✓ Building (11/11)
     ✓ Compiled successfully in 3.6s
       Checking validity of types ...
       Collecting page data ...
    Error: Module [project]/packages/next/dist/esm/server/response-cache/types.js [app-route] (ecmascript) <export CachedRouteKind> was instantiated because it was required from module [project]/packages/next/dist/esm/server/response-cache/types.js { side effect 0 => "[project]/packages/next/dist/esm/server/response-cache/index.js [app-route] (ecmascript) <module evaluation>" } [app-route] (ecmascript, side effects) <export CachedRouteKind>, but the module factory is not available. It might have been deleted in an HMR update.

      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:559:15)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)
      at esmImport (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:132:20)
      at [project]/packages/next/dist/esm/server/response-cache/types.js { side effect 0 => "[project]/packages/next/dist/esm/server/response-cache/index.js [app-route] (ecmascript) <module evaluation>" } [app-route] (ecmascript, side effects) <export CachedRouteKind> (integration/app-dir-export/.next/server/chunks/[root of the server]__fe2291._.js:1:131049)
      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:589:23)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)
      at esmImport (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:132:20)
      at [project]/packages/next/dist/esm/server/lib/patch-fetch.js [app-route] (ecmascript) <internal part 24> (integration/app-dir-export/.next/server/chunks/[root of the server]__fe2291._.js:1:149788)
      at instantiateModule (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:589:23)
      at getOrInstantiateModuleFromParent (integration/app-dir-export/.next/server/chunks/[turbopack]_runtime.js:644:12)
      > Build error occurred
      Error: Failed to collect page data for /api/json
      at <unknown> (../packages/next/dist/build/utils.js:1233:15) {
        type: 'Error'
      }
      at ChildProcess.<anonymous> (lib/next-test-utils.ts:310:11)

</details>


Read more about building and testing Next.js in [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md).

2024-11-07 07:22 UTC, sokra commented on turbopack/crates/turbopack-ecmascript/src/references/esm/export.rs
> +                export_name.clone(),
Why do we need a clone here now? I think that can be removed?

2024-11-07 08:03 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| buildDuration | 19.6s | 17.4s | N/A |
| buildDurationCached | 16.5s | 14.7s | N/A |
| nodeModulesSize | 404 MB | 404 MB | ✓ |
| nextStartRea..uration (ms) | 471ms | 477ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 5403-HASH.js gzip | 45.6 kB | 45.6 kB | N/A |
| 9015-HASH.js gzip | 5.27 kB | 5.27 kB | N/A |
| 9022.HASH.js gzip | 169 B | 169 B | ✓ |
| e950bafc-HASH.js gzip | 52.5 kB | 52.5 kB | ✓ |
| framework-HASH.js gzip | 57.3 kB | 57.3 kB | N/A |
| main-app-HASH.js gzip | 235 B | 236 B | N/A |
| main-HASH.js gzip | 33.2 kB | 33.2 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 52.6 kB | 52.6 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 192 B | N/A |
| _error-HASH.js gzip | 192 B | 192 B | ✓ |
| amp-HASH.js gzip | 512 B | 512 B | ✓ |
| css-HASH.js gzip | 343 B | 341 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | N/A |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 364 B | N/A |
| hooks-HASH.js gzip | 391 B | 392 B | N/A |
| image-HASH.js gzip | 4.4 kB | 4.41 kB | N/A |
| index-HASH.js gzip | 267 B | 268 B | N/A |
| link-HASH.js gzip | 2.78 kB | 2.78 kB | N/A |
| routerDirect..HASH.js gzip | 326 B | 325 B | N/A |
| script-HASH.js gzip | 394 B | 397 B | N/A |
| withRouter-HASH.js gzip | 323 B | 324 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 1.07 kB | 1.07 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| _buildManifest.js gzip | 747 B | 750 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| index.html gzip | 522 B | 522 B | ✓ |
| link.html gzip | 536 B | 537 B | N/A |
| withRouter.html gzip | 519 B | 518 B | N/A |
| Overall change | 522 B | 522 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| edge-ssr.js gzip | 128 kB | 128 kB | N/A |
| page.js gzip | 198 kB | 198 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 669 B | 668 B | N/A |
| middleware-r..fest.js gzip | 156 B | 156 B | ✓ |
| middleware.js gzip | 31 kB | 31 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 1 kB | 1 kB | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 196-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 196.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 319 kB | 319 kB | ✓ |
| app-page-exp..prod.js gzip | 123 kB | 123 kB | ✓ |
| app-page-tur..prod.js gzip | 136 kB | 136 kB | ✓ |
| app-page-tur..prod.js gzip | 131 kB | 131 kB | ✓ |
| app-page.run...dev.js gzip | 309 kB | 309 kB | ✓ |
| app-page.run..prod.js gzip | 119 kB | 119 kB | ✓ |
| app-route-ex...dev.js gzip | 36 kB | 36 kB | ✓ |
| app-route-ex..prod.js gzip | 24.4 kB | 24.4 kB | ✓ |
| app-route-tu..prod.js gzip | 24.4 kB | 24.4 kB | ✓ |
| app-route-tu..prod.js gzip | 24.2 kB | 24.2 kB | ✓ |
| app-route.ru...dev.js gzip | 37.6 kB | 37.6 kB | ✓ |
| app-route.ru..prod.js gzip | 24.2 kB | 24.2 kB | ✓ |
| pages-api-tu..prod.js gzip | 9.59 kB | 9.59 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.4 kB | 11.4 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.58 kB | 9.58 kB | ✓ |
| pages-turbo...prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| pages.runtim...dev.js gzip | 26.5 kB | 26.5 kB | ✓ |
| pages.runtim..prod.js gzip | 20.9 kB | 20.9 kB | ✓ |
| server.runti..prod.js gzip | 915 kB | 915 kB | ✓ |
| Overall change | 2.32 MB | 2.32 MB | ✓ |

</details>

<details>
<summary><strong>build cache</strong> Overall increase ⚠️</summary>

|  | vercel/next.js canary  | vercel/next.js kdy1/ts-reexport-all | Change |
| - | - | - | - |
| 0.pack gzip | 2.01 MB | 2.01 MB | ⚠️ +1.85 kB |
| index.pack gzip | 145 kB | 145 kB | ⚠️ +350 B |
| Overall change | 2.15 MB | 2.15 MB | ⚠️ +2.2 kB |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>page.js</strong></summary>

```diff
@@ -15,7 +15,7 @@
       /***/
     },
 
-    /***/ 1196: /***/ (
+    /***/ 6124: /***/ (
       __unused_webpack_module,
       __webpack_exports__,
       __webpack_require__
@@ -30,7 +30,7 @@
         default: () => /* binding */ nHandler,
       });
 
-      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-66855b96-20241106_re_tjdjcv66rjwb4lr57yec3cy6dm/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsVnNFZD%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
+      // NAMESPACE OBJECT: ./node_modules/.pnpm/next@file+..+diff-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-66855b96-20241106_re_7lkajdsgoih2to5bkepll3tc3y/node_modules/next/dist/build/webpack/loaders/next-app-loader/index.js?name=app%2Fapp-edge-ssr%2Fpage&page=%2Fapp-edge-ssr%2Fpage&pagePath=private-next-app-dir%2Fapp-edge-ssr%2Fpage.js&appDir=%2Ftmp%2Fnext-statsVnNFZD%2Fstats-app%2Fapp&appPaths=%2Fapp-edge-ssr%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&flyingShuttle=false&preferredRegion=&middlewareConfig=e30%3D!./app/app-edge-ssr/page.js?__next_edge_ssr_entry__
       var page_next_edge_ssr_entry_namespaceObject = {};
       __webpack_require__.r(page_next_edge_ssr_entry_namespaceObject);
       __webpack_require__.d(page_next_edge_ssr_entry_namespaceObject, {
@@ -83,35 +83,35 @@
         workUnitAsyncStorage: () => entry_base /* workUnitAsyncStorage */.FP,
       });
 
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-66855b96-20241106_re_tjdjcv66rjwb4lr57yec3cy6dm/node_modules/next/dist/esm/server/web/globals.js
-      var globals = __webpack_require__(6049);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-66855b96-20241106_re_tjdjcv66rjwb4lr57yec3cy6dm/node_modules/next/dist/esm/server/web/adapter.js + 3 modules
-      var adapter = __webpack_require__(213);
-      // EXTERNAL MODULE: ./node_modules/.pnpm/next@file+..+main-repo+packages+next+next-packed.tgz_react-dom@19.0.0-rc-66855b96-20241106_re_tjdjcv66rjwb4lr57yec3c [...]

2024-11-18 03:11 UTC, kdy1 commented on turbopack/crates/turbopack-ecmascript/src/references/mod.rs
> +                        if !is_side_effect_free {
Without this change, all next.js tests pass (CI) but the side-effect-optimization unit test fails because of `non-existing.js`.

2024-11-18 06:15 UTC, kdy1 commented
# Investigation of CI failure:

```js
# Module 2
var TracesSamplerValues;
export { TracesSamplerValues as a };

# Module 3
import { a as TracesSamplerValues } from "__TURBOPACK_PART__" with {
    __turbopack_part__: -2
};
(function(TracesSamplerValues) {
    TracesSamplerValues["AlwaysOff"] = "always_off";
    TracesSamplerValues["AlwaysOn"] = "always_on";
    TracesSamplerValues["ParentBasedAlwaysOff"] = "parentbased_always_off";
    TracesSamplerValues["ParentBasedAlwaysOn"] = "parentbased_always_on";
    TracesSamplerValues["ParentBasedTraceIdRatio"] = "parentbased_traceidratio";
    TracesSamplerValues["TraceIdRatio"] = "traceidratio";
})(TracesSamplerValues || (TracesSamplerValues = {}));
```

Module 3 is skipped because it was treated as a side effect.

2024-11-18 09:47 UTC, sokra requested changes
enable the test case for the side effects optimization

2024-11-19 08:01 UTC, kdy1 reviewed
@sokra I extracted changes required to enable the tree shaking cargo test case to https://github.com/vercel/next.js/pull/72947

2024-11-19 08:36 UTC, sokra approved these changes

2024-11-19 09:53 UTC, merged