[next@14] Update eslint-plugin-react-hooks to stable v5
vercel/next.js pull request #71291
Opened 2024-10-15 07:03 UTC by lorand-horvath

eslint-plugin-react-hooks should be bumped to stable v5 for next@14 as well.
Justification here: https://github.com/vercel/next.js/pull/71218#issuecomment-2413171398

2024-10-15 07:03 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: cf2bc7549e2829206a504802c342c3be9797971f

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-10-15 08:56 UTC, eps1lon requested changes
Using `eslint-plugin-react-hooks@5.x` is a breaking change. If anything, we should backport a downgrade. Existing apps just didn't see the breaking change during upgrade when they were using lockfiles.

2024-10-15 10:24 UTC, lorand-horvath commented
> Using `eslint-plugin-react-hooks@5.x` is a breaking change.

@eps1lon Why so? At the moment next@14 has a dependency on `^4.5.0 || 5.0.0-canary-7118f5dd7-20230705`. I actually wonder why the 5.0.0-canary (from July 2023) was added in the first place? I have a justification for why v5 is a better solution, if you don't mind reading it, here: https://github.com/vercel/next.js/pull/71218#issuecomment-2413171398

Also eslint-plugin-react-hooks@5 supports eslint versions ^3 to ^9 as per https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/package.json

Anyway, if v5 is not acceptable, I can modify the PR to downgrade it to ^4.6.2.

2024-10-15 10:30 UTC, eps1lon commented
> Using eslint-plugin-react-hooks@5.x is a breaking change.

Generally, because it's released in a SemVer major. Here specifically, it's the introduction of a new violation.

It's not a critical fix. Technically breaking again if you already relied on the new behavior considering for how long this has been out there. I don't see a path to safely backport nor the urgency to do this. You could always use `resolutions` or `overrides` to fix it.

2024-10-15 21:39 UTC, ijjk submitted a review, later dismissed

2025-01-22 00:00 UTC, ijjk commented
# Stats from current PR

<details open>
<summary><strong>Default Build</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| buildDuration | 19s | 26.4s | ⚠️ +7.3s |
| buildDurationCached | 15.2s | 12.9s | N/A |
| nodeModulesSize | 418 MB | 417 MB | N/A |
| nextStartRea..uration (ms) | 406ms | 428ms | N/A |

</details>

<details>
<summary><strong>Client Bundles (main, webpack)</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| 5306-HASH.js gzip | 54 kB | 53.3 kB | N/A |
| 8276.HASH.js gzip | 169 B | 168 B | N/A |
| 8377-HASH.js gzip | 5.46 kB | 5.44 kB | N/A |
| bccd1874-HASH.js gzip | 52.9 kB | 52.9 kB | N/A |
| framework-HASH.js gzip | 57.5 kB | 57.5 kB | N/A |
| main-app-HASH.js gzip | 240 B | 242 B | N/A |
| main-HASH.js gzip | 34.4 kB | 34.2 kB | N/A |
| webpack-HASH.js gzip | 1.71 kB | 1.71 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 39.4 kB | 39.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| _app-HASH.js gzip | 193 B | 193 B | ✓ |
| _error-HASH.js gzip | 193 B | 193 B | ✓ |
| amp-HASH.js gzip | 512 B | 510 B | N/A |
| css-HASH.js gzip | 343 B | 342 B | N/A |
| dynamic-HASH.js gzip | 1.84 kB | 1.84 kB | ✓ |
| edge-ssr-HASH.js gzip | 265 B | 265 B | ✓ |
| head-HASH.js gzip | 363 B | 362 B | N/A |
| hooks-HASH.js gzip | 393 B | 392 B | N/A |
| image-HASH.js gzip | 4.59 kB | 4.57 kB | N/A |
| index-HASH.js gzip | 268 B | 268 B | ✓ |
| link-HASH.js gzip | 2.35 kB | 2.34 kB | N/A |
| routerDirect..HASH.js gzip | 328 B | 328 B | ✓ |
| script-HASH.js gzip | 397 B | 397 B | ✓ |
| withRouter-HASH.js gzip | 323 B | 326 B | N/A |
| 1afbb74e6ecf..834.css gzip | 106 B | 106 B | ✓ |
| Overall change | 3.59 kB | 3.59 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 748 B | 747 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| index.html gzip | 525 B | 524 B | N/A |
| link.html gzip | 539 B | 537 B | N/A |
| withRouter.html gzip | 521 B | 520 B | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Edge SSR bundle Size</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| edge-ssr.js gzip | 129 kB | 129 kB | N/A |
| page.js gzip | 208 kB | 207 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Middleware size</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| middleware-b..fest.js gzip | 671 B | 667 B | N/A |
| middleware-r..fest.js gzip | 155 B | 156 B | N/A |
| middleware.js gzip | 31.3 kB | 31.2 kB | N/A |
| edge-runtime..pack.js gzip | 844 B | 844 B | ✓ |
| Overall change | 844 B | 844 B | ✓ |

</details>

<details>
<summary><strong>Next Runtimes</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| 274-experime...dev.js gzip | 322 B | 322 B | ✓ |
| 274.runtime.dev.js gzip | 314 B | 314 B | ✓ |
| app-page-exp...dev.js gzip | 375 kB | 369 kB | N/A |
| app-page-exp..prod.js gzip | 130 kB | 130 kB | N/A |
| app-page-tur..prod.js gzip | 143 kB | 142 kB | N/A |
| app-page-tur..prod.js gzip | 139 kB | 138 kB | N/A |
| app-page.run...dev.js gzip | 363 kB | 357 kB | N/A |
| app-page.run..prod.js gzip | 126 kB | 126 kB | N/A |
| app-route-ex...dev.js gzip | 37.6 kB | 37.6 kB | N/A |
| app-route-ex..prod.js gzip | 25.6 kB | 25.6 kB | N/A |
| app-route-tu..prod.js gzip | 25.6 kB | 25.6 kB | N/A |
| app-route-tu..prod.js gzip | 25.4 kB | 25.4 kB | N/A |
| app-route.ru...dev.js gzip | 39.2 kB | 39.2 kB | N/A |
| app-route.ru..prod.js gzip | 25.4 kB | 25.4 kB | N/A |
| pages-api-tu..prod.js gzip | 9.69 kB | 9.69 kB | ✓ |
| pages-api.ru...dev.js gzip | 11.6 kB | 11.6 kB | ✓ |
| pages-api.ru..prod.js gzip | 9.68 kB | 9.68 kB | ✓ |
| pages-turbo...prod.js gzip | 21.9 kB | 21.7 kB | N/A |
| pages.runtim...dev.js gzip | 27.7 kB | 27.5 kB | N/A |
| pages.runtim..prod.js gzip | 21.9 kB | 21.7 kB | N/A |
| server.runti..prod.js gzip | 916 kB | 916 kB | N/A |
| Overall change | 31.6 kB | 31.6 kB | ✓ |

</details>

<details>
<summary><strong>build cache</strong></summary>

|  | vercel/next.js canary  | skushagra/next.js patch-3 | Change |
| - | - | - | - |
| 0.pack gzip | 2.1 MB | 2.09 MB | N/A |
| index.pack gzip | 74.7 kB | 74.4 kB | N/A |
| Overall change | 0 B | 0 B | ✓ |

</details>

<details>
<summary><strong>Diff details</strong></summary>

<details>
<summary>Diff for <strong>middleware.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>edge-ssr.js</strong></summary>

Diff too large to display
</details>
<details>
<summary>Diff for <strong>image-HASH.js</strong></summary>

```diff
@@ -1,7 +1,7 @@
 (self["webpackChunk_N_E"] = self["webpackChunk_N_E"] || []).push([
   [2983],
   {
-    /***/ 3705: /***/ (
+    /***/ 8255: /***/ (
       __unused_webpack_module,
       __unused_webpack_exports,
       __webpack_require__
@@ -9,7 +9,7 @@
       (window.__NEXT_P = window.__NEXT_P || []).push([
         "/image",
         function () {
-          return __webpack_require__(8448);
+          return __webpack_require__(8926);
         },
       ]);
       if (false) {
@@ -18,7 +18,7 @@
       /***/
     },
 
-    /***/ 7342: /***/ (module, exports, __webpack_require__) => {
+    /***/ 4369: /***/ (module, exports, __webpack_require__) => {
       "use strict";
       /* __next_internal_client_entry_do_not_use__  cjs */
       Object.defineProperty(exports, "__esModule", {
@@ -40,17 +40,17 @@
         __webpack_require__(6049)
       );
       const _head = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(7196)
+        __webpack_require__(956)
       );
-      const _getimgprops = __webpack_require__(2661);
-      const _imageconfig = __webpack_require__(72);
-      const _imageconfigcontextsharedruntime = __webpack_require__(6386);
-      const _warnonce = __webpack_require__(4496);
-      const _routercontextsharedruntime = __webpack_require__(6443);
+      const _getimgprops = __webpack_require__(485);
+      const _imageconfig = __webpack_require__(4664);
+      const _imageconfigcontextsharedruntime = __webpack_require__(1250);
+      const _warnonce = __webpack_require__(1648);
+      const _routercontextsharedruntime = __webpack_require__(907);
       const _imageloader = /*#__PURE__*/ _interop_require_default._(
-        __webpack_require__(3433)
+        __webpack_require__(6489)
       );
-      const _usemergedref = __webpack_require__(1942);
+      const _usemergedref = __webpack_require__(5942);
       // This is replaced by webpack define plugin
       const configEnv = {
         deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
@@ -377,7 +377,7 @@
       /***/
     },
 
-    /***/ 1942: /***/ (module, exports, __webpack_require__) => {
+    /***/ 5942: /***/ (module, exports, __webpack_require__) => {
       "use strict";
 
       Object.defineProperty(exports, "__esModule", {
@@ -391,39 +391,22 @@
       });
       const _react = __webpack_require__(8101);
       function useMergedRef(refA, refB) {
-        const cleanupA = (0, _react.useRef)(null);
-        const cleanupB = (0, _react.useRef)(null);
-        // NOTE: I [...]

2025-01-22 08:13 UTC, closed without merging