Fix checking for protocol relative URLs in image optimization when parameter starts with encoded slashes
vercel/next.js pull request #72100
Opened 2024-10-30 18:32 UTC by jpreynat

### What?

This PR improves the security of the `_next/image` endpoint by making sure that url parameters starting with multiple escaped slashes are properly detected as protocol relative ones.

### Why?

For some reason, the `new URL()` constructor behaves very strangely with this, as it can accept any number of forward slashes and backslashes, and it will still consider the URL as protocol relative, discarding any hostname passed as second argument.

So except for `new URL('\\example.com', 'https://n')`, that properly returns `'https://n/example.com'`, all of these:
- `new URL('\//example.com', 'https://n')`
- `new URL('/\//example.com', 'https://n')`
- `new URL('/\\example.com', 'https://n')`
- `new URL('/\\/example.com', 'https://n')`
-  `new URL('/\\/\/\/\/example.com', 'https://n')`

will actually return `'https://example.com/'`.

### How?

To prevent this from happening, this PR transforms all consecutive slashes and backslashes, when there are more than 2, into `//` when we check if the `url` starts by `//`, a protocol relative URL.

2024-10-30 18:33 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: d576ce8f557c27a6e74b295e2b706f894db44dca

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-11-01 12:48 UTC, timneutkens requested changes
After having a quick look I don't think we should change the url handling. If it doesn't allow in `new URL` it should throw an error / bad request instead

2024-11-01 13:02 UTC, jpreynat commented
Hi @timneutkens 👋 
Thanks for your reply.

Just to confirm, you suggest going with a new kind of check and error specifically for this, after checking if the URL starts with double slashes, but before the more complex checks for absolute/relative URL patterns, right?
I agree that it can otherwise be misleading, but since these URLs can, for some reason and though improperly, still be parsed by the `new URL` constructor, I wasn’t sure. But if we agree on the above, that sounds good to me 👍

2024-11-04 12:42 UTC, timneutkens commented
Yeah adding a special case for `//`. However I'm still not sure if we really should do that given that I think we also want to support protocol-relative urls?

2024-11-04 16:37 UTC, jpreynat commented
Well, protocol-relative URLs were already rejected in https://github.com/vercel/next.js/pull/65752
This PR only adds better detection for similar URLs when escaped slashes and backslashes are used, but that result in identical URLs under the hood.

2024-11-07 14:42 UTC, jpreynat commented
@timneutkens I made the changes to have it as a separate error, thanks for having another look

2024-11-07 15:48 UTC, styfle commented on packages/next/src/server/image-optimizer.ts
> +    if (INVALID_URL_REGEX.test(url)) {
Line 238 already handles `//` which would also handle `///`.

I think you can change this to the following:

```suggestion
    if (url.startsWith('\\') {
```

2024-11-07 15:54 UTC, styfle commented on packages/next/src/server/image-optimizer.ts
> +      return { errorMessage: '"url" parameter is invalid' }
```suggestion
      return { errorMessage: '"url" parameter cannot start with backslash' }
```

Let's be more specific here so we can confirm the new tests are hitting this condition.

2024-11-07 16:02 UTC, styfle requested changes
Thanks for the PR!

I am not able to reproduce the issue, can you share the url you are visiting that is optimizing an image?

For example, this fails as I would expect:

```
http://localhost:3000/_next/image?url=%5C%5Cimage-optimization-one.vercel.app%2Ffrog.png&w=828&q=75
```

And thats because `new URL('\\image-optimization-one.vercel.app%2Ffrog.png')` also fails.

https://github.com/vercel/next.js/blob/1c219b1660ea751ca6624e483807ab490587934e/packages/next/src/server/image-optimizer.ts#L264

2024-11-13 10:21 UTC, jpreynat commented
@styfle Thanks for your review and comments.
Actually you're right, I've made more testing and it seems that indeed, URLs are properly rejected when needed.
I was surprised because we are using Next in a specific environment and in this specific scenario, URLs are converted, but it looks like it's actually due to our proxying in place rather than Next.

I'm going to close the PR for now, and will reopen it in case I can actually come back to an issue in Next.

2024-11-13 10:21 UTC, closed without merging

2024-11-13 18:44 UTC, styfle commented
Thanks!

In the future, this type of bug looks more like a vulnerability so it would be best to disclose privately.

See https://github.com/vercel/next.js/security

2024-11-14 13:12 UTC, jpreynat commented
Duly noted @styfle, thanks again for your help 👍