Clarify serialization behavior of "use cache"
vercel/next.js pull request #72286
Opened 2024-11-04 19:55 UTC by gaearon

Maybe not ideal wording but this should be more correct. See https://github.com/vercel/next.js/pull/72081#discussion_r1828278059.

2024-11-04 19:56 UTC, ijjk commented
Allow CI Workflow Run

- [ ] approve CI run for commit: 27a5f95e8ef5b75232fb0398e8d6885c9f217fa0

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

2024-11-04 20:09 UTC, gaearon commented
slightly reworded.

2024-11-04 20:53 UTC, unstubbable approved these changes
Sounds good to me. Requested a review from @delbaoliveira for final approval.

2024-11-05 07:37 UTC, delbaoliveira requested changes
Thank you for further clarifying it Dan.

Tbh, the how `use cache` information is so essential that shouldn't live under a good to know. I'll move it out to its own in the future.

2024-11-05 07:37 UTC, delbaoliveira commented on docs/02-app/02-api-reference/01-directives/use-cache.mdx
> +- Any [serializable](https://react.dev/reference/rsc/use-server#serializable-parameters-and-return-values) arguments (or props) to the cached function, as well as any serializable values it reads fro
```suggestion
- Any [serializable](https://react.dev/reference/rsc/use-server#serializable-parameters-and-return-values) arguments (or props) passed to the cached function, as well as any serializable values it reads from the parent scope, will be converted to a format like JSON and automatically become a part of the cache key.
```

2024-11-05 07:37 UTC, delbaoliveira commented on docs/02-app/02-api-reference/01-directives/use-cache.mdx
> +- Any non-serializable arguments, props, or closed-over values will turn into opaque references inside the cached function. For example, a cached function can take some JSX as a `children` prop and r
```suggestion
- Any non-serializable arguments, props, or closed-over values will turn into opaque references inside the cached function, and can be only passed through and not inspected nor modified. These non-serializable values will be filled in at the request time and won't become a part of the cache key.
  - For example, a cached function can take in JSX as a `children` prop and return `<div>{children}</div>`, but it won't be able to introspect the actual `children` object. 
```

2024-11-05 13:05 UTC, delbaoliveira approved these changes

2024-11-05 20:41 UTC, ijjk approved these changes

2024-11-05 20:43 UTC, merged