Updated typescript examples
vercel/next.js pull request #7337
Opened 2019-05-15 05:22 UTC by resir014

* Removed class component examples to focus on FC usage
* Rename list example to "initial props"
* Updated layout component to reflect new examples

2019-05-15 12:38 UTC, Timer requested changes
Many people still use classes -- can we please keep at least one example of both? 🙏

2019-05-15 18:13 UTC, resir014 commented
@Timer Whoops, alright then, I'll undo the changes in the `/detail` page. 🙏 

I've also updated the `tsconfig.json` file since `next dev` auto-fixed some config items along with it.

2019-05-16 02:02 UTC, lfades commented
@resir014 Thank you 💯

2019-05-16 02:03 UTC, lfades approved these changes

2019-05-16 02:04 UTC, merged