with-cookie-auth: don't rely on the Host header
vercel/next.js pull request #7435
Opened 2019-05-27 18:56 UTC by dunglas

Relying on the `Host` HTTP header [is a bad practice that can lead to severe security vulnerabilities](https://dzone.com/articles/what-is-a-host-header-attack).

Even the code contained in this example can cause some damages:

    curl -H 'Host: attacker.com'  http://localhost:3000/profile

It forces the server to make an HTTP request to `http://attacker.com/api/profile.js`. It may among other things:

* reveal the origin IP address of your server, that you may want to hide (for instance when using DDOS protection systems such as CloudFlare)
* give many details about your platform including the User Agent of the HTTP client you use, or even [the exact version of the OS your server uses](https://www.infoq.com/articles/tcp-syn-security-unauthorized-os/)
* allow an attacker to amplify a DDOS attack using your infrastructure

This PR fixes the issue by storing the API URL in the configuration instead of relying on untrusted headers.

2019-05-27 20:36 UTC, lfades commented on examples/with-cookie-auth/www/next.config.js
> +  publicRuntimeConfig: {
Use `env:` instead, https://nextjs.org/docs#build-time-configuration

2019-05-27 20:37 UTC, lfades commented
@j0lv3r4 Can you review this PR 🙏

2019-05-27 21:25 UTC, Timer requested changes

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/next.config.js
> +  publicRuntimeConfig: {
```suggestion
  env: {
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/login.js
> +import getConfig from 'next/config'
```suggestion
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/login.js
> +const { publicRuntimeConfig } = getConfig()
```suggestion
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/login.js
> +const { API_URL } = publicRuntimeConfig
```suggestion
const { API_URL } = process.env
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/profile.js
> +import getConfig from 'next/config'
```suggestion
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/profile.js
> +const { publicRuntimeConfig } = getConfig()
```suggestion
```

2019-05-27 21:25 UTC, Timer commented on examples/with-cookie-auth/www/pages/profile.js
> +const { API_URL } = publicRuntimeConfig
```suggestion
const { API_URL } = process.env
```

2019-05-27 22:21 UTC, j0lv3r4 commented
@lfades sure! 

Hey, @dunglas. This looks awesome. Thank you.

I think once the changes @Timer and @lfades suggested are done, this will be ready to merge.

2019-05-28 23:25 UTC, lfades commented
@dunglas Did you test it after the changes ? afaik destructuring in `process.env` will only work in the server, but in the client it's `undefined`, so unless I'm wrong change the following:
```js
const { API_URL } = process.env
```
with
```js
const API_URL = process.env.API_URL
```

2019-05-29 11:06 UTC, timneutkens commented
@lfades is correct, destructuring doesn't work, it has to be written in full as the value itself is replaced.

2019-05-29 17:41 UTC, dunglas commented
Hi, no I just merged the suggestions for now. I'll test it (and fix it) asap.

2019-06-04 21:26 UTC, dunglas commented
Unfortunately, it doesn't work. `process.env.API_URL` is `undefined` when using using build time config (it works when using runtime config). Any idea why?

2019-06-06 19:48 UTC, lfades commented
@dunglas No idea, I'm going to clone the repo and check why

2019-06-06 21:24 UTC, lfades commented
@dunglas @j0lv3r4 Try the example again, it should be working now 👍

2019-06-07 09:44 UTC, dunglas commented
@lfades I confirm that it works properly. Thank you!

2019-06-07 17:47 UTC, lfades approved these changes

2019-06-07 18:18 UTC, merged