Randomize the port returned from test util's findPort().
vercel/next.js pull request #753
Opened 2017-01-12 19:40 UTC by arunoda

Otherwise, it'll use 8000 always.
It's much better and safer to randomize the basePort.

2017-01-12 19:59 UTC, rauchg commented
Still not very robust. Why not ephemeral ports given by `listen()` ?

2017-01-12 21:31 UTC, sedubois commented
Random behavior in tests is nice but can also lead to randomly failing tests sometimes hard to track down (saw that in my previous company). How about testing several startups using a predefined list of ports?

2017-01-12 21:45 UTC, rauchg commented
Can you elaborate? How are ephemeral ports error pone?

2017-01-13 01:14 UTC, arunoda commented
> Random behavior in tests is nice but can also lead to randomly failing tests sometimes hard to track down

This is not true. We use [portfinder](https://www.npmjs.com/package/portfinder) and it'll give an available port. It starts with 8000.
Here we've randomized that.

2017-01-13 01:17 UTC, arunoda commented
> Still not very robust. Why not ephemeral ports given by listen() ?

That's a good idea. I'll update.

2017-01-13 02:20 UTC, arunoda commented
@rauchg updated as you suggested.

2017-01-13 02:37 UTC, rauchg requested changes

2017-01-13 02:37 UTC, rauchg commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/prr/-/prr-0.0.0.tgz#1a84b85908325501411853d0081ee3fa86e2926a"
when you remove a project, you need to re-instantiate the lock. we should be seeing red here, for portmapper

2017-01-13 05:45 UTC, arunoda commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/prr/-/prr-0.0.0.tgz#1a84b85908325501411853d0081ee3fa86e2926a"
Yep yep. Need to do it. I use both npm and yarn at the same time. That's a bad habit. 

Will update.

2017-01-13 06:07 UTC, sedubois commented
> Can you elaborate?

I was just speaking in a general context. A test which is based on random behavior isn't repeatable. It might start to fail sometimes but not every time, might be quite unsettling. A test (explicitly or not) has 3 parts: the "given", the "when" and the "then". It would be quite helpful to know the "given" just by reading the source code.

2017-01-13 06:08 UTC, rauchg commented
But the randomness of the port has no impact in the outcome, correct? Specially considering that ephemeral ports (via `listen()`) always give us a free port.

2017-01-13 06:27 UTC, arunoda commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/prr/-/prr-0.0.0.tgz#1a84b85908325501411853d0081ee3fa86e2926a"
@rauchg done.

2017-01-13 07:41 UTC, sedubois commented
If the randomness has no impact on the outcome, why do you use it? Why make this PR in that case?

2017-01-13 07:54 UTC, rauchg commented
Because let's say you have something running on port 8000, the tests would have failed for the _wrong_ reason

2017-01-13 08:45 UTC, sedubois commented
I think I just haven't understood why that port would be randomly unavailable in the first place. Normally the point of a test env is to offer a reproducible context.

Anyways can just discard my comments, it's just that the subject of randomness triggered some sensitive memories from a past life at F-Secure 😄

2017-01-13 09:17 UTC, sedubois commented
I hope the port isn't randomly unavailable in the test automation env? So it's on some developers' laptops that the issue arises? Then other option than randomness might be to allow the dev to configure the port when running tests (with a sensible default).

2017-01-13 09:41 UTC, arunoda commented
I think here we started to randomize the base port. But now we are doing something else.
We let node's http module to pick an available port and use for the test app.

2017-01-13 09:48 UTC, sedubois commented
Other issue with random port is that it might hide the fact that another instance of the tests might have been stuck and left running elsewhere on the machine.

2017-01-13 10:09 UTC, arunoda commented
@sedubois we always run test in parallel and Jest know how to report them well.

> it might hide the fact that another instance of the tests might have been stuck and left running elsewhere on the machine.

Let's ignore this case for now. Let's do things one by one.
We can create a new issue and continue.

This is a good improvement compared with the current setup as we longer using  `portfinder`.

2017-01-13 10:28 UTC, sedubois commented
👍

2017-01-13 17:11 UTC, rauchg commented
> I just hadn't understood why that port would be randomly unavailable in the first place. Normally the point of a test env is to offer a reproducible context.

@sedubois sure but we also run tests upon `prepush`, `prepublish`, so the tests have to be useful on developer machines

2017-01-13 17:11 UTC, rauchg commented
Thanks for your input @sedubois, always much appreciated

2017-02-09 12:57 UTC, timneutkens commented
@arunoda updated the branch https://github.com/arunoda/next.js/pull/1.

2017-02-09 13:27 UTC, timneutkens approved these changes
Looks good 👍 @arunoda ready for merge?

2017-02-09 13:30 UTC, arunoda commented
I think this is good to merge.

2017-02-09 13:40 UTC, merged

2017-02-09 13:40 UTC, timneutkens commented
Awesome ❤️

2017-02-09 13:47 UTC, nkzawa commented on package.json
> -    "react-dom": "15.4.2",
Please don't remove `react` and `react-dom`. Tests fail when you did clean install.

2017-02-09 13:55 UTC, timneutkens commented on package.json
> -    "react-dom": "15.4.2",
Ah right, my fault when resolving merge conflicts.