Add initial static indicator
vercel/next.js pull request #7682
Opened 2019-06-27 04:52 UTC by ijjk

Adds an indicator to signify that a page will be auto exported. Follows the build indicator's style

2019-06-27 06:57 UTC, timneutkens commented
Can you add a gif/screenshot?

2019-07-02 21:10 UTC, Timer requested changes
![overlap](https://user-images.githubusercontent.com/616428/60546878-48da6d00-9cec-11e9-8575-ed22ff32fe20.gif)

This overlaps with the build indicator, can we adjust? 🙏 

Also, it seems odd that they're at different heights / dimensions.

2019-07-02 21:51 UTC, ijjk commented
Updated, should be side-by-side now

2019-07-03 00:42 UTC, Timer approved these changes

2019-07-03 00:42 UTC, merged