Http methods update for static files and pages
vercel/next.js pull request #7721
Opened 2019-07-01 19:17 UTC by huv1k

This PR only allows `GET` and `HEAD` for `static` files and reverts `POST` on `pages` to return `404`.

2019-07-01 19:20 UTC, Timer requested changes

2019-07-01 19:20 UTC, Timer commented on packages/next-server/server/next-server.ts
> +      res.statusCode = 405
We need to set an appropriate `Allow` header specifiying `GET` and `HEAD`.

2019-07-01 19:20 UTC, Timer commented on packages/next-server/server/next-server.ts
> +      return this.render404(req, res, parsedUrl)
We shouldn't be returning an explicit `404`, the previous implementation just didn't match -- if we're responding on behalf of the user then it should be a `405`. I still think this should follow the old behavior.

2019-07-03 19:57 UTC, Timer approved these changes
I tweaked this to `405` on pages instead of `501` per Slack conversations.

2019-07-03 20:17 UTC, ijjk commented on test/integration/production/test/index.test.js
> +    it('should retrun 405 method on static then GET and HEAD', async () => {
```suggestion
    it('should return 405 method on static then GET and HEAD', async () => {
```

2019-07-03 20:24 UTC, ijjk approved these changes

2019-07-04 08:22 UTC, merged