Replace deprecated fs.exists with fs.access.
vercel/next.js pull request #7742
Opened 2019-07-03 08:52 UTC by imdreamrunner

`fs.exists` is [deprecated](https://nodejs.org/docs/latest-v8.x/api/fs.html#fs_fs_exists_path_callback), and is suggested to use `fs.access` to check file existence.

I was working with @clouddra on this pull request.

2019-07-03 09:33 UTC, Janpot commented
a quick search in github shows that `exists` and `existsSync` are used al over the codebase. Would it make sense to create a helper and reuse it everywhere?

2019-07-03 09:37 UTC, imdreamrunner commented
Thanks @Janpot ! From node.js [documentation](https://nodejs.org/api/fs.html#fs_fs_existssync_path)

> fs.exists() is deprecated, but fs.existsSync() is not. The callback parameter to fs.exists() accepts parameters that are inconsistent with other Node.js callbacks. fs.existsSync() does not use a callback.

I think it makes sense to replace all `fs.exists` usage. Where would you suggest to put such util functions?

2019-07-04 03:00 UTC, imdreamrunner commented
Hi @Janpot I add a new utility file inside the `lib` folder where other `fs` related util functions such as `recursive-delete` are located. All usage of `fs.exists` were replaced with the new utility function. Please help reviewing again. Thank you!

2019-07-04 13:49 UTC, Janpot commented
Well, it makes sense to me. But you'd probably rather want some input of a core maintainer before putting too much work into it.

2019-07-13 02:25 UTC, imdreamrunner commented
Hi maintainers, how can I get this PR to be reviewed? Is there anything missing from this PR. Thanks

2019-07-16 12:19 UTC, timneutkens commented on packages/next/lib/file-exists.ts
> +  } catch (_) {
This should probably check for the specific code, I think it's `ENOENT` from the top of my mind. Otherwise it catches all errors.

2019-07-16 12:20 UTC, timneutkens submitted a review, later dismissed
Looks great! Just had one comment 💯

2019-07-16 19:59 UTC, Timer requested changes

2019-07-16 19:59 UTC, Timer commented on packages/next/lib/file-exists.ts
> +  } catch (_) {
```suggestion
  } catch (err) {
```

2019-07-16 19:59 UTC, Timer commented on packages/next/lib/file-exists.ts
> +    return false
```suggestion
    if (err.code === 'ENOENT') {
      return false
    }
    throw err
```

2019-07-17 06:00 UTC, Timer approved these changes
Looks good!

2019-07-17 06:01 UTC, merged

2019-07-17 06:03 UTC, imdreamrunner commented
Thanks @timneutkens for reviewing and @Timer  for fixing the issue!

2019-07-17 06:07 UTC, Timer commented
Thank you for contributing, @imdreamrunner!