Upgrade next.js version of custom-typescript-server example
vercel/next.js pull request #7772
Opened 2019-07-08 06:07 UTC by Rokt33r

2019-07-08 12:52 UTC, resir014 requested changes
I was planning to do this over the weekend but I forgot about it. This looks great! Just a couple things in mind:

2019-07-08 12:52 UTC, resir014 commented on examples/custom-server-typescript/package.json
>      "@types/next": "^8.0.5",
We don't need this anymore since Next.js typings are included by default. We can replace this with `@types/node`.

2019-07-08 12:52 UTC, resir014 commented on examples/custom-server-typescript/package.json
> +    "next": "^8.1.1-canary.69",
Bump this version up to `^9.0.0` since it's published already.

2019-07-09 17:20 UTC, huv1k approved these changes

2019-07-09 17:23 UTC, Timer commented
Thanks!!

2019-07-09 17:24 UTC, merged