[WIPConfiguration for body parsing size limit
vercel/next.js pull request #7896
Opened 2019-07-11 15:44 UTC by huv1k

2019-07-12 21:55 UTC, lfades commented on packages/next/README.md
> +Body parsing is enabled by default and size limit of parsed body is `1mb`.
```suggestion
Body parsing is enabled by default with a size limit of `1mb` for the parsed body.
```

2019-07-12 21:59 UTC, lfades submitted a review, later dismissed

2019-07-16 11:53 UTC, timneutkens commented on packages/next-server/server/api-utils.ts
> +      req.body = await parseBody(req, bodySizeLimit)
Can't this be: 

```suggestion
      req.body = await parseBody(req, config.api && config.api.bodySizeLimit ? config.api.bodySizeLimit : '1mb')
```

2019-07-17 02:22 UTC, Timer requested changes

2019-07-17 02:22 UTC, Timer commented on packages/next/README.md
> +[![Next.js](h
Seems this was broken.

2019-07-17 02:22 UTC, Timer commented on packages/next-server/types/index.d.ts
> +    bodySizeLimit?: number | string
This should be merged into the `bodyParser` key IMO.

e.g.
```ts
api?: { 
  bodyParser?: { sizeLimit?: number | string } | false 
}

2019-07-25 15:43 UTC, Timer approved these changes

2019-07-25 15:43 UTC, merged