Added Google AMP example
vercel/next.js pull request #793
Opened 2017-01-16 16:30 UTC by impronunciable

Related to #744

2017-01-16 16:31 UTC, impronunciable commented
And it validates:

![screen shot 2017-01-16 at 1 21 29 pm](https://cloud.githubusercontent.com/assets/165799/21991102/137d3986-dbf0-11e6-8986-70bb73087d27.png)

2017-01-16 17:18 UTC, rauchg commented
This is really awesome. The only thing I wonder about is how one would do "The AMP version" of a site. Should that be handled at the proxy level, and you set up two Next apps?

2017-01-16 17:26 UTC, frol commented on examples/with-amp/pages/_document.js
> +import { DOMProperty } from 'react-dom/../lib/ReactInjection'
Could you, please, shed some light on what this hack is about?

2017-01-16 17:28 UTC, impronunciable commented on examples/with-amp/pages/_document.js
> +import { DOMProperty } from 'react-dom/../lib/ReactInjection'
Yes, there is an issue with the path resolution, I had to do a hack as you guessed :P more than happy to change it for a more elegant solution

2017-01-16 17:46 UTC, nkzawa commented on examples/with-amp/pages/_document.js
> +          <div id='__next' dangerouslySetInnerHTML={{ __html: html }} />
maybe `html` includes `data-reactid` things ? Ideally, we'd like to render the html by `ReactDOMServer.renderToStaticMarkup`.

2017-01-16 18:05 UTC, impronunciable commented on examples/with-amp/pages/_document.js
> +          <div id='__next' dangerouslySetInnerHTML={{ __html: html }} />
@nkzawa The idea is to override `getInitialProps` on the custom document and get that html?

2017-01-16 18:24 UTC, nkzawa commented on examples/with-amp/pages/_document.js
> +          <div id='__next' dangerouslySetInnerHTML={{ __html: html }} />
yep, though we don't support it for now 😂

2017-01-16 18:56 UTC, sedubois commented on examples/with-amp/README.md
> +Download the example [or clone the repo](https://github.com/zeit/next.js.git):
(.git isn't needed)

2017-01-16 18:57 UTC, impronunciable commented on examples/with-amp/README.md
> +Download the example [or clone the repo](https://github.com/zeit/next.js.git):
I think this was because of `git clone https://github.com/zeit/next.js.git`

2017-01-16 18:58 UTC, sedubois commented on examples/with-amp/README.md
> +Download the example [or clone the repo](https://github.com/zeit/next.js.git):
`git clone https://github.com/zeit/next.js` also works

2017-01-17 01:05 UTC, arunoda commented on examples/with-amp/pages/_document.js
> +import { DOMProperty } from 'react-dom/../lib/ReactInjection'
@impronunciable would like to know about more info.
What was the problem?

2017-01-17 01:14 UTC, impronunciable commented
Sure, if you remove the ../ you'll see next complaining about a missing
import

On Mon, Jan 16, 2017, 10:05 PM Arunoda Susiripala <notifications@github.com>
wrote:

> *@arunoda* commented on this pull request.
> ------------------------------
>
> In examples/with-amp/pages/_document.js
> <https://github.com/zeit/next.js/pull/793>:
>
> > @@ -0,0 +1,27 @@
> +import Document, { Head } from 'next/document'
> +import { DOMProperty } from 'react-dom/../lib/ReactInjection'
>
> @impronunciable <https://github.com/impronunciable> would like to know
> about more info.
> What was the problem?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/zeit/next.js/pull/793>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKHp4iuSgzEdzWM03Cr34jvC4XuVK7Rks5rTBPOgaJpZM4Lkv-f>
> .
>

2017-01-17 01:25 UTC, arunoda commented
@impronunciable okay. Let's see.

2017-01-23 19:57 UTC, impronunciable commented
@arunoda Had you have time to see this?

2017-01-24 00:35 UTC, arunoda commented on examples/with-amp/pages/index.js
> +import Link from 'next/prefetch'
You can use `next/link` here.
Anyway, you don't need it at all. Simply use the `a` tag since there's no any client side next.

2017-01-24 00:40 UTC, arunoda commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
I just removed this and it didn't trigger any errors for me.

2017-01-24 00:40 UTC, arunoda commented
@impronunciable sorry for the delay. See my comments.

2017-01-24 12:21 UTC, impronunciable commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
It doesn't trigger errors but it's not a valid AMP document anymore. Try going to http://localhost:3000/#development=1 and check the console

2017-01-24 12:42 UTC, arunoda commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
Okay. I'll test.
BTW: What does this line do?

2017-01-24 12:45 UTC, impronunciable commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
By default react limit the set of valid DOM elements and attributes https://github.com/facebook/react/issues/140 this config whitelist amp elements/attributes

2017-01-24 13:12 UTC, arunoda requested changes

2017-01-24 13:12 UTC, arunoda commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
Okay. Then that's totally fine.
Shall we add a few lines of comments?
After that I think we could take this.

2017-01-24 13:15 UTC, impronunciable commented on examples/with-amp/pages/_document.js
> +DOMProperty.injectDOMPropertyConfig({
Good idea, done

2017-01-24 13:20 UTC, arunoda approved these changes

2017-01-24 13:20 UTC, merged