Avoid sending user errors to client
vercel/next.js pull request #8005
Opened 2019-07-16 20:29 UTC by huv1k

2019-07-16 20:38 UTC, Timer requested changes

2019-07-16 20:38 UTC, Timer commented on packages/next-server/server/next-server.ts
> +    } catch (e) {
The `await` above will automatically throw the error -- we don't need this `try { ... } catch (...) { ... }`. Please remove it.

2019-07-16 20:38 UTC, Timer commented on test/integration/api-support/test/index.test.js
> +    expect(res.statusText).toBe('Internal Server Error')
We need to be checking the response body text, not the status text.

2019-07-16 20:38 UTC, Timer commented on packages/next-server/server/api-utils.ts
> +      throw e
Good catch -- this would expose stack traces otherwise.

2019-07-16 20:49 UTC, lucleray commented on test/integration/api-support/test/index.test.js
> +    expect(res.status).toBe(500)
I don't think the status would be 500 in that case? Is anything setting it to 500?

2019-07-17 00:35 UTC, Timer approved these changes

2019-07-17 00:35 UTC, merged