Fix /_error not rendering 404 in development
vercel/next.js pull request #8033
Opened 2019-07-19 00:37 UTC by ijjk

In development if you visit `/_error` the error page is rendered incorrectly and instead should render a 404 since it is a blocked page along with `_app` and `_document`.

2019-07-19 02:05 UTC, Timer requested changes
This doesn't seem right -- how do you edit/develop your error component?

We need to figure out why it doesn't render when visiting it.

2019-07-19 09:29 UTC, timneutkens commented on packages/next-server/lib/constants.ts
> +export const BLOCKED_PAGES = ['/_document', '/_app', '/_error']
This is also used during `next build` with serverless target I think 🤔

2019-07-19 09:32 UTC, timneutkens commented
> We need to figure out why it doesn't render when visiting it.

Same feedback from me, should figure out why it doesn't finish compiling, probably related to on-demand-entries.

2019-08-12 03:59 UTC, Timer commented
Closing this stale PR in favor of the issue: https://github.com/zeit/next.js/issues/8036

2019-08-12 03:59 UTC, closed without merging