[Example] with-typescript-graphql-hooks-styled-components example
vercel/next.js pull request #8213
Opened 2019-08-01 22:03 UTC by ManAnRuck

add an example which combines

typescript
graphql-hooks
styled-components

2019-08-01 22:09 UTC, lfades commented on .gitignore
> +/.vscode
This is a change for another PR, let's remove it

2019-08-01 22:16 UTC, lfades commented
@ManAnRuck Hi thank you for the PR, here's some feedback from my quick view over the files:

- Exclude automatically generated files
- You're adding `styled-components` but using `styled-jsx`, only use one. If you decide for styled-jsx then rename the example to be `with-graphql-hooks-typescript`
- if you can remove Apollo related packages and only have `graphql-hooks`, please do.
- Remove packages that are not necessary for the example to work, like all the eslint packages

2019-08-01 22:17 UTC, lfades requested changes
Check out my comments 🕵️‍♂️

2019-08-02 08:23 UTC, ManAnRuck commented
sure, I will make the requested changes.

removing styled-components
remove generated files (and add a script to generate them)
remove eslint

I don't want to remove typescript in reason of there is an js Apollo-hooks example (but missing with typescript)

2019-08-08 20:24 UTC, ManAnRuck commented
this PR is now deprecated in reason of the official [apollo hooks](https://www.npmjs.com/package/@apollo/react-hooks)

2019-08-08 20:24 UTC, closed without merging