Also provide AppTree in NextPageContext
vercel/next.js pull request #8223
Opened 2019-08-02 16:11 UTC by ijjk

Follow up to #7732 that exposes `AppTree` in `NextPageContext`. 

Might be good to remove `AppTree` from `AppContextType` since it's being supplied in two places here and `_app` could still access the value in `ctx.AppTree`

2019-08-03 11:26 UTC, timneutkens commented
Related to https://github.com/FormidableLabs/urql/issues/344#issuecomment-517327060

2019-08-05 17:38 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 12.2s | 12.2s | -41ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +564 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ⚠️  +94 B |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ⚠️  +30 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.35 kB | 5.36 kB | ⚠️  +11 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +62 B |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ⚠️  +19 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 703 kB | ⚠️  +536 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 13s | 13.3s | ⚠️  +318ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +564 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ⚠️  +94 B |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ⚠️  +30 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.35 kB | 5.36 kB | ⚠️  +11 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +62 B |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ⚠️  +19 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ⚠️  +137 B |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.9 kB | ⚠️  +37 B |
| Serverless `pages/index` Size | 244 kB | 244 kB | ⚠️  +137 B |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.7 kB | ⚠️  +37 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ⚠️  +137 B |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ⚠️  +37 B |
| Serverless `pages/routerDirect` Size | 244 kB | 245 kB | ⚠️  +137 B |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +37 B |
| Serverless `pages/withRouter` Size | 244 kB | 245 kB | ⚠️  +137 B |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.8 kB | ⚠️  +34 B |
| Build Dir Size | 1.89 MB | 1.89 MB | ⚠️  +1.36 kB |

</details>
<details>
        <summary>Diff for <strong>commons.js</strong></summary>

```diff

@@ -3336,7 +3336,8 @@ function () {
           var ctx = {
             pathname: pathname,
             query: query,
-            asPath: as
+            asPath: as,
+            AppTree: null
           };
 
           _this3.getInitialProps(Component, ctx).then(function (props) {
@@ -3378,7 +3379,8 @@ function () {
             var ctx = {
               err: err,
               pathname: pathname,
-              query: query
+              query: query,
+              AppTree: null
             };
             return new _promise["default"](function (resolve) {
               _this3.getInitialProps(Component, ctx).then(function (props) {
@@ -3563,7 +3565,7 @@ function () {
       var _getInitialProps = (0, _asyncToGenerator2["default"])(
       /*#__PURE__*/
       _regenerator["default"].mark(function _callee2(Component, ctx) {
-        var cancelled, cancel, App, props, err;
+        var cancelled, cancel, App, AppTree, props, err;
         return _regenerator["default"].wrap(function _callee2$(_context2) {
           while (1) {
             switch (_context2.prev = _context2.next) {
@@ -3576,15 +3578,18 @@ function () {
 
                 this.clc = cancel;
                 App = this.components['/_app'].Component;
-                _context2.next = 6;
+                AppTree = this._wrapApp(App);
+                _context2.next = 7;
                 return utils_1.loadGetInitialProps(App, {
-                  AppTree: this._wrapApp(App),
+                  AppTree: AppTree,
                   Component: Component,
                   router: this,
-                  ctx: ctx
+                  ctx: (0, _assign["default"])({}, ctx, {
+                    AppTree: AppTree
+                  })
                 });
 
-              case 6:
+              case 7:
                 props = _context2.sent;
 
                 if (cancel === this.clc) {
@@ -3592,7 +3597,7 @@ function () {
                 }
 
                 if (!cancelled) {
-                  _context2.next = 12;
+                  _context2.next = 13;
                   break;
                 }
 
@@ -3600,10 +3605,10 @@ function () {
                 err.cancelled = true;
                 throw err;
 
-              case 12:
+              case 13:
                 return _context2.abrupt("return", props);
 
-              case 13:
+              case 14:
               case "end":
                 return _context2.stop();
             }

```
</details>
      
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -670,7 +670,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -696,44 +696,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitial [...]

2019-08-06 13:44 UTC, timneutkens commented
<img width="566" alt="Screenshot 2019-08-06 at 15 43 37" src="https://user-images.githubusercontent.com/6324199/62544937-ffd48600-b860-11e9-8aa2-6e820cfb83ec.png">

I guess those two null declarations are not really needed 🤔

2019-08-06 14:38 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 13.8s | 13.7s | -133ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +724 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ⚠️  +21 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | -1 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `main` Size | 15.4 kB | 15.4 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.35 kB | 5.36 kB | ⚠️  +11 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +36 B |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ⚠️  +11 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 700 kB | 701 kB | ⚠️  +519 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 14.8s | 15.2s | ⚠️  +470ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +724 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ⚠️  +22 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.35 kB | 5.36 kB | ⚠️  +11 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +36 B |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ⚠️  +11 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ⚠️  +174 B |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ⚠️  +63 B |
| Serverless `pages/index` Size | 243 kB | 244 kB | ⚠️  +174 B |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.7 kB | ⚠️  +63 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ⚠️  +174 B |
| Serverless `pages/_error` gzip Size | 65.3 kB | 65.4 kB | ⚠️  +61 B |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ⚠️  +174 B |
| Serverless `pages/routerDirect` gzip Size | 65.5 kB | 65.6 kB | ⚠️  +61 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ⚠️  +174 B |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | ⚠️  +62 B |
| Build Dir Size | 1.88 MB | 1.89 MB | ⚠️  +1.56 kB |

</details>
<details>
        <summary>Diff for <strong>commons.js</strong></summary>

```diff

@@ -3333,6 +3333,7 @@ function () {
         if (false) { var _require, isValidElementType; }
 
         return new _promise["default"](function (resolve, reject) {
+          // we provide AppTree later so this needs to be `any`
           var ctx = {
             pathname: pathname,
             query: query,
@@ -3374,7 +3375,8 @@ function () {
             var routeInfo = {
               Component: Component,
               err: err
-            };
+            }; // AppTree provided later
+
             var ctx = {
               err: err,
               pathname: pathname,
@@ -3563,7 +3565,7 @@ function () {
       var _getInitialProps = (0, _asyncToGenerator2["default"])(
       /*#__PURE__*/
       _regenerator["default"].mark(function _callee2(Component, ctx) {
-        var cancelled, cancel, App, props, err;
+        var cancelled, cancel, App, AppTree, props, err;
         return _regenerator["default"].wrap(function _callee2$(_context2) {
           while (1) {
             switch (_context2.prev = _context2.next) {
@@ -3576,15 +3578,18 @@ function () {
 
                 this.clc = cancel;
                 App = this.components['/_app'].Component;
-                _context2.next = 6;
+                AppTree = this._wrapApp(App);
+                _context2.next = 7;
                 return utils_1.loadGetInitialProps(App, {
-                  AppTree: this._wrapApp(App),
+                  AppTree: AppTree,
                   Component: Component,
                   router: this,
-                  ctx: ctx
+                  ctx: (0, _assign["default"])({}, ctx, {
+                    AppTree: AppTree
+                  })
                 });
 
-              case 6:
+              case 7:
                 props = _context2.sent;
 
                 if (cancel === this.clc) {
@@ -3592,7 +3597,7 @@ function () {
                 }
 
                 if (!cancelled) {
-                  _context2.next = 12;
+                  _context2.next = 13;
                   break;
                 }
 
@@ -3600,10 +3605,10 @@ function () {
                 err.cancelled = true;
                 throw err;
 
-              case 12:
+              case 13:
                 return _context2.abrupt("return", props);
 
-              case 13:
+              case 14:
               case "end":
                 return _context2.stop();
             }

```
</details>
      
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -670,7 +670,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -696,44 +696,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitialProps)(App, appCtx);
 
-          case 14:
+          ca [...]

2019-08-08 16:15 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 22.6s | 22.7s | ⚠️  +118ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +712 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ⚠️  +24 B |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ⚠️  +28 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ⚠️  +1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.46 kB | 5.48 kB | ⚠️  +17 B |
| Client `main` Modern Size | 12.8 kB | 12.9 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.83 kB | 4.85 kB | ⚠️  +17 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +36 B |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ⚠️  +6 B |
| Client `commons` Modern Size | 169 kB | 169 kB | ⚠️  +40 B |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ⚠️  +11 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | ⚠️  +985 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 23.8s | 23.6s | -237ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +712 B |
| Total Bundle (main, webpack, commons) Size | 207 kB | 207 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 68.1 kB | ⚠️  +25 B |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 182 kB | ⚠️  +68 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.9 kB | ⚠️  +28 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.8 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.46 kB | 5.48 kB | ⚠️  +19 B |
| Client `main` Modern Size | 12.8 kB | 12.9 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.83 kB | 4.85 kB | ⚠️  +17 B |
| Client `commons` Size | 188 kB | 188 kB | ⚠️  +36 B |
| Client `commons` gzip Size | 61.3 kB | 61.3 kB | ⚠️  +6 B |
| Client `commons` Modern Size | 169 kB | 169 kB | ⚠️  +40 B |
| Client `commons` Modern gzip Size | 55.1 kB | 55.1 kB | ⚠️  +11 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +173 B |
| Serverless `pages/link` gzip Size | 68.6 kB | 68.6 kB | ⚠️  +60 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ⚠️  +173 B |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +60 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +173 B |
| Serverless `pages/_error` gzip Size | 66.1 kB | 66.2 kB | ⚠️  +59 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +173 B |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 66.4 kB | ⚠️  +59 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +173 B |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66.5 kB | ⚠️  +74 B |
| Build Dir Size | 2.59 MB | 2.6 MB | ⚠️  +2.03 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -695,7 +695,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -721,44 +721,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _util [...]

2019-08-11 20:32 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 23s | 23.2s | ⚠️  +210ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -13.8 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | -659 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.3 kB | -318 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | -491 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.1 kB | -236 B |
| Client `_app` Size | 2.35 kB | 2.39 kB | ⚠️  +35 B |
| Client `_app` gzip Size | 1.07 kB | 1.08 kB | ⚠️  +8 B |
| Client `_app` Modern Size | 1.79 kB | 1.83 kB | ⚠️  +35 B |
| Client `_app` gzip Modern Size | 880 B | 890 B | ⚠️  +10 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.08 kB | -104 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.8 kB | -26 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.7 kB | -113 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.7 kB | -28 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 15.8 kB | -439 B |
| Client `main` gzip Size | 5.73 kB | 5.48 kB | -250 B |
| Client `main` Modern Size | 13.1 kB | 12.9 kB | -238 B |
| Client `main` Modern gzip Size | 4.99 kB | 4.85 kB | -144 B |
| Client `commons` Size | 195 kB | 195 kB | -255 B |
| Client `commons` gzip Size | 63.6 kB | 63.5 kB | -76 B |
| Client `commons` Modern Size | 176 kB | 176 kB | -253 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.3 kB | -92 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.44 MB | 1.43 MB | -10.1 kB |

</details>


<details>
<summary>Click to expand serverless stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 25.4s | 24.6s | -814ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -13.8 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | -659 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.3 kB | -319 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | -491 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.1 kB | -236 B |
| Client `_app` Size | 2.35 kB | 2.39 kB | ⚠️  +35 B |
| Client `_app` gzip Size | 1.07 kB | 1.08 kB | ⚠️  +7 B |
| Client `_app` Modern Size | 1.79 kB | 1.83 kB | ⚠️  +35 B |
| Client `_app` gzip Modern Size | 880 B | 890 B | ⚠️  +10 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.08 kB | -104 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.8 kB | -26 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.7 kB | -113 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.7 kB | -28 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 15.8 kB | -439 B |
| Client `main` gzip Size | 5.73 kB | 5.48 kB | -250 B |
| Client `main` Modern Size | 13.1 kB | 12.9 kB | -238 B |
| Client `main` Modern gzip Size | 4.99 kB | 4.85 kB | -144 B |
| Client `commons` Size | 195 kB | 195 kB | -255 B |
| Client `commons` gzip Size | 63.6 kB | 63.5 kB | -76 B |
| Client `commons` Modern Size | 176 kB | 176 kB | -253 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.3 kB | -92 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | -514 B |
| Serverless `pages/link` gzip Size | 68.8 kB | 68.7 kB | -145 B |
| Serverless `pages/index` Size | 249 kB | 248 kB | -269 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.5 kB | -90 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | -269 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.2 kB | -84 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | -269 B |
| Serverless `pages/routerDirect` gzip Size | 66.5 kB | 66.4 kB | -84 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | -269 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.5 kB | -74 B |
| Build Dir Size | 2.64 MB | 2.63 MB | -11.8 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -1,5 +1,20 @@
 (window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
+/***/ "+iuc":
+/***/ (function(module, exports, __webpack_require__) {
+
+__webpack_require__("wgeU");
+__webpack_require__("FlQf");
+__webpack_require__("bBy9");
+__webpack_require__("B9jh");
+__webpack_require__("dL40");
+__webpack_require__("xvv9");
+__webpack_require__("V+O7");
+module.exports = __webpack_require__("WEpk").Set;
+
+
+/***/ }),
+
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -54,6 +69,28 @@ __webpack_require__("cHUd")('Map');
 
 /***/ }),
 
+/***/ "B9jh":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+var strong = __webpack_require__("Wu5q");
+var validate = __webpack_require__("n3ko");
+var SET = 'Set';
+
+// 23.2 Set Objects
+module.exports = __webpack_require__("raTm")(SET, function (get) {
+  return function Set() { return get(this, arguments.length > 0 ? arguments[0] : undefined); };
+}, {
+  // 23.2.3.1 Set.prototype.add(value)
+  add: function add(value) {
+    return strong.def(validate(this, SET), value = value === 0 ? 0 : value, value);
+  }
+}, strong);
+
+
+/***/ }),
+
 /***/ "BMP1":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -658,7 +695,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _ [...]

2019-08-11 20:43 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 22.6s | 22.6s | -80ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -13.8 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | -659 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.3 kB | -318 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | -491 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.1 kB | -236 B |
| Client `_app` Size | 2.35 kB | 2.39 kB | ⚠️  +35 B |
| Client `_app` gzip Size | 1.07 kB | 1.08 kB | ⚠️  +8 B |
| Client `_app` Modern Size | 1.79 kB | 1.83 kB | ⚠️  +35 B |
| Client `_app` gzip Modern Size | 880 B | 890 B | ⚠️  +10 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.08 kB | -104 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.8 kB | -26 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.7 kB | -113 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.7 kB | -28 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 15.8 kB | -439 B |
| Client `main` gzip Size | 5.73 kB | 5.48 kB | -250 B |
| Client `main` Modern Size | 13.1 kB | 12.9 kB | -238 B |
| Client `main` Modern gzip Size | 4.99 kB | 4.85 kB | -144 B |
| Client `commons` Size | 195 kB | 195 kB | -255 B |
| Client `commons` gzip Size | 63.6 kB | 63.5 kB | -76 B |
| Client `commons` Modern Size | 176 kB | 176 kB | -253 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.3 kB | -92 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.44 MB | 1.43 MB | -10.1 kB |

</details>


<details>
<summary>Click to expand serverless stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 23.8s | 24s | ⚠️  +165ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -13.8 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | -659 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.3 kB | -318 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | -491 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.1 kB | -236 B |
| Client `_app` Size | 2.35 kB | 2.39 kB | ⚠️  +35 B |
| Client `_app` gzip Size | 1.07 kB | 1.08 kB | ⚠️  +8 B |
| Client `_app` Modern Size | 1.79 kB | 1.83 kB | ⚠️  +35 B |
| Client `_app` gzip Modern Size | 880 B | 890 B | ⚠️  +10 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.08 kB | -104 B |
| Client `pages/link` gzip Size | 1.82 kB | 1.8 kB | -26 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.7 kB | -113 B |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.7 kB | -28 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 15.8 kB | -439 B |
| Client `main` gzip Size | 5.73 kB | 5.48 kB | -250 B |
| Client `main` Modern Size | 13.1 kB | 12.9 kB | -238 B |
| Client `main` Modern gzip Size | 4.99 kB | 4.85 kB | -144 B |
| Client `commons` Size | 195 kB | 195 kB | -255 B |
| Client `commons` gzip Size | 63.6 kB | 63.5 kB | -76 B |
| Client `commons` Modern Size | 176 kB | 176 kB | -253 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.3 kB | -92 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 255 kB | -544 B |
| Serverless `pages/link` gzip Size | 68.8 kB | 68.7 kB | -157 B |
| Serverless `pages/index` Size | 249 kB | 248 kB | -299 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.5 kB | -103 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | -299 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.2 kB | -97 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | -299 B |
| Serverless `pages/routerDirect` gzip Size | 66.5 kB | 66.4 kB | -98 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | -299 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.5 kB | -88 B |
| Build Dir Size | 2.64 MB | 2.63 MB | -12 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -1,5 +1,20 @@
 (window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
+/***/ "+iuc":
+/***/ (function(module, exports, __webpack_require__) {
+
+__webpack_require__("wgeU");
+__webpack_require__("FlQf");
+__webpack_require__("bBy9");
+__webpack_require__("B9jh");
+__webpack_require__("dL40");
+__webpack_require__("xvv9");
+__webpack_require__("V+O7");
+module.exports = __webpack_require__("WEpk").Set;
+
+
+/***/ }),
+
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -54,6 +69,28 @@ __webpack_require__("cHUd")('Map');
 
 /***/ }),
 
+/***/ "B9jh":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+var strong = __webpack_require__("Wu5q");
+var validate = __webpack_require__("n3ko");
+var SET = 'Set';
+
+// 23.2 Set Objects
+module.exports = __webpack_require__("raTm")(SET, function (get) {
+  return function Set() { return get(this, arguments.length > 0 ? arguments[0] : undefined); };
+}, {
+  // 23.2.3.1 Set.prototype.add(value)
+  add: function add(value) {
+    return strong.def(validate(this, SET), value = value === 0 ? 0 : value, value);
+  }
+}, strong);
+
+
+/***/ }),
+
 /***/ "BMP1":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -658,7 +695,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _conte [...]

2019-08-11 20:52 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 21.6s | 22.2s | ⚠️  +597ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +740 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.6 kB | ⚠️  +11 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | ⚠️  +36 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.4 kB | ⚠️  +12 B |
| Client `_app` Size | 2.35 kB | 2.35 kB | ✓ |
| Client `_app` gzip Size | 1.07 kB | 1.07 kB | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ⚠️  +1 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 16.3 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.73 kB | 5.74 kB | ⚠️  +14 B |
| Client `main` Modern Size | 13.1 kB | 13.1 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.99 kB | 5.01 kB | ⚠️  +16 B |
| Client `commons` Size | 195 kB | 195 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | -3 B |
| Client `commons` Modern Size | 176 kB | 176 kB | ⚠️  +8 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | -4 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.44 MB | 1.44 MB | ⚠️  +592 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 25.5s | 25s | -516ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +740 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.6 kB | ⚠️  +11 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | ⚠️  +36 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.4 kB | ⚠️  +12 B |
| Client `_app` Size | 2.35 kB | 2.35 kB | ✓ |
| Client `_app` gzip Size | 1.07 kB | 1.07 kB | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 16.3 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.73 kB | 5.74 kB | ⚠️  +14 B |
| Client `main` Modern Size | 13.1 kB | 13.1 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.99 kB | 5.01 kB | ⚠️  +16 B |
| Client `commons` Size | 195 kB | 195 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | -3 B |
| Client `commons` Modern Size | 176 kB | 176 kB | ⚠️  +8 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | -4 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ⚠️  +39 B |
| Serverless `pages/link` gzip Size | 68.8 kB | 68.9 kB | ⚠️  +32 B |
| Serverless `pages/index` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +34 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ⚠️  +39 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +34 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/routerDirect` gzip Size | 66.5 kB | 66.6 kB | ⚠️  +33 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +41 B |
| Build Dir Size | 2.64 MB | 2.65 MB | ⚠️  +859 B |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -658,7 +658,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -684,44 +684,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitialPr [...]

2019-08-11 23:02 UTC, timneutkens requested changes
@ijjk could you add a test for this?

2019-08-11 23:58 UTC, ijjk commented
Added a test for it in the `app-tree` suite

2019-08-12 00:05 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 22.2s | 22.8s | ⚠️  +644ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +740 B |
| Total Bundle (main, webpack, commons) Size | 213 kB | 213 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 70 kB | 70 kB | ⚠️  +16 B |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ⚠️  +36 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.8 kB | 61.8 kB | ⚠️  +11 B |
| Client `_app` Size | 2.35 kB | 2.35 kB | ✓ |
| Client `_app` gzip Size | 1.07 kB | 1.07 kB | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 14.7 kB | 14.7 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.08 kB | 5.1 kB | ⚠️  +19 B |
| Client `main` Modern Size | 11.6 kB | 11.7 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.37 kB | 4.38 kB | ⚠️  +15 B |
| Client `commons` Size | 195 kB | 195 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | -3 B |
| Client `commons` Modern Size | 176 kB | 176 kB | ⚠️  +8 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | -4 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.43 MB | 1.43 MB | ⚠️  +592 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 24.2s | 24.5s | ⚠️  +360ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +740 B |
| Total Bundle (main, webpack, commons) Size | 213 kB | 213 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 70 kB | 70 kB | ⚠️  +16 B |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ⚠️  +36 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.8 kB | 61.8 kB | ⚠️  +11 B |
| Client `_app` Size | 2.35 kB | 2.35 kB | ✓ |
| Client `_app` gzip Size | 1.07 kB | 1.07 kB | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 14.7 kB | 14.7 kB | ⚠️  +32 B |
| Client `main` gzip Size | 5.08 kB | 5.1 kB | ⚠️  +19 B |
| Client `main` Modern Size | 11.6 kB | 11.7 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.37 kB | 4.38 kB | ⚠️  +15 B |
| Client `commons` Size | 195 kB | 195 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | -3 B |
| Client `commons` Modern Size | 176 kB | 176 kB | ⚠️  +8 B |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | -4 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ⚠️  +39 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +34 B |
| Serverless `pages/index` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +33 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ⚠️  +39 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.4 kB | ⚠️  +32 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +32 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ⚠️  +39 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +38 B |
| Build Dir Size | 2.64 MB | 2.64 MB | ⚠️  +859 B |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -656,7 +656,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regenerator["default"].wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -682,44 +682,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitialProps)(App, appCtx); [...]

2019-08-12 04:23 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 20.6s | 19.7s | -878ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -2.21 kB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 213 kB | ⚠️  +2.81 kB |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 70 kB | ⚠️  +684 B |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 188 kB | ⚠️  +798 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.8 kB | ⚠️  +178 B |
| Client `_app` Size | 1.9 kB | 2.35 kB | ⚠️  +455 B |
| Client `_app` gzip Size | 913 B | 1.07 kB | ⚠️  +161 B |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.22 kB | ⚠️  +199 B |
| Client `_error` gzip Size | 3.13 kB | 3.16 kB | ⚠️  +29 B |
| Client `_error` Modern Size | 5.82 kB | 5.85 kB | ⚠️  +23 B |
| Client `_error` gzip Modern Size | 2.35 kB | 2.33 kB | -13 B |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.1 kB | 4.18 kB | ⚠️  +85 B |
| Client `pages/link` gzip Size | 1.8 kB | 1.82 kB | ⚠️  +22 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | -1 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 14.7 kB | ⚠️  +978 B |
| Client `main` gzip Size | 4.88 kB | 5.1 kB | ⚠️  +225 B |
| Client `main` Modern Size | 11.4 kB | 11.7 kB | ⚠️  +255 B |
| Client `main` Modern gzip Size | 4.32 kB | 4.38 kB | ⚠️  +58 B |
| Client `commons` Size | 194 kB | 195 kB | ⚠️  +1.37 kB |
| Client `commons` gzip Size | 63.3 kB | 63.6 kB | ⚠️  +298 B |
| Client `commons` Modern Size | 175 kB | 176 kB | ⚠️  +543 B |
| Client `commons` Modern gzip Size | 57.3 kB | 57.4 kB | ⚠️  +120 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.43 MB | ⚠️  +17.8 kB |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 22.1s | 22s | -61ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -2.21 kB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 213 kB | ⚠️  +2.81 kB |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 70 kB | ⚠️  +684 B |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 188 kB | ⚠️  +798 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.8 kB | ⚠️  +179 B |
| Client `_app` Size | 1.9 kB | 2.35 kB | ⚠️  +455 B |
| Client `_app` gzip Size | 913 B | 1.07 kB | ⚠️  +161 B |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.22 kB | ⚠️  +199 B |
| Client `_error` gzip Size | 3.13 kB | 3.16 kB | ⚠️  +29 B |
| Client `_error` Modern Size | 5.82 kB | 5.85 kB | ⚠️  +23 B |
| Client `_error` gzip Modern Size | 2.35 kB | 2.33 kB | -13 B |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.1 kB | 4.18 kB | ⚠️  +85 B |
| Client `pages/link` gzip Size | 1.8 kB | 1.82 kB | ⚠️  +22 B |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 14.7 kB | ⚠️  +978 B |
| Client `main` gzip Size | 4.88 kB | 5.1 kB | ⚠️  +225 B |
| Client `main` Modern Size | 11.4 kB | 11.7 kB | ⚠️  +255 B |
| Client `main` Modern gzip Size | 4.32 kB | 4.38 kB | ⚠️  +59 B |
| Client `commons` Size | 194 kB | 195 kB | ⚠️  +1.37 kB |
| Client `commons` gzip Size | 63.3 kB | 63.6 kB | ⚠️  +298 B |
| Client `commons` Modern Size | 175 kB | 176 kB | ⚠️  +543 B |
| Client `commons` Modern gzip Size | 57.3 kB | 57.4 kB | ⚠️  +120 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 256 kB | ⚠️  +1.59 kB |
| Serverless `pages/link` gzip Size | 68.8 kB | 68.9 kB | ⚠️  +45 B |
| Serverless `pages/index` Size | 247 kB | 249 kB | ⚠️  +1.59 kB |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.6 kB | -4 B |
| Serverless `pages/_error` Size | 247 kB | 248 kB | ⚠️  +1.59 kB |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.4 kB | ⚠️  +38 B |
| Serverless `pages/routerDirect` Size | 248 kB | 249 kB | ⚠️  +1.59 kB |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +13 B |
| Serverless `pages/withRouter` Size | 248 kB | 249 kB | ⚠️  +1.59 kB |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +30 B |
| Build Dir Size | 2.61 MB | 2.64 MB | ⚠️  +28.3 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -1,5 +1,50 @@
 (window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
+/***/ "+oT+":
+/***/ (function(module, exports, __webpack_require__) {
+
+var _Promise = __webpack_require__("eVuF");
+
+function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
+  try {
+    var info = gen[key](arg);
+    var value = info.value;
+  } catch (error) {
+    reject(error);
+    return;
+  }
+
+  if (info.done) {
+    resolve(value);
+  } else {
+    _Promise.resolve(value).then(_next, _throw);
+  }
+}
+
+function _asyncToGenerator(fn) {
+  return function () {
+    var self = this,
+        args = arguments;
+    return new _Promise(function (resolve, reject) {
+      var gen = fn.apply(self, args);
+
+      function _next(value) {
+        asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
+      }
+
+      function _throw(err) {
+        asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
+      }
+
+      _next(undefined);
+    });
+  };
+}
+
+module.exports = _asyncToGenerator;
+
+/***/ }),
+
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -32,9 +77,11 @@ window.next = next;
 "use strict";
 
 
-var _classCallCheck = __webpack_require__("/HRN");
+var _interopRequireDefault2 = __webpack_require__("KI45");
+
+var _classCallCheck2 = _interopRequireDefault2(__webpack_require__("0iUn"));
 
-var _createClass = __webpack_require__("WaGi");
+ [...]

2019-08-12 14:41 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 24.4s | 23.1s | -1.3s |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +1.19 kB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ⚠️  +14 B |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ⚠️  +37 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ⚠️  +7 B |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ⚠️  +32 B |
| Client `main` gzip Size | 4.88 kB | 4.89 kB | ⚠️  +18 B |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.32 kB | 4.34 kB | ⚠️  +12 B |
| Client `commons` Size | 194 kB | 194 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | -4 B |
| Client `commons` Modern Size | 175 kB | 175 kB | ⚠️  +9 B |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | -5 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.41 MB | ⚠️  +595 B |

</details>


<details>
<summary>Click to expand serverless stats ⚠️ Total Bundle Size Increase ⚠️</summary>

| | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| Build Duration | 25s | 25.2s | ⚠️  +239ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +1.19 kB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ⚠️  +38 B |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ⚠️  +14 B |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ⚠️  +37 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ⚠️  +7 B |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ⚠️  +32 B |
| Client `main` gzip Size | 4.88 kB | 4.89 kB | ⚠️  +18 B |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ⚠️  +28 B |
| Client `main` Modern gzip Size | 4.32 kB | 4.34 kB | ⚠️  +12 B |
| Client `commons` Size | 194 kB | 194 kB | ⚠️  +6 B |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | -4 B |
| Client `commons` Modern Size | 175 kB | 175 kB | ⚠️  +9 B |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | -5 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +303 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +69 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +303 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +70 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +303 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.4 kB | ⚠️  +70 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +303 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +70 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +303 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +75 B |
| Build Dir Size | 2.61 MB | 2.61 MB | ⚠️  +2.18 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -586,7 +586,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regeneratorRuntime.wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -612,44 +612,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitialProps)(App, appCtx);
 
-         [...]

2019-08-12 19:57 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| buildDuration | 23.1s | 22.6s | -540ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ⚠️ +1.19 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> ⚠️ Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ⚠️ +32 B |
| main-HASH.js gzip | 4.84 kB | 4.86 kB | ⚠️ +18 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ⚠️ +6 B |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | -5 B |
| Overall change |  |  | ⚠️ +38 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> ⚠️ Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ⚠️ +28 B |
| main-HASH.module.js gzip | 4.29 kB | 4.3 kB | ⚠️ +13 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ⚠️ +9 B |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | -5 B |
| Overall change |  |  | ⚠️ +37 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js add-apptree-ctx | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 847 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 840 B | ⚠️ +3 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 833 B | 836 B | ⚠️ +3 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -586,7 +586,7 @@ function _renderError() {
   _renderError = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee3(props) {
-    var App, err, appCtx, initProps;
+    var App, err, AppTree, appCtx, initProps;
     return _regeneratorRuntime.wrap(function _callee3$(_context3) {
       while (1) {
         switch (_context3.prev = _context3.next) {
@@ -612,44 +612,46 @@ function _renderError() {
             // In production we do a normal render with the `ErrorComponent` as component.
             // If we've gotten here upon initial render, we can use the props from the server.
             // Otherwise, we need to call `getInitialProps` on `App` before mounting.
+            AppTree = wrapApp(App);
             appCtx = {
-              AppTree: wrapApp(App),
               Component: ErrorComponent,
+              AppTree: AppTree,
               router: router,
               ctx: {
                 err: err,
                 pathname: page,
                 query: query,
-                asPath: asPath
+                asPath: asPath,
+                AppTree: AppTree
               }
             };
 
             if (!props.props) {
-              _context3.next = 12;
+              _context3.next = 13;
               break;
             }
 
             _context3.t0 = props.props;
-            _context3.next = 15;
+            _context3.next = 16;
             break;
 
-          case 12:
-            _context3.next = 14;
+          case 13:
+            _context3.next = 15;
             return (0, _utils.loadGetInitialProps)(App, appCtx);
 
-          case 14:
+          case 15:
             _context3.t0 = _context3.sent;
 
-          case 15:
+          case 16:
             initProps = _context3.t0;
-            _context3.next = 18;
+            _context3.next = 19;
             return doRender((0, _extends2["default"])({}, props, {
               err: err,
               Component: ErrorComponent,
               props: initProps
             }));
 
-          case 18:
+          case 19:
           case "end":
             return _context3.stop();
         }
@@ -747,7 +749,7 @@ function _doRender() {
   _doRender = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee4(_ref5) {
-    var App, Component, props, err, _router2, pathname, _query, _asPath, appCtx, appProps;
+    var App, Component, props, err, _router2, pathname, _query, _asPath, AppTree, appCtx, appProps;
 
     return _regeneratorRuntime.wrap(function _callee4$(_context4) {
       while (1) {
@@ -757,29 +759,31 @@ function _doRender() {
             // this is for when ErrorComponent gets replaced by Component by HMR
 
             if (!(!props && Component && Component !== ErrorComponent && lastAppProps.Component === ErrorComponent)) {
-              _context4.next = 7;
+              _context4.next = 8;
               break;
             }
 
             _router2 = router, pathname = _router2.pathname, _query = _router2.query, _asPath = _router2.asPath;
+            AppTree = wrapApp(App);
             appCtx = {
               router: router,
-              AppTree: wrapApp(App),
+              AppTree: AppTree,
               Component: ErrorComponent,
               ctx: {
                 err: err,
                 pathname: pathname,
                 query: _query,
-                asPath: _asPath
+                asPath: _asPath,
+                AppTree: AppTree
               }
             };
-            _context4.next = 6;
+            _context4.next = 7;
             return (0, _utils.loadGetInitialProps)(App, appCtx);
 
-          case 6:
+          case 7:
             props = _context4.sent;
 
-          case 7:
+          case 8:
             Component = Component || lastAppProps.Component;
             props = props || lastAppProps.props;
             appProps = (0, _extends2["default"])({}, props, {
@@ -802,7 +806,7 @@ function _doRender() {
               appProps: appProps
             });
 
-          case 14:
+          case 15:
           case "end":
             return _context4.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>commons.HASH.js</strong></summary>

```diff
@@ -3431,13 +3431,12 @@ function () {
         if (false) { var _require, isValidElementType; }
 
         return new _Promise(function (resolve, reject) {
-          var ctx = {
+          // we provide AppTree later so this needs to be `any`
+          _this3.getInitialProps(Component, {
             pathname: pathname,
             query: query,
             asPath: as
-          };
-
-          _this3.get [...]

2019-08-13 09:33 UTC, timneutkens approved these changes

2019-08-13 09:33 UTC, merged