Experimental modern optimization - URL lib
vercel/next.js pull request #8225
Opened 2019-08-02 18:25 UTC by janicklas-ralph

NextJS uses the [node-url](https://www.npmjs.com/package/url) package on the client side for their next-router library. Node-url has utilities for URL resolution and parsing meant to have feature parity with node.js core url module. Node-url adds ~5kb (gzip) to the common.js bundle in production.
Replacing this library with our custom snippet that uses the relatively new URL class reduces the size of common.js by ~5kb (gzip) in a NextJS production build.

Additionally, I'm replacing the `querystring` module with a lighter alternative `qss`

The URL class is [supported](https://caniuse.com/#feat=url) is all browsers that [support type=module](https://caniuse.com/#feat=es6-module). We use the [module/nomodule implementation](https://github.com/zeit/next.js/pull/7704) to load a [url-polyfill](https://www.npmjs.com/package/url-polyfill) in a nomodule script which conditionally loads this polyfill in all browsers that don’t support type=module.

Stats:
Common.js file for the basic integration app

Common.js (gzip) | Before | After
-- | -- | --
type=module | 52.29 kb | 48.34 kb
nomodule | 58.25 kb | 54.28 kb + 2.02 kb (url-polyfill)

Adding this feature behind an experimental flag

2019-08-05 17:18 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 12.5s | 12.3s | -188ms |
| `node_modules` Size | 43.6 MB | 43.7 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 703 kB | ⚠️  +437 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 13.5s | 13.4s | -124ms |
| `node_modules` Size | 43.6 MB | 43.7 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ⚠️  +1 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ⚠️  +1 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ⚠️  +27 B |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ⚠️  +1 B |
| Serverless `pages/index` Size | 244 kB | 244 kB | ⚠️  +27 B |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +2 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ⚠️  +27 B |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ⚠️  +1 B |
| Serverless `pages/routerDirect` Size | 244 kB | 245 kB | ⚠️  +27 B |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +1 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ⚠️  +27 B |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | ⚠️  +1 B |
| Build Dir Size | 1.89 MB | 1.89 MB | ⚠️  +545 B |

</details>

2019-08-06 17:21 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 13.1s | 13.2s | ⚠️  +129ms |
| `node_modules` Size | 43.6 MB | 43.7 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 700 kB | 701 kB | ⚠️  +437 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 14.4s | 14.1s | -310ms |
| `node_modules` Size | 43.6 MB | 43.7 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ⚠️  +27 B |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ⚠️  +2 B |
| Serverless `pages/index` Size | 243 kB | 244 kB | ⚠️  +27 B |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +3 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ⚠️  +27 B |
| Serverless `pages/_error` gzip Size | 65.3 kB | 65.3 kB | ⚠️  +3 B |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ⚠️  +27 B |
| Serverless `pages/routerDirect` gzip Size | 65.5 kB | 65.5 kB | ⚠️  +3 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ⚠️  +27 B |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | ⚠️  +2 B |
| Build Dir Size | 1.88 MB | 1.88 MB | ⚠️  +545 B |

</details>

2019-08-09 16:25 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 22.4s | 22.5s | ⚠️  +174ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.43 MB | 1.43 MB | ⚠️  +437 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| Build Duration | 24.4s | 23.6s | -726ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +86.2 kB |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ⚠️  +27 B |
| Serverless `pages/link` gzip Size | 68.7 kB | 68.7 kB | ⚠️  +1 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ⚠️  +27 B |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +6 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ⚠️  +27 B |
| Serverless `pages/_error` gzip Size | 66.2 kB | 66.2 kB | ⚠️  +5 B |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ⚠️  +27 B |
| Serverless `pages/routerDirect` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +7 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ⚠️  +27 B |
| Serverless `pages/withRouter` gzip Size | 66.5 kB | 66.5 kB | ⚠️  +7 B |
| Build Dir Size | 2.64 MB | 2.64 MB | ⚠️  +545 B |

</details>

2019-08-13 20:48 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode (⚠️ Increase detected ⚠️)</strong></summary>

<br/>

<details>
<summary><strong>General</strong> ⚠️ Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| buildDuration | 21.3s | 21.6s | ⚠️ +275ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +86.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 847 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 837 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 832 B | -4 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode (⚠️ Increase detected ⚠️)</strong></summary>

<br/>

<details>
<summary><strong>General</strong> ⚠️ Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| buildDuration | 22.7s | 22.2s | -503ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +86.2 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> ⚠️ Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ⚠️ +27 B |
| _error.js gzip | 66.2 kB | 66.2 kB | ⚠️ +7 B |
| index.js | 247 kB | 247 kB | ⚠️ +27 B |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +5 B |
| link.js | 255 kB | 255 kB | ⚠️ +27 B |
| link.js gzip | 68.7 kB | 68.7 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ⚠️ +27 B |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +6 B |
| withRouter.js | 248 kB | 248 kB | ⚠️ +27 B |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +4 B |
| Overall change |  |  | ⚠️ +135 B |

</details>

</details>

2019-08-20 19:20 UTC, Timer requested changes

2019-08-20 19:20 UTC, Timer commented on packages/next/build/webpack-config.ts
> +      'next/config': 'next-servegit sr/dist/lib/runtime-config.js',
```suggestion
      'next/config': 'next-server/dist/lib/runtime-config.js',
```

2019-08-20 19:20 UTC, Timer commented on packages/next-server/server/config.ts
> +    modernOptimizations: false,
```suggestion
```

2019-08-20 19:20 UTC, Timer commented on packages/next/build/webpack-config.ts
> +        ...(config.experimental.modernOptimizations
```suggestion
        ...(config.experimental.modern
```

2019-08-20 19:20 UTC, Timer commented on packages/next/build/webpack-config.ts
> +      ...(config.experimental.modernOptimizations &&
```suggestion
      ...(config.experimental.modern &&
```

2019-08-20 19:20 UTC, Timer commented on packages/next/build/webpack-config.ts
> +        'process.env.__NEXT_MODERN_OPTIMIZATIONS': !!config.experimental
```suggestion
```

2019-08-20 19:20 UTC, Timer commented on packages/next/build/webpack-config.ts
> +          .modernOptimizations,
```suggestion
```

2019-08-20 19:20 UTC, Timer commented on packages/next/pages/_document.tsx
> +        {process.env.__NEXT_MODERN_OPTIMIZATIONS ? (
```suggestion
        {process.env. __NEXT_MODERN_BUILD ? (
```

2019-08-20 19:20 UTC, Timer commented on test/integration/modern-mode/next.config.js
> +  experimental: { modern: true, modernOptimizations: true }
```suggestion
  experimental: { modern: true }
```

2019-08-21 21:33 UTC, janicklas-ralph commented
@Timer Resolved some of the comments. I still want to keep `modernOptimizations` under a flag for two reasons: Want to give users the ability to turn it off if theres an error. Also I'm looking into adding another PR that will auto toggle modern mode based on user's browser target. In that case if they decide to target only modern browsers, the `NextESMPlugin` will not trigger, but the `modernOptimizatins` will still apply

2019-08-22 22:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| buildDuration | 22.3s | 21.7s | -624ms |
| nodeModulesSize | 41.2 MB | 41.3 MB | ⚠️ +84.4 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | -1 B |
| main-HASH.js gzip | 6.63 kB | 6.62 kB | -1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | -1 B |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | -1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.9 kB | ⚠️ +67 B |
| _app.js gzip | 884 B | 908 B | ⚠️ +24 B |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ⚠️ +1 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 434 B | ⚠️ +1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ⚠️ +68 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.79 kB | ⚠️ +68 B |
| _app.module.js gzip | 840 B | 866 B | ⚠️ +26 B |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 805 B | ⚠️ +1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ⚠️ +1 B |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 430 B | ⚠️ +1 B |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ⚠️ +69 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js canary | Change |
| - | - | - | - |
| link | 3.75 kB | 3.85 kB | ⚠️ +107 B |
| link gzip | 964 B | 978 B | ⚠️ +14 B |
| index | 3.69 kB | 3.8 kB | ⚠️ +107 B |
| index gzip | 956 B | 968 B | ⚠️ +12 B |
| withRouter | 3.75 kB | 3.86 kB | ⚠️ +107 B |
| withRouter gzip | 951 B | 963 B | ⚠️ +12 B |
| Overall change |  |  | ⚠️ +321 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
@@ -321,7 +321,7 @@ var _routerContext = __webpack_require__("9EOK");
 
 var _dataManager = __webpack_require__("cuFY");
 
-var _querystring = __webpack_require__("s4NR");
+var _querystring = __webpack_require__("o6se");
 
 var _isDynamic = __webpack_require__("kcOw");
 /* global location */
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
@@ -393,7 +393,7 @@ var _routerContext = __webpack_require__("9EOK");
 
 var _dataManager = __webpack_require__("cuFY");
 
-var _querystring = __webpack_require__("s4NR");
+var _querystring = __webpack_require__("o6se");
 
 var _isDynamic = __webpack_require__("kcOw");
 /* global location */
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -118,7 +118,8 @@ function (_react$default$Compon) {
   }]);
 
   return App;
-}(_react["default"].Component);
+}(_react["default"].Component); // @deprecated noop for now until removal
+
 
 exports["default"] = App;
 App.childContextTypes = {
@@ -126,17 +127,15 @@ App.childContextTypes = {
 };
 App.origGetInitialProps = appGetInitialProps;
 App.getInitialProps = appGetInitialProps;
-var warnContainer;
-var warnUrl;
-
-if (false) {} // @deprecated noop for now until removal
-
 
 function Container(p) {
-  if (false) {}
   return p.children;
 }
 
+var warnUrl = (0, _utils.execOnce)(function () {
+  if (false) {}
+});
+
 function createUrl(router) {
   // This is to make sure we don't references the router object at call time
   var pathname = router.pathname,
@@ -144,40 +143,40 @@ function createUrl(router) {
       query = router.query;
   return {
     get query() {
-      if (false) {}
+      warnUrl();
       return query;
     },
 
     get pathname() {
-      if (false) {}
+      warnUrl();
       return pathname;
     },
 
     get asPath() {
-      if (false) {}
+      warnUrl();
       return asPath;
     },
 
     back: function back() {
-      if (false) {}
+      warnUrl();
       router.back();
     },
     push: function push(url, as) {
-      if (false) {}
+      warnUrl();
       return router.push(url, as);
     },
     pushTo: function pushTo(href, as) {
-      if (false) {}
+      warnUrl();
       var pushRoute = as ? href : '';
       var pushUrl = as || href;
       return router.push(pushRoute, pushUrl);
     },
     replace: function replace(url, as) {
-      if (false) {}
+      warnUrl();
       return router.replace(url, as);
     },
     replaceTo: function replaceTo(href, as) {
-      if (false) {}
+      warnUrl();
       var replaceRoute = as ? href : '';
       var replaceUrl = as || href;
       return router.replace(replaceRoute, replaceUrl);
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -427,7 +427,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("O9qo");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -121,7 +121,8 @@ class App extends _react.default.Component {
     }));
   }
 
-}
+} // @deprecated noop for now until removal
+
 
 exports.default = App;
 App.childContextTypes = {
@@ -129,17 +130,15 @@ App.childContextTypes = {
 };
 App.origGetInitialProps = appGetInitialProps;
 App.getInitialProps = appGetInitialProps;
-let warnContainer;
-let warnUrl;
-
-if (false) {} // @deprecated noop for now until removal
-
 
 function Container(p) {
-  if (false) {}
   return p.children;
 }
 
+const warnUr [...]

2019-08-23 14:59 UTC, Timer requested changes
Let's figure out an alternative for the QS story or remove it from this PR.

2019-08-23 14:59 UTC, Timer commented on packages/next/build/webpack-config.ts
> +              querystring: 'qss',
As explored/discussed on Slack, none of these overrides are ever safe.

2019-09-04 11:45 UTC, aralroca commented
One question @janicklas-ralph @arunoda regarding this example of the docs about polyfills:

https://github.com/zeit/next.js/blob/8aaac0c1e81cfe6700beb2bf63f713f15cc8b315/examples/with-polyfills/next.config.js

How can the people include this `unshift('./client/polyfills.js')` only in legacy builds? Is there some available variable inside the `webpack()` method?

2019-09-04 23:16 UTC, janicklas-ralph commented
As part of the PR, we will generate and include the `polyfill.js` file for only the legacy build.

2019-09-05 13:23 UTC, aralroca commented
> As part of the PR, we will generate and include the `polyfill.js` file for the legacy build. The goal is to have the optimizations by default, but you could still override the polyfill chunk with the example above.

@janicklas-ralph Then the example to add custom polyfills can be updated to something like:

```js
module.exports = {
  webpack: function (cfg) {
    const originalEntry = cfg.entry
    cfg.entry = async () => {
      const entries = await originalEntry()

     // polyfill.js only exist in legacy builds
     if(entries['polyfill.js']) {
        entries['polyfill.js'].unshift('./client/polyfills.js')
     }
      
      return entries
    }

    return cfg
  }
}
```
Or I'm wrong?

2019-09-10 17:38 UTC, Timer commented
Closing this because it's pretty stale now. Let's do future work in an new PR, please! 🙏

2019-09-10 17:38 UTC, closed without merging