Throw error if next export detects an API route
vercel/next.js pull request #8257
Opened 2019-08-06 01:51 UTC by lfades

Continuation of #8250 

The error was moved to after we get the paths defined by the user, and it now throws instead of doing a log, this avoids a throw from `next export` if attempting to compile the file

2019-08-06 01:58 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 12.8s | 12.5s | -265ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 702 kB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 13.4s | 13.6s | ⚠️  +191ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 300 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ✓ |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Serverless `pages/index` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | ✓ |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ✓ |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ⚠️  +1 B |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +2 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | -1 B |
| Build Dir Size | 1.89 MB | 1.89 MB | ✓ |

</details>

2019-08-06 04:54 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 13.2s | 13.2s | -55ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 702 kB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 14.6s | 14.6s | ⚠️  +69ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ✓ |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | -1 B |
| Serverless `pages/index` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | -1 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ✓ |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ✓ |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | -1 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | -1 B |
| Build Dir Size | 1.89 MB | 1.89 MB | ✓ |

</details>

2019-08-06 05:20 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 13.1s | 13.1s | -83ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | -1 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | -1 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 702 kB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 14.3s | 14.2s | -47ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | -1 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | -1 B |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ✓ |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Serverless `pages/index` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | ✓ |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ✓ |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ✓ |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | ✓ |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | ⚠️  +2 B |
| Build Dir Size | 1.89 MB | 1.89 MB | ✓ |

</details>

2019-08-06 05:36 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 12.4s | 12.6s | ⚠️  +233ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Base Rendered Size | 1.35 kB | 1.35 kB | ✓ |
| Build Dir Size | 702 kB | 702 kB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 13.2s | 13.7s | ⚠️  +490ms |
| `node_modules` Size | 43.6 MB | 43.6 MB | ⚠️  +429 B |
| Total Bundle (main, webpack, commons) Size | 206 kB | 206 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 67.8 kB | 67.8 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `main` Size | 15.4 kB | 15.4 kB | ✓ |
| Client `main` gzip Size | 5.35 kB | 5.35 kB | ✓ |
| Client `commons` Size | 188 kB | 188 kB | ✓ |
| Client `commons` gzip Size | 61.1 kB | 61.1 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Serverless `pages/link` Size | 251 kB | 251 kB | ✓ |
| Serverless `pages/link` gzip Size | 67.8 kB | 67.8 kB | ⚠️  +1 B |
| Serverless `pages/index` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/index` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +1 B |
| Serverless `pages/_error` Size | 243 kB | 243 kB | ✓ |
| Serverless `pages/_error` gzip Size | 65.4 kB | 65.4 kB | ✓ |
| Serverless `pages/routerDirect` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 65.6 kB | 65.6 kB | ⚠️  +1 B |
| Serverless `pages/withRouter` Size | 244 kB | 244 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 65.7 kB | 65.7 kB | ✓ |
| Build Dir Size | 1.89 MB | 1.89 MB | ✓ |

</details>

2019-08-06 20:21 UTC, huv1k requested changes
I would show a warning for default export map, so users are aware that there is no export fo API routes.

2019-08-07 10:03 UTC, timneutkens commented
I would remove the routes from defaultPathMap, but show a warning indeed.

2019-08-08 15:28 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 21.2s | 21s | -242ms |
| `node_modules` Size | 43.6 MB | 43.5 MB | -29.9 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 206 kB | -674 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 67.8 kB | -285 B |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 181 kB | -467 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.7 kB | -205 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.6 kB | -240 B |
| Client `main` gzip Size | 5.46 kB | 5.39 kB | -63 B |
| Client `main` Modern Size | 12.8 kB | 12.7 kB | -197 B |
| Client `main` Modern gzip Size | 4.83 kB | 4.77 kB | -65 B |
| Client `commons` Size | 188 kB | 188 kB | -434 B |
| Client `commons` gzip Size | 61.3 kB | 61.1 kB | -222 B |
| Client `commons` Modern Size | 169 kB | 168 kB | -270 B |
| Client `commons` Modern gzip Size | 55.1 kB | 54.9 kB | -140 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.39 MB | 1.39 MB | -5.02 kB |

</details>


<details>
<summary>Click to expand serverless stats ✅ Total Bundle Size Decrease ✅</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 22.4s | 22.8s | ⚠️  +377ms |
| `node_modules` Size | 43.6 MB | 43.5 MB | -29.9 kB |
| Total Bundle (main, webpack, commons) Size | 207 kB | 206 kB | -674 B |
| Total Bundle (main, webpack, commons) gzip Size | 68.1 kB | 67.8 kB | -285 B |
| Total Bundle (main, webpack, commons) Modern Size | 182 kB | 181 kB | -467 B |
| Total Bundle (main, webpack, commons) Modern gzip Size | 59.9 kB | 59.7 kB | -205 B |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.08 kB | 4.08 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.7 kB | 3.7 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.7 kB | 1.7 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.8 kB | 15.6 kB | -240 B |
| Client `main` gzip Size | 5.46 kB | 5.39 kB | -63 B |
| Client `main` Modern Size | 12.8 kB | 12.7 kB | -197 B |
| Client `main` Modern gzip Size | 4.83 kB | 4.77 kB | -65 B |
| Client `commons` Size | 188 kB | 188 kB | -434 B |
| Client `commons` gzip Size | 61.3 kB | 61.1 kB | -222 B |
| Client `commons` Modern Size | 169 kB | 168 kB | -270 B |
| Client `commons` Modern gzip Size | 55.1 kB | 54.9 kB | -140 B |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 254 kB | -1.18 kB |
| Serverless `pages/link` gzip Size | 68.6 kB | 68.2 kB | -398 B |
| Serverless `pages/index` Size | 248 kB | 247 kB | -1.16 kB |
| Serverless `pages/index` gzip Size | 66.4 kB | 66 kB | -382 B |
| Serverless `pages/_error` Size | 247 kB | 246 kB | -1.16 kB |
| Serverless `pages/_error` gzip Size | 66.1 kB | 65.7 kB | -386 B |
| Serverless `pages/routerDirect` Size | 248 kB | 247 kB | -1.16 kB |
| Serverless `pages/routerDirect` gzip Size | 66.3 kB | 65.9 kB | -388 B |
| Serverless `pages/withRouter` Size | 248 kB | 247 kB | -1.16 kB |
| Serverless `pages/withRouter` gzip Size | 66.4 kB | 66 kB | -384 B |
| Build Dir Size | 2.59 MB | 2.58 MB | -12.8 kB |

</details>
<details>
        <summary>Diff for <strong>main.js</strong></summary>

```diff

@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
@@ -503,7 +503,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regenerator["default"].mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx, appCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType;
 
     return _regenerator["default"].wrap(function _callee$(_context) {
       while (1) {
@@ -584,41 +584,16 @@ function () {
                 });
               }
             });
-            renderCtx = {
+            render({
               App: App,
               Component: Component,
               props: props,
               err: initialErr,
               emitter: emitter
-            };
-            render(renderCtx);
-
-            if (!(window.__NEXT_DATA__.skeleton && Component.getInitialProps)) {
-              _context.next = 32;
-              break;
-            }
-
-            appCtx = {
-              router: router,
-              AppTree: wrapApp(App),
-              Component: Component,
-              ctx: {
-                pathname: page,
-                asPath: asPath,
-                query: query
-              }
-            };
-            _context.next = 30;
-            return App.getInitialProps(appCtx);
-
-          case 30:
-            props.pageProps = _context.sent.pageProps;
-            render(renderCtx);
-
-          case 32:
+            });
             return _context.abrupt("return", emitter);
 [...]

2019-08-09 17:56 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 20.3s | 20.5s | ⚠️  +238ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +612 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.43 MB | 1.43 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | lfades/next.js api-export-error | Change |
| - | - | - | - |
| Build Duration | 22s | 22.1s | ⚠️  +76ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | ⚠️  +612 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.3 kB | 70.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 188 kB | 188 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.1 kB | 62.1 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 15.6 kB | 15.6 kB | ✓ |
| Client `main` gzip Size | 5.5 kB | 5.5 kB | ✓ |
| Client `main` Modern Size | 12.4 kB | 12.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.78 kB | 4.78 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.5 kB | 63.5 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ✓ |
| Serverless `pages/link` gzip Size | 68.7 kB | 68.7 kB | ⚠️  +2 B |
| Serverless `pages/index` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +2 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.2 kB | 66.2 kB | ✓ |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.4 kB | 66.4 kB | ⚠️  +1 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.5 kB | 66.5 kB | ⚠️  +1 B |
| Build Dir Size | 2.64 MB | 2.64 MB | ✓ |

</details>

2019-08-11 22:37 UTC, timneutkens approved these changes

2019-08-11 22:37 UTC, merged