Use 'initial' setting for SplitChunksPlugin
vercel/next.js pull request #8293
Opened 2019-08-09 06:00 UTC by atcastle

This fixes an issue with the granular chunks experimental feature in apps with dynamic imports. Using the "initial" setting for the chunks property causes SplitChunksPlugin not to split out modules that have been dynamically imported. This brings that behavior back in line with the current build system behavior.

I'll be investigating better solutions for code splitting with dynamic imports.

2019-08-09 13:55 UTC, Timer requested changes
We should really add a test case covering this exact scenario.

2019-08-09 19:57 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| Build Duration | 23.7s | 23.4s | -329ms |
| `node_modules` Size | 41.6 MB | 41.6 MB | -52 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.6 kB | ⚠️  +1 B |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.4 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ⚠️  +1 B |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ⚠️  +1 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 300 B | 301 B | ⚠️  +1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 16.3 kB | ✓ |
| Client `main` gzip Size | 5.73 kB | 5.73 kB | ✓ |
| Client `main` Modern Size | 13.1 kB | 13.1 kB | ✓ |
| Client `main` Modern gzip Size | 4.99 kB | 4.99 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.44 MB | 1.44 MB | ✓ |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| Build Duration | 24.9s | 26.1s | ⚠️  +1.3s |
| `node_modules` Size | 41.6 MB | 41.6 MB | -52 B |
| Total Bundle (main, webpack, commons) Size | 214 kB | 214 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 70.6 kB | 70.6 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 189 kB | 189 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 62.4 kB | 62.4 kB | ✓ |
| Client `_app` Size | 2.39 kB | 2.39 kB | ✓ |
| Client `_app` gzip Size | 1.08 kB | 1.08 kB | ✓ |
| Client `_app` Modern Size | 1.83 kB | 1.83 kB | ✓ |
| Client `_app` gzip Modern Size | 890 B | 890 B | ✓ |
| Client `_error` Size | 8.22 kB | 8.22 kB | ✓ |
| Client `_error` gzip Size | 3.16 kB | 3.16 kB | ✓ |
| Client `_error` Modern Size | 5.85 kB | 5.85 kB | ✓ |
| Client `_error` gzip Modern Size | 2.33 kB | 2.33 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.18 kB | 4.18 kB | ✓ |
| Client `pages/link` gzip Size | 1.82 kB | 1.82 kB | ✓ |
| Client `pages/link` Modern Size | 3.81 kB | 3.81 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 16.3 kB | 16.3 kB | ✓ |
| Client `main` gzip Size | 5.73 kB | 5.73 kB | ✓ |
| Client `main` Modern Size | 13.1 kB | 13.1 kB | ✓ |
| Client `main` Modern gzip Size | 4.99 kB | 4.99 kB | ✓ |
| Client `commons` Size | 195 kB | 195 kB | ✓ |
| Client `commons` gzip Size | 63.6 kB | 63.6 kB | ✓ |
| Client `commons` Modern Size | 176 kB | 176 kB | ✓ |
| Client `commons` Modern gzip Size | 57.4 kB | 57.4 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 256 kB | 256 kB | ✓ |
| Serverless `pages/link` gzip Size | 68.8 kB | 68.8 kB | ✓ |
| Serverless `pages/index` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.6 kB | -1 B |
| Serverless `pages/_error` Size | 248 kB | 248 kB | ✓ |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ✓ |
| Serverless `pages/routerDirect` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/routerDirect` gzip Size | 66.5 kB | 66.5 kB | -1 B |
| Serverless `pages/withRouter` Size | 249 kB | 249 kB | ✓ |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.6 kB | ✓ |
| Build Dir Size | 2.65 MB | 2.65 MB | ✓ |

</details>

2019-08-12 20:38 UTC, Timer approved these changes

2019-08-12 20:46 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 22.4s | 22.2s | -276ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 846 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 838 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 835 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 23.8s | 23.4s | -413ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ✓ |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | -1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

2019-08-12 21:00 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 22.8s | 22.8s | -74ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 847 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 834 B | -4 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 834 B | ✓ |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 25s | 24.7s | -315ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | -1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | -3 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | -2 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | -2 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | -2 B |
| Overall change |  |  | ✓ |

</details>

2019-08-12 21:23 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 23.1s | 23.2s | ⚠️ +158ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 846 B | -2 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 836 B | -2 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 835 B | 833 B | -2 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 25.7s | 25s | -712ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ⚠️ +1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ⚠️ +2 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

2019-08-12 21:39 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24.1s | ⚠️ +155ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 286 B | 287 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ⚠️ +1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 845 B | 847 B | ⚠️ +2 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 834 B | 838 B | ⚠️ +4 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 830 B | 834 B | ⚠️ +4 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 26.3s | 26.4s | ⚠️ +130ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | -1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | -2 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | -1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | -1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

2019-08-13 00:30 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 22.4s | 22.1s | -252ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 847 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 838 B | ⚠️ +1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 834 B | ✓ |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| buildDuration | 23.3s | 24s | ⚠️ +625ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | -68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | atcastle/next.js update-granular-chunks | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ⚠️ +1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ⚠️ +2 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +2 B |
| Overall change |  |  | ✓ |

</details>

2019-08-13 00:35 UTC, merged