[WIP] Fix for __dirname
vercel/next.js pull request #8334
Opened 2019-08-12 12:03 UTC by huv1k

2019-08-12 12:09 UTC, Timer requested changes

2019-08-12 12:09 UTC, Timer commented on packages/next/build/webpack-config.ts
> +              emitDirnameAll: false,
```suggestion
```

2019-08-12 12:09 UTC, Timer commented on packages/next/build/webpack-config.ts
> +              emitFilterAssetBaseAll: false,
```suggestion
```

2019-08-12 12:10 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 21.2s | 21s | -220ms |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.41 MB | ⚠️  +427 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 22.2s | 23s | ⚠️  +859ms |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | -1 B |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 300 B | -1 B |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +55 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +22 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +21 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +22 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +23 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +20 B |
| Build Dir Size | 2.61 MB | 2.61 MB | ⚠️  +275 B |

</details>

2019-08-12 12:14 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 24.4s | 23.5s | -805ms |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.41 MB | ⚠️  +427 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 25.6s | 26.9s | ⚠️  +1.3s |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +55 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +20 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +20 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +20 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +20 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +17 B |
| Build Dir Size | 2.61 MB | 2.61 MB | ⚠️  +275 B |

</details>

2019-08-12 12:22 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 22.9s | 22.3s | -542ms |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.41 MB | ⚠️  +427 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 25.1s | 26.9s | ⚠️  +1.8s |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +55 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +19 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +18 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +18 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +19 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +18 B |
| Build Dir Size | 2.61 MB | 2.61 MB | ⚠️  +275 B |

</details>

2019-08-12 13:32 UTC, ijjk commented
## Stats from current PR

<details>
<summary>Click to expand stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 22.6s | 22.9s | ⚠️  +273ms |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Base Rendered Size | 2.76 kB | 2.76 kB | ✓ |
| Build Dir Size | 1.41 MB | 1.41 MB | ⚠️  +427 B |

</details>


<details>
<summary>Click to expand serverless stats</summary>

| | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| Build Duration | 24.3s | 25.5s | ⚠️  +1.2s |
| `node_modules` Size | 41.6 MB | 43 MB | ⚠️  +1.38 MB |
| Total Bundle (main, webpack, commons) Size | 210 kB | 210 kB | ✓ |
| Total Bundle (main, webpack, commons) gzip Size | 69.3 kB | 69.3 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern Size | 187 kB | 187 kB | ✓ |
| Total Bundle (main, webpack, commons) Modern gzip Size | 61.6 kB | 61.6 kB | ✓ |
| Client `_app` Size | 1.9 kB | 1.9 kB | ✓ |
| Client `_app` gzip Size | 913 B | 913 B | ✓ |
| Client `_app` Modern Size | 1.79 kB | 1.79 kB | ✓ |
| Client `_app` gzip Modern Size | 880 B | 880 B | ✓ |
| Client `_error` Size | 8.02 kB | 8.02 kB | ✓ |
| Client `_error` gzip Size | 3.13 kB | 3.13 kB | ✓ |
| Client `_error` Modern Size | 5.82 kB | 5.82 kB | ✓ |
| Client `_error` gzip Modern Size | 2.35 kB | 2.35 kB | ✓ |
| Client `pages/index` Size | 343 B | 343 B | ✓ |
| Client `pages/index` gzip Size | 246 B | 246 B | ✓ |
| Client `pages/index` Modern Size | 319 B | 319 B | ✓ |
| Client `pages/index` gzip Modern Size | 254 B | 254 B | ✓ |
| Client `pages/link` Size | 4.07 kB | 4.07 kB | ✓ |
| Client `pages/link` gzip Size | 1.8 kB | 1.8 kB | ✓ |
| Client `pages/link` Modern Size | 3.78 kB | 3.78 kB | ✓ |
| Client `pages/link` gzip Modern Size | 1.72 kB | 1.72 kB | ✓ |
| Client `pages/routerDirect` Size | 423 B | 423 B | ✓ |
| Client `pages/routerDirect` gzip Size | 306 B | 306 B | ✓ |
| Client `pages/routerDirect` Modern Size | 411 B | 411 B | ✓ |
| Client `pages/routerDirect` gzip Modern Size | 314 B | 314 B | ✓ |
| Client `pages/withRouter` Size | 435 B | 435 B | ✓ |
| Client `pages/withRouter` gzip Size | 301 B | 301 B | ✓ |
| Client `pages/withRouter` Modern Size | 423 B | 423 B | ✓ |
| Client `pages/withRouter` gzip Modern Size | 309 B | 309 B | ✓ |
| Client `main` Size | 13.8 kB | 13.8 kB | ✓ |
| Client `main` gzip Size | 4.88 kB | 4.88 kB | ✓ |
| Client `main` Modern Size | 11.4 kB | 11.4 kB | ✓ |
| Client `main` Modern gzip Size | 4.32 kB | 4.32 kB | ✓ |
| Client `commons` Size | 194 kB | 194 kB | ✓ |
| Client `commons` gzip Size | 63.3 kB | 63.3 kB | ✓ |
| Client `commons` Modern Size | 175 kB | 175 kB | ✓ |
| Client `commons` Modern gzip Size | 57.3 kB | 57.3 kB | ✓ |
| Client `webpack` Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` gzip Size | 778 B | 778 B | ✓ |
| Client `webpack` Modern Size | 1.53 kB | 1.53 kB | ✓ |
| Client `webpack` Modern gzip Size | 785 B | 785 B | ✓ |
| Serverless `pages/link` Size | 255 kB | 255 kB | ⚠️  +55 B |
| Serverless `pages/link` gzip Size | 68.9 kB | 68.9 kB | ⚠️  +19 B |
| Serverless `pages/index` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/index` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +18 B |
| Serverless `pages/_error` Size | 247 kB | 247 kB | ⚠️  +55 B |
| Serverless `pages/_error` gzip Size | 66.3 kB | 66.3 kB | ⚠️  +19 B |
| Serverless `pages/routerDirect` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/routerDirect` gzip Size | 66.6 kB | 66.6 kB | ⚠️  +20 B |
| Serverless `pages/withRouter` Size | 248 kB | 248 kB | ⚠️  +55 B |
| Serverless `pages/withRouter` gzip Size | 66.6 kB | 66.7 kB | ⚠️  +19 B |
| Build Dir Size | 2.61 MB | 2.61 MB | ⚠️  +275 B |

</details>

2019-08-16 12:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 25.7s | 24.8s | -903ms |
| nodeModulesSize | 41.3 MB | 42.6 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.27 kB | -1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 601 B | ⚠️ +1 B |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | -1 B |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 289 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 850 B | 847 B | -3 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 840 B | 838 B | -2 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 837 B | 834 B | -3 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 26.5s | 28.5s | ⚠️ +2s |
| nodeModulesSize | 41.3 MB | 42.6 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ✓ |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ⚠️ +55 B |
| _error.js gzip | 66.3 kB | 66.3 kB | ⚠️ +21 B |
| hooks.html | 2.87 kB | 2.87 kB | ✓ |
| hooks.html gzip | 864 B | 867 B | ⚠️ +3 B |
| index.js | 248 kB | 248 kB | ⚠️ +55 B |
| index.js gzip | 66.6 kB | 66.6 kB | ⚠️ +21 B |
| link.js | 255 kB | 255 kB | ⚠️ +55 B |
| link.js gzip | 68.8 kB | 68.8 kB | ⚠️ +21 B |
| routerDirect.js | 248 kB | 248 kB | ⚠️ +55 B |
| routerDirect.js gzip | 66.5 kB | 66.5 kB | ⚠️ +22 B |
| withRouter.js | 248 kB | 248 kB | ⚠️ +55 B |
| withRouter.js gzip | 66.6 kB | 66.6 kB | ⚠️ +19 B |
| Overall change |  |  | ⚠️ +275 B |

</details>

</details>

2019-08-20 15:49 UTC, Timer requested changes

2019-08-20 15:49 UTC, Timer commented on packages/next/build/webpack-config.ts
> +              debugLog: false,
```suggestion
```

This is the default.

2019-08-20 15:49 UTC, Timer commented on packages/next/build/webpack-config.ts
> +    cache: isServer && dev ? false : true,
Disabling server cache seems wrong.

2019-08-29 15:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 23.3s | 22.6s | -691ms |
| nodeModulesSize | 41.3 MB | 42.7 MB | ⚠️ +1.35 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.8 kB | 17.9 kB | ⚠️ +106 B |
| main-HASH.js gzip | 6.55 kB | 6.56 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | ✓ |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | -1 B |
| Overall change |  |  | ⚠️ +106 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.1 kB | 16.2 kB | ⚠️ +59 B |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | -7 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | ✓ |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | ✓ |
| Overall change |  |  | ⚠️ +59 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.9 kB | ⚠️ +67 B |
| _app.js gzip | 881 B | 905 B | ⚠️ +24 B |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 600 B | 600 B | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 290 B | 290 B | ✓ |
| Overall change |  |  | ⚠️ +67 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.72 kB | 1.79 kB | ⚠️ +68 B |
| _app.module.js gzip | 838 B | 865 B | ⚠️ +27 B |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ⚠️ +68 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,7 +289,7 @@ var _interopRequireDefault = __webpack_require__("KI45");
 exports.__esModule = true;
 exports.render = render;
 exports.renderError = renderError;
-exports["default"] = exports.emitter = exports.ErrorComponent = exports.router = exports.dataManager = exports.version = void 0;
+exports["default"] = exports.emitter = exports.ErrorComponent = exports.router = exports.dataManager = void 0;
 
 var _asyncToGenerator2 = _interopRequireDefault(__webpack_require__("+oT+"));
 
@@ -338,13 +338,12 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.5";
-exports.version = version;
 var props = data.props,
     err = data.err,
     page = data.page,
     query = data.query,
     buildId = data.buildId,
+    dynamicBuildId = data.dynamicBuildId,
     assetPrefix = data.assetPrefix,
     runtimeConfig = data.runtimeConfig,
     dynamicIds = data.dynamicIds;
@@ -517,6 +516,8 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
+            if (false) {}
+
             exports.router = router = (0, _router.createRouter)(page, query, asPath, {
               initialProps: props,
               pageLoader: pageLoader,
@@ -547,7 +548,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
@@ -1434,6 +1435,8 @@ var PageLoader =
 /*#__PURE__*/
 function () {
   function PageLoader(buildId, assetPrefix) {
+    var _this3 = this;
+
     _classCallCheck(this, PageLoader);
 
     this.buildId = buildId;
@@ -1441,6 +1444,9 @@ function () {
     this.pageCache = {};
     this.pageRegisterEvents = (0, _mitt["default"])();
     this.loadingRoutes = {};
+    this.promisedBuildId = _promise["default"].resolve();
+
+    if (false) {}
 
     if (false) {}
   } // Returns a promise for the dependencies for a particular route
@@ -1469,7 +1475,7 @@ function () {
   }, {
     key: "loadPage",
     value: function loadPage(route) {
-      var _this3 = this;
+      var _this4 = this;
 
       route = this.normalizeRoute(route);
       return new _promise["default"](function (resolve, reject) {
@@ -1477,9 +1483,9 @@ function () {
           var error = _ref.error,
               page = _ref.page;
 
-          _this3.pageRegisterEvents.off(route, fire);
+          _this4.pageRegisterEvents.off(route, fire);
 
-          delete _this3.loadingRoutes[route];
+          delete _this4.loadingRoutes[route];
 
           if (error) {
             reject(error);
@@ -1489,7 +1495,7 @@ function () {
         }; // If there's a cached version of the page, let's use it.
 
 
-        var cachedPage = _this3.pageCache[route];
+        var cachedPage = _this4.pageCache[route];
 
         if (cachedPage) {
           var error = cachedPage.error,
@@ -1499,7 +1505,7 @@ function () {
         } // Register a listener to get the page
 
 
-        _this3.pageRegisterEvents.on(route, fire); // If the page is loading via SSR, we need to wait for it
+        _this4.pageRegisterEvents.on(route, fire); // If the page is loading via SSR, we need to wait for it
         // rather downloading it again.
 
 
@@ -1507,11 +1513,11 @@ function () {
           return;
         }
 
-        if (!_this3.loadingRoutes[route]) {
+        if (!_this4.loadingRoutes[route]) {
           if (false) {} else {
-            _this3.loadRoute(route);
+            _this4.loadRoute(route);
 
-            _this3.loadingRoutes[route] = true;
+            _this4.loadingRoutes[route] = true;
           }
         }
       });
@@ -1529,13 +1535,22 @@ function () {
           while (1) {
             switch (_context.prev = _context.next) {
               case 0:
+                if (true) {
+                  _context.next = 3;
+                  break;
+                }
+
+                _context.next = 3;
+                return _this.promisedBuildId;
+
+              case 3:
                 route = _this.normalizeRoute(route);
                 scriptRoute = route === '/' ? '/index.js' : route + ".js";
                 url = _this.assetPrefix + "/_next/static/" + encodeURIComponent(_this.buildId) + "/pages" + scriptRoute;
 
                 _this.loadScript(url, route, true);
 
-              case 4:
+              case 7:
               case "end":
                 return _context.stop();
             }
@@ -1546,7 +1561,7 @@ function () {
   }, {
     key: "loadScript",
     value: function loadScript(url, route, isPage) {
-      var _this4 = this;
+      var _this5 = this;
 
       var script = document.createElement('script');
 
@@ -1564,7 +1579,7 @@ function () {
      [...]

2019-08-30 09:48 UTC, huv1k commented
Blocked by https://github.com/zeit/webpack-asset-relocator-loader/pull/69

2019-08-30 09:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 22.6s | 22.4s | -284ms |
| nodeModulesSize | 41.8 MB | 42.7 MB | ⚠️ +898 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 17.8 kB | 17.9 kB | ⚠️ +84 B |
| main-HASH.js gzip | 6.56 kB | 6.56 kB | ⚠️ +3 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 190 kB | 190 kB | -46 B |
| commons.HASH.js gzip | 61.6 kB | 61.6 kB | -20 B |
| Overall change |  |  | ⚠️ +38 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.2 kB | 16.2 kB | ⚠️ +37 B |
| main-HASH.module.js gzip | 6.28 kB | 6.28 kB | -9 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 171 kB | 171 kB | -46 B |
| commons.HASH.module.js gzip | 55.4 kB | 55.4 kB | -15 B |
| Overall change |  |  | -9 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.9 kB | ⚠️ +67 B |
| _app.js gzip | 881 B | 905 B | ⚠️ +24 B |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 1.06 kB | 1.06 kB | ✓ |
| hooks.js gzip | 601 B | 600 B | -1 B |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.13 kB | 8.13 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 429 B | 429 B | ✓ |
| routerDirect.js gzip | 292 B | 292 B | ✓ |
| withRouter.js | 439 B | 439 B | ✓ |
| withRouter.js gzip | 289 B | 290 B | ⚠️ +1 B |
| Overall change |  |  | ⚠️ +67 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.72 kB | 1.79 kB | ⚠️ +68 B |
| _app.module.js gzip | 838 B | 865 B | ⚠️ +27 B |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| hooks.module.js | 596 B | 596 B | ✓ |
| hooks.module.js gzip | 354 B | 354 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 417 B | 417 B | ✓ |
| routerDirect.module.js gzip | 292 B | 292 B | ✓ |
| withRouter.module.js | 427 B | 427 B | ✓ |
| withRouter.module.js gzip | 291 B | 291 B | ✓ |
| Overall change |  |  | ⚠️ +68 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -289,7 +289,7 @@ var _interopRequireDefault = __webpack_require__("KI45");
 exports.__esModule = true;
 exports.render = render;
 exports.renderError = renderError;
-exports["default"] = exports.emitter = exports.ErrorComponent = exports.router = exports.dataManager = exports.version = void 0;
+exports["default"] = exports.emitter = exports.ErrorComponent = exports.router = exports.dataManager = void 0;
 
 var _asyncToGenerator2 = _interopRequireDefault(__webpack_require__("+oT+"));
 
@@ -338,13 +338,12 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.5";
-exports.version = version;
 var props = data.props,
     err = data.err,
     page = data.page,
     query = data.query,
     buildId = data.buildId,
+    dynamicBuildId = data.dynamicBuildId,
     assetPrefix = data.assetPrefix,
     runtimeConfig = data.runtimeConfig,
     dynamicIds = data.dynamicIds;
@@ -517,6 +516,8 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
+            if (false) {}
+
             exports.router = router = (0, _router.createRouter)(page, query, asPath, {
               initialProps: props,
               pageLoader: pageLoader,
@@ -547,7 +548,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
@@ -1425,7 +1426,7 @@ function preloadScript(url) {
   var link = document.createElement('link');
   link.rel = 'preload';
   link.crossOrigin = "anonymous";
-  link.href = encodeURI(url);
+  link.href = url;
   link.as = 'script';
   document.head.appendChild(link);
 }
@@ -1434,6 +1435,8 @@ var PageLoader =
 /*#__PURE__*/
 function () {
   function PageLoader(buildId, assetPrefix) {
+    var _this3 = this;
+
     _classCallCheck(this, PageLoader);
 
     this.buildId = buildId;
@@ -1441,6 +1444,9 @@ function () {
     this.pageCache = {};
     this.pageRegisterEvents = (0, _mitt["default"])();
     this.loadingRoutes = {};
+    this.promisedBuildId = _promise["default"].resolve();
+
+    if (false) {}
 
     if (false) {}
   } // Returns a promise for the dependencies for a particular route
@@ -1469,7 +1475,7 @@ function () {
   }, {
     key: "loadPage",
     value: function loadPage(route) {
-      var _this3 = this;
+      var _this4 = this;
 
       route = this.normalizeRoute(route);
       return new _promise["default"](function (resolve, reject) {
@@ -1477,9 +1483,9 @@ function () {
           var error = _ref.error,
               page = _ref.page;
 
-          _this3.pageRegisterEvents.off(route, fire);
+          _this4.pageRegisterEvents.off(route, fire);
 
-          delete _this3.loadingRoutes[route];
+          delete _this4.loadingRoutes[route];
 
           if (error) {
             reject(error);
@@ -1489,7 +1495,7 @@ function () {
         }; // If there's a cached version of the page, let's use it.
 
 
-        var cachedPage = _this3.pageCache[route];
+        var cachedPage = _this4.pageCache[route];
 
         if (cachedPage) {
           var error = cachedPage.error,
@@ -1499,7 +1505,7 @@ function () {
         } // Register a listener to get the page
 
 
-        _this3.pageRegisterEvents.on(route, fire); // If the page is loading via SSR, we need to wait for it
+        _this4.pageRegisterEvents.on(route, fire); // If the page is loading via SSR, we need to wait for it
         // rather downloading it again.
 
 
@@ -1507,11 +1513,11 @@ function () {
           return;
         }
 
-        if (!_this3.loadingRoutes[route]) {
+        if (!_this4.loadingRoutes[route]) {
           if (false) {} else {
-            _this3.loadRoute(route);
+            _this4.loadRoute(route);
 
-            _this3.loadingRoutes[route] = true;
+            _this4.loadingRoutes[route] = true;
           }
         }
       });
@@ -1529,13 +1535,22 @@ function () {
           while (1) {
             switch (_context.prev = _context.next) {
               case 0:
+                if (true) {
+                  _context.next = 3;
+                  break;
+                }
+
+                _context.next = 3;
+                return _this.promisedBuildId;
+
+              case 3:
                 route = _this.normalizeRoute(route);
                 scriptRoute = route === '/' ? '/index.js' : route + ".js";
                 url = _this.assetPrefix + "/_next/static/" + encodeURIComponent(_this.buildId) + "/pages" + scriptRoute;
 
                 _this.loadScript(url, route, true);
 
-              case 4:
+              case 7:
               case "end":
                 return _context.stop( [...]

2019-09-11 07:50 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24.5s | ⚠️ +554ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 956 B | 956 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 25s | 25.5s | ⚠️ +460ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  [...]

2019-09-11 08:48 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 24s | 25.3s | ⚠️ +1.3s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 956 B | 956 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 24s | 26.3s | ⚠️ +2.3s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | z [...]

2019-09-11 12:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 24.3s | 24s | -303ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 956 B | 956 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 23.9s | 25.6s | ⚠️ +1.7s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | z [...]

2019-09-11 13:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 27.3s | 27.2s | -148ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 956 B | 956 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 27.5s | 28.2s | ⚠️ +773ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|   [...]

2019-09-11 16:23 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 23.1s | 22.8s | -291ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 956 B | 956 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24.8s | ⚠️ +1.1s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | [...]

2019-09-11 17:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 22.3s | 23.2s | ⚠️ +924ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..1c5d17695.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..7695.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5f.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.11 kB | 8.11 kB | ✓ |
| link.js gzip | 3.48 kB | 3.48 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.5 kB | 8.5 kB | ✓ |
| link.module.js gzip | 3.66 kB | 3.66 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 945 B | 945 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 941 B | 941 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 22.3s | 23.5s | ⚠️ +1.2s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..1c5d17695.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..7695.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5f.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.11 kB | 8.11 kB | ✓ |
| link.js gzip | 3.48 kB | 3.48 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.5 kB | 8.5 kB | ✓ |
| link.module.js gzip | 3.66 kB | 3.66 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  |  [...]

2019-09-11 19:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 22.1s | 21.8s | -265ms |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..1c5d17695.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..7695.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5f.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.11 kB | 8.11 kB | ✓ |
| link.js gzip | 3.48 kB | 3.48 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.5 kB | 8.5 kB | ✓ |
| link.module.js gzip | 3.66 kB | 3.66 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 945 B | 945 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 953 B | 953 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 941 B | 941 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 21.6s | 23.5s | ⚠️ +1.9s |
| nodeModulesSize | 42.4 MB | 43.8 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..1c5d17695.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..7695.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.4 kB | 6.4 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..5f.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.11 kB | 8.11 kB | ✓ |
| link.js gzip | 3.48 kB | 3.48 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.5 kB | 8.5 kB | ✓ |
| link.module.js gzip | 3.66 kB | 3.66 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zei [...]

2019-09-17 07:01 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 16s | 15.9s | -136ms |
| nodeModulesSize | 42 MB | 43.3 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..3fa59b1f5.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..b1f5.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 945 B | 945 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 954 B | 954 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 941 B | 941 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| buildDuration | 16s | 16.7s | ⚠️ +637ms |
| nodeModulesSize | 42 MB | 43.3 MB | ⚠️ +1.38 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.65 kB | 6.65 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..3fa59b1f5.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..b1f5.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..4b.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js dirname-fix | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/n [...]

2019-09-21 17:59 UTC, tomthornton commented
Very excited for this feature. My API involves reading and writing files so this will be great.

2019-10-01 07:18 UTC, BrunoBernardino commented
Thank you so much for this @huv1k! For @Timer : Is there anything I can do to help get this merged/shipped more quickly?

2019-10-16 05:09 UTC, Timer commented
Closing this as we decided to go with a simpler variant that doesn't parse the webpack output. We'll post updates here when we have movement on it.

2019-10-16 05:09 UTC, closed without merging

2019-10-16 07:07 UTC, BrunoBernardino commented
Thanks @Timer! Is there a rough ETA? Like before EOY or whenever more people ask for it?

2019-10-16 08:56 UTC, timneutkens commented
I've de-prioritized this work as we're currently focused on other improvements that have more impact than this change and this change is quite tricky to get right (would require quite a bit of maintenance overhead).

2019-10-16 09:52 UTC, BrunoBernardino commented
That makes sense, I'll make sure to build a separate lambda that makes the file reading, then.

Thanks for the honesty, @timneutkens!

2019-10-16 10:35 UTC, timneutkens commented
Feel free to take on this issue / investigate a solution btw!

2019-10-16 10:57 UTC, BrunoBernardino commented
Would you be willing to share your thoughts on:

> we decided to go with a simpler variant that doesn't parse the webpack output

? I'm happy to try and implement something with very few pointers. This PR actually seemed like a pretty simple solution to me, so I'm probably missing a ton of context.

2019-12-24 01:14 UTC, Albert-Gao commented
Any updates on this? just migrated my API to Now serverless, and encounter this problem when using Prisma2, don't want to change my deployment solution.

2020-03-06 02:27 UTC, lupelius commented
this is quite an impactful piece of next.js, the whole /api/ capability, without this no one can serve xml pages etc on production builds... Quite a limitation for next.js over php...

2021-08-17 13:49 UTC, Vrq commented
Why was closed and what is the other option @Timer

2021-08-18 10:08 UTC, timneutkens commented
This is currently in progress: #25538