Add missing dependency "compression" to next-server
vercel/next.js pull request #8344
Opened 2019-08-12 21:41 UTC by elliottsj

On version 9.0.3, this error occurs after installing Next.js using pnpm and starting a server:

```
Error: Cannot find module 'compression'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path/to/project/node_modules/.registry.npmjs.org/next-server/9.0.3_react-dom@16.9.0+react@16.9.0/node_modules/next-server/dist/server/next-server.js:17:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

This happens because the _compression_ package isn't visible to _next-server_ in pnpm's strict `node_modules` structure.

The fix is for _next-server_ to declare _compression_ as a dependency.

2019-08-12 21:48 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 22.5s | 22.3s | -191ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 845 B | -1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 836 B | -1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 833 B | -1 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 24.5s | 24.1s | -449ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ✓ |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

2019-08-13 00:57 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 23s | 22.7s | -254ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 846 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 837 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 834 B | ✓ |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 25.2s | 24.8s | -410ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ⚠️ +28 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ⚠️ +1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ✓ |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ⚠️ +1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

2019-08-13 02:17 UTC, Timer requested changes
Please remove this dep from the `next` package, too.

2019-08-13 03:22 UTC, elliottsj commented
@Timer Done

2019-08-13 03:29 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 23s | 23s | ⚠️ +68ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 844 B | 845 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 836 B | 836 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 832 B | 833 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 25.1s | 25.2s | ⚠️ +12ms |
| nodeModulesSize | 41.6 MB | 41.6 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.84 kB | 4.84 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.29 kB | 4.29 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.1 kB | 66.1 kB | ✓ |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.6 kB | 68.6 kB | ⚠️ +1 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ✓ |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

2019-08-13 03:51 UTC, Timer approved these changes

2019-08-13 15:11 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 22.5s | 23s | ⚠️ +525ms |
| nodeModulesSize | 41.5 MB | 41.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 848 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 842 B | ⚠️ +4 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 837 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 24.3s | 23.9s | -408ms |
| nodeModulesSize | 41.5 MB | 41.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 287 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | ✓ |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | -1 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | -1 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ✓ |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | -1 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | -1 B |
| Overall change |  |  | ✓ |

</details>

2019-08-13 15:57 UTC, ijjk commented
# Stats from current PR

### Default Server Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 24.6s | 24.2s | -430ms |
| nodeModulesSize | 41.5 MB | 41.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 847 B | 848 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 840 B | ⚠️ +3 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 836 B | ⚠️ +2 B |
| Overall change |  |  | ✓ |

</details>


### Serverless Mode

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| buildDuration | 26.4s | 25.6s | -742ms |
| nodeModulesSize | 41.5 MB | 41.5 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.07 kB | ✓ |
| link.js gzip | 1.79 kB | 1.79 kB | ✓ |
| routerDirect.js | 423 B | 423 B | ✓ |
| routerDirect.js gzip | 290 B | 290 B | ✓ |
| withRouter.js | 435 B | 435 B | ✓ |
| withRouter.js gzip | 287 B | 286 B | -1 B |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.78 kB | ✓ |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 411 B | ✓ |
| routerDirect.module.js gzip | 291 B | 291 B | ✓ |
| withRouter.module.js | 423 B | 423 B | ✓ |
| withRouter.module.js gzip | 288 B | 288 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | elliottsj/next.js add-compression-dep | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ✓ |
| _error.js gzip | 66.2 kB | 66.2 kB | ⚠️ +7 B |
| index.js | 247 kB | 247 kB | ✓ |
| index.js gzip | 66.5 kB | 66.5 kB | ⚠️ +5 B |
| link.js | 255 kB | 255 kB | ✓ |
| link.js gzip | 68.7 kB | 68.7 kB | ⚠️ +6 B |
| routerDirect.js | 248 kB | 248 kB | ✓ |
| routerDirect.js gzip | 66.4 kB | 66.4 kB | ⚠️ +4 B |
| withRouter.js | 248 kB | 248 kB | ✓ |
| withRouter.js gzip | 66.5 kB | 66.5 kB | ⚠️ +4 B |
| Overall change |  |  | ✓ |

</details>

2019-08-13 16:03 UTC, merged

2024-06-06 15:39 UTC, wbinnssmith approved these changes