Feature: Add transparent JSX optimization
vercel/next.js pull request #8350
Opened 2019-08-13 17:30 UTC by developit

This retains the existing React auto-import behavior (via the same plugin), but changes the JSX pragma to use hoisted `__jsx()` function that avoids the overhead of repeated `Object(_react.default.createElement)()` calls.

2019-08-13 21:49 UTC, developit commented
Update: `babel-plugin-react-require` duplicates the React import, not sure why given it has logic to detect this. Since the JSX plugin added here already adds `React` to any file with JSX if not already defined, we can consolidate.

2019-08-13 21:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 25.5s | 25.7s | ⚠️ +222ms |
| nodeModulesSize | 41.2 MB | 41.5 MB | ⚠️ +363 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 845 B | 845 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 838 B | 839 B | ⚠️ +1 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 833 B | 831 B | -2 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPAC [...]

2019-08-14 01:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 23.4s | 23.7s | ⚠️ +289ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +4.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.31 kB | 4.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 175 kB | 175 kB | ✓ |
| commons.HASH.module.js gzip | 57.1 kB | 57.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 847 B | ⚠️ +1 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 839 B | 837 B | -2 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 835 B | 832 B | -3 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEB [...]

2019-08-14 15:39 UTC, developit commented
Actual tests are [passing](https://travis-ci.org/zeit/next.js/jobs/571616318#L2901), failures are from canary.

2019-08-15 14:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 24.8s | 24.4s | -447ms |
| nodeModulesSize | 41.3 MB | 41.3 MB | ⚠️ +4.81 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 848 B | 848 B | ✓ |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 839 B | 839 B | ✓ |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 836 B | 834 B | -2 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED [...]

2019-08-15 14:54 UTC, Timer approved these changes
This looks great.

2019-08-15 15:00 UTC, Timer requested changes
Let's drop `babel-plugin-react-require` from `package.json`!

2019-08-15 16:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 24.1s | 24.2s | ⚠️ +105ms |
| nodeModulesSize | 41.3 MB | 41.2 MB | -3.54 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 848 B | ⚠️ +2 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 840 B | 843 B | ⚠️ +3 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 835 B | 838 B | ⚠️ +3 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEB [...]

2019-08-15 16:54 UTC, Timer approved these changes

2019-08-15 17:03 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24.4s | ⚠️ +557ms |
| nodeModulesSize | 41.3 MB | 41.2 MB | -3.95 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.86 kB | 4.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 286 B | 290 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -1 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.81 kB | 2.81 kB | ✓ |
| link gzip | 846 B | 848 B | ⚠️ +2 B |
| index | 2.76 kB | 2.76 kB | ✓ |
| index gzip | 837 B | 842 B | ⚠️ +5 B |
| withRouter | 2.82 kB | 2.82 kB | ✓ |
| withRouter gzip | 834 B | 837 B | ⚠️ +3 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEB [...]

2019-08-15 18:05 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 23.8s | 22.7s | -1.1s |
| nodeModulesSize | 41.3 MB | 41.2 MB | -3.95 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 848 B | 848 B | ✓ |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 840 B | 840 B | ✓ |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 837 B | 837 B | ✓ |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I use withRouter");
+  return __jsx("div", null, "I use withRouter");
 }
 
 useWithRouter.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.module.js</strong></summary>

```diff
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = () => ({});
```
</details>
<details>
<summary>Diff for <strong>withRouter.module.js</strong></summary>

```diff
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__ [...]

2019-08-15 18:20 UTC, Timer commented
Tests are failing because of CommonJS incompatibility. We can land this once that's resolved!

2019-08-15 20:55 UTC, developit commented
@Timer apologies for the delay, should be fixed now.

2019-08-15 21:03 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| buildDuration | 23.4s | 23.9s | ⚠️ +497ms |
| nodeModulesSize | 41.3 MB | 41.2 MB | -2.96 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.js | 13.8 kB | 13.8 kB | ✓ |
| main-HASH.js gzip | 4.87 kB | 4.87 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.js | 194 kB | 194 kB | ✓ |
| commons.HASH.js gzip | 63.1 kB | 63.1 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| main-HASH.module.js | 11.4 kB | 11.4 kB | ✓ |
| main-HASH.module.js gzip | 4.3 kB | 4.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| commons.HASH.module.js | 176 kB | 176 kB | ✓ |
| commons.HASH.module.js gzip | 57.2 kB | 57.2 kB | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 905 B | 905 B | ✓ |
| _error.js | 8.02 kB | 8.02 kB | ✓ |
| _error.js gzip | 3.12 kB | 3.12 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 4.07 kB | 4.04 kB | -28 B |
| link.js gzip | 1.79 kB | 1.79 kB | -1 B |
| routerDirect.js | 423 B | 429 B | ⚠️ +6 B |
| routerDirect.js gzip | 290 B | 293 B | ⚠️ +3 B |
| withRouter.js | 435 B | 439 B | ⚠️ +4 B |
| withRouter.js gzip | 287 B | 290 B | ⚠️ +3 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 865 B | 865 B | ✓ |
| _error.module.js | 5.82 kB | 5.82 kB | ✓ |
| _error.module.js gzip | 2.33 kB | 2.33 kB | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 3.78 kB | 3.75 kB | -28 B |
| link.module.js gzip | 1.7 kB | 1.7 kB | -2 B |
| routerDirect.module.js | 411 B | 417 B | ⚠️ +6 B |
| routerDirect.module.js gzip | 291 B | 293 B | ⚠️ +2 B |
| withRouter.module.js | 423 B | 427 B | ⚠️ +4 B |
| withRouter.module.js gzip | 288 B | 292 B | ⚠️ +4 B |
| Overall change |  |  | -18 B |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | developit/next.js jsx-namespace-optimization | Change |
| - | - | - | - |
| link | 2.8 kB | 2.8 kB | ✓ |
| link gzip | 848 B | 849 B | ⚠️ +1 B |
| index | 2.75 kB | 2.75 kB | ✓ |
| index gzip | 842 B | 841 B | -1 B |
| withRouter | 2.81 kB | 2.81 kB | ✓ |
| withRouter gzip | 837 B | 838 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
@@ -26,10 +26,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("YFqc");
 /* harmony import */ var next_link__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_link__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function aLink(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("h3", null, "A Link page!"), react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
+  return __jsx("div", null, __jsx("h3", null, "A Link page!"), __jsx(next_link__WEBPACK_IMPORTED_MODULE_1___default.a, {
     href: "/"
   }, "Go to /"));
 }
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
@@ -23,12 +23,13 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 /* eslint-disable-next-line */
 
 
 function routerDirect(props) {
-  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "I import the router directly");
+  return __jsx("div", null, "I import the router directly");
 }
 
 routerDirect.getInitialProps = function () {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
@@ -10,10 +10,11 @@ __webpack_require__.r(__webpack_exports__);
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("nOHt");
 /* harmony import */ var next_router__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(next_router__WEBPACK_IMPORTED_MODULE_1__);
 
+var __jsx = react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement;
 
 
 function useWithRouter(props) {
-  return react__WEBPACK_IMPORTED_MO [...]

2019-08-15 21:07 UTC, merged

2019-10-30 15:29 UTC, cranberyxl commented
When using next.js with typescript and importing react `import * as React from 'react';` I'm getting double React imports. Any advice? I'm looking into how some other plugins detect it to see if there is a workaround.