Fix bug in hook destructuring optimization when ignoring array elements
vercel/next.js pull request #8455
Opened 2019-08-21 04:35 UTC by raon0211

Recent versions of next.js contain optimization in hook destructuring. (see #8382)

This transform inputs like

```ts
function Foo() {
  const [count, setCount] = useState(0);
}
```

to outputs like the following.

```ts
function Foo() {
  const { 0: count, 1: setCount } = useState(0);
}
```

However when some of the values are ignored in the destructuring process like the following code, the plugin emits an error.

```ts
function Foo() {
  const [, foo] = useSomeHook(arg);
}

// --> TypeError: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got null
//        at Array.map (<anonymous>)
```

This is because when some elements are ignored, those elements are marked as `null` in babel, and it violates the babel's validation logic where it is passed to the second argument of `t.objectProperty`.

This PR fixes this bug by adding the filtering logic of ignored elements.

2019-08-21 04:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 22s | 22.5s | ⚠️ +426ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.75 kB | 3.75 kB | ✓ |
| link gzip | 961 B | 962 B | ⚠️ +1 B |
| index | 3.69 kB | 3.69 kB | ✓ |
| index gzip | 953 B | 953 B | ✓ |
| withRouter | 3.75 kB | 3.75 kB | ✓ |
| withRouter gzip | 948 B | 949 B | ⚠️ +1 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 24s | 24.1s | ⚠️ +135ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ⚠️ +5 B |
| _error.js gzip | 66.4 kB | 66.4 kB | ⚠️ +62 B |
| hooks.html | 3.81 kB | 3.81 kB | ⚠️ +1 B |
| hooks.html gzip | 977 B | 976 B | -1 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.6 kB | 66.7 kB | ⚠️ +89 B |
| link.js | 256 kB | 256 kB | ✓ |
| link.js gzip | 68.9 kB | 68.9 kB | ⚠️ +16 B |
| routerDirect.js | 249 kB | 249 kB | ✓ |
| routerDirect.js gzip | 66.7 kB | 66.7 kB | ⚠️ +20 B |
| withRouter.js | 249 kB | 249 kB | ✓ |
| withRouter.js gzip | 66.8 kB | 66.9 kB | ⚠️ +76 B |
| Overall change |  |  | ⚠️ +6 B |

</details>

</details>

2019-08-21 04:48 UTC, Timer requested changes
Please add a test case!

2019-08-21 05:02 UTC, raon0211 commented
I added some test cases.

2019-08-21 05:10 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 24.4s | 24.7s | ⚠️ +242ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ⚠️ +1 B |
| main-HASH.js gzip | 6.62 kB | 6.63 kB | ⚠️ +1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ⚠️ +1 B |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ⚠️ +1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | -1 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | -1 B |
| routerDirect.js | 434 B | 433 B | -1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 866 B | 867 B | ⚠️ +1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 805 B | 804 B | -1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 430 B | 429 B | -1 B |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.75 kB | 3.74 kB | -4 B |
| link gzip | 961 B | 958 B | -3 B |
| index | 3.69 kB | 3.69 kB | -4 B |
| index gzip | 953 B | 950 B | -3 B |
| withRouter | 3.75 kB | 3.75 kB | -4 B |
| withRouter gzip | 947 B | 945 B | -2 B |
| Overall change |  |  | -12 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
` [...]

2019-08-21 12:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 22.3s | 22s | -322ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.74 kB | 3.75 kB | ⚠️ +3 B |
| link gzip | 961 B | 962 B | ⚠️ +1 B |
| index | 3.69 kB | 3.69 kB | ⚠️ +3 B |
| index gzip | 953 B | 953 B | ✓ |
| withRouter | 3.75 kB | 3.75 kB | ⚠️ +3 B |
| withRouter gzip | 947 B | 948 B | ⚠️ +1 B |
| Overall change |  |  | ⚠️ +9 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24s | ⚠️ +235ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ⚠️ +8 B |
| _error.js gzip | 66.4 kB | 66.4 kB | ⚠️ +12 B |
| hooks.html | 3.81 kB | 3.81 kB | ⚠️ +3 B |
| hooks.html gzip | 980 B | 980 B | ✓ |
| index.js | 248 kB | 248 kB | ⚠️ +8 B |
| index.js gzip | 66.6 kB | 66.7 kB | ⚠️ +105 B |
| link.js | 256 kB | 256 kB | ⚠️ +8 B |
| link.js gzip | 68.7 kB | 68.8 kB | ⚠️ +38 B |
| routerDirect.js | 249 kB | 249 kB | ⚠️ +8 B |
| routerDirect.js gzip | 66.7 kB | 66.7 kB | -12 B |
| withRouter.js | 249 kB | 249 kB | ⚠️ +8 B |
| withRouter.js gzip | 66.7 kB | 66.9 kB | ⚠️ +149 B |
| Overall change |  |  | ⚠️ +43 B |

</details>

</details>

2019-08-21 14:34 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 25.4s | 24.9s | -531ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.74 kB | 3.75 kB | ⚠️ +3 B |
| link gzip | 959 B | 964 B | ⚠️ +5 B |
| index | 3.69 kB | 3.69 kB | ⚠️ +3 B |
| index gzip | 951 B | 956 B | ⚠️ +5 B |
| withRouter | 3.75 kB | 3.75 kB | ⚠️ +3 B |
| withRouter gzip | 947 B | 950 B | ⚠️ +3 B |
| Overall change |  |  | ⚠️ +9 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 26.9s | 27.4s | ⚠️ +507ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ⚠️ +3 B |
| _error.js gzip | 66.3 kB | 66.3 kB | ⚠️ +47 B |
| hooks.html | 3.81 kB | 3.81 kB | ⚠️ +2 B |
| hooks.html gzip | 978 B | 978 B | ✓ |
| index.js | 248 kB | 248 kB | ⚠️ +3 B |
| index.js gzip | 66.7 kB | 66.6 kB | -112 B |
| link.js | 256 kB | 256 kB | ⚠️ +3 B |
| link.js gzip | 68.9 kB | 68.9 kB | -13 B |
| routerDirect.js | 249 kB | 249 kB | ⚠️ +3 B |
| routerDirect.js gzip | 66.6 kB | 66.9 kB | ⚠️ +271 B |
| withRouter.js | 249 kB | 249 kB | ⚠️ +3 B |
| withRouter.js gzip | 66.9 kB | 66.8 kB | -97 B |
| Overall change |  |  | ⚠️ +17 B |

</details>

</details>

2019-08-21 16:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 24.3s | 23.7s | -631ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.74 kB | 3.74 kB | ⚠️ +5 B |
| link gzip | 962 B | 962 B | ✓ |
| index | 3.69 kB | 3.69 kB | ⚠️ +5 B |
| index gzip | 954 B | 954 B | ✓ |
| withRouter | 3.75 kB | 3.75 kB | ⚠️ +5 B |
| withRouter gzip | 949 B | 948 B | -1 B |
| Overall change |  |  | ⚠️ +15 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
 
 /***/ "0Hlz":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = w [...]

2019-08-21 18:17 UTC, Timer requested changes
We need a test for the modern version, too!

2019-08-22 02:50 UTC, raon0211 commented
Could you elaborate? Do you mean I have to add an example to a stats app (in `test/.stats-app/pages/hooks.js`)? or add a test for CommonJS mode? 

The reason is that there are no more explicit tests added in the [original pull request](https://github.com/zeit/next.js/pull/8381), and it seems that my test is already for modern mode. (the second argument to the babel function is given as `true`.)

I will happily add tests needed when things become clear!

2019-08-22 14:37 UTC, developit approved these changes
LGTM! Just to clarify, the intermediary output here is as follows: (useful when outputting modern, since we can leave destructuring in-place)

```js
// input:
const [, foo] = useState(0);

// output:
const { 1: foo } = useState(0);
```

2019-08-22 14:49 UTC, Timer approved these changes

2019-08-22 15:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 24.4s | 24.2s | -217ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Fetched pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| link | 3.73 kB | 3.74 kB | ⚠️ +7 B |
| link gzip | 956 B | 961 B | ⚠️ +5 B |
| index | 3.69 kB | 3.69 kB | ⚠️ +7 B |
| index gzip | 948 B | 953 B | ⚠️ +5 B |
| withRouter | 3.74 kB | 3.75 kB | ⚠️ +7 B |
| withRouter gzip | 943 B | 948 B | ⚠️ +5 B |
| Overall change |  |  | ⚠️ +21 B |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| buildDuration | 25.3s | 25.3s | ⚠️ +21ms |
| nodeModulesSize | 41.2 MB | 41.2 MB | ⚠️ +299 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.js | 18.1 kB | 18.1 kB | ✓ |
| main-HASH.js gzip | 6.63 kB | 6.63 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.36 kB | 6.36 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.js | 1.9 kB | 1.9 kB | ✓ |
| _app.js gzip | 908 B | 908 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _app.module.js | 1.79 kB | 1.79 kB | ✓ |
| _app.module.js gzip | 867 B | 867 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | raon0211/next.js hook-destructure | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ⚠️ +13 B |
| _error.js gzip | 66.4 kB | 66.3 kB | -137 B |
| hooks.html | 3.81 kB | 3.81 kB | ⚠️ +4 B |
| hooks.html gzip | 977 B | 978 B | ⚠️ +1 B |
| index.js | 248 kB | 248 kB | ⚠️ +13 B |
| index.js gzip | 66.8 kB | 66.6 kB | -185 B |
| link.js | 256 kB | 256 kB | ⚠️ +13 B |
| link.js gzip | 68.9 kB | 68.9 kB | ⚠️ +47 B |
| routerDirect.js | 249 kB | 249 kB | ⚠️ +13 B |
| routerDirect.js gzip | 66.7 kB | 66.9 kB | ⚠️ +143 B |
| withRouter.js | 249 kB | 249 kB | ⚠️ +13 B |
| withRouter.js gzip | 66.6 kB | 66.8 kB | ⚠️ +193 B |
| Overall change |  |  | ⚠️ +69 B |

</details>

</details>

2019-08-22 15:21 UTC, merged