Update performance marking
vercel/next.js pull request #8527
Opened 2019-08-27 00:32 UTC by housseindjirdeh

Fixes #8517 

This PR:

- Only clears Next-specific performance marks
- Adds an integration test to make sure marks are cleared

2019-08-27 08:59 UTC, timneutkens commented on packages/next-server/lib/utils.ts
> +export const PERF_MARKS = {
This is used on the client-side so definitely don't use constants.ts as it would include all constants in the client side

2019-08-27 09:05 UTC, timneutkens commented on packages/next-server/lib/utils.ts
> +export const PERF_MARKS = {
It's probably best to hardcode these to save bundle size.

2019-08-28 18:34 UTC, Timer requested changes
Let's please add a test that makes sure a custom mark is not deleted. 🙏

2019-08-30 22:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| buildDuration | 25.6s | 24s | -1.6s |
| nodeModulesSize | 42 MB | 41.5 MB | -453 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ⚠️ +68 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +15 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.6 kB | ⚠️ +51 B |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +51 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| index.html | 3.69 kB | 3.69 kB | ⚠️ +3 B |
| index.html gzip | 955 B | 952 B | -3 B |
| link.html | 3.74 kB | 3.74 kB | ⚠️ +3 B |
| link.html gzip | 963 B | 960 B | -3 B |
| withRouter.html | 3.75 kB | 3.75 kB | ⚠️ +3 B |
| withRouter.html gzip | 951 B | 947 B | -4 B |
| Overall change |  |  | ⚠️ +9 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
@@ -742,7 +742,10 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(function (mark) {
+    return performance.clearMarks(mark);
+  });
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
@@ -1425,7 +1428,7 @@ function preloadScript(url) {
   var link = document.createElement('link');
   link.rel = 'preload';
   link.crossOrigin = "anonymous";
-  link.href = encodeURI(url);
+  link.href = url;
   link.as = 'script';
   document.head.appendChild(link);
 }
@@ -1576,7 +1579,7 @@ function () {
       }
 
       script.crossOrigin = "anonymous";
-      script.src = encodeURI(url);
+      script.src = url;
 
       script.onerror = function () {
         var error = new Error("Error loading script " + url);
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
@@ -684,7 +684,8 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(mark => performance.clearMarks(mark));
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
@@ -1338,7 +1339,7 @@ function preloadScript(url) {
   const link = document.createElement('link');
   link.rel = 'preload';
   link.crossOrigin = "anonymous";
-  link.href = encodeURI(url);
+  link.href = url;
   link.as = 'script';
   document.head.appendChild(link);
 }
@@ -1456,7 +1457,7 @@ class PageLoader {
     }
 
     script.crossOrigin = "anonymous";
-    script.src = encodeURI(url);
+    script.src = url;
 
     script.onerror = () => {
       const error = new Error("Error loading script " + url);
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "LtRI":
  [...]

2019-08-30 22:43 UTC, housseindjirdeh commented
@timer Done 🕺

2019-08-30 22:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| buildDuration | 21.2s | 20.3s | -982ms |
| nodeModulesSize | 42 MB | 41.5 MB | -453 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ⚠️ +68 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +15 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +68 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.6 kB | ⚠️ +51 B |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ⚠️ +8 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +51 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| index.html | 3.7 kB | 3.69 kB | -4 B |
| index.html gzip | 956 B | 955 B | -1 B |
| link.html | 3.75 kB | 3.74 kB | -4 B |
| link.html gzip | 964 B | 963 B | -1 B |
| withRouter.html | 3.75 kB | 3.75 kB | -4 B |
| withRouter.html gzip | 951 B | 950 B | -1 B |
| Overall change |  |  | -12 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -742,7 +742,10 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(function (mark) {
+    return performance.clearMarks(mark);
+  });
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
@@ -1425,7 +1428,7 @@ function preloadScript(url) {
   var link = document.createElement('link');
   link.rel = 'preload';
   link.crossOrigin = "anonymous";
-  link.href = encodeURI(url);
+  link.href = url;
   link.as = 'script';
   document.head.appendChild(link);
 }
@@ -1576,7 +1579,7 @@ function () {
       }
 
       script.crossOrigin = "anonymous";
-      script.src = encodeURI(url);
+      script.src = url;
 
       script.onerror = function () {
         var error = new Error("Error loading script " + url);
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -684,7 +684,8 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(mark => performance.clearMarks(mark));
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
@@ -1338,7 +1339,7 @@ function preloadScript(url) {
   const link = document.createElement('link');
   link.rel = 'preload';
   link.crossOrigin = "anonymous";
-  link.href = encodeURI(url);
+  link.href = url;
   link.as = 'script';
   document.head.appendChild(link);
 }
@@ -1456,7 +1457,7 @@ class PageLoader {
     }
 
     script.crossOrigin = "anonymous";
-    script.src = encodeURI(url);
+    script.src = url;
 
     script.onerror = () => {
       const error = new Error("Error loading script " + url);
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/3n8fam_SA9zet8inmQcm9/pages/index.module.js"
+        <link rel="preload" href="/_next/static/l-aFOuTC4KLI5eBtFDI6R/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/3n8fam_SA9zet8inmQcm9/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/l-aFOuTC4KLI5eBtFDI6R/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-b34dfc4fd33bc7bccca0.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-b1cac6f2a3b3f3780443.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/uIQlfCtW0vzzoEGcsWqAJb+hk=.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/YwiaeZ2tSIdxRp7TrAjWr0PfVas=.72ab6ea1ebeafbd8c735.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/3n8fam_SA9zet8inmQcm9/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/l-aFOuTC4KLI5eBtFDI6R/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,40 +26,40 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"3n8fam_SA9zet8inmQcm9"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"l-aFOuTC4KLI5eBtFDI6R"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!( [...]

2019-08-31 02:19 UTC, Timer approved these changes

2019-08-31 02:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| buildDuration | 21.4s | 21.1s | -266ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +174 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +90 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +19 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +90 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.6 kB | ⚠️ +73 B |
| main-HASH.module.js gzip | 6.38 kB | 6.39 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +73 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | azukaru/next.js update-clear-marks | Change |
| - | - | - | - |
| index.html | 3.7 kB | 3.69 kB | -5 B |
| index.html gzip | 953 B | 956 B | ⚠️ +3 B |
| link.html | 3.74 kB | 3.74 kB | -5 B |
| link.html gzip | 962 B | 964 B | ⚠️ +2 B |
| withRouter.html | 3.75 kB | 3.75 kB | -5 B |
| withRouter.html gzip | 948 B | 951 B | ⚠️ +3 B |
| Overall change |  |  | -15 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -742,7 +742,10 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(function (mark) {
+    return performance.clearMarks(mark);
+  });
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -684,7 +684,8 @@ function markRenderComplete() {
 }
 
 function clearMarks() {
-  performance.clearMarks();
+  ;
+  ['beforeRender', 'afterHydrate', 'afterRender', 'routeChange'].forEach(mark => performance.clearMarks(mark));
   /*
   * TODO: uncomment the following line when we have a way to
   * expose this to user code.
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/5fQR6h4b6nOxmeJx5ZB13/pages/index.module.js"
+        <link rel="preload" href="/_next/static/XEmT_UNfwBcHU_BZdvPS5/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/5fQR6h4b6nOxmeJx5ZB13/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/XEmT_UNfwBcHU_BZdvPS5/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-b34dfc4fd33bc7bccca0.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-ea228487a429f03c22be.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/f+AJXxLU0z7V2en7bqEIb9Kk0w=.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/MPvRrA0m6eE5WMnLEFXevfwozlo=.c659a74b6088e6ac1abe.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/5fQR6h4b6nOxmeJx5ZB13/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/XEmT_UNfwBcHU_BZdvPS5/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,40 +26,40 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"5fQR6h4b6nOxmeJx5ZB13"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"XEmT_UNfwBcHU_BZdvPS5"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/5fQR6h4b6nOxmeJx5ZB13/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/XEmT_UNfwBcHU_BZdvPS5/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/5fQR6h4b6nOxmeJx5ZB13/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/XEmT_UNfwBcHU_BZdvPS5/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/5fQR6h4b6nOxmeJx5ZB13/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/XEmT_UNfwBcHU_BZdvPS5/pages/_app.js"
          [...]

2019-08-31 02:40 UTC, merged