Support for adding different Node.js compression middleware
vercel/next.js pull request #8587
Opened 2019-08-31 14:37 UTC by antoniopangallo

Currently if we want to add any other Node.js compression middleware we must disable the default compression which is performed using the middleware [compression](https://www.npmjs.com/package/compression) and create a custom server. What if we allow to change that middleware using the nextConfig in ```next.config.js```  in order to avoid to create a custom server to perform by default other compressions?

For instance:

```js
// next.config.js
const shrinkRay = require("shrink-ray-current");
module.exports = {
  compressor: {
    middleware: shrinkRay,
    args: [
      {
        filter: (req, res) =>  true
      },
      arg2,
      argN,
    ]
  }
}
```

The [shrink-ray-current](https://www.npmjs.com/package/shrink-ray-current) will enable the compression using [brotli](https://github.com/google/brotli). 

What do you think?

2019-08-31 14:44 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| buildDuration | 22s | 21.4s | -601ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +1.05 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| index.html | 3.7 kB | 3.7 kB | ⚠️ +1 B |
| index.html gzip | 955 B | 957 B | ⚠️ +2 B |
| link.html | 3.74 kB | 3.75 kB | ⚠️ +1 B |
| link.html gzip | 964 B | 965 B | ⚠️ +1 B |
| withRouter.html | 3.75 kB | 3.75 kB | ⚠️ +1 B |
| withRouter.html gzip | 950 B | 952 B | ⚠️ +2 B |
| Overall change |  |  | ⚠️ +3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/index.module.js"
+        <link rel="preload" href="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/fEH3zhPKSaqCTdQyqejcJxvtT3Q=.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/g3BQwYvnGY+M9aGcIT7saAkgt+o=.c659a74b6088e6ac1abe.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/2xKlD6DesCiQjq0bLtJC3/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/4N8qrBXB9TlKjMHQjRp8B/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"2xKlD6DesCiQjq0bLtJC3"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"4N8qrBXB9TlKjMHQjRp8B"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/2xKlD6DesCiQjq0bLtJC3/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/4N8qrBXB9TlKjMHQjRp8B/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -51,15 +51,15 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/N5icBWuru6GvP+U37T6gbOFrB8A=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/5WM69cQxZ3H43e+tDlubagbnCAU=.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/fEH3zhPKSaqCTdQyqejcJxvtT3Q=.f6f7599a2edf91d8366a.js"
+        <script src="/_next/static/chunks/g3BQwYvnGY+M9aGcIT7saAkgt+o=.f6f7599a2edf91d8 [...]

2019-08-31 14:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| buildDuration | 20.4s | 20.5s | ⚠️ +151ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +1.05 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | antoniopangallo/next.js canary | Change |
| - | - | - | - |
| index.html | 3.69 kB | 3.7 kB | ⚠️ +4 B |
| index.html gzip | 954 B | 961 B | ⚠️ +7 B |
| link.html | 3.74 kB | 3.75 kB | ⚠️ +4 B |
| link.html gzip | 964 B | 969 B | ⚠️ +5 B |
| withRouter.html | 3.75 kB | 3.75 kB | ⚠️ +4 B |
| withRouter.html gzip | 951 B | 955 B | ⚠️ +4 B |
| Overall change |  |  | ⚠️ +12 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/index.module.js"
+        <link rel="preload" href="/_next/static/0DRviILjsv3HswS01utuZ/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/0DRviILjsv3HswS01utuZ/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/rQewwiUsz0leRLK4knYU+lmhRkY=.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/IRFUNXWjrQQyfHrWv0MM0I292Y=.c659a74b6088e6ac1abe.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/1XCtFjXCroMjJR_2GO2aB/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/0DRviILjsv3HswS01utuZ/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"1XCtFjXCroMjJR_2GO2aB"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"0DRviILjsv3HswS01utuZ"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/0DRviILjsv3HswS01utuZ/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/0DRviILjsv3HswS01utuZ/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/0DRviILjsv3HswS01utuZ/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/1XCtFjXCroMjJR_2GO2aB/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/0DRviILjsv3HswS01utuZ/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -51,15 +51,15 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/jiB0HhnMvFCQPdooxDuKw+k4m8s=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/MMLMwutW0oygrkDW2BwywuHwOKE=.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/rQewwiUsz0leRLK4knYU+lmhRkY=.f6f7599a2edf91d8366a.js"
+        <script src="/_next/static/chunks/IRFUNXWjrQQyfHrWv0MM0I292Y=.f6f7599a2ed [...]

2019-09-01 15:34 UTC, Timer requested changes
I'm not sure it's worth increasing the API surface area for this. `compression` is very close to adding Brotli support.

Furthermore, you can set `compression: false` and apply your own compression middleware in a custom server.
However, it's generally suggested to handle compression in a proxy -- this default compression was meant for users who were not aware compression should be configured.

2019-09-02 08:55 UTC, antoniopangallo commented
I agree that compression should be done by a proxy as well as I totally get that if we set ```compress: false``` it is possible to create a custom server with a different compression middleware, but I also think that giving the possibility to inject another compression mode directly in the next.config.js avoiding the creation of a custom server might be useful sometimes.

2019-09-03 13:34 UTC, Timer commented
I'd rather accept a solution that integrates Brotli by default into our configuration.
For the reasons outlined above, we'll not be allowing this to be customized.

Thank you for your contribution!

2019-09-03 13:34 UTC, closed without merging