Fixes unhandled error when emitWarning is issued from Webpack and HMR tries to send it to the client
vercel/next.js pull request #8600
Opened 2019-09-02 16:11 UTC by nicolasgarfinkiel

Just a small code fix that prevents a "TypeError: Converting circular structure to JSON" unhandled promise error when emitWarning is issued from Webpack and HMR tries to send it to the client.

2019-09-02 16:19 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| buildDuration | 22.6s | 22.4s | -224ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| index.html | 3.69 kB | 3.7 kB | ⚠️ +3 B |
| index.html gzip | 958 B | 960 B | ⚠️ +2 B |
| link.html | 3.74 kB | 3.75 kB | ⚠️ +3 B |
| link.html gzip | 966 B | 968 B | ⚠️ +2 B |
| withRouter.html | 3.75 kB | 3.75 kB | ⚠️ +3 B |
| withRouter.html gzip | 953 B | 955 B | ⚠️ +2 B |
| Overall change |  |  | ⚠️ +9 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/index.module.js"
+        <link rel="preload" href="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/TCxkKmBFELLC8yxRu9lqRVxCMks=.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/+7Vy3rnETmCUuddB7fh6iiqZzmA=.c659a74b6088e6ac1abe.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/eK7auiy3SXGWvYX0ke7L4/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/kdtnJHxhpcTSfyWmK1uTc/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"eK7auiy3SXGWvYX0ke7L4"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"kdtnJHxhpcTSfyWmK1uTc"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/eK7auiy3SXGWvYX0ke7L4/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/kdtnJHxhpcTSfyWmK1uTc/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -51,15 +51,15 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/nGXa80EhNAkYwgh2sPnX9g0aBUI=.155621535702fe040780.js"
+        <script src="/_next/static/chunks/GBb8zd4pNFfSt2Tmpyt4j21FLIg=.1 [...]

2019-09-02 16:42 UTC, nicolasgarfinkiel commented
Referenced issue: #8601

2019-09-05 20:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| buildDuration | 23.9s | 24.3s | ⚠️ +489ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 1f35071d648075178007f59a9e323a7a66c86477.e2c00d0314f283e7a4a0.js | 42.9 kB | N/A | N/A |
| 1f35071d648075178007f59a9e323a7a66c86477.e2c00d0314f283e7a4a0.js gzip | 15.4 kB | N/A | N/A |
| a5d99b2d2f79d88222055b593adf32304236a7a6.1f064d5355d2b8407376.js | 21.9 kB | N/A | N/A |
| a5d99b2d2f79d88222055b593adf32304236a7a6.1f064d5355d2b8407376.js gzip | 7.81 kB | N/A | N/A |
| framework.5b4f940f1eadbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b4f940f1eadbaff70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 9a0dbd3c07a17f18b1f0e69815f1ea60f0808264.1f064d5355d2b8407376.js | N/A | 21.9 kB | N/A |
| 9a0dbd3c07a17f18b1f0e69815f1ea60f0808264.1f064d5355d2b8407376.js gzip | N/A | 7.81 kB | N/A |
| bce8711f51db03b70864b0996c7aaa8c22494e78.e2c00d0314f283e7a4a0.js | N/A | 42.9 kB | N/A |
| bce8711f51db03b70864b0996c7aaa8c22494e78.e2c00d0314f283e7a4a0.js gzip | N/A | 15.4 kB | N/A |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| 1f35071d648075178007f59a9e323a7a66c86477.36c6b20a7d953b3f28f0.module.js | 45.5 kB | N/A | N/A |
| 1f35071d648075178007f59a9e323a7a66c86477.36c6b20a7d953b3f28f0.module.js gzip | 16.5 kB | N/A | N/A |
| framework.5b4f940f1eadbaff70d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b4f940f1eadbaff70d3.module.js gzip | 39.4 kB | 39.4 kB | ✓ |
| bce8711f51db03b70864b0996c7aaa8c22494e78.36c6b20a7d953b3f28f0.module.js | N/A | 45.5 kB | N/A |
| bce8711f51db03b70864b0996c7aaa8c22494e78.36c6b20a7d953b3f28f0.module.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 961 B | 959 B | -2 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 970 B | 968 B | -2 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 957 B | 955 B | -2 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/N8Lsa_ISnNJ2gKbHz_qxN/pages/index.module.js"
+        <link rel="preload" href="/_next/static/GLW2ymPIbbpFztymY7ZAP/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/N8Lsa_ISnNJ2gKbHz_qxN/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/GLW2ymPIbbpFztymY7ZAP/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/379d2f25c8748a7aff8138b6bad037f057c51301.85e4c18b9e4b400e5496.module.js"
+        <link rel="preload" href="/_next/static/chunks/13a1a523090899b29104af912cde1da307ad486d.85e4c18b9e4b400e5496.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/N8Lsa_ISnNJ2gKbHz_qxN/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/GLW2ymPIbbpFztymY7ZAP/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"N8Lsa_ISnNJ2gKbHz_qxN"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"GLW2ymPIbbpFztymY7ZAP"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/N8Lsa_ISnNJ2gKbHz_qxN/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static [...]

2019-09-24 13:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| buildDuration | 15s | 14.6s | -402ms |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..2ca0edb75.js | 43.2 kB | 43.2 kB | ✓ |
| de003c3a9d30..db75.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c0.module.js | 45.6 kB | 45.6 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 948 B | 948 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 955 B | 955 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 943 B | 943 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| buildDuration | 15.6s | 17.1s | ⚠️ +1.4s |
| nodeModulesSize | 48.2 MB | 48.2 MB | ⚠️ +30 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..2ca0edb75.js | 43.2 kB | 43.2 kB | ✓ |
| de003c3a9d30..db75.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| main-HASH.module.js | 16.5 kB | 16.5 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..c0.module.js | 45.6 kB | 45.6 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | nicolasgarfinkiel/next.js fixes-circular-reference-error-warnings-hmr | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall c [...]

2019-09-24 14:55 UTC, Timer requested changes
This would suppress type errors when a warning is encountered. This behavior isn't correct.

I'm going to close this in favor of the issue that was opened, thanks!

2019-09-24 14:55 UTC, closed without merging

2020-04-17 17:04 UTC, Timer commented
Fix up in https://github.com/zeit/next.js/pull/11976