Add link to docs for prerender indicator and allow disabling
vercel/next.js pull request #8610
Opened 2019-09-03 14:28 UTC by ijjk

Allows disabling the indicator when not needed e.g. electron apps and links to docs explaining what the indicator is

Closes: #8603

2019-09-03 14:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 23.8s | 23.3s | -538ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +1.59 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| index.html | 3.7 kB | 3.7 kB | ✓ |
| index.html gzip | 959 B | 959 B | ✓ |
| link.html | 3.75 kB | 3.75 kB | ✓ |
| link.html gzip | 968 B | 968 B | ✓ |
| withRouter.html | 3.75 kB | 3.75 kB | ✓ |
| withRouter.html gzip | 955 B | 954 B | -1 B |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 24.5s | 24.5s | -14ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +1.59 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _error.js | 247 kB | 247 kB | ⚠️ +13 B |
| _error.js gzip | 66.3 kB | 66.3 kB | ⚠️ +13 B |
| hooks.html | 3.81 kB | 3.81 kB | ⚠️ +4 B |
| hooks.html gzip | 983 B | 982 B | -1 B |
| index.js | 248 kB | 248 kB | ⚠️ +13 B |
| index.js gzip | 66.6 kB | 66.8 kB | ⚠️ +159 B |
| link.js | 256 kB | 256 kB | ⚠️ +13 B |
| link.js gzip | 68.8 kB | 68.9 kB | ⚠️ +74 B |
| routerDirect.js | 249 kB | 249 kB | ⚠️ +13 B |
| routerDirect.js gzip | 66.8 kB | 66.8 kB | -77 B |
| withRouter.js | 249 kB | 249 kB | ⚠️ +13 B |
| withRouter.js gzip | 66.8 kB | 66.7 kB | -149 B |
| Overall change |  |  | ⚠️ +69 B |

</details>

</details>

2019-09-03 16:25 UTC, Timer requested changes
Not sure I'm a fan of the options to disable it -- I'd prefer a click-action to disable it for the _session_ only. Wdyt?

To clarify: clicking should open docs, but on hover, maybe some small text that says "Dismiss"!

2019-09-03 19:44 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 21.3s | 21.2s | -81ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +4.59 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.3 kB | ✓ |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 961 B | 962 B | ⚠️ +1 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 970 B | 970 B | ✓ |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 957 B | 957 B | ✓ |
| Overall change |  |  | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 22.5s | 22.6s | ⚠️ +75ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +4.59 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +1 B |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | ⚠️ +1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +1 B |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | ⚠️ +1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | -1 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | -1 B |
| routerDirect.js | 434 B | 433 B | -1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 805 B | 804 B | -1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 430 B | 429 B | -1 B |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Serverless bundles</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _error.js | 248 kB | 248 kB | ✓ |
| _error.js gzip | 66.3 kB | 66.5 kB | ⚠️ +118 B |
| hooks.html | 3.86 kB | 3.86 kB | ✓ |
| hooks.html gzip | 983 B | 986 B | ⚠️ +3 B |
| index.js | 248 kB | 248 kB | ✓ |
| index.js gzip | 66.8 kB | 66.7 kB | -135 B |
| link.js | 256 kB | 256 kB | ✓ |
| link.js gzip | 68.9 kB | 68.9 kB | -47 B |
| routerDirect.js | 249 kB | 249 kB | ✓ |
| routerDirect.js gzip | 66.8 kB | 66.7 kB | -65 B |
| withRouter.js | 249 kB | 249 kB | ✓ |
| withRouter.js gzip | 66.7 kB | 66.8 kB | ⚠️ +164 B |
| Overall change |  |  | ✓ |

</details>

</details>

2019-09-03 19:47 UTC, ijjk commented
I think we should allow it to be disabled in `next.config.js` so that we don't cause people to opt-out of the automatic prerendering optimization just to get rid of the indicator. 

I updated it to be disabled by default when `electron` is detected and also added a button on the indicator to allow dismissing it for the session

2019-09-03 19:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 21.1s | 20.8s | -302ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +4.78 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.3 kB | 18.2 kB | -1 B |
| main-HASH.js gzip | 6.66 kB | 6.66 kB | -1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | -1 B |
| main-HASH.module.js gzip | 6.39 kB | 6.39 kB | -1 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change |  |  | -1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 884 B | 884 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.76 kB | 4.76 kB | ⚠️ +1 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 434 B | ⚠️ +1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 840 B | 840 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.62 kB | 8.62 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 805 B | ⚠️ +1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 430 B | ⚠️ +1 B |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change |  |  | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change |  |  | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 963 B | 958 B | -5 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 971 B | 967 B | -4 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 958 B | 954 B | -4 B |
| Overall change |  |  | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,9 +6,9 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/IdftG-9d-HM_tprge79z2/pages/index.module.js"
+        <link rel="preload" href="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/IdftG-9d-HM_tprge79z2/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
@@ -16,9 +16,9 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/0f501d34f035549691b65ee9af9ecc042b1c93ec.c659a74b6088e6ac1abe.module.js"
+        <link rel="preload" href="/_next/static/chunks/3854c7224cda075fa2875ef6077e61c0ea526a2b.c659a74b6088e6ac1abe.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/IdftG-9d-HM_tprge79z2/_buildManifest.module.js"
+        <link rel="preload" href="/_next/static/Q15xdkQSPrLxPGy4563oE/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -26,18 +26,18 @@
         <div id="__next">Hello world 👋</div>
         <script id="__NEXT_DATA__" type="application/json"
         crossorigin="anonymous">
-            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"IdftG-9d-HM_tprge79z2"}
+            {"dataManager":"[]","props":{"pageProps":{}},"page":"/","query":{},"buildId":"Q15xdkQSPrLxPGy4563oE"}
         </script>
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script async="" data-next-page="/" src="/_next/static/IdftG-9d-HM_tprge79z2/pages/index.js"
+        <script async="" data-next-page="/" src="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/" src="/_next/static/IdftG-9d-HM_tprge79z2/pages/index.module.js"
+        <script async="" data-next-page="/" src="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/index.module.js"
         crossorigin="anonymous" type="module"></script>
-        <script async="" data-next-page="/_app" src="/_next/static/IdftG-9d-HM_tprge79z2/pages/_app.js"
+        <script async="" data-next-page="/_app" src="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/_app.js"
         crossorigin="anonymous" nomodule=""></script>
-        <script async="" data-next-page="/_app" src="/_next/static/IdftG-9d-HM_tprge79z2/pages/_app.module.js"
+        <script async="" data-next-page="/_app" src="/_next/static/Q15xdkQSPrLxPGy4563oE/pages/_app.module.js"
         crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
         async="" crossorigin="anonymous" nomodule=""></script>
@@ -51,15 +51,15 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/chunks/63414e9783cf0d6577f7599a538ab3da839ced53.155621535702fe040780.js"
+        <script src="/_next/static/chunks/58a41f921657eda921ff13fec7c8165738f28eb6.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
- [...]

2019-09-05 16:04 UTC, alieslamifard commented
It's really cool feature, guys. I'm waiting for it. is it shows just for a second?

2019-09-06 11:17 UTC, timneutkens commented
I think in this case we should allow disabling the indicator as talked about with @rauchg. It's less than ideal though.

2019-09-06 15:31 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| buildDuration | 21.7s | 21.8s | ⚠️ +153ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +4.78 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.2 kB | -1 B |
| main-HASH.js gzip | 6.64 kB | 6.64 kB | -1 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 96d605fcc5adc223cf9e484d60493d0e39dcc27c.1f064d5355d2b8407376.js | 21.9 kB | N/A | N/A |
| 96d605fcc5adc223cf9e484d60493d0e39dcc27c.1f064d5355d2b8407376.js gzip | 7.81 kB | N/A | N/A |
| e4de2736601d067666db67283c4af6d3c6d01957.e2c00d0314f283e7a4a0.js | 42.9 kB | N/A | N/A |
| e4de2736601d067666db67283c4af6d3c6d01957.e2c00d0314f283e7a4a0.js gzip | 15.4 kB | N/A | N/A |
| framework.5b4f940f1eadbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b4f940f1eadbaff70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 03791a46c5aaa3b9dc4fb531e1deb37149b1cecc.e2c00d0314f283e7a4a0.js | N/A | 42.9 kB | N/A |
| 03791a46c5aaa3b9dc4fb531e1deb37149b1cecc.e2c00d0314f283e7a4a0.js gzip | N/A | 15.4 kB | N/A |
| 4be78e447e78bb63043499b71d3da21f50564e57.1f064d5355d2b8407376.js | N/A | 21.9 kB | N/A |
| 4be78e447e78bb63043499b71d3da21f50564e57.1f064d5355d2b8407376.js gzip | N/A | 7.81 kB | N/A |
| Overall change | 210 kB | 210 kB | -1 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | -1 B |
| main-HASH.module.js gzip | 6.38 kB | 6.38 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| e4de2736601d067666db67283c4af6d3c6d01957.36c6b20a7d953b3f28f0.module.js | 45.5 kB | N/A | N/A |
| e4de2736601d067666db67283c4af6d3c6d01957.36c6b20a7d953b3f28f0.module.js gzip | 16.5 kB | N/A | N/A |
| framework.5b4f940f1eadbaff70d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b4f940f1eadbaff70d3.module.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 03791a46c5aaa3b9dc4fb531e1deb37149b1cecc.36c6b20a7d953b3f28f0.module.js | N/A | 45.5 kB | N/A |
| 03791a46c5aaa3b9dc4fb531e1deb37149b1cecc.36c6b20a7d953b3f28f0.module.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 189 kB | 189 kB | -1 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 434 B | ⚠️ +1 B |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 840 B | -1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 805 B | ⚠️ +1 B |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 430 B | ⚠️ +1 B |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ⚠️ +1 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js link-prerender-indicator | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 956 B | 962 B | ⚠️ +6 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 965 B | 971 B | ⚠️ +6 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 952 B | 958 B | ⚠️ +6 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[3],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "B5Ud":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[5],{
 
 /***/ "+iuc":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>hooks.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[6],{
 
 /***/ "+MDD":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>index.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[7],{
 
 /***/ "RNiq":
 /***/ (function(module, __webpack_exports__, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[8],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>routerDirect.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[10],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[9],{
 
 /***/ "LtRI":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>withRouter.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"]  [...]

2019-09-15 21:18 UTC, timneutkens approved these changes

2019-09-15 21:18 UTC, merged