Fix yarn workspaces example
vercel/next.js pull request #8631
Opened 2019-09-05 07:59 UTC by huv1k

Fixes #8615

2019-09-05 08:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| buildDuration | 21.2s | 20.6s | -589ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +27.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +33 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +22 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change | 19.7 kB | 19.8 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +33 B |
| main-HASH.module.js gzip | 6.38 kB | 6.39 kB | ⚠️ +2 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 884 B | ⚠️ +1 B |
| _error.js | 12.1 kB | 12.1 kB | ⚠️ +44 B |
| _error.js gzip | 4.74 kB | 4.76 kB | ⚠️ +16 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 840 B | -1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ⚠️ +44 B |
| _error.module.js gzip | 8.6 kB | 8.62 kB | ⚠️ +22 B |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.68 kB | ⚠️ +3 B |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.3 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 962 B | 961 B | -1 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 971 B | 969 B | -2 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 957 B | 957 B | ✓ |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[11],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
@@ -9,62 +9,6 @@ __webpack_require__("cHUd")('Map');
 
 /***/ }),
 
-/***/ "0IRE":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-
-var _Map = __webpack_require__("LX0d");
-
-var _classCallCheck = __webpack_require__("/HRN");
-
-var _createClass = __webpack_require__("WaGi");
-
-var _Object$defineProperty = __webpack_require__("hfKm");
-
-_Object$defineProperty(exports, "__esModule", {
-  value: true
-});
-
-var DataManager =
-/*#__PURE__*/
-function () {
-  function DataManager(data) {
-    _classCallCheck(this, DataManager);
-
-    this.data = new _Map(data);
-  }
-
-  _createClass(DataManager, [{
-    key: "getData",
-    value: function getData() {
-      return this.data;
-    }
-  }, {
-    key: "get",
-    value: function get(key) {
-      return this.data.get(key);
-    }
-  }, {
-    key: "set",
-    value: function set(key, value) {
-      this.data.set(key, value);
-    }
-  }, {
-    key: "overwrite",
-    value: function overwrite(data) {
-      this.data = new _Map(data);
-    }
-  }]);
-
-  return DataManager;
-}();
-
-exports.DataManager = DataManager;
-
-/***/ }),
-
 /***/ "8iia":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -264,7 +208,33 @@ function reactElementToDOM(_ref) {
 
 /***/ }),
 
-/***/ "FYa8":
+/***/ "HohS":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+
+var _Object$defineProperty = __webpack_require__("hfKm");
+
+_Object$defineProperty(exports, "__esModule", {
+  value: true
+});
+
+var runtimeConfig;
+
+exports["default"] = function () {
+  return runtimeConfig;
+};
+
+function setConfig(configValue) {
+  runtimeConfig = configValue;
+}
+
+exports.setConfig = setConfig;
+
+/***/ }),
+
+/***/ "IClC":
 /***/ (function(module, exports, __webpack_require__) {
 
 "use strict";
@@ -335,25 +305,25 @@ var _headManager = _interopRequireDefault(__webpack_require__("DqTX"));
 
 var _router = __webpack_require__("nOHt");
 
-var _mitt = _interopRequireDefault(__webpack_require__("dZ6Y"));
+var _mitt = _interopRequireDefault(__webpack_require__("kiME"));
 
-var _utils = __webpack_require__("g/15");
+var _utils = __webpack_require__("Bu4q");
 
 var _pageLoader = _interopRequireDefault(__webpack_require__("zmvN"));
 
-var envConfig = _interopRequireWildcard(__webpack_require__("yLiY"));
+var envConfig = _interopRequireWildcard(__webpack_require__("PBx+"));
 
-var _headManagerContext = __webpack_require__("FYa8");
+var _headManagerContext = __webpack_require__("IClC");
 
-var _dataManagerContext = __webpack_require__("qArv");
+var _dataManagerContext = __webpack_require__("qS9g");
 
-var _routerContext = __webpack_require__("qOIg");
+var _routerContext = __webpack_require__("9EOK");
 
-var _dataManager = __webpack_require__("0IRE");
+var _dataManager = __webpack_require__("cuFY");
 
 var _querystring = __webpack_require__("s4NR");
 
-var _isDynamic = __webpack_require__("/jkW");
+var _isDynamic = __webpack_require__("kcOw");
 /* global location */
 // Polyfill Promise globally
 // This is needed because Webpack's dynamic loading(common chunks) code
@@ -368,7 +338,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.6-canary.0";
+var version = "9.0.5";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -900,6 +870,14 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
+/***/ "PBx+":
+/***/ (function(module, exports, __webpack_require__) {
+
+module.exports = __webpack_require__("HohS")
+
+
+/***/ }),
+
 /***/ "RRc/":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -1199,6 +1177,62 @@ module.exports = function (COLLECTION) {
 
 /***/ }),
 
+/***/ "cuFY":
+/***/ (function(module,  [...]

2019-09-05 08:19 UTC, timneutkens approved these changes

2019-09-05 08:21 UTC, timneutkens approved these changes

2019-09-05 08:26 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| buildDuration | 19.7s | 19.5s | -139ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +27.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +33 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +22 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change | 19.7 kB | 19.8 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +33 B |
| main-HASH.module.js gzip | 6.38 kB | 6.39 kB | ⚠️ +2 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 884 B | ⚠️ +1 B |
| _error.js | 12.1 kB | 12.1 kB | ⚠️ +44 B |
| _error.js gzip | 4.74 kB | 4.76 kB | ⚠️ +16 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 840 B | -1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ⚠️ +44 B |
| _error.module.js gzip | 8.6 kB | 8.62 kB | ⚠️ +22 B |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.68 kB | ⚠️ +3 B |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.3 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 960 B | 963 B | ⚠️ +3 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 968 B | 971 B | ⚠️ +3 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 956 B | 959 B | ⚠️ +3 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -9,62 +9,6 @@ __webpack_require__("cHUd")('Map');
 
 /***/ }),
 
-/***/ "0IRE":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-
-var _Map = __webpack_require__("LX0d");
-
-var _classCallCheck = __webpack_require__("/HRN");
-
-var _createClass = __webpack_require__("WaGi");
-
-var _Object$defineProperty = __webpack_require__("hfKm");
-
-_Object$defineProperty(exports, "__esModule", {
-  value: true
-});
-
-var DataManager =
-/*#__PURE__*/
-function () {
-  function DataManager(data) {
-    _classCallCheck(this, DataManager);
-
-    this.data = new _Map(data);
-  }
-
-  _createClass(DataManager, [{
-    key: "getData",
-    value: function getData() {
-      return this.data;
-    }
-  }, {
-    key: "get",
-    value: function get(key) {
-      return this.data.get(key);
-    }
-  }, {
-    key: "set",
-    value: function set(key, value) {
-      this.data.set(key, value);
-    }
-  }, {
-    key: "overwrite",
-    value: function overwrite(data) {
-      this.data = new _Map(data);
-    }
-  }]);
-
-  return DataManager;
-}();
-
-exports.DataManager = DataManager;
-
-/***/ }),
-
 /***/ "8iia":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -264,7 +208,33 @@ function reactElementToDOM(_ref) {
 
 /***/ }),
 
-/***/ "FYa8":
+/***/ "HohS":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+
+var _Object$defineProperty = __webpack_require__("hfKm");
+
+_Object$defineProperty(exports, "__esModule", {
+  value: true
+});
+
+var runtimeConfig;
+
+exports["default"] = function () {
+  return runtimeConfig;
+};
+
+function setConfig(configValue) {
+  runtimeConfig = configValue;
+}
+
+exports.setConfig = setConfig;
+
+/***/ }),
+
+/***/ "IClC":
 /***/ (function(module, exports, __webpack_require__) {
 
 "use strict";
@@ -335,25 +305,25 @@ var _headManager = _interopRequireDefault(__webpack_require__("DqTX"));
 
 var _router = __webpack_require__("nOHt");
 
-var _mitt = _interopRequireDefault(__webpack_require__("dZ6Y"));
+var _mitt = _interopRequireDefault(__webpack_require__("kiME"));
 
-var _utils = __webpack_require__("g/15");
+var _utils = __webpack_require__("Bu4q");
 
 var _pageLoader = _interopRequireDefault(__webpack_require__("zmvN"));
 
-var envConfig = _interopRequireWildcard(__webpack_require__("yLiY"));
+var envConfig = _interopRequireWildcard(__webpack_require__("PBx+"));
 
-var _headManagerContext = __webpack_require__("FYa8");
+var _headManagerContext = __webpack_require__("IClC");
 
-var _dataManagerContext = __webpack_require__("qArv");
+var _dataManagerContext = __webpack_require__("qS9g");
 
-var _routerContext = __webpack_require__("qOIg");
+var _routerContext = __webpack_require__("9EOK");
 
-var _dataManager = __webpack_require__("0IRE");
+var _dataManager = __webpack_require__("cuFY");
 
 var _querystring = __webpack_require__("s4NR");
 
-var _isDynamic = __webpack_require__("/jkW");
+var _isDynamic = __webpack_require__("kcOw");
 /* global location */
 // Polyfill Promise globally
 // This is needed because Webpack's dynamic loading(common chunks) code
@@ -368,7 +338,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.6-canary.0";
+var version = "9.0.5";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -900,6 +870,14 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
+/***/ "PBx+":
+/***/ (function(module, exports, __webpack_require__) {
+
+module.exports = __webpack_require__("HohS")
+
+
+/***/ }),
+
 /***/ "RRc/":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -1199,6 +1177,62 @@ module.exports = function (COLLECTION) {
 
 /***/ }),
 
+/***/ "cuFY":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+
+var _Map = __webpack_require__("LX0d");
+
+var _classCallCheck = __webpack_require__("/HRN");
+
+var _createClass = __webpack_require__("WaGi");
+
+var _Object$def [...]

2019-09-05 14:10 UTC, Timer requested changes

2019-09-05 14:10 UTC, Timer commented on examples/with-yarn-workspaces/now.json
> +}
Please add a trailing line here.

2019-09-05 14:10 UTC, Timer commented on examples/with-yarn-workspaces/now.json
> +    { "src": "/(.*)", "dest": "packages/web-app/$1" }
This route isn't correct -- the application will be broken. 😄 
```suggestion
    { "src": "(.*)", "dest": "packages/web-app$1", "continue": true }
```

2019-09-05 21:18 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| buildDuration | 22.3s | 21.5s | -791ms |
| nodeModulesSize | 42 MB | 42 MB | ⚠️ +27.9 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +33 B |
| main-HASH.js gzip | 6.64 kB | 6.66 kB | ⚠️ +22 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| Overall change | 19.7 kB | 19.8 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +33 B |
| main-HASH.module.js gzip | 6.38 kB | 6.39 kB | ⚠️ +2 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.module.js gzip | 746 B | 746 B | ✓ |
| Overall change | 18.1 kB | 18.1 kB | ⚠️ +33 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 884 B | ⚠️ +1 B |
| _error.js | 12.1 kB | 12.1 kB | ⚠️ +44 B |
| _error.js gzip | 4.74 kB | 4.76 kB | ⚠️ +16 B |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ⚠️ +1 B |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 840 B | -1 B |
| _error.module.js | 23.3 kB | 23.3 kB | ⚠️ +44 B |
| _error.module.js gzip | 8.6 kB | 8.62 kB | ⚠️ +22 B |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.68 kB | ⚠️ +3 B |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect.module.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.module.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.3 kB | ⚠️ +44 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManifest.module.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | huv1k/next.js yarn-workspaces-now | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 957 B | 964 B | ⚠️ +7 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 967 B | 972 B | ⚠️ +5 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 954 B | 960 B | ⚠️ +6 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -9,62 +9,6 @@ __webpack_require__("cHUd")('Map');
 
 /***/ }),
 
-/***/ "0IRE":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-
-var _Map = __webpack_require__("LX0d");
-
-var _classCallCheck = __webpack_require__("/HRN");
-
-var _createClass = __webpack_require__("WaGi");
-
-var _Object$defineProperty = __webpack_require__("hfKm");
-
-_Object$defineProperty(exports, "__esModule", {
-  value: true
-});
-
-var DataManager =
-/*#__PURE__*/
-function () {
-  function DataManager(data) {
-    _classCallCheck(this, DataManager);
-
-    this.data = new _Map(data);
-  }
-
-  _createClass(DataManager, [{
-    key: "getData",
-    value: function getData() {
-      return this.data;
-    }
-  }, {
-    key: "get",
-    value: function get(key) {
-      return this.data.get(key);
-    }
-  }, {
-    key: "set",
-    value: function set(key, value) {
-      this.data.set(key, value);
-    }
-  }, {
-    key: "overwrite",
-    value: function overwrite(data) {
-      this.data = new _Map(data);
-    }
-  }]);
-
-  return DataManager;
-}();
-
-exports.DataManager = DataManager;
-
-/***/ }),
-
 /***/ "8iia":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -264,7 +208,33 @@ function reactElementToDOM(_ref) {
 
 /***/ }),
 
-/***/ "FYa8":
+/***/ "HohS":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+
+var _Object$defineProperty = __webpack_require__("hfKm");
+
+_Object$defineProperty(exports, "__esModule", {
+  value: true
+});
+
+var runtimeConfig;
+
+exports["default"] = function () {
+  return runtimeConfig;
+};
+
+function setConfig(configValue) {
+  runtimeConfig = configValue;
+}
+
+exports.setConfig = setConfig;
+
+/***/ }),
+
+/***/ "IClC":
 /***/ (function(module, exports, __webpack_require__) {
 
 "use strict";
@@ -335,25 +305,25 @@ var _headManager = _interopRequireDefault(__webpack_require__("DqTX"));
 
 var _router = __webpack_require__("nOHt");
 
-var _mitt = _interopRequireDefault(__webpack_require__("dZ6Y"));
+var _mitt = _interopRequireDefault(__webpack_require__("kiME"));
 
-var _utils = __webpack_require__("g/15");
+var _utils = __webpack_require__("Bu4q");
 
 var _pageLoader = _interopRequireDefault(__webpack_require__("zmvN"));
 
-var envConfig = _interopRequireWildcard(__webpack_require__("yLiY"));
+var envConfig = _interopRequireWildcard(__webpack_require__("PBx+"));
 
-var _headManagerContext = __webpack_require__("FYa8");
+var _headManagerContext = __webpack_require__("IClC");
 
-var _dataManagerContext = __webpack_require__("qArv");
+var _dataManagerContext = __webpack_require__("qS9g");
 
-var _routerContext = __webpack_require__("qOIg");
+var _routerContext = __webpack_require__("9EOK");
 
-var _dataManager = __webpack_require__("0IRE");
+var _dataManager = __webpack_require__("cuFY");
 
 var _querystring = __webpack_require__("s4NR");
 
-var _isDynamic = __webpack_require__("/jkW");
+var _isDynamic = __webpack_require__("kcOw");
 /* global location */
 // Polyfill Promise globally
 // This is needed because Webpack's dynamic loading(common chunks) code
@@ -368,7 +338,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.6-canary.1";
+var version = "9.0.5";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -900,6 +870,14 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
+/***/ "PBx+":
+/***/ (function(module, exports, __webpack_require__) {
+
+module.exports = __webpack_require__("HohS")
+
+
+/***/ }),
+
 /***/ "RRc/":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -1199,6 +1177,62 @@ module.exports = function (COLLECTION) {
 
 /***/ }),
 
+/***/ "cuFY":
+/***/ (function(module, exports, __webpack_require__) {
+
+"use strict";
+
+
+var _Map = __webpack_require__("LX0d");
+
+var _classCallCheck = __webpack_require__("/HRN");
+
+var _createClass = __webpack_require__("WaGi");
+
+var _Object$def [...]

2019-09-06 11:44 UTC, timneutkens approved these changes

2019-09-06 11:44 UTC, merged