Delay updating asPath for auto exported pages
vercel/next.js pull request #8681
Opened 2019-09-09 18:40 UTC by ijjk

Since we parse the `asPath` from the URL and this value will differ during auto-prerender we need to wait before updating this value similar to the query values to prevent a hydration mismatch

2019-09-09 18:48 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| buildDuration | 26.8s | 25.3s | -1.5s |
| nodeModulesSize | 42.4 MB | 42.4 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +46 B |
| main-HASH.js gzip | 6.64 kB | 6.65 kB | ⚠️ +11 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 99e1ba2204bd..2b8407376.js | 21.9 kB | N/A | N/A |
| 99e1ba2204bd..7376.js gzip | 7.81 kB | N/A | N/A |
| a1bcf5a6f5d1..799a4e38e.js | 43.1 kB | N/A | N/A |
| a1bcf5a6f5d1..e38e.js gzip | 15.4 kB | N/A | N/A |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 63a06b64910c..2b8407376.js | N/A | 21.9 kB | N/A |
| 63a06b64910c..7376.js gzip | N/A | 7.81 kB | N/A |
| b55ea4681f38..799a4e38e.js | N/A | 43.1 kB | N/A |
| b55ea4681f38..e38e.js gzip | N/A | 15.4 kB | N/A |
| Overall change | 210 kB | 210 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +50 B |
| main-HASH.module.js gzip | 6.38 kB | 6.4 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| a1bcf5a6f5d1..f0.module.js | 45.5 kB | N/A | N/A |
| a1bcf5a6f5d1..dule.js gzip | 16.5 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| b55ea4681f38..f0.module.js | N/A | 45.5 kB | N/A |
| b55ea4681f38..dule.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 189 kB | 189 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 957 B | 958 B | ⚠️ +1 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 966 B | 968 B | ⚠️ +2 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 953 B | 955 B | ⚠️ +2 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, initialAsPath, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -547,7 +547,10 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
-            exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+            // if auto prerendered and dynamic route wait to update asPath
+            // until after mount to prevent hydration mismatch
+            initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+            exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
               initialProps: props,
               pageLoader: pageLoader,
               App: App,
@@ -577,7 +580,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -545,9 +545,12 @@ function () {
 
     if (window.__NEXT_PRELOADREADY) {
       yield window.__NEXT_PRELOADREADY(dynamicIds);
-    }
+    } // if auto prerendered and dynamic route wait to update asPath
+    // until after mount to prevent hydration mismatch
+
 
-    exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+    const initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+    exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
       initialProps: props,
       pageLoader,
       App,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -6,19 +6,19 @@
         <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
         />
         <meta name="next-head-count" content="2" />
-        <link rel="preload" href="/_next/static/lez2IWM77PzYAvX_M60t8/pages/index.module.js"
+        <link rel="preload" href="/_next/static/T5iH9-Najjsc6kk9l58jn/pages/index.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/lez2IWM77PzYAvX_M60t8/pages/_app.module.js"
+        <link rel="preload" href="/_next/static/T5iH9-Najjsc6kk9l58jn/pages/_app.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link  [...]

2019-09-10 16:33 UTC, Timer requested changes
Can we add a test that ensures the value is swapped out? We might already cover it somewhere else, but I don't think it hurts.

2019-09-10 16:44 UTC, ijjk commented
Added 👍

2019-09-10 16:51 UTC, Timer approved these changes

2019-09-10 16:51 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| buildDuration | 23.5s | 23.5s | -44ms |
| nodeModulesSize | 42.4 MB | 42.4 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +46 B |
| main-HASH.js gzip | 6.64 kB | 6.65 kB | ⚠️ +11 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +50 B |
| main-HASH.module.js gzip | 6.38 kB | 6.4 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 955 B | 956 B | ⚠️ +1 B |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 942 B | 943 B | ⚠️ +1 B |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, initialAsPath, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -547,7 +547,10 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
-            exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+            // if auto prerendered and dynamic route wait to update asPath
+            // until after mount to prevent hydration mismatch
+            initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+            exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
               initialProps: props,
               pageLoader: pageLoader,
               App: App,
@@ -577,7 +580,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -545,9 +545,12 @@ function () {
 
     if (window.__NEXT_PRELOADREADY) {
       yield window.__NEXT_PRELOADREADY(dynamicIds);
-    }
+    } // if auto prerendered and dynamic route wait to update asPath
+    // until after mount to prevent hydration mismatch
+
 
-    exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+    const initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+    exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
       initialProps: props,
       pageLoader,
       App,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -43,9 +43,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
+        <script src="/_next/static/runtime/main-55b45fe5fab1b051a823.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <script src="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@ [...]

2019-09-10 17:08 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| buildDuration | 23.8s | 23.5s | -297ms |
| nodeModulesSize | 42.4 MB | 42.4 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +46 B |
| main-HASH.js gzip | 6.64 kB | 6.65 kB | ⚠️ +11 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +50 B |
| main-HASH.module.js gzip | 6.38 kB | 6.4 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 955 B | 956 B | ⚠️ +1 B |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 942 B | 943 B | ⚠️ +1 B |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, initialAsPath, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -547,7 +547,10 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
-            exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+            // if auto prerendered and dynamic route wait to update asPath
+            // until after mount to prevent hydration mismatch
+            initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+            exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
               initialProps: props,
               pageLoader: pageLoader,
               App: App,
@@ -577,7 +580,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -545,9 +545,12 @@ function () {
 
     if (window.__NEXT_PRELOADREADY) {
       yield window.__NEXT_PRELOADREADY(dynamicIds);
-    }
+    } // if auto prerendered and dynamic route wait to update asPath
+    // until after mount to prevent hydration mismatch
+
 
-    exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+    const initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+    exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
       initialProps: props,
       pageLoader,
       App,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -43,9 +43,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
+        <script src="/_next/static/runtime/main-55b45fe5fab1b051a823.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <script src="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
 [...]

2019-09-10 17:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| buildDuration | 24s | 24.2s | ⚠️ +265ms |
| nodeModulesSize | 42.4 MB | 42.4 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +46 B |
| main-HASH.js gzip | 6.64 kB | 6.65 kB | ⚠️ +11 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +50 B |
| main-HASH.module.js gzip | 6.38 kB | 6.4 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 955 B | 956 B | ⚠️ +1 B |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 942 B | 943 B | ⚠️ +1 B |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, initialAsPath, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -547,7 +547,10 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
-            exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+            // if auto prerendered and dynamic route wait to update asPath
+            // until after mount to prevent hydration mismatch
+            initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+            exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
               initialProps: props,
               pageLoader: pageLoader,
               App: App,
@@ -577,7 +580,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -545,9 +545,12 @@ function () {
 
     if (window.__NEXT_PRELOADREADY) {
       yield window.__NEXT_PRELOADREADY(dynamicIds);
-    }
+    } // if auto prerendered and dynamic route wait to update asPath
+    // until after mount to prevent hydration mismatch
+
 
-    exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+    const initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+    exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
       initialProps: props,
       pageLoader,
       App,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -43,9 +43,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
+        <script src="/_next/static/runtime/main-55b45fe5fab1b051a823.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <script src="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff [...]

2019-09-10 17:30 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| buildDuration | 23.8s | 24.1s | ⚠️ +309ms |
| nodeModulesSize | 42.4 MB | 42.4 MB | ⚠️ +412 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.js | 18.2 kB | 18.3 kB | ⚠️ +46 B |
| main-HASH.js gzip | 6.64 kB | 6.65 kB | ⚠️ +11 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..799a4e38e.js | 43.1 kB | 43.1 kB | ✓ |
| de003c3a9d30..e38e.js gzip | 15.4 kB | 15.4 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 210 kB | 210 kB | ⚠️ +46 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| main-HASH.module.js | 16.6 kB | 16.6 kB | ⚠️ +50 B |
| main-HASH.module.js gzip | 6.38 kB | 6.4 kB | ⚠️ +12 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..f0.module.js | 45.5 kB | 45.5 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 189 kB | 189 kB | ⚠️ +50 B |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.js | 1.83 kB | 1.83 kB | ✓ |
| _app.js gzip | 883 B | 883 B | ✓ |
| _error.js | 12.1 kB | 12.1 kB | ✓ |
| _error.js gzip | 4.74 kB | 4.74 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.81 kB | 4.81 kB | ✓ |
| index.js | 343 B | 343 B | ✓ |
| index.js gzip | 237 B | 237 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.49 kB | 3.49 kB | ✓ |
| routerDirect.js | 433 B | 433 B | ✓ |
| routerDirect.js gzip | 296 B | 296 B | ✓ |
| withRouter.js | 444 B | 444 B | ✓ |
| withRouter.js gzip | 294 B | 294 B | ✓ |
| Overall change | 36 kB | 36 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _app.module.js | 1.73 kB | 1.73 kB | ✓ |
| _app.module.js gzip | 841 B | 841 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.6 kB | 8.6 kB | ✓ |
| hooks.module.js | 1.55 kB | 1.55 kB | ✓ |
| hooks.module.js gzip | 804 B | 804 B | ✓ |
| index.module.js | 319 B | 319 B | ✓ |
| index.module.js gzip | 238 B | 238 B | ✓ |
| link.module.js | 8.52 kB | 8.52 kB | ✓ |
| link.module.js gzip | 3.67 kB | 3.67 kB | ✓ |
| routerDirect.module.js | 419 B | 419 B | ✓ |
| routerDirect..dule.js gzip | 294 B | 294 B | ✓ |
| withRouter.module.js | 429 B | 429 B | ✓ |
| withRouter.m..dule.js gzip | 293 B | 293 B | ✓ |
| Overall change | 36.2 kB | 36.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | ijjk/next.js fix/aspath-mismatch | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 947 B | 947 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 955 B | 956 B | ⚠️ +1 B |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 942 B | 943 B | ⚠️ +1 B |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, initialAsPath, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -547,7 +547,10 @@ function () {
             return window.__NEXT_PRELOADREADY(dynamicIds);
 
           case 22:
-            exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+            // if auto prerendered and dynamic route wait to update asPath
+            // until after mount to prevent hydration mismatch
+            initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+            exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
               initialProps: props,
               pageLoader: pageLoader,
               App: App,
@@ -577,7 +580,7 @@ function () {
             render(renderCtx);
             return _context.abrupt("return", emitter);
 
-          case 26:
+          case 27:
           case "end":
             return _context.stop();
         }
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -545,9 +545,12 @@ function () {
 
     if (window.__NEXT_PRELOADREADY) {
       yield window.__NEXT_PRELOADREADY(dynamicIds);
-    }
+    } // if auto prerendered and dynamic route wait to update asPath
+    // until after mount to prevent hydration mismatch
+
 
-    exports.router = router = (0, _router.createRouter)(page, query, asPath, {
+    const initialAsPath = (0, _isDynamic.isDynamicRoute)(page) && data.nextExport ? page : asPath;
+    exports.router = router = (0, _router.createRouter)(page, query, initialAsPath, {
       initialProps: props,
       pageLoader,
       App,
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,7 +12,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <link rel="preload" href="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
@@ -43,9 +43,9 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/runtime/main-26e9253859bbcb659328.js"
+        <script src="/_next/static/runtime/main-55b45fe5fab1b051a823.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/runtime/main-e3367c6cc0a826287f74.module.js"
+        <script src="/_next/static/runtime/main-0d26b819b58d326b70e7.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/framework.cdb73e402d876d4ac87f.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```di [...]

2019-09-10 17:30 UTC, merged