Fix #8634
vercel/next.js pull request #8978
Opened 2019-10-07 07:11 UTC by pavelzubov

Set history options if window.history.state is defined

2019-10-07 07:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| buildDuration | 15.3s | 13.7s | -1.6s |
| nodeModulesSize | 48.3 MB | 41.8 MB | -6.53 MB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.2 kB | -685 B |
| main-HASH.js gzip | 6.79 kB | 6.64 kB | -144 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 253b41ed762a..2b8407376.js | 21.9 kB | N/A | N/A |
| 253b41ed762a..7376.js gzip | 7.81 kB | N/A | N/A |
| be994614a9f0..6604acae7.js | 43.2 kB | N/A | N/A |
| be994614a9f0..cae7.js gzip | 15.5 kB | N/A | N/A |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 5f526ad5765b..ab6ad1311.js | N/A | 43.1 kB | N/A |
| 5f526ad5765b..1311.js gzip | N/A | 15.4 kB | N/A |
| b907a87c3a75..2b8407376.js | N/A | 21.9 kB | N/A |
| b907a87c3a75..7376.js gzip | N/A | 7.81 kB | N/A |
| Overall change | 211 kB | 210 kB | -685 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 16.6 kB | -616 B |
| main-HASH.module.js gzip | 6.52 kB | 6.38 kB | -134 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| be994614a9f0..42.module.js | 45.6 kB | N/A | N/A |
| be994614a9f0..dule.js gzip | 16.5 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 5f526ad5765b..be.module.js | N/A | 45.5 kB | N/A |
| 5f526ad5765b..dule.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 190 kB | 189 kB | -616 B |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.83 kB | ⚠️ +25 B |
| _app.js gzip | 873 B | 883 B | ⚠️ +10 B |
| _error.js | 12 kB | 12.1 kB | ⚠️ +25 B |
| _error.js gzip | 4.73 kB | 4.74 kB | ⚠️ +11 B |
| hooks.js | 12.7 kB | 12.7 kB | ⚠️ +25 B |
| hooks.js gzip | 4.79 kB | 4.81 kB | ⚠️ +16 B |
| index.js | 318 B | 343 B | ⚠️ +25 B |
| index.js gzip | 222 B | 237 B | ⚠️ +15 B |
| link.js | 8.14 kB | 8.14 kB | -5 B |
| link.js gzip | 3.5 kB | 3.49 kB | -7 B |
| routerDirect.js | 409 B | 433 B | ⚠️ +24 B |
| routerDirect.js gzip | 281 B | 296 B | ⚠️ +15 B |
| withRouter.js | 419 B | 444 B | ⚠️ +25 B |
| withRouter.js gzip | 280 B | 294 B | ⚠️ +14 B |
| Overall change | 35.8 kB | 36 kB | ⚠️ +144 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.73 kB | ⚠️ +25 B |
| _app.module.js gzip | 832 B | 841 B | ⚠️ +9 B |
| _error.module.js | 23.3 kB | 23.3 kB | ⚠️ +25 B |
| _error.module.js gzip | 8.59 kB | 8.6 kB | ⚠️ +10 B |
| hooks.module.js | 1.52 kB | 1.55 kB | ⚠️ +25 B |
| hooks.module.js gzip | 794 B | 804 B | ⚠️ +10 B |
| index.module.js | 294 B | 319 B | ⚠️ +25 B |
| index.module.js gzip | 223 B | 238 B | ⚠️ +15 B |
| link.module.js | 8.53 kB | 8.52 kB | -5 B |
| link.module.js gzip | 3.68 kB | 3.67 kB | -8 B |
| routerDirect.module.js | 394 B | 419 B | ⚠️ +25 B |
| routerDirect..dule.js gzip | 280 B | 294 B | ⚠️ +14 B |
| withRouter.module.js | 405 B | 429 B | ⚠️ +24 B |
| withRouter.m..dule.js gzip | 278 B | 293 B | ⚠️ +15 B |
| Overall change | 36.1 kB | 36.2 kB | ⚠️ +144 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| index.html | 3.75 kB | 3.75 kB | ✓ |
| index.html gzip | 960 B | 958 B | -2 B |
| link.html | 3.79 kB | 3.79 kB | ✓ |
| link.html gzip | 968 B | 966 B | -2 B |
| withRouter.html | 3.8 kB | 3.8 kB | ✓ |
| withRouter.html gzip | 956 B | 953 B | -3 B |
| Overall change | 11.3 kB | 11.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -327,7 +327,7 @@ var _extends2 = _interopRequireDefault(__webpack_require__("htGi"));
 
 var _promise = _interopRequireDefault(__webpack_require__("eVuF"));
 
-var _react = _interopRequireDefault(__webpack_require__("q1tI"));
+var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
 
 var _reactDom = _interopRequireDefault(__webpack_require__("i8i4"));
 
@@ -368,7 +368,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.0.9-canary.0";
+var version = "9.0.6-canary.1";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -417,7 +417,7 @@ exports.router = router;
 var ErrorComponent;
 exports.ErrorComponent = ErrorComponent;
 var Component;
-var App, onPerfEntry;
+var App;
 
 var Container =
 /*#__PURE__*/
@@ -490,7 +490,7 @@ function () {
   var _ref2 = (0, _asyncToGenerator2["default"])(
   /*#__PURE__*/
   _regeneratorRuntime.mark(function _callee(_temp) {
-    var _ref, passedWebpackHMR, _ref3, app, mod, initialErr, _require, isValidElementType, renderCtx;
+    var _ref, passedWebpackHMR, initialErr, _require, isValidElementType, renderCtx;
 
     return _regeneratorRuntime.wrap(function _callee$(_context) {
       while (1) {
@@ -501,69 +501,52 @@ function () {
             if (false) {}
 
             _context.next = 4;
-            return pageLoader.loadPageScript('/_app');
+            return pageLoader.loadPage('/_app');
 
           case 4:
-            _ref3 = _context.sent;
-            app = _ref3.page;
-            mod = _ref3.mod;
-            App = app;
-
-            if (mod && mod.unstable_onPerformanceData) {
-              onPerfEntry = function onPerfEntry(_ref3) {
-                var name = _ref3.name,
-                    startTime = _ref3.startTime,
-                    value = _ref3.value;
-                mod.unstable_onPerformanceData({
-                  name: name,
-                  startTime: startTime,
-                  value: value
-                });
-              };
-            }
-
+            App = _context.sent;
             initialErr = err;
-            _context.prev = 10;
-            _context.next = 13;
+            _context.prev = 6;
+            _context.next = 9;
             return pageLoader.loadPage(page);
 
-          case 13:
+          case 9:
             Component = _context.sent;
 
             if (true) {
-              _context.next = 18;
+              _context.next = 14;
               break;
             }
 
             _require = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'react-is'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())), isValidElementType = _require.isValidElementType;
 
             if (isValidElementType(Component)) {
-              _context.next = 18;
+              _context.next = 14;
               break;
             }
 
             throw new Error("The default export is not a React Component in page: \"" + page + "\"");
 
-          case 18:
-            _context.next = 23;
+          case  [...]

2019-10-07 07:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| buildDuration | 14.7s | 15.7s | ⚠️ +984ms |
| nodeModulesSize | 48.3 MB | 48.3 MB | ⚠️ +116 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..2b8407376.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..7376.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..6604acae7.js | 43.2 kB | N/A | N/A |
| de003c3a9d30..cae7.js gzip | 15.5 kB | N/A | N/A |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| de003c3a9d30..16fd47bf2.js | N/A | 43.2 kB | N/A |
| de003c3a9d30..7bf2.js gzip | N/A | 15.5 kB | N/A |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..42.module.js | 45.6 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 16.5 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| de003c3a9d30..4d.module.js | N/A | 45.6 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 16.5 kB | N/A |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | pavelzubov/next.js canary | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 945 B | 943 B | -2 B |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 953 B | 952 B | -1 B |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 941 B | 939 B | -2 B |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -16,7 +16,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.119f7caa0f0e5f3f7629.module.js"
+        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.de81ed692db39d5d22c5.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
         as="script" crossorigin="anonymous" />
@@ -53,9 +53,9 @@
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9e7d362a01a7a57a5210.js"
+        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3b424217ea7d1cf12042.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.119f7caa0f0e5f3f7629.module.js"
+        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.de81ed692db39d5d22c5.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
         crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -14,7 +14,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/framework.cdb73e402d876d4ac87f.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.119f7caa0f0e5f3f7629.module.js"
+        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.de81ed692db39d5d22c5.module.js"
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-ab3e460f58f5676f29ef.module.js"
         as="script" crossorigin="anonymous" />
@@ -52,9 +52,9 @@
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.155621535702fe040780.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.9e7d362a01a7a57a5210.js"
+        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3b424217ea7d1cf12042.js"
         async="" crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.119f7caa0f0e5f3f7629.module.js"
+        <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.de81ed692db39d5d22c5.module.js"
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/runtime/main-391abed99e83465b0660.js"
         async="" crossorigin="anonymous" nomodule=""></script>
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -14,7 +14,7 @@
         as="script" crossorigin="anonymous" />
         <link  [...]

2019-10-07 09:36 UTC, timneutkens requested changes
This PR doesn't seem correct. The only way a user can inject that state is through manually editing the history which breaks back button behavior and shouldn't be done.

2019-10-07 09:46 UTC, pavelzubov commented
> This PR doesn't seem correct. The only way a user can inject that state is through manually editing the history which breaks back button behavior and shouldn't be done.

Can you describe it in issue topic (zeit#8634) for we can discuss it with other interested users?

2019-10-16 05:21 UTC, Timer commented
I'll close this PR in favor of the linked issue since it appears tests don't pass with this.

Let's please discuss there, I'll tag that issue for investigation!

2019-10-16 05:21 UTC, closed without merging