Dynamic granular chunking
vercel/next.js pull request #9090
Opened 2019-10-15 21:14 UTC by janicklas-ralph

Enabling granular chunks config to 'all' modules

2019-10-15 21:37 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.8s | 17s | ⚠️ +227ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..9dda6167a.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..167a.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..3a0560775.js | 43.2 kB | 43.2 kB | ✓ |
| de003c3a9d30..0775.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..72.module.js | 45.6 kB | 45.6 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.62 kB | 3.62 kB | ✓ |
| index.html gzip | 946 B | 946 B | ✓ |
| link.html | 3.66 kB | 3.66 kB | ✓ |
| link.html gzip | 954 B | 954 B | ✓ |
| withRouter.html | 3.67 kB | 3.67 kB | ✓ |
| withRouter.html gzip | 942 B | 942 B | ✓ |
| Overall change | 10.9 kB | 10.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17.2s | 17.4s | ⚠️ +211ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..9dda6167a.js | 21.9 kB | 21.9 kB | ✓ |
| 4952ddcd88e7..167a.js gzip | 7.81 kB | 7.81 kB | ✓ |
| de003c3a9d30..3a0560775.js | 43.2 kB | 43.2 kB | ✓ |
| de003c3a9d30..0775.js gzip | 15.5 kB | 15.5 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| de003c3a9d30..72.module.js | 45.6 kB | 45.6 kB | ✓ |
| de003c3a9d30..dule.js gzip | 16.5 kB | 16.5 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.81 kB | 1.81 kB | ✓ |
| _app.js gzip | 873 B | 873 B | ✓ |
| _error.js | 12 kB | 12 kB | ✓ |
| _error.js gzip | 4.73 kB | 4.73 kB | ✓ |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 8.14 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 408 B | 408 B | ✓ |
| routerDirect.js gzip | 281 B | 281 B | ✓ |
| withRouter.js | 419 B | 419 B | ✓ |
| withRouter.js gzip | 280 B | 280 B | ✓ |
| Overall change | 35.8 kB | 35.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.7 kB | 1.7 kB | ✓ |
| _app.module.js gzip | 832 B | 832 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 793 B | 793 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 394 B | 394 B | ✓ |
| routerDirect..dule.js gzip | 281 B | 281 B | ✓ |
| withRouter.module.js | 404 B | 404 B | ✓ |
| withRouter.m..dule.js gzip | 278 B | 278 B | ✓ |
| Overall change | 36.1 kB | 36.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 8 [...]

2019-10-16 00:25 UTC, Timer requested changes
Seems tests aren't passing:
```
 FAIL  test/integration/chunking/test/index.test.js (69.93s)
  Chunking
    ✕ should use all url friendly names (4ms)
    ✕ should create a framework chunk (1ms)
    ✕ should not create a commons chunk
    ✕ should not create a lib chunk for react or react-dom
    ✕ should create a _buildManifest.js file (2ms)
    ✕ should not include more than one instance of react-dom (2ms)
    ✕ should hydrate with granularChunks config (60004ms)
```

2019-10-17 20:44 UTC, janicklas-ralph commented
I'm not sure why the tests are failing. They work fine locally. From the errors I think the build isn't running.

I've testing it out by undoing my changes and the tests still fail. Any idea why?

2019-10-22 04:42 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.3s | 16.7s | ⚠️ +308ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17.9s | 17.4s | -509ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 [...]

2019-10-22 15:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15.9s | 17.3s | ⚠️ +1.4s |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17s | 16s | -1s |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓  [...]

2019-10-22 18:26 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15.3s | 15.3s | ⚠️ +27ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.8s | 15.9s | -838ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -139 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54  [...]

2019-10-22 18:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.2s | 17.2s | ⚠️ +953ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.6s | 16.7s | ⚠️ +82ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1. [...]

2019-10-22 19:09 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.1s | 16.6s | ⚠️ +493ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.9s | 17.2s | ⚠️ +333ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1 [...]

2019-10-22 21:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17s | 18.5s | ⚠️ +1.5s |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 18.2s | 18.2s | ⚠️ +72ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54  [...]

2019-10-28 23:26 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.4s | 16.6s | ⚠️ +217ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17s | 16.2s | -724ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB |  [...]

2019-10-29 02:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 16.6s | 16.4s | -180ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 18.3s | 17s | -1.4s |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
 [...]

2019-10-29 20:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15s | 15.4s | ⚠️ +387ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.5s | -27ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -140 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ [...]

2019-10-29 20:49 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17.1s | 16.8s | -310ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -476 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 17.7s | 17.4s | -306ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -476 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ [...]

2019-10-30 01:04 UTC, Timer approved these changes

2019-10-30 01:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15.6s | 15.7s | ⚠️ +159ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -476 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.85 kB | 5.85 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.94 kB | ✓ |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.47 kB | ✓ |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| buildDuration | 15.7s | 15.8s | ⚠️ +143ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -476 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.85 kB | 5.85 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js dynamic-granular-chunking | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53  [...]

2019-10-30 01:27 UTC, merged