Convert wrapper class to function component
vercel/next.js pull request #9095
Opened 2019-10-16 10:41 UTC by timneutkens

Follow-up of #9083

2019-10-16 10:48 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| buildDuration | 16s | 15.8s | -138ms |
| nodeModulesSize | 48.5 MB | 48.5 MB | -443 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 25.6 kB | ⚠️ +6.66 kB |
| main-HASH.js gzip | 6.79 kB | 9.25 kB | ⚠️ +2.46 kB |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..2641f57f9.js | 14.9 kB | N/A | N/A |
| 16b1a7225520..57f9.js gzip | 5.38 kB | N/A | N/A |
| 4952ddcd88e7..0fb1924cf.js | 21.7 kB | N/A | N/A |
| 4952ddcd88e7..24cf.js gzip | 7.77 kB | N/A | N/A |
| de003c3a9d30..aab6ec1a2.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..c1a2.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.5b..dbaff70d3.js | 125 kB | 125 kB | ✓ |
| framework.5b..70d3.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..c320fa3a6.js | N/A | 14.6 kB | N/A |
| 16b1a7225520..a3a6.js gzip | N/A | 5.28 kB | N/A |
| 4952ddcd88e7..47e0aa49c.js | N/A | 15.1 kB | N/A |
| 4952ddcd88e7..a49c.js gzip | N/A | 5.44 kB | N/A |
| Overall change | 211 kB | 211 kB | ⚠️ +6.66 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..3e.module.js | 10.8 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 4.05 kB | N/A | N/A |
| de003c3a9d30..e6.module.js | 34.8 kB | 34.8 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.9 kB | 12.9 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..0c.module.js | N/A | 10.6 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 3.99 kB | N/A |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 8.29 kB | ⚠️ +6.66 kB |
| _app.js gzip | 786 B | 3.45 kB | ⚠️ +2.66 kB |
| _error.js | 12.2 kB | 18.9 kB | ⚠️ +6.66 kB |
| _error.js gzip | 4.78 kB | 7.26 kB | ⚠️ +2.48 kB |
| hooks.js | 12.7 kB | 12.7 kB | ✓ |
| hooks.js gzip | 4.79 kB | 4.79 kB | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.14 kB | 14.8 kB | ⚠️ +6.66 kB |
| link.js gzip | 3.5 kB | 5.98 kB | ⚠️ +2.48 kB |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 35.9 kB | 55.8 kB | ⚠️ +20 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 754 B | 754 B | ✓ |
| _error.module.js | 23.3 kB | 23.3 kB | ✓ |
| _error.module.js gzip | 8.59 kB | 8.59 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.68 kB | 3.68 kB | ✓ |
| routerDirect.module.js | 396 B | 396 B | ✓ |
| routerDirect..dule.js gzip | 283 B | 283 B | ✓ |
| withRouter.module.js | 407 B | 407 B | ✓ |
| withRouter.m..dule.js gzip | 281 B | 281 B | ✓ |
| Overall change | 35.9 kB | 35.9 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 199 B | 200 B | ⚠️ +1 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| index.html | 3.5 kB | 3.5 kB | ✓ |
| index.html gzip | 944 B | 944 B | ✓ |
| link.html | 4.03 kB | 4.03 kB | ✓ |
| link.html gzip | 1.02 kB | 1.02 kB | ✓ |
| withRouter.html | 4.03 kB | 4.03 kB | ✓ |
| withRouter.html gzip | 1.01 kB | 1.01 kB | ✓ |
| Overall change | 11.6 kB | 11.6 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,5 +1,44 @@
 (window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
 
+/***/ "+SFK":
+/***/ (function(module, exports, __webpack_require__) {
+
+__webpack_require__("AUvm");
+__webpack_require__("wgeU");
+__webpack_require__("adOz");
+__webpack_require__("dl0q");
+module.exports = __webpack_require__("WEpk").Symbol;
+
+
+/***/ }),
+
+/***/ "+plK":
+/***/ (function(module, exports, __webpack_require__) {
+
+__webpack_require__("ApPD");
+module.exports = __webpack_require__("WEpk").Object.getPrototypeOf;
+
+
+/***/ }),
+
+/***/ "/+P4":
+/***/ (function(module, exports, __webpack_require__) {
+
+var _Object$getPrototypeOf = __webpack_require__("Bhuq");
+
+var _Object$setPrototypeOf = __webpack_require__("TRZx");
+
+function _getPrototypeOf(o) {
+  module.exports = _getPrototypeOf = _Object$setPrototypeOf ? _Object$getPrototypeOf : function _getPrototypeOf(o) {
+    return o.__proto__ || _Object$getPrototypeOf(o);
+  };
+  return _getPrototypeOf(o);
+}
+
+module.exports = _getPrototypeOf;
+
+/***/ }),
+
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -65,6 +104,76 @@ exports.DataManager = DataManager;
 
 /***/ }),
 
+/***/ "2Nb0":
+/***/ (function(module, exports, __webpack_require__) {
+
+__webpack_require__("FlQf");
+__webpack_require__("bBy9");
+module.exports = __webpack_require__("zLkG").f('iterator');
+
+
+/***/ }),
+
+/***/ "6/1s":
+/***/ (function(module, exports, __webpack_require__) {
+
+var META = __webpack_require__("YqAc")('meta');
+var isObject = __webpack_require__("93I4");
+var has = __webpack_require__("B+OT");
+var setDesc = __webpack_require__("2faE").f;
+var id = 0;
+var isExtensible = Object.isExtensible || function () {
+  return true;
+};
+var FREEZE = !__webpack_require__("KUxP")(function () {
+  return isExtensible(Object.preventExtensions({}));
+});
+var setMeta = function (it) {
+  setDesc(it, META, { value: {
+    i: 'O' + ++id, // object ID
+    w: {}          // weak collections IDs
+  } });
+};
+var fastKey = function (it, create) {
+  // return primitive with prefix
+  if (!isObject(it)) return typeof it == 'symbol' ? it : (typeof it == 'string' ? 'S' : 'P') + it;
+  if (!has(it, META)) {
+    // can't set metadata to uncaught frozen object
+    if (!isExtensible(it)) return 'F';
+    // not necessary to add metadata
+    if (!create) return 'E';
+    // add missing metadata
+    setMeta(it);
+  // return object ID
+  } return it[META].i;
+};
+var getWeak = function (it, create) {
+  if (!has(it, META)) {
+    // can't set metadata to uncaught frozen object
+    if (!isExtensible(it)) return true;
+    // not necessary to add metadata
+    if (!create) return false;
+    // add missing metadata
+    setMeta(it);
+  // return hash weak collections IDs
+  } return it[META].w;
+};
+// add metadata on freeze-family methods calling
 [...]

2019-10-16 13:19 UTC, Janpot commented on packages/next/client/with-router.tsx
> +  function WithRouteWrapper(props: any) {
I feel like this was meant to be called `WithRouterWrapper` instead of `WithRouteWrapper`?

2019-10-18 05:20 UTC, Timer requested changes
We need to figure out why this added 6kB.

2019-10-30 03:22 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| buildDuration | 16s | 16.5s | ⚠️ +447ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -591 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 14.8 kB | -1.76 kB |
| main-HASH.js gzip | 5.85 kB | 5.09 kB | -764 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..63e75d588.js | 19.7 kB | N/A | N/A |
| 16b1a7225520..d588.js gzip | 7.23 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | N/A | N/A |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | N/A | N/A |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..bf733128b.js | N/A | 19.4 kB | N/A |
| 16b1a7225520..128b.js gzip | N/A | 7.13 kB | N/A |
| 314e4c089430..de6eb480f.js | N/A | 7.9 kB | N/A |
| 314e4c089430..480f.js gzip | N/A | 3.31 kB | N/A |
| de003c3a9d30..325502e84.js | N/A | 33 kB | N/A |
| de003c3a9d30..2e84.js gzip | N/A | 12.3 kB | N/A |
| Overall change | 214 kB | 213 kB | -1.76 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..51.module.js | 15.8 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.06 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..91.module.js | N/A | 15.6 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6 kB | N/A |
| Overall change | 192 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 7.71 kB | ⚠️ +6.08 kB |
| _app.js gzip | 788 B | 3.22 kB | ⚠️ +2.43 kB |
| _error.js | 12.3 kB | 14.9 kB | ⚠️ +2.64 kB |
| _error.js gzip | 4.79 kB | 5.57 kB | ⚠️ +783 B |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 4.05 kB | -1.76 kB |
| link.js gzip | 2.56 kB | 1.81 kB | -755 B |
| routerDirect.js | 413 B | 411 B | -2 B |
| routerDirect.js gzip | 285 B | 283 B | -2 B |
| withRouter.js | 423 B | 421 B | -2 B |
| withRouter.js gzip | 284 B | 282 B | -2 B |
| Overall change | 22.8 kB | 29.7 kB | ⚠️ +6.96 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 353 B | ⚠️ +109 B |
| _buildManifest.js gzip | 199 B | 260 B | ⚠️ +61 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 210 B | 205 B | -5 B |
| Overall change | 495 B | 604 B | ⚠️ +109 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.79 kB | -154 B |
| index.html gzip | 1 kB | 983 B | -19 B |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +23 B |
| withRouter.html | 4.47 kB | 4.32 kB | -154 B |
| withRouter.html gzip | 1.07 kB | 1.05 kB | -23 B |
| Overall change | 12.9 kB | 12.6 kB | -308 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -65,22 +65,6 @@ exports.DataManager = DataManager;
 
 /***/ }),
 
-/***/ "8iia":
-/***/ (function(module, exports, __webpack_require__) {
-
-// https://github.com/DavidBruant/Map-Set.prototype.toJSON
-var classof = __webpack_require__("QMMT");
-var from = __webpack_require__("RRc/");
-module.exports = function (NAME) {
-  return function toJSON() {
-    if (classof(this) != NAME) throw TypeError(NAME + "#toJSON isn't generic");
-    return from(this);
-  };
-};
-
-
-/***/ }),
-
 /***/ "BMP1":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -902,20 +886,6 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
-/***/ "RRc/":
-/***/ (function(module, exports, __webpack_require__) {
-
-var forOf = __webpack_require__("oioR");
-
-module.exports = function (iter, ITERATOR) {
-  var result = [];
-  forOf(iter, false, result.push, result, ITERATOR);
-  return result;
-};
-
-
-/***/ }),
-
 /***/ "UDep":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -931,158 +901,6 @@ module.exports = __webpack_require__("WEpk").Map;
 
 /***/ }),
 
-/***/ "Wu5q":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-var dP = __webpack_require__("2faE").f;
-var create = __webpack_require__("oVml");
-var redefineAll = __webpack_require__("XJU/");
-var ctx = __webpack_require__("2GTP");
-var anInstance = __webpack_require__("EXMj");
-var forOf = __webpack_require__("oioR");
-var $iterDefine = __webpack_require__("MPFp");
-var step = __webpack_require__("UO39");
-var setSpecies = __webpack_require__("TJWN");
-var DESCRIPTORS = __webpack_require__("jmDH");
-var fastKey = __webpack_require__("6/1s").fastKey;
-var validate = __webpack_require__("n3ko");
-var SIZE = DESCRIPTORS ? '_s' : 'size';
-
-var getEntry = function (that, key) {
-  // fast case
-  var index = fastKey(key);
-  var entry;
-  if (index !== 'F') return that._i[index];
-  // frozen object case
-  for (entry = that._f; entry; entry = entry.n) {
-    if (entry.k == key) return entry;
-  }
-};
-
-module.exports = {
-  getConstructor: function (wrapper, NAME, IS_MAP, ADDER) {
-    var C = wrapper(function (that, iterable) {
-      anInstance(that, C, NAME, '_i');
-      that._t = NAME;         // collection type
-      that._i = create(null); // index
-      that._f = undefined;    // first entry
-      that._l = undefined;    // last entry
-      that[SIZE] = 0;         // size
-      if (iterable != undefined) forOf(iterable, IS_MAP, that [...]

2019-10-30 03:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| buildDuration | 15.9s | 16.1s | ⚠️ +250ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -581 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 14.8 kB | -1.76 kB |
| main-HASH.js gzip | 5.85 kB | 5.09 kB | -764 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..63e75d588.js | 19.7 kB | N/A | N/A |
| 16b1a7225520..d588.js gzip | 7.23 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | N/A | N/A |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | N/A | N/A |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..5a3c69e4c.js | N/A | 19.4 kB | N/A |
| 16b1a7225520..9e4c.js gzip | N/A | 7.13 kB | N/A |
| 314e4c089430..de6eb480f.js | N/A | 7.9 kB | N/A |
| 314e4c089430..480f.js gzip | N/A | 3.31 kB | N/A |
| de003c3a9d30..325502e84.js | N/A | 33 kB | N/A |
| de003c3a9d30..2e84.js gzip | N/A | 12.3 kB | N/A |
| Overall change | 214 kB | 213 kB | -1.76 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..51.module.js | 15.8 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.06 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..d7.module.js | N/A | 15.6 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6 kB | N/A |
| Overall change | 192 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 7.71 kB | ⚠️ +6.08 kB |
| _app.js gzip | 788 B | 3.22 kB | ⚠️ +2.43 kB |
| _error.js | 12.3 kB | 14.9 kB | ⚠️ +2.64 kB |
| _error.js gzip | 4.79 kB | 5.57 kB | ⚠️ +783 B |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 4.05 kB | -1.76 kB |
| link.js gzip | 2.56 kB | 1.81 kB | -755 B |
| routerDirect.js | 413 B | 411 B | -2 B |
| routerDirect.js gzip | 285 B | 283 B | -2 B |
| withRouter.js | 423 B | 421 B | -2 B |
| withRouter.js gzip | 284 B | 282 B | -2 B |
| Overall change | 22.8 kB | 29.7 kB | ⚠️ +6.96 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 353 B | ⚠️ +109 B |
| _buildManifest.js gzip | 199 B | 259 B | ⚠️ +60 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 210 B | 209 B | -1 B |
| Overall change | 495 B | 604 B | ⚠️ +109 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.79 kB | -154 B |
| index.html gzip | 1 kB | 983 B | -19 B |
| link.html | 4.47 kB | 4.47 kB | ✓ |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +24 B |
| withRouter.html | 4.47 kB | 4.32 kB | -154 B |
| withRouter.html gzip | 1.07 kB | 1.05 kB | -21 B |
| Overall change | 12.9 kB | 12.6 kB | -308 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -65,22 +65,6 @@ exports.DataManager = DataManager;
 
 /***/ }),
 
-/***/ "8iia":
-/***/ (function(module, exports, __webpack_require__) {
-
-// https://github.com/DavidBruant/Map-Set.prototype.toJSON
-var classof = __webpack_require__("QMMT");
-var from = __webpack_require__("RRc/");
-module.exports = function (NAME) {
-  return function toJSON() {
-    if (classof(this) != NAME) throw TypeError(NAME + "#toJSON isn't generic");
-    return from(this);
-  };
-};
-
-
-/***/ }),
-
 /***/ "BMP1":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -902,20 +886,6 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
-/***/ "RRc/":
-/***/ (function(module, exports, __webpack_require__) {
-
-var forOf = __webpack_require__("oioR");
-
-module.exports = function (iter, ITERATOR) {
-  var result = [];
-  forOf(iter, false, result.push, result, ITERATOR);
-  return result;
-};
-
-
-/***/ }),
-
 /***/ "UDep":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -931,158 +901,6 @@ module.exports = __webpack_require__("WEpk").Map;
 
 /***/ }),
 
-/***/ "Wu5q":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-var dP = __webpack_require__("2faE").f;
-var create = __webpack_require__("oVml");
-var redefineAll = __webpack_require__("XJU/");
-var ctx = __webpack_require__("2GTP");
-var anInstance = __webpack_require__("EXMj");
-var forOf = __webpack_require__("oioR");
-var $iterDefine = __webpack_require__("MPFp");
-var step = __webpack_require__("UO39");
-var setSpecies = __webpack_require__("TJWN");
-var DESCRIPTORS = __webpack_require__("jmDH");
-var fastKey = __webpack_require__("6/1s").fastKey;
-var validate = __webpack_require__("n3ko");
-var SIZE = DESCRIPTORS ? '_s' : 'size';
-
-var getEntry = function (that, key) {
-  // fast case
-  var index = fastKey(key);
-  var entry;
-  if (index !== 'F') return that._i[index];
-  // frozen object case
-  for (entry = that._f; entry; entry = entry.n) {
-    if (entry.k == key) return entry;
-  }
-};
-
-module.exports = {
-  getConstructor: function (wrapper, NAME, IS_MAP, ADDER) {
-    var C = wrapper(function (that, iterable) {
-      anInstance(that, C, NAME, '_i');
-      that._t = NAME;         // collection type
-      that._i = create(null); // index
-      that._f = undefined;    // first entry
-      that._l = undefined;    // last entry
-      that[SIZE] = 0;         // size
-      if (iterable != undefined) forOf(iterable, IS_MAP, th [...]

2019-11-09 22:35 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| buildDuration | 14.8s | 15.1s | ⚠️ +258ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | -581 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 14.8 kB | -1.76 kB |
| main-HASH.js gzip | 5.88 kB | 5.12 kB | -765 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | N/A | N/A |
| 16b1a7225520..34ec.js gzip | 7.38 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | N/A | N/A |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | N/A | N/A |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | N/A | N/A |
| de003c3a9d30..add9.js gzip | 10.9 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..641cd3dea.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..3dea.js gzip | N/A | 7.28 kB | N/A |
| 314e4c089430..de6eb480f.js | N/A | 7.9 kB | N/A |
| 314e4c089430..480f.js gzip | N/A | 3.31 kB | N/A |
| de003c3a9d30..39988e4af.js | N/A | 33.1 kB | N/A |
| de003c3a9d30..e4af.js gzip | N/A | 12.3 kB | N/A |
| Overall change | 214 kB | 214 kB | -1.76 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.22 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..68.module.js | N/A | 16 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.17 kB | N/A |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| polyfills-HASH.js | 8.14 kB | 8.14 kB | ✓ |
| polyfills-HASH.js gzip | 2.76 kB | 2.76 kB | ✓ |
| Overall change | 8.14 kB | 8.14 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 7.71 kB | ⚠️ +6.08 kB |
| _app.js gzip | 788 B | 3.22 kB | ⚠️ +2.43 kB |
| _error.js | 12.3 kB | 14.9 kB | ⚠️ +2.64 kB |
| _error.js gzip | 4.79 kB | 5.57 kB | ⚠️ +783 B |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 4.05 kB | -1.76 kB |
| link.js gzip | 2.56 kB | 1.81 kB | -755 B |
| routerDirect.js | 413 B | 411 B | -2 B |
| routerDirect.js gzip | 285 B | 283 B | -2 B |
| withRouter.js | 423 B | 421 B | -2 B |
| withRouter.js gzip | 284 B | 282 B | -2 B |
| Overall change | 22.8 kB | 29.7 kB | ⚠️ +6.96 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 353 B | ⚠️ +109 B |
| _buildManifest.js gzip | 201 B | 260 B | ⚠️ +59 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 208 B | -1 B |
| Overall change | 495 B | 604 B | ⚠️ +109 B |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | timneutkens/next.js fix/class-to-function-withrouter | Change |
| - | - | - | - |
| index.html | 4.06 kB | 3.9 kB | -154 B |
| index.html gzip | 1.04 kB | 1.02 kB | -20 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.14 kB | ⚠️ +24 B |
| withRouter.html | 4.59 kB | 4.43 kB | -154 B |
| withRouter.html gzip | 1.1 kB | 1.09 kB | -18 B |
| Overall change | 13.2 kB | 12.9 kB | -308 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -65,22 +65,6 @@ exports.DataManager = DataManager;
 
 /***/ }),
 
-/***/ "8iia":
-/***/ (function(module, exports, __webpack_require__) {
-
-// https://github.com/DavidBruant/Map-Set.prototype.toJSON
-var classof = __webpack_require__("QMMT");
-var from = __webpack_require__("RRc/");
-module.exports = function (NAME) {
-  return function toJSON() {
-    if (classof(this) != NAME) throw TypeError(NAME + "#toJSON isn't generic");
-    return from(this);
-  };
-};
-
-
-/***/ }),
-
 /***/ "BMP1":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -915,20 +899,6 @@ module.exports = __webpack_require__("UDep");
 
 /***/ }),
 
-/***/ "RRc/":
-/***/ (function(module, exports, __webpack_require__) {
-
-var forOf = __webpack_require__("oioR");
-
-module.exports = function (iter, ITERATOR) {
-  var result = [];
-  forOf(iter, false, result.push, result, ITERATOR);
-  return result;
-};
-
-
-/***/ }),
-
 /***/ "UDep":
 /***/ (function(module, exports, __webpack_require__) {
 
@@ -944,158 +914,6 @@ module.exports = __webpack_require__("WEpk").Map;
 
 /***/ }),
 
-/***/ "Wu5q":
-/***/ (function(module, exports, __webpack_require__) {
-
-"use strict";
-
-var dP = __webpack_require__("2faE").f;
-var create = __webpack_require__("oVml");
-var redefineAll = __webpack_require__("XJU/");
-var ctx = __webpack_require__("2GTP");
-var anInstance = __webpack_require__("EXMj");
-var forOf = __webpack_require__("oioR");
-var $iterDefine = __webpack_require__("MPFp");
-var step = __webpack_require__("UO39");
-var setSpecies = __webpack_require__("TJWN");
-var DESCRIPTORS = __webpack_require__("jmDH");
-var fastKey = __webpack_require__("6/1s").fastKey;
-var validate = __webpack_require__("n3ko");
-var SIZE = DESCRIPTORS ? '_s' : 'size';
-
-var getEntry = function (that, key) {
-  // fast case
-  var index = fastKey(key);
-  var entry;
-  if (index !== 'F') return that._i[index];
-  // frozen object case
-  for (entry = that._f; entry; entry = entry.n) {
-    if (entry.k == key) return entry;
-  }
-};
-
-module.exports = {
-  getConstructor: function (wrapper, NAME, IS_MAP, ADDER) {
-    var C = wrapper(function (t [...]

2019-11-09 22:56 UTC, timneutkens commented
It's because of the 50% calculation and the way the test app is set up currently. Going to merge this for now.

2019-11-09 22:57 UTC, merged

2019-11-26 21:57 UTC, dustinsavery commented on packages/next/client/router.ts
> -export { Router, RouterContext, NextRouter }
@timneutkens I don't know why this was reverted. This was how I was able to type my router props before:
```
router: React.ContextType<typeof RouterContext>;
```

Is it available from another location now without having to dig multiple layers deep?