Adding an example for universal custom routing
vercel/next.js pull request #913
Opened 2017-01-28 18:31 UTC by gcpantazis

Howdy! I was looking through the examples for a custom `server.js`, and they all worked well enough on the server-side. I did notice that they stop working on the client-side unless you use the `href` and `as` attributes in conjunction on your `Link` components, effectively duplicating your routing logic wherever you have a `Link`.

I can't find it at the moment, but in another issue @rauchg (or perhaps another of the maintainers) +1'd the concept of making a custom component to handle the route matching, referencing some shared configuration, which works like a charm for us. I didn't see a complete example of universal route matching in `./examples`, so I thought I'd add one.

Hopefully this isn't duplicative from another example! Thanks so much to the team — this project has been an amazing leg up for us! Hoping to get some of our production code moved over to Next soon!

2017-01-29 00:13 UTC, arunoda requested changes
This is pretty superb. This is why we ship a meta api for routing.

Then we see projects like this.

2017-01-29 00:13 UTC, arunoda commented on examples/custom-universal-routing/components/link.js
> +    return route.match(element.test)
How about if we written this like this:

```js
element.test(route)
```

2017-01-29 00:13 UTC, arunoda commented on examples/custom-universal-routing/next.config.js
> +  customRoutes: [{
I like using `next.config.js` as the place for this. But in this file, we might import a lot of server only modules. 
So, when we import this on both environments, that'll be an issue.

So, let's use a different file called `routes.json` or `routes.js`

2017-01-29 00:13 UTC, arunoda commented on examples/custom-universal-routing/next.config.js
> +    test: /^\/about(\/?)$/,
Use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) for express like route URLs.

2017-01-29 11:57 UTC, sedubois commented on examples/custom-universal-routing/components/link.js
> +  const match = customRoutes.find((element) => {
should this match boolean be memorized for performance?

2017-01-29 12:19 UTC, sedubois commented
This is quite inspiring :) would also be great to see
- how to handle route params (e.g /foo/:id)?
- how would an HTTP server like Koa or Express handle such a `routes.js` config file without DRY?

2017-01-29 17:45 UTC, frol commented
@gcpantazis Great example! Thanks for sharing it!

JFYI: I have recently bumped into another approach with routing: https://github.com/matthewmueller/next-route

2017-01-30 02:30 UTC, arunoda commented
@frol That's a good one too.
And I'm waiting for, someone is building a React Router like API on top of our routing API.
That's totally doable.

2017-02-25 15:30 UTC, timneutkens commented
@gcpantazis could you update this one also?

2017-02-25 20:58 UTC, gcpantazis commented
@timneutkens aye, will do on Monday. I implemented much of what @arunoda suggested in our downstream project, so I'll port that up here as well. 👍

2017-02-25 21:21 UTC, timneutkens commented
Awesome, thank you very much ❤️

2017-03-08 22:10 UTC, shane-gorilla commented on examples/custom-universal-routing/components/link.js
> +    return route.match(element.test)
Does it have to be a regex?

2017-03-08 22:14 UTC, mcdermed commented on examples/custom-universal-routing/components/link.js
> +    return route.match(element.test)
Using match gives more flexibility in the way you define the `element.test`
```
'/test'.match('/test')
// ["/test"]
```

2017-10-22 10:05 UTC, timneutkens commented
I'm going to close this for inactivity. Cleaning up old PRs. i'd love to take this in one day though ❤️

2017-10-22 10:05 UTC, closed without merging