Decrease the load priority of client _buildManifest.js
vercel/next.js pull request #9167
Opened 2019-10-22 21:27 UTC by janicklas-ralph

2019-10-22 21:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 15.5s | 15.8s | ⚠️ +293ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | N/A | N/A |
| _buildManife..dule.js gzip | 209 B | N/A | N/A |
| Overall change | 495 B | 244 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.81 kB | -130 B |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.34 kB | -130 B |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.34 kB | -130 B |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.5 kB | -390 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -61,10 +61,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3e859d76b9dfffa4e32d.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -70,10 +70,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e28bfaa83b9b757c5b6b.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -68,10 +68,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e28bfaa83b9b757c5b6b.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 16.9s | 16s | -869ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.j [...]

2019-10-22 22:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 16.7s | 17s | ⚠️ +284ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 211 kB | 211 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 17.2 kB | 17.2 kB | ✓ |
| main-HASH.module.js gzip | 6.53 kB | 6.53 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d2.module.js | 10.8 kB | 10.8 kB | ✓ |
| 16b1a7225520..dule.js gzip | 4.05 kB | 4.05 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..11.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.68 kB | 8.68 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.51 kB | 1.51 kB | ✓ |
| hooks.js gzip | 789 B | 789 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 8.15 kB | 8.15 kB | ✓ |
| link.js gzip | 3.5 kB | 3.5 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 24.7 kB | 24.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 756 B | 756 B | ✓ |
| _error.module.js | 10.6 kB | 10.6 kB | ✓ |
| _error.module.js gzip | 4.28 kB | 4.28 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 794 B | 794 B | ✓ |
| index.module.js | 294 B | 294 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 8.53 kB | 8.53 kB | ✓ |
| link.module.js gzip | 3.69 kB | 3.69 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 23.3 kB | 23.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | N/A | N/A |
| _buildManife..dule.js gzip | 209 B | N/A | N/A |
| Overall change | 495 B | 244 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.81 kB | -130 B |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.34 kB | -130 B |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.34 kB | -130 B |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.5 kB | -390 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -61,10 +61,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.3e859d76b9dfffa4e32d.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -70,10 +70,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e28bfaa83b9b757c5b6b.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -68,10 +68,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-e28bfaa83b9b757c5b6b.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 18.7s | 16.9s | -1.8s |
| nodeModulesSize | 48.7 MB | 48.7 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 18.9 kB | 18.9 kB | ✓ |
| main-HASH.js gzip | 6.79 kB | 6.79 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4a7b46563.js | 14.9 kB | 14.9 kB | ✓ |
| 16b1a7225520..6563.js gzip | 5.38 kB | 5.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js [...]

2019-10-23 10:54 UTC, timneutkens approved these changes

2019-10-23 15:22 UTC, Timer requested changes
Blocking this merge as this PR doesn't seem right. Will review in depth after my flight!

2019-10-28 23:28 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 15.4s | 15.8s | ⚠️ +318ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | N/A | N/A |
| _buildManife..dule.js gzip | 209 B | N/A | N/A |
| Overall change | 495 B | 244 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.81 kB | -130 B |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.34 kB | -130 B |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.34 kB | -130 B |
| withRouter.html gzip | 1.07 kB | 1.07 kB | ✓ |
| Overall change | 12.9 kB | 12.5 kB | -390 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -61,10 +61,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.710f68a91537b45d6153.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -70,10 +70,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-11265a5ef9be647fbeaa.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -68,10 +68,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-11265a5ef9be647fbeaa.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 16.2s | 15.7s | -531ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.j [...]

2019-10-29 20:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 16.8s | 16.9s | ⚠️ +103ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | 28.6 kB | ✓ |
| de003c3a9d30..d310.js gzip | 10.8 kB | 10.8 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | 15.9 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.08 kB | 6.08 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | 22.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.67 kB | 8.67 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | N/A | N/A |
| _buildManife..dule.js gzip | 209 B | N/A | N/A |
| Overall change | 495 B | 244 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.94 kB | 3.81 kB | -130 B |
| index.html gzip | 1 kB | 1 kB | ✓ |
| link.html | 4.47 kB | 4.34 kB | -130 B |
| link.html gzip | 1.08 kB | 1.08 kB | ✓ |
| withRouter.html | 4.47 kB | 4.34 kB | -130 B |
| withRouter.html gzip | 1.07 kB | 1.07 kB | -1 B |
| Overall change | 12.9 kB | 12.5 kB | -390 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -61,10 +61,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.710f68a91537b45d6153.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -70,10 +70,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-a085a6c64ecf07be5320.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -68,10 +68,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-a085a6c64ecf07be5320.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 17.3s | 17.1s | -153ms |
| nodeModulesSize | 48.4 MB | 48.4 MB | -1.5 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..586e.js gzip | 7.25 kB | 7.25 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HAS [...]

2019-10-30 01:08 UTC, Timer requested changes

2019-10-30 01:08 UTC, Timer commented on packages/next/build/webpack/plugins/build-manifest-plugin.ts
> -            compilation.assets[modernClientManifestPath] = new RawSource(
We still need to generate this bundle, correct? Can you explain why this is removed?

2019-10-30 01:08 UTC, Timer commented on test/integration/chunking-minimal/test/index.test.js
> -  it('should have an empty modern client-manifest', async () => {
Seems this should still be here.

2019-10-30 01:10 UTC, Timer requested changes

2019-10-30 01:10 UTC, Timer commented on packages/next/build/webpack/plugins/build-manifest-plugin.ts
> -          assetMap.pages['/_app'].push(
Should we still inject this to the `assetMap` and continue filtering it out later?

2019-10-30 01:10 UTC, Timer commented on packages/next/pages/_document.tsx
> -              !file.includes('_buildManifest')
(filtering out here)

2019-10-30 01:10 UTC, Timer commented on packages/next/pages/_document.tsx
> +        {process.env.__NEXT_GRANULAR_CHUNKS ? (
Is this the meat of the PR? Adding a separate async for this specific script to the end?

Also, we need to support the modern version of this.

2019-11-11 05:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 13.7s | -369ms |
| nodeModulesSize | 49 MB | 49 MB | -1.62 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | N/A | N/A |
| _buildManife..dule.js gzip | 209 B | N/A | N/A |
| Overall change | 604 B | 353 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.66 kB | -245 B |
| index.html gzip | 1.01 kB | 983 B | -32 B |
| link.html | 4.58 kB | 4.34 kB | -245 B |
| link.html gzip | 1.14 kB | 1.11 kB | -34 B |
| withRouter.html | 4.43 kB | 4.19 kB | -245 B |
| withRouter.html gzip | 1.09 kB | 1.05 kB | -35 B |
| Overall change | 12.9 kB | 12.2 kB | -735 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -31,7 +31,6 @@
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script crossorigin="anonymous" nomodule="" src="/_next/static/runtime/polyfills-e754f88c1bb3ceddee51.js"></script>
         <script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.js"
         crossorigin="anonymous" nomodule=""></script>
         <script async="" data-next-page="/" src="/_next/static/BUILD_ID/pages/index.module.js"
@@ -60,10 +59,7 @@
         async="" crossorigin="anonymous" type="module"></script>
         <script src="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.6ad24cd530d796126b06.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -36,7 +36,6 @@
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
         </script>
-        <script crossorigin="anonymous" nomodule="" src="/_next/static/runtime/polyfills-e754f88c1bb3ceddee51.js"></script>
         <script async="" data-next-page="/link" src="/_next/static/BUILD_ID/pages/link.js"
         crossorigin="anonymous" nomodule=""></script>
         <script async="" data-next-page="/link" src="/_next/static/BUILD_ID/pages/link.module.js"
@@ -71,10 +70,7 @@
         async="" crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/runtime/main-7f5a8bf381b68c2fbe01.module.js"
         async="" crossorigin="anonymous" type="module"></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.js" async=""
-        crossorigin="anonymous" nomodule=""></script>
-        <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
-        async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymou [...]

2019-11-11 06:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 14.6s | 14.8s | ⚠️ +197ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +314 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 4.11 kB | ⚠️ +209 B |
| index.html gzip | 1.01 kB | 1.03 kB | ⚠️ +12 B |
| link.html | 4.58 kB | 4.79 kB | ⚠️ +209 B |
| link.html gzip | 1.14 kB | 1.15 kB | ⚠️ +10 B |
| withRouter.html | 4.43 kB | 4.64 kB | ⚠️ +209 B |
| withRouter.html gzip | 1.09 kB | 1.1 kB | ⚠️ +10 B |
| Overall change | 12.9 kB | 13.5 kB | ⚠️ +627 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -20,6 +20,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.6ad24cd530d796126b06.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -64,6 +66,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,6 +22,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-7f5a8bf381b68c2fbe01.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -75,6 +77,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,6 +22,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-7f5a8bf381b68c2fbe01.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -71,6 +73,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 15.2s | 15.2s | ⚠️ +7ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +314 B |

</details>

<details>
<summary><strong>Cli [...]

2019-11-11 07:00 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 12.6s | -189ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +314 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 4.11 kB | ⚠️ +209 B |
| index.html gzip | 1.01 kB | 1.03 kB | ⚠️ +12 B |
| link.html | 4.58 kB | 4.79 kB | ⚠️ +209 B |
| link.html gzip | 1.14 kB | 1.15 kB | ⚠️ +10 B |
| withRouter.html | 4.43 kB | 4.64 kB | ⚠️ +209 B |
| withRouter.html gzip | 1.09 kB | 1.1 kB | ⚠️ +10 B |
| Overall change | 12.9 kB | 13.5 kB | ⚠️ +627 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -20,6 +20,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.6ad24cd530d796126b06.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -64,6 +66,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -22,6 +22,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-7f5a8bf381b68c2fbe01.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -75,6 +77,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -22,6 +22,8 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/runtime/main-7f5a8bf381b68c2fbe01.module.js"
         as="script" crossorigin="anonymous" />
+        <link rel="preload" href="/_next/static/BUILD_ID/_buildManifest.module.js"
+        as="script" crossorigin="anonymous" />
     </head>
     
     <body>
@@ -71,6 +73,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 13s | 13.2s | ⚠️ +219ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +314 B |

</details>

<details>
<summary><strong>Client [...]

2019-11-11 07:13 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 12.8s | 13s | ⚠️ +209ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +576 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 4 kB | ⚠️ +97 B |
| index.html gzip | 1.01 kB | 1.02 kB | ⚠️ +6 B |
| link.html | 4.58 kB | 4.68 kB | ⚠️ +97 B |
| link.html gzip | 1.14 kB | 1.15 kB | ⚠️ +7 B |
| withRouter.html | 4.43 kB | 4.53 kB | ⚠️ +97 B |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ⚠️ +7 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +291 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -64,6 +64,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -75,6 +75,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -71,6 +71,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.6s | ⚠️ +301ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +576 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 [...]

2019-11-11 07:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 14s | 14.3s | ⚠️ +280ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +664 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 4 kB | ⚠️ +97 B |
| index.html gzip | 1.01 kB | 1.02 kB | ⚠️ +6 B |
| link.html | 4.58 kB | 4.68 kB | ⚠️ +97 B |
| link.html gzip | 1.14 kB | 1.15 kB | ⚠️ +7 B |
| withRouter.html | 4.43 kB | 4.53 kB | ⚠️ +97 B |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ⚠️ +7 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +291 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -64,6 +64,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -75,6 +75,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -71,6 +71,7 @@
         crossorigin="anonymous" nomodule=""></script>
         <script src="/_next/static/BUILD_ID/_buildManifest.module.js"
         async="" crossorigin="anonymous" type="module"></script>
+        <script async="" crossorigin="anonymous" src="/_next/static/BUILD_ID/_buildManifest.js"></script>
     </body>
 
 </html>
\ No newline at end of file
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.3s | ⚠️ +148ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +664 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 [...]

2019-11-11 07:26 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 11.6s | 12.1s | ⚠️ +472ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +482 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 12s | 12s | ⚠️ +14ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +482 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ | [...]

2019-11-11 07:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.3s | ⚠️ +245ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +408 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 259 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.09 kB | 1.09 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| buildDuration | 15.1s | 14.8s | -321ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +408 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 14.9 kB | ✓ |
| main-HASH.js gzip | 5.12 kB | 5.12 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b3f403e8a.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..3e8a.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..d8.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js issue131 | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ [...]

2019-11-11 07:30 UTC, Timer approved these changes

2019-11-11 07:35 UTC, merged