Native url
vercel/next.js pull request #9200
Opened 2019-10-25 17:15 UTC by janicklas-ralph

Following-up on the URL work from the [previous PR](https://github.com/zeit/next.js/pull/8225)
Built a new library called [native-url](https://github.com/GoogleChromeLabs/native-url) to address the concerns with the differences in the api between our solution the node-url
The library has an exhaustive list of test-cases to ensure it remains API compatible.

2019-10-26 16:43 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 15.9s | 15.3s | -561ms |
| nodeModulesSize | 48.7 MB | 48.9 MB | ⚠️ +214 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +12 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +14 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +14 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" cros [...]

2019-10-28 17:50 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 16.4s | 16.7s | ⚠️ +325ms |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +214 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" c [...]

2019-10-28 18:38 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 16s | 16.5s | ⚠️ +598ms |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" cro [...]

2019-10-28 21:17 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 16.8s | 16.7s | -56ms |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" cross [...]

2019-10-28 22:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 15.1s | 15.1s | ⚠️ +47ms |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" cr [...]

2019-10-28 23:24 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 14.7s | 16.3s | ⚠️ +1.6s |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" cr [...]

2019-10-29 02:28 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 16.4s | 16s | -368ms |
| nodeModulesSize | 48.4 MB | 48.6 MB | ⚠️ +214 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.86 kB | 5.86 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..b6ebb586e.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..586e.js gzip | 7.25 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..9e9c1d310.js | 28.6 kB | N/A | N/A |
| de003c3a9d30..d310.js gzip | 10.8 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..1125d2f48.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..2f48.js gzip | N/A | 7.25 kB | N/A |
| de003c3a9d30..e17ebe025.js | N/A | 21.4 kB | N/A |
| de003c3a9d30..e025.js gzip | N/A | 8.23 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14 kB | 14 kB | ✓ |
| main-HASH.module.js gzip | 5.25 kB | 5.25 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..4c.module.js | 15.9 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.08 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..c0.module.js | 22.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.67 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..28.module.js | N/A | 15.9 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.08 kB | N/A |
| de003c3a9d30..fd.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.09 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.53 kB | 1.53 kB | ✓ |
| _app.module.js gzip | 749 B | 749 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.47 kB | 5.47 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.1 kB | 20.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.94 kB | 4.04 kB | ⚠️ +94 B |
| index.html gzip | 1 kB | 1.02 kB | ⚠️ +15 B |
| link.html | 4.47 kB | 4.56 kB | ⚠️ +94 B |
| link.html gzip | 1.08 kB | 1.1 kB | ⚠️ +16 B |
| withRouter.html | 4.47 kB | 4.57 kB | ⚠️ +94 B |
| withRouter.html gzip | 1.07 kB | 1.09 kB | ⚠️ +17 B |
| Overall change | 12.9 kB | 13.2 kB | ⚠️ +282 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[14],{
 
 /***/ "/h46":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1,4 +1,4 @@
-(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[12],{
+(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[13],{
 
 /***/ "+oT+":
 /***/ (function(module, exports, __webpack_require__) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a1936a21395e34d00ee0.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.07be4b3c869de9ce5d37.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.8d1caa0eed52bc802a38.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.1d79965e6468763e51fb.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -12,13 +12,13 @@
         as="script" crosso [...]

2019-11-05 19:06 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 13.7s | 14.8s | ⚠️ +1.1s |
| nodeModulesSize | 48.6 MB | 48.8 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.89 kB | 5.89 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 201 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.03 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.11 kB | ✓ |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.4s | -12ms |
| nodeModulesSize | 48.6 MB | 48.8 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.89 kB | 5.89 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | 20.1 kB | ✓ |
| 16b1a7225520..34ec.js gzip | 7.38 kB | 7.38 kB | ✓ |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | 28.7 kB | ✓ |
| de003c3a9d30..add9.js gzip | 10.9 kB | 10.9 kB | ✓ |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 214 kB | 214 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | 16.2 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.22 kB | 6.22 kB | ✓ |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 192 kB | 192 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | ✓ |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.modul [...]

2019-11-05 19:11 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 14.2s | 14.2s | -84ms |
| nodeModulesSize | 48.6 MB | 48.8 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 16.6 kB | 16.6 kB | ✓ |
| main-HASH.js gzip | 5.89 kB | 5.89 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..7459734ec.js | 20.1 kB | N/A | N/A |
| 16b1a7225520..34ec.js gzip | 7.38 kB | N/A | N/A |
| 4952ddcd88e7..bfe360fe6.js | 10.5 kB | 10.5 kB | ✓ |
| 4952ddcd88e7..0fe6.js gzip | 4.06 kB | 4.06 kB | ✓ |
| commons.HASH.js | 11.3 kB | 11.3 kB | ✓ |
| commons.HASH.js gzip | 4.23 kB | 4.23 kB | ✓ |
| de003c3a9d30..254ddadd9.js | 28.7 kB | N/A | N/A |
| de003c3a9d30..add9.js gzip | 10.9 kB | N/A | N/A |
| framework.1b..cdcfe1283.js | 125 kB | 125 kB | ✓ |
| framework.1b..1283.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..fb128ee66.js | N/A | 20.1 kB | N/A |
| 16b1a7225520..ee66.js gzip | N/A | 7.38 kB | N/A |
| de003c3a9d30..cbcd658e3.js | N/A | 21.6 kB | N/A |
| de003c3a9d30..58e3.js gzip | N/A | 8.3 kB | N/A |
| Overall change | 214 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.31 kB | 5.31 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0d.module.js | 16.2 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.22 kB | N/A | N/A |
| 4952ddcd88e7..4a.module.js | 12.8 kB | 12.8 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.75 kB | 4.75 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.5b..d3.module.js | 125 kB | 125 kB | ✓ |
| framework.5b..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..c9.module.js | N/A | 16.2 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.22 kB | N/A |
| de003c3a9d30..86.module.js | N/A | 15.1 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 192 kB | 185 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 1.63 kB | 1.63 kB | ✓ |
| _app.js gzip | 788 B | 788 B | ✓ |
| _error.js | 12.3 kB | 12.3 kB | ✓ |
| _error.js gzip | 4.79 kB | 4.79 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 5.81 kB | 5.81 kB | ✓ |
| link.js gzip | 2.56 kB | 2.56 kB | -1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 1.52 kB | 1.52 kB | ✓ |
| hooks.module.js gzip | 792 B | 792 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 20.2 kB | 20.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 199 B | -2 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 210 B | ⚠️ +1 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.03 kB | 1.03 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.11 kB | 1.11 kB | ⚠️ +1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -297,7 +297,7 @@ exports["default"] = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>link.module.js</strong></summary>

```diff
@@ -285,7 +285,7 @@ exports.default = void 0;
 
 var _map = _interopRequireDefault(__webpack_require__("LX0d"));
 
-var _url = __webpack_require__("CxY0");
+var _url = __webpack_require__("z/uh");
 
 var _react = _interopRequireWildcard(__webpack_require__("q1tI"));
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.a9e45275d81f65ce1b3a.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.385e78faee10fe6ac545.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.module.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.13a61a2410d3fe9a0cb1.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a){return {"/link":[a],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.adf253ce96142ddda060.module.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -18,7 +18,7 @@
         as="script" crossorigin="anonymous" />
         <link rel="preload" href="/_next/static/chunks/4952ddcd88e7185e66c9cf40e2d848b7e27f1574.89ebf3e33b855a0478ce.module.js"
         as="script" crossorigin="anonymous" />
-        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.dda3a797bb804537ed85.module.js"
+        <link rel="preload" href="/_next/static/chunks/de003c3a9d308750aa009870a5926f9b18ab31f4.8d106b3a04ffa60957f1.module.js"
         as="script" crossorigin="anonymous" />
     </head>
     
@@ -31,7 +31,7 @@
         <script crossorigin="anonymous" nomodule="">
             !function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbefore [...]

2019-11-19 22:54 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13s | ⚠️ +65ms |
| nodeModulesSize | 48.3 MB | 48.5 MB | ⚠️ +213 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..0f1a45b52.js | 19.9 kB | N/A | N/A |
| 16b1a7225520..5b52.js gzip | 7.34 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..e4af.js gzip | 12.3 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..615b6a603.js | N/A | 19.9 kB | N/A |
| 16b1a7225520..a603.js gzip | N/A | 7.34 kB | N/A |
| de003c3a9d30..490593d6f.js | N/A | 26 kB | N/A |
| de003c3a9d30..3d6f.js gzip | N/A | 9.78 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..99.module.js | 16.1 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.22 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..82.module.js | N/A | 16.1 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.22 kB | N/A |
| de003c3a9d30..86.module.js | N/A | 15.1 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 191 kB | 184 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 259 B | 261 B | ⚠️ +2 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 210 B | ⚠️ +5 B |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ⚠️ +1 B |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | -1 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[objec [...]

2019-11-25 19:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.8s | ⚠️ +80ms |
| nodeModulesSize | 48.3 MB | 48.5 MB | ⚠️ +215 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..ebc17c08d.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..c08d.js gzip | 7.35 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..ca9b7d26b.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..d26b.js gzip | N/A | 7.35 kB | N/A |
| de003c3a9d30..5a138db32.js | N/A | 21.2 kB | N/A |
| de003c3a9d30..db32.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..9a.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.14 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..b6.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.14 kB | N/A |
| de003c3a9d30..86.module.js | N/A | 15.1 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 196 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 201 B | 200 B | -1 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 208 B | 209 B | ⚠️ +1 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.03 kB | -3 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.11 kB | -1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | -1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[object  [...]

2019-11-25 19:34 UTC, Timer requested changes

2019-11-25 19:34 UTC, Timer commented on packages/next/build/webpack-config.ts
> +    url: 'native-url',
For consistency, let's do:
```suggestion
    // Replace: full URL polyfill with platform-based polyfill
    url: require.resolve('native-url'),
```

2019-11-25 19:34 UTC, Timer commented on test/integration/chunking/test/index.test.js
> +      .replace(/"static\\(.*?":?)/g, match => match.replace(/\\/g, '\\\\'))
Why was this changed?

2019-11-25 22:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 12.9s | 12.9s | ⚠️ +70ms |
| nodeModulesSize | 48.3 MB | 48.5 MB | ⚠️ +203 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a54bb7b4c.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..7b4c.js gzip | 7.37 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..4166349af.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..49af.js gzip | N/A | 7.35 kB | N/A |
| de003c3a9d30..64b97c6d1.js | N/A | 21.1 kB | N/A |
| de003c3a9d30..c6d1.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..76.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.16 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..8d.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.14 kB | N/A |
| de003c3a9d30..f3.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 197 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 208 B | ⚠️ +3 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.03 kB | -3 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.11 kB | -2 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.1 kB | ✓ |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -437,7 +437,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.5-canary.6";
+var version = "9.1.5-canary.5";
 exports.version = version;
 var props = data.props,
     err = data.err,
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -341,7 +341,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.5-canary.6";
+var version = "9.1.5-canary.5";
 exports.version = version;
 var {
   props,
```
</details>
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+  [...]

2019-11-25 22:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.1s | -21ms |
| nodeModulesSize | 48.3 MB | 48.6 MB | ⚠️ +215 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a54bb7b4c.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..7b4c.js gzip | 7.37 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..4086094cc.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..94cc.js gzip | N/A | 7.37 kB | N/A |
| de003c3a9d30..64b97c6d1.js | N/A | 21.1 kB | N/A |
| de003c3a9d30..c6d1.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..76.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.16 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..95.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.16 kB | N/A |
| de003c3a9d30..f3.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 197 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 210 B | ⚠️ +5 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | -1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.11 kB | ⚠️ +1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[object Arra [...]

2019-11-25 22:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.8s | ⚠️ +357ms |
| nodeModulesSize | 48.3 MB | 48.6 MB | ⚠️ +215 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a54bb7b4c.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..7b4c.js gzip | 7.37 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..4086094cc.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..94cc.js gzip | N/A | 7.37 kB | N/A |
| de003c3a9d30..64b97c6d1.js | N/A | 21.1 kB | N/A |
| de003c3a9d30..c6d1.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..76.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.16 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..95.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.16 kB | N/A |
| de003c3a9d30..f3.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 197 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 210 B | ⚠️ +5 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | -1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.11 kB | ⚠️ +1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[object  [...]

2019-11-25 22:57 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 15s | 15s | ⚠️ +38ms |
| nodeModulesSize | 48.3 MB | 48.6 MB | ⚠️ +215 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a54bb7b4c.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..7b4c.js gzip | 7.37 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..4086094cc.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..94cc.js gzip | N/A | 7.37 kB | N/A |
| de003c3a9d30..64b97c6d1.js | N/A | 21.1 kB | N/A |
| de003c3a9d30..c6d1.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..76.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.16 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..95.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.16 kB | N/A |
| de003c3a9d30..f3.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 197 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 210 B | ⚠️ +5 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | -1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.11 kB | ⚠️ +1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[object Array [...]

2019-11-25 23:36 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| buildDuration | 12.6s | 12.9s | ⚠️ +261ms |
| nodeModulesSize | 48.3 MB | 48.6 MB | ⚠️ +215 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.js | 17.9 kB | 17.9 kB | ✓ |
| main-HASH.js gzip | 6.33 kB | 6.33 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a54bb7b4c.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..7b4c.js gzip | 7.37 kB | N/A | N/A |
| 4952ddcd88e7..49d7903c2.js | 9.6 kB | 9.6 kB | ✓ |
| 4952ddcd88e7..03c2.js gzip | 3.76 kB | 3.76 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..a824c82eb.js | 28.3 kB | N/A | N/A |
| de003c3a9d30..82eb.js gzip | 10.7 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..4086094cc.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..94cc.js gzip | N/A | 7.37 kB | N/A |
| de003c3a9d30..64b97c6d1.js | N/A | 21.1 kB | N/A |
| de003c3a9d30..c6d1.js gzip | N/A | 8.15 kB | N/A |
| Overall change | 213 kB | 206 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..76.module.js | 21.3 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 8.16 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..95.module.js | N/A | 21.3 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 8.16 kB | N/A |
| de003c3a9d30..f3.module.js | N/A | 15 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 6.13 kB | N/A |
| Overall change | 197 kB | 189 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.75 kB | ⚠️ +1.64 kB |
| Overall change | 9.11 kB | 15.3 kB | ⚠️ +6.16 kB |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.js | 2.92 kB | 2.92 kB | ✓ |
| _app.js gzip | 1.32 kB | 1.32 kB | ✓ |
| _error.js | 13.2 kB | 13.2 kB | ✓ |
| _error.js gzip | 5.1 kB | 5.1 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.76 kB | 6.76 kB | ✓ |
| link.js gzip | 2.88 kB | 2.88 kB | ⚠️ +1 B |
| routerDirect.js | 413 B | 413 B | ✓ |
| routerDirect.js gzip | 285 B | 285 B | ✓ |
| withRouter.js | 423 B | 423 B | ✓ |
| withRouter.js gzip | 284 B | 284 B | ✓ |
| Overall change | 26 kB | 26 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.46 kB | -1 B |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| _buildManifest.js | 244 B | 244 B | ✓ |
| _buildManifest.js gzip | 200 B | 200 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 205 B | 210 B | ⚠️ +5 B |
| Overall change | 495 B | 495 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js native-url | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | -1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.12 kB | 1.12 kB | -1 B |
| withRouter.html | 4.59 kB | 4.59 kB | ✓ |
| withRouter.html gzip | 1.1 kB | 1.11 kB | ⚠️ +1 B |
| Overall change | 13.2 kB | 13.2 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>polyfills-HASH.js</strong></summary>

```diff
@@ -635,6 +635,497 @@ module.exports = shouldUseNative() ? Object.assign : function (target, source) {
 
 /***/ }),
 
+/***/ "T1qB":
+/***/ (function(module, exports, __webpack_require__) {
+
+/* WEBPACK VAR INJECTION */(function(global) {(function(global) {
+  /**
+   * Polyfill URLSearchParams
+   *
+   * Inspired from : https://github.com/WebReflection/url-search-params/blob/master/src/url-search-params.js
+   */
+
+  var checkIfIteratorIsSupported = function() {
+    try {
+      return !!Symbol.iterator;
+    } catch (error) {
+      return false;
+    }
+  };
+
+
+  var iteratorSupported = checkIfIteratorIsSupported();
+
+  var createIterator = function(items) {
+    var iterator = {
+      next: function() {
+        var value = items.shift();
+        return { done: value === void 0, value: value };
+      }
+    };
+
+    if (iteratorSupported) {
+      iterator[Symbol.iterator] = function() {
+        return iterator;
+      };
+    }
+
+    return iterator;
+  };
+
+  /**
+   * Search param name and values should be encoded according to https://url.spec.whatwg.org/#urlencoded-serializing
+   * encodeURIComponent() produces the same result except encoding spaces as `%20` instead of `+`.
+   */
+  var serializeParam = function(value) {
+    return encodeURIComponent(value).replace(/%20/g, '+');
+  };
+
+  var deserializeParam = function(value) {
+    return decodeURIComponent(String(value).replace(/\+/g, ' '));
+  };
+
+  var polyfillURLSearchParams = function() {
+
+    var URLSearchParams = function(searchString) {
+      Object.defineProperty(this, '_entries', { writable: true, value: {} });
+      var typeofSearchString = typeof searchString;
+
+      if (typeofSearchString === 'undefined') {
+        // do nothing
+      } else if (typeofSearchString === 'string') {
+        if (searchString !== '') {
+          this._fromString(searchString);
+        }
+      } else if (searchString instanceof URLSearchParams) {
+        var _this = this;
+        searchString.forEach(function(value, name) {
+          _this.append(name, value);
+        });
+      } else if ((searchString !== null) && (typeofSearchString === 'object')) {
+        if (Object.prototype.toString.call(searchString) === '[object Array]') {
+          for (var i = 0; i < searchString.length; i++) {
+            var entry = searchString[i];
+            if ((Object.prototype.toString.call(entry) === '[object  [...]

2019-11-26 04:09 UTC, Timer approved these changes

2019-11-26 04:10 UTC, merged