Integration test case for fetch alias
vercel/next.js pull request #9391
Opened 2019-11-12 23:44 UTC by janicklas-ralph

First draft of an integration test case for fetch alias. Love to hear feedback on the approach

2019-11-12 23:50 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 13.5s | 7.4s | -6.1s |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +618 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 38.4 kB | ⚠️ +23.6 kB |
| main-HASH.js gzip | 5.12 kB | 9.04 kB | ⚠️ +3.92 kB |
| webpack-HASH.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..14b571e4d.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..1e4d.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | N/A | N/A |
| 314e4c089430..480f.js gzip | 3.31 kB | N/A | N/A |
| commons.HASH.js | 10.4 kB | 26.2 kB | ⚠️ +15.8 kB |
| commons.HASH.js gzip | 3.91 kB | 7.01 kB | ⚠️ +3.11 kB |
| de003c3a9d30..39988e4af.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..e4af.js gzip | 12.3 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HASH.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..8d4cbea5c.js | N/A | 57.8 kB | N/A |
| 16b1a7225520..ea5c.js gzip | N/A | 15.5 kB | N/A |
| 314e4c089430..781ecd750.js | N/A | 22.1 kB | N/A |
| 314e4c089430..d750.js gzip | N/A | 5.88 kB | N/A |
| de003c3a9d30..24d8fff40.js | N/A | 109 kB | N/A |
| de003c3a9d30..ff40.js gzip | N/A | 30.7 kB | N/A |
| Overall change | 213 kB | 391 kB | ⚠️ +49.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 34.5 kB | ⚠️ +20.4 kB |
| main-HASH.module.js gzip | 5.31 kB | 9.43 kB | ⚠️ +4.13 kB |
| webpack-HASH.module.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH..dule.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..15.module.js | 16 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.17 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | N/A | N/A |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HA..dule.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..2f.module.js | N/A | 46 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 13 kB | N/A |
| 4952ddcd88e7..06.module.js | N/A | 30.2 kB | N/A |
| 4952ddcd88e7..dule.js gzip | N/A | 7.9 kB | N/A |
| de003c3a9d30..85.module.js | N/A | 71.6 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 20.9 kB | N/A |
| Overall change | 191 kB | 320 kB | ⚠️ +30.6 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 17.2 kB | ⚠️ +8.07 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.74 kB | ⚠️ +1.63 kB |
| Overall change | 9.11 kB | 17.2 kB | ⚠️ +8.07 kB |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 21 kB | ⚠️ +13.3 kB |
| _app.js gzip | 3.22 kB | 5.75 kB | ⚠️ +2.53 kB |
| _error.js | 14.9 kB | 38 kB | ⚠️ +23.1 kB |
| _error.js gzip | 5.57 kB | 9.58 kB | ⚠️ +4.01 kB |
| hooks.js | 1.92 kB | 5.54 kB | ⚠️ +3.63 kB |
| hooks.js gzip | 941 B | 1.61 kB | ⚠️ +671 B |
| index.js | 318 B | 666 B | ⚠️ +348 B |
| index.js gzip | 222 B | 350 B | ⚠️ +128 B |
| link.js | 4.05 kB | 11.4 kB | ⚠️ +7.33 kB |
| link.js gzip | 1.81 kB | 3.55 kB | ⚠️ +1.74 kB |
| routerDirect.js | 411 B | 1.33 kB | ⚠️ +916 B |
| routerDirect.js gzip | 283 B | 523 B | ⚠️ +240 B |
| withRouter.js | 421 B | 1.35 kB | ⚠️ +927 B |
| withRouter.js gzip | 282 B | 510 B | ⚠️ +228 B |
| Overall change | 29.7 kB | 79.3 kB | ⚠️ +49.5 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 4.33 kB | ⚠️ +2.79 kB |
| _app.module.js gzip | 759 B | 1.49 kB | ⚠️ +727 B |
| _error.module.js | 10.5 kB | 26.6 kB | ⚠️ +16.1 kB |
| _error.module.js gzip | 4.26 kB | 7.36 kB | ⚠️ +3.1 kB |
| hooks.module.js | 677 B | 1.79 kB | ⚠️ +1.11 kB |
| hooks.module.js gzip | 384 B | 620 B | ⚠️ +236 B |
| index.module.js | 292 B | 624 B | ⚠️ +332 B |
| index.module.js gzip | 223 B | 341 B | ⚠️ +118 B |
| link.module.js | 5.49 kB | 15.9 kB | ⚠️ +10.4 kB |
| link.module.js gzip | 2.47 kB | 4.8 kB | ⚠️ +2.33 kB |
| routerDirect.module.js | 399 B | 1.31 kB | ⚠️ +910 B |
| routerDirect..dule.js gzip | 285 B | 525 B | ⚠️ +240 B |
| withRouter.module.js | 409 B | 1.33 kB | ⚠️ +921 B |
| withRouter.m..dule.js gzip | 282 B | 511 B | ⚠️ +229 B |
| Overall change | 19.3 kB | 51.9 kB | ⚠️ +32.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 261 B | ⚠️ +1 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 210 B | 210 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.02 kB | ⚠️ +1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ⚠️ +2 B |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | -1 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 13.8s | 7.9s | -6s |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +618 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 38.4 kB | ⚠️ +23.6 kB |
| main-HASH.js gzip | 5.12 kB | 9.04 kB | ⚠️ +3.92 kB |
| webpack-HASH.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..14b571e4d.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..1e4d.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | N/A | N/A |
| 314e4c089430..480f.js gzip | 3.31 kB | N/A | N/A |
| commons.HASH.js | 10.4 kB | 26.2 kB | ⚠️ +15.8 kB |
| commons.HASH.js gzip | 3.91 kB | 7.01 kB | ⚠️ +3.11 kB |
| de003c3a9d30..39988e4af.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..e4af.js gzip | 12.3 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HASH.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..8d4cbea5c.js | N/A | 57.8 kB | N/A |
| 16b1a7225520..ea5c.js gzip | N/A | 15.5 kB | N/A |
| 314e4c089430..781ecd750.js | N/A | 22.1 kB | N/A |
| 314e4c089430..d750.js gzip | N/A | 5.88 kB | N/A |
| de003c3a9d30..24d8fff40.js | N/A | 109 kB | N/A |
| de003c3a9d30..ff40.js gzip | N/A | 30.7 kB | N/A |
| Overall change | 213 kB | 391 kB | ⚠️ +49.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpac [...]

2019-11-12 23:58 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 14s | 7.8s | -6.2s |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +618 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 38.4 kB | ⚠️ +23.6 kB |
| main-HASH.js gzip | 5.12 kB | 9.04 kB | ⚠️ +3.92 kB |
| webpack-HASH.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..14b571e4d.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..1e4d.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | N/A | N/A |
| 314e4c089430..480f.js gzip | 3.31 kB | N/A | N/A |
| commons.HASH.js | 10.4 kB | 26.2 kB | ⚠️ +15.8 kB |
| commons.HASH.js gzip | 3.91 kB | 7.01 kB | ⚠️ +3.11 kB |
| de003c3a9d30..39988e4af.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..e4af.js gzip | 12.3 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HASH.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..8d4cbea5c.js | N/A | 57.8 kB | N/A |
| 16b1a7225520..ea5c.js gzip | N/A | 15.5 kB | N/A |
| 314e4c089430..781ecd750.js | N/A | 22.1 kB | N/A |
| 314e4c089430..d750.js gzip | N/A | 5.88 kB | N/A |
| de003c3a9d30..24d8fff40.js | N/A | 109 kB | N/A |
| de003c3a9d30..ff40.js gzip | N/A | 30.7 kB | N/A |
| Overall change | 213 kB | 391 kB | ⚠️ +49.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 34.5 kB | ⚠️ +20.4 kB |
| main-HASH.module.js gzip | 5.31 kB | 9.43 kB | ⚠️ +4.13 kB |
| webpack-HASH.module.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH..dule.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..15.module.js | 16 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.17 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | N/A | N/A |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | N/A | N/A |
| de003c3a9d30..36.module.js | 22.2 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 8.71 kB | N/A | N/A |
| framework.HASH.module.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HA..dule.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..2f.module.js | N/A | 46 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 13 kB | N/A |
| 4952ddcd88e7..06.module.js | N/A | 30.2 kB | N/A |
| 4952ddcd88e7..dule.js gzip | N/A | 7.9 kB | N/A |
| de003c3a9d30..85.module.js | N/A | 71.6 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 20.9 kB | N/A |
| Overall change | 191 kB | 320 kB | ⚠️ +30.6 kB |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 17.2 kB | ⚠️ +8.07 kB |
| polyfills-HASH.js gzip | 3.11 kB | 4.74 kB | ⚠️ +1.63 kB |
| Overall change | 9.11 kB | 17.2 kB | ⚠️ +8.07 kB |

</details>

<details>
<summary><strong>Client Pages</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 21 kB | ⚠️ +13.3 kB |
| _app.js gzip | 3.22 kB | 5.75 kB | ⚠️ +2.53 kB |
| _error.js | 14.9 kB | 38 kB | ⚠️ +23.1 kB |
| _error.js gzip | 5.57 kB | 9.58 kB | ⚠️ +4.01 kB |
| hooks.js | 1.92 kB | 5.54 kB | ⚠️ +3.63 kB |
| hooks.js gzip | 941 B | 1.61 kB | ⚠️ +671 B |
| index.js | 318 B | 666 B | ⚠️ +348 B |
| index.js gzip | 222 B | 350 B | ⚠️ +128 B |
| link.js | 4.05 kB | 11.4 kB | ⚠️ +7.33 kB |
| link.js gzip | 1.81 kB | 3.55 kB | ⚠️ +1.74 kB |
| routerDirect.js | 411 B | 1.33 kB | ⚠️ +916 B |
| routerDirect.js gzip | 283 B | 523 B | ⚠️ +240 B |
| withRouter.js | 421 B | 1.35 kB | ⚠️ +927 B |
| withRouter.js gzip | 282 B | 510 B | ⚠️ +228 B |
| Overall change | 29.7 kB | 79.3 kB | ⚠️ +49.5 kB |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 4.33 kB | ⚠️ +2.79 kB |
| _app.module.js gzip | 759 B | 1.49 kB | ⚠️ +727 B |
| _error.module.js | 10.5 kB | 26.6 kB | ⚠️ +16.1 kB |
| _error.module.js gzip | 4.26 kB | 7.36 kB | ⚠️ +3.1 kB |
| hooks.module.js | 677 B | 1.79 kB | ⚠️ +1.11 kB |
| hooks.module.js gzip | 384 B | 620 B | ⚠️ +236 B |
| index.module.js | 292 B | 624 B | ⚠️ +332 B |
| index.module.js gzip | 223 B | 341 B | ⚠️ +118 B |
| link.module.js | 5.49 kB | 15.9 kB | ⚠️ +10.4 kB |
| link.module.js gzip | 2.47 kB | 4.8 kB | ⚠️ +2.33 kB |
| routerDirect.module.js | 399 B | 1.31 kB | ⚠️ +910 B |
| routerDirect..dule.js gzip | 285 B | 525 B | ⚠️ +240 B |
| withRouter.module.js | 409 B | 1.33 kB | ⚠️ +921 B |
| withRouter.m..dule.js gzip | 282 B | 511 B | ⚠️ +229 B |
| Overall change | 19.3 kB | 51.9 kB | ⚠️ +32.6 kB |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 261 B | ⚠️ +1 B |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 210 B | 210 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.02 kB | ⚠️ +1 B |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ⚠️ +2 B |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | -1 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 14.2s | 8s | -6.2s |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +618 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.9 kB | 38.4 kB | ⚠️ +23.6 kB |
| main-HASH.js gzip | 5.12 kB | 9.04 kB | ⚠️ +3.92 kB |
| webpack-HASH.js | 1.53 kB | 6.42 kB | ⚠️ +4.89 kB |
| webpack-HASH.js gzip | 746 B | 1.71 kB | ⚠️ +960 B |
| 16b1a7225520..14b571e4d.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..1e4d.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | N/A | N/A |
| 314e4c089430..480f.js gzip | 3.31 kB | N/A | N/A |
| commons.HASH.js | 10.4 kB | 26.2 kB | ⚠️ +15.8 kB |
| commons.HASH.js gzip | 3.91 kB | 7.01 kB | ⚠️ +3.11 kB |
| de003c3a9d30..39988e4af.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..e4af.js gzip | 12.3 kB | N/A | N/A |
| framework.HASH.js | 125 kB | 131 kB | ⚠️ +5.37 kB |
| framework.HASH.js gzip | 39.4 kB | 41 kB | ⚠️ +1.65 kB |
| 16b1a7225520..8d4cbea5c.js | N/A | 57.8 kB | N/A |
| 16b1a7225520..ea5c.js gzip | N/A | 15.5 kB | N/A |
| 314e4c089430..781ecd750.js | N/A | 22.1 kB | N/A |
| 314e4c089430..d750.js gzip | N/A | 5.88 kB | N/A |
| de003c3a9d30..24d8fff40.js | N/A | 109 kB | N/A |
| de003c3a9d30..ff40.js gzip | N/A | 30.7 kB | N/A |
| Overall change | 213 kB | 391 kB | ⚠️ +49.6 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, [...]

2019-11-13 02:54 UTC, Timer requested changes

2019-11-13 02:54 UTC, Timer commented on packages/next/build/webpack-config.ts
> +    'whatwg-fetch': path.join(
Should this still terminate?

```suggestion
    'whatwg-fetch$': path.join(
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +  Headers: self.Headers.bind(self),
Do these need to be bound? We're not decorating any properties on them.
```suggestion
  Headers: self.Headers,
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +  Request: self.Request.bind(self),
```suggestion
  Request: self.Request,
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +  Response: self.Response.bind(self),
```suggestion
  Response: self.Response,
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +  fetch: self.fetch.bind(self),
```suggestion
  fetch: self.fetch,
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +const fetch = {
This is a confusing name IMO, as it's a reserved ("confusing") global.

Let's rename?

```suggestion
const stub = {
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +module.exports = fetch
```suggestion
module.exports = stub
```

2019-11-13 02:54 UTC, Timer commented on packages/next/build/polyfills/fetch/whatwg-fetch.js
> +module.exports.default = fetch
Do we need the default variant here? The real package doesn't expose any default. We may even be able to make this whole file ESM exports instead.

2019-11-13 02:54 UTC, Timer commented on packages/next/build/webpack-config.ts
> +      minimize: false, //!(dev || isServer),
Seems like this needs undone.

2019-11-13 18:36 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 12.1s | 11.8s | -347ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +1.07 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.9 kB | ⚠️ +12 B |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..45d9.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..14b571e4d.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..1e4d.js gzip | N/A | 7.28 kB | N/A |
| Overall change | 213 kB | 213 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +12 B |
| main-HASH.module.js gzip | 5.3 kB | 5.31 kB | ⚠️ +9 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.17 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..15.module.js | N/A | 16 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.17 kB | N/A |
| Overall change | 191 kB | 191 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 260 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 210 B | ⚠️ +1 B |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ⚠️ +2 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -326,7 +326,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -402,7 +402,7 @@ function (_react$default$Compon) {
       // If it's a dynamic route or has a querystring
 
 
-      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
         // update query on mount for exported pages
         router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2["default"])({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
           // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -341,7 +341,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var {
   props,
@@ -403,7 +403,7 @@ class Container extends _react.default.Component {
     // If it's a dynamic route or has a querystring
 
 
-    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
       // update query on mount for exported pages
       router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2.default)({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
         // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.7ecd57e5cdc5ea0af8ba.js","static\u002Fchunks\u002F314e4c089430eb8cdc865a8a097be397fffdf2f3.dabd6bf1b89781ecd750.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a7 [...]

2019-11-13 18:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 13.9s | 13.5s | -369ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +973 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.9 kB | ⚠️ +12 B |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..45d9.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..14b571e4d.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..1e4d.js gzip | N/A | 7.28 kB | N/A |
| Overall change | 213 kB | 213 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +12 B |
| main-HASH.module.js gzip | 5.3 kB | 5.31 kB | ⚠️ +9 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.17 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..15.module.js | N/A | 16 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.17 kB | N/A |
| Overall change | 191 kB | 191 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 260 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 210 B | ⚠️ +1 B |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ⚠️ +2 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -326,7 +326,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -402,7 +402,7 @@ function (_react$default$Compon) {
       // If it's a dynamic route or has a querystring
 
 
-      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
         // update query on mount for exported pages
         router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2["default"])({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
           // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -341,7 +341,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var {
   props,
@@ -403,7 +403,7 @@ class Container extends _react.default.Component {
     // If it's a dynamic route or has a querystring
 
 
-    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
       // update query on mount for exported pages
       router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2.default)({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
         // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.7ecd57e5cdc5ea0af8ba.js","static\u002Fchunks\u002F314e4c089430eb8cdc865a8a097be397fffdf2f3.dabd6bf1b89781ecd750.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a722 [...]

2019-11-15 06:09 UTC, Timer approved these changes
LGTM!

2019-11-15 06:15 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 14.5s | 14.9s | ⚠️ +430ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +496 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.9 kB | ⚠️ +12 B |
| main-HASH.js gzip | 5.11 kB | 5.12 kB | ⚠️ +9 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | N/A | N/A |
| 16b1a7225520..45d9.js gzip | 7.28 kB | N/A | N/A |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..14b571e4d.js | N/A | 19.8 kB | N/A |
| 16b1a7225520..1e4d.js gzip | N/A | 7.28 kB | N/A |
| Overall change | 213 kB | 213 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ⚠️ +12 B |
| main-HASH.module.js gzip | 5.3 kB | 5.31 kB | ⚠️ +9 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | N/A | N/A |
| 16b1a7225520..dule.js gzip | 6.17 kB | N/A | N/A |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| 16b1a7225520..15.module.js | N/A | 16 kB | N/A |
| 16b1a7225520..dule.js gzip | N/A | 6.17 kB | N/A |
| Overall change | 191 kB | 191 kB | ⚠️ +12 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 260 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 210 B | ⚠️ +1 B |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ⚠️ +2 B |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -326,7 +326,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -402,7 +402,7 @@ function (_react$default$Compon) {
       // If it's a dynamic route or has a querystring
 
 
-      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+      if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
         // update query on mount for exported pages
         router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2["default"])({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
           // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -341,7 +341,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.4-canary.4";
+var version = "9.1.4-canary.3";
 exports.version = version;
 var {
   props,
@@ -403,7 +403,7 @@ class Container extends _react.default.Component {
     // If it's a dynamic route or has a querystring
 
 
-    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search)) {
+    if (data.nextExport && ((0, _isDynamic.isDynamicRoute)(router.pathname) || location.search || data.skeleton)) {
       // update query on mount for exported pages
       router.replace(router.pathname + '?' + (0, _querystring.stringify)((0, _extends2.default)({}, router.query, {}, (0, _querystring.parse)(location.search.substr(1)))), asPath, {
         // WARNING: `_h` is an internal option for handing Next.js
```
</details>
<details>
<summary>Diff for <strong>_buildManifest.js</strong></summary>

```diff
@@ -1 +1 @@
-self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a72255206b7853bf6603dc58ec83de39b142.7ecd57e5cdc5ea0af8ba.js","static\u002Fchunks\u002F314e4c089430eb8cdc865a8a097be397fffdf2f3.dabd6bf1b89781ecd750.js"));self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB()
\ No newline at end of file
+self.__BUILD_MANIFEST = (function(a,b){return {"/_error":[b],"/link":[a,b],"/routerDirect":[a],"/withRouter":[a]}}("static\u002Fchunks\u002F16b1a [...]

2019-11-15 06:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.7s | ⚠️ +229ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +431 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..45d9.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 260 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +96ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +431 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..45d9.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222  [...]

2019-11-15 06:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 13s | 12.8s | -179ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +431 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..45d9.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 4.05 kB | 4.05 kB | ✓ |
| link.js gzip | 1.81 kB | 1.81 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 29.7 kB | 29.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 759 B | 759 B | ✓ |
| _error.module.js | 10.5 kB | 10.5 kB | ✓ |
| _error.module.js gzip | 4.26 kB | 4.26 kB | ✓ |
| hooks.module.js | 677 B | 677 B | ✓ |
| hooks.module.js gzip | 384 B | 384 B | ✓ |
| index.module.js | 292 B | 292 B | ✓ |
| index.module.js gzip | 223 B | 223 B | ✓ |
| link.module.js | 5.49 kB | 5.49 kB | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect.module.js | 399 B | 399 B | ✓ |
| routerDirect..dule.js gzip | 285 B | 285 B | ✓ |
| withRouter.module.js | 409 B | 409 B | ✓ |
| withRouter.m..dule.js gzip | 282 B | 282 B | ✓ |
| Overall change | 19.3 kB | 19.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _buildManifest.js | 353 B | 353 B | ✓ |
| _buildManifest.js gzip | 260 B | 260 B | ✓ |
| _buildManifest.module.js | 251 B | 251 B | ✓ |
| _buildManife..dule.js gzip | 209 B | 209 B | ✓ |
| Overall change | 604 B | 604 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| index.html | 3.9 kB | 3.9 kB | ✓ |
| index.html gzip | 1.01 kB | 1.01 kB | ✓ |
| link.html | 4.58 kB | 4.58 kB | ✓ |
| link.html gzip | 1.14 kB | 1.14 kB | ✓ |
| withRouter.html | 4.43 kB | 4.43 kB | ✓ |
| withRouter.html gzip | 1.08 kB | 1.08 kB | ✓ |
| Overall change | 12.9 kB | 12.9 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| buildDuration | 14s | 14.1s | ⚠️ +146ms |
| nodeModulesSize | 48.8 MB | 48.8 MB | ⚠️ +431 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.js | 14.8 kB | 14.8 kB | ✓ |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..a6fc245d9.js | 19.8 kB | 19.8 kB | ✓ |
| 16b1a7225520..45d9.js gzip | 7.28 kB | 7.28 kB | ✓ |
| 314e4c089430..de6eb480f.js | 7.9 kB | 7.9 kB | ✓ |
| 314e4c089430..480f.js gzip | 3.31 kB | 3.31 kB | ✓ |
| commons.HASH.js | 10.4 kB | 10.4 kB | ✓ |
| commons.HASH.js gzip | 3.91 kB | 3.91 kB | ✓ |
| de003c3a9d30..39988e4af.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..e4af.js gzip | 12.3 kB | 12.3 kB | ✓ |
| framework.HASH.js | 125 kB | 125 kB | ✓ |
| framework.HASH.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 213 kB | 213 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| main-HASH.module.js | 14.1 kB | 14.1 kB | ✓ |
| main-HASH.module.js gzip | 5.3 kB | 5.3 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 16b1a7225520..85.module.js | 16 kB | 16 kB | ✓ |
| 16b1a7225520..dule.js gzip | 6.17 kB | 6.17 kB | ✓ |
| 4952ddcd88e7..cc.module.js | 11.9 kB | 11.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 4.43 kB | 4.43 kB | ✓ |
| de003c3a9d30..36.module.js | 22.2 kB | 22.2 kB | ✓ |
| de003c3a9d30..dule.js gzip | 8.71 kB | 8.71 kB | ✓ |
| framework.HASH.module.js | 125 kB | 125 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 191 kB | 191 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| polyfills-HASH.js | 9.11 kB | 9.11 kB | ✓ |
| polyfills-HASH.js gzip | 3.11 kB | 3.11 kB | ✓ |
| Overall change | 9.11 kB | 9.11 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | janicklas-ralph/next.js polyfill-fetch | Change |
| - | - | - | - |
| _app.js | 7.71 kB | 7.71 kB | ✓ |
| _app.js gzip | 3.22 kB | 3.22 kB | ✓ |
| _error.js | 14.9 kB | 14.9 kB | ✓ |
| _error.js gzip | 5.57 kB | 5.57 kB | ✓ |
| hooks.js | 1.92 kB | 1.92 kB | ✓ |
| hooks.js gzip | 941 B | 941 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B |  [...]

2019-11-15 06:47 UTC, merged