Allow parsed url to be passed down
vercel/next.js pull request #950
Opened 2017-02-01 21:22 UTC by timneutkens

Fixes #947

2017-02-01 21:51 UTC, rauchg commented
Something I thought of: we should re-parse qs if people didn't pass `true` to `parse` (ie: query is not an object)

2017-02-01 22:08 UTC, timneutkens commented
@rauchg added 👍

2017-02-02 02:55 UTC, arunoda requested changes

2017-02-02 02:55 UTC, arunoda commented on server/index.js
> +    return (req, res, url) => {
I like to see `url` as `parsedUrl` here and everywhere else.

2017-02-02 02:55 UTC, arunoda commented on server/router.js
> +  match (req, res, url = parse(req.url)) {
We don't need to parse the url here.
`.match()` is always called with a parsedUrl.

2017-02-02 02:55 UTC, arunoda commented on server/router.js
> +          return r.fn(req, res, { ...params, url })
I don't like keeping parsedUrl inside the `params`. Make it the 4th argument.

2017-02-02 06:08 UTC, timneutkens commented on server/index.js
> +    return (req, res, url) => {
Done 👍

2017-02-02 06:08 UTC, timneutkens commented on server/router.js
> +  match (req, res, url = parse(req.url)) {
True, removed.

2017-02-02 06:09 UTC, timneutkens commented on server/router.js
> +          return r.fn(req, res, { ...params, url })
Added as fourth argument.

2017-02-02 06:51 UTC, arunoda approved these changes

2017-02-02 06:51 UTC, merged

2017-02-02 06:51 UTC, arunoda commented
Thanks @timneutkens