[with-react-intl] Fix message extraction script on consecutive builds
vercel/next.js pull request #9788
Opened 2019-12-19 17:15 UTC by lostfictions

I wasn't aware, but it seems like Next doesn't do a fresh build every time `next build` is run -- unchanged files that have already passed through Babel are skipped on subsequent runs. Unfortunately, that breaks message extraction (via [babel-plugin-react-intl](https://github.com/formatjs/formatjs/tree/master/packages/babel-plugin-react-intl)) in this example: on subsequent runs it'll fail to extract messages in unchanged files, leaving the list of strings shorter than it should be (or just completely empty)!

This PR fixes that case by simply removing the `.next` directory before building. It also relaxes the requirement in the helper script forbidding duplicate message IDs -- they're allowed if their corresponding messages are identical, which is the same rule enforced by babel-plugin-react-intl on a per-file basis.

2019-12-19 17:20 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.4s | -35ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.js | 18.5 kB | 18.5 kB | ✓ |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..1db6754d3.js | 12 kB | 12 kB | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js | 10.9 kB | 10.9 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..7d55a2235.js | 38.3 kB | 38.3 kB | ✓ |
| de003c3a9d30..2235.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js | 126 kB | 126 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 207 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.module.js | 14.5 kB | 14.5 kB | ✓ |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..b9.module.js | 14.9 kB | 14.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..a0.module.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HASH.module.js | 126 kB | 126 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| polyfills-HASH.js | 15.3 kB | 15.3 kB | ✓ |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.js | 2.94 kB | 2.94 kB | ✓ |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js | 10.4 kB | 10.4 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js | 1.44 kB | 1.44 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.77 kB | 6.77 kB | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 22.7 kB | 22.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js | 7.35 kB | 7.35 kB | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js | 651 B | 651 B | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js | 276 B | 276 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js | 5.45 kB | 5.45 kB | ✓ |
| link.module.js gzip | 2.46 kB | 2.46 kB | ✓ |
| routerDirect.module.js | 383 B | 383 B | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.module.js | 394 B | 394 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 16 kB | 16 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html | 4.11 kB | 4.11 kB | ✓ |
| link.html gzip | 1.05 kB | 1.05 kB | ✓ |
| withRouter.html | 4.12 kB | 4.12 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 12.3 kB | 12.3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.8s | ⚠️ +259ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.js | 18.5 kB | 18.5 kB | ✓ |
| main-HASH.js gzip | 6.5 kB | 6.5 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..1db6754d3.js | 12 kB | 12 kB | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js | 10.9 kB | 10.9 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..7d55a2235.js | 38.3 kB | 38.3 kB | ✓ |
| de003c3a9d30..2235.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js | 126 kB | 126 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 207 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.module.js | 14.5 kB | 14.5 kB | ✓ |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..b9.module.js | 14.9 kB | 14.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..a0.module.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HASH.module.js | 126 kB | 126 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| polyfills-HASH.js | 15.3 kB | 15.3 kB | ✓ |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.js | 2.94 kB | 2.94 kB | ✓ |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js | 10.4 kB | 10.4 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js | 1.44 kB | 1.44 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.77 kB | 6.77 kB | ✓ |
| link.js gzip | 2.89 kB | 2.89 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 22.7 kB | 22.7 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.mod [...]

2019-12-23 12:18 UTC, Timer requested changes
This will result in very slow builds and should be solved in a different way. 🤔

2019-12-23 20:21 UTC, lostfictions commented
@Timer Looks like the formatjs org recently added a cli to do extraction (via a babel pass using the same plugin), so I've switched this example over to that. Better?

2019-12-23 20:24 UTC, Timer approved these changes
Much better, thanks!

2019-12-23 20:25 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.1s | -272ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | -895 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.js | 18.6 kB | 18.5 kB | -59 B |
| main-HASH.js gzip | 6.52 kB | 6.5 kB | -19 B |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..1db6754d3.js | 12 kB | 12 kB | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js | 10.9 kB | 10.9 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..17cdc0d60.js | 38.3 kB | N/A | N/A |
| de003c3a9d30..0d60.js gzip | 13.9 kB | N/A | N/A |
| framework.HASH.js | 126 kB | 126 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| de003c3a9d30..7d55a2235.js | N/A | 38.3 kB | N/A |
| de003c3a9d30..2235.js gzip | N/A | 13.9 kB | N/A |
| Overall change | 207 kB | 207 kB | -59 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.module.js | 14.5 kB | 14.5 kB | -56 B |
| main-HASH.module.js gzip | 5.44 kB | 5.42 kB | -18 B |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..b9.module.js | 14.9 kB | 14.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..e3.module.js | 33.1 kB | N/A | N/A |
| de003c3a9d30..dule.js gzip | 12.5 kB | N/A | N/A |
| framework.HASH.module.js | 126 kB | 126 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| de003c3a9d30..a0.module.js | N/A | 33.1 kB | N/A |
| de003c3a9d30..dule.js gzip | N/A | 12.5 kB | N/A |
| Overall change | 190 kB | 190 kB | -56 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| polyfills-HASH.js | 15.3 kB | 15.3 kB | ✓ |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.js | 2.94 kB | 2.94 kB | ✓ |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js | 10.4 kB | 10.4 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js | 1.44 kB | 1.44 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.88 kB | 6.77 kB | -109 B |
| link.js gzip | 2.93 kB | 2.89 kB | -37 B |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 22.8 kB | 22.7 kB | -109 B |

</details>

<details>
<summary><strong>Client Pages Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js | 7.35 kB | 7.35 kB | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js | 651 B | 651 B | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js | 276 B | 276 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js | 5.54 kB | 5.45 kB | -89 B |
| link.module.js gzip | 2.49 kB | 2.46 kB | -35 B |
| routerDirect.module.js | 383 B | 383 B | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.module.js | 394 B | 394 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 16.1 kB | 16 kB | -89 B |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ⚠️ +1 B |
| link.html | 4.11 kB | 4.11 kB | ✓ |
| link.html gzip | 1.04 kB | 1.05 kB | ⚠️ +1 B |
| withRouter.html | 4.12 kB | 4.12 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 12.3 kB | 12.3 kB | ✓ |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -437,7 +437,7 @@ if (!window.Promise) {
 
 var data = JSON.parse(document.getElementById('__NEXT_DATA__').textContent);
 window.__NEXT_DATA__ = data;
-var version = "9.1.7-canary.2";
+var version = "9.1.7-canary.0";
 exports.version = version;
 var props = data.props,
     err = data.err,
@@ -1428,7 +1428,6 @@ function () {
     this.buildId = buildId;
     this.assetPrefix = assetPrefix;
     this.pageCache = {};
-    this.prefetched = {};
     this.pageRegisterEvents = (0, _mitt["default"])();
     this.loadingRoutes = {};
 
@@ -1652,7 +1651,7 @@ function () {
                 url = _this2.assetPrefix + (isDependency ? route : "/_next/static/" + encodeURIComponent(_this2.buildId) + "/pages" + encodeURI(scriptRoute)); // n.b. If preload is not supported, we fall back to `loadPage` which has
                 // its own deduping mechanism.
 
-                if (!(_this2.prefetched[route] || document.querySelector("link[rel=\"" + prefetchOrPreload + "\"][href^=\"" + url + "\"], script[data-next-page=\"" + route + "\"]"))) {
+                if (!document.querySelector("link[rel=\"" + prefetchOrPreload + "\"][href^=\"" + url + "\"], script[data-next-page=\"" + route + "\"]")) {
                   _context2.next = 6;
                   break;
                 }
@@ -1660,63 +1659,61 @@ function () {
                 return _context2.abrupt("return");
 
               case 6:
-                _this2.prefetched[route] = true; // Inspired by quicklink, license: https://github.com/GoogleChromeLabs/quicklink/blob/master/LICENSE
-
                 if (!(cn = navigator.connection)) {
-                  _context2.next = 10;
+                  _context2.next = 9;
                   break;
                 }
 
                 if (!((cn.effectiveType || '').indexOf('2g') !== -1 || cn.saveData)) {
-                  _context2.next = 10;
+                  _context2.next = 9;
                   break;
                 }
 
                 return _context2.abrupt("return");
 
-              case 10:
+              case 9:
                 if (!( true && !isDependency)) {
-                  _context2.next = 16;
+                  _context2.next = 15;
                   break;
                 }
 
                 ;
-                _context2.next = 14;
+                _context2.next = 13;
                 return _this2.getDependencies(route);
 
-              case 14:
+              case 13:
                 _context2.t0 = function (url) {
                   _this2.prefetch(url, true);
                 };
 
                 _context2.sent.forEach(_context2.t0);
 
-              case 16:
+              case 15:
                 if (!hasPreload) {
-                  _context2.next = 19;
+               [...]

2019-12-23 20:30 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| buildDuration | 13.3s | 13.3s | ⚠️ +61ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.js | 18.6 kB | 18.6 kB | ✓ |
| main-HASH.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..1db6754d3.js | 12 kB | 12 kB | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js | 10.9 kB | 10.9 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..17cdc0d60.js | 38.3 kB | 38.3 kB | ✓ |
| de003c3a9d30..0d60.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js | 126 kB | 126 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 207 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.module.js | 14.5 kB | 14.5 kB | ✓ |
| main-HASH.module.js gzip | 5.44 kB | 5.44 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..b9.module.js | 14.9 kB | 14.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..e3.module.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HASH.module.js | 126 kB | 126 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| polyfills-HASH.js | 15.3 kB | 15.3 kB | ✓ |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.js | 2.94 kB | 2.94 kB | ✓ |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js | 10.4 kB | 10.4 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js | 1.44 kB | 1.44 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.88 kB | 6.88 kB | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.module.js | 1.54 kB | 1.54 kB | ✓ |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js | 7.35 kB | 7.35 kB | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js | 651 B | 651 B | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js | 276 B | 276 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js | 5.54 kB | 5.54 kB | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect.module.js | 383 B | 383 B | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.module.js | 394 B | 394 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 16.1 kB | 16.1 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _buildManifest.js | 81 B | 81 B | ✓ |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManifest.module.js | 81 B | 81 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 162 B | 162 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| index.html | 4.06 kB | 4.06 kB | ✓ |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html | 4.11 kB | 4.11 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | ✓ |
| withRouter.html | 4.12 kB | 4.12 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 12.3 kB | 12.3 kB | ✓ |

</details>

</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| buildDuration | 13.6s | 13.7s | ⚠️ +71ms |
| nodeModulesSize | 48.7 MB | 48.7 MB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.js | 18.6 kB | 18.6 kB | ✓ |
| main-HASH.js gzip | 6.52 kB | 6.52 kB | ✓ |
| webpack-HASH.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..1db6754d3.js | 12 kB | 12 kB | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js | 10.9 kB | 10.9 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..17cdc0d60.js | 38.3 kB | 38.3 kB | ✓ |
| de003c3a9d30..0d60.js gzip | 13.9 kB | 13.9 kB | ✓ |
| framework.HASH.js | 126 kB | 126 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 207 kB | 207 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| main-HASH.module.js | 14.5 kB | 14.5 kB | ✓ |
| main-HASH.module.js gzip | 5.44 kB | 5.44 kB | ✓ |
| webpack-HASH.module.js | 1.53 kB | 1.53 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..b9.module.js | 14.9 kB | 14.9 kB | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..e3.module.js | 33.1 kB | 33.1 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HASH.module.js | 126 kB | 126 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 190 kB | 190 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| polyfills-HASH.js | 15.3 kB | 15.3 kB | ✓ |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 15.3 kB | 15.3 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
| _app.js | 2.94 kB | 2.94 kB | ✓ |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js | 10.4 kB | 10.4 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js | 1.44 kB | 1.44 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js | 318 B | 318 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js | 6.88 kB | 6.88 kB | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js | 411 B | 411 B | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js | 421 B | 421 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 22.8 kB | 22.8 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary | lostfictions/next.js fix-react-intl-example | Change |
| - | - | - | - |
 [...]

2019-12-23 20:32 UTC, merged