Enable New CSS Support by Default
vercel/next.js pull request #9927
Opened 2020-01-03 20:26 UTC by Timer

This enables the new CSS support in Next.js by default.

2020-01-03 20:33 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.8s | 12.8s | -1.1s |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.43 kB | 6.43 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.41 kB | 5.41 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 3.11 kB | 3.11 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.1s | 13.2s | ⚠️ +131ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.43 kB | 6.43 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.41 kB | 5.41 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 k [...]

2020-01-03 20:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.3s | ⚠️ +442ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.43 kB | 6.43 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.41 kB | 5.41 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 3.11 kB | 3.11 kB | ⚠️ +1 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.4s | 13.8s | ⚠️ +372ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.43 kB | 6.43 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.41 kB | 5.41 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2. [...]

2020-01-03 20:44 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 12.4s | 13s | ⚠️ +533ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | -1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | -1 B |
| Overall change | 3.11 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 12.9s | 13.4s | ⚠️ +456ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzi [...]

2020-01-03 20:59 UTC, ijjk approved these changes

2020-01-03 21:03 UTC, ijjk requested changes
Looks like me might need to update tests 🤔

2020-01-03 21:04 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 11.8s | 12s | ⚠️ +200ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | -1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | -1 B |
| Overall change | 3.11 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +82ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip [...]

2020-01-03 21:07 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.7s | 13.8s | ⚠️ +140ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | ✓ |
| link.html gzip | 1.04 kB | 1.04 kB | -1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | -1 B |
| Overall change | 3.11 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 14s | 14.7s | ⚠️ +650ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.44 kB | 6.44 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.42 kB | 5.42 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzi [...]

2020-01-03 21:13 UTC, ijjk submitted a review, later dismissed
Looks like we need to add `!this.context._documentProps.inAmpMode &&` to [here](https://github.com/zeit/next.js/blob/3707701cc9e9d03016dfc830d2d80a4de8517718/packages/next/pages/_document.tsx#L398) since it's not allowed in AMP mode

2020-01-03 21:39 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14.8s | ⚠️ +876ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.45 kB | 6.45 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.43 kB | 5.43 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | -3 B |
| link.html gzip | 1.04 kB | 1.04 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ✓ |
| Overall change | 3.12 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 14.5s | 15.6s | ⚠️ +1s |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.45 kB | 6.45 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.43 kB | 5.43 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.7 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js g [...]

2020-01-04 12:14 UTC, timneutkens approved these changes

2020-01-09 14:34 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 11.5s | 11.7s | ⚠️ +139ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -1 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | -1 B |
| Overall change | 3.06 kB | 3.06 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 11.7s | 12.3s | ⚠️ +565ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +234 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2 [...]

2020-01-09 14:55 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 16.2s | 16.1s | -32ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +172 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -1 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | -1 B |
| Overall change | 3.06 kB | 3.06 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 16s | 16.8s | ⚠️ +866ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +172 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB  [...]

2020-01-09 14:56 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.7s | ⚠️ +484ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -1 B |
| withRouter.html gzip | 1.01 kB | 1.01 kB | -1 B |
| Overall change | 3.06 kB | 3.06 kB | -3 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.6s | 14.4s | ⚠️ +778ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip |  [...]

2020-01-09 19:40 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.8s | 14s | ⚠️ +188ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.01 kB | 1.02 kB | ⚠️ +2 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.9s | 14.8s | ⚠️ +875ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2. [...]

2020-01-09 19:42 UTC, timneutkens approved these changes

2020-01-09 19:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong></summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 12.8s | 13.3s | ⚠️ +484ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| withRouter.html gzip | 1.01 kB | 1.02 kB | ⚠️ +2 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -114,13 +114,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -21,7 +21,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      href="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -109,13 +109,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/webpack-a470c2a25bcb4d5a8ec0.js"
+      src="/_next/static/runtime/webpack-4d739ac7b0d8f888ab18.js"
       defer=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/webpack-7928590be3ef2e55b835.module.js"
+      src="/_next/static/runtime/webpack-d629b83a65f3e33fa99e.module.js"
       defer=""
       crossorigin="anonymous"
       type="module"
```
</details>
</details>
<hr/>
<details>
<summary><strong>Serverless Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 13.2s | 13.7s | ⚠️ +492ms |
| nodeModulesSize | 49 MB | 49 MB | ⚠️ +423 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB |  [...]

2020-01-09 20:29 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| buildDuration | 14.1s | 14.9s | ⚠️ +762ms |
| nodeModulesSize | 49 MB | 48.9 MB | -61.8 kB |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.11 kB | 5.11 kB | ✓ |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..9881.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.4 kB | 67.4 kB | ✓ |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.17 kB | 4.17 kB | ✓ |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | ✓ |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | Timer/next.js enable/css | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | ⚠️ +1 B |
| link.html gzip | 1.03 kB | 1.03 kB | ⚠️ +2 B |
| withRouter.html gzip | 1.01 kB | 1.02 kB | ⚠️ +2 B |
| Overall change | 3.06 kB | 3.06 kB | ⚠️ +5 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>_app.js</strong></summary>

```diff
@@ -144,10 +144,6 @@
       exports.AppInitialProps = _utils.AppInitialProps
 
       __webpack_require__('nOHt')
-      /**
-       * `App` component is used for initialize of pages. It allows for overwriting and full control of the `page` initialization.
-       * This allows for keeping state between navigation, custom error handling, injecting additional data.
-       */
 
       function appGetInitialProps(_x) {
         return _appGetInitialProps.apply(this, arguments)
@@ -200,9 +196,6 @@
           _createClass(App, [
             {
               key: 'componentDidCatch',
-              // Kept here for backwards compatibility.
-              // When someone ended App they could call `super.componentDidCatch`.
-              // @deprecated This method is no longer needed. Errors are caught at the top level
               value: function componentDidCatch(error, _errorInfo) {
                 throw error
               },
@@ -235,7 +228,7 @@
       var warnUrl
 
       if (false) {
-      } // @deprecated noop for now until removal
+      }
 
       function Container(p) {
         if (false) {
@@ -244,7 +237,6 @@
       }
 
       function createUrl(router) {
-        // This is to make sure we don't references the router object at call time
         var pathname = router.pathname,
           asPath = router.asPath,
           query = router.query
```
</details>
<details>
<summary>Diff for <strong>_app.module.js</strong></summary>

```diff
@@ -92,10 +92,6 @@
       exports.AppInitialProps = _utils.AppInitialProps
 
       __webpack_require__('nOHt')
-      /**
-       * `App` component is used for initialize of pages. It allows for overwriting and full control of the `page` initialization.
-       * This allows for keeping state between navigation, custom error handling, injecting additional data.
-       */
 
       function appGetInitialProps(_x) {
         return _appGetInitialProps.apply(this, arguments)
@@ -113,9 +109,6 @@
       }
 
       class App extends _react.default.Component {
-        // Kept here for backwards compatibility.
-        // When someone ended App they could call `super.componentDidCatch`.
-        // @deprecated This method is no longer needed. Errors are caught at the top level
         componentDidCatch(error, _errorInfo) {
           throw error
         }
@@ -139,7 +132,7 @@
       var warnUrl
 
       if (false) {
-      } // @deprecated noop for now until removal
+      }
 
       function Container(p) {
         if (false) {
@@ -148,7 +141,6 @@
       }
 
       function createUrl(router) {
-        // This is to make sure we don't references the router object at call time
         var { pathname, asPath, query } = router
         return {
           get query() {
```
</details>
<details>
<summary>Diff for <strong>_error.js</strong></summary>

```diff
@@ -120,9 +120,6 @@
         405: 'Method Not Allowed',
         500: 'Internal Server Error',
       }
-      /**
-       * `Error` component used for handling errors.
-       */
 
       var Error =
         /*#__PURE__*/
```
</details>
<details>
<summary>Diff for <strong>_error.module.js</strong></summary>

```diff
@@ -75,9 +75,6 @@
         405: 'Method Not Allowed',
         500: 'Internal Server Error',
       }
-      /**
-       * `Error` component used for handling errors.
-       */
 
       class Error extends _react.default.Component {
         static getInitialProps(_ref) {
```
</details>
<details>
<summary>Diff for <strong>link.js</strong></summary>

```diff
@@ -491,10 +491,9 @@
       var prefetched = {}
 
       function getObserver() {
-        // Return shared instance of IntersectionObserver if already created
         if (observer) {
           return observer
-        } // Only create shared IntersectionObserver if supported in browser
+        }
 
         if (!IntersectionObserver) {
           return undefined
@@ -568,7 +567,6 @@
             })
 
             _this.linkClicked = function(e) {
-              // @ts-ignore target exists on currentTarget
               var _e$currentTarget = e.currentTarget,
                 nodeName = _e$currentTarget.nodeName,
                 target = _e$currentTarget.target
@@ -581,7 +579,6 @@
                   e.shiftKey ||
                   (e.nativeEvent && e.nativeEvent.which === 2))
               ) {
-                // ignore click for new tab / new window behavior
                 return
               }
 
@@ -593,20 +590,18 @@
                 as = _this$formatUrls.as
 
                [...]

2020-01-09 20:31 UTC, merged

2020-01-16 18:43 UTC, raduchiriac commented
Hello @Timer and thank you for all your work.
Can you explain what this `New CSS Support` actually does?

I am using this package [pigeon-maps](https://github.com/mariusandra/pigeon-maps) and it stopped working after this tag. I think the width of the component is not being set anymore so the maps are not loading