Add assetPrefix when fetching script and style dependencies for granularChunks
vercel/next.js pull request #9933
Opened 2020-01-04 01:34 UTC by bmathews

This continues the work from https://github.com/zeit/next.js/pull/8993, fixing more cases of https://github.com/zeit/next.js/issues/8989

2020-01-04 01:41 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 13.8s | 13.9s | ⚠️ +57ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +88 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.45 kB | 6.45 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.43 kB | 5.43 kB | ⚠️ +6 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.8 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | -3 B |
| link.html gzip | 1.04 kB | 1.04 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| Overall change | 3.12 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1758,7 +1758,11 @@
                             /\.js$/.test(d) &&
                             !document.querySelector('script[src^="' + d + '"]')
                           ) {
-                            _this3.loadScript(d, route, false)
+                            _this3.loadScript(
+                              '' + _this3.assetPrefix + d,
+                              route,
+                              false
+                            )
                           }
 
                           if (
@@ -1767,7 +1771,10 @@
                               'link[rel=stylesheet][href^="' + d + '"]'
                             )
                           ) {
-                            appendLink(d, 'stylesheet')['catch'](function() {
+                            appendLink(
+                              '' + _this3.assetPrefix + d,
+                              'stylesheet'
+                            )['catch'](function() {
                               // FIXME: handle failure
                               // Right now, this is needed to prevent an unhandled rejection.
                             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1299,7 +1299,7 @@
                       /\.js$/.test(d) &&
                       !document.querySelector('script[src^="' + d + '"]')
                     ) {
-                      this.loadScript(d, route, false)
+                      this.loadScript('' + this.assetPrefix + d, route, false)
                     }
 
                     if (
@@ -1308,10 +1308,12 @@
                         'link[rel=stylesheet][href^="' + d + '"]'
                       )
                     ) {
-                      appendLink(d, 'stylesheet').catch(() => {
-                        // FIXME: handle failure
-                        // Right now, this is needed to prevent an unhandled rejection.
-                      })
+                      appendLink('' + this.assetPrefix + d, 'stylesheet').catch(
+                        () => {
+                          // FIXME: handle failure
+                          // Right now, this is needed to prevent an unhandled rejection.
+                        }
+                      )
                     }
                   })
                   this.loadRoute(route)
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-91848b38da8864f33281.js"
+      src="/_next/static/runtime/main-b3308bc79e19d15f79d1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      src="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-91848b38da8864f33281.js"
+      src="/_next/static/runtime/main-b3308bc79e19d15f79d1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      src="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
  [...]

2020-01-04 02:59 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Increase detected ⚠️)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 13.1s | 12.7s | -401ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +130 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.js gzip | 6.45 kB | 6.45 kB | ⚠️ +7 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..6ef5.js gzip | 13.8 kB | 13.8 kB | ✓ |
| framework.HASH.js gzip | 39.5 kB | 39.5 kB | ✓ |
| Overall change | 69.2 kB | 69.2 kB | ⚠️ +7 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 5.43 kB | 5.43 kB | ⚠️ +6 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.6 kB | 12.6 kB | ✓ |
| framework.HA..dule.js gzip | 39.4 kB | 39.4 kB | ✓ |
| Overall change | 63.7 kB | 63.8 kB | ⚠️ +6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.93 kB | 2.93 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.89 kB | 9.89 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.49 kB | 2.49 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.43 kB | 7.43 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 1.04 kB | 1.04 kB | -3 B |
| link.html gzip | 1.04 kB | 1.04 kB | ✓ |
| withRouter.html gzip | 1.03 kB | 1.03 kB | ⚠️ +1 B |
| Overall change | 3.12 kB | 3.11 kB | -2 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1758,7 +1758,11 @@
                             /\.js$/.test(d) &&
                             !document.querySelector('script[src^="' + d + '"]')
                           ) {
-                            _this3.loadScript(d, route, false)
+                            _this3.loadScript(
+                              '' + _this3.assetPrefix + d,
+                              route,
+                              false
+                            )
                           }
 
                           if (
@@ -1767,7 +1771,10 @@
                               'link[rel=stylesheet][href^="' + d + '"]'
                             )
                           ) {
-                            appendLink(d, 'stylesheet')['catch'](function() {
+                            appendLink(
+                              '' + _this3.assetPrefix + d,
+                              'stylesheet'
+                            )['catch'](function() {
                               // FIXME: handle failure
                               // Right now, this is needed to prevent an unhandled rejection.
                             })
```
</details>
<details>
<summary>Diff for <strong>main-HASH.module.js</strong></summary>

```diff
@@ -1299,7 +1299,7 @@
                       /\.js$/.test(d) &&
                       !document.querySelector('script[src^="' + d + '"]')
                     ) {
-                      this.loadScript(d, route, false)
+                      this.loadScript('' + this.assetPrefix + d, route, false)
                     }
 
                     if (
@@ -1308,10 +1308,12 @@
                         'link[rel=stylesheet][href^="' + d + '"]'
                       )
                     ) {
-                      appendLink(d, 'stylesheet').catch(() => {
-                        // FIXME: handle failure
-                        // Right now, this is needed to prevent an unhandled rejection.
-                      })
+                      appendLink('' + this.assetPrefix + d, 'stylesheet').catch(
+                        () => {
+                          // FIXME: handle failure
+                          // Right now, this is needed to prevent an unhandled rejection.
+                        }
+                      )
                     }
                   })
                   this.loadRoute(route)
```
</details>
<details>
<summary>Diff for <strong>index.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-91848b38da8864f33281.js"
+      src="/_next/static/runtime/main-b3308bc79e19d15f79d1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      src="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>link.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -168,13 +168,13 @@
       type="module"
     ></script
     ><script
-      src="/_next/static/runtime/main-91848b38da8864f33281.js"
+      src="/_next/static/runtime/main-b3308bc79e19d15f79d1.js"
       async=""
       crossorigin="anonymous"
       nomodule=""
     ></script
     ><script
-      src="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      src="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       async=""
       crossorigin="anonymous"
       type="module"
```
</details>
<details>
<summary>Diff for <strong>withRouter.html</strong></summary>

```diff
@@ -45,7 +45,7 @@
     />
     <link
       rel="preload"
-      href="/_next/static/runtime/main-01c8e34aedcd31fa5d19.module.js"
+      href="/_next/static/runtime/main-94c907819f37fb1c1773.module.js"
       as="script"
       crossorigin="anonymous"
     />
@@ -163,13 +163,13 @@
       type="module"
   [...]

2020-01-04 11:54 UTC, timneutkens submitted a review, later dismissed
This needs tests, besides that it looks fine 👍

2020-01-04 17:01 UTC, Timer requested changes
This isn't correct. You're adjusting the script asset prefix after checking if it already exists on the DOM, meaning it'll inject this script infinity times.

2020-01-04 17:03 UTC, Timer requested changes
To solve this, please append the assetPrefix in the `getDependencies` function.

Then, in the `prefetch` function, do not append `assetPrefix` if `isDependency` is `true`.

2020-01-04 21:36 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 12.5s | 12.3s | -287ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +74 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.13 kB | 5.13 kB | -4 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..4cf7.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -4 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.19 kB | 4.19 kB | -6 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | -1 B |
| Overall change | 3.07 kB | 3.07 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1286,11 +1286,13 @@
             {
               key: 'getDependencies',
               value: function getDependencies(route) {
+                var _this = this
+
                 return this.promisedBuildManifest.then(function(man) {
                   return (
                     (man[route] &&
                       man[route].map(function(url) {
-                        return '/_next/' + encodeURI(url)
+                        return _this.assetPrefix + '/_next/' + encodeURI(url)
                       })) ||
                     []
                   )
@@ -1308,7 +1310,7 @@
             {
               key: 'loadPageScript',
               value: function loadPageScript(route) {
-                var _this = this
+                var _this2 = this
 
                 route = normalizeRoute(route)
                 return new _promise['default'](function(resolve, reject) {
@@ -1317,9 +1319,9 @@
                       page = _ref.page,
                       mod = _ref.mod
 
-                    _this.pageRegisterEvents.off(route, fire)
+                    _this2.pageRegisterEvents.off(route, fire)
 
-                    delete _this.loadingRoutes[route]
+                    delete _this2.loadingRoutes[route]
 
                     if (error) {
                       reject(error)
@@ -1331,7 +1333,7 @@
                     }
                   } // If there's a cached version of the page, let's use it.
 
-                  var cachedPage = _this.pageCache[route]
+                  var cachedPage = _this2.pageCache[route]
 
                   if (cachedPage) {
                     var error = cachedPage.error,
@@ -1346,7 +1348,7 @@
                     return
                   } // Register a listener to get the page
 
-                  _this.pageRegisterEvents.on(route, fire) // If the page is loading via SSR, we need to wait for it
+                  _this2.pageRegisterEvents.on(route, fire) // If the page is loading via SSR, we need to wait for it
                   // rather downloading it again.
 
                   if (
@@ -1357,17 +1359,17 @@
                     return
                   }
 
-                  if (!_this.loadingRoutes[route]) {
-                    _this.loadingRoutes[route] = true
+                  if (!_this2.loadingRoutes[route]) {
+                    _this2.loadingRoutes[route] = true
 
                     if (true) {
-                      _this.getDependencies(route).then(function(deps) {
+                      _this2.getDependencies(route).then(function(deps) {
                         deps.forEach(function(d) {
                           if (
                             /\.js$/.test(d) &&
                             !document.querySelector('script[src^="' + d + '"]')
                           ) {
-                            _this.loadScript(d, route, false)
+                            _this2.loadScript(d, route, false)
                           }
 
                           if (
@@ -1383,7 +1385,7 @@
                           }
                         })
 
-                        _this.loadRoute(route)
+                        _this2.loadRoute(route)
                       })
                     } else {
                     }
@@ -1408,7 +1410,7 @@
             {
               key: 'loadScript',
               value: function loadScript(url, route, isPage) {
-                var _this2 = this
+                var _this3 = this
 
                 var script = document.createElement('script')
 
@@ -1426,7 +1428,7 @@
                   var error = new Error('Error loading script ' + url)
                   error.code = 'PAGE_LOAD_ERROR'
 
-                  _this2.pageRegisterEvents.emit(route, {
+                  _this3.pageRegisterEvents.emit(route, {
                     error: error,
                   })
                 }
@@ -1437,7 +1439,7 @@
             {
               key: 'registerPage',
               value: function registerPage(route, regFn) {
-                var _this3 = this
+                var _this4 = this
 
                 var register = function register() {
                   try {
@@ -1446,15 +1448,15 @@
                       page: mod['default'] || mod,
                       mod: mod,
                     }
-                    _this3.pageCache[route] = pageData
+                    _this4.pageCache[route] = pageData
 
-                    _this3.pageRegisterEvents.emit(route, pageData)
+                    _this4.pag [...]

2020-01-04 21:43 UTC, bmathews commented
@Timer Corrected. Thanks for the pointer.
@timneutkens Added tests.

2020-01-04 21:47 UTC, ijjk commented
# Stats from current PR

<details>
<summary><strong>Default Server Mode</strong> (Decrease detected ✓)</summary>

<br/>

<details>
<summary><strong>General</strong> Overall increase ⚠️</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| buildDuration | 12.4s | 12.5s | ⚠️ +111ms |
| nodeModulesSize | 48.9 MB | 48.9 MB | ⚠️ +74 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons)</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.js gzip | 5.13 kB | 5.13 kB | -4 B |
| webpack-HASH.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..54d3.js gzip | 4.68 kB | 4.68 kB | ✓ |
| commons.HASH.js gzip | 4.06 kB | 4.06 kB | ✓ |
| de003c3a9d30..4cf7.js gzip | 13.7 kB | 13.7 kB | ✓ |
| framework.HASH.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 67.5 kB | 67.5 kB | -4 B |

</details>

<details>
<summary><strong>Client Bundles (main, webpack, commons) Modern</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| main-HASH.module.js gzip | 4.19 kB | 4.19 kB | -6 B |
| webpack-HASH..dule.js gzip | 746 B | 746 B | ✓ |
| 4952ddcd88e7..dule.js gzip | 5.56 kB | 5.56 kB | ✓ |
| de003c3a9d30..dule.js gzip | 12.5 kB | 12.5 kB | ✓ |
| framework.HA..dule.js gzip | 39.1 kB | 39.1 kB | ✓ |
| Overall change | 62.1 kB | 62.1 kB | -6 B |

</details>

<details>
<summary><strong>Legacy Client Bundles (polyfills)</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| polyfills-HASH.js gzip | 4.76 kB | 4.76 kB | ✓ |
| Overall change | 4.76 kB | 4.76 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.js gzip | 1.33 kB | 1.33 kB | ✓ |
| _error.js gzip | 4.07 kB | 4.07 kB | ✓ |
| hooks.js gzip | 779 B | 779 B | ✓ |
| index.js gzip | 222 B | 222 B | ✓ |
| link.js gzip | 2.9 kB | 2.9 kB | ✓ |
| routerDirect.js gzip | 283 B | 283 B | ✓ |
| withRouter.js gzip | 282 B | 282 B | ✓ |
| Overall change | 9.87 kB | 9.87 kB | ✓ |

</details>

<details>
<summary><strong>Client Pages Modern</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _app.module.js gzip | 757 B | 757 B | ✓ |
| _error.module.js gzip | 3.06 kB | 3.06 kB | ✓ |
| hooks.module.js gzip | 371 B | 371 B | ✓ |
| index.module.js gzip | 212 B | 212 B | ✓ |
| link.module.js gzip | 2.47 kB | 2.47 kB | ✓ |
| routerDirect..dule.js gzip | 273 B | 273 B | ✓ |
| withRouter.m..dule.js gzip | 272 B | 272 B | ✓ |
| Overall change | 7.41 kB | 7.41 kB | ✓ |

</details>

<details>
<summary><strong>Client Build Manifests</strong></summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| _buildManifest.js gzip | 61 B | 61 B | ✓ |
| _buildManife..dule.js gzip | 61 B | 61 B | ✓ |
| Overall change | 122 B | 122 B | ✓ |

</details>

<details>
<summary><strong>Rendered Page Sizes</strong> Overall decrease ✓</summary>

|  | zeit/next.js canary  | bmathews/next.js patch-1 | Change |
| - | - | - | - |
| index.html gzip | 1.02 kB | 1.02 kB | -1 B |
| link.html gzip | 1.03 kB | 1.03 kB | -2 B |
| withRouter.html gzip | 1.02 kB | 1.02 kB | -1 B |
| Overall change | 3.07 kB | 3.07 kB | -4 B |

</details>

#### Diffs
<details>
<summary>Diff for <strong>main-HASH.js</strong></summary>

```diff
@@ -1286,11 +1286,13 @@
             {
               key: 'getDependencies',
               value: function getDependencies(route) {
+                var _this = this
+
                 return this.promisedBuildManifest.then(function(man) {
                   return (
                     (man[route] &&
                       man[route].map(function(url) {
-                        return '/_next/' + encodeURI(url)
+                        return _this.assetPrefix + '/_next/' + encodeURI(url)
                       })) ||
                     []
                   )
@@ -1308,7 +1310,7 @@
             {
               key: 'loadPageScript',
               value: function loadPageScript(route) {
-                var _this = this
+                var _this2 = this
 
                 route = normalizeRoute(route)
                 return new _promise['default'](function(resolve, reject) {
@@ -1317,9 +1319,9 @@
                       page = _ref.page,
                       mod = _ref.mod
 
-                    _this.pageRegisterEvents.off(route, fire)
+                    _this2.pageRegisterEvents.off(route, fire)
 
-                    delete _this.loadingRoutes[route]
+                    delete _this2.loadingRoutes[route]
 
                     if (error) {
                       reject(error)
@@ -1331,7 +1333,7 @@
                     }
                   } // If there's a cached version of the page, let's use it.
 
-                  var cachedPage = _this.pageCache[route]
+                  var cachedPage = _this2.pageCache[route]
 
                   if (cachedPage) {
                     var error = cachedPage.error,
@@ -1346,7 +1348,7 @@
                     return
                   } // Register a listener to get the page
 
-                  _this.pageRegisterEvents.on(route, fire) // If the page is loading via SSR, we need to wait for it
+                  _this2.pageRegisterEvents.on(route, fire) // If the page is loading via SSR, we need to wait for it
                   // rather downloading it again.
 
                   if (
@@ -1357,17 +1359,17 @@
                     return
                   }
 
-                  if (!_this.loadingRoutes[route]) {
-                    _this.loadingRoutes[route] = true
+                  if (!_this2.loadingRoutes[route]) {
+                    _this2.loadingRoutes[route] = true
 
                     if (true) {
-                      _this.getDependencies(route).then(function(deps) {
+                      _this2.getDependencies(route).then(function(deps) {
                         deps.forEach(function(d) {
                           if (
                             /\.js$/.test(d) &&
                             !document.querySelector('script[src^="' + d + '"]')
                           ) {
-                            _this.loadScript(d, route, false)
+                            _this2.loadScript(d, route, false)
                           }
 
                           if (
@@ -1383,7 +1385,7 @@
                           }
                         })
 
-                        _this.loadRoute(route)
+                        _this2.loadRoute(route)
                       })
                     } else {
                     }
@@ -1408,7 +1410,7 @@
             {
               key: 'loadScript',
               value: function loadScript(url, route, isPage) {
-                var _this2 = this
+                var _this3 = this
 
                 var script = document.createElement('script')
 
@@ -1426,7 +1428,7 @@
                   var error = new Error('Error loading script ' + url)
                   error.code = 'PAGE_LOAD_ERROR'
 
-                  _this2.pageRegisterEvents.emit(route, {
+                  _this3.pageRegisterEvents.emit(route, {
                     error: error,
                   })
                 }
@@ -1437,7 +1439,7 @@
             {
               key: 'registerPage',
               value: function registerPage(route, regFn) {
-                var _this3 = this
+                var _this4 = this
 
                 var register = function register() {
                   try {
@@ -1446,15 +1448,15 @@
                       page: mod['default'] || mod,
                       mod: mod,
                     }
-                    _this3.pageCache[route] = pageData
+                    _this4.pageCache[route] = pageData
 
-                    _this3.pageRegisterEvents.emit(route, pageData)
+                    _this4. [...]

2020-01-06 15:55 UTC, Timer approved these changes
LGTM

2020-01-06 15:55 UTC, merged